### ISSUE TITLE
GitHub Explore background is white

### ISSUE THREAD

**Issue by meme** [StylishThemes/GitHub-Dark#1000]
* **Browser**: 
Firefox Nightly
* **Operating System**: 
Arch Linux
* **Link to page with the issue**: 
https://github.com/explore
* **Screenshot**:
![2019-09-16_22-15](https://user-images.githubusercontent.com/18178821/65005895-7be5d300-d8cf-11e9-81cf-1011244bdb9d.png)

**Comment by Mottie** [comment]
Hi @meme!

Thanks for reporting this problem!

@the-j0k3r It seems your commit https://github.com/StylishThemes/GitHub-Dark/commit/0dcec1ff28747e564232cc0c61658c5d35b3a378 was reverted?

**Comment by xt0rted** [comment]
Just fixed this in d1c00527b9ed74b3d3e4307558c06729270068ff.

Some how the change was lost in https://github.com/StylishThemes/GitHub-Dark/commit/341a8e27dd702f9f95cbb5821c1c0664e2b9ba7e#diff-8ee667bab1ff34fa0e7a4c6f479130efL6488.
