### ISSUE TITLE
Enhancement: generator could support $background-image

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#1004]
Adding:

`  "$background-image: linear-gradient(#599bcd,#3072b3)": "linear-gradient(/*[[base-color]]*/ #4f8cc9, /*[[base-color]]*/ #4f8cc9)",` produces no output.

Perhaps this support could be added to generator? Sacrificing a small toad for @silverwind's magic :pray: :wink: 

* **Screenshot**:
![Capture](https://user-images.githubusercontent.com/31389848/65222821-27557a00-dac0-11e9-9a39-329b7f1d46bc.PNG)

**Comment by silverwind** [comment]
`background-image` is covere via `$background`, try that instead.
