### ISSUE TITLE
double border in posts

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#1005]
* **Browser**: FF 69.0
* **Operating System**:  Win 10 pro 1803/1903
* **Link to page with the issue**:  https://github.com/the-j0k3r/GitHub-Community-Dark/pull/2
* **Screenshot**:
![Screenshot_2019-09-25  pull  master from StylishThemes master by pull · Pull Request #2 · the-j0k3r GitHub-Community-Dark](https://user-images.githubusercontent.com/31389848/65588088-31c3b800-df87-11e9-876f-28058e81f14e.png)

default has only one border.

![Screenshot_2019-09-25  pull  master from StylishThemes master by pull · Pull Request #2 · the-j0k3r GitHub-Community-Dark(1)](https://user-images.githubusercontent.com/31389848/65588203-5ddf3900-df87-11e9-9298-8b41e6bf2b46.png)

**Comment by the-j0k3r** [comment]
Visiting the link affected wont show issue cause it was linked, but if you visit a post like "GitHub-Community-Dark/pull/1" at the bottom the double border is visible

**Comment by xt0rted** [comment]
I was looking into this recently and it seemed to be a result of the background image. The line is always there but the top margin of the comment area covers it and hides it, but without a solid background set the line is always visible.

**Comment by the-j0k3r** [comment]
A linear-gradient to transparent or something along those lines might work best in this case. Ill have a look.

Thx

**Comment by the-j0k3r** [comment]
Yep @xt0rted definetly looks better with linear gradient.

```css
.TimelineItem-break {
	background-image: linear-gradient(to bottom, rgba(25, 25, 25, .8) 1%, transparent 80%) !important;
}
```
![generic](https://user-images.githubusercontent.com/31389848/65601541-89235180-dfa2-11e9-9ef9-0b32a00d3055.gif)

The gradient can be tweaked it would be great if we could come up with a better fixed based on that.

With that fix above you dont hide the line completely but the faded look isnt so impressing upon the eyes.
