### ISSUE TITLE
The github-dark.css hasn't changed dark theme 100% in Safari

### ISSUE THREAD

**Issue by danhnguyen30041975** [StylishThemes/GitHub-Dark#1009]
Hi team,

I use MacBook and Safari browser more than Chrome and I found no free extension in Safari for turning Github page into dark theme. So I try a hack for myself is to use existing code at https://github.com/turnoffthelights/Turn-Off-the-Lights-Safari-extension/tree/master/Turn%20Off%20the%20Lights.safariextension and replace the css with github-dark.css on your page. I made many changes in code but it works with very dirty approach :)

However, the github pages aren't in dark completely like in Chrome (see below screenshots). After investigating, it turns out that Safari treats the injected css from extension lower priority than website css ([link here](https://developer.apple.com/documentation/safariservices/safari_app_extensions/about_injected_style_sheets_and_scripts)).

I just want to inform this problem to you, one of the fixing is to set `!important` on css element so that Safari actually overrides the styles from github-dark.css

* **Browser: Safari 12.1**: 
* **Operating System: MacOS 10.14.4**: 
* **Link to page with the issue**:

  - https://github.com/StylishThemes/GitHub-Dark/blob/master/Gruntfile.js
  - https://github.com/StylishThemes/GitHub-Dark/pulls
 
* **Screenshot**:

![Screen Shot 2019-10-06 at 1 32 32 PM](https://user-images.githubusercontent.com/38257704/66265288-3bc6a000-e83e-11e9-8ebb-b112aa5880fe.png)

![Screen Shot 2019-10-06 at 1 32 52 PM](https://user-images.githubusercontent.com/38257704/66265290-3bc6a000-e83e-11e9-8ed6-2afc28862ecb.png)

![Screen Shot 2019-10-06 at 1 34 00 PM](https://user-images.githubusercontent.com/38257704/66265291-3c5f3680-e83e-11e9-9079-5107e8976396.png)

**Comment by Mottie** [comment]
Hi @danhnguyen30041975!

[Tampermonkey](https://www.tampermonkey.net/?ext=dhdg&browser=safari) is free. You can then install [GitHub-Dark Script](https://github.com/StylishThemes/GitHub-Dark-Script) to pull in the css from this repo; but I noticed you use a custom version of GHD, you could modify the userscript to pull in your custom style instead.

**Comment by Mottie** [comment]
And I don't think this is a bug since the style on those pages look fine to me.  Have you created your custom build of GHD with the most recent version?

**Comment by the-j0k3r** [comment]
Also theres cascadea for safari see https://cascadea.app and stop pulling hairs out.

**Comment by Mottie** [comment]
Cascadea isn't free, I think that's why the OP is going through all this extra trouble.

**Comment by the-j0k3r** [comment]
Theres plenty of free (as in free beer) options like Goggle Chrome + Stylus in macOS also and no fussing around necessary especially since its breaking the style.

@danhnguyen30041975 mentions.

> I just want to inform this problem to you, one of the fixing is to set !important on css element so that Safari actually overrides the styles from github-dark.css

IDK what this means exactly, if its use of !important in rules that start with `/* auto-generated rule for` this is unlikely to happen since the rules are generated to match the use of `!important` in default stylesheets.

Seems like a lot of fussing around in any case, there are ways to get this done without.

**Comment by mxdanger** [comment]
@danhnguyen30041975 Just wondering, why do you want a dark theme for GitHub when your computer is set to light mode?

**Comment by the-j0k3r** [comment]
Ill be closing this for lack of feedback from OP, its an external issue in any case.

macOS users that insist on sticking to safari can use Cascadea for macOS/Safari and pay the fee cost for Cascadea.

For free (as in free beer) you can alternatively install Firefox or Google chrome with Stylus installed which is the recommended fool proof method.

If there's further information provided  or a need to reopen this issue, please just ping me.

Thanks for understanding.
