### ISSUE TITLE
Automated changelog on releases

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#1011]
**Describe the change you'd like**

* An automated changelog
* Automated changelog additions to

**Additional context**

Would like to create a script that picks up the latest entries since last release and adds them to a changelog.md and appends to the tag message when bumping via ver.

Work so far and would appreciate help pls.

```sh
#!/bin/bash

## TODO:
#  * Call ver for version bumping and tagging with respective changelog entries.
#  * Check for and only append entries since last release to tags and changelog.md

version=$( git describe --tags --always )
tag=$( git describe --tags --always --abbrev=0 )

  if [ "$version" = "$tag" ];
    then # on a tag
      current="$tag"
      previous=$( git describe --tags --abbrev=0 HEAD~ )
    else
      current=$( git log -1 --format="%H" )
      previous="$tag"
  fi

file="CHANGELOG.md"
date=$( git log -1 --date=short --format="%ad" )
url=$( git remote get-url origin | sed -e 's/^git@\(.*\):/https:\/\/\1\//' -e 's/\.git$//' )
title='# '${url##*/}

  if [ ! -e  "$file" ];
    then
      echo -ne "$title\n\n## [${version}](${url}/tree/${current}) ($date)\n\n[Full Changelog](${url}/compare/${previous}...${current})\n\n" > "${file}"
      git shortlog --no-merges --reverse "$previous..$current" | sed -e  '/^\w/G' -e 's/^      /- /' >> "${file}"
    else
      echo -ne "$title\n\n## [${version}](${url}/tree/${current}) ($date)\n\n[Full Changelog](${url}/compare/${previous}...${current})\n\n" >> "${file}"
      git shortlog --no-merges --reverse "$previous..$current" | sed -e  '/^\w/G' -e 's/^      /- /' >> "${file}"
  fi

```

That outputs things in this format below*, 
 * a great deal needs tweaking in script still.

---
# GitHub-Dark

## [v1.22.97-16-g0568d637](https://github.com/StylishThemes/GitHub-Dark/tree/0568d6373284f132907bd87a671368c56ac8ef05) (2019-09-27)

[Full Changelog](https://github.com/StylishThemes/GitHub-Dark/compare/v1.22.97...0568d6373284f132907bd87a671368c56ac8ef05)

Brian Surowiec (1):

- Remove border from .blankslate

Rob Garrison (2):

- 1.22.98
- ZenHub: Add block banner styling

Roman Reiss (8):

- 1.22.102
- automated regeneration
- 1.22.101
- automated regeneration
- 1.22.100
- automated regeneration
- 1.22.99
- automated regeneration

the-j0k3r (5):

- consolidate selector
- fix explore page comments gradient
- fix https://github.com/features/security page
- fix double border closes #1005
- themes: lowercase hex colors

**Comment by silverwind** [comment]
You should be able to specifiy multiple `-m` (One per paragraph) to `ver` now. I think GitHub renders those tag messages a pure ASCII only, so there's no Markdown available there.

I don't think we really need a changelog file if it only consists of git history, but feel free to add something to do those release tag messages.

**Comment by the-j0k3r** [comment]
> but feel free to add something to do those release tag messages.

Thanks for reply, nice to read you btw =)

This should be automated hence the point here (I though if I started this way I could get some clews on how to get there), off the top of my head not sure how to get around that at this time. Ideas appreciated, though eventually I hope to get it done either way.

Famous last words.

**Comment by silverwind** [comment]
Maybe I'll add a `--changelog` option to `ver` to create such a log, seems like a reasonable option to have.

**Comment by silverwind** [comment]
https://github.com/silverwind/ver/issues/11

**Comment by the-j0k3r** [comment]
wow.

**Comment by silverwind** [comment]
Fixed as of https://github.com/StylishThemes/GitHub-Dark/commit/c9d19969c6933c58460e896c68382ba7287d94ba.

**Comment by the-j0k3r** [comment]
Fantastic, great news. Thx for this, I think it will be helpful indeed. Especially with semi sane commit messages.
