### ISSUE TITLE
Failed to install usercss with Stylus on Firefox Dev Edition on Windows 10

### ISSUE THREAD

**Issue by z0rc** [StylishThemes/GitHub-Dark#1013]
* **Browser**: Firefox Dev Edition 70.0b13
* **Operating System**: Windows 10 Pro (1903)
* **Link to page with the issue**: Not applicable
* **Screenshot**:
![image](https://user-images.githubusercontent.com/787519/66519523-25e00600-eaf0-11e9-96e7-880d2f436e9f.png)

Other styles I tested install just fine on this system. Also I tested installation on the same Firefox version running on Kubuntu 19.04 and Macos, Firefox configuration synced and same addons installed, usercss installs just fine. Also tested installation on Chrome on the same Windows machine, successful. So it's combination of Firefox, Windows and Stylus that fail to install this usercss.

Also opened https://github.com/openstyles/stylus/issues/788 as it isn't clear whether it's usercss of Stylus issue.

**Comment by the-j0k3r** [comment]
@z0rc Thanks for reporting this to us.

just in case can you try installing via https://github.com/StylishThemes/GitHub-Dark/raw/master/github-dark.user.css and let us know of the result?

Thanks

**Comment by the-j0k3r** [comment]
I can confirm that in Firefox Developer Edition installing via 


https://stylishthemes.github.io/GitHub-Dark/github-dark.user.css

**Comment by z0rc** [comment]
Sorry for delay, had to confirm couple of things on my side.

Indeed, with clean profile the issue is gone. I went ahead a did "refresh" of Firefox profile, installed script successfully. Unfortunately with this done it isn't possible to confirm what caused the issue in the first place. Sorry for trouble, and thanks for the help.

**Comment by the-j0k3r** [comment]
Thanks for the feedback in any case. closing this then =)
