### ISSUE TITLE
Unable to create a new release

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#1016]
I'm not sure what may of caused this, but I'm unable to create releases now. The `npx grunt patch` task is completing successfully, but it seems to be exiting at different stages because sometimes the usercss file is created, other times the usercss is created & version numbers are patched, but it never commits the changes. I'm running this through powershell core on win10. I didn't try with bash/wsl because git's not setup on there right now.

**Comment by silverwind** [comment]
Probably https://github.com/silverwind/ver/issues/12. I'm pretty sure it's related to the multiline strings that `ver` passes to git when on Windows. I should have a fix ready soon, meanwhile, a automatic release happened.

**Comment by silverwind** [comment]
Should be fixed, try reinstalling dependencies and do a release.

**Comment by the-j0k3r** [comment]
Its not fixed but I think this is nodejs/npm issue best track https://github.com/silverwind/ver/issues/12

closing but if you need it open here reopen or make some noise.
