### ISSUE TITLE
Issue template editor needs better header styling

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#1020]
I'm not really sure how to fix this one. The selectors are too generic, and there's margins on the tabs and main content area that allow the background image to show through.

* **Browser**: chrome 78
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/issues/templates/edit
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/67906105-eaae8100-fb49-11e9-8310-dee3dd57416b.png)

**Comment by Mottie** [comment]
The pagehead across the top has a slightly darker background and a bottom border

<img width="515" alt="2019-10-30 19_26_06-Issue template editor needs better header styling · Issue #1020 · StylishThemes_" src="https://user-images.githubusercontent.com/136959/67908916-47f70200-fb4b-11e9-84da-4ba0ee469ffc.png">

For the tab, GitHub makes the background of the active tab white with a transparent bottom border so it overlays and hides the horizontal line and matches the content body so it looks continuous

<img width="530" alt="2019-10-30 19_20_00-Issue template editor needs better header styling · Issue #1020 · StylishThemes_" src="https://user-images.githubusercontent.com/136959/67908700-79230280-fb4a-11e9-949c-2a60461fe7fe.png">

So, I don't think it's possible to make the active tab match the content body unless a solid background color is used. No background image.

**Comment by the-j0k3r** [comment]
I cant navigate to https://github.com/StylishThemes/GitHub-Dark/issues/templates/edit and have a tab selected because I cant access the GitHub Dark settings.

I resolve this by doing this.

```
.repository-content .bg-white {
    background-color: transparent !important;
    background-image: none !important;
  }
```

and thats it.

**Comment by the-j0k3r** [comment]
Re: second issue with button focus see https://github.com/StylishThemes/GitHub-Dark/commit/6a5e50673ad72c6696181eb09534ad38cdd3e863

**Comment by Mottie** [comment]
Sorry, long day yesterday. I misunderstood the question in the issue 😿

**Comment by the-j0k3r** [comment]
Figured as much, diapers and B plugs testing is a demanding job

**Comment by the-j0k3r** [comment]
I added the bg-white as above to style in https://github.com/StylishThemes/GitHub-Dark/commit/07d60705378e4a2808d8a62de5695756c48060d4

Before:

![Capture](https://user-images.githubusercontent.com/31389848/67925607-27af5d80-fbb4-11e9-9757-24732fa1df9e.PNG)

After

![Capture](https://user-images.githubusercontent.com/31389848/67923295-b7054280-fbad-11e9-8f01-2a02dc70b1b8.PNG)

Im leaving this open because:

1) Some tab margin issue which I cant see or duplicate
2) the `.repository-content .bg-white` addition may affect other areas, so this can be tracked here.

@xt0rted update to v1.22.130 and let me know what gives.

**Comment by the-j0k3r** [comment]
ping @xt0rted

**Comment by xt0rted** [comment]
Looks a little weird with a background image (tab has a background color but nothing else around it does), but if you don't use a background image then it looks fine. Seems fixed to me since we don't really want to mess with margins & padding to try and fill that whole area.

**Comment by the-j0k3r** [comment]
All the tabs have a solid background everywhere, this has been discussed once already somewhere if memory serves me right.

this page tabs

![Capture](https://user-images.githubusercontent.com/31389848/68526331-ee28d180-02da-11ea-9aac-dd955f19a157.PNG)

actions tabs
 
![Capture](https://user-images.githubusercontent.com/31389848/67938639-2e4bce00-fbd0-11e9-84c7-a4032faf1bcf.PNG)

LGTM

**Comment by Mottie** [comment]
> this has been discussed once already somewheres if memory serves me right.

That was the first comment I made. I marked it as off-topic, but I guess it's not anymore 😸

**Comment by the-j0k3r** [comment]
Nope, I was a bit lost at first with that comment, but I assumed that all tabs having a solid bg is desired since all of them have it so doesn't make sense to have different styling, just here.

I still cant see any padding/margin issues though.

Comment was restored.
