### ISSUE TITLE
Actions runs background + search bar need better styling

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#1025]
* **Browser**:  FF 73.0.1
* **Operating System**:  Win 10
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/commit/98f96ae4937e455e5f005fce18b1a6160a7120b9/checks?check_suite_id=296546644
* **Screenshot**:
![generic](https://user-images.githubusercontent.com/31389848/68215271-3d22ee00-ffdf-11e9-942c-21ab12674423.gif)

Essentially the background `.bg-gray-dark` is `#181818` autogen, then the search input bar when focus is same color, theres not a sausage of contrast at all.

I suggest making search bar focus the same as it is when not focus or something lighter than `#181818` all other search bars just seem to brighten the text on focus, the bg color stays the same.

**Comment by xt0rted** [comment]
When custom styling actions elements we should keep those rules grouped together for now so we can more easily remove the old ones. This UI is only on github.com and still in preview so the styles keep changing every few days. There's also been a different UI that's being turned on and off over the last few weeks so there's even more changes to come by the time [GitHub Universe](https://githubuniverse.com/) rolls around (that's when actions comes out of beta).

**Comment by the-j0k3r** [comment]
Well it would be easier if this were in its own section. Failing that, how to keep track of all autogen stuff and all manual additions is a bit hard.

**Comment by xt0rted** [comment]
Most of the stuff I've been adding is grouped together here https://github.com/StylishThemes/GitHub-Dark/blob/b0eea172aadf37a61c5f8bf6496a462b9162ff82/github-dark.css#L8682-L8702
