### ISSUE TITLE
Make this theme officially supported by GitHub

### ISSUE THREAD

**Issue by saschagrunert** [StylishThemes/GitHub-Dark#1026]
**Describe the change you'd like**

I would like to have this theme as an official style supported by GitHub. The idea is to select the dark mode based on time or general preference.

**Additional context**

Your work is amazing! This theme is the major driver behind css plugins like stylus (at least from my perspective), so I'd like to ask if there are any considerations from @github to bring this theme into their official "dark mode support", which does not exist yet.

What do you think?

**Comment by the-j0k3r** [comment]
I think and speaking for myself only, that your share is a nice sentiment, and more importantly to know my contributions enhance my own and other GHD users experience to the point of getting fellow users recognition for the project, this is more important than official recognition in my mind.

Speaking of official recognition/acceptance though, it is not anywhere in any of my thoughts when I make a push.fix a bug or make a release, etc to this repo, its not a motivator at all.

Thanks for the :heart: and share.

:wink:

**Comment by the-j0k3r** [comment]
This would never happen in any case. Best chance to get an default dark style for GitHub is to contribute directly to primer, As for official recognition while just speaking for myself in this matter, its not a factor in the bigger scheme of things.

What we need is more time in a day or more hands on deck.
