### ISSUE TITLE
Suddenly appears to be crashing Chrome tab

### ISSUE THREAD

**Issue by nickforddesign** [StylishThemes/GitHub-Dark#1027]
* **Browser**: Chrome Version 77.0.3865.90 (Official Build) (64-bit)
* **Operating System**: MacOS Mojave
* **Link to page with the issue**: github.com/*
* **Screenshot**: n/a

For some reason, just starting today, some core http requests just hang while loading any GH link with the scripts turned on. If I disable GH dark script, pages load immediately without issue. If I turn it back on, it hangs and then Chrome alerts with "The tab is not responding, do you want to kill it"...

**Comment by Mottie** [comment]
Please see https://github.com/StylishThemes/GitHub-Dark-Script/issues/72#issuecomment-551109600
