### ISSUE TITLE
Approved changes timeline icon has a green border when it shouldn't

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#1028]
The issue is coming from this rule: https://github.com/StylishThemes/GitHub-Dark/blob/f965162e9cf6a10ba65b0ebf39c07e1cb72d7cf4/github-dark.css#L7950-L7963

I was going to remove the `.bg-green` selector from this (line 7959) but wasn't sure if there was a good reason for it being there since it shows up in the auto generated section. This seems to be an artifact from a year or more ago and so far I haven't seen a spot that was broken by removing it.

* **Browser**: chrome 78
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/desktop/desktop/pull/8542#pullrequestreview-308188789
* **Screenshot**:
![image](https://user-images.githubusercontent.com/831974/68460658-68bbf900-01d6-11ea-9518-210bba2f0a41.png)

**Comment by the-j0k3r** [comment]
Yep remove it.

**Comment by xt0rted** [comment]
I removed this yesterday in 2e84d50cc98b9208acc8bb5cde62cda99b1a8e6c but forgot to close the issue 🤯
