### ISSUE TITLE
CSS issue

### ISSUE THREAD

**Issue by pradeepb6** [StylishThemes/GitHub-Dark#1029]
* **Chrome**: 
* **MacOS**: 
* **Screenshot**:
 
![image](https://user-images.githubusercontent.com/6407736/68753287-09f6e500-0605-11ea-9842-7bec27268259.png)

* **Description**:

I installed the plugin today and found a css issue (background color for the buttons) when I opened a PR in my repository. I believe that it should be fixed using below css
```
.bg-gray-light {
    background-color: rgb(51, 56, 66) !important;
}
``` 
instead of 
```
.bg-gray-light {
    background-color: rgb(27, 29, 35) !important;
}
``` 

But I was not able to figure out where should I make the change and create PR as a fix. 

I was able to find the class only in the file `github-dark.user.css`. Any suggestion or fix for this would be awesome :)

**Comment by the-j0k3r** [comment]
Hello.

Please look at https://github.com/StylishThemes/GitHub-Dark/blob/master/.github/CONTRIBUTING.md

If in doubt, dont edit any rules that start with /* autogenerated  etc etc or the user.css file thats autogenerated style also... Edit the github-dark.css

However I can repro this issue, I dont understand the screenshot either, there is no prettier buttons in out style.
Are you sure you arent using some 3rd party Github extension? if so disable it and retest.

Thanks.

**Comment by pradeepb6** [comment]
Hi,

Prettier is another plugin from Prettier. Issue still persists even after disabling it. I will look into how can I fix it and create a PR. Thank you :)

**Comment by the-j0k3r** [comment]
Can you please paste a link to affected page and make sure you are using the latest GitHub Dark version [click here](https://github.com/StylishThemes/GitHub-Dark/raw/master/github-dark.user.css)

also our buttons dont look like that, so its something likely in your config or interference from another plugin.

Are you using stylus?

this is how our style looks

![Screenshot_2019-11-13 Replace some grunt scripts by the-j0k3r · Pull Request #1019 · StylishThemes GitHub-Dark](https://user-images.githubusercontent.com/31389848/68755058-3a8c4e00-0608-11ea-9777-3e9005403c88.png)

**Comment by pradeepb6** [comment]
I tried disabling all plugins as well as dark mode in MacOS. Nothing changed. And unfortunately, I was not able to inject the CSS into the page as chrome did not allow. Getting some violation error :-|

**Comment by the-j0k3r** [comment]
You are going to need to be more specific than that.

Are you using stylus?
Where exactly are you getting this violation error?

## Describe the steps that lead you to this error

Please provide screenshot of https://github.com/StylishThemes/GitHub-Dark/pull/1019 for comarison with above.

**Comment by pradeepb6** [comment]
Ok you are right. My stupidity. Sorry for wasting your time. I was confused with chrome plugin name with this repository name. Install Stylus now. all looks good. Once again sorry. :-|

**Comment by the-j0k3r** [comment]
No problem, I definitely found it strange, but am glad you solved it.

Have a nice day.
