### ISSUE TITLE
Code previews for repos do not indicate its private status

### ISSUE THREAD

**Issue by haykam821** [StylishThemes/GitHub-Dark#1030]
Normally, previews of code from a private repository show with a yellow accent in search results. However, with GitHub Dark, this does not happen.

* **Browser**: Chromium 78
* **Operating System**: macOS Mojave
* **Link to page with the issue**: https://github.com/search?q=private+repo&type=Code
* **Screenshot**: The following is code from a private repository in both GitHub Dark and GitHub Dark-less environments: ![Code preview for private repo (with GitHub Dark)](https://user-images.githubusercontent.com/24855774/68782586-a4582800-0607-11ea-9bd9-2b4df3d1e296.png) 
![Code preview for private repo (without GitHub Dark)](https://user-images.githubusercontent.com/24855774/68782743-dbc6d480-0607-11ea-8440-33dff0f969f1.png)

**Comment by the-j0k3r** [comment]
This is intentional, its still highlighted but hard to see

@xt0rted added this, I would prefer more contrast also.

**Comment by haykam821** [comment]
@the-j0k3r I don't see any styling that affects the relevant `code-list-item-private` class here.

**Comment by the-j0k3r** [comment]
Oh I misunderstood. Yea Ill look into it when I have time. Just taken with other projects also, so bare with us.

**Comment by haykam821** [comment]
@the-j0k3r  I've clarified the link so it shows the 'code' tab. Those previews have a yellow tint.

**Comment by xt0rted** [comment]
I'm working on a fix for this.

**Comment by xt0rted** [comment]
| Before | After |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/831974/68824236-25450d00-0664-11ea-8ade-f9b452309e64.png) | ![image](https://user-images.githubusercontent.com/831974/68824249-38f07380-0664-11ea-8119-e1bf67124fed.png) |

Regarding the highlighted text, I've been playing around with using the highlight color from my syntax theme. I use Monokai which uses `#a6e22e` and looks like this:

![image](https://user-images.githubusercontent.com/831974/68824661-9afda880-0665-11ea-9372-919dce672136.png)

I'm not sure what this is like with the other themes, but it could be an option to make this a bit easier to see.
