### ISSUE TITLE
Pause Dark-mode Toggle

### ISSUE THREAD

**Issue by MylesWardell** [StylishThemes/GitHub-Dark#1033]
Instead of removing the web-page from white-list I would love a toggle button that would toggle the dark theme.

**Comment by Mottie** [comment]
Our style adds CSS to the website, we don't control whether the style is enabled, disabled or white-listed. If you're using Stylus, open the popup and click the style there, or use the keyboard shortcut.

**Comment by silverwind** [comment]
Yeah, CSS cannot toggle itself unfortunately, it has to be done via your userstyle manager.

**Comment by UncleGoogle** [comment]
Excuse me for my ignorance, but isn't it released as standalone [chrome extension](https://chrome.google.com/webstore/detail/github-dark-theme/odkdlljoangmamjilkamahebpkgpeacp) with a [GUI](https://i.gyazo.com/afeb20ec92cb29e05f184ba1f14fd81b.png)?

If it's still impossible, does anyone know a way to toggle it/ any extension on shedule? It is so common to use dark mode at night only...

**Comment by the-j0k3r** [comment]
@UncleGoogle hello and welcome.

>Excuse me for my ignorance, but isn't it released as standalone chrome extension with a GUI?

No, this is a style/theme for Stylus, and is [to be installed as documented here](https://github.com/StylishThemes/GitHub-Dark#installation)

Those chrome extension styles are 100% unrelated to this project.

Hope that clears that up.

If you have any further questions feel free to open a new question issue. =)

**Comment by UncleGoogle** [comment]
@the-j0k3r thanks for clarification and sorry for unrelated question!

**Comment by the-j0k3r** [comment]
No problem. =)
