### ISSUE TITLE
[REQUEST] Stylus+GreaseMonkey surrogate option?

### ISSUE THREAD

**Issue by ImportTaste** [StylishThemes/GitHub-Dark#1036]
Not only is the GreaseMonkey script not as snappy at applying CSS as Stylus, it also doesn't really make the CSS persist from page to page, so you'll get brief flashes of the normal web design, which is a lot like getting flashbanged every time you click on a page. But of course, Stylus lacks fancier options that can only be implemented through javascript injection.

A 'best of both worlds' option, with the only caveat being that a user needs to have both a GreaseMonkey and Stylish extension, would be quite nice.

**Comment by silverwind** [comment]
It's certainly possible to have some interaction via CSS variables, so the userstyle could define variables which are subsequently overwritten via JS, but I'm not sure if anyone is really motivated to do all that. Stylus with the option interface is usually "good enough".

**Comment by the-j0k3r** [comment]
>  with the only caveat being that a user needs to have both a GreaseMonkey and Stylish extension, would be quite nice.

You can also have https://github.com/StylishThemes/GitHub-Dark-Script it has a couple of unfixed bugs but other than that it works,maybe this is more a request for that part.

**Comment by silverwind** [comment]
Yeah, it would be quite a unholy setup indeed. I don't think we should do this.

**Comment by ImportTaste** [comment]
_Satan frowns._
