### ISSUE TITLE
Unable to select text when viewing a file

### ISSUE THREAD

**Issue by stijnherreman** [StylishThemes/GitHub-Dark#1039]
With this style enabled, selecting text is not possible, as if mouse interaction is blocked. With the style disabled, selecting text is possible. I'm using GitHub Dark v1.22.149

* **Browser**: Firefox 70.0.1 (64-bit)
* **Operating System**: Windows 10 (1903)
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/blob/master/.gitignore

1. Enable the style and try to select text, this does not work:
![image](https://user-images.githubusercontent.com/1618054/69730308-152f3200-1128-11ea-93b3-360c1a888012.png)

2. Disable the style and try to select text, this works:
![image](https://user-images.githubusercontent.com/1618054/69730375-37c14b00-1128-11ea-97a9-60692963b953.png)

3. Enable the style and try to deselect text or select other text, this does not work:
![image](https://user-images.githubusercontent.com/1618054/69730428-558eb000-1128-11ea-87ed-0faf4e31f5bb.png)

**Comment by silverwind** [comment]
Fixed in https://github.com/StylishThemes/GitHub-Dark/commit/0b8967b98ed168bd3d4d7e3ddc7515f886f5b4bf.
