### ISSUE TITLE
Author & Member labels in PR code comments appear hidden due to style

### ISSUE THREAD

**Issue by poly2d** [StylishThemes/GitHub-Dark#1040]
* **Browser**:  Chrome 78.0.3904.108
* **Operating System**: macOS 10.15.1 
* **Link to page with the issue**: 
Example: https://github.com/StylishThemes/GitHub-Dark/pull/1015/files  
* **Screenshot**:

<img width="580" alt="Screen Shot 2019-11-27 at 4 11 20 PM" src="https://user-images.githubusercontent.com/43548622/69767432-16189180-1131-11ea-9284-f280d1320fa8.png">

<img width="580" alt="Screen Shot 2019-11-27 at 4 11 15 PM" src="https://user-images.githubusercontent.com/43548622/69767435-1a44af00-1131-11ea-8856-dc84ec98afe7.png">

<img width="441" alt="Screen Shot 2019-11-27 at 4 19 06 PM" src="https://user-images.githubusercontent.com/43548622/69767922-50832e00-1133-11ea-9b3d-b6d6bcb96b05.png">

**Comment by the-j0k3r** [comment]
I think that youre using some other style [or probably some standalone chrome theme](https://chrome.google.com/webstore/detail/github-dark-theme/odkdlljoangmamjilkamahebpkgpeacp) that does this and it has nothing todo with our GitHub Dark style here is how it looks for me.

![Screenshot_2019-11-28  Replace some grunt scripts by the-j0k3r · Pull Request #1015 · StylishThemes GitHub-Dark](https://user-images.githubusercontent.com/31389848/69778252-e787ce80-11a3-11ea-965e-720d657cf671.png)

If you want to use our style, see https://github.com/StylishThemes/GitHub-Dark#installation

**Comment by silverwind** [comment]
Yeah, something else seems to interfere. I wonder what it is.

**Comment by the-j0k3r** [comment]
It wouldn't be the first chrome user to install these addons from goggle store that are named Github Dark, thats what it looks like.

**Comment by poly2d** [comment]
I am so sorry, you are right @the-j0k3r 
I was trying out different themes and mixed them up. 
Thanks for taking a look!

**Comment by the-j0k3r** [comment]
@poly2d Use our style, its much better =)

https://github.com/StylishThemes/GitHub-Dark#installation
