### ISSUE TITLE
Issue Followup Post Increasing Textbox Doesn't Move Footer Down

### ISSUE THREAD

**Issue by FrankHu-MSFT** [StylishThemes/GitHub-Dark#1042]
* **Browser**: Brave
* **Operating System**: Windows 10
* **Link to page with the issue**: Any New Issue 
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/6366013/71200169-6e344680-224c-11ea-880a-2200a7edd283.png)

For some reason when you enter text, it doesn't move the bottom footer SOMETIMES. I haven't been able to pinpoint when/why this happens. But this only happens sometimes.

**Comment by FrankHu-MSFT** [comment]
I have a chrome extension that runs a content script and injects JavaScript into the GitHub page which might be the issue. If anyone else is experiencing this, I'd love to know.

**Comment by the-j0k3r** [comment]
@FrankHu-MSFT Try without any other extensions, I also see your screenshot has other icons like the upload icon and its not available per default or with GitHub Dark style, so definitely try without any extensions that modify GitHub, preferably try only with Stylus and GHD.

**Comment by silverwind** [comment]
Very likely not caused by GHD. We only rarely do layout changes that would cause bugs like that.

**Comment by the-j0k3r** [comment]
@FrankHu-MSFT ping.

**Comment by FrankHu-MSFT** [comment]
hey sorry i guess this hasn't happened recently. I'm not sure what could have caused this. very odd must have been one of my extensions or something... 

Thanks for engaging quickly i'll go ahead and close this out.
