### ISSUE TITLE
border color is different between upper and lower

### ISSUE THREAD

**Issue by su8ru** [StylishThemes/GitHub-Dark#1045]
* **Browser**: Google Chrome 79
* **Operating System**: Windows 10
* **Link to page with the issue**: ex)https://github.com/su8ru (not only me but also everyone)
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/33474143/71766751-a32be300-2f46-11ea-9ba6-f719a4bb4a54.png)

upper is `#727272`, but lower is `#525252`.

**Comment by the-j0k3r** [comment]
upper is `#484848` and is coming from https://github.com/StylishThemes/GitHub-Dark/blob/ab31d603b3d28d9c3161a2748fd1b0a5f64587fe/github-dark.css#L6260 which set img to `#484848` border while bottom is autogenerated at `#343434`

easy fix, thx.
