### ISSUE TITLE
`diff` language is not styled

### ISSUE THREAD

**Issue by digama0** [StylishThemes/GitHub-Dark#1046]
This is using the default "GitHub Dark" theme.

* **Browser**: Firefox
* **Operating System**: Ubuntu
* **Link to page with the issue**:
```diff
  foo
+ bar
- baz
```
* **Screenshot**: 
![github](https://user-images.githubusercontent.com/868588/71784521-6f8e9e80-2fc2-11ea-96d9-1401a6e6fdef.png)

The HTML uses the `pl-md` and `pl-mi1` classes:
```html
<div class="highlight highlight-source-diff">
<pre>  foo
<span class="pl-mi1"><span class="pl-mi1">+</span> bar</span>
<span class="pl-md"><span class="pl-md">-</span> baz</span></pre>
</div>
```

which have very light backgrounds [github-dark.css#L81-L96](https://github.com/StylishThemes/GitHub-Dark/blob/master/themes/src/github/github-dark.css#L81-L96), along with two other themes for changed and ignored that I don't know how to trigger. I'm not a designer though, so I won't suggest a replacement color.

**Comment by the-j0k3r** [comment]
Thanks for report,  this its fixed, pls update to 1.22.182!
