### ISSUE TITLE
White area around reaction avatars in Refined GitHub

### ISSUE THREAD

**Issue by DuBistKomisch** [StylishThemes/GitHub-Dark#1047]
* **Browser**: Firefox Developer Edition 72.0b11 (64-bit)
* **Operating System**: Arch Linux
* **Link to page with the issue**: Anything really, for example https://github.com/apache/cordova-plugin-inappbrowser/pull/584#issuecomment-560321948.
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/703055/71789778-3b2de780-3081-11ea-8dc1-07c55ac91d86.png)

If I untick this particular `box-shadow` rule:

![image](https://user-images.githubusercontent.com/703055/71789801-53056b80-3081-11ea-98c3-9e3ef4dcdd89.png)

It removes it:

![image](https://user-images.githubusercontent.com/703055/71789819-5f89c400-3081-11ea-9b3a-6fe75a327037.png)

So perhaps just needs to be replaced with an appropriate GitHub-Dark colour instead of almost white.

**Comment by the-j0k3r** [comment]
Ive added the `background #efefef` to generator, however the box shadow has no effect on generator and had to be added manually.

I dont think anyone here uses Refined GitHub, I dont,  and the resulting fixes for this also affect other areas that may cause undesired styling to picked up elements by generator.

@silverwind
