### ISSUE TITLE
Border issues on image diff

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#1054]
https://github.com/go-gitea/gitea/pull/10065/files?short_path=e00f11d#diff-e00f11db70883b51bc33243dc5d0b9d5

<img width="287" alt="image" src="https://user-images.githubusercontent.com/115237/73428945-bc079880-433a-11ea-8761-83568695fdd6.png">

<img width="276" alt="image" src="https://user-images.githubusercontent.com/115237/73428962-c32ea680-433a-11ea-9885-3de041a66cca.png">

Seems there are a bunch of unneccesary dark borders inside the green one added by us, need to remove them so the insides of this example are white.

**Comment by the-j0k3r** [comment]
Im not sure if the borders are the issue. This is however.

https://github.com/StylishThemes/GitHub-Dark/blob/cc878562aca1a7e3442ab7541da4403c30744636/github-dark.css#L8621-L8624

![generic](https://user-images.githubusercontent.com/31389848/73430213-c5463480-433d-11ea-9552-4c4a0cdb7c8e.gif)

**Comment by silverwind** [comment]
That border is not the issue, that's just wrong semi-transparent pixels on the "Before" image.

**Comment by the-j0k3r** [comment]
I cant see the issue you mentioned without serious zooming, the other is obvious.

**Comment by silverwind** [comment]
The bottom-border issue is fixed. The ~1px border around the image is in GH's style to and while I would prefer to remove it, it seems impossible in CSS because both parent and child element have absolute dimension. The only solution is to stretch the child to 100% but then all images would render 2px bigger than they are.

**Comment by the-j0k3r** [comment]
Yea, what about https://github.com/StylishThemes/GitHub-Dark/issues/1054#issuecomment-580126911 thats really looks ugly.

**Comment by silverwind** [comment]
I much prefer the dark bg we currently have.

**Comment by the-j0k3r** [comment]
There has to be a way to fix this without adding jagged dark edges to files.

**Comment by silverwind** [comment]
As I said, the jagged edges are the image's fault, not ours. It was a result of a improper imagemagick conversion that left semi-transparent pixels around the logo.
