### ISSUE TITLE
PR Toolbar shadow does not stick to top and obstructs view

### ISSUE THREAD

**Issue by KnutZuidema** [StylishThemes/GitHub-Dark#1056]
* **Browser**: Firefox 72
* **Operating System**: 5.4.15-arch1-1
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/pull/959/files
* **Screenshot**:
![image](https://user-images.githubusercontent.com/28651746/74030394-3f666100-49af-11ea-9d4b-b9e1d31f82af.png)

the toolbar shadow somehow does not stick to the top of the page

**Comment by the-j0k3r** [comment]
@KnutZuidema Thanks for this report.

Please ensure you have no other styles for GitHub Interfering here. As is I cant see this issue,
Also make sure you have the latest GitHub Dark v1.22.203 installed,

![Screenshot_2020-02-07 Codemirror tabs by Mottie · Pull Request #959 · StylishThemes GitHub-Dark](https://user-images.githubusercontent.com/31389848/74031105-f4e5e400-49b0-11ea-845b-04d741155c1e.png)

If you have other information how to duplicate this, please let me know.

I'm assuming this is not a OS issue, but in any case In Windows 10 is as you see above screenshot.

**Comment by the-j0k3r** [comment]
OK was able to duplicate. Required to expand file in order to trigger it.

![generic](https://user-images.githubusercontent.com/31389848/74031729-8d309880-49b2-11ea-91f9-c4c797bdbaaa.gif)

**Comment by KnutZuidema** [comment]
BTW, in case this was not clear, this happens for every PR, not just for the link I posted. I believe it is because of some inline css which adds a `top: 60px !important;` (at least it fixes it if I remove that) but as far as I can tell this is added server side by github.

**Comment by the-j0k3r** [comment]
This is fixed by
```css
  .toolbar-shadow[style="top: 60px !important;"] {
    margin-top: -60px !important;
  }
```

Yes theres an inline style but am not sure if the above is best fix for this.

@silverwind @xt0rted for feedback

**Comment by KnutZuidema** [comment]
I can confirm that this fixes it for me as well

**Comment by silverwind** [comment]
Would use `.toolbar-shadow[style*="top: 60px"]`
