### ISSUE TITLE
Issues and pull request background regress

### ISSUE THREAD

**Issue by skeggse** [StylishThemes/GitHub-Dark#1057]
Not seeing other related issues (#786 is similar but a slightly different region of the page) - looks like this _just_ started happening. Looks isolated to issues and pull-request pages.

* **Browser**: Chrome, 80.0.3987.87
* **Operating System**: Linux 5.4.15
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/issues
* **Screenshot**:

![image](https://user-images.githubusercontent.com/1348991/74071355-860c8900-49b8-11ea-8a00-9beceee27b73.png)

**Comment by geniiii** [comment]
Can confirm;
![image](https://user-images.githubusercontent.com/24881499/74072047-440e3200-4a0e-11ea-86dc-83b414871906.png)

**Comment by silverwind** [comment]
Fixed in 1.22.204.

**Comment by armano2** [comment]
seems to look different on some pages now

![image](https://user-images.githubusercontent.com/625469/74072222-6bf99780-4a06-11ea-9a99-4c28556b7e2a.png)
https://github.com/StylishThemes/GitHub-Dark/issues/1057


![image](https://user-images.githubusercontent.com/625469/74072240-7ae04a00-4a06-11ea-8f8f-180c504e4b5d.png)
https://github.com/conventional-changelog/commitlint/pull/436

**Comment by silverwind** [comment]
1.22.205 pushed which should bring back the semi-transparency in all cases. Thought it seems GitHub just reverted their change or something.

**Comment by armano2** [comment]
this seems like experiment and its only on some repositories

**Comment by the-j0k3r** [comment]
> this seems like experiment and its only on some repositories

Its tab related see https://github.com/StylishThemes/GitHub-Dark/commit/7f2c0781596eeeb7fe78f08d1cf7a400b781a670#comments

**Comment by silverwind** [comment]
> this seems like experiment

Actually it is not. Some pages are "responsive" while others aren't. Only responsive ones have the problematic `!important` style from GitHub.
