### ISSUE TITLE
 github community support

### ISSUE THREAD

**Issue by sungle3737** [StylishThemes/GitHub-Dark#1061]
**Describe the change you'd like**
- github community support
**Additional context**
![image](https://user-images.githubusercontent.com/27716524/74313302-c86a0780-4db6-11ea-9e1e-772cf6ae0651.png)

**Comment by the-j0k3r** [comment]
@sungle3737 This is already implemented, see https://github.com/StylishThemes/GitHub-Community-Dark

We maintain additional companion styles For GitHub Dark located within our [readme](https://github.com/StylishThemes/GitHub-Dark#additional-userstyles) you may be interesteded in checking this list out.

Thanks though, ;)
