### ISSUE TITLE
Made a GitHub Education Dark Theme

### ISSUE THREAD

**Issue by TheBillyIsMe** [StylishThemes/GitHub-Dark#1062]
Hello 😄,
As a big fan of this project, I figured why not go ahead and extend the concept to [GitHub Education](https://education.github.com/). I've created a [GitHub Education Dark Theme](https://github.com/TheBillyIsMe/GitHub-Education-Dark/) and as the StylishThemes organization is the sole maintainer of GitHub-related Dark Stylus themes, I was wondering if the team here would be interested in having the repository transferred to the organization.

Thanks for your time,
TheBillyIsMe.

https://github.com/TheBillyIsMe/GitHub-Education-Dark

**Comment by Mottie** [comment]
Hi @TheBillyIsMe!

We are really only able to maintain styles that we tend to use a lot. If you're willing to continue keeping this style up-to-date, we could move it over to this organization and make you a maintainer. We may not be able, or have time, to help you maintain it. So, the only real benefit would be more exposure for your style.

**Comment by TheBillyIsMe** [comment]
> 
> 
> Hi @TheBillyIsMe!
> 
> We are really only able to maintain styles that we tend to use a lot. If you're willing to continue keeping this style up-to-date, we could move it over to this organization and make you a maintainer. We may not be able, or have time, to help you maintain it. So, the only real benefit would be more exposure for your style.

I'd definitely be able to do that, that would be great! How would we go about doing so?

**Comment by the-j0k3r** [comment]
Well, heres the rub, I dont mind either but, why do we need a whole new theme?

from basic testing, adding education to GitHub Dark is pretty much  little more than adding education to the regexp

```diff
-@-moz-document regexp("^https?://((gist|guides|help|lab|launch-editor|raw|resources|status|developer|support)\\.)?github\\.com/((?!generated_pages/preview).)*$"), domain("githubusercontent.com"), domain("graphql-explorer.githubapp.com"), domain("www.githubstatus.com") {
+@-moz-document regexp("^https?://((education|gist|guides|help|lab|launch-editor|raw|resources|status|developer|support)\\.)?github\\.com/((?!generated_pages/preview).)*$"), domain("githubusercontent.com"), domain("graphql-explorer.githubapp.com"), domain("www.githubstatus.com") {
```
Then maybe a couple of text colors, so is it really necessary all that extra work?
