### ISSUE TITLE
How do I install the Chrome extension?

### ISSUE THREAD

**Issue by andrewphamvk** [StylishThemes/GitHub-Dark#1066]
### I would like to be able do the following

1. Follow the instructions on how to install
2. Install the extension for Chrome

**Comment by Mottie** [comment]
Hi @andrewphamvk!

This repository contains the CSS that is injected by the extension. To install the extension, please refer to the see the instructions on how to [install Stylus](https://github.com/openstyles/stylus/).

**Comment by andrewphamvk** [comment]
Thanks @Mottie. The link to the non-Beta extension was down but I tried the Beta link and it works. Then I installed the dark style.

**Comment by the-j0k3r** [comment]
The beta is actually the latest production release, Odd..

**Comment by Mottie** [comment]
We just released a new version of Stylus, and for some reason while the new version is pending, they took down the old version. This didn't happen with the beta version. The stable & beta versions have been the same for a while now.
