### ISSUE TITLE
upstream: rebase/squash button borders + on hover

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#1070]
* **Browser**:  FF 73.0.1
* **Operating System**: Win 10 Pro 1809
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/pull/1069
* **Screenshot**:

![generic](https://user-images.githubusercontent.com/31389848/75091427-630fd680-556d-11ea-86c9-bd3729003b93.gif)

<s>**Issue 1)**  Squash and merge has extra border on right (before dropdown button)</s>
**Issue 2)**  Rebase and merge on hover needs extra border on right (before dropdown button)

Cant test plain merge button as its disabled in this repo adn I have no open prs on any of mine to test.

Howevr the Squash/Rebase can be fixed with the following.

Workaround style https://github.com/StylishThemes/GitHub-Upstream-BugFixes

**Comment by silverwind** [comment]
For me, the border between buttons also disappears in GH's original style, while that does not seem to be the case in your screenshots.

**Comment by the-j0k3r** [comment]
Yes its the same as you., its the rebase merge border on hover that gets lost, its issue 2 on OP

**Comment by silverwind** [comment]
This is so minor, it's probably not worth adding a hack for.

**Comment by the-j0k3r** [comment]
>This is so minor,

Sore corneas here =) But the point was to document issue and fix it until its fixed upstream

it's probably not worth adding a hack for.

Youre right,  though.

**Comment by the-j0k3r** [comment]
This has changed

Issue 1 is no longer and issue,

**Comment by the-j0k3r** [comment]
Updated workaround theme, it accounts for all possible instances so far depending on state of PR

**Comment by the-j0k3r** [comment]
Added https://github.com/StylishThemes/GitHub-Upstream-BugFixes

Their all long term issues.

**Comment by the-j0k3r** [comment]
No longer an issue for me
