### ISSUE TITLE
Invite users to new org page has unstyled input box

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#1072]
When setting up an org there's a new page that asks you about inviting people to it. The input box is missing a background and foreground color, and the drop down could use a border at the very least. You should be able to view this page if you're an admin of an org, it's not limited to initial setup.

* **Browser**: chrome 80
* **Operating System**: win10
* **Link to page with the issue**: `https://github.com/organizations/:org/invite`
* **Screenshot**:

Default | GitHub Dark
-- | --
![image](https://user-images.githubusercontent.com/831974/75114927-38cf1f00-5628-11ea-965d-edfff60114cd.png) | ![image](https://user-images.githubusercontent.com/831974/75114880-04f3f980-5628-11ea-9ca6-9eeb6947c33b.png)

**Comment by the-j0k3r** [comment]
Sounds like this happened before https://github.com/StylishThemes/GitHub-Dark/issues/1041

**Comment by silverwind** [comment]
On it...

**Comment by silverwind** [comment]
That input box is not styled by GitHub at all, it's just a browser default coloring. I added some very broad text-type input selectors to cover such cases, maybe there will be false-positives.

**Comment by xt0rted** [comment]
> maybe there will be false-positives

we've never had those before 😄

**Comment by silverwind** [comment]
For the record, specific selector here is just `#search-member` for 

````html
<input type="text" class="hx_badge-input m-2 f4 flex-auto js-badge-input flex-order-2" id="search-member" aria-owns="new-org-members-complete-results" autocomplete="off" spellcheck="false" aria-autocomplete="list" aria-controls="new-org-members-complete-results">
