### ISSUE TITLE
Create new org team input has green check mark wallpaper

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#1073]
This looks to be a side effect of the change made in 41269389ca9eeef2af3d3978a1fc9cce721a4eb4. When I disable that background rule the issue goes away.

This is an issue on the new repo page as well. Probably all inputs with the check mark feedback do it.

* **Browser**: chrome 80
* **Operating System**: win10
* **Link to page with the issue**: `https://github.com/orgs/:org/new-team`
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/75127532-a1041c00-568d-11ea-9957-091da4cc635f.png)

**Comment by Ovyerus** [comment]
Happens in the create new repo name box as well. Seems to be any input that that validation thing I guess.

![image](https://user-images.githubusercontent.com/18654005/75127815-4f06d900-5715-11ea-9720-5335d2e871ea.png)

**Comment by the-j0k3r** [comment]
So GitHub Dark developed a tick.

**Comment by the-j0k3r** [comment]
Thereºs another issue with these boxes. until the validate icon is displayed thereºs an octicon gif animation that looks like it was shredded.

![generic](https://user-images.githubusercontent.com/31389848/75133522-7476f100-56db-11ea-82fe-d0cfa4cb4352.gif)

And also the best upstream bug prize goes to GitHub, now repos cant be deleted.

![generic](https://user-images.githubusercontent.com/31389848/75133270-6674a080-56da-11ea-95da-6d418a270d12.gif)

**Comment by Ovyerus** [comment]
> And also the best upstream bug prize goes to GitHub, now repos cant be deleted.

Nah, you gotta type the whole repo name now (`style-it-themes/delete-me`)

**Comment by the-j0k3r** [comment]
> Nah, you gotta type the whole repo name now

 I should have read what the box says, I didn't expect this to have changed without any notice.

**Comment by the-j0k3r** [comment]
Please check https://github.com/StylishThemes/GitHub-Dark/issues/1072 isn't broken by the fix above.

**Comment by Ovyerus** [comment]
It's back to how it was before now :+1:

**Comment by the-j0k3r** [comment]
I hope this means that its fixed on here and #1072

**Comment by silverwind** [comment]
https://github.com/StylishThemes/GitHub-Dark/issues/1072 is fine. The only reason I used specific selectors was that I was afraid of affecting checkboxes and such, but I guess we override those later anyways so it's fine to just use `input`.
