### ISSUE TITLE
Repo files table blue?

### ISSUE THREAD

**Issue by zmni** [StylishThemes/GitHub-Dark#1074]
* **Browser**: 
Edge (Chromium)
* **Operating System**: 
Windows
* **Link to page with the issue**: 
All repos.
* **Screenshot**:
![gh-dark](https://user-images.githubusercontent.com/841523/75140506-9eeb9d00-5721-11ea-82eb-c83ffafbfcf5.jpg)

Is this intentional? The header background & table border looks weird.

**Comment by the-j0k3r** [comment]
No its not intentional and I could only duplicate until I refreshed the page. Now I cant see the issue anymore

**Comment by zmni** [comment]
Yeah, hard refresh my browser and the header look like your screenshot now. But the blue color is weird, imho previous style is better. This change of style is permanent?

**Comment by the-j0k3r** [comment]
I cant see any issue, we use this blue around the style. but t answer your question, yes it seems its changed from dark grey to blue sometime ago.

**Comment by the-j0k3r** [comment]
I checked this out, many of the tables now, have a blue `.Box-header--blue` GitHub must have added new classes recently that are now picked up with this from our generator.

Now to remove this just here would make the rest of the same like areas feel out of place, also changing all to grey makes the style look like death by gray and TBH theres already way too much grey.

I vote leave as is!

**Comment by silverwind** [comment]
This blue is coming from a GH change. I fixed the black background in https://github.com/StylishThemes/GitHub-Dark/commit/b444841444fc53b259c6eba5ad2819f90651f1ad.

**Comment by zmni** [comment]
Ok, thank for the answer. You should also update the screenshot in readme, it still use old style.
