### ISSUE TITLE
Selected search result text looks darker then it should be

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#1080]
I'm not sure if it's just me or if something recently changed but the text in the search box looks darker then it should be now. Right now it's `#dcdcdc` because of a manual style but other areas that use the primary color are all set to use `#ffffff` for the text.

Should the manual style be removed so the value from the generator is used?

Using `#dcdcdc`

![image](https://user-images.githubusercontent.com/831974/75738758-121c8280-5cd1-11ea-9738-94a46a5fec48.png)

Using `#ffffff`

![image](https://user-images.githubusercontent.com/831974/75738891-78a1a080-5cd1-11ea-89c5-fb79fec90c00.png)

**Comment by xt0rted** [comment]
After some more testing every drop down I've looked at uses `#ffffff` for the text color so I PRed the change so you could see what would be removed.

**Comment by the-j0k3r** [comment]
That really needs to be brighter than `#dcdcdc`, it looks very dull when selected, I suggest ticking that over to `#eeeeee`

**Comment by the-j0k3r** [comment]
Actually from my side looks OK'ish but still too dull.

![generic](https://user-images.githubusercontent.com/31389848/75749059-2ee0a680-5d21-11ea-88f4-f4e271e7a303.gif)

**Comment by xt0rted** [comment]
Compare the search results to the watch drop down on the top of this page. All of these drop downs use the primary color for the background and `#ffffff` for the text color. The only spot that's not doing that, due to the manual override, is the search results which is why my proposed fix is to remove the override and let the generator handle it.

**Comment by the-j0k3r** [comment]
With your PR this is better, however.

GitHub Dark uses `#afafaf` for the non highlighted parts `.jump-to-suggestions-path` 
 and `#dcdcdc` for the highlighted parts `.jump-to-suggestions-results-container mark`.

This is not even in the same shade family af vs dc, they both must be somewhere in same building not in a dif neighborhood.

**Comment by silverwind** [comment]
`#fff` over base color seems fine to me. We want maximum contrast there.

**Comment by the-j0k3r** [comment]
If you also remove   .jump-to-suggestions-results-container mark, form the same rule in #1081 you end up with the right balance between the two but VERY DULL

**Comment by the-j0k3r** [comment]
See https://github.com/StylishThemes/GitHub-Dark/pull/1081/files#r386888785 its illustraded enough the issue.
