### ISSUE TITLE
Releases and Tags buttons have text that looks too dark

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#1085]
This is similar to #1080.

There's a number of rules being applied to these that look like they might be out of order. There's also a number of manual styles even though it's in the generator, but it looks like some of those are because of rules having `!important` so the generated rules aren't applied. If I remove the manual styles and `!important` from the others that give the wrong color then they look ok but I'm not sure what this may break elsewhere.

* **Browser**: chrome 80
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/tags
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/76264154-51018980-6237-11ea-8ae2-4814b685173e.png)

**Comment by xt0rted** [comment]
I'm wondering if we should adjust the order some of our rules are applied in. Right now the generated stuff is at the start of the file, but if we move some of the custom styling to before the generator then things should cascade as expected and we won't need `!important` as much. What I'm thinking is order rules something like this:

1. Things not part of the base style
2. Generated
3. Overrides
4. Plugins

There's an example of my proposed changes for these buttons in the [`order-testing`](https://github.com/StylishThemes/GitHub-Dark/commits/ordering-testing) branch.

**Comment by silverwind** [comment]
Not sure about the ordering but feel free to gratuitously cut out manual `!important` styles. The come mostly from a time before we had the generator.

**Comment by the-j0k3r** [comment]
I only use `!important` in manual styles if absolutely needed no matter if its before or after.

You will find that most places where there are pre-existing manual rules set  with `!important` that if its removed, nothing breaks, so I think we should do cleanup of that `!important` where not absolutely necessary.

**Comment by the-j0k3r** [comment]
if we remove important here it breaks the styling, the generated parts dont even do anything here.

The fix I submitted is just a change of rules for the text color for these. Until  a better fix comes along,


Fell free to reopen anyway if you want.
