### ISSUE TITLE
GraphQL explorer is no longer themed

### ISSUE THREAD

**Issue by jack1142** [StylishThemes/GitHub-Dark#1089]
* **Browser**: Chrome 80
* **Operating System**: Windows 10
* **Link to page with the issue**: https://developer.github.com/v4/explorer/
* **Screenshot**:
![image](https://user-images.githubusercontent.com/6032823/77652670-e8bce280-6f6e-11ea-9e1e-c5af531c1273.png)

**Comment by the-j0k3r** [comment]
Actually not fixed for me.

**Comment by the-j0k3r** [comment]
must have been a burp in my internet connection and the fix was removing classes.

Seems fixed now whatever it was.
