### ISSUE TITLE
Refined GitHub: color of CI icons in header

### ISSUE THREAD

**Issue by fregante** [StylishThemes/GitHub-Dark#1090]
* **Browser**: Firefox
* **Operating System**: macOS
* **Link to page with the issue**: This page 
* **Screenshot**:

<img width="728" alt="dimmed colors" src="https://user-images.githubusercontent.com/1402241/77864528-51cf7f00-7229-11ea-947a-14560fadf4c0.png">

<img width="712" alt="regular" src="https://user-images.githubusercontent.com/1402241/77864633-07023700-722a-11ea-8a67-a5c8a7664ff0.png">

**Comment by fregante** [comment]
I think this should be more specific: `.repohead h1 .octicon-repo`

https://github.com/StylishThemes/GitHub-Dark/blob/a4c96edabb6c015aeb6c29d52f85a17c04dd496c/github-dark.user.css#L4214



And this should be dropped:

https://github.com/StylishThemes/GitHub-Dark/blob/a4c96edabb6c015aeb6c29d52f85a17c04dd496c/github-dark.user.css#L10270-L10272

**Comment by silverwind** [comment]
Thanks, I came to the exact same conclusions.
