### ISSUE TITLE
Better secondary colour

### ISSUE THREAD

**Issue by johnletey** [StylishThemes/GitHub-Dark#1094]
**Describe the change you'd like**

Using the default base colour, the secondary colour look fine:

<img width="1312" alt="Screenshot 2020-04-13 at 16 14 51" src="https://user-images.githubusercontent.com/62398724/79132784-d500e100-7da2-11ea-8998-d03f02cd1797.png">

But when using a custom base colour `#a76c6e`, the secondary colour looks odd and doesn't match the colours:

<img width="1312" alt="Screenshot 2020-04-13 at 16 15 00" src="https://user-images.githubusercontent.com/62398724/79132858-ed70fb80-7da2-11ea-9a0c-4c6758f967b3.png">

Could we potentially add another configuration option for this? Or, personally the option I want to go with, is to make the secondary colour configured to a darker version of the base colour?

**Additional context**

This secondary colour is all over the site, for example:

<img width="1312" alt="Screenshot 2020-04-13 at 16 27 39" src="https://user-images.githubusercontent.com/62398724/79133350-cb2bad80-7da3-11ea-8ab5-1a47060bd20c.png">

**Comment by the-j0k3r** [comment]
This seems a duplicate of an old issue, I cant find it atm but its essentially the same and never went anywhere.

@silverwind

**Comment by jletey** [comment]
> This seems a duplicate of an old issue, I cant find it atm but its essentially the same and never went anywhere.

@the-j0k3r Ah okay, I couldn't find any other issues related to this, but I guess I missed one. Still would love for this to be resolved :)

**Comment by the-j0k3r** [comment]
> Still would love for this to be resolved :)

I may have a solution but not directly in style, as is the style doesnt support less/stylus preprocessor and that means we cant use `darken(color, percentage)` so there is no way to actually darken the base color, as for adding a secondary color option as is we face similar issue, it would possibly work, need exploring this further.

In StackOverflow I used a alpha color for tags etc, it works there due to design of site, here that wouldn't work so well.

Not a high priority in any case. I have the syntax themes to fix before this and no time to do it.

Once I find the dupe issue Ill link it. Until then feel free to hack away in dedicated theme for overriding this locally.

**Comment by silverwind** [comment]
That's not really a secondary color, we actually have it as a regular blue.

CSS provides no method to modify a color (besides the dropped [color-mod proposal](https://github.com/w3c/csswg-drafts/issues/813)), and this blue would need at least 2-3 colors (border, background, color) to make it work, so I'm hesitant to add so many variables. I'm actually thinking we should maybe remove the option to change base color and only support blue.

**Comment by xt0rted** [comment]
I use a slightly brighter blue because I find it easier to see (`#2e8fff`) but I'm in favor of dropping the color selection. If someone wants to maintain a style to apply on top of this to change the colors more then they can, but having it built-in just makes things harder for us.

**Comment by silverwind** [comment]
Indeed, once we have implemented [CSS variables](https://github.com/StylishThemes/GitHub-Dark/issues/1096), users can easily replace all colors in simple add-on userstyles. Let's drop the color option after that one is done.

**Comment by the-j0k3r** [comment]
Im not in favor of dropping user configurable colors. Having to edit the style to change colors is lame.

**Comment by the-j0k3r** [comment]
This is easily solved by making the color configurable for these parts, now removing the base color is not the way to solve the design issue.

**Comment by the-j0k3r** [comment]
All see https://github.com/StylishThemes/GitHub-Dark/issues/1113#issuecomment-658075241

In a few days will be published as addon style
