### ISSUE TITLE
Better read notification styling

### ISSUE THREAD

**Issue by jletey** [StylishThemes/GitHub-Dark#1095]
**Describe the change you'd like**

In the new GitHub notifications beta, you can easily tell the difference between read and unread notifications in the default theme:

<img width="1312" alt="Screenshot 2020-04-14 at 08 50 04" src="https://user-images.githubusercontent.com/62398724/79199878-84829580-7e2d-11ea-8fa9-68d1790281f0.png">

But when using this extension, it's harder to visually distinguish the two:

<img width="1312" alt="Screenshot 2020-04-14 at 08 50 11" src="https://user-images.githubusercontent.com/62398724/79200075-d0353f00-7e2d-11ea-80ec-70a4287bc1d7.png">

**Additional context**

**Comment by the-j0k3r** [comment]
@jletey Thanks for this report.

I'm failing to recognize any issue at this time and find it as easy to distinguish in both counts. The dot on the list is quite prominent, even with the base color you have chosen.

Can you be more specific as to which issue exists according to your perception that should be improved?

**Comment by the-j0k3r** [comment]
I see the read notifications bg is same color, while default isn't.

![generic](https://user-images.githubusercontent.com/31389848/79219253-3633bd80-7e52-11ea-8ef0-5bfbaba0fd95.gif)

fix incoming.

**Comment by jletey** [comment]
@the-j0k3r Thanks so much for fixing this :) Sorry for not replying to your comment sooner

**Comment by the-j0k3r** [comment]
np, enjoy.
