### ISSUE TITLE
Changing the 'color' property of a specific class

### ISSUE THREAD

**Issue by Twaha-Rahman** [StylishThemes/GitHub-Dark#1097]
### I would like to be able do the following

1. Change the 'color' property of a specific class
### Additional context

I wanted to contribute to this awesome project. I have read the `CONTRIBUTING.md` and was proceeding accordingly. I wanted to change the color property of these class `.form-group.successed .success` which had the color property set to "#144620". So I opened up the `github-dark.css` and did a search for "#144620" but nothing showed up. Then I searched by the class name and kept on searching for hours but I didn't find it. Am I doing something wrong here?
(P.S. : I also searched in the `src` folder too)

**Comment by the-j0k3r** [comment]
All of `.form-group.successed .success` are autogenerated colors and if you search for it you will see it in rules that star with `remap-css rule for blablabla` as such editing those areas any chnages are lost on regeneration.

The color you quoted doesnt exist so I assume it was a typo.

But it would be better for you to describe what your reasons are for wanting to do this and it probably be faster. Illustrate with screenshots etc and be sure to provide links to where this is shows and we will have a look.

Regards.

**Comment by Twaha-Rahman** [comment]
@the-j0k3r If you want the screenshot here it is.....
![Capture](https://user-images.githubusercontent.com/39026437/79463066-2d8de380-801a-11ea-90aa-4fb63004b4be.PNG)

**Comment by the-j0k3r** [comment]
Link to page and screenshot of said page please circling the problem area pls.

**Comment by Twaha-Rahman** [comment]
As to why I want to change the color, when I go to the "Create A New Repository" page there is this text color contrast problem.....
![Capture](https://user-images.githubusercontent.com/39026437/79463343-8bbac680-801a-11ea-98f3-cee46ec129d7.PNG)

**Comment by Twaha-Rahman** [comment]
As you can see the text inside the tooltip has contrast problem....

I really want to help this project, please tell me what I can do😀

**Comment by Twaha-Rahman** [comment]
Here's a more informative screenshot......

I have selected the corresponding DOM node so you can see the styling...

![Capture](https://user-images.githubusercontent.com/39026437/79463707-01269700-801b-11ea-950c-e5229526ccd9.PNG)

**Comment by the-j0k3r** [comment]
I see the issue now clearly, fix underway.

When the fix is published study the changes so you better understand how the style works.

Currenly we dont style the color or the ::before/::after very well. Ill fix the lot.

See preview of local fix.
![Capture](https://user-images.githubusercontent.com/31389848/79464485-674ef200-7ffa-11ea-9a3b-104c8f901809.PNG)

**Comment by Twaha-Rahman** [comment]
So you're saying that these colors for the ::before/::after CSS selectors aren't assigned in your CSS, rather they are generated on-the-fly?

**Comment by the-j0k3r** [comment]
The ::after and color in this case were missing from generator. and yes we generally add rules to the generator and the backend generates the CSS based on default stylesheets with the override colors we earlier added to generator.

Any changes upstream are then generated and applied assuming the rules in gen are up-to-date at regular intervals.

See https://github.com/StylishThemes/GitHub-Dark/commit/742d39ea3c6aefad6492823ddc350a3e44bcb8f5 for color changes

and https://github.com/StylishThemes/GitHub-Dark/commit/90abe8a0499e714d5e1e0e156b22e0a2b759fa37 for border::after changes

**Comment by the-j0k3r** [comment]
If you update to 2.0.47 this should look like screenshot above.

Feel free to close this.

**Comment by Twaha-Rahman** [comment]
Well done and thanks for everything!
