### ISSUE TITLE
Clone button for "SSH or HTTPS" has styling issues with background color

### ISSUE THREAD

**Issue by Twaha-Rahman** [StylishThemes/GitHub-Dark#1100]
* **Browser**: Chrome Version 81.0.4044.113 (Official Build) (64-bit)
* **Operating System**: Windows 10 (64 Bit)
* **Link to page with the issue**: 
* **Screenshot**: ![Capture](https://user-images.githubusercontent.com/39026437/80012717-8f08f300-84ef-11ea-88b3-19ae6b058154.PNG)

**Comment by xt0rted** [comment]
This is a duplicate of #1099.
