### ISSUE TITLE
How to create a BitBucket-Dark variant?

### ISSUE THREAD

**Issue by cognifloyd** [StylishThemes/GitHub-Dark#1101]
### I would like to be able do the following
1. Make a BitBucket-Dark theme similar to Github-Dark and other StylishThemes/*-Dark.

### Additional context
This question doesn't belong on the GitHub-Dark repo, but I'm not sure where to ask about creating a new StylishThemes repo.

I use BitBucket alot and have not had luck finding a good usercss to add a dark theme.
After beginning to hack on a usercss, I decided doing that manually was far too error prone and requires too much work.

I would like to use a scripted solution like GitHub-Dark does. So, I forked GitHub-Dark, but there is a lot of other StylishThemes infra that I would have to recreate to maintain a theme.

Can someone help me get started with BitBucket-Dark? Can this be part of StylishThemes?

**Comment by the-j0k3r** [comment]
Hi and thanks for reaching out to us.

It could be part of stylishthemes, but that means a commitment to a standard of quality and bug fixing response, all for the grand payment of 0, if you are looking to make a commitment to being the maintainer for this bitbucket style that is..

I dont personally use bitbucket so as for help with that I cant offer any. Nor any commitments to the future.

Regarding the generator, the author @silverwind is best to answer that question, though I cant see why not. You need to study the [generator.js file](https://github.com/StylishThemes/GitHub-Dark/blob/master/tools/generate.js) and try to adapt it to the bitbucket domains.

also the @-moz-document sections need to be adapted etc.

I know there are plans to make a general style generator and I suppose the finished product would probably be easier to configure and plug in to other sites, that again is pretty much JavaScript and knowledge of scrapping the CSS files and outputting remapped versions which the latter @silverwind has implemented thus far, though it has its limitations at the moment.

**Comment by silverwind** [comment]
`generate.js` is as simple as it gets, all the complexity is in the dependencies `remap-css` and `fetch-css`.

I'm afraid I can't offer more support but the modules are well documented so a bit of JS knowledge should get you pretty far.
