### ISSUE TITLE
Screenshot of the notifications page

### ISSUE THREAD

**Issue by mesqueeb** [StylishThemes/GitHub-Dark#1105]
**Describe the change you'd like**

 Before I go through all the install steps, I'd love to see how the notifications page looks. Since this is where I spent 90% of my time on Github.

I was hoping someone could add a screenshot to the ReadMe for the notification page!

**Comment by xt0rted** [comment]
This is using `#2e8fff` for the base color and without a background image.

![github com_notifications_query=repo%3AStylishThemes%2FGitHub-Dark](https://user-images.githubusercontent.com/831974/80784465-2226d600-8b4b-11ea-9c32-3628c8c3c87b.png)

This is a variation I've been testing using `#000000` for the background.

![github com_notifications_query=repo%3AStylishThemes%2FGitHub-Dark (1)](https://user-images.githubusercontent.com/831974/80784517-44205880-8b4b-11ea-9b52-f345068c39ad.png)

**Comment by mesqueeb** [comment]
Thanks so much! I wonder if it's easy to see the difference between Unread and read threads. Another dark mode I tried before this was very difficult to see, because it was too subtle.

**Comment by the-j0k3r** [comment]
@mesqueeb see https://github.com/StylishThemes/GitHub-Dark/issues/1095#issuecomment-613381166 read/unread

**Comment by mesqueeb** [comment]
Thanks so much ! That gif should be on the readme!!! 😊
