### ISSUE TITLE
Private repo icons aren't yellow on the dashboard

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#1109]
* **Browser**: chrome 81
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/
* **Screenshot**:

Before | After
-- | --
![image](https://user-images.githubusercontent.com/831974/81029235-307a3800-8e52-11ea-9224-05e5956f606a.png) | ![image](https://user-images.githubusercontent.com/831974/81029265-44259e80-8e52-11ea-9649-2aabe5e0fe97.png)

This is happening because of the `.octicon { fill: currentColor; }` rule. Removing that fixes these but I'm not sure what that may break elsewhere.

**Comment by silverwind** [comment]
Pretty sure we can now remove most of these generator rules that don't actually change the values, those were mostly to deal with order-related issues IIRC. There is still a possibility that non-github.com sites introduce conflicting styles, I plan to deal with that eventually.

**Comment by xt0rted** [comment]
Looks like removing all of those default generator rules fixes it. Not seeing anything broke elsewhere yet which is also nice.

**Comment by xt0rted** [comment]
Fixed in e326a5a509dab20f88f780a25810fdc0bde2c3c7.
