### ISSUE TITLE
.Counter no longer highlights non-zero counters

### ISSUE THREAD

**Issue by fregante** [StylishThemes/GitHub-Dark#1110]
Affected URL (among others): https://github.com/StylishThemes/GitHub-Dark/search?q=test&unscoped_q=test

It's no longer highlighting non-zero counters like GitHub does by default:

<img width="247" alt="Screen Shot 2020-05-05 at 23 31 34" src="https://user-images.githubusercontent.com/1402241/81118148-aa7cf080-8f28-11ea-8e44-7efc9386468e.png"> <img width="245" alt="Screen Shot 2020-05-05 at 23 31 42" src="https://user-images.githubusercontent.com/1402241/81118144-a8b32d00-8f28-11ea-93d3-ea9657b789ec.png">

**Comment by silverwind** [comment]
Fixed:

<img width="313" alt="image" src="https://user-images.githubusercontent.com/115237/81122363-08153b00-8f31-11ea-8236-8ef56a2c97b6.png">

**Comment by fregante** [comment]
I barely see any difference though. Categories with items normally stand out; with this change they just have less contrast than the `0` ones. 

An equivalent style would be like:

```css
.Counter--gray {
    background-color: white;
    color: #555;
}
```

<img width="249" alt="8" src="https://user-images.githubusercontent.com/1402241/81123768-27619780-8f34-11ea-80ef-fc05597da661.png">

**Comment by silverwind** [comment]
Hmm yes, I just noticed github itself has them white-on-dark, so we should invert too.

**Comment by silverwind** [comment]
This should be better:

<img width="326" alt="image" src="https://user-images.githubusercontent.com/115237/81125826-a907f400-8f39-11ea-92da-6a12acb499b8.png">

**Comment by fregante** [comment]
Yes, thank you!
