### ISSUE TITLE
Move to Less preprocessor

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#1111]
We want to output a less format for stylus' Less preprocessor while also having the ability to `@import` files so we can break up our theme sections. I plan to:

1. Move current `github-dark.css` to `src/index.less`
2. Split `src/index.less` up into multiple files in `src` via `@import`
3. Create a build step that resolves only the `@import` statements and outputs `github-dark.user.css`.

I'm not sure yet how to do the Less to Less build or if existing Less/Webpack tooling can be configured to only do the imports and not fully compile to CSS.

**Comment by the-j0k3r** [comment]
Do we need any github-dark.css at all? Why do we need it?

My main concern is keeping things in a user friendly format, all these complexities will probably put ppl off from contributing or making proper contributions. As is there's already a learning curb most ppl dont read the contrib file.

What considerations are we giving in this proposed design to K.I.S.S?

**Comment by silverwind** [comment]
I don't share your concerns, after this it will be easier because there is no more confusion about `github-dark.user.css` vs. `github-dark.css` (which will be gone).

**Comment by xt0rted** [comment]
@silverwind why switch to less instead of scss?

**Comment by silverwind** [comment]
I would prefer SCSS but Stylus only [supports](https://github.com/openstyles/stylus/wiki/UserCSS-authors#preprocessor) Less and Stylus (the preprocessor), thought that may be a good opportunity to contribute SCSS support to Stylus.

**Comment by xt0rted** [comment]
> that may be a good opportunity to contribute SCSS support to Stylus.

I was thinking the same thing. Not sure how complicated that might be, but I'd much rather see scss over less at this point.

@mikefreuden what does Cascadea support for [preprocessors](https://github.com/openstyles/stylus/wiki/UserCSS-authors#preprocessor)?

The Cascadea userbase is small compared to Stylus, but it's the only option for Safari users so it'd be nice to make sure we don't abandon them with a move like this.

**Comment by silverwind** [comment]
I've attempted to load `dart-sass` into Stylus but as they rely on globals in their web worker code, I don't think its possible without a bundler because dart-sass expects a commonjs environment. I know how to get it to work via Webpack's `worker-loader` but using that would be a major refactor of Stylus that I'm not willing to do.

Also there is https://github.com/openstyles/stylus/issues/72 where there are concerns on bundle size because dart-sass is 3.6 MB, thought I don't really see much of an issue in that personally, but I don't know exactly how stylus does the preprocessing and when the worker is loaded.

**Comment by xt0rted** [comment]
I was looking at that issue earlier and figured the hardest part of this would be convincing them.

I've been using [zeit/ncc](https://github.com/zeit/ncc) to package all of my JS stuff up into a single file, I figured we'd do something like that with `dart-sass` and with some tree shaking maybe get rid of a good chunk of code that won't be used. To simplify it on the Stylus side we could create a new npm package that's nothing more than a single file version of this so their workflow doesn't need to change.

**Comment by silverwind** [comment]
Pretty sure `dart-sass` cannot be tree shaken. It's cross-compiled from dart so conventional methods like rollup uses will not work.

That said, I'm still not convinced the benefits of Less outweight the drawbacks. The only benefits are:

- A way to use `@import` if we compile Less to Less but something like that is very uncommon
- A way to map one Usercss variable to many (needed for themes)

**Comment by mikefreuden** [comment]
> > that may be a good opportunity to contribute SCSS support to Stylus.
> 
> I was thinking the same thing. Not sure how complicated that might be, but I'd much rather see scss over less at this point.
> 
> @mikefreuden what does Cascadea support for [preprocessors](https://github.com/openstyles/stylus/wiki/UserCSS-authors#preprocessor)?
> 
> The Cascadea userbase is small compared to Stylus, but it's the only option for Safari users so it'd be nice to make sure we don't abandon them with a move like this.

Cascadea currently supports Stylus-lang, but not Less or Sass/SCSS. I've been working with getting Less working as well, though. I suspect it won't be too terribly difficult, and will mostly require some hackery to get Less playing nice in macOS's JavaScriptCore frameworks that I haven't had a chance to get around to doing. Prioritized Stylus-lang support as in my experience it seems like more userstyles are opting for that rather than Less.

Haven't looked into Sass or SCSS much given Stylus doesn't support it either, but if Stylus adopts support and some popular userstyles (like this one!) start using it I'd definitely consider it. Given Stylus is very much the de facto standard for userstyles it is absolutely my intention to make Cascadea play as nicely with Stylus (and styles written for it) as possible.

**Comment by fregante** [comment]
My guess is that if you want to preserve broad support, you must ship CSS IMHO

That means either leaving things as is, or adding a build step.

**Comment by silverwind** [comment]
Yeah, I'm now leaning towards keeping the output CSS. It probably means keeping the Theme CSS in usercss variables as the `default` preprocessor can not map one variable to many and a preprocessor would not help us either because CSS does not provide a way to conditionally load a block.

**Comment by silverwind** [comment]
By the way, I did experiment with emulating conditions using keyframes, but it only works in Chrome/Safari:

https://jsfiddle.net/silverwind/xmh4r5f2/
