### ISSUE TITLE
Enterprise Last commit info broken

### ISSUE THREAD

**Issue by arpitjindal97** [StylishThemes/GitHub-Dark#1114]
GitHub Enterprise Server 2.20.7

* **Browser**:  Chrome
* **Operating System**: Mac OS

* **Screenshot**:
![image](https://user-images.githubusercontent.com/15676216/82479006-5f99d600-9aef-11ea-80cf-2de0e7c1e9c8.png)

Added Domain here:

![image](https://user-images.githubusercontent.com/15676216/82479445-08483580-9af0-11ea-8e9f-11e10ba7c98d.png)

**Comment by silverwind** [comment]
We don't have access to Enterprise CSS, but if you can post the CSS rule that adds this background, we can try to add it.

**Comment by arpitjindal97** [comment]
Is it enough ?

![image](https://user-images.githubusercontent.com/15676216/82544713-2c992600-9b73-11ea-9a90-179cdafb515c.png)

**Comment by silverwind** [comment]
Should be fixed, try again with v2.0.90.

**Comment by arpitjindal97** [comment]
how to persist my URL addition after update ?

**Comment by silverwind** [comment]
No idea, Stylus should keep them, but best to check it's documentation.

**Comment by the-j0k3r** [comment]
> No idea, Stylus should keep them, but best to check it's documentation.

Stylus updates the whole style, no custom URL or any local chnages will be kept, thats not how updates work for styles.

Any custom edits must always be re-added including @-moz-document URLS

**Comment by silverwind** [comment]
> Stylus updates the whole style, no custom URL or any local chnages will be kept

Sounds like a Stylus bug to me. Ideally it should migrate style settings between updates, e.g. remove non-existant settings, add default values for new settings.

**Comment by the-j0k3r** [comment]
Yes, but if you mod the moz-doc rule it wont, and it shouldnt

**Comment by silverwind** [comment]
Ah yes, CSS modification disables updating, this is fine. I just thought we had a config option for enterprise URL, but apparently not.

**Comment by xt0rted** [comment]
There's a solution for this in #938 but it was never implemented. It's been awhile since looking into this so I'm not sure what the real holdup was with it.
