### ISSUE TITLE
Stargazers selected tab is no longer styled

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#1115]
* **Browser**: chrome 83
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/stargazers
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/82860758-a2412100-9ee8-11ea-8091-f54b9807a392.png)

**Comment by the-j0k3r** [comment]
You know tab also.

**Comment by silverwind** [comment]
Was fixed by https://github.com/StylishThemes/GitHub-Dark/commit/eaf46859369d4fba4c8134e3e55640dfe97dbf1d#diff-64ae9f3acdf5e1c48548adca960457b1R7664 but I don't like that it's `#181818`, should be `#202020` so manual style may be needed.
