### ISSUE TITLE
New version of octicons is being used on the site now

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#1117]
I'm not sure if we're still inlining some of the octicons, but if we are a [new version](https://github.com/primer/octicons-v2) is being used on the site as of today so we'll need to double check and adjust them if needed. We might have to adjust some of our selectors since they're a different style but so far they seem ok to me.

**Comment by silverwind** [comment]
Removed some ancient SVGs that are probably not in use any more. The only thing we modify is the spinners and those should not be covered by the octicons.

**Comment by silverwind** [comment]
There are a few more SVG's used in `background` on off-sites like developer, but main site is fine. We should remove all of them and style the original icons via `fill` if possible.

**Comment by xt0rted** [comment]
There's one on the developer site that's inlined because they're also inlineing it. It's the arrow used in the right nav https://developer.github.com/v3/. I'm not sure about the rest though.

**Comment by Fahme** [comment]
There are still Octicons that don't have ```fill`` probably in the css for the github.com domain, few examples 

- PR list icons
- CI checks icons 
etc ...

screenshots : 

![Screen Shot 2020-06-03 at 3 24 36 PM](https://user-images.githubusercontent.com/10753722/83636390-96232680-a5ae-11ea-9c0e-2e1176539d5f.png)

@silverwind

**Comment by the-j0k3r** [comment]
the checkmark should be green not grey as its show in your screenshot.

**Comment by silverwind** [comment]
Those are green for me, must be an issue on your end, try updating/reinstalling.

**Comment by Fahme** [comment]
nvm problem from my end just updated and it worked. Thanks !
