### ISSUE TITLE
Search field not properly styled when focused while logged out

### ISSUE THREAD

**Issue by LingMan** [StylishThemes/GitHub-Dark#1118]
Follow up to https://github.com/StylishThemes/GitHub-Dark/issues/1116.

It's still broken when you focus the search field.

* **Browser**:  Firefox 76.0.1
* **Operating System**: Manjaro Linux
* **Github Dark version**: 2.0.94
* **Link to page with the issue**: https://github.com/
* **Screenshot**: ![github_dark_search_bug_2](https://user-images.githubusercontent.com/18645382/83213001-4df4a600-a161-11ea-8dd5-5fffebb71828.png)

**Comment by silverwind** [comment]
Would not call it broken, the style is close to the original, except inverted colors. The border is present on original too.

**Comment by LingMan** [comment]
Ah, I should have explained this one in detail. It doesn't really come out in a screenshot that well.

When logged in and this theme is active the background of the search field has the same color no matter if it's focused or not. A grey slightly lighter than the header bar surrounding the search field.
Unfocused:
![gh_search_loggedin_styled_nofocus](https://user-images.githubusercontent.com/18645382/83278167-6ef5df00-a1d3-11ea-802a-fac27a9223f4.png)
Focused:
![gh_search_loggedin_styled_focus](https://user-images.githubusercontent.com/18645382/83278187-774e1a00-a1d3-11ea-8cf5-f94834a16ce1.png)

However, when logged out the background of the search field changes color between focused and unfocused. In the focused case it is the same color as the surrounding header bar.
Unfocused:
![gh_search_loggedout_styled_nofocus](https://user-images.githubusercontent.com/18645382/83278607-27238780-a1d4-11ea-8f90-45bfdbb1385a.png)
Focused:
![gh_search_loggedout_styled_focus](https://user-images.githubusercontent.com/18645382/83278647-34d90d00-a1d4-11ea-89b6-66bd31fed0ae.png)

Now that I see the logged in and logged out fields directly next to each other it appears that there's a color mismatch even when unfocused. Both the text as well as the background are lighter than when logged in. The text should be darker when unfocused and logged out, just like in the logged in case. On the other hand I like that the field itself stands out a bit more when logged out.
Whatever color combination you end up choosing here, they should be identical whether logged in or out.

In the default Github style the colors for the logged in and logged out case are identical.
The border at the bottom does exist in the default Github style but is almost invisible because the field background turns white when focused.
Default unfocused:
![gh_search_loggedout_unstyled_nofocus](https://user-images.githubusercontent.com/18645382/83279964-386d9380-a1d6-11ea-8911-7b395fe0abbc.png)
Default focused:
![gh_search_loggedout_unstyled_focus](https://user-images.githubusercontent.com/18645382/83279987-3f94a180-a1d6-11ea-98f5-e56d06f2472b.png)

(The text "Search" disappears when the field gets focused in the default Github style when logged out. That doesn't happen when logged in and I consider it a bug in the default style.)

**Comment by LingMan** [comment]
This is no longer a problem with the new design.
