### ISSUE TITLE
Timeline "Load More" button and wobbly line

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#1120]
<img width="881" alt="image" src="https://user-images.githubusercontent.com/115237/84042243-1974bb80-a9a5-11ea-949a-71bcccbc7b86.png">

https://github.com/go-gitea/gitea/pull/8346#issuecomment-638578779
https://github.com/swagger-api/swagger-ui/pull/6030#issuecomment-638412978

This seems to be caused by a recent generator change and possibly wrong removal of a fix for the wobbly line. IIRC, we had at some point a replacement background image for the wobbly line with proper transparency, not sure what happened to it.

**Comment by the-j0k3r** [comment]
> not sure what happened to it.

You nuked it from orbit, only way to be sure.

**Comment by the-j0k3r** [comment]
https://github.com/StylishThemes/GitHub-Dark/commit/4eb413710f2c2529613bfa73223a22960c5f17cc

https://github.com/StylishThemes/GitHub-Dark/commit/5484e380923f878690e4f9257bcf88a57576c44a

**Comment by silverwind** [comment]
Oops, I might have accidentially deleted too much, fixing.

**Comment by the-j0k3r** [comment]
OK removing     background-image: none; from https://github.com/StylishThemes/GitHub-Dark/blob/27f68a747835bfb4ba1c33823289e7c7fd9cfaa8/github-dark.css#L10478 shows the squigly line but with a white bg

**Comment by silverwind** [comment]
Just restoring the deleted rule was enough to fix both cases. Also cleaned up one dead selector.
