### ISSUE TITLE
The design has a problem at the margin

### ISSUE THREAD

**Issue by RenanOfugi** [StylishThemes/GitHub-Dark#1124]
**problem in CSS** 

* **Browser**: Google Chrome 81.0
* **Operating System**: Linux Mint 19.3
* **Link to page with the issue**: homepage https://github.com/
* **Screenshot**:
![Seleção_009](https://user-images.githubusercontent.com/8943600/84575404-2a497680-ad83-11ea-9adb-56b0454f1bc6.png)

**Comment by silverwind** [comment]
This must be another extension interfering, we don't do shades of blue like on that screenshot.

**Comment by the-j0k3r** [comment]
What are you willing to bet its another Google store GitHub Dark style extension.

**Comment by the-j0k3r** [comment]
ping @RenanOfugi

**Comment by RenanOfugi** [comment]
oh really, actually had another extension interfering
