### ISSUE TITLE
Profile Photo is Negative

### ISSUE THREAD

**Issue by arpitjindal97** [StylishThemes/GitHub-Dark#1125]
Go to Network graph: https://github.com/StylishThemes/GitHub-Dark/network

Hover on HEAD of any branch, profile picture will pop up and the photo is Negative

Screenshot:
![image](https://user-images.githubusercontent.com/15676216/84597742-a4612480-ae83-11ea-9da2-c17c139af139.png)

**Comment by xt0rted** [comment]
This is a known issue and limitation of styling the `<canvas>` tag being used for this.

Duplicate of #583
