### ISSUE TITLE
Eight (8) duplicate CSS properties

### ISSUE THREAD

**Issue by Gitoffthelawn** [StylishThemes/GitHub-Dark#1126]
The CSS code (v2.0.110) has 8 locations where the same property is defined in the same ruleset more than once.  Here they are:

warning | 16068 | : | 5 | Duplicate property 'background-image' found.
warning | 16176 | : | 5 | Duplicate property 'background-color' found.
warning | 16622 | : | 5 | Duplicate property 'background-color' found.
warning | 16659 | : | 5 | Duplicate property 'background-color' found.
warning | 16732 | : | 5 | Duplicate property 'background-color' found.
warning | 16798 | : | 5 | Duplicate property 'background-color' found.
warning | 16856 | : | 5 | Duplicate property 'background-color' found.
warning | 16906 | : | 5 | Duplicate property 'background-color' found.

**Comment by the-j0k3r** [comment]
Linting issues arent bugs per say, and can be safely ignored.

**Comment by Gitoffthelawn** [comment]
Yes, they often do not result in critical runtime errors, but is there any reason all those properties are being defined multiple times in the same rulesets?

**Comment by the-j0k3r** [comment]
Its likely caused by a bug in one of the generators components.

**Comment by silverwind** [comment]
Yes these are generator bugs I'm aware of but quite hard to solve actually and low priority.
