### ISSUE TITLE
build system: make update issues

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#1131]
Running `make update` outputs this here

```
> make update
yarn -s run updates -cu
NAME       OLD     NEW     AGE    INFO
stylelint  13.6.0  13.6.1  1 day  https://github.com/stylelint/stylelint
 ╭────────────────────────╮
 │  package.json updated  │
 ╰────────────────────────╯
rm -rf node_modules
process_begin: CreateProcess(NULL, rm -rf node_modules, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:32: update] Error 2
```

package.json is updated but it fails at removing `node_modules`

OS: Windows 10 1903

**Comment by silverwind** [comment]
Is that Powershell? I guess their `rm` shim is not unix-compatible.

**Comment by the-j0k3r** [comment]
none of those work with my Atom terminal and working with external terminals isnt an option ide like to entertain.

**Comment by silverwind** [comment]
I'm not familar with Atom terminal. Isn't it just a wrapper around `powershell` or `cmd`?

I think I could actually fix this by just adding a flag to `updates` that removes `node_modules` after writing the update even thought it's kind of unrelated what the module does.

**Comment by the-j0k3r** [comment]
Im using terminus or x-terminal its a sort of wrapper yes, with bash recent updates broke the ability to be wrapped, only way would be external here.

Would rather this worked OOB

**Comment by silverwind** [comment]
try again on master

**Comment by darek-grund** [comment]
@the-j0k3r running `make update` fails because your system can't use linux commands, `rm` in particular. IMO easiest way to work with linux is use WSL assuming you are using Windows. But if you not wish to learn how to use Linux, then next best thing is to:

1. Install [Cygwin](https://cygwin.com/install.html) 
2. Add Cygwin install directory to PATH variable, because the installer somehow doesn't do that part. Here's step by step [instructions](https://www.howtogeek.com/howto/41382/how-to-use-linux-commands-in-windows-with-cygwin/)
3. Check if everything works by typing in terminal `rm --varsion` - you should get response like `rm (GNU coreutils) 8.26`

You can now use `make update` in x-terminal.

**Comment by the-j0k3r** [comment]
> @the-j0k3r running `make update` fails because your system can't use linux commands, `rm`

I am aware thx.

> IMO easiest way to work with linux is use WSL assuming you are using Windows. But if you not wish to learn how to use Linux, then next best thing is to:

I can use Linux and know enough Linux to do enough damage ;), I refer you to https://github.com/StylishThemes/GitHub-Dark/issues/1131#issuecomment-646276619.

Git for Windows ships with bash binaries but like I said, it wont open inside the Atom x-terminal or terminus instead opens externally.

My dev machine is a VM, I could solve this by transferring all my Keys and setup to a Linux VM, this takes time and will I dont have in particular abundance.

Thanks for your advice and guides in any case, its not know how Im short of and besides none of that is the point, ths should work OOB for any OS.

**Comment by silverwind** [comment]
Native Windows development is and always will be a pain in the ass. I'd recommend WSL or Git Bash to get a proper shell. Never been a fan of doing development in a VM (WSL2 still runs one but it's abstracted well enough).

**Comment by the-j0k3r** [comment]
Surely it must be possible to detect OS and run a script for folder removal that's OS dependent,

**Comment by silverwind** [comment]
Sure, workarounds are possible but I prefer not having to maintain them for a OS that I don't even use.

Most serious open source projects handle it that way, it'd just be too much of a maintenance burden to support native Windows (e..g Powershell) when it's so easy to get a Bash shell on it and use one script for all platforms.

**Comment by silverwind** [comment]
@the-j0k3r does it work now on master for you? If so, we can close this.

**Comment by the-j0k3r** [comment]
> @the-j0k3r does it work now on master for you? If so, we can close this.

Yes thanks, **rimraf** works a treat with yarn, npm YMMV

saved me precious time,  until I have more to move to all related properly to Linux vm..

**Comment by the-j0k3r** [comment]
I was able with the latest update of git which received bug fixes to address https://github.com/bus-stop/x-terminal/issues/15

So now am using git-bash again, it works internally as it should now, work with standard Linux commands. I prefer git-bash because of powerline integration is better than for posh-git for powershell.

Thumbs up, Im happy issue was fixed upstream.
