### ISSUE TITLE
Twilight renders all variables in green

### ISSUE THREAD

**Issue by FichteFoll** [StylishThemes/GitHub-Dark#1132]
I must confess I noticed this first many months ago, but only today it bothered me enough (with no other important tasks in the way) that I am reporting it. Not sure if it's actually a bug or intended.

This concerns the Twilight theme for code highlighting when reading – I don't edit on Github. It seems to affect other themes as well, however.

Before the change, non-significant tokens (normal variables) in a code file were highlighted in white while green was used for strings. At some point in time, the scheme started to show all variables in green instead and strings are now yellow.

This is the HTML of the first line in the page linked below:
```html
<span class="pl-k">import</span><span data-rgh-whitespace="·"> </span><span class="pl-s1">sublime</span>,<span data-rgh-whitespace="·"> </span><span class="pl-s1">sublime_plugin</span>
```

According to the source, it seems to me that this class should be added to strings, but is added to variables instead for me.

https://github.com/StylishThemes/GitHub-Dark/blob/f2ef8b208c862a32f5d7bafdd10d53e4774bc58e/themes/src/github/twilight.css#L57

I don't use other stylish themes. I use Refined Github, but disabling that has no effect.

* **Browser**: FireFox 77.0.1
* **Operating System**: Arch Linux
* **Link to page with the issue**: https://github.com/cockscomb/SublimeMakeExecutable/blob/master/make_executable.py
* **Screenshot**: 
![2020-06-19_01-37-51_github-dark_twilight](https://user-images.githubusercontent.com/931051/85081888-984fcc80-b1cd-11ea-8d94-e0862750603b.png)
![2020-06-19_01-42-04_github-dark_settings](https://user-images.githubusercontent.com/931051/85082087-23c95d80-b1ce-11ea-8c90-fec8ffd8662b.png)

**Comment by silverwind** [comment]
It was introduced when GH changed the syntax classes when they introduced code navigation but I think the new classes are now used all the time. Also see https://github.com/StylishThemes/GitHub-Dark/issues/1052.

**Comment by FichteFoll** [comment]
Yes, looks like the same issue to me.
