### ISSUE TITLE
Options in repo settings are not rendered correctly with recent GH design updates 

### ISSUE THREAD

**Issue by pattacini** [StylishThemes/GitHub-Dark#1133]
Hi 👋 

First of all, thank you for this superb style I've been using since quite a long while by now ✨ 

Lately, GitHub has introduced in preview an overhaul of its design as per the screenshot below:

![Annotation 2020-06-19 131132](https://user-images.githubusercontent.com/3738070/85127004-e0eba200-b22e-11ea-995c-bbcc08850fb4.png)

The GitHub-Dark comes along pretty well with this refreshed style except for how the settings options of a repository get rendered. I've provided an example in the screenshot at the bottom of the post. It appears that only one option is clearly visible, whereas all the others remain black on black.

Although the GitHub design updates are still in preview, it would be great if this could be sorted out.

Thanks in advance.

* **Browser**: Chrome Version 83.0.4103.106 (Official Build) (64-bit)
* **Operating System**: Windows 10 Pro 2004 19041.329
* **Link to page with the issue**: Repo Settings are reachable only by owners
* **Screenshot**:

![Annotation 2020-06-19 131115](https://user-images.githubusercontent.com/3738070/85126856-9407cb80-b22e-11ea-8551-e47203914336.png)

**Comment by silverwind** [comment]
See https://github.com/StylishThemes/GitHub-Dark/issues/1123. We can't support the feature preview until it is live, so you probably want to disable it for the time being or try one of the workarounds in that issue.

**Comment by pattacini** [comment]
Thanks 👍 
Sorry for multiple posting, I missed #1123
