### ISSUE TITLE
White underline on new preview navbar

### ISSUE THREAD

**Issue by 0x11DFE** [StylishThemes/GitHub-Dark#1134]
* **Browser**: All
* **Operating System**: All
* **Link to page with the issue**: On any repository
* **Screenshot**: [![Preview](https://i.imgur.com/cAKNChI.png)](https://i.imgur.com/cAKNChI.png)

Got this issue once enabled the new preview features.

[![FeaturePreview](https://i.imgur.com/Pj2vX4z.png)](https://i.imgur.com/Pj2vX4z.png)

**Comment by the-j0k3r** [comment]
this in a way is a duplicate of https://github.com/StylishThemes/GitHub-Dark/issues/1123

closing
