### ISSUE TITLE
New user profile design does not render the profile navbar completely

### ISSUE THREAD

**Issue by yg** [StylishThemes/GitHub-Dark#1135]
New user profile design does not render the profile navbar completely 

* **Browser**: Chrome
* **Operating System**: Ubuntu
* **Link to page with the issue**: All GitHub user profiles
* **Screenshot**:

![Screenshot](https://user-images.githubusercontent.com/61746440/85228110-1a730780-b3ff-11ea-89fa-db1dd8af3f8b.png)

**Comment by yg** [comment]
The same happens in repo page too

![Screenshot](https://user-images.githubusercontent.com/61746440/85228180-89e8f700-b3ff-11ea-9e6e-d4e1547d1b73.png)

**Comment by xt0rted** [comment]
See #1123 for issues about the design preview.

**Comment by yg** [comment]
@xt0rted I think this not addressed in #1123

![Screenshot](https://user-images.githubusercontent.com/61746440/85575913-949cc980-b655-11ea-8819-79dbec3f00cb.png)

**Comment by silverwind** [comment]
It's tracked in https://github.com/StylishThemes/GitHub-Dark/issues/1142
