### ISSUE TITLE
GitHub sponsors left navigation font color is not visible

### ISSUE THREAD

**Issue by yg** [StylishThemes/GitHub-Dark#1136]
GitHub sponsors left navigation font color is not visible

* **Browser**: Chrome
* **Operating System**: Ubuntu
* **Link to page with the issue**: https://github.com/sponsors/<username>/dashboard
* **Screenshot**:

![Screenshot](https://user-images.githubusercontent.com/61746440/85228217-d3394680-b3ff-11ea-81e1-703bdac395ae.png)

**Comment by yg** [comment]
Also happening in user settings!

![Screenshot](https://user-images.githubusercontent.com/61746440/85228414-f87a8480-b400-11ea-8e0a-3ca9e9fbc087.png)

**Comment by xt0rted** [comment]
See #1123 for issues about the design preview.

**Comment by the-j0k3r** [comment]
issue #1123 is pinned, why ppl doent read?
