### ISSUE TITLE
There is a white separator below tabs

### ISSUE THREAD

**Issue by yg** [StylishThemes/GitHub-Dark#1137]
There is a white separator below tabs

* **Browser**: 
* **Operating System**: 
* **Link to page with the issue**: 
* **Screenshot**:

![Screenshot](https://user-images.githubusercontent.com/61746440/85228354-a5a0cd00-b400-11ea-9302-0f3100878179.png)
![Screenshot](https://user-images.githubusercontent.com/61746440/85228385-cb2dd680-b400-11ea-8e6e-db70b4b29003.png)

**Comment by xt0rted** [comment]
See #1123 for issues about the design preview.
