### ISSUE TITLE
Account Settings Panel Not Contrasted Properly

### ISSUE THREAD

**Issue by wmcnamara** [StylishThemes/GitHub-Dark#1138]
* **Firefox (I have not tested on Chrome)**
* **Windows 10**
* **https://github.com/settings/profile**

![error](https://user-images.githubusercontent.com/57050262/85247767-d55dce00-b41c-11ea-8da7-fb2e8dd45e44.PNG)

Extremely difficult to view. The text on the side panel is barely visible. (Yes it is there)

**Comment by the-j0k3r** [comment]
duplicate of #1123
