### ISSUE TITLE
They added a new design

### ISSUE THREAD

**Issue by YTGamer** [StylishThemes/GitHub-Dark#1139]
They added a new design and I seen some unthemed classes. (to enable: click your pfp at top right -->Feature Preview)

Screenshot: 

![image](https://user-images.githubusercontent.com/48304290/85309948-ac3c4c80-b4b3-11ea-936f-bc24e168fc71.png)

**Comment by silverwind** [comment]
We can't support that preview until it's live but you can try workarounds like https://github.com/StylishThemes/GitHub-Dark/issues/1123#issuecomment-646759368.
