### ISSUE TITLE
The GitHub new feature version not support profile setting page

### ISSUE THREAD

**Issue by kis87988** [StylishThemes/GitHub-Dark#1140]
* **Browser**:  Chrome 83.0.4103
* **Operating System**: MacOS 
* **Link to page with the issue**:  https://github.com/settings/profile
* **Screenshot**:

![image](https://user-images.githubusercontent.com/25014776/85433492-60cc8180-b539-11ea-935c-97eaed7c4532.png)

**Comment by silverwind** [comment]
See https://github.com/StylishThemes/GitHub-Dark/issues/1123.
