### ISSUE TITLE
Notification alert close button isn't styled

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#1144]
* **Browser**: chrome 83
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/notifications view any notification you have
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/85443740-9edc9c00-b55f-11ea-8417-1a94a338f4f8.png)

**Comment by xt0rted** [comment]
Re-running an actions workflow shows an alert and this problem is there too, so it looks like all of these types of alerts have this issue.

**Comment by silverwind** [comment]
I miss this kind of stuff because I run https://github.com/StylishThemes/GitHub-Sticky-Sidebar which hides all those stick headers.

**Comment by xt0rted** [comment]
I think the change you made fixes it in all spots, at least for the blue alerts.
