### ISSUE TITLE
[New GitHub style] Is that me or the "closed" tag is a bit bright?

### ISSUE THREAD

**Issue by Geobert** [StylishThemes/GitHub-Dark#1145]
In any closed ticket, we have the red "closed" tag and I don't know if it's me or what, but it looks a bit bright for a dark theme.

**Comment by Geobert** [comment]
Same remark for the "question" label on this very ticket ^^'

**Comment by the-j0k3r** [comment]
Could be just you, rather your particular screen its settings, quality etc. Not all screens are made equal.

**Comment by Geobert** [comment]
On my 3 (different) screens, I found red-ish labels a bit too vibrant, but it looks like it's me so I'm closing :)

**Comment by the-j0k3r** [comment]
With the new redesign, the red is set at `#ff4444` by us and looks a bit too bright, maybe `#cc0000` would look less in your eyes. D

**Comment by Geobert** [comment]
I put #b94242 in a local personal style but #cc0000 is good :D 

Thanks!

**Comment by silverwind** [comment]
The red is too bright, yes. I wonder why this issue comes up now as we've been remapping that color for quite some time IIRC.

**Comment by the-j0k3r** [comment]
its the shift to the new design, because now it sticks out like a sore thumb
