### ISSUE TITLE
Primary buttons have the wrong default & hover color

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#1146]
The `:active` state is correct, but the default & hover state isn't.

* **Browser**: chrome 83
* **Operating System**: win10
* **Link to page with the issue**:
  - https://github.com/StylishThemes/GitHub-Dark/issues/new/choose
  - https://github.com/:user -> `edit profile`
* **Screenshot**:

Normal | Dark
-- | --
![image](https://user-images.githubusercontent.com/831974/85473970-073c7500-b582-11ea-8aa7-341e930ce99b.png) | ![image](https://user-images.githubusercontent.com/831974/85474145-3e128b00-b582-11ea-95c9-ac14d554437e.png)
![image](https://user-images.githubusercontent.com/831974/85474015-13c0cd80-b582-11ea-994f-2917cf11158a.png) | ![image](https://user-images.githubusercontent.com/831974/85474042-220ee980-b582-11ea-8308-9f8114fcffa6.png)
![image](https://user-images.githubusercontent.com/831974/85474386-99dd1400-b582-11ea-8fd7-2b9c19fb9dfe.png) | ![image](https://user-images.githubusercontent.com/831974/85474445-b11c0180-b582-11ea-9bdb-2bc9da3dffd8.png)

**Comment by silverwind** [comment]
Rules for `support.github.com` (which still uses old button styles) is interfering.

**Comment by the-j0k3r** [comment]
Also the gray buttons hover gray color is insanely bright, its at #404040 and it should be way more subdued, like before whacking them in the generator.
