### ISSUE TITLE
Choosing branch on comparing change page is not styled correctly

### ISSUE THREAD

**Issue by scote** [StylishThemes/GitHub-Dark#1148]
On comparing change page when we choose branch for comparaison the small popup tab have white underline which is not there on light official theme.

* **Browser**:  Chrome 83
* **Operating System**: Windows 10
* **Link to page with the issue**: 
* **Screenshot**:
![image](https://user-images.githubusercontent.com/2046218/85711332-2c7dd000-b6b5-11ea-8d14-c72aa0157fb4.png)

**Comment by the-j0k3r** [comment]
Yep because the background is the same color as the tabs, it looks broken.
