### ISSUE TITLE
Contributions calendar on Profile is back to green

### ISSUE THREAD

**Issue by MCOfficer** [StylishThemes/GitHub-Dark#1150]
* **Browser**:  Firefox 77.0.1 (64-bit)
* **Operating System**: Manjaro Lysia 20.0.3 64-bit
* **Link to page with the issue**: any profile, f.e. https://github.com/the-j0k3r
* **Screenshot**:
![image](https://user-images.githubusercontent.com/22377202/85845941-56aebb00-b7a5-11ea-9848-5ae0505c4d22.png)

**Comment by the-j0k3r** [comment]
Even the bits I fixed yesterday are broken again. Looks like GH is not using the same colors on graph and legend also... nice.
