### ISSUE TITLE
color of user icons are flipped on the Fork network pages

### ISSUE THREAD

**Issue by atsushieno** [StylishThemes/GitHub-Dark#1151]
* **Browser**: firefox 77.0.1
* **Operating System**: macos 10.14.6
* **Link to page with the issue**: for example, https://github.com/atsushieno/managed-midi/network
* **Screenshot**:

The colors of icons on the fork "network" pages are flipped, which makes lots of human face photos look weird.

For example, I'm using this icon:

<img width="66" alt="image" src="https://user-images.githubusercontent.com/53929/85891243-b6e74080-b829-11ea-9ded-4de4029d8477.png">

This works on the most pages with GitHub-Dark, but on this page it looks weird:

<img width="438" alt="image" src="https://user-images.githubusercontent.com/53929/85891077-80a9c100-b829-11ea-8f88-dda968c902f0.png">

**Comment by the-j0k3r** [comment]
There is nothing we can do but whats done, GitHub uses canvas for this and thers no way to reach it but by inverting everything.

See #583 #961 #1108 #1125

**Comment by atsushieno** [comment]
Ohh, okay. Fair enough.
