### ISSUE TITLE
Initialize repo bug on protocol switch button

### ISSUE THREAD

**Issue by tobimori** [StylishThemes/GitHub-Dark#1153]
* **Browser**: Chrome 83
* **Operating System**: Windows 10 2004
* **Link to page with the issue**: Create a repository that isn't initialized yet
* **Screenshot**: ![](https://user-images.githubusercontent.com/29142128/85931975-80143780-b8c8-11ea-878f-01fd9384783d.png)

**Comment by the-j0k3r** [comment]
and also 
![Capture](https://user-images.githubusercontent.com/31389848/85940025-479d4980-b91a-11ea-95bf-668bb2233e56.PNG)

at e.g. https://github.com/StylishThemes/GitHub-Dark/pull/938
