### ISSUE TITLE
Issue and pr views are partially styled on mobile now

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#1158]
This started early this morning for me where parts of the issue/pr pages (including the pr diff view) aren't styled now. I don't think this was due to a change on our end after looking through the recent commits but I could have missed one. This is the dedicated mobile view, not the responsive view.

* **Browser**: kiwi browser
* **Operating System**: Android 10
* **Link to page with the issue**: any issue or pr
* **Screenshot**:

![Screenshot_20200629-172222](https://user-images.githubusercontent.com/831974/86057751-c040fa80-ba2d-11ea-90b0-549f80fff9f3.png)

**Comment by the-j0k3r** [comment]
This may have been when stuff was moved from `$background` to `$color`

**Comment by xt0rted** [comment]
Looks like issue pages are fine now, but prs are still broke. I think it's due to the generator looking at https://github.com/StylishThemes/GitHub-Dark which no longer has a dedicated mobile view so we're not picking up the mobile stylesheet. Pointing that to a pr should hopefully fix it.
