### ISSUE TITLE
Gist search box gaining focus looses bottom border radius

### ISSUE THREAD

**Issue by LunarTwilight** [StylishThemes/GitHub-Dark#1162]
When you go to gist.github.com and focus on the search box in the top left, the bottom of the box looses its border radius (ignore the box inside the search box, thats #1121) 

* **Browser**: Chrome
* **Operating System**: Windows 10
* **Link to page with the issue**: https://gist.github.com
* **Screenshot**: 
![chrome_2020-07-02_21-06-26](https://user-images.githubusercontent.com/13520392/86433926-76b01400-bca8-11ea-994c-617ee2f494bb.png)

Seems to be due to the element gaining the `focus` class, which then gets affected by the following CSS:
![chrome_2020-07-02_21-06-00](https://user-images.githubusercontent.com/13520392/86433947-8f202e80-bca8-11ea-80b1-7009e4cf5c1a.png)

**Comment by the-j0k3r** [comment]
The issue it seems is https://github.com/StylishThemes/GitHub-Dark/blob/d7211b8a031318643a6538b9c445446697b0b117/github-dark.css#L25602-L25604

FYI if you want radius revert style see https://github.com/StylishThemes/Feature-Override-Styles/blob/master/github-custom-border-radii.user.css

**Comment by the-j0k3r** [comment]
Ill publish my personal upstream GitHub fixes script which also fixes the double border, will link later

**Comment by silverwind** [comment]
This is a GitHub bug.

<img width="256" alt="image" src="https://user-images.githubusercontent.com/115237/86453263-ca107980-bd1d-11ea-81c2-f96a74f7d205.png">

**Comment by the-j0k3r** [comment]
@silverwind OP read again

**Comment by silverwind** [comment]
Looks like GH finally fixed this.

**Comment by the-j0k3r** [comment]
>Looks like GH finally fixed this. There's still a border-radius bug in the dropdown thought 😆.

You are thinking about  https://github.com/StylishThemes/GitHub-Dark/issues/1121

This issue had nothing to do with that.

**Comment by silverwind** [comment]
Indeed. Bottom left and right corners of the dropdown, but it's a GH bug of course.

![image](https://user-images.githubusercontent.com/115237/88300211-8351e600-cd03-11ea-8a81-af85c9120b93.png)

**Comment by the-j0k3r** [comment]
@silverwind see https://github.com/StylishThemes/GitHub-Upstream-BugFixes for a collection of fixes all over GH, most unfixed for years

**Comment by silverwind** [comment]
Thanks. These border radius bugs are all over the place recently. The quality of GitHub is really going down the drain lately. You should add that style to the README.

**Comment by the-j0k3r** [comment]
Any more such upstream issue fell free to report to the repo, its not even hard to contribute.

Will add to readme. When I have a few. ;)

>The quality of GitHub is really going down the drain lately

It certainly doesnt help, TBH I should really start looking at submitting fixes upstream if I weren't so dammed busy and OCD'ed
