### ISSUE TITLE
contact page sign out button hover

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#1164]
* **Browser**:  ff 78
* **Operating System**: win 10 pro 
* **Link to page with the issue**: https://support.github.com/contact
* **Screenshot**:

![generic](https://user-images.githubusercontent.com/31389848/86509673-eb3e9c00-bde9-11ea-9809-55533b0ed821.gif)

Essentially the issue is with our generated styles. In particular this...

https://github.com/StylishThemes/GitHub-Dark/blob/161d652e8feed789bb557e45968d343ce66d4d0b/github-dark.css#L7003-L7008

Again @silverwind this seems like `$color` generator issues, its getting to be a lot of issues I find related to `$color` breaking things all over.

https://github.com/StylishThemes/GitHub-Dark/blob/161d652e8feed789bb557e45968d343ce66d4d0b/tools/generate.js#L42.

IMO either this `$color` needs to be a lot smarter or removed.

**Comment by the-j0k3r** [comment]
This is not the only overly specificity manipulation that causes issues, With the exception of border I find issues relating to $color all over. Just no time to work on workarounds or report all issues I find.

**Comment by silverwind** [comment]
It's related to a removal of `color: #fff` which we had earlier. It's one of the colors one does not want to invert so maybe it'll give a few false positives but I'm optimistic.
