### ISSUE TITLE
Generator: revert $color or make it smarter or fix it.

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#1166]
According to @silverwind `$color` is supposed to work more like `$value` see https://github.com/StylishThemes/GitHub-Dark/commit/6e8fc59076d88f9d0f0dbd2e4ca1a986e339d16c#comments

Whatever this is supposed to be is causing conflicts between `$background` and other plain `color` there are several issues reported inline on commits and on issue tracker that I cant track to this `$color`

this `$color` is also generating things that shouldnt be generating like 

https://github.com/StylishThemes/GitHub-Dark/blob/161d652e8feed789bb557e45968d343ce66d4d0b/github-dark.css#L10119-L10121

So my request is to revert or fix these changes. Clearly its not working out and aside from being buggy its frustrating to work with it.

@silverwind 

cc @xt0rted

**Comment by the-j0k3r** [comment]
On another note, the remap comments ceased to be helpful

https://github.com/StylishThemes/GitHub-Dark/blob/161d652e8feed789bb557e45968d343ce66d4d0b/github-dark.css#L39

It use to be that we had clear comments of which properties were being replaced, if it was background or border or color xyz, now its just the end color, not helpful.

All in all, trying to make the comments minimal is a good idea, but to the detriment of it being helpful.

**Comment by silverwind** [comment]
`$color` generally works from my testing and should be a boon to us so we can have less generator rules to replace a single color. What probably does not work correctly is the precedence over other rules like `$border`, `$background` and `$box-shadow` (those should have priority to allow more fine-grained mappings, e.g. `$border: blue` should have priority over `$color: blue`.

`$border` recently got some treatment to only emit a minimal longhand replacement rule. That is not in place yet for `$background`, that's why you see shorthands being emitted like above. I will fix that soon.

**Comment by the-j0k3r** [comment]
I dont think so, I notice things like https://github.com/StylishThemes/GitHub-Dark/issues/1164 and other issue I reported recently all tied to this.

**Comment by the-j0k3r** [comment]
this is re: https://github.com/StylishThemes/GitHub-Dark/pull/1184 and other issue re: `$color`

I now understand why this is causing so many issues, especialy around buttons but not exclusively.

The generated properties for the value are OK for some rules/classes and break another, this will never be able to be a sustainable model unless the issue is fixed.

the PR #1184 is a perfect example, by looking at the diff you see the issue exactly.

**Comment by silverwind** [comment]
Ideally I want to use only `$color` rules that act as a lightness inversion. That ought to get us 90% of the way and the rest is manual override styles that fix those issues like those too-light borders seen recently.

Button's are not "broken" but I do agree that we can tweak them a bit, especially the disabled state is a bit too prominent currently.

**Comment by the-j0k3r** [comment]
>That ought to get us 90% of the way and the rest is manual override

That estimate is grossly overstated, the truth is that misusing $color for everything causes most harm than good.

Then it raises the question, why generate something thats is wrong when we could simply ignore it and manually override it because we must in that case.

Then theres the questions of duplicates for different sections both valid and invalid, style is 50K lines and growing, its a memory hog when editing in Stylus because one must check the fixes and tweak on the fly.

What I would like is a more direct approach to replace border color replace borders, to replace bg replace a bg and color for color, blindly replacing every occurrenceof the value  leads to the huge 50k ++++

But Im sure Im just imagining things ;)

**Comment by silverwind** [comment]
> misusing $color for everything causes most harm than good.

I don't get your complaints. Lightness Inversion is the best method we have for automatic generation and it keeps the spirit of the original theme. Any custom rule will divert from that original spirit, but it is sometimes necessary because we support things like textured backgrounds.

Most cases that already "look right" in the original style will be properly handled with the inversion. Take for example the unread notification: Background is already different in the original style so this is something easily covered by the generator.

**Comment by the-j0k3r** [comment]
> Any custom rule will divert from that original spirit, but it is sometimes necessary because we support things like textured backgrounds.

I dont do custom rules, well unless I cant help it, rare these are from me.
I only use CSS classes and rules found in default stylesheet for overrides.

As for lightness inversion, this is not what I see in the diffs proff is in the pudding.

> Most cases that already "look right" in the original style will be properly handled with a inversion. Take for example the unread notification: Background is already different in the original style so this is something easily covered by the generator.

Yes lets, covered by generator OK covered by $color in generator chaos will ensue in unrelated rules. For which you will turn a blind eye because of the way its designed. Its your baby I get it.

Only you, though thinks its OK to generate classes with wrong values because were targeting something unrelated and dont see this is convoluted and backwards, because its a bludgeon and it could be a scalpel.

And the duplicates, did I mention the duplicates?

>I don't get your complaints

And I dont get why you dont get them. =)

Things need to be handled sensibly and your approach is a big nuke button that you keep pressing.
