### ISSUE TITLE
Support support sites

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#1168]
When visiting https://github.com/contact/dmca (this is not about the dmca link its an example to get to this menu) we see

![Capture](https://user-images.githubusercontent.com/31389848/86526192-f26cb500-be90-11ea-991b-cc6480856776.PNG)

The premium and enterprise support links lead to unstyled WHITE pages.

https://premium.githubsupport.com/

https://enterprise.githubsupport.com/hc/en-us/requests/new

Adding the domains to GHD reveals only partially supported styling, so needs specific @-moz-doc section for both to style remainder manually.

**Comment by xt0rted** [comment]
I wouldn't bother with these. They're just going to add more cruft to the style that's already broken due to the lack of document sections. I think we should remove http://support.github.com/ too because there's pages on there that aren't fully styled due to the style sheets only being used on specific pages when you're logged in and viewing tickets. I've set Stylus to ignore this site for now.

**Comment by the-j0k3r** [comment]
Yea if you remove that, then we need a separate style, Im not blinding myself

Im not sure why removing stuff is even a solution. thats not and should not be an issue to support pages like this.

Also

![Capture](https://user-images.githubusercontent.com/31389848/86526448-783e2f80-be94-11ea-82c9-47334bb2b1fa.PNG)

I dont want to add more styles to fix GItHub Dark related crap. I want less styles and as is, if I dont have all these, yea its a worst mess.

**Comment by the-j0k3r** [comment]
https://github.com/StylishThemes/GitHub-Dark/issues/1169 opened, That is what we should be doing, not removing needed basic stuff.

**Comment by silverwind** [comment]
I'm for supporting such off-sites in the main style but I would hold back on adding more until we have the generator output separate `@-moz-document` rules or alternatively add them with a prefix. Certainly don't include unprefixed off-site as they are bound to interfere with other site's styles.

**Comment by silverwind** [comment]
I think actually it's probably not worth styling these rarely visited sites. You style them once and then not visit them for years after which they are subtly broken. Seen that pattern too many times now. I think we should keep to the "core" sites of github only.

**Comment by the-j0k3r** [comment]
I disagree sorry.

**Comment by xt0rted** [comment]
GitHub will be getting an official dark theme "soon" but I'm not sure how deep that will go. They have a lot of small sites that are all different versions of Primer, but it'd be nice if it made it to most of them.

**Comment by silverwind** [comment]
Looking forward to that. Hope they do a proper job so we can lay this repo to rest 😉
