### ISSUE TITLE
Move supported extensions to OWN style/repo.

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#1169]
**Describe the change you'd like**

Move https://github.com/StylishThemes/GitHub-Dark#supported-github-extensions to own style

**Additional context**

We should support basic Github stuffs and pages, remove these edge cases to own style will make things cleaner and more manageable.

Also see https://github.com/StylishThemes/GitHub-Dark/issues/1168

We should support directly basic pages for most users, secondary is extensions (does any of us actually use these?) I dont. And even if we use 1 of those extensions we still generating all the stuffs related to those others.

IMO in this OWN repo for these ASAP.

**Comment by the-j0k3r** [comment]
See https://github.com/StylishThemes/GitHub-Dark/pull/1171

**Comment by silverwind** [comment]
I do use the notifications preview, but nothing else. The issue I see here that it'll be more work setting up the additional repo (e.g. actions for automatic publishing) and the fact that my Stylish popup menu needs to scroll to show all enabled styles.

**Comment by the-j0k3r** [comment]
Its already setup, just need to fix one issue.

**Comment by the-j0k3r** [comment]
Actually last commit and repo https://github.com/StylishThemes/GitHub-Dark-Extensions seems fully operational and closed StylishThemes/GitHub-Dark-Extensions#1, just made no releases yet.

**Comment by silverwind** [comment]
Automated release could not have worked without a SSH key in `DEPLOY_KEY` and the matching public key added for write access as a deploy key. I've configured that now. For the record, you can generate such a keypair using `ssh-keygen -t ed25519 -a 100`.

**Comment by the-j0k3r** [comment]
Excellent, thx.

I dont think we want to do any releases for that repo yet, or do we?, I wanted to push more commits into here for fully removing octotree and other manual styles we have for some extensions.

When this is merged then we could do releases there too. But I guess given the nature of this, it doesn't have to be so.

**Comment by the-j0k3r** [comment]
Now the sections are split into files, we should look at PR #1171 

soon as I manage to now find needles in a haystack.

**Comment by the-j0k3r** [comment]
@silverwind if you pull in branch https://github.com/StylishThemes/GitHub-Dark/tree/separate-extensions and run ANY of the make commands, the extensions file is not removed/updated and the usercss does not change.

I suppose that would be true about any other removal of sources from NOW new rules.js

**Comment by silverwind** [comment]
I think I will actually adjust the tooling to just create a second `.user.css` file in this repo, should not be too hard and I vastly prefer to have addon styles in the same repo.

**Comment by silverwind** [comment]
Also, extraction of extension styles is a breaking change to all current users who have extensions installed. I don't think it's worth it.

**Comment by the-j0k3r** [comment]
> Also, extraction of extension styles is a breaking change to all current users who have extensions installed. I don't think it's worth it.

this should never be a reason to not do something.



> I think I will actually adjust the tooling to just create a second `.user.css` file in this repo, should not be too hard and I vastly prefer to have addon styles in the same repo for ease of maintenance.

That would also be an acceptable solution.

**Comment by the-j0k3r** [comment]
Ive archived the extensions repo in meanhwile to stop ppl from using it, pita cause we cant dev to it either

**Comment by the-j0k3r** [comment]
closing since no interest anymore to pursue this.
