### ISSUE TITLE
Broken backgrounds due to $color

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#1170]
* **Browser**: 
* **Operating System**: 
* **Link to page with the issue**: 
* **Screenshot**: https://developer.github.com/v3/actions/secrets/ and a gazillion other pages with similar breakages. 

![Capture](https://user-images.githubusercontent.com/31389848/86566140-7003f400-bf69-11ea-8484-2a785261e9b3.PNG)

mis-generated as:

https://github.com/StylishThemes/GitHub-Dark/blob/3b5976df9fdcbdc7f1f19026621d39f2ff9fab8f/github-dark.css#L1862-L1868

the `background: -webkit-linear-gradient(#213, #f6f1ff);` is not in generator $color is retrieving properties from default stylesheet and screwing up the second value of this.

https://github.com/StylishThemes/GitHub-Dark/blob/3b5976df9fdcbdc7f1f19026621d39f2ff9fab8f/tools/generate.js#L117

Again, why does the generator think this is OK, if we havent told the generator to replace this value it shouldn't exist

Overly complicated, replacements on a 1:1 basis are ideal IMO, trying to be too clever is confusing for anyone.

and why are we retrieving `-webkit-linear-gradient` anyway, the world is not owned by Google chrome.

**Comment by silverwind** [comment]
This was a trivial fix, one half of the gradient was covered by the generator, the other not. `$color` replaces anywhere so it even replaces half a gradient if it has to 😉 (and I think this is fine).
