### ISSUE TITLE
docs. not found page unstyled notification blue text

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#1173]
I can track this to a 

* **Browser**: ff 78.0
* **Operating System**: win 10 pro
* **Link to page with the issue**: e.g on purpose https://docs.github.com/en/tickets/personal/0
* **Screenshot**:

![Capture](https://user-images.githubusercontent.com/31389848/87072892-d06e8c00-c21c-11ea-9cfa-cd779794b8db.PNG)

https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L10535-L10538

removing .d-lg-flex fixes the issue.

also in pages like https://docs.github.com/en that works but removing `.d-lg-flex` fixes the issue and doesnt seem to break anything.

I can also add a manual override in the moz rule that we already have for this site.

**Comment by silverwind** [comment]
The prefix is no longer present. I'll work on splitting up to multiple generated sections to get rid of these issues once and for all.

**Comment by silverwind** [comment]
Fixed in https://github.com/StylishThemes/GitHub-Dark/commit/36297b1c027cfed85f4c73f0eec5eeef9ba35a00.
