### ISSUE TITLE
make generate/build no longer generates a github-dark.css

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#1174]
@silverwind have you removed github-dark.css already, the file is still in main repo and build scripts still point to it though.

Problem because Im trying to rebase #1171 and rebuild the commit due to major changes and to add more related CSS to those commits

It isnt because there arent differences, I removed all the extensions from generate.js committed that and ran make generate, 

expected the removed generated portions to be reflected on both usercss and css files

Pls advise

**Comment by silverwind** [comment]
Nothing should have changed in that regard, generator still writes `github-dark.css` and usercss is only written on release.

**Comment by the-j0k3r** [comment]
See gif

![generic](https://user-images.githubusercontent.com/31389848/87137510-50d4d180-c29d-11ea-9d44-2f0511c4f8e3.gif)

removed protion in gen

make generate does ziltch now here.

**Comment by the-j0k3r** [comment]
Also if I run `make build` the resulting usercss version DOES not have anything removed

lol

**Comment by the-j0k3r** [comment]
on an unrelated note ALL extensions ONLY CSS is outputted to `@-moz-document domain("github.com"), domain("gist.github.com")`

So lol wtf, how come theres no other CSS generated for github.com

Weee.

**Comment by the-j0k3r** [comment]
I have a theory, because all the extensions css is generated into `@-moz-document domain("github.com"), domain("gist.github.com")` removing the generator portions doesnt remove any of it cause it wont remove the sections which would be empty otherwise.

Maybe Im wrong, but makes sense why it causes this issue.

**Comment by the-j0k3r** [comment]
@silverwind have you tested the scenario out yet?

**Comment by the-j0k3r** [comment]
@silverwind if you pull in branch https://github.com/StylishThemes/GitHub-Dark/tree/separate-extensions with only https://github.com/StylishThemes/GitHub-Dark/pull/1171/commits/35b05790e03b03fd7a71374fc5672607f7ed8dad and run ANY of the make commands, the extensions file is not removed/updated and the usercss does not change.

I suppose that would be true about any other removal of sources from NOW new rules.js

Is this wanted behavior?

**Comment by silverwind** [comment]
I'm sorry but I think you may want to fork off master again now with all the changes. Removal of extensions is just removal in `rules.js` and `extensions.css` but overall I'm still not really sold of extracting the extensions, would probably prefer to keep them.

**Comment by the-j0k3r** [comment]
> I'm sorry but I think you may want to fork off master again now with all the changes.

I have tried, its not a fork its a branch

>Removal of extensions is just removal in rules.js and extensions.css

So you need to manually remove the extensions.css file? Im not getting clear answers here.

**Comment by silverwind** [comment]
Issue is two separate repos is additional work I'm not really interested in doing. There seems to be no real performance issue, even with a 1.5MB style so I guess I prefer to keep extension here.

**Comment by the-j0k3r** [comment]
There is a performance issue when you use stylus to test and write fixes.

**Comment by the-j0k3r** [comment]
closing clearly its the way it is now when removing sections
