### ISSUE TITLE
Custom background image doesn't work

### ISSUE THREAD

**Issue by AlphaKennyBudy** [StylishThemes/GitHub-Dark#1176]
My custom background image doesn't appear on the github. I tried just an URL and `url("URL")`

* **Vivaldi**: 
* **Windows 10**: 
* **All pages**: 
* **![image](https://user-images.githubusercontent.com/48881444/87227017-a7373280-c3b9-11ea-8511-a32bc2fc6cdc.png)
**:

**Comment by the-j0k3r** [comment]
You should take the image and base64 convert it then use url("base64encwhavever")

**Comment by silverwind** [comment]
I think I see this too, now I just need to untangle that messy way we set backgrounds.

**Comment by the-j0k3r** [comment]
custom bg works just fine, using base64, vivaldi side IDK

**Comment by silverwind** [comment]
Actually I think this is some kind of Stylus bug. I can't get http-based background to work. What does work is `url(data:image/png;base64,...)`. You can use tools like https://onlinepngtools.com/convert-png-to-data-uri to get a image into that format.
