### ISSUE TITLE
Why does this style apply to every website?

### ISSUE THREAD

**Issue by Bauke** [StylishThemes/GitHub-Dark#1177]
I noticed just now that GitHub Dark applies to every website I visit (even after reinstalling it, every site shows it in the extension badge). Is that intentional and if so, why?

**Comment by the-j0k3r** [comment]
Cannot duplicate issue, refer to https://github.com/StylishThemes/GitHub-Dark#installation

If this is not how you installed then explain, give more details, links screenshots etc.

**Comment by tophf** [comment]
It happens because of 71f4718f56cedb0ab9a38e90a33ce9a43c67e02e, now it inserts these variables on every URL.

**Comment by Bauke** [comment]
@the-j0k3r, yeah I installed it via the `.user.css` link from there. From what I can tell @tophf is right and it's inserting those variables in `:root` everywhere.

**Comment by DianaNites** [comment]
Having this issue too, stylus says it's active on every site.

**Comment by silverwind** [comment]
Right, those vars should be fenced off.
