### ISSUE TITLE
"You're sponsoring..." text box has white background

### ISSUE THREAD

**Issue by tobimori** [StylishThemes/GitHub-Dark#1178]
* **Browser**: Chrome 76
* **Operating System**: Windows 10
* **Link to page with the issue**: Any sponsors page after you started sponsoring someone
* **Screenshot**: ![](https://user-images.githubusercontent.com/29142128/87424371-1f7d3e00-c5dc-11ea-8fef-c3c340bef3e8.png)

**Comment by tobimori** [comment]
![image](https://user-images.githubusercontent.com/29142128/87424598-86025c00-c5dc-11ea-93bf-9cf0122db516.png)

**Comment by the-j0k3r** [comment]
mm odd I cant see this box myself but we already style 

.Box-header {```css
    background-color: #222;
  }
```

Are you sure your style is up-to-date?

[Click here](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.user.css?raw=true) to force update.

**Comment by tobimori** [comment]
Yes, as you can see in the screenshot it's getting overwritten by inline-styles.

**Comment by the-j0k3r** [comment]
Whats overriding is an inline style

![Capture](https://user-images.githubusercontent.com/31389848/87425919-c06cf880-c5de-11ea-8565-990626cb757c.PNG)

![Capture](https://user-images.githubusercontent.com/31389848/87425973-d4b0f580-c5de-11ea-9194-2d1d9eda138f.PNG)

They could have just inlined the border color, but hey.

Not hard fix but bare with me., I dont have time atm.

**Comment by tobimori** [comment]
The color choice for the border feels kind of weird.
![image](https://user-images.githubusercontent.com/29142128/87799580-b0a71b80-c84d-11ea-882d-a9431c16627d.png)

**Comment by the-j0k3r** [comment]
We have that color `#c49` or `#e6b` pick one

**Comment by tobimori** [comment]
Opacity seems fine way, would make it grayscale tho.
![image](https://user-images.githubusercontent.com/29142128/87803152-683e2c80-c852-11ea-8bec-2aec5b9ca394.png)

**Comment by the-j0k3r** [comment]
pink to gray, hmmm, I suppose in this case.

**Comment by the-j0k3r** [comment]
upgrade to v2.2.14 by force update because you edited the style, local edits block updates

**Comment by tobimori** [comment]
I'm on 2.2.16 but it didn't change.
![image](https://user-images.githubusercontent.com/29142128/87872909-f9c9ad80-c9bc-11ea-88b3-bf48bec41da4.png)
