### ISSUE TITLE
Dependency badge isn't working in the readme

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#1182]
The dependencies badge says `inaccessible` and links to a 502 error page. Should this be kept or updated to something that works?

![image](https://user-images.githubusercontent.com/831974/87716538-f7791080-c77c-11ea-956e-c9069cf092fa.png)

**Comment by the-j0k3r** [comment]
Its an issue with https://david-dm.org/ unrelated to badge.

![Capture](https://user-images.githubusercontent.com/31389848/87719860-573ede00-c7b4-11ea-9bc8-e09915f3eb32.PNG)

**Comment by the-j0k3r** [comment]
All back to normal, servers going down happens.

https://david-dm.org/StylishThemes/GitHub-Dark?type=dev works NOW
