### ISSUE TITLE
Text in page types on a search page is unreadable

### ISSUE THREAD

**Issue by mixtur** [StylishThemes/GitHub-Dark#1183]
* **Browser**: 
Google Chrome 83.0.4103.116
* **Operating System**: 
Ubuntu 18.04
* **Link to page with the issue**: 
https://github.com/webpack/webpack/search?q=hmr&unscoped_q=hmr
* **Screenshot**:
![image](https://user-images.githubusercontent.com/2968077/87772510-84c66e80-c82a-11ea-853d-7146b3cc5fbc.png)

**Comment by the-j0k3r** [comment]
Thanks for the report, howver cannot duplicate with current version of GHD.


Click https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-dark.user.css to force update

**Comment by the-j0k3r** [comment]
If its still an issue with latest GHD after its been force updated, please re-open,
