### ISSUE TITLE
Readme has a different black background

### ISSUE THREAD

**Issue by CumpsD** [StylishThemes/GitHub-Dark#1187]
Take a look at: https://github.com/CumpsD/second-brain/blob/main/Dodge%20RAM/Carbon%20Wrap%20Console.md

![image](https://user-images.githubusercontent.com/1201644/87886409-e6e6c580-ca1c-11ea-9747-c5f4aa49dba0.png)

The markdown body of the readme has a different black than the page.

This seems to come from `#readme .markdown-body`

* **Browser**: Chrome Version 84.0.4147.89 (Official Build) (64-bit)
* **Operating System**: Ubuntu

**Comment by the-j0k3r** [comment]
All readmes.

You can thank @silverwind https://github.com/StylishThemes/GitHub-Dark/commit/0305de9b8b347a810c25319b183083210ed9d289#diff-6c6331d530703d2e5a5618a39a83caef for choosing colors that break this and custom backgrounds.

To avoid conflicts between my styling choices and his, Ill let this issue be resolved by him.

**Comment by the-j0k3r** [comment]
in the meanwile you can use this hack 

```css
	#readme .markdown-body {
		background: inherit !important
	}
```

Dont forget that if you edit the style locally it overrides auto updates, when fix is commmited you need to force update manually.

**Comment by the-j0k3r** [comment]
OK turned out it can be fixed by removing older manual rules see https://github.com/StylishThemes/GitHub-Dark/commit/ccf0ea3268ad664b72c1f0632279ac3522311b60 if interested

**Comment by CumpsD** [comment]
Thanks :) I'll wait till the update comes, it's not killing me ;) If I update manually I'll forget in the future

**Comment by the-j0k3r** [comment]
v2.2.18 is out includes the fix

**Comment by CumpsD** [comment]
Awesome, fixed, thanks!
