### ISSUE TITLE
What exactly changed between v2.1.36 and v2.2.0 and why the github-dark.css file is no longer available?

### ISSUE THREAD

**Issue by simov** [StylishThemes/GitHub-Dark#1190]
I'm using my own extension to load this theme. Up until recently I was able to copy/paste the contents of `github-dark.css` into my local file and get it working only with some minor quirks here and there.

Now by using `github-dark.user.css` things got a bit more out of hand than expected so this got me thinking.

My extension doesn't support the `@-moz-document` thing so that might be it, but I was just curious why the other file was dropped.

**Comment by the-j0k3r** [comment]
That file is no longer available, we build it from https://github.com/StylishThemes/GitHub-Dark/tree/master/src

>My extension doesn't support the @-moz-document

IDK, even `github-dark.user.css` used `@-moz-document` sections. You maybe talking about the usercss meta

I suggest you use stylus for best user experience 

Else you could get the user.css and remove this part https://github.com/StylishThemes/GitHub-Dark/blob/master/src/template.css

it should be the same as before.

**Comment by simov** [comment]
Yes I lost some colors definitely. I'll try to figure something out, thanks :+1:

**Comment by silverwind** [comment]
`github-dark.css` became unmanagable because it included a lot of autogenerated CSS and was a pain to edit because of that, so we split it up into multiple sources in the `src` directory.

`github-dark.user.css` is the final compiled file. Difference to the old `github-dark.css` is that it now builds on the usercss format variables and no longer provides fallbacks.

`@-moz-document` certainly was in the previous file too.

**Comment by simov** [comment]
Got it, thanks for the feedback. Definitely my issue right now is with missing defaults then. I'm just stripping the `@-moz-document` lines and include everything, it works for the most part.

**Comment by the-j0k3r** [comment]
So you need to do this everyday since thats how often we make new releases.

Better you than me =)

**Comment by simov** [comment]
Yeah, I'm feeling left out definitely, but I got the point no worries.

**Comment by the-j0k3r** [comment]
We are all left out these days, so dont feel bad.

You do have options like using stylus.
