### ISSUE TITLE
Text color and background-color is same

### ISSUE THREAD

**Issue by AdriBloober** [StylishThemes/GitHub-Dark#1191]
* **Browser**: Chrome 
* **Operating System**: Linux
* **Link to page with the issue**: https://github.com/login/oauth/authorize?*****
* **Screenshot**: 
https://screen.adribloober.wtf/agVal7l0UuHdAubvuXc4/2020-07-23-200348_500x778_scrot.png

The "read-only" for Organizations & Teams has the color: rgb(68, 68, 68) and the background #444.
You can't read the "read-only" because these colors are the same.

**Comment by the-j0k3r** [comment]
Can you please grab the HTML for that pls?

**Comment by the-j0k3r** [comment]
found it

![Capture](https://user-images.githubusercontent.com/31389848/88390912-77286000-cdb9-11ea-8ecb-60c1f6a1d74c.PNG)

**Comment by the-j0k3r** [comment]
In future when reporting issues, consider that people fixing it have to be able to duplicate or know what css rules are affected.

A 2 minute fix turned into a full out hunt not all apps trigger this exact menu, Our time is valuable.

Thanks for your consideration in future.

Your friendly neighborhood Bat watcher. Joker ;)

**Comment by the-j0k3r** [comment]
In future when reporting issues, consider providing more relevant information
Whoever is fixing it, has to be able to duplicate or know what css rules are affected.

Thanks for your consideration in future.

Your friendly neighborhood Bat watcher. Joker ;)
