### ISSUE TITLE
.line-comments .inline-comments have broken background

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#1194]
* **Browser**: 
* **Operating System**: 
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/commit/9ba315de954aebbd6780a36b74891326ba40eb10
* **Screenshot**:

![generic](https://user-images.githubusercontent.com/31389848/88484098-88659e00-cf6c-11ea-9eaa-09159f8ee0b3.gif)

I cant find where the bg is being removed/modified but it is. this is a recent breakage.

**Comment by silverwind** [comment]
Yes, I recently ripped out huge block of legacy background definitions, a few such issues are expected.

**Comment by the-j0k3r** [comment]
and more broken https://github.com/StylishThemes/GitHub-Dark/blame/master/src/main.css

**Comment by silverwind** [comment]
Fixed in https://github.com/StylishThemes/GitHub-Dark/commit/8679c7f752fc84e8dd943967958be29a053bc802 and properly applied theme background as well.
