### ISSUE TITLE
Sub-heading in GitHub Guides isn't styled

### ISSUE THREAD

**Issue by Geeyun-JY3** [StylishThemes/GitHub-Dark#1195]
Can't see the sub-heading in GitHub Guides 
* **Browser**: Cent Browser 4.2.10.171 (64-bit) (Chromium 80.0.3987.163), Chrome 84.0.4147.89 (Official Build) (64-bit) 
* **Operating System**: Windows 10
* **Link to page with the issue**: https://guides.github.com/activities/hello-world, https://guides.github.com/features/issues (for instance)
* **Screenshot**:
![image](https://user-images.githubusercontent.com/49396421/88500646-db3a6680-cffb-11ea-81ec-2ce8baf2e067.png)

**Comment by the-j0k3r** [comment]
For some reason this stylesheet isnt picked up by our generator, even after specifically adding its source at https://guides.github.com/stylesheets/main.css

The mappings already exist so makes no difference as it cant reach it

Manual fix incoming.

**Comment by silverwind** [comment]
The guides domain is not currently in [the sources](https://github.com/StylishThemes/GitHub-Dark/blob/master/src/gen/sources.js). Maybe I'll add it later.

**Comment by the-j0k3r** [comment]
> The guides domain is not currently in [the sources](https://github.com/StylishThemes/GitHub-Dark/blob/master/src/gen/sources.js). Maybe I'll add it later.

Ive tried to add it didint work
