### ISSUE TITLE
Addition in rendered prose view of comment revision isn't styled

### ISSUE THREAD

**Issue by Geeyun-JY3** [StylishThemes/GitHub-Dark#1196]
* **Browser**: Cent Browser 4.2.10.171 (64-bit) (Chromium 80.0.3987.163), Chrome 84.0.4147.89 (Official Build) (64-bit)
* **Operating System**: Windows 10
* **Screenshot**:
![gif](https://user-images.githubusercontent.com/49396421/88506661-fb265600-d00c-11ea-8981-a64f4f6bb5ad.gif)

Insterestingly you can see what was added while unordered list is involved in changes, but looks strange…: https://github.com/StylishThemes/GitHub-Dark/issues/1195#issue-665953328 
![image](https://user-images.githubusercontent.com/49396421/88502836-50a93580-d002-11ea-9e11-d1074707f11e.png)

**Comment by the-j0k3r** [comment]
fixed 

![Capture](https://user-images.githubusercontent.com/31389848/88535456-31aea180-d00a-11ea-81c1-d9d18f7304b6.PNG)
