### ISSUE TITLE
Is missing background a bug or a feature?

### ISSUE THREAD

**Issue by Kir-Antipov** [StylishThemes/GitHub-Dark#1198]
Sometimes I come across panels that don't have a background (it's transparent) when interacting with GitHub.

I don’t know for sure if it was done on purpose or if some styles got broken due to the fact that Microsoft changed some layout elements dramatically.

----

#### First issue

![issues](https://user-images.githubusercontent.com/40232067/88696287-bcc39080-d10b-11ea-9af6-219bd7e1947d.png)

<sup>div.mb-4.js-notice &gt; pager-flow.content.p-4.text-center.rounded-1.border.border-gray-light.d-block</sup>

#### First time contributing
![contributing](https://user-images.githubusercontent.com/40232067/88695258-4d00d600-d10a-11ea-8562-5638cf093e16.png)

<sup>div.container-xl.mb-4.js-notice &gt; div.content.p-4.text-center.rounded-1.border.border-gray-light</sup>

#### Actions tip

![actions](https://user-images.githubusercontent.com/40232067/88695924-3e66ee80-d10b-11ea-8753-2feea03554e3.png)

<sup>div.p-3.border.rounded-1.box-shadow.d-flex.mx-0.mb-4.js-notice</sup>

#### You don't have any projects yet

![projects](https://user-images.githubusercontent.com/40232067/88696814-6276ff80-d10c-11ea-87e1-206e7bc51cc4.png)

<sup>div#projects-results &gt; div.blankslate.blankslate-capped.border-0</sup>

---- 

If you didn’t intend it to look like this, I have one small request: it would be very nice of you if you'll add support of old summary layout (I'm working on script that reverts terrible UI update):

![summary](https://user-images.githubusercontent.com/40232067/88698261-81769100-d10e-11ea-9059-a65b1edede8b.png)

<sup>div.repository-content &gt; div.overall-summary.border-bottom-0.mb-0.rounded-bottom-0</sup>

Something simple like this will be enough I think:

```css
.overall-summary {
    backgroud-color: ...;
}
```

**Comment by silverwind** [comment]
Those are bugs. We recently cleaned out some ancient rules and there were a few casualities.

**Comment by Kir-Antipov** [comment]
@silverwind, thank you much! :)

**Comment by silverwind** [comment]
I could probably add proper support for https://github.com/Kir-Antipov/GitHub-Defreshed if you could add a class to `html` that would allow us to style the extension only when its active. e.g. `document.documentElement.classList.add('github-defreshed')` on load.

**Comment by Kir-Antipov** [comment]
@silverwind, will do it, since I need to know if my extension has already been activated too (so it won't be reactivated). Currently I use this:

```js
if (!window.defreshed && isGitHub()) {
    window.defreshed = true;
    defresh();
}
```
But `html.github-defreshed` will be much better :)
