### ISSUE TITLE
Transparent .pr-toolbar

### ISSUE THREAD

**Issue by zmni** [StylishThemes/GitHub-Dark#1200]
* **Browser**: Edge
* **Operating System**: Windows
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/pull/959/files
* **Screenshot**:

![image](https://user-images.githubusercontent.com/841523/88990885-599f4d00-d309-11ea-8653-f177cfff238b.png)

Or any PR > files tab and scroll down.

**Comment by silverwind** [comment]
Looks fine to me, is your style you up to date?

**Comment by zmni** [comment]
Yes, currently `v2.3.16`.

The selector `.pr-toolbar.is-stuck` on [main.css#L697](https://github.com/StylishThemes/GitHub-Dark/blob/master/src/main.css#L697) seems to be overriden by `.pr-toolbar` on [main.css#L884](https://github.com/StylishThemes/GitHub-Dark/blob/master/src/main.css#L884) because of `!important` property.

**Comment by the-j0k3r** [comment]
Im able to duplicate with split view only, fix incoming.
