### ISSUE TITLE
add style for webkit scroll bar

### ISSUE THREAD

**Issue by tobimori** [StylishThemes/GitHub-Dark#1201]
It annoys me to have this kind of white, blending scroll bars everywhere on GitHub.
![image](https://user-images.githubusercontent.com/29142128/89014878-75f5b680-d316-11ea-9cbf-4e24968fe1a7.png)

**Comment by the-j0k3r** [comment]
Please use https://github.com/StylishThemes/Overlay-Scrollbars its already supported. You have a global and a github only style.
