### ISSUE TITLE
Stylus failed to parse usercss: [object Event]

### ISSUE THREAD

**Issue by MicaelJarniac** [StylishThemes/GitHub-Dark#1202]
* **Browser**:
Google Chrome
* **Operating System**:
Windows 10 x64
* **Link to page with the issue**:
https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-dark.user.css
* **Screenshot**:
![Screenshot](https://i.imgur.com/1OWMSBZ.png)

I've been using this theme for a long time now, and today I noticed it wasn't working. I then came back here to reinstall it, and it's giving me that "Stylus failed to parse usercss: [object Event]" error.

**Comment by silverwind** [comment]
Can't reproduce. Is your Stylus up to date?

**Comment by MicaelJarniac** [comment]
It started working again. I have no idea what happened, but I had opened the Stylus config, the theme wasn't listed there, I tried reinstalling the theme, it gave me that error, and today it just worked, as if nothing happened.

**Comment by the-j0k3r** [comment]
Stylus has its moments, maybe its becoming self aware!

**Comment by silverwind** [comment]
Stylus unfortunately honours http cache when loading styles. CTRL-Shift-R usually solves it.
