### ISSUE TITLE
Why was the ability to customize the font used for code removed?

### ISSUE THREAD

**Issue by dstaley** [StylishThemes/GitHub-Dark#1203]
I noticed that in v4.0.0 the ability to customize the font for code was removed. Is there a paticular reason why? Also, is there a suggested alternative to customizing the font?

**Comment by SekiBetu** [comment]
same question, i love using the font called "Jetbrains mono", after this update, i can't change the font 😢

**Comment by silverwind** [comment]
It had never fit well in a theme that's supposed to be color-only. And then there was this issue https://github.com/StylishThemes/GitHub-Dark/pull/1197#issuecomment-667643980 with the new method that we created. It can be restored as a add-on style but I don't see it having a place in the main style.

**Comment by silverwind** [comment]
Extracted font customization it to its own .user.css in this repo. Install this:

https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-custom-fonts.user.css

**Comment by SekiBetu** [comment]
> Extracted font customization it to its own .user.css in this repo. Install this:
> 
> [`master`/github-custom-fonts.user.css (raw)](https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-custom-fonts.user.css)

thx 😘

**Comment by the-j0k3r** [comment]
> Extracted font customization it to its own .user.css in this repo. Install this:
> 
> https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-custom-fonts.user.css

@silverwind, why not use feature override repo for this? It was the primary reason why it was made.

**Comment by silverwind** [comment]
I think we're better off moving everything to this repo. I find it much easier to maintain one repo instead of many. Simple styles can be added just a plain .user.css file without any build process. The version numbers will increment along with the main style.

**Comment by the-j0k3r** [comment]
> I think we're better off moving everything to this repo

So instead of adding new ones to the repo tat already exists we will have to fiddle with update urls and mess around with things so that existing users experience is unbroken,.

Sorry, I dont think thats the way to work sanely.

**Comment by silverwind** [comment]
I hear your pain. I think we can keep the Feature-Overrides repo, but I'll move the little style like tab-size and code-wrap to this repo. It's just too much work to keep the tooling on these repos up to date with the main repo for me personally.

**Comment by the-j0k3r** [comment]
Linting would be an issue too.

I also dont want to have a million repos to work with but they keep turning up.
