### ISSUE TITLE
"Mention in a new comment" has poor contrast

### ISSUE THREAD

**Issue by DanielPower** [StylishThemes/GitHub-Dark#1208]
On an issue reply, there is a button under the user's avatar to mention them in a reply. This button doesn't seem to be styled by GitHub-Dark, resulting in it being very hard to see.

* **Browser**: Firefox 80.0b6
* **Operating System**: OSX 10.15
* **Link to page with the issue**: https://github.com/fabricjs/fabric.js/issues/6517
* **Screenshot**:<img width="949" alt="Screen Shot 2020-08-12 at 5 39 06 PM" src="https://user-images.githubusercontent.com/12166320/90062755-ba903300-dcc2-11ea-8d90-e6650423ffb0.png">

**Comment by the-j0k3r** [comment]
@DanielPower thanks for the report.

I cant see this in any issue or pull request, so I have to ask if this is a feature preview you're trying out or maybe some 3rd party extension for GitHub you may have.

If its a preview we need access to it and I have no feature previews available at all (idk if other team members have access either), if its an addon we need to know which.

If you could clear that up and also if you inspect the element let us know what the css for this is.

TIA

**Comment by DanielPower** [comment]
Sorry about that, it turns out it is part of an extension, I didn't even realize that.
The feature is added by "Refined GitHub".

*Element*
```
<svg class="octicon octicon-reply" width="16" height="16" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" clip-rule="evenodd" d="M6.78033 1.96967C7.07322 2.26256 7.07322 2.73744 6.78033 3.03033L3.81066 6H10.25C12.8733 6 15 8.12663 15 10.75V13.25C15 13.6642 14.6642 14 14.25 14C13.8358 14 13.5 13.6642 13.5 13.25V10.75C13.5 8.95507 12.0449 7.5 10.25 7.5H3.81066L6.78033 10.4697C7.07322 10.7626 7.07322 11.2374 6.78033 11.5303C6.48744 11.8232 6.01256 11.8232 5.71967 11.5303L1.46967 7.28033C1.17678 6.98744 1.17678 6.51256 1.46967 6.21967L5.71967 1.96967C6.01256 1.67678 6.48744 1.67678 6.78033 1.96967Z"></path>
</svg>
```

*Styles applied to the element*
```
element {
}
svg:not(:root) {
    overflow: hidden;
}
.octicon {
    vertical-align: text-bottom;
}
.octicon {
    display: inline-block;
    vertical-align: text-top;
    fill: currentColor;
}
* {
    -moz-tab-size: 4 !important;
    tab-size: 4 !important;
}
* {
    box-sizing: border-box;
}
button.rgh-quick-mention:not(:hover):not(:focus) {
    color: inherit;
}
.btn-link {
    font-size: inherit;
    color: #0366d6;
    white-space: nowrap;
    cursor: pointer;
}
button {
    cursor: pointer;
}
button, input, select, textarea {
    font-family: inherit;
    font-size: inherit;
    line-height: inherit;
}
button, select {
    text-transform: none;
}
button, input, select, textarea {
    font: inherit;
        font-size: inherit;
        line-height: inherit;
        font-family: inherit;
}
body {
    word-wrap: break-word;
}
body {
    font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji;
    font-size: 14px;
    line-height: 1.5;
    color: #24292e;
}
:root {
    --github-green: #28a745;
    --github-red: #cb2431;
    --github-gray-background: #fafbfc;
    --github-gray-text: #6a737d;
    --github-faint-yellow: #fffbdd;
}
html {
    font-family: sans-serif;
    -webkit-text-size-adjust: 100%;
}
```

**Comment by silverwind** [comment]
Can you check in the computed style where that `color` is actutally coming from? All I see in that CSS is `color: inherit` which does not help us.

**Comment by fregante** [comment]
This was a choice I made in Refined GitHub to avoid making it too noisy. It's meant to be there if you look at it, but disappear if don't need it. The contrast is about the same in both light and dark

<img width="61" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/104139201-5d7ed300-536f-11eb-9b2b-6acf87c4ba1e.png"> <img width="58" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/104139200-5c4da600-536f-11eb-916d-329a93bc338a.png">

**Comment by DanielPower** [comment]
I no longer use GitHub-Dark since the official dark theme has been released. And i no longer use GitHub Refined. So I don't have a strong opinion.

And since as @fregante said, the contrast was intentional. So for those reasons I'm going to close this issue.

**Comment by fregante** [comment]
> And i no longer use GitHub Refined

How could you? 😱

**Comment by DanielPower** [comment]
It wasn't a conscious decision. I switched to another laptop, and didn't end up reinstalling it.
