### ISSUE TITLE
Rich diff is failing to display

### ISSUE THREAD

**Issue by runxel** [StylishThemes/GitHub-Dark#1209]
* **Browser**: Firefox 79
* **Operating System**: Windows 10
* **Link to page with the issue**: Everywhere with rich diff possibility.
* **Screenshot**:
![rich diff](https://user-images.githubusercontent.com/2277182/90388554-45d54400-e088-11ea-9ae7-ddaa1010c73a.png)

The rich diff fails to display. When I disable the user stlye it is there however.

**Comment by silverwind** [comment]
Can't reproduce [here](https://github.com/StylishThemes/GitHub-Dark/commit/d4a9711f621ca6b101b758d31df4e89ad9803e24?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8). Maybe some other extension interfering?

**Comment by the-j0k3r** [comment]
[Here](https://github.com/StylishThemes/GitHub-Dark/commit/099cf07b66e0ab8bb054d6d0823a755a4e3543e4?short_path=484798a#diff-484798ad23565464b1a45143d9b623e9)

I see this

![Capture](https://user-images.githubusercontent.com/31389848/90397205-ca7b8e80-e097-11ea-8d42-890237005820.PNG)

So Ill have to agree something local to @runxel is going on. Another style, but it would be best to test on actual page to determine exactly first hand.

**Comment by runxel** [comment]
Ah, interesting! I see it there, too, with your link @the-j0k3r.
I'm one of the maintainer of simple-icons, so let's take a random [PR](https://github.com/simple-icons/simple-icons/pull/3460/files?short_path=0372cf5#diff-0372cf58adeb160546b4fb8c2d11b53b).

For this repo it fails consistently.

@silverwind Might be the case, yeah. But where to look? What other extension might that be?
I mean: Let's say, your're right: Why does it work when I disable the styling and only the styling? ... 

Weird thing, any case 🤔

**Comment by silverwind** [comment]
Seems like a bug. Our `width: 100%, height: 100%` causes the image to collapse for some reason. I only recently reworked this part to eliminate a double border which made these width/height adjustments necessary.

Works: https://github.com/StylishThemes/GitHub-Dark/blob/099cf07b66e0ab8bb054d6d0823a755a4e3543e4/images/progressive-disclosure-line.svg
Fails: https://github.com/simple-icons/simple-icons/pull/3460/files?short_path=0372cf5#diff-0372cf58adeb160546b4fb8c2d11b53b

**Comment by runxel** [comment]
So do you think I can be circumvented?
Thanks for being so quick, btw! ❤️

**Comment by silverwind** [comment]
Yes, I suppose a workaround for SVGs that don't specifify width/height can be done. We can not generally remove the 100% rules because that would introduce a 1px right/bottom margin on other images like seen [here](https://github.com/go-gitea/gitea/commit/7cf23399a0b97cb8211e8e7b00020e9b1a5fdac1?short_path=e00f11d#diff-e00f11db70883b51bc33243dc5d0b9d5):

<img width="258" alt="image" src="https://user-images.githubusercontent.com/115237/90415281-2acafa00-e0b1-11ea-861c-cf1f21b5ab9a.png">
