### ISSUE TITLE
"Get email updates" button has not the right text color

### ISSUE THREAD

**Issue by busybox11** [StylishThemes/GitHub-Dark#1210]
* **Browser**: Chrome Beta 84.0.4147.89 (Using Stylus 1.5.13)
* **Operating System**: Debian bullseye / sid
* **Link to page with the issue**: https://github.com/explore
* **Screenshot**:
![image](https://user-images.githubusercontent.com/29630035/90423470-cca41400-e0bc-11ea-98dc-6a95d5003b86.png)

**Comment by silverwind** [comment]
That button has manual text color `#ddd`. We can make it `#fff` but we can not make it dark because the style operations on the assumption that base color is not too bright (CSS offers no way to calculate a complementary color).

**Comment by silverwind** [comment]
Maybe the button should be styled to be dark anways, it seems very obnoxious the way it is.

**Comment by the-j0k3r** [comment]
Again see https://github.com/StylishThemes/GitHub-Dark/issues/1113#issuecomment-658075241 its the same issue and its still being worked on, Nothing can or should be done in GHD because of its limitations.

**Comment by silverwind** [comment]
Increased contrast a bit by letting the default `#fff` take over color in https://github.com/StylishThemes/GitHub-Dark/commit/6a36034f15413d6c888838eb0dea7c0399d1fa0c.
