### ISSUE TITLE
white background on any version

### ISSUE THREAD

**Issue by shrek-gabe-itch** [StylishThemes/GitHub-Dark#1218]
* **Browser**: Firefox 80.0.1 release
* **Windows 10 1809**: 
* **Link to page with the issue**: everywhere
* **Screenshot**: ![Screenshot 2020-09-10 202147](https://user-images.githubusercontent.com/58945139/92753764-a1eb6980-f3a3-11ea-9a26-111940ed1a13.png)

**Comment by the-j0k3r** [comment]
Not able to duplicate disable all other styles, maybe even remove GHD and reinstall

**Comment by shrek-gabe-itch** [comment]
> 
> 
> Not able to duplicate disable all other styles, maybe even remove GHD and reinstall

disabling other styles and reinstalling doesn't help, other dark styles for gihub I've tried behave the same except one
https://userstyles.org/styles/182032/github-one-dark-theme

**Comment by the-j0k3r** [comment]
> disabling other styles and reinstalling doesn't help, other dark styles for github I've tried behave the same except one
> https://userstyles.org/styles/182032/github-one-dark-theme

I hope you're not installing GitHub Dark from userstyles website, if you are, remove it and install from https://github.com/StylishThemes/GitHub-Dark#installation

**Comment by shrek-gabe-itch** [comment]
> 
> I hope you're not installing GitHub Dark from userstyles website, if you are, remove it and install from https://github.com/StylishThemes/GitHub-Dark#installation

version from github looks broken for me, I just gave an example of the theme with which everything looks fine

**Comment by the-j0k3r** [comment]
Sorry cannot duplicate

What extension are you using? Stylus? Stylish? Other?

If the answer is anything but Stylus, then this could explain your issues.

**Comment by silverwind** [comment]
Must be something interferring, try a fresh browser profile.

**Comment by Gambloide** [comment]
**Steps to reproduce in Firefox (on Linux):**
1. Save or copy the content of https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-dark.user.css
1. Install Stylus
1. Open Stylus
1. Click `Write new style`
1. Either paste the contents of `github-dark.user.css` or use the `import` button under **Mozilla Format**

**Result:**
Exactly as seen in the screenshot pf @shrek-gabe-itch.
Why? Some placeholders do not get correctly resolved, e.g.:

``` css
-ghd-bg-custom: /*[[bg-custom]]*/;
--ghd-bg-img: /*[[bg-choice]]*/;
--ghd-bg-color: /*[[bg-color]]*/;
```

**Workaround**
1. Install Stylus first
1. Click on https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-dark.user.css
1. (At this point Stylus should have intercepted the request and be showing a custom interface.)
1. Install the style using the `install style` button

**Comment by the-j0k3r** [comment]
@Gambloide the workaround is the correct way to add this style, 

Also you need to ensure that when creating a new style in stylus, the usercss option has to be enabled.

![Capture](https://user-images.githubusercontent.com/31389848/97091276-0c4a2780-163b-11eb-9de9-1ae3277fb8e9.PNG)

if not it may explain the issues with your main method. It works just fine here FYI.

**Comment by tophf** [comment]
This is the first time I see someone incorrectly pasting a usercss code into the legacy editor. Well, there are always lots of ways to shoot oneself in the leg but I agree we should show a confirmation and switch the editor accordingly or at least explain how to do it to the user.

**Comment by Gambloide** [comment]
As someone that comes from legacy extensions where this was the approach to "install" a style, I parsed the [GitHub-Dark installation instructions](https://github.com/StylishThemes/GitHub-Dark#installation) as: (1) install extension; (2) create new style, paste css into editor, check and if required adjust scope, click apply.

    1. Install Stylus for Firefox, Chrome, Opera or Cascadea for Safari.
    2. Install github-dark.user.css.

I think https://github.com/openstyles/stylus/issues/1080 is a good idea catering to users new to Sylus and Usercss.
Though I would suggest simply linking to https://github.com/openstyles/stylus/wiki/Usercss#how-do-i-install-usercss in the [GitHub-Dark installation instructions](https://github.com/StylishThemes/GitHub-Dark#installation). The documentation has all the information covering different approaches to installing Usercss.

**Comment by the-j0k3r** [comment]
>As someone that comes from legacy extensions where this was the approach to "install" a style, I parsed the GitHub-Dark installation instructions as: (1) install extension; (2) create new style, paste css into editor, check and if required adjust scope, click apply.

We never recommended that method, the instructions should be clear as to click here or something like it use to be.

**Comment by the-j0k3r** [comment]
See the new install instructions https://github.com/StylishThemes/GitHub-Dark/commit/6481d41c82dfd540560853a233192b209f4fd2ed

Should resolve issue.
