### ISSUE TITLE
New sticky header not darkned.

### ISSUE THREAD

**Issue by mikhoul** [StylishThemes/GitHub-Dark#1224]
* **Brave**: 
* **Windows**: 
* **https://github.com/Advansoftware/IPTV/blob/master/index.php**: 
* **Screenshot**:   
![image](https://user-images.githubusercontent.com/5678673/94615238-6b539100-0275-11eb-87ba-e05b859abe8b.png)

![image](https://user-images.githubusercontent.com/5678673/94615254-727a9f00-0275-11eb-913d-71805fc19f46.png)

Since today there is a sticky header with the title of the page that is not darkned 

Also: Could it be possible to have the the sticky header optional ? 🤔

**Comment by silverwind** [comment]
I don't think that header is coming from GitHub. Maybe it's some browser extension?

**Comment by mikhoul** [comment]
Sorry, 

You are right I had an extension that after an update added a new "feature" that is not related to the main feature of the extension.
