### ISSUE TITLE
Unreadable settings

### ISSUE THREAD

**Issue by nikhilCad** [StylishThemes/GitHub-Dark#1229]
* **Browser**: Firefox v81.0
* **Operating System**:Windows 7 
* **Link to page with the issue**: https://github.com/settings/repositories
* **Screenshot**:
![github](https://user-images.githubusercontent.com/47214394/95043632-fcee5300-06fa-11eb-8bdf-e6caeaa74fbb.png)

Cant see the what is written in settings tab. Text is written in very dark tone of blue i guess

**Comment by silverwind** [comment]
Looks fine to me, is your style up to date (v4.0.92)?

**Comment by nikhilCad** [comment]
Oh that's the problem. My version of your addon is outdated. Thanks for
telling.

Pls close the issue, I am replying through email.
