### ISSUE TITLE
Commit description not darkened

### ISSUE THREAD

**Issue by guihkx** [StylishThemes/GitHub-Dark#1231]
* **Browser**: Chromium 86
* **Operating System**: Arch Linux
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/commit/0c980a937a3c2cbf39a52c9a1d93c62205f8657b
* **Screenshot**: 

![image](https://user-images.githubusercontent.com/626206/96274675-2e8ed600-0fa7-11eb-903a-d2ac84e31a4d.png)

**Comment by Vangelis66** [comment]
Just a little clarification: The bug manifests itself **only** when one is **logged-in**... 
BTW, many thanks for the developers' efforts!

**Comment by silverwind** [comment]
Seems GitHub switched to CSS vars but those are not being picked up for some reason, checking.
