### ISSUE TITLE
Repo header changes

### ISSUE THREAD

**Issue by dgw** [StylishThemes/GitHub-Dark#1236]
* **Browser**: Chrome 86
* **Operating System**: Windows 10
* **Link to page with the issue**: Any repo, really, but here 😝: https://github.com/StylishThemes/GitHub-Dark
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/164140/96404063-8859f080-119f-11eb-8e99-040b468003d9.png)

These changes happened _very_ recently, sometime in the last few hours. I was using GitHub earlier today (US Central) and everything looked fine.

Bonus: Emoji picker background is now white (lmk if this should be its own issue)
![image](https://user-images.githubusercontent.com/164140/96404184-e25ab600-119f-11eb-8c43-09346cbc49ed.png)

**Comment by rokibhasansagar** [comment]
I too just updated and saw the exact issue.

**Note: The Star Counter background became white** :disappointed: 

My System:
* **Browser**: Brave Browser
* **Operating System**: Ubuntu 20.04.1 LTS

**Comment by dgw** [comment]
Quick fix 🚀 much appreciated 🥳
