### ISSUE TITLE
Border on new issue comment is really bright

### ISSUE THREAD

**Issue by tgreen7** [StylishThemes/GitHub-Dark#1237]
* **Browser**: Chrome 86.0.4240.80
* **Operating System**: macos 10.14.6
* **Link to page with the issue**: This issue
* **Screenshot**:
<img width="937" alt="Screen Shot 2020-10-18 at 11 48 05 PM" src="https://user-images.githubusercontent.com/10415101/96410844-627f1c80-119c-11eb-94a2-737107a3f869.png">

**Comment by silverwind** [comment]
This was fixed yesterday, please update.

**Comment by tgreen7** [comment]
thanks!
