### ISSUE TITLE
Clicked menu color Bug In Github Gist

### ISSUE THREAD

**Issue by 1-EXON** [StylishThemes/GitHub-Dark#1238]
![image](https://user-images.githubusercontent.com/56220973/96451544-b5b3a680-1252-11eb-9b40-84eb0b777ff6.png)
The color of the menu clicked on the GitHub gist has changed like this.

**Comment by NaleRaphael** [comment]
Hi @1-EXON, it seems this issue has been fixed in v4.2.10 (see also commit 3222ffe). You can update it by clicking the link attached in the description of this repository.

**Comment by 1-EXON** [comment]
Oh, thank you!
