### ISSUE TITLE
All versions after 4.2.2+3-ga023b22 broken for signed-out users

### ISSUE THREAD

**Issue by Vangelis66** [StylishThemes/GitHub-Dark#1239]
* **Browser**: 360 Extreme Explorer v12 (**Chromium 78**_32-bit Chinese fork, XP+Vista compatible)
* **Operating System**: Windows Vista SP2 (build 6.0.6003) 32-bit
* **Userstyle manager**: Stylus 1.5.13 (latest)
* **Userstyle version**: 4.2.10 (latest)
* **Link to page with the issue**: https://github.com/gorhill/uBlock (sample page, happens everywhere)
* **Screenshot**: 

![360EEv12_GitHub](https://user-images.githubusercontent.com/9669492/96474445-7cbc0780-123b-11eb-9f63-641daed8f910.JPG)

The **same** page when logged-in:

![360EEv12_GitHub_in](https://user-images.githubusercontent.com/9669492/96474549-9c533000-123b-11eb-9396-0d920f2c0ac4.jpg)

 If this is a new change by design, may I humbly add that it is not welcome here... While it is true I spend a lot of time on GitHub pages, (me not being a coder) it is just to read code, learn/download stuff and I only sign-in specifically when I have to report bugs/create new issues (such as this one) and/or comment on existing issues... 

 If GHD has now turned into a GitHub-members-only style, then I wouldn't personally want to use it always signed-in, and this is also for privacy considerations, especially taking into account the practices of current GitHub owner, Microsoft (but this is a discussion suited best elsewhere...).

 Many thanks for your stupendous coding efforts developing and maintaining this userstyle, they are highly appreciated! I have now reverted to v4.2.2 of the style, until this issue is addressed further or v4.2.2. breaks to a non-usable point...

Kindest regards!

**Comment by the-j0k3r** [comment]
Nothing to do with us, GitHub switched to using CSS vars that are only exposed when logged in.

I agree this sounds unusual, maybe GH have a good reason to follow this method, I know of none, though I would personally prefer always available CSS vars no matter what status the user is.

If enough users provide feedback on this to GitHub maybe they will address it, else well have to hack around whatever is missing

**Comment by silverwind** [comment]
I had the signed-out CSS (which is completely different from signed-in CSS now because of awesome GitHub engineering) in the style but removed it because the rules were interfering each other. Maybe worth attempting to add them again.

**Comment by Vangelis66** [comment]
Huge thanks for the swift fix 🥇 ; I've updated to v**4.2.12** now and things look much saner again! Take the best of care during these difficult times... 😃
