### ISSUE TITLE
Codespaces select page not themed

### ISSUE THREAD

**Issue by ent3r** [StylishThemes/GitHub-Dark#1241]
* **Browser**: 82.0b9 (64-bit)
* **Operating System**: Windows 10 x64
* **Link to page with the issue**: https://github.com/codespaces/
* **Screenshot**: ![Screenshot of affected page](https://bug-hunters.me/279692618391093250/358c32.png)

**Comment by silverwind** [comment]
Page is intentionally not styled, but should be possible if we can discern it from the actual codespaces application.

**Comment by ent3r** [comment]
From what i've seen the codespaces application is on `github.dev`, while this page is on `github.com`. I think it should be possible to differentiate between the two

**Comment by silverwind** [comment]
Fixed. VSCode is still white while loading but I guess that's not something we want to attempt to fix.
