### ISSUE TITLE
Broken colors again

### ISSUE THREAD

**Issue by Leo40Git** [StylishThemes/GitHub-Dark#1246]
* **Browser**: Mozilla Firefox 82.0
* **Operating System**: Windows 10
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/issues/new?assignees=&labels=bug+%3Abug%3A&template=bug_report.md&title=
* **Screenshot**:
![firefox_V5vZnk90Ue](https://user-images.githubusercontent.com/7997354/97032001-c3766e00-1569-11eb-8f58-feaa0350c50d.png)

**Comment by qwertyuu** [comment]
Damn you're quick!

**Comment by Leo40Git** [comment]
Not really, I noticed that the top tabs' text color is wrong while browsing, went here to report it and got blinded by the issue preview.

**Comment by qwertyuu** [comment]
Your mouse cursor is epic btw

**Comment by Leo40Git** [comment]
I am aware 😎

**Comment by LeonardSSH** [comment]
same: 
![image](https://user-images.githubusercontent.com/35312043/97033813-341a8c00-1564-11eb-9111-e3937d0adb49.png)
![image](https://user-images.githubusercontent.com/35312043/97033845-41377b00-1564-11eb-9562-45febbc21c42.png)

**Comment by synthead** [comment]
The preview tab is extra bright :sun_with_face: 

![image](https://user-images.githubusercontent.com/820984/97034856-630c1000-151a-11eb-8dcd-f7a8f07d1fbb.png)

**Comment by htmlboss** [comment]
Fixed! Thanks ❤️
