### ISSUE TITLE
Empty context lines of diffs are unstyled and show up white

### ISSUE THREAD

**Issue by dbeckwith** [StylishThemes/GitHub-Dark#1254]
Empty context parts of diffs show up as white blocks instead of being dark.

* **Browser**: Firefox 82.0
* **Operating System**: Ubuntu 18.04
* **Link to page with the issue**: https://github.com/rust-lang/rust/pull/78516/files
* **Screenshot**:
Vanilla:
![image](https://user-images.githubusercontent.com/1279939/97589235-aa3f4880-19d3-11eb-81d3-e7c5a89105d8.png)
With GitHub-Dark:
![image](https://user-images.githubusercontent.com/1279939/97589172-985da580-19d3-11eb-9e42-06a2b20c9a01.png)

**Comment by silverwind** [comment]
Fixed by https://github.com/StylishThemes/GitHub-Dark/commit/e332b98339432b8e8fe6480e5c707f9c48c64da8.
