### ISSUE TITLE
[SOLVED] The contributions grid is partially light 

### ISSUE THREAD

**Issue by ewerybody** [StylishThemes/GitHub-Dark#1259]
Ooops. Style WAS latest already! I was just about writing this then went into the Stylus settings, cranked the color And BOOM fixed! So ... also after reload and all 🤷‍♀️ I don't know what that was.

It showed up a couple days ago was NOT so severe as THis #1252 but well kinda ugly.

* **Browser**: Firefox 83.0b9 (64-bit)
* **Operating System**: Win 10.0.19041.1
* **Link to page with the issue**: https://github.com/ewerybody
* **Screenshot**:

![image](https://user-images.githubusercontent.com/218956/98364776-af367480-2031-11eb-9f5b-141f71f2fb25.png)

![image](https://user-images.githubusercontent.com/218956/98365031-20762780-2032-11eb-9ea1-a55e03fd16c5.png)

## Solution:
• Goto **Stylus** Menu,
• click the ⚙ on **GitHug Dark** 
• click the Base Color
• crank it around or even just click the ↔ double arrow thing
• Voilà

![image](https://user-images.githubusercontent.com/218956/98365558-e5282880-2032-11eb-8c9b-83dd39a30012.png)

**Comment by ewerybody** [comment]
Pardon. I "fixed" this already. I don't know what it was in the first place tho! Maybe that's another issue?!
Anyway for future documentation and ... I'll leave it to so else to close it.
Thanks! 🙏

**Comment by ewerybody** [comment]
@the-j0k3r : I have a repro now!

- click the ↔ double arrow thing until **HSLA**:
  ![image](https://user-images.githubusercontent.com/218956/98364776-af367480-2031-11eb-9f5b-141f71f2fb25.png)
- click ↔ away from **HSLA** like HEX or RGBA:
  ![image](https://user-images.githubusercontent.com/218956/98365031-20762780-2032-11eb-9ea1-a55e03fd16c5.png)

but I dunno if that's an issue of this style or rather a **Stylus** one?

**Comment by the-j0k3r** [comment]
> but I dunno if that's an issue of this style or rather a **Stylus** one?

It doesn't sound like a style issue. However Stylus has many fixes to colorpicker upstream so you may want to talk to the devs about this issue.

For that see https://github.com/openstyles/stylus#help

**Comment by ewerybody** [comment]
Ok. [posted it there #1105](https://github.com/openstyles/stylus/issues/1105).
