### ISSUE TITLE
Border of pinned issues is still white when Refined GitHub is enabled

### ISSUE THREAD

**Issue by Geeyun-JY3** [StylishThemes/GitHub-Dark#1260]
The border of pinned issues is still white when Refined GitHub is enabled.
Maybe relating to this PR?: sindresorhus/refined-github/pull/3657
* **Browser**: Cent Browser 4.2.10.171 (64-bit) (Chromium 80.0.3987.163), Chrome 86.0.4240.183 (Official Build) (64-bit)
* **Operating System**: Windows 10 1909
* **Link to page with the issue**: https://github.com/sindresorhus/refined-github/issues
* **Screenshot**:
![image](https://user-images.githubusercontent.com/49396421/98432784-c2624680-20fc-11eb-93a2-0cdf8bc7bd05.png)

**Comment by silverwind** [comment]
Are you up to date? This should have been specifically fixed by https://github.com/StylishThemes/GitHub-Dark/commit/badb3c94ee4f5574b47b566c7c975385ceae66af. Can you check the value of the `--github-border-color` css variable in devtools?

**Comment by Geeyun-JY3** [comment]
Yeah it is up to date.
![image](https://user-images.githubusercontent.com/49396421/98436329-8ab3c880-2115-11eb-89fc-e98e8fc3f822.png)


> Can you check the value of the `--github-border-color` css variable in devtools?

like this?
![image](https://user-images.githubusercontent.com/49396421/98436501-aec3d980-2116-11eb-89bd-bde8a9876a72.png)

**Comment by silverwind** [comment]
Ah, I see it's a bug in our selector prefixing.
