### ISSUE TITLE
Is there a way to install this theme without Stylus?

### ISSUE THREAD

**Issue by xhuliojamaku** [StylishThemes/GitHub-Dark#1263]
### I would like to be able do the following

1. Get the CSS/js code manually
2. Install it using another plugin such as "Stylish"

### Additional context
Unfortunately, Stylus cannot be installed on my machine so I am looking for an alternative.

**Comment by the-j0k3r** [comment]
Stylish isnt supported, we dont support spyware

**Comment by xhuliojamaku** [comment]
> Stylish isnt supported, we dont support spyware

Is there any other supported plugin?

**Comment by xt0rted** [comment]
[Cascadea](https://cascadea.app/) on macOS/Safari is the only other option at this point.

**Comment by silverwind** [comment]
There is also xStyle, but no idea if it works. Basically anything that supports the usercss format should work.

See https://github.com/openstyles/stylus/wiki/Usercss#userstyle-manager
