### ISSUE TITLE
Add configuration for code font family/size

### ISSUE THREAD

**Issue by RUSshy** [StylishThemes/GitHub-Dark#1264]
Hi, 

It would be nice to be able to select font size and font familly for code blocks

By default it is way to small "12px" on some fonts it looks blurry (specially on Linux)

Allowing to set a custom size would fix that

**Comment by silverwind** [comment]
Does https://github.com/StylishThemes/GitHub-Dark/raw/master/github-custom-fonts.user.css work for you?

**Comment by RUSshy** [comment]
yes thanks
