### ISSUE TITLE
"Click here to install" shows raw text

### ISSUE THREAD

**Issue by AntonioCS** [StylishThemes/GitHub-Dark#1266]
I am unable to use the "Click here to install the github-dark.user.css." link.
I have Stylish installed:
![image](https://user-images.githubusercontent.com/1086401/99780162-fd597680-2b0d-11eb-967a-fd72efb61f97.png)
but every time I click on the link I just see the contents of the file.

* **Browser**: Firefox 83.0 (64-bit)
* **Operating System**: Windows 10 Pro 64bit
* **Link to page with the issue**: 
* **Screenshot**:

**Comment by silverwind** [comment]
I don't think Stylish is supported any more, please try Stylus as linked in the README.

**Comment by the-j0k3r** [comment]
Please use Stylus and remove that spyware, we dont support it.

**Comment by AntonioCS** [comment]
Got it, sorry I confused the name! Thanks
