### ISSUE TITLE
Contributions have turned back to being green

### ISSUE THREAD

**Issue by HexedHero** [StylishThemes/GitHub-Dark#1268]
They have always been blue and just recently have gone back to being green. I checked for updates and installed the latest but it didn't fix it.  I'm using GitHub Dark v4.2.78 right now.

* **Browser**: Chrome Version 87.0.4280.66 (Official Build) (64-bit)
* **Operating System**: Windows 10
* **Link to page with the issue**: https://github.com/HexedHero
* **Screenshot**: https://i.imgur.com/bnpNaws.png

**Comment by silverwind** [comment]
GitHub seems to have reverted those from CSS vars back to plain colors. Sometimes I really ponder their actions.

**Comment by the-j0k3r** [comment]
They havent, the current hacks need updating.

**Comment by Sylvia3259** [comment]
Quick fix (I'm sorry for my poor English)

```
text.month, text.wday {
    fill: #222!important;
}
.graph-before-activity-overview {
    background: #fff!important;
    border: 1px solid #eee!important;
    filter: invert(90%) hue-rotate(180deg)!important;
}
ul.legend > li:nth-child(1) {
    background: rgb(235, 237, 240)!important;
}
```

**Comment by HexedHero** [comment]
Last update didn't fix the "Less [] [] [] [] [] More" section.

**Comment by silverwind** [comment]
Fixed in https://github.com/StylishThemes/GitHub-Dark/commit/2482c17d1cf32173876e5e612d792556c0082b82.
