### ISSUE TITLE
Move to Sass

### ISSUE THREAD

**Issue by EnzoMartin** [StylishThemes/GitHub-Dark#127]
Discussion for moving to SASS

Proposal from @silverwind:
> 
    https://github.com/sindresorhus/grunt-sass
    https://github.com/nDmitry/grunt-autoprefixer
    https://github.com/gruntjs/grunt-contrib-cssmin

I'm in agreement with using grunt and lib-sass, though I don't think the prefixes are necessary as both Chrome and Firefox support most CSS3 styles without needing prefixes, but it definitely doesn't hurt anything.

**Comment by silverwind** [comment]
Don't think we're doing Sass anytime soon unless Stylish supports it out of the box.
