### ISSUE TITLE
Hi from ZenHub team

### ISSUE THREAD

**Issue by EvHaus** [StylishThemes/GitHub-Dark#1273]
👋 Hi GitHub-Dark community!

Ev here from the ZenHub team. We're big fans of this project here and I just wanted to pop by and thank you all for your efforts. I wanted to give you a heads up that my team is actively working on making wide-sweeping CSS changes to the ZenHub product. We're migrating our CSS from an old Stylus-based system to CSS Modules. As part of this change, all our CSS class names are going to start to get scrambled. We suspect a lot of your code will break as a result. I'm really sorry for that.

But! I have good news. We're centralizing all our colors via CSS Custom Properties. So creating a dark theme for ZenHub should become much easier by simply replacing the base color values. (We might even ship a dark mode we support natively soon too!).

Tagging @silverwind @Mottie @olets as I see you guys have contributed to maintaining ZenHub here most recently.

Feel free to close this issue.

**Comment by silverwind** [comment]
CSS variables (I prefer that name) are a very welcome change. Our ZenHub integration is pretty much fully automated where we generate a matching stylesheet on top of yours with colors swapped.

That automatism will work as long as you're not introducing new color shades and it will even transition to variables automatically. It might of course be helpful if you can provide a list of all colors in use after your transition to variables so we can be sure to catch them all.

**Comment by EvHaus** [comment]
Nice! And thanks for the fast response. We can provide that full list once it finalizes in the coming weeks for sure.

**Comment by the-j0k3r** [comment]
Also inline styles that define colors cant be automatically handled.

**Comment by silverwind** [comment]
Yeah, please no inline styles if possible 😉

**Comment by EvHaus** [comment]
We won't be using any inline styles. 👍

**Comment by the-j0k3r** [comment]
>We're centralizing all our colors via CSS Custom Properties

If you match the default GH CSS vars, no matter automation here or not, you will be automatically supported by any design that overrides the CSS vars

**Comment by silverwind** [comment]
That'd put them in a situation where they are dependant on GitHub not changing their variables which they seem to be happy to do, so I understand if they want to use their own.

**Comment by EvHaus** [comment]
Unfortunately we won't be able to use GH's vars. This is too risky for us as we have no control over them.

**Comment by fregante** [comment]
Aren’t extensions inherently risky? Your whole product is gone once they drop a single class. Colors are something that if used correctly aren’t likely to cause issues, especially because they’re very specific.

**Comment by silverwind** [comment]
The risk is real and if GH can't guarantee a stable interface for the CSS vars, I think it's indeed to risky to rely on them. Maybe it's possible to strike a stability deal with them thought :)

**Comment by ewerybody** [comment]
As this is already a question, not an issue and there is no discussions yet:
I also just want to say thanks to the makers of this here! 🌈♥

Even tho GitHub just released their very OWN built-in dark mode and I tried it a couple days I just switched back to GitHub-Dark and am so happy with it. Thanks!

**Comment by EvHaus** [comment]
Quick update on this. ZenHub is planning to launch native dark mode support in mid-September.

**Comment by EvHaus** [comment]
ZenHub launched official dark mode support today! Please give it a try: https://changelog.zenhub.com/you-asked-we-delivered-dark-mode-has-arrived-in-zenhub!-207395
