### ISSUE TITLE
Conflicts when using with Chrome's Forced Dark mode

### ISSUE THREAD

**Issue by SpriteOvO** [StylishThemes/GitHub-Dark#1274]
I've been using Chrome's Force Dark, which automatically installs the dark theme on all pages, although sometimes it doesn't work well. It can automatically detect the current page and do nothing if it is already in dark theme.

But today, it started failing to detect GitHub-Dark's dark theme, and simply reversed the color, incorrectly showing it as a bright color.

When I disable Chrome's Force Dark, GitHub-Dark works fine. But they worked fine together before today, and I don't know which commit caused the problem.

You can find the Force Dark feature at `chrome://flags/#enable-force-dark` in the Chrome address bar.
I am using the `Enabled with selective inversion of everything` option.

Thanks for this great project!

* **Browser**: Google Chrome 87.0.4280.88 and 87.0.4280.66
* **Operating System**: Windows 10 1909
* **Link to page with the issue**: Everywhere in GitHub with GitHub-Dark
* **Screenshot**:
![image](https://user-images.githubusercontent.com/33660554/101127221-0b43e700-3638-11eb-8138-6ef32334c9d9.png)

**Comment by the-j0k3r** [comment]
You should not use background in Github Dark, because the chrome forced dark mode inverts these.

Solution is use none.

![generic](https://user-images.githubusercontent.com/31389848/101186879-ee1d1180-3653-11eb-82ef-ea855fe6e54d.gif)

That or dont use both chrome forced dark mode and GitHub Dark.

**Comment by SpriteOvO** [comment]
@the-j0k3r It works now, thank you!
