### ISSUE TITLE
GitHub Native Dark Mode

### ISSUE THREAD

**Issue by peaceiris** [StylishThemes/GitHub-Dark#1275]
Today, we got the GitHub native dark theme.

This stylus GitHub Dark theme has helped me always. I want to leave my big thanks for this awesome project!

![Screen Shot 2020-12-09 at 3 03 20](https://user-images.githubusercontent.com/30958501/101523479-02526d00-39cc-11eb-80b5-089cfe47e7e2.png)

**Comment by peaceiris** [comment]
Did you have a collaboration with the GitHub team? Just curious.

**Comment by weslenng** [comment]
Thank you, guys ❤️

**Comment by the-j0k3r** [comment]
Nothing to do with us.

**Comment by the-j0k3r** [comment]
Gists is are unstyled by dark mode.

**Comment by whyseman** [comment]
@the-j0k3r Lots of components are unstyled yet, but that's why it's still in "Beta".

**Comment by erkinalp** [comment]
Official dark theme is more like _Solarized Dark_, so, we would still like to have a deep dark update for this.

**Comment by friendlyanon** [comment]
Personally I dislike the native dark theme, because it's too blue (12,17,23) compared to this theme's neutral black (24,24,24).

**Comment by silverwind** [comment]
Just pinning this for visibilty. I guess we will keep maintaining this style for at least a while because I personally can't stand GH's dark mode 😉

**Comment by hazarek** [comment]
I'm not happy with these shades of blue. https://github.community/t/please-use-grey-like-the-stylish-theme-instead-of-dark-blue/147811/5

**Comment by hazarek** [comment]
@silverwind You can use new "Discussions" beta feature for this topic.

**Comment by auscompgeek** [comment]
Perhaps it'd be worth mentioning the native dark theme in the readme as well?

**Comment by rEnr3n** [comment]
I hope you continue maintining this for those who choose not to have an account here.

**Comment by damianh** [comment]
Definitely don't like their dark blue theme. This one is much nicer.

**Comment by Geobert** [comment]
Moreover, we can choose the syntax highlighting color with this theme :)

**Comment by the-j0k3r** [comment]
Unsubcribed

**Comment by mxdanger** [comment]
Will this theme eventually just act as a custom GitHub theme that only changes GitHub's 600+ CSS variables? This entire theme can now just be a few hundred lines of variables defined in one `:root` instead of the current 33,900 lines of CSS.

**Comment by silverwind** [comment]
Not if we want to keep support for the other sites like docs.github.com and the numerous extensions that still lack a dark mode.

**Comment by the-j0k3r** [comment]
Actually you can remove 90% of the generated CSS by simply replacing the CSS vars assignments and instead of colors for the OTHER site assign them CSS vars... I know for a fact that works I done the same this style does in less than 5K lines all in (only status isnt supported)

Would make this style sane again though, but it was easier for me to do it from scratch else the syntax themes work is not possible to do as this style currently is.

**Comment by silverwind** [comment]
I'm not going to put any more time into such ventures. It works as-is and if GH decides to variablify their other sites, it will automatically adapt.

**Comment by synthead** [comment]
I love the GitHub-Dark custom CSS because it does so much more than just a "dark theme."  I love being able to have my console font in code blocks with a color scheme of my choice, for example.  Please keep this project going; I love it!

**Comment by ThiefMaster** [comment]
I think this theme is still superior to the native dark mode, especially the background!

**Comment by PyGamer0** [comment]
Well github just added the new *Dark Dimmed*. The background looks better than the other dark version
