### ISSUE TITLE
Network Graph looks really bad in the new Dark Mode

### ISSUE THREAD

**Issue by OutdatedGuy** [StylishThemes/GitHub-Dark#1281]
The network graph looks really basic(html like view) in the new dark mode.

Here's a screenshot of how it looks.

![image](https://user-images.githubusercontent.com/74326345/101826279-cac2fc80-3b54-11eb-9ba8-f21375fdcf3b.png)

- Suggestions:
1. Use Pink, Yellow or Cyan color to highlight Numbers.
2. Make graph branch structure of different bright color.
3. Make the whole background black after point 2

**Comment by the-j0k3r** [comment]
Dark mode is native to GitHub, so you need to report this issue to them. Its unrelated to this project.

**Comment by silverwind** [comment]
Seems like GitHub fixed the network graph in dark mode, I removed the inversions. It should now work fine of you set GH to dark while having our style applied on top.

**Comment by the-j0k3r** [comment]
I would instead wrap the inversions in a `@media (prefers-color-scheme:light)` and use that when light mode is used. removing the override totally is not ideal in any way.

**Comment by silverwind** [comment]
No need, I already added to docs that we require dark mode to be set.

Also, there is some issue with the commit labels in the canvas. I assume the JS pulls some color variable or `getComputedStyle`.

**Comment by the-j0k3r** [comment]
Well, it will suck that way, because dark mode mangles labels and PR/ISSUE status colors.
