### ISSUE TITLE
SVG preview cutoff

### ISSUE THREAD

**Issue by Mkassabov** [StylishThemes/GitHub-Dark#1286]
GitHub-Dark cuts off `.svg` previews, other image previews work fine. In order to fix this the style needs to be disabled and the page refreshed. Just disabling the style itself does not work.

* **Browser**: Version 89.0.4350.6 (Official Build) dev (64-bit)
* **Operating System**: 

> OS Name	Microsoft Windows 10 Pro
> Version	10.0.19042 Build 19042

* **Link to page with the issue**: private repo sorry :(
* **Screenshot**:
![image](https://user-images.githubusercontent.com/35264484/103179900-7743f480-485e-11eb-9f93-3a94ba1e53ab.png)
![image](https://user-images.githubusercontent.com/35264484/103179902-77dc8b00-485e-11eb-9c6e-85c7505afde0.png)

**Comment by CraigSiemens** [comment]
Same thing happens in Safari Version 14.0.3
