### ISSUE TITLE
Remove unused/unneeded selectors

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#129]
I'm sure that at least 20-30% of our selectors aren't used any more on GitHub's HTML. We'll have to cross-match our selectors to the GitHub stylesheets, and remove any which aren't used anymore by GitHub.

These are the current stylesheets they use:

https://github.global.ssl.fastly.net/assets/github2-f14002c8b8c821aeaeaf37b52de1d6c4d29dc214.css
https://github.global.ssl.fastly.net/assets/github-dd2e4ab77e94896e4418f4dd1d11ce1efb595fd1.css

This will probably break a few things like cases where we use `.child` and the original style uses `.parent .child`, but It'll be worth it in the long run.

**Comment by Mottie** [comment]
GitHub has released their stylesheet!

https://github.com/primer/primer

I think we can use it as a reference to look for selectors and classes that have been removed.

**Comment by silverwind** [comment]
Woah, how unexpected of them, I've been asking for ages ;)

Not sure it's gonna help us with removing cruft, as Gist and Company are still missing, but it's a start and will probably help us figure out updates more easily.

**Comment by silverwind** [comment]
[uncss](https://github.com/giakki/uncss) looks to be something worth investigating. We'd have to compile a huge list of all possible URLs for it to match our style against. I'm not sure it's really practical, as I don't see an authorization option where we could pass a GitHub session cookie, so it might be necessary to save alle html files locally. Still a lot of work to get right I assume, but it's the most promising tool I've found yet.

**Comment by Mottie** [comment]
I started a [list of pages](https://github.com/StylishThemes/GitHub-Dark/wiki/Pages) that I *used* to test against (getting lazy in my old age)... I haven't updated it in a while.

**Comment by silverwind** [comment]
That's a start, yes. But there's still a ton of special conditions that must be met so certain boxes appear and stuff. It's not something that should be done carelessly, and there's not real urge to it either ;)

**Comment by Mottie** [comment]
Has anyone tried css optimizer before? https://github.com/css/csso

It looks interesting.

**Comment by silverwind** [comment]
Quick test using the default options on each minifier, doesn't look like an improvement:

``
-rw-r--r--   1 silverwind users 102770 Jan 15 01:59 cleancss.css
-rw-r--r--   1 silverwind users 103208 Jan 15 01:59 csso.css
``

**Comment by silverwind** [comment]
It does however run around 250% faster than `cleancss`.

````
File:       github-dark.css
Original:   130 050 bytes
Compressed: 103 208 bytes (79.36%)
Saving:     26 842 bytes (20.64%)
Time:       5261 ms
Memory:     14.726 MB
````

**Comment by silverwind** [comment]
Also see http://goalsmashers.github.io/css-minification-benchmark/

**Comment by silverwind** [comment]
Just [confirmed](https://silverwind.io/cssbench.html) that `clean-css` is in fact the best minifier for `github-dark.css`. :wink:

**Comment by Mottie** [comment]
LOL thanks for checking!

**Comment by silverwind** [comment]
On the topic of tooling, I might implement https://github.com/stylelint/stylelint :)

**Comment by silverwind** [comment]
Closing as this will be a non-issue with [v2](https://github.com/StylishThemes/New-GitHub-Dark).
