### ISSUE TITLE
'Go to file' highlight

### ISSUE THREAD

**Issue by zmni** [StylishThemes/GitHub-Dark#1292]
* **Browser**: Firefox 84.0.2
* **Operating System**:  Windows 8.1
* **Link to page with the issue**:  https://github.com/StylishThemes/GitHub-Dark/find/master
* **Screenshot**:

![code](https://user-images.githubusercontent.com/841523/104354854-6bce1a00-553c-11eb-888f-65207d4462d4.png)

**Comment by the-j0k3r** [comment]
easy fix 

this uses css vars: ` --color-search-hover-hl: var(--color-scale-white)`

so --color-scale-white needs to be added to vars.css
