### ISSUE TITLE
Gitako support?

### ISSUE THREAD

**Issue by aminomancer** [StylishThemes/GitHub-Dark#1293]
Hi there, I noticed the readme says it supports Gitako, but for me, the sidebar is just styled by the default bluish github dark mode. I'm wondering what the readme means when it lists Gitako under supported. Thanks!

FYI this is Firefox 86 on windows 10. My DOM related prefs are definitely less restrictive than the defaults, but if there's some specific setting I'm missing let me know and I'll give it a try. I'm using the latest version of this stylesheet and the latest version of the extension.

**Comment by SpedNSFW** [comment]
I can confirm. It was working fine one day but I reset my browser including extensions and now it's not working at all. I'm using a Chromium browser for what it's worth.

![image](https://user-images.githubusercontent.com/68614336/106376193-f214a800-63e6-11eb-8a74-d02b26f8544d.png)

**Comment by the-j0k3r** [comment]
Dont select the dark github mode, use the light mode.

**Comment by SpedNSFW** [comment]
@the-j0k3r Yeah no. That's not it. And it is designed to be used with GitHub's own dark mode. It specifically says to select it in the installation instructions.

![image](https://user-images.githubusercontent.com/68614336/106376264-be864d80-63e7-11eb-864b-e95178d0d51b.png)

**Comment by aminomancer** [comment]
@SpedNSFW have you tried this theme with octotree by any chance?

**Comment by SpedNSFW** [comment]
@the-j0k3r I have not but I don't see how that's relevant? The Gitako support doesn't work. That's what this issue is about.

**Comment by the-j0k3r** [comment]
Because this style is missing 1001 CSS vars from GitHub fact, so YMMV

However it does seem that gitako css is now outdated., so wai for next regeneration.

**Comment by aminomancer** [comment]
I know what the issue is about, after all I'm the one who filed it. I'm trying to help determine if this is because the CSS rules for this particular extension are incorrect or missing, or because of a broader issue. For instance, Stylus inserts these sheets inline, and some extensions might do the same. There could be a style conflict, a problem parsing the rules, or gitako might even be actively changing the DOM. If it can't be narrowed down to gitako, then that info may help the author debug.

**Comment by the-j0k3r** [comment]
the style was last updated 5 days ago, this is mostly autogenerated, even extensions.... Not that many devs use them.

The extensions css is automatically pulled e.g.

https://github.com/StylishThemes/GitHub-Dark/blob/f4dc70bdeb9c01e03cbdf8af177c992ea85f88b9/src/gen/sources.js#L111-L117

Now if there were changes upstream in gitako recently, this would have triggered some auto generation, it hasnt, so could be other issues. At this time, I dont help out in deving this style anymore so I dont have a quick way to find out and I dont use gitako anyway.

So wait guys, keep calm and keep githubbing.

**Comment by the-j0k3r** [comment]
Any news now there has been updates to master?

**Comment by the-j0k3r** [comment]
no reply so Ill assume issue is gone, if not feel free to reopen.
