### ISSUE TITLE
Projects aren't updated for the recent style changes

### ISSUE THREAD

**Issue by RheingoldRiver** [StylishThemes/GitHub-Dark#1294]
Hi, if you already were aware of this no rush to fix it! Just wanted to leave an issue since you updated everything else, in case you didn't notice this particular page. Either way thanks so much for your extremely quick responses to the recent Github style changes, your theme is much nicer than the official dark theme and I've really appreciated your repo for years!!

* **Browser**: Firefox
* **Operating System**: Windows
* **Link to page with the issue**: https://github.com/users/TsubakiBotPad/projects/1
* **Screenshot**:
![image](https://user-images.githubusercontent.com/18037011/105337802-6c039080-5ba0-11eb-877c-2585092616f5.png)

**Comment by the-j0k3r** [comment]
Dont use the github dark theme and this together.

**Comment by RheingoldRiver** [comment]
Oh ok. I hadn't had an issue with running both at the same time before but I'll turn off their dark theme now, for a while it was making the label colors darker which was nice but it stopped doing that anyway so I'll just turn it off now. Thanks, that works!

If you do want to fix this, it looks like the issue is just the variable --color-project-card-bg but I'll go ahead and close this since this solves.

**Comment by the-j0k3r** [comment]
The way the labels were recolored is wrong, when you create labels and choose a color in dark mode they never match.

> If you do want to fix this, it looks like the issue is just the variable --color-project-card-bg but I'll go ahead and close this since this solves.

I dont use this theme anymore, so hardly makes sense to fix it myself, also this style doesnt implement the full css vars that Github uses but you can submit the variables and overrides into https://github.com/StylishThemes/GitHub-Dark/blob/master/src/vars.css

something like `--color-project-card-bg: #333` or something that fits
