### ISSUE TITLE
Docs footer has bright background

### ISSUE THREAD

**Issue by ThiefMaster** [StylishThemes/GitHub-Dark#1297]
* **Browser**: Firefox
* **Operating System**:  Windows
* **Link to page with the issue**: https://docs.github.com/en/developers/apps/authorizing-oauth-apps
* **Screenshot**:

![image](https://user-images.githubusercontent.com/179599/108114865-a24a0800-7099-11eb-8f4d-dce93e15ae68.png)

**Comment by priyanks25coder** [comment]
This issue is open? Wanted to work on it...

**Comment by the-j0k3r** [comment]
It is, afaik this section has inline color style it needs to be overridden in https://github.com/StylishThemes/GitHub-Dark/blob/master/src/docs.css read the instructions on how to contrib in readme.

Thx

**Comment by priyanks25coder** [comment]
ok and thnx for the help
