### ISSUE TITLE
Mermaid integration

### ISSUE THREAD

**Issue by dvogt23** [StylishThemes/GitHub-Dark#1300]
Hey is it possible to add [mermaid](https://mermaid-js.github.io) to this theme as well?

It renders some mermaid syntax in markdown files to diagrams 😍

**Comment by silverwind** [comment]
No, this is a CSS-only theme but what you suggest requires JS.

**Comment by xt0rted** [comment]
I've been using this recently which is available for both chrome and firefox.

https://chrome.google.com/webstore/detail/github-+-mermaid/goiiopgdnkogdbjmncgedmgpoajilohe
