### ISSUE TITLE
Miscolored formatting options background

### ISSUE THREAD

**Issue by Leo40Git** [StylishThemes/GitHub-Dark#1301]
* **Browser**: Mozilla Firefox 86.0.1
* **Operating System**: Windows 10
* **Link to page with the issue**: Any issues page, like this one
* **Screenshot**:
![image](https://user-images.githubusercontent.com/7997354/111900997-2ba87d80-8a3e-11eb-8ca1-e48d69e3f8ef.png)
![image](https://user-images.githubusercontent.com/7997354/111901017-43800180-8a3e-11eb-9298-d3e6d0c72bce.png)

**Comment by silverwind** [comment]
Fixed in latest version.
