### ISSUE TITLE
Style stopped working with ZenHub

### ISSUE THREAD

**Issue by pattacini** [StylishThemes/GitHub-Dark#1311]
This style has just stopped working with ZenHub. There's lots of white everywhere.

* **Browser**:  Chrome Version 91.0.4472.77 (Official Build) (64-bit)
* **Operating System**:  Windows 21H1 19043.1023
* **Link to page with the issue**:  https://github.com/robotology/icub-tech-support#workspaces/icub-tech-support-5891912f3cfa2d0e47948e0c/board?repos=32422299
* **Screenshot**:

![image](https://user-images.githubusercontent.com/3738070/120199072-1d879200-c223-11eb-9450-27912d8933e1.png)

**Comment by silverwind** [comment]
Must be another breaking change from ZH's side I assume. TBH I'm pretty tired of this constant breakage, mayb evaluate dropping ZH support. Do they support Github's dark themes yet?

**Comment by pattacini** [comment]
>Do they support Github's own dark themes yet?

Not yet, but I know from their blog that they've been working to provide their own dark mode.
Maybe that's why they do no longer seem much concerned about these breaking changes...

**Comment by the-j0k3r** [comment]
ping @EvHaus

**Comment by EvHaus** [comment]
Hey guys. Yeah, as I mentioned [here](https://github.com/StylishThemes/GitHub-Dark/issues/1273), there will be a number of breaking changes every few weeks. Our team is actively updating our UI component to support dark mode themes natively. We're getting pretty close! I can't provide an exact release date just yet but will keep this group informed once we have one.

You may have noticed we added a `data-color-mode` property on the `.zh-app` element already. If you're feeling adventurous you can flip that on to "dark" to see our current progress.

**Comment by pattacini** [comment]
Just to let you know that the style is working ok again with ZenHub.

**Comment by EvHaus** [comment]
ZenHub launched official dark mode support today! Please give it a try: https://changelog.zenhub.com/you-asked-we-delivered-dark-mode-has-arrived-in-zenhub!-207395

**Comment by the-j0k3r** [comment]
Closing since its solved
