### ISSUE TITLE
GitHub Dark isn't working properly on Zenhub , the background is now white again

### ISSUE THREAD

**Issue by kiyanwang** [StylishThemes/GitHub-Dark#1313]
Zenhub currently looks like the screenshot below, they've clearly changed something again which has resulted in the background reverting to white with only some of the content panes in dark.

* **Browser**: 

Chrome 90.0.4430.212 (Official Build) (x86_64)

* **Operating System**: 

macOs: 11.14

* **Link to page with the issue**: 
* **Screenshot**:

![image](https://user-images.githubusercontent.com/1135464/120988072-1eb24500-c776-11eb-9af0-2bd6ffba6c92.png)

**Comment by the-j0k3r** [comment]
duplicate of #1311
