### ISSUE TITLE
Colors are broken on `developer.github.com/changes`

### ISSUE THREAD

**Issue by jack1142** [StylishThemes/GitHub-Dark#1316]
* **Browser**: Chrome 91
* **Operating System**: Windows 10
* **Link to page with the issue**: https://developer.github.com/changes/2016-04-06-deployment-and-deployment-status-enhancements/
* **Screenshot**:
![image](https://user-images.githubusercontent.com/6032823/123842125-b8ea5080-d910-11eb-8c95-d7d06bbca064.png)

**Comment by silverwind** [comment]
Dropped support for that site, it does not follow the main site styling so it's a extra burden we can not reasonably maintain.
