### ISSUE TITLE
Bright "hx_commit-tease.Box-header" when logged in...

### ISSUE THREAD

**Issue by Vangelis66** [StylishThemes/GitHub-Dark#1317]
This is with the latest version (**4.3.55**) of the userstyle: 

![DGH_bug](https://user-images.githubusercontent.com/9669492/124310721-49c16600-db75-11eb-8fd2-0382e06794e8.JPG)

No issue while signed out: 

![DGH_bug0](https://user-images.githubusercontent.com/9669492/124310915-92791f00-db75-11eb-85af-f546b0e3273f.jpg)

For all I know, this is a recent breakage... 😉 

Thanks for your efforts 👍 , this is **much better** that what GH themselves are currently offering...

**Comment by prisoneer** [comment]
Hello Vangelis66,

First of all.. I'm sorry that I'm writing here but I couldn't find any other way to contact you.
I can't help you with your issue but I think you might be able to help me with my youtube-dl issue.
Could you please check it: https://github.com/ytdl-org/youtube-dl/issues/29831

**Comment by Vangelis66** [comment]
This **specific** issue appears to have been fixed in recent versions, 

![gh](https://user-images.githubusercontent.com/9669492/133099702-f9300b15-9329-409d-bb61-8d8082fdf423.jpg)

... so I'll be closing this ticket... 

 However, as it's obvious in the screenshot above, Microsoft 👎 have again ( 😠 ) broken `GitHub Dark` in many places since ca. the last 12 hours, which should be already filed ticket https://github.com/StylishThemes/GitHub-Dark/issues/1320 (locked by userstyle maintainers...).
