### ISSUE TITLE
Timeline items have no color

### ISSUE THREAD

**Issue by ouuan** [StylishThemes/GitHub-Dark#1319]
The timeline items no longer have colors. I've tried older versions of GitHub-Dark and this issue persists. So I guess it's caused by a change on the GitHub side.

* **Browser**: Mozilla Firefox 91.0.2
* **Operating System**: Arch Linux
* **Link to page with the issue**: e.g. https://github.com/StylishThemes/GitHub-Dark/pull/1284
* **Screenshot**:
  ![图片](https://user-images.githubusercontent.com/30581822/131427604-93dc00b0-1b61-4739-a9e1-e9ea278554d9.png)
  ![图片](https://user-images.githubusercontent.com/30581822/131427621-80812d26-1732-4e5f-9166-053520696b79.png)

  ![图片](https://user-images.githubusercontent.com/30581822/131427653-3c6eea88-edaa-4657-909a-d4b683d6d488.png)
  ![图片](https://user-images.githubusercontent.com/30581822/131427644-76453be3-6333-4c56-b960-e350e737ccf5.png)

**Comment by silverwind** [comment]
This is a tough one, I don't see any styles coming from us and what is even more strange, is that I see the bug in GitHub's own dark theme as well without any userstyles active. It seem to be some sort of conflict between `background-image` and `background-color` that GH sets on these badges.

**Comment by ouuan** [comment]
> and what is even more strange, is that I see the bug in GitHub's own dark theme on Chrome (but not on Firefox) as well without any userstyles active

I confirmed this just now. In this case, I think we could wait for GitHub to fix this at least on Chrome first.

**Comment by silverwind** [comment]
Might have something to do with this recent change from GH:

https://github.com/StylishThemes/GitHub-Dark/commit/97d86f04f2f7958c6305f7efad6585c103cf0885#diff-543d1c96774b46e60d15fd897d5fa33f14c7e4cc9a5840c2d31382e2a2dde49cR2365-R2367

**Comment by silverwind** [comment]
Looks like GitHub has fixed it.
