### ISSUE TITLE
Style doesn't work on a specific repository

### ISSUE THREAD

**Issue by IceSentry** [StylishThemes/GitHub-Dark#1325]
Every other page on github is styled properly, but when I go on that specific page it doesn't work for some reason.

* **Browser**: Vivaldi 4.1
* **Operating System**: Windows 10
* **Link to page with the issue**: https://github.com/klaussinani/signale#readme 
* **Screenshot**:
![image](https://user-images.githubusercontent.com/8348954/133911597-ec617af9-130e-404b-b5c6-53089833b2bb.png)

**Comment by IceSentry** [comment]
Oh, I just realized this happens when the url has the id #readme

**Comment by the-j0k3r** [comment]
Shouldn't matter what the URL is.

What it looks like is that the GitHub default dark CSS vars are taking over because this style has the CSS vars in some subdomain section and not in the main CSS where they belong.
