### ISSUE TITLE
Agressive styling for mentions

### ISSUE THREAD

**Issue by FichteFoll** [StylishThemes/GitHub-Dark#1329]
Some recent update from GitHub (I think?) made mentions of yourself stand out a lot compared to before and it doesn't fit the rest of the theme. Specifically the background isn't padded properly and the color is unadjusted.

* **Browser**: FireFox
* **Operating System**: Arch Linux
* **Link to page with the issue**: any comment or readme with a mention (find one [here](https://github.com/notifications?query=reason%3Amention))
* **Screenshot**: 
native light: 
![2021-10-08_01-25-02_github-dark_mention-light](https://user-images.githubusercontent.com/931051/136475498-8a0d43b9-744e-41ef-9494-a6f6dba3faf9.png)
native dark:
![2021-10-08_01-26-02_github-dark_mention-dark](https://user-images.githubusercontent.com/931051/136475551-fe200946-ad32-41e1-98f3-d00540d97945.png)

**Comment by the-j0k3r** [comment]
all github is undergoing constant changes, I no longer have time to maintain style, hence it breaks, feel free to fork and update.
