### ISSUE TITLE
[Custom Fonts (5.2.37)] New Editor - background/read-only content used for cursor/text selection not using custom font settings

### ISSUE THREAD

**Issue by dbarbuzzi** [StylishThemes/GitHub-Dark#1354]
* **Browser**: Chrome, Firefox
* **Operating System**: Windows 11, macOS 12
* **Link to page with the issue**: https://github.com/ibaiGorordo/ONNX-YOLOv8-Object-Detection/blob/main/video_object_detection.py
* **Screenshot**: 
![Screenshot 2023-04-18 120846](https://user-images.githubusercontent.com/642904/232838030-a8f4dde0-7661-46e9-8ff6-aa7e9af12eb0.png)

As seen in the screenshot (a bit hard due to the black background text on the dark GitHub theme), the new view’s code display has a background/“read-only” copy of the content that is rendered in the site’s default font. This affects UX because it is that version of the content that is used when e.g. selecting text within the displayed code. I was able to fix this locally by applying my custom font settings to the selector `#read-only-cursor-text-area`. If a different selector is preferred, here is a screenshot of the relevant element from the DOM inspector:

![Screenshot 2023-04-18 121251](https://user-images.githubusercontent.com/642904/232838989-9c83bd05-eb22-4de1-9c7e-622cdf02c4a4.png)

**Comment by silverwind** [comment]
Try v5.2.38
