### ISSUE TITLE
GH Custom Fonts: PRs and issues with `code` in titles have small font size relative to rest of the title

### ISSUE THREAD

**Issue by ian-h-chamberlain** [StylishThemes/GitHub-Dark#1359]
Using GitHub Custom Fonts `5.3.146`, it applies the `--ghd-font-size` variable to _all_ `code`, `pre` etc. on a page, which can include `h1 code` elements in PR/issue titles. This ends up looking pretty awkward as the `code` will be much smaller than the rest of the title.

* **Browser**: Firefox 121.0.1 (64-bit), also tested with FF developer edition 122.0b9 (64-bit)
* **Operating System**: macOS Ventura 13.6.3
* **Link to page with the issue**: this issue should show it, or any PR/issue with backtick `code` in its title.
* **Screenshot**: 
![Screenshot 2024-01-16 at 11 57 31](https://github.com/StylishThemes/GitHub-Dark/assets/11131775/eb056f83-c2be-49ca-9edc-73c2eeb7496c)

A workaround is to configure the font size using a relative size, e.g. `0.8em`, but this isn't ideal since it makes code blocks rather small by comparison. Of course another user style can also override this one.

I think there might two slightly better options:
* "hard code" to ignore `h1` (and maybe any other `h2`, `h3`, etc.?) elements when applying the font size	
* Don't mark the `font-size` as `!important`, and add more specific selectors for certain things like `.markdown-body code`, `.commit-desc pre`, etc. This is probably a pain to find all the different classes and stuff that would be needed

Edit: option 1 could possibly look something like 
```css
h1 code,
h2 code,
h3 code,
h4 code,
h5 code,
h6 code {
  font-size: inherit !important; 
}
```

**Comment by silverwind** [comment]
I've removed the `!important` which seems to fix it. This works because stylus inserts rules at the end of `<head>` so the rules win by ordering alone. If might be that this breaks some other cases, but the solution will be to add those exact selectors to the file, which will make precendence by order work.

**Comment by silverwind** [comment]
Can you reproduce on https://microsoft.github.io/monaco-editor/playground.html as well?

**Comment by ian-h-chamberlain** [comment]
> Can you reproduce on [microsoft.github.io/monaco-editor/playground.html](https://microsoft.github.io/monaco-editor/playground.html) as well? Paste into editor on right.

Not sure I understand what you mean by this — is the userstyle meant to apply to the playground there as well, or are you suggesting to paste the whole style into there? 

FWIW — after updating the new style does seem to fix this issue, and the font size setting now looks like it no longer affects a few different things (which is correct behavior IMO):
* Title inline `` `code` `` like in the title of this issue
* Comments inline `code` <- like this
* Comment code blocks (this one might be nice to have?)
	```html
	<b>like this</b>
	```

The font size setting still seems to apply to 
* diff view on PR e.g. https://github.com/StylishThemes/GitHub-Dark/pull/1285/files
* File view e.g. https://github.com/StylishThemes/GitHub-Dark/blob/master/index.html
* commit titles and hashes e.g. 
<img width="889" alt="Screenshot 2024-02-24 at 12 26 22" src="https://github.com/StylishThemes/GitHub-Dark/assets/11131775/e3dcb773-e54d-4f6a-a0c3-e3ded5db4323">

As far as I'm concerned this seems to be do pretty much what I expect, maybe with the exception of the `<pre>` blocks in comments. Thanks!

**Comment by silverwind** [comment]
Ignore that last comment, is wasn't for this thread. Regarding selector list, yes it's likely outdated and can be improved.
