### ISSUE TITLE
Updating is broken - stuck at version 5.3.143

### ISSUE THREAD

**Issue by glitsj16** [StylishThemes/GitHub-Dark#1360]
I've noticed a problem with the update routine lately. According to Stylus the latest available version is `5.3.143`, even though the [automated regeneration commit](https://github.com/StylishThemes/GitHub-Dark/commit/b5c422ca28a1eb46a2b635b787bd62244ce6ea89) is at version `5.3.148`.

The badge on https://stylishthemes.github.io/GitHub-Dark/github-dark.user.css is refering to version 5.3.148, yet the style still contains `@version     5.3.143`.

* **Browser**: Firefox 121.0.1 / Firefox 1230a1
* **Operating System**: Arch Linux
* **Link to page with the issue**: 
* **Screenshot**: https://img.shields.io/github/tag/StylishThemes/GitHub-Dark.svg

**Comment by Vangelis66** [comment]
... Yes, this has been happening for ca. two weeks now :disappointed: ... 
To update the two scripts I have installed (**GitHub-Dark** + **GitHub Custom Fonts**), I have to **re-install/update manually** via: 
```
https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-dark.user.css

https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-custom-fonts.user.css
```

**Comment by Vangelis66** [comment]
... After close to a full month of breakage 😞 , this issue appears _now_ to have fixed itself 👍 ; indeed:
```
https://stylishthemes.github.io/GitHub-Dark/github-dark.user.css
```
, the value of `@updateURL`, now points to the most-up-to-date version, `5.3.151`; my manually installed `5.3.150` versions successfully updated inside my **Stylus** installation; @glitsj16, would you mind  **closing** this issue? Thanks 😄 !

**Comment by glitsj16** [comment]
@Vangelis66 Indeed, it started to work again with `5.3.151`. Thanks!
