### ISSUE TITLE
Minor display issues on new beta "commit details" page

### ISSUE THREAD

**Issue by ian-h-chamberlain** [StylishThemes/GitHub-Dark#1369]
GitHub has introduced a new "commit details" page, currently in public beta: https://github.com/orgs/community/discussions/139005

The style seems to mostly work on this page, but has some small differences vs the old view which would be nice to keep consistent.

* **Browser**: Firefox 130.0 (64-bit)
* **Operating System**: macOS 14.6.1
* **Link to page with the issue**: I think any commit should do, for example my screenshots are from https://github.com/tornadoweb/tornado/commit/a6dfd70d7a6398b2187021df63ca77daa5781e5e
* **Screenshot**:
  New commit details page (`Feature Preview > New Commit Details Page > Enable`):

  ![Screenshot 2024-10-07 at 12 57 29](https://github.com/user-attachments/assets/b88d8012-717f-45f2-8d9c-c62df4c1b33b)

  Old commit page (`Feature Preview > New Commit Details Page > Disable`):

  ![Screenshot 2024-10-07 at 12 57 12](https://github.com/user-attachments/assets/3510400c-707f-4437-9a05-b64174205b5f)

The main differences I noticed:
- Code background is transparent / same as page background. This is the most jarring thing for me.
- Header background color changed (github default seems to just be same color as background?)
- Some visual artifacts around each file header — background color extended too far / not far enough? 

There may be some other subtle differences, but maybe not worth spending too much effort on, in case there are further changes to the commit details view — but if the code background could be made non-transparent I think that would be a huge help for readability, especially with a custom / patterned background is configured.

**Comment by the-j0k3r** [comment]
all github is undergoing constant changes, I no longer have time to maintain style, hence it breaks, feel free to fork and update.
