### ISSUE TITLE
CSP solution

### ISSUE THREAD

**Issue by leoj3n** [StylishThemes/GitHub-Dark#188]
Regarding https://github.com/StylishThemes/GitHub-Dark/wiki/Image, my solution for now is to put the following code in `background.js` of a Chrome Extension:

``` js
//
// Disable CSP on GitHub
//

chrome.webRequest.onHeadersReceived.addListener(function(details) {
    for (var i = 0; i < details.responseHeaders.length; i++) {
        if (details.responseHeaders[i].name.toUpperCase() === 'CONTENT-SECURITY-POLICY') {
            var begin = details.responseHeaders[i].value.split('img-src', 2);
            var end = begin[1].split(';', 2);
            details.responseHeaders[i].value = begin[0] + 'img-src \'self\' data: *;' + end[1];

            console.log('New CSP should be... ' + details.responseHeaders[i].value);
        }
    }
    return {
        responseHeaders: details.responseHeaders
    };
}, {
    urls: [ '*://*.github.com/*' ],
    types: [ 'main_frame', 'sub_frame', 'stylesheet', 'script', 'image', 'object', 'xmlhttprequest', 'other' ]
}, [ 'blocking', 'responseHeaders' ]);

console.log('background.js Event Page');
```

And in `manifest.json`:

``` json
{
    "permissions": [
        "webRequest",
        "webRequestBlocking"
    ]
}
```

:smiling_imp:

**Comment by Mottie** [comment]
This is odd, I can add an external image in comments, but not as a background image?

![safe?](http://i1134.photobucket.com/albums/m612/Jesseforever69/Funny%20Things/IZZSAFEIZZZZNOOTTT_3650d0_4347705.gif) &larr; from Photobucket

![stplr](http://farm3.staticflickr.com/2214/2087834469_ddccc5f427_m.jpg) &larr; Flickr

**Comment by Mottie** [comment]
Hmm, never mind, it looks like they upload and show it to their cloud, but keep the original link.

**Comment by silverwind** [comment]
Yeah, they re-host every image. I think they periodically query the original source too for updates.

**Comment by silverwind** [comment]
Data-URIs work by the way because they are explicitely allowed:

```
img-src 'self' data: assets-cdn.github.com identicons.github.com www.google-analytics.com checkout.paypal.com collector.githubapp.com *.gravatar.com *.wp.com *.githubusercontent.com
```
