### ISSUE TITLE
Support mobile github.com

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#202]
https://github.com/blog/1924-mobile-search

This will surely require a few style updates, will check it out.

**Comment by silverwind** [comment]
I think it may be worth to write an own style for GitHub mobile. There's a ton of selector overlap and it seems almost nothing is shared with the main site. Thought this is very low priority for myself, as I prefer the desktop version over the gimped mobile one any day :)

**Comment by jawshooah** [comment]
Yup, I vastly prefer [OctoDroid/gh4a](https://github.com/slapperwan/gh4a) to the subpar mobile site anyway.

**Comment by auscompgeek** [comment]
This issue isn't Firefox-specific, Stylish for Dolphin exists as well :dolphin:

**Comment by silverwind** [comment]
Unfortunately, I don't think I'll have time or motivation to style the mobile site anytime soon. If Mobile Chrome gets the ability to run userstyles, I will reconsider.

Of course, we're open to contributions for the mobile theme, ideally in it's own section so we track which rules only apply to mobile.

**Comment by Mottie** [comment]
If I open GitHub with the Chrome developer tools "Toggle device toolbar" set to emulate a mobile device, I can see that this css file gets loaded: https://assets-cdn.github.com/assets/mobile-196a715f10ab3d1d09c93a1aea1f95ba.css

![](https://user-images.githubusercontent.com/136959/40633521-c43f96d6-62b5-11e8-87fc-a926f003660d.png)

I'm not sure how to modify the `generate.js` file to set up [a got proxy](https://github.com/sindresorhus/got#proxies) to make it pretend to be a mobile device. Any ideas?

**Comment by auscompgeek** [comment]
I think setting the user-agent should be enough. https://github.com/sindresorhus/got#user-agent

**Comment by silverwind** [comment]
Yes, set `opts.headers["User-Agent"]` to a iPhone or Android UA string (also probably worth checking if they serve different content for iPhones). I'd turn `urls` into a array of objects of `{url, userAgent}` and then adjust the `got` options based on that.

**Comment by silverwind** [comment]
@Mottie I added option support in https://github.com/StylishThemes/GitHub-Dark/commit/9a3a31be5b4813c9c43964f7623ca75630e89312.  You should be able to use:

````js
{url: "https://github.com", opts: {headers: {"User-Agent": "Mozilla/5.0 (Linux; Android 8.0.0; Pixel Build/OPP3.170518.006) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.66 Mobile Safari/537.36"}}},
{url: "https://github.com", opts: {headers: {"User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A356 Safari/604.1"}}},
````

to simulate Android and IOS user agents.

**Comment by Mottie** [comment]
Sadly, this method isn't working. I changed the `generate.js` to *only* use the url with an Android header and the css file names do not include "mobile". I even tried using `"user-agent"` (lower cased) per the got example.

**Comment by silverwind** [comment]
Ah, it apparently depends on the presence of a `user_session` cookie, which means only logged in users get the mobile css, so one needs to simulate a log in, preferably via a trash account using credentials from the environment.

**Comment by silverwind** [comment]
Ah, it appears `https://github.com/login` combined with the mobile UA serves the mobile CSS :)

**Comment by silverwind** [comment]
I've reverted the introduction of mobile rules (https://github.com/StylishThemes/GitHub-Dark/commit/fdc940a8f99d93dfb3db640a2fb2301455402639) because they cause minor issues on the desktop site. I'm sure it can be made to work, but some overrides of generated rules will be necessary.

**Comment by the-j0k3r** [comment]
Why cant it just be a separate style anyway? I was browsing GH over my mobile and found a few issues but with exception of the Github Tab colors which is a rather small theme and could include one of the fixes, the rest could very well be a separate mobile site only style.

**Comment by xt0rted** [comment]
How do you use GitHub Dark on mobile?

**Comment by silverwind** [comment]
> How do you use GitHub Dark on mobile?

You install Stylus on Firefox Mobile.

> Why cant it just be a separate style anyway

I'd go with a separate `@-moz-document` section. Mobile has its own stylesheet that is causing issues on the desktop site if both are applied.

**Comment by silverwind** [comment]
Found a way to style the mobile site without breaking the desktop one. Mobile styles are prefixed with `.page-responsive` which is present on `body`. Still a few issues, but doesn't look too bad:

<img width="275" alt="screenshot 2019-03-02 at 18 44 26" src="https://user-images.githubusercontent.com/115237/53685471-62a67c00-3d1b-11e9-94a1-4ed16892fb4c.png">

I suggest we cover the mobile site entirely using generated rules, it can be tested using Chrome's device option in the devtools.

**Comment by xt0rted** [comment]
@silverwind the `.page-responsive` class is used on desktop pages too as seen on:

- https://github.com/ (when logged in & not logged in)
- https://github.com/StylishThemes/GitHub-Dark/releases
- https://github.com/StylishThemes/GitHub-Dark/wiki
- https://github.com/marketplace
- https://github.com/topics/usercss

They've been slowly merging their mobile views into the desktop version and making them responsive.

- https://github.blog/changelog/2018-07-31-responsive-search-pgs/
- https://github.blog/changelog/2018-08-07-responsive-wiki-pgs/
- https://github.blog/changelog/2018-08-14-responsive-release-pgs/
- https://github.blog/changelog/2019-01-16-dashboard-ui-refresh/

**Comment by silverwind** [comment]
Limited them further to pages only containing the single class `page-responsive`. This looks to be true for all mobile pages I tested except projects.

I wish they would add a `mobile` class when they decide to pull in their mobile stylesheets, or better yet, merge those stylesheets.

**Comment by silverwind** [comment]
I'm gonna close this as fixed. Mobile looks reasonably well now. Not totally in line with the desktop style, but certainly acceptable.
