### ISSUE TITLE
Manual installation - Chrome

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#204]
For Firefox, one can simply copy/paste the style into a new Stylish Style, but I think for Chrome one has to remove the `@-moz-document` and add the domain rule - am I correct?

I wonder if it's possible to build a paste-able Chrome file to which we could point Chrome users.

**Comment by Mottie** [comment]
Yes, for Chrome you just need to remove the first (`@-moz-document`) and last (`}`, closing bracket) line from the style.

The repository is set up so that you can create a [`build.json`](https://github.com/StylishThemes/GitHub-Dark/wiki/Build) file in the root directory with the `"chrome"` setting set to `true`, and then use `grunt` to create a custom style that can be directly copied &amp; pasted into the Chrome stylish editor.

If you want, I can create/update this file whenever we bump the version. It just needs to not be ignored by git (`.gitignore`) to be visible.

**Comment by silverwind** [comment]
Don't think we should manually update it, too much work for a minor gain.

But as for a fresh Chrome installation, you need to define the domains rule, right? Maybe we should document that.

**Comment by Mottie** [comment]
It seems to me that it's so much easier to just "fresh" install the style from userstyles, but sure if you think it needs documenting, then that isn't a problem.

**Comment by Mottie** [comment]
Here is a link to the [new page](https://github.com/StylishThemes/GitHub-Dark/wiki/Install)

**Comment by Mottie** [comment]
Does anyone use Safari? I don't know if [this extension](http://sobolev.us/stylish/) works.

The install instructions would need to be updated with instructions if it works. It seems the [Stylish author is happy with it](https://forum.userstyles.org/discussion/comment/87644/#Comment_87644).

**Comment by silverwind** [comment]
Just tested in Safari 8.0.3. The [extension](http://sobolev.us/stylish/) installs, but userstyles.org still thinks I should install Stylish and won't let me install a style. Also, It seems that extension doesn't allow manual installation of styles at all.

With the last update being 2011, I think Safari Stylish is just broken and unmaintained.

**Comment by silverwind** [comment]
> Here is a link to the new page; please feel free to tweak it however you desire :smile_cat:

Thanks for the writeup. I may tweak it a bit later, but else it looks fine.

By the way: does the note about unfinished themes still apply in the readme?

**Comment by silverwind** [comment]
I think he's dead, jim.

![screenshot_23](https://cloud.githubusercontent.com/assets/115237/5692520/0874964c-98f9-11e4-81eb-cfb2989577e4.png)
![screenshot_24](https://cloud.githubusercontent.com/assets/115237/5692518/057ec46c-98f9-11e4-8d07-7481bfa814cd.png)

The 'Install Stylish' button on userstyles.org still redirects me to the authors side, and I then tried to manually install from the provided link (says version 1.6.6), but that brought me no further, the site can't detect the extension it seem.

cc @JasonBarnabe

**Comment by silverwind** [comment]
Oh wait, I'm dumb and didn't notice the "S" button besides the location bar. It apparently gives a custom interface to userstyles.org, and I was able to successfully install our style, yay.

![screenshot_25](https://cloud.githubusercontent.com/assets/115237/5692565/2299441c-98fb-11e4-8786-fa698700b303.png)

I'll add a section for Safari later.

**Comment by Mottie** [comment]
Sweet, thanks! I removed that note as well.

**Comment by Mottie** [comment]
By the way, I just renamed the build script `"chrome"` option to `"webkit"` to avoid confusion; wiki docs updated as well.

**Comment by silverwind** [comment]
Yeah, I was just about to "save" my wiki edits when it noticed me about your change to it :dancer: 

Anyways, I restructured the install page a bit now and added the safari method. I don't think Safari allows manual installation so I didn't add a section.

**Comment by silverwind** [comment]
https://github.com/JasonBarnabe/userstyles/issues/60 for the safari issue.
