### ISSUE TITLE
Background issues on GitHub Enterprise

### ISSUE THREAD

**Issue by chimericdream** [StylishThemes/GitHub-Dark#205]
On GHE, the diff backgrounds do not extend through the code. This makes it difficult to see where the diff lines are. The cause is an extra ```<pre>``` tag that needs to be styled. PR coming shortly.

**Comment by Mottie** [comment]
Hi @chimericdream!

We would greatly appreciate it if you would check and/or update the style for the new Enterprise Instance Health page! Pretty please with cat nip on top! :heart_eyes_cat: 

If the colors of the graph are off (hopefully it's all svg), then you can [copy or merge it into the styling](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L654) we already have for the [graph page](https://github.com/StylishThemes/GitHub-Dark/graphs).

Thanks!
