### ISSUE TITLE
Third-party access

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#207]
I am not seeing the "Third-party access" tab on the settings page. The [blog post has a screenshot of it](https://github.com/blog/1941-organization-approved-applications), so either we need to integrate in something, or does that only apply to Enterprise organizations and they forgot to mention it?

**Comment by silverwind** [comment]
I see it, but didn't want to proceed further because I'm not sure what it restricts.

**Comment by Mottie** [comment]
LOL, ok I found it... I was looking at the repo settings page, derp.

I guess I could set up a dummy organization to test it...

**Comment by Mottie** [comment]
It looks like pretty much everything is already styled. There is a page with 3 images that is a little bright, but I think given the amount of time you'll probably spend on that page that it's not worth replacing them (inverting them would look bad).
