### ISSUE TITLE
Code links

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#209]
I was posting some code which linked back to documentation and noticed that the link was not being styled; there is no indication that it is a link except for hovering over it:

[`linked code`](https://github.com/StylishThemes/GitHub-Dark)

I'm not sure if making it match the base color would be a good idea, but maybe we could at least underline it? What do you guys think?

**Comment by silverwind** [comment]
Definitely a bug if it's colored with the style disabled, looking into it.

**Comment by silverwind** [comment]
Well that was easy, but may affect other code tags, I must've put it there for a reason, but I don't remember right now.

**Comment by silverwind** [comment]
hmm underline still missing.

**Comment by silverwind** [comment]
strange that it doesn't underline on hover, given that we don't touch `text-decoration`. There's `a:hover, a:active { text-decoration: underline }` in GH's sheet.

@Mottie could you have a look in Chrome's inspector? Firefox still shows the underline in computed styles, but doesnt render it.

**Comment by Mottie** [comment]
Hmm, I'm not seeing where the text-decoration is being changed, when I click on the `code` block, I do see this entry show up in the <em>user agent stylesheet</em>

```css
a:-webkit-any-link {
  color: -webkit-link;
  text-decoration: underline;
  cursor: auto;
}
```

If I add this css (even without the `!important` flag) to the stylesheet, it appears to work:

```css
a:hover code {
  text-decoration: underline;
}
```

But my question still is about the text color. There isn't any syntax highlighting, so should we leave the text off-white or the base color?

**Comment by silverwind** [comment]
> so should we leave the text off-white or the base color?

My general rule of thumb is, if it's colored without the style, it should be colored with the style, so base color seems fine to me.

![b4](https://cloud.githubusercontent.com/assets/115237/6150664/0163ab14-b211-11e4-909f-b9b8ce561653.png)
![after](https://cloud.githubusercontent.com/assets/115237/6150667/0400a8c2-b211-11e4-818b-a03786aaea00.png)

**Comment by Mottie** [comment]
Ok, sounds reasonable :smile_cat:

**Comment by silverwind** [comment]
This underline thing smells like a Firefox bug to me, or a spec misbehaviour in Chrome, or both. I'm not sure if that property shall be inherited by child elements att all. Setting

````css
a:hover code {text-decoration: underline !important}
````

does fix it, but I'm afraid this might have side-effects on other parts of the site. Hmm.

**Comment by silverwind** [comment]
I have an idea on how to fix this without causing too much side-effects.

**Comment by silverwind** [comment]
Please check if you still have the underline on hover in Chrome.

**Comment by Mottie** [comment]
Sorry, I've been doing a lot of running around today... yeah that is working just fine :P
