### ISSUE TITLE
Blame heats

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#212]
Something's wrong here:

![screenshot_35](https://cloud.githubusercontent.com/assets/115237/6238115/bbe38c84-b6f8-11e4-8f4c-99c6c8cd43b4.png)

Also, if you want to rewrite heats, I suggest doing some `filter: brightness` stuff instead of opacity hacks :D

**Comment by Mottie** [comment]
LOL they added `.heat9` and `.heat10` - no idea why, it's not "that" easy to see the differences.

**Comment by Mottie** [comment]
Oops forgot to fix this...

**Comment by Mottie** [comment]
Well, I ended up keeping `opacity` (https://github.com/StylishThemes/GitHub-Dark/commit/b4ca0a32520985696675da73671f319143b581ac)... it appears that the filters don't work on svg elements, or maybe I did something wrong. Either way, it's less bytes to use opacity :wink:
