### ISSUE TITLE
file-header has no style

### ISSUE THREAD

**Issue by Archenoth** [StylishThemes/GitHub-Dark#213]
It looks like the header for files doesn't have a style:

![screenshot from 2015-02-17 20 00 18](https://cloud.githubusercontent.com/assets/1385527/6241765/f9e8645a-b6df-11e4-9c34-e00adb42455d.png)

That is [this page](https://github.com/xach/quickproject/blob/master/quickproject.lisp).

I'm not 100% sure what these headers were called before, but it appears to be the result of a recent class name change of the file-header element.

**Comment by Mottie** [comment]
Hi @Archenoth!

It's already been taken care of in https://github.com/StylishThemes/GitHub-Dark/commit/da492e4e822b7618e64c22c38631798f65e64ee6

I'm working on pushing a new update now.

**Comment by Mottie** [comment]
Done!
