### ISSUE TITLE
Inconsistent source fonts

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#215]
Example: https://github.com/iojs/io.js/blob/v1.x/lib/_tls_wrap.js#L57

![screenshot_36](https://cloud.githubusercontent.com/assets/115237/6521053/7214d776-c3d1-11e4-9341-6ae59492f9f6.png)

**Comment by silverwind** [comment]
I guess I'm crazy. It's not actually variable width, but something's not right about the fonts there.

**Comment by Mottie** [comment]
I was just looking at it... the fonts are all the same size... it does look odd, but if I edit the HTML and camel case the name, it doesn't look so bad LOL

![2015-03-06 00_35_26-io js__tls_wrap js at v1 x iojs_io js](https://cloud.githubusercontent.com/assets/136959/6521150/bc0ac34c-c398-11e4-82b6-2fa101313dc4.png)

**Comment by silverwind** [comment]
Yeah, it's probably just the all-lowercase that seems out of place, lol. But the fact that it renders in Menlo is a local issue here (I have a second stylesheet that overrides it to Monace).
