### ISSUE TITLE
Multiple buttons are not styled

### ISSUE THREAD

**Issue by Fuuzetsu** [StylishThemes/GitHub-Dark#218]
From about 3 minutes ago:

![Buttons](http://fuuzetsu.co.uk/images/1426799489.png)

**Comment by Mottie** [comment]
Hi @Fuuzetsu!

Thanks! Fixed in https://github.com/StylishThemes/GitHub-Dark/commit/16e709e66505c99a3d20616a7c5003afd5c0eee2.

**Comment by silverwind** [comment]
Might be work to remove the leftover `.button` selectors, if we can be sure they aren't used anymore.
