### ISSUE TITLE
Issue list and comment box headers

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#219]
There are new classes around, these shouldn't be colored unless hovered.

**Comment by silverwind** [comment]
Also, the 'owner' header label in commants should have a light colored border. There's probably more minor changes needed, we should check everything :)

**Comment by silverwind** [comment]
Oh, and 'Comment' button highlight shouldn't be grey.

**Comment by Mottie** [comment]
Awesome work!
