### ISSUE TITLE
Don't use gradients

### ISSUE THREAD

**Issue by liquiddandruff** [StylishThemes/GitHub-Dark#221]
Compare various UI elements with the native Github look--gradients are never used. In my opinion, flatter styles look better anyways, and I feel others probably think the same. Loving the theme so far!

Examples:
div class file-header
div id readme
td id class blob-code (code line mouseover)
div class timeline-comment-header-text (this gradient looks "okayish" though :) )

**Comment by silverwind** [comment]
I actually plan on changing the last remaining gradients. There is one place where Github still uses them, and that is on buttons so we might keep those for a while at least.

**Comment by liquiddandruff** [comment]
Great! Eager for the updates.

**Comment by silverwind** [comment]
Let's leave this open for visibilty.

**Comment by silverwind** [comment]
Removed pretty much all gradients I could spot, except buttons of course. @Mottie hope you like it :)

**Comment by liquiddandruff** [comment]
It's beautiful! Great stuff, @silverwind :D

**Comment by Mottie** [comment]
I miss the blue gradient, but I can live with flat.

I can live with just about anything... but the vampire cat in me doesn't like bright backgrounds!


![runsies_by_sereneworx](https://cloud.githubusercontent.com/assets/136959/6815897/e6086760-d259-11e4-9e50-63e8b8c8f7bb.gif)

**Comment by silverwind** [comment]
Should all be fixed now! I plan on removing the leftover gradient selectors at some point later.
