### ISSUE TITLE
background-attachment: fixed

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#226]
Looking for feedback if i should add this. To try it, add this to the `body` group:

````css
background-attachment: fixed !important;
```

I think it looks fabulous with the default backdrop. Scrolling performance may be reduced though.

**Comment by Mottie** [comment]
Huh?

It is already one of the options on the userstyles site:

![2015-04-17 12_49_26-github dark - themes and skins for github - userstyles org](https://cloud.githubusercontent.com/assets/136959/7207613/4cc238e2-e500-11e4-964d-8e65a8a39ab4.png)

**Comment by silverwind** [comment]
Oh, I didn't notice as I just paste the style. We should add it to the default style, something like

````css
background-attachment: /*[[bg-attachment]]*/ fixed !important;
````

**Comment by Mottie** [comment]
Well, right now it is stored as `/*[[bg-options2]]*/`

![2015-04-17 12_54_16-editing github dark - userstyles org](https://cloud.githubusercontent.com/assets/136959/7207691/f65ee562-e500-11e4-94b4-836a560de1b2.png)

I would prefer not to have the default set to fixed, but that's fine. I'm not sure if Grunt will replace it properly without some tweaks.

**Comment by silverwind** [comment]
Any other user opinions on whether the background should be fixed (non-scrolling) by default?

**Comment by Mottie** [comment]
It really doesn't matter to me since I usually install from userstyles.. to make sure everything works.

**Comment by silverwind** [comment]
![yes](https://cloud.githubusercontent.com/assets/115237/7216486/c94ad6ba-e601-11e4-9205-addd46f50856.gif)
