### ISSUE TITLE
Label editor

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#227]
@Mottie can you take a look at this one? I can't seem to find what's styling the background:

https://github.com/StylishThemes/GitHub-Dark/labels

![screenshot_45](https://cloud.githubusercontent.com/assets/115237/7207866/ee69b94a-e53c-11e4-8179-e780950a8fc5.png)

**Comment by Mottie** [comment]
Hmm, now the issue comment box is too bright LOL

**Comment by Mottie** [comment]
LOL it's not my day... ok now it has the correct focus highlight border color as well.

**Comment by silverwind** [comment]
Almost perfect! Just missing the :focus box-shadow, I'll add that.
