### ISSUE TITLE
Diff views dont have correct color palette

### ISSUE THREAD

**Issue by qlonik** [StylishThemes/GitHub-Dark#228]
Hello. It seems that diff views in pull requests do not have correct syntax highlighting:
![2015-04-23-014402_1339x1003_scrot](https://cloud.githubusercontent.com/assets/1373271/7290712/49d410a2-e95a-11e4-97c0-b612dab97881.png)

Example link: https://github.com/torvalds/linux/pull/174/files

Here is background and text are both dark, and text is unreadable.
Did I do something wrong or is it an issue with the style?

**Comment by silverwind** [comment]
It looks like Github and additional wrapper class `.blob-code-inner` which set `#333` text color. I've already pushed an fix in https://github.com/StylishThemes/GitHub-Dark/commit/2e0233921383c8519d2aa60e96f316ce7c2a56c7 30 minutes ago, I'm sure @Mottie will do a release with that :)

**Comment by qlonik** [comment]
That's awesome! Thank you for quick response.

**Comment by Mottie** [comment]
Done :smiley_cat:
