### ISSUE TITLE
Jupyter Notebooks renderer

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#230]
https://github.com/blog/1995-github-jupyter-notebooks-3

Example: https://github.com/sujitpal/statlearning-notebooks/blob/master/src/chapter2.ipynb

**Comment by Mottie** [comment]
I fixed the output, but the syntax highlighting appears to still be using Pygments. *sigh*

**Comment by silverwind** [comment]
Featuring: Sexy dark graphs:

![screenshot_52](https://cloud.githubusercontent.com/assets/115237/7541273/2e872ada-f5b4-11e4-97d2-00f5e4ed1917.png)

**Comment by silverwind** [comment]
Notebooks should be done, except syntax.

@Mottie would you mind digging through our git history to restore pygments themes? :stuck_out_tongue_winking_eye:

**Comment by Mottie** [comment]
I guess... the api docs are still using pygments as well.

Although, it'll have to wait until tomorrow, when I have a bit more free time.

**Comment by silverwind** [comment]
Yeah, no problem. If I remember correctly, we removed pygments for size concerns, which shouldn't be an issue any more. So let's keep them around :)

**Comment by Mottie** [comment]
And those graphs are [too sexy](https://screen.yahoo.com/ah-yes-show-lyme-disease-000000563.html)!

**Comment by silverwind** [comment]
Yahoo doesn't feel like providing that content at my location.
 
I was surprised a straight number like 90% fitted so perfectly :D

**Comment by Mottie** [comment]
It was a skit from SNL, Chris Kattan as Antonio Banderas... No no too sexy! LOL

**Comment by silverwind** [comment]
Banderas, lol

**Comment by Mottie** [comment]
Ok, all done... I had to add `#notebook` as a prefix to every selector so it would only target Jupyter notebook pages. That was the only way I could think of to ensure that the pygments `.highlight` selectors don't interfere with the other syntax highlighter scheme.

**Comment by silverwind** [comment]
:clap:

**Comment by ddavison** [comment]
:clap: :clap:

**Comment by Mottie** [comment]
I got antibiotics from the doctor to treat that, really!
