### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#235]
Noticed there's a slight conflict in which licence we state to use. The comment on top of the css says WTFPL while the package.json says BSD. I'd be fine with any MIT, BSD or GPL variant. Please state which licence you prefer.

cc: @Mottie @ddavison

**Comment by Mottie** [comment]
Yeah, I originally made the license WTFPL. Userstyles doesn't have this as an option. It's set to [Creative Commons Attribution-ShareAlike](http://creativecommons.org/licenses/by-sa/4.0/), so I guess none of the licenses match.

I really don't care what license we use, it'd be nice to keep it consistent.

**Comment by silverwind** [comment]
Just checked userstyles.org, they don't even have options for common open source licences it seems, just CC ones. From these, my preference would be [Attribution-NonCommercial](http://creativecommons.org/licenses/by-nc/4.0/).

**Comment by ddavison** [comment]
non commercial does seem like a good fit.  the license will require any worked based on our code to have proper attribution.

**Comment by silverwind** [comment]
I went with the permissive CC-BY-SA licence we already had set as default on the userstyle account as the default. I don't really have much of an opinion on whether someone should be allowed to sell our work, so I left it open.

**Comment by Mottie** [comment]
:trophy:
