### ISSUE TITLE
Wrong colors in Markdown rich diff

### ISSUE THREAD

**Issue by jawshooah** [StylishThemes/GitHub-Dark#236]
Here's an [example](https://github.com/brigade/overcommit/commit/de6f7f65581dfb211eb8f128c57f3b00570c1318?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8), and a screenshot:

![wrong colors](https://i.imgur.com/i5tJjPA.png)

**Comment by jawshooah** [comment]
Looks like the problem is only inside tables. Diffs look fine elsewhere.

**Comment by silverwind** [comment]
Fixed, thanks for the report!
