### ISSUE TITLE
Green search background color under blue links

### ISSUE THREAD

**Issue by simov** [StylishThemes/GitHub-Dark#238]
:wave: nice theme!

![green-color](https://cloud.githubusercontent.com/assets/1694112/8699137/e44ff50e-2b0b-11e5-9a92-1ee078cf5143.png)

I don't think that's the best background color when you have a link on top of it.

**Comment by silverwind** [comment]
that's actually yellow, but I agree it's hard to read. Maybe a neutral grey or a darker yellow is in order. Don't think it's possible to use a darker shade of the user-supplied color unfortunately.

**Comment by simov** [comment]
> Don't think it's possible to use a darker shade of the user-supplied color unfortunately.

I don't think I'm following you. Where else is this color used?

**Comment by silverwind** [comment]
I mean the color you specify on userstyles. It defaults to light blue, but can be user-supplied. I think a darker shade of the same color would be ideal for the highlight background, but because of certain limitations of CSS and userstyles, we can't really have it set dynamically. I'll try a grey I think.

**Comment by Mottie** [comment]
That is the search result word highlighter. It is styled for the repositories & issues, but not code & users... I got a fix incoming.

**Comment by Mottie** [comment]
https://github.com/search?q=default&ref=searchresults&type=Repositories
https://github.com/search?q=default&ref=searchresults&type=Code
https://github.com/search?q=default&ref=searchresults&type=Issues
https://github.com/search?q=default&ref=searchresults&type=Users

**Comment by silverwind** [comment]
Thanks @Mottie! Last i checked the parts around search highlights, the styles were a bit of a mess. I'll keep in mind to clean that up later.

**Comment by simov** [comment]
That's great, thank you @Mottie!

@silverwind got it! I'm not using the *styler* extension. I have my own and I'm just copying the raw css file and the extension injects it, really simple stuff. I like the ability to edit my files in sublime, ultimately I was going to fix it myself if it was something very annoying, but decided to give you a feedback.

Thanks again :+1:
