### ISSUE TITLE
Auto-formatting of linebreaks

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#239]
As discussed I think we could benefit from a tool that does consistent line breaks automatically at a certain width. We could run a grunt that task before every release.

Here's a possible plugin: https://github.com/csscomb/grunt-csscomb
And the confguration docs: https://github.com/csscomb/csscomb.js/blob/master/doc/configuration.md

I'd actually be fine if we force wrap at 80 chars because sometimes I'm on a pretty small screen. Any objections to that?

**Comment by silverwind** [comment]
CTRL-F "wrap" on https://github.com/csscomb/csscomb.js/blob/master/doc/options.md doesn't return an option to wrap at certain chars. Maybe it's not suitable after all.

**Comment by Mottie** [comment]
No objections here... can you do me a favor and check grunt-cssmin? I updated the modules and now when it compresses the source theme css, it is removing all but the `#notebook` definitions (see [twilight.min.css](https://github.com/StylishThemes/GitHub-Dark/blob/master/themes/twilight.min.css)).

**Comment by silverwind** [comment]
Doh, shouldn't have bumped the dependencies without testing. My fault.

It looks like we have gone from clean-css@2.2.23 to clean-css@3.3.6 with that update. Will investigate.

**Comment by Mottie** [comment]
Thanks!

**Comment by Poorchop** [comment]
This might be worth noting in a separate issue but it seems like GitHub's default CSS doesn't respect line breaks in code blocks. With this style applied, this results code blocks that overflow their container:

![untitled](https://cloud.githubusercontent.com/assets/5256208/9077133/7e00d212-3af8-11e5-8f06-2cd4d5271210.png)

The closest that I could come to a solution was using `word-break: break-all; white-space: pre-line` but using word-break is bad and messes up a lot of things:

![untitled1](https://cloud.githubusercontent.com/assets/5256208/9077199/1e7047be-3af9-11e5-8e3b-318ddfedf2d8.png)

You can find an example [here](https://github.com/Laverna/laverna/issues/265). The line breaks are a GitHub issue but the word-wrapping is an issue with the style.

**Comment by Mottie** [comment]
Hi @Poorchop!

I added those selectors to the selector at [line 164](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L164-L166) and have yet to run into it messing "up a lot of things". Do you have an example?

```css
  code {
    overflow: visible !important;
    word-break: break-all;
    white-space: pre-line;
  }
```

\* NOTE \* The `!important` flags were left out intentionally. Adding them does cause any `pre code` combo selectors to mess up and would require more definitions to remove the `word-break` & `white-space` settings.

**Comment by Poorchop** [comment]
When I say that it "messes up a lot of things," I mean in general that it is unfavorable over the behavior of `word-wrap: break-word`. If you look at the preceding code block after adding those selectors, then the word "devDependencies" will be split across two lines (might not be the case depending on your custom font/font size).

I just think that ignoring delimiters like white space is a bad idea, especially if it results in a single word being spread across two lines in a code block. I'm kind of curious as to why the style introduces this issue though since I don't see any word-wrapping rules, although it does style code blocks a little differently than GitHub's default CSS.

**Comment by silverwind** [comment]
Is it broken in Github's default style too? If so, I'd question if the pasted text has correct linebreaks at all or if it's corrupted somehow. If it's just broken in our style, we should remove non-color changes until it works as expected :)

**Comment by silverwind** [comment]
Looking at the example, the overflow issue is ours, while the wrap issue seems not ;)

**Comment by silverwind** [comment]
I see the code block in question is actually a single-line code block abused for multiline. The issue here is that we're working around a Firefox text selection bug (https://bugzilla.mozilla.org/show_bug.cgi?id=1123450) with `inline-block`, and I like to keep that workaround personally. I'll see what can be done.

**Comment by silverwind** [comment]
Fixed the overflow issue. I don't think we should fiddle with wordwrap there. Also, please open an seperate issue next time :wink:

**Comment by silverwind** [comment]
Ontopic here, maybe https://github.com/ben-eb/perfectionist is worth investigating.

**Comment by Mottie** [comment]
Nice find!

It does some weird stuff with indenting though:

```css

    .octofication .message, .panel-nav:not(.disabled):active, .diagram-icon:not(.active),
.full-commit .btn.btn-outline:hover, .btn.btn-outline:hover, .btn.btn-outline.zeroclipboard-is-hover,
:checked + .radio-label {
        border-color: #4183C4 !important;
    }
```

The `maxSelectorLength` option is set to `120` above

**Comment by silverwind** [comment]
Not bad. Looks like a bug to report. I think it naively assumes all selector lines start at zero indent.

**Comment by Mottie** [comment]
It also removed the `/*[[base-color]]*/` placeholder :(

**Comment by silverwind** [comment]
Care to report these? It seems our best bet yet on a formatter.

**Comment by Mottie** [comment]
Ok, I was trying to see if I could find the code and fix it... it's not very straight-forward.

**Comment by silverwind** [comment]
Sure, if you find it :)

**Comment by silverwind** [comment]
If everything fails, we could do our own formatter using the [PostCSS API](https://github.com/postcss/postcss/blob/master/docs/api.md).

**Comment by Mottie** [comment]
Opened https://github.com/ben-eb/perfectionist/issues/7 & https://github.com/ben-eb/perfectionist/issues/8

**Comment by silverwind** [comment]
:+1:

**Comment by Mottie** [comment]
Almost have everything set... one more issue to get around: https://github.com/ben-eb/perfectionist/issues/11

**Comment by Mottie** [comment]
Ok, all done... I did a quick test of the reformatted github-dark.css file and everything appears to be fine.

**Comment by silverwind** [comment]
Looking good! Maybe you can get into the habit of running the formatter before each release :yum:

**Comment by Mottie** [comment]
Oh yeah, I forgot to mention, you just need to use `grunt clean` to run perfectionist.
