### ISSUE TITLE
Wrong colors in Markdown code blocks

### ISSUE THREAD

**Issue by jawshooah** [StylishThemes/GitHub-Dark#240]
![SO BRIGHT](http://i.imgur.com/w4LM29H.png)

Here's my `build.json` for reference:

```json
{
    "theme"  : "Tomorrow Night Eighties",
    "color"  : "#008080",
    "image"  : "url(https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/images/backgrounds/bg-tile1.png)",
    "tiled"  : true,
    "attach" : "scroll",
    "tab"    : 4,
    "chrome" : true
}
```

**Comment by Mottie** [comment]
Yeah, this is because we updated the dependencies and for some reason cssmin is removing most of the theme definitions and only leaving the Jupyter `#notebook` definitions (mentioned in [#239](https://github.com/StylishThemes/GitHub-Dark/issues/239#issuecomment-121667524)).

**Comment by Mottie** [comment]
And by the way, I just updated the [Build wiki page](https://github.com/StylishThemes/GitHub-Dark/wiki/Build), the `build.json` now includes a `font` definition.

**Comment by jawshooah** [comment]
Thanks for the tip! And 27f5c88 appears to have fixed this, albeit temporarily. Shall I close?

**Comment by Mottie** [comment]
And @silverwind, I don't think the problem is with `clean-css`, I think it's with `grunt-contrib-cssmin`

**Comment by Mottie** [comment]
@jawshooah no, please leave it open for now. I don't like temporary fixes :wink:

**Comment by silverwind** [comment]
@Mottie clean-css does all the minifying work, so I think it's safe to assume the issue stems from it.

**Comment by silverwind** [comment]
@Mottie Could you provide some steps/output on what's wrong. If I run a custom build that pastes the minfied themes, it all looks correct. The twilight theme is 8185 characters in the source and is pasted with the same amount in the userstyle.

**Comment by Mottie** [comment]
I just changed the Gruntfile to use the src theme file... you'll need to switch it back to use the `.min.css` file

```js
config.themeFile = file === '' || file === 'default' ? '' : 'themes/' + file + '.min.css';
```

**Comment by silverwind** [comment]
Yeah, I did that. Wait, now I see the issue after activating this style.

**Comment by Mottie** [comment]
Hmm, actually you know what, I'm wrong. The css is minified correctly - sorry! I think it's the string replacement

**Comment by Mottie** [comment]
Ugh... nope that's working too.

**Comment by Mottie** [comment]
Yeah, there is something wrong with the minified css... it's all there, just not working correctly.

**Comment by silverwind** [comment]
Something is causing the style with `font-style:italic!important` to move before the background definition, which breaks out our concatenated background sections.

**Comment by silverwind** [comment]
Found it, fixed it. Please try again :)

**Comment by jawshooah** [comment]
Fixed indeed! :beers:

**Comment by Mottie** [comment]
Awesome, you rock :rocket:... I don't care what they say about you :wink:

**Comment by silverwind** [comment]
The issue was that cleancss does try to merge selectors with the same rules. In our case it saw the opportunity to merge a few italic rules to save a few bytes, unknowing that it broke our background hack in process. :wink:
