### ISSUE TITLE
Contributions overlay - hard to see

### ISSUE THREAD

**Issue by simov** [StylishThemes/GitHub-Dark#241]
![contrib-overlay](https://cloud.githubusercontent.com/assets/1694112/8794104/4b91d022-2f88-11e5-919c-84d2b4732acd.png)

It might be my TN monitor, but still. A slightly lighter color improves visibility.

**Comment by silverwind** [comment]
Thanks. We hadn't styled that one yet. I didn't even know you could click that graph :)

**Comment by simov** [comment]
:+1: :)

**Comment by Mottie** [comment]
Had to update this fix because now it is now completely graying out the contribution graph.
