### ISSUE TITLE
Gist updates

### ISSUE THREAD

**Issue by auscompgeek** [StylishThemes/GitHub-Dark#243]
Looks like GitHub has messed around with the CSS on Gist again.

On Gist lists (e.g. user's Gists, all Gists):

![screenshot from 2015-07-24 18-43-10](https://cloud.githubusercontent.com/assets/128854/8870795/e350b222-3233-11e5-93c0-d2a9876b2c74.png)

* The metadata count links (number of files, forks, comments and stars) are given the base colour rather than a grey like it is unstyled (`.gist-snippet-meta .gist-count-links > li > a`).
* Gist descriptions are left unstyled and unreadable (`.gist-snippet-meta .description`).

Everything else seems to be mostly fine for now.

**Comment by Mottie** [comment]
Hi @auscompgeek!

Thanks for letting us know about this issue. I'll have it fixed shortly in the master branch. I'll update userstyles either today or tomorrow as I hope to get #242 changes included.

**Comment by silverwind** [comment]
Looks like Gist finally switched from `.button` to `.btn` classes. I'm not removing `.button` yet, unless I'm sure it's used nowhere else on the site.

Going to do a few more fixes for Gist now.

**Comment by silverwind** [comment]
Should all be handled, thanks for reporting again.

**Comment by auscompgeek** [comment]
Oops! Looks like we forgot about the search suggestions again…

![screenshot from 2015-07-27 15-00-41](https://cloud.githubusercontent.com/assets/128854/8898916/5a4f3536-3470-11e5-806f-a36f5b70b877.png)
