### ISSUE TITLE
Closed issue notifications are green instead of red

### ISSUE THREAD

**Issue by jawshooah** [StylishThemes/GitHub-Dark#245]
With GitHub-Dark enabled: ![enabled](https://i.imgur.com/XGSh8JU.png)

And disabled: ![disabled](https://i.imgur.com/2YzzkWV.png)

**Comment by Mottie** [comment]
Hi @jawshooah!

Thanks for reporting this problem, I'll try to get that fixed ASAP.

**Comment by jawshooah** [comment]
Great, thanks for the quick response!
