### ISSUE TITLE
Wrong icon color for closed issues in Notifications view

### ISSUE THREAD

**Issue by simov** [StylishThemes/GitHub-Dark#246]
![closed-issue-default](https://cloud.githubusercontent.com/assets/1694112/8901008/e865ee78-344d-11e5-93f3-3c103c2a1460.png)
![closend-issue-dark](https://cloud.githubusercontent.com/assets/1694112/8901009/e87f974c-344d-11e5-8278-7cc952951f63.png)

Obviously this makes it harder to see the closed issues quickly.

Also this may apply for PRs as well (the PR icon) but I don't have such example at the moment.

**Comment by silverwind** [comment]
Looks like the fix in https://github.com/StylishThemes/GitHub-Dark/commit/f091ead66b861e67e49611b7b09002078eb1d6bf wasn't done properly, I'll have a look.

**Comment by silverwind** [comment]
Let me know if that works, I don't have any unread notifications right now.

**Comment by silverwind** [comment]
Had a typo, sorry.

**Comment by simov** [comment]
Seems to be working:

![closed-issues-color](https://cloud.githubusercontent.com/assets/1694112/8901454/a25f95a6-3451-11e5-925f-221403cba7b4.png)

For PRs I think they can be either:

- green: proposed
- red: closed (without being merged)
- purple: merged

So if a comment arrives in a PR, the color of the icon should be one of the above based on the state of the PR (but currently I don't have such cases to prove it or show it you).

**Comment by silverwind** [comment]
All colors should be there now. I took care to include purple (`state-merged`) and grey (`state-none`). Thanks!

**Comment by simov** [comment]
Thanks :+1:

**Comment by Mottie** [comment]
Doh, it looks good to me... oh well. Thanks for fixing it @silverwind.

Oh and if you don't have any unread notifications, go to the "All notifications" tab then open the console and type in:

```js
$('.list-group-item').removeClass('read').addClass('unread');
```
