### ISSUE TITLE
Highlighted tags text color off

### ISSUE THREAD

**Issue by keith** [StylishThemes/GitHub-Dark#248]
![screen shot 2015-07-27 at 12 06 33](https://cloud.githubusercontent.com/assets/283886/8915125/fecc3320-3457-11e5-8f38-33a078d6f5ed.png)

The text color of tags is off in the branch switcher dropdown. It should probably look the same as branches:

![screen shot 2015-07-27 at 12 07 28](https://cloud.githubusercontent.com/assets/283886/8915143/16db73fe-3458-11e5-947f-85fa6d125940.png)

**Comment by Mottie** [comment]
Hi @keith!

Thanks for reporting this problem, I'll have it fixed shortly.

**Comment by keith** [comment]
Thanks @Mottie !!
