### ISSUE TITLE
Bold text not as striking as on white background

### ISSUE THREAD

**Issue by simov** [StylishThemes/GitHub-Dark#250]
![bold-white](https://cloud.githubusercontent.com/assets/1694112/9021364/7ee4610c-3847-11e5-8fb7-80ff46afd19a.png)
---
![bold-black](https://cloud.githubusercontent.com/assets/1694112/9021366/828f6f68-3847-11e5-9b17-1abdd8371143.png)
---
![bold-lighter](https://cloud.githubusercontent.com/assets/1694112/9021367/8548e11c-3847-11e5-8591-4d1139e6fb89.png)
---
As you can see the bold text on white background easily catches your attention, even if you're not looking directly into it.

The second screenshot shows how the bold text looks like ATM. I hardly can distinguish the bold from the regular text and it certainly can't catch my attention.

On the third screenshot I'm using lighter gray color `#e4e4e4` to make the bold text stand out a little bit.

Now I'm not saying that this should be exact color, nor that it should be pure white, but my point is that the bold text should catch the user's attention easily, because often times it represents important information.

**Comment by silverwind** [comment]
Interestingly, the bold in Github's style doesn't use any brighter shade than the default body text `#333`, so it's more of a psychological thing that it seems darker ;)

I agree that we could make it slightly brighter, thought I could also see making body text slightly darker (currently `#c0c0c0`).

**Comment by simov** [comment]
Yes it's weird, I'm only saying what the bold text currently feels like for me. I'm not sure if making the body text darker than what it is ATM would be good. It may make it harder to read if it's darker than that, I personally work with very dim monitor brightness.

**Comment by silverwind** [comment]
I'd be fine going for `#c4c4c4` or similar. Let's hear what others think about this.

**Comment by Poorchop** [comment]
The third screenshot looks good. `#c4c4c4` looks like it provides enough contrast to stand out as well.

**Comment by Mottie** [comment]
Sounds good to me too :yum:

**Comment by silverwind** [comment]
Went with `#e6e6e6` so it properly stands out.

**Comment by simov** [comment]
One side effect of that change is that the [**bold links**]() becаme *white* instead of [blue]()

**Comment by silverwind** [comment]
That's a bug :wink: 

**bold** ~~**bold-strike**~~ [**bold-link**]() ~~[**bold-strike-link**]()~~

**Comment by simov** [comment]
Yep you're right. BTW with risking to get too annoying my point with this one was that the `<strong>` text does not have good enough contrast among the rest of the text with same font size. The headers on the other hand are with much higher font size to begin with, so you can easily see them without color change. Of course now you can see them even better, but now they may shadow the content, because lots of readmes have small sections resulting in a lot of headers with tiny text between them.

Just my thoughts again, I can easily override the header styles in the next file.css after this theme :+1:

**Comment by silverwind** [comment]
Headers alone shouldn't be changed, unless they contain bold text.

# this is **bold**
## this is **bold**
### this is **bold**
#### this is **bold**

**Comment by simov** [comment]
Ok, enough staring at headers for today :grinning: they probably were that way. I just tested with a previous commit, nevermind probably my eyes plays tricks on me.

**Comment by Mottie** [comment]
@silverwind When you get a chance, would you please look at this again? The bold elements in the headers are darker.

># **bold** with a [link]() and some `code`
## **bold** with a [link]() and some `code`
### **bold** with a [link]() and some `code`
#### **bold** with a [link]() and some `code`

> Quote block text color

Also, @un1versal is requesting that the base text color be set to `#eee` to match the text color of the textarea while you type in a comment. Personally I think `#eee` is way too bright. Also, he would like the quote blocks brighter - set to the current text color of `#c0c0c0`.

**Comment by un1versal** [comment]
`#c0c0c0` is far too dull contrast for reading text

**Comment by silverwind** [comment]
Will check out. Instead of hijacking a old closed issue, please open a new one in the future, it's easier to track.
