### ISSUE TITLE
Extract only .markdown-body styles

### ISSUE THREAD

**Issue by simov** [StylishThemes/GitHub-Dark#252]
:wave: 

Would it be possible/easy to extract only the `.markdown-body` related styles from this theme, like it's done [here](https://github.com/sindresorhus/github-markdown-css/blob/gh-pages/github-markdown.css)?

I'm using the above styles in my [markdown-viewer](https://chrome.google.com/webstore/detail/markdown-viewer/ckkdlimhmcjmikdlpkmbgfkaikojcbjk) extension, and I certainly don't need the styles for the entire site there. On the other hand I though it would be cool to have the *GitHub-Dark* theme as option there.

**Comment by silverwind** [comment]
I'm not totally certain all markdown styles are descended `.markdown-body`, and there ought to be a few hacks in place, which wouldn't be needed in a standalone style. You might be better off starting from scratch then trying to extract the styles, I think a few styles for `background` and `color` would get you 90% there. :wink:

**Comment by simov** [comment]
Yep, most of the styles that I need are probably stable enough to just hardcode them. And I certainly don't need the pygment styles as I'm using in browser syntaxhighlighter anyway. :+1:
