### ISSUE TITLE
User: contributions calendar: legend for Halloween colours is broken

### ISSUE THREAD

**Issue by auscompgeek** [StylishThemes/GitHub-Dark#261]
:stuck_out_tongue_winking_eye:

With the theme off:

![gh-contrib-halloween-light](https://cloud.githubusercontent.com/assets/128854/10862724/fba6e88c-8008-11e5-927a-b15e4e2b5ca6.png)

**Comment by silverwind** [comment]
Fixed!

![screen shot 2015-10-31 at 1 44 47 pm](https://cloud.githubusercontent.com/assets/115237/10863654/9b0bfe14-7fd5-11e5-8279-c5578a27e586.png)

@Mottie time for a quick release?

**Comment by auscompgeek** [comment]
Nice! I think the brightest colour should be a bit more yellow though.

**Comment by silverwind** [comment]
Hmm, let me tweak those colors a bit.

**Comment by silverwind** [comment]
Spooky enough?

![screen shot 2015-10-31 at 2 01 10 pm](https://cloud.githubusercontent.com/assets/115237/10863702/e2982986-7fd7-11e5-81e8-884e126a8fc5.png)

**Comment by auscompgeek** [comment]
I love it. :+1:

**Comment by auscompgeek** [comment]
Shame that Halloween is over now here. I wanted to enjoy these calendars a bit longer.

**Comment by silverwind** [comment]
I think these colors well be active for a week or so, if I recall correctly.

**Comment by Mottie** [comment]
They only kept the colors for a day :disappointed:
