### ISSUE TITLE
Big update is coming

### ISSUE THREAD

**Issue by simov** [StylishThemes/GitHub-Dark#263]
https://github.com/blog/2085-a-new-look-for-repositories

Should I opt in for the new design, or should I wait for the end of the two weeks period before migrating?

**Comment by simov** [comment]
> Hmm, I don't see a way to opt-in yet...

Yep that's pretty fresh update and I just got excited about it. If the upcoming work is pushed into separate branch I can be your beta tester :)

**Comment by silverwind** [comment]
Can't find that opt-in either, sounds like it's not live yet. I'm not a fan of `*` rules because it makes it easy to miss changes. I like to style each border invididually, actually.

As for cleaning up unused selectors: Still a ton of work I assume. I'd rather start from scratch again ;)

**Comment by Mottie** [comment]
LOL ok, start from scratch it is :sweat_smile: 

What ideas did you have for the layout? Do you want to keep it as sections for background color, border, text color, etc? or just define each element individually and let the css minify sort it all out?

**Comment by silverwind** [comment]
If you really wanna try, here's how I'd start:

- Download copies of all CSS files currently in use. Should be at least 2-3 files, maybe more. Make sure to visit al sub-sites like Gist, Developers etc.
- Run some kind of preprocesser that removes all non-color rules, so we're left with background, border, color styles.
- Merge these selectors through a minifier.
- Change colors.
- Apply special tweaks like filters and other fixes from the current stylesheet.

I'd wager the new sheet might not be much smaller. GitHub's selectors are usually very over-qualified :wink:.

**Comment by ThePsionic** [comment]
@simov @Mottie @silverwind you should be able to opt-in now by visiting any repo

**Comment by Mottie** [comment]
I'm still not seeing it... maybe you need to be a [Developer Program Member](https://developer.github.com/)?

**Comment by mkoch227** [comment]
CSS-wise, it looks like not much has changed.  The only thing "off" is the styling for the selected nav item, which uses the `selected` class.  See below for a visual representation of the changes.
![screen shot 2015-11-16 at 9 10 22 pm](https://cloud.githubusercontent.com/assets/333430/11200846/0303bd3a-8ca7-11e5-9a5d-1fba8167bc14.png)

**Comment by simov** [comment]
I'm not seeing it either .. :worried:

**Comment by silverwind** [comment]
Guess they are rolling it out in batches, nothing here yet either.

**Comment by mkoch227** [comment]
Since I no longer have the previous view, would anyone mind sending the sections of the stylesheet that should be affecting the active tab? I can try adding the new CSS selectors to the existing stylesheet to see if it works with the new CSS classes. It's hard for me to tell which selectors are targeting the active tab now that I no longer have the original view

**Comment by ThePsionic** [comment]
I think the border is controlled by [github-dark.css#596](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L596) and the color itself by [github-dark.css#837](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L837), @mkoch227. I don't know for sure but [github-dark.css#1395](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L1395) might also be involved in this.

**Comment by silverwind** [comment]
You can add the new class to all styles that also affect `.pagehead-tabs-item.selected`.

**Comment by mkoch227** [comment]
So I added `.js-selected-navigation-item.selected.reponav-item` wherever I found `.pagehead-tabs-item.selected`, and it seems to look quite nice:

![screen shot 2015-11-17 at 4 02 35 pm](https://cloud.githubusercontent.com/assets/333430/11224844/0568d404-8d45-11e5-8c1c-30b22c65e2fb.png)

If everything looks good, I opened #264 which contains the necessary changes.

**Comment by silverwind** [comment]
I finally got access to the preview, will finish this shortly ;)

**Comment by simov** [comment]
Me too! BTW they mention something about giving them feedback, so do you know where is the appropriate place to send them feedback about the new design and in general?

I would really like to see some smarter header for example, when I scroll down I want some simplified fixed header to stay on top with a bunch of links for quick access.

**Comment by keith** [comment]
I've started seeing this banner this morning for the preview as well:

![screen shot 2015-11-18 at 10 58 46](https://cloud.githubusercontent.com/assets/283886/11250859/668613e8-8de3-11e5-9517-55ca181f41dd.png)

**Comment by silverwind** [comment]
@simov I use https://github.com/contact to contact them.
@keith fixed on master already.

**Comment by simov** [comment]
@silverwind I actually got response from them - Amazing!
Will report if I find any bugs with master.

**Comment by ddavison** [comment]
they're typically very fast, @simov :)

**Comment by EvanHahn** [comment]
Things are looking good for me with the latest version. Should we close this issue?

**Comment by simov** [comment]
Yep, working for me too.
