### ISSUE TITLE
Home: pagination button is unstyled

### ISSUE THREAD

**Issue by auscompgeek** [StylishThemes/GitHub-Dark#265]
The pagination button on the home page is now unstyled, as of yesterday. Specifically, the button is now white and the Octocat spinner is now GitHub's .gif as a background-image on the button.

The new selectors in question are `.ajax-pagination-form .ajax-pagination-btn` (along with `:hover` and `:focus`) and `.ajax-pagination-form.loading .ajax-pagination-btn`.

**Comment by auscompgeek** [comment]
What about the spinner?

**Comment by silverwind** [comment]
Fixed, didn't realize there was a spinner.
