### ISSUE TITLE
Gist user's profille avatar

### ISSUE THREAD

**Issue by simov** [StylishThemes/GitHub-Dark#267]
![gist-avatar](https://cloud.githubusercontent.com/assets/1694112/11409273/7104c80c-93c7-11e5-9196-a672a0689447.png)

Not your own profile, but someone else.

**Comment by silverwind** [comment]
Layout bugs are usually GitHub bugs, and this is definitely one, as it shows with the stylesheet too. I can add a hack to fix it, but could you report it to them first?

**Comment by silverwind** [comment]
Contacted them.

**Comment by silverwind** [comment]
They have it on their tracker.

**Comment by simov** [comment]
> Layout bugs are usually GitHub bugs

Right, I totally missed that.

I was too lazy to disable my extension, so I just checked the URL in Firefox where the bug is not present.

**Comment by silverwind** [comment]
Looks like they fixed it!

**Comment by simov** [comment]
Yep :sparkles:
