### ISSUE TITLE
Links to labels don't get recoloured

### ISSUE THREAD

**Issue by ThePsionic** [StylishThemes/GitHub-Dark#268]
As seen on [this README.md](https://github.com/HearthSim/hs-bugs/blob/master/README.md), when using a custom link colour, the links to the labels don't get recoloured. All other links get recoloured as intended.

![blob](http://i.imgur.com/zxn4oPa.png)

**Comment by silverwind** [comment]
Should be fixed, thanks. The underlying issue is with our hackish way of styling labels.

**Comment by silverwind** [comment]
Looks like this isn't the proper fix, investigating.

**Comment by silverwind** [comment]
Ok, should be good now :wink:
