### ISSUE TITLE
Org-Teams-Team-Member-Options Dropdown

### ISSUE THREAD

**Issue by simov** [StylishThemes/GitHub-Dark#269]
I guess you have to be an owner for that org:

![dropdown](https://cloud.githubusercontent.com/assets/1694112/11455985/cbfc8370-967f-11e5-936a-b40025e94c79.png)

The text should be *white* on hover.

Here is an example URL: `https://github.com/orgs/request/teams/contributors` - Contributors is the team.

**Comment by silverwind** [comment]
Yeah, looks pretty broken. Here's a link:

https://github.com/orgs/StylishThemes/teams/Github-Dark

**Comment by silverwind** [comment]
Partly fixed. There's a weird hover rendering on the last item, not sure where it's coming from:

![screen shot 2015-11-29 at 11 06 11 am](https://cloud.githubusercontent.com/assets/115237/11456446/80f10112-9689-11e5-9beb-29e5ea92a661.png)

**Comment by silverwind** [comment]
Done! The red items shouldn't shift by 1px when hovering now too. Thanks for reporting.
