### ISSUE TITLE
Not working in new Github's style

### ISSUE THREAD

**Issue by deniszh** [StylishThemes/GitHub-Dark#270]
Hello!
Couple of days ago Github asked me do I want to test new web interface. "Sure", I said. It works great with current style, except top tabs are still white when switched on:
<img width="1440" alt="screen shot 2015-11-30 at 09 28 12" src="https://cloud.githubusercontent.com/assets/1227222/11467386/0dd5f3c6-9748-11e5-9572-c8cf06752cec.png">
<img width="1438" alt="screen shot 2015-11-30 at 09 28 48" src="https://cloud.githubusercontent.com/assets/1227222/11467387/10ee9e64-9748-11e5-8cf4-c6988c7cf572.png">
Unfortunately, I don't know CSS and don't know how to enable new web interface - I didn't find any switches or obvious cookies for enabling that.

**Comment by ThePsionic** [comment]
This has been fixed by #264 already. Update your style in Stylish.

**Comment by deniszh** [comment]
Cool, thanks!
