### ISSUE TITLE
Diff blocks are no longer gray

### ISSUE THREAD

**Issue by ThePsionic** [StylishThemes/GitHub-Dark#274]
![a](http://i.imgur.com/IfkrYng.png)
As far as I know, the white blocks were always normally gray?

**Comment by Mottie** [comment]
Hi @ThePsionic!

This was fixed in https://github.com/StylishThemes/GitHub-Dark/commit/fb42a9d7c13ed74998c54f21f6641717554dd06e

Userstyles.org was just updated as well :grinning:
