### ISSUE TITLE
Firefox: Checkboxes and Radios Buttons without AGENT_SHEET

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#275]
This came up in https://github.com/StylishThemes/GitHub-Dark-Script/issues/1#issuecomment-166144225. When the style is applied without user agent privileges (which only Stylish and other extensions have the ability to do so), checkbox and radio button styling breaks.

This is a longstanding Firefox bug and we could attempt to either `-moz-appearance: none` or go with some sort of hack using `:before` and `:after`, or even better, contribute a fix to Firefox :wink:.

**Comment by Mottie** [comment]
Sadly `:before` and `:after` doesn't work on `input` elements.

**Comment by silverwind** [comment]
I'm surprised they don't work.

The root of this issue seems to be that the UA rules for checkboxes are [applied with `!important`](https://github.com/mozilla/gecko-dev/blob/719ce6825cbbcce1ba2031611fa0dd94dc14b41e/layout/style/forms.css#L561-L573) and `-moz-appearance: none` apparently [can't get rid of them](https://bugzilla.mozilla.org/show_bug.cgi?id=605985) for some reason. Guess we're blocked until this is fixed in Firefox.

Here's something to test: http://codepen.io/silverwind/pen/XXNbWv?editors=110

**Comment by Mottie** [comment]
Yeah, I guess webkit treats checkboxes like a container, but Firefox doesn't.

Check out the input text type, it's even weirder: http://codepen.io/Mottie/pen/EPNjyj?editors=110

**Comment by silverwind** [comment]
There's [this explanation](http://stackoverflow.com/a/4660434) on why pseudo elements don't work on `<input>` as they're self-closing tags. Still, Chrome violates that rule on checkboxes :laughing:.  Guess I'll have to dig deeper into Firefox's source and see if I can fix `-moz-appearance: none` myself, and maybe submit them a patch :wink:

**Comment by Mottie** [comment]
Sadly, I don't know any other language like C or Java, or whatever Firefox uses in their source. So, I'm no help there :disappointed:

**Comment by silverwind** [comment]
The language is usually not the issue. If you know JS, you can contribute simple fixes to C++. The issue with Firefox for me is finding the right spot in the code for the fix and enduring the long time it takes to build and test the changes.

**Comment by silverwind** [comment]
The bug will be finally fixed in 54 🎉 . From the [changelog](https://developer.mozilla.org/en-US/Firefox/Releases/54#CSS):

> <input> elements of types checkbox and radio with -moz-appearance: none; set on them are now non-replaced elements, and can now be styled with significantly more CSS properties including border and background-color (bug 418833, bug 605985, bug 1320732).

We can't really drop `AGENT_SHEET` because of scrollbars, but at least styled checkbox will work in the script once Firefox 54 goes live.

**Comment by silverwind** [comment]
Or actually, I think we can drop `AGENT_SHEET` as we don't touch Firefox's scrollbars. Yay.

**Comment by silverwind** [comment]
Let's close this and keep `AGENT_SHEET`, I think it helps on raising specificity.
