### ISSUE TITLE
ZenHub sign-in floater not styled

### ISSUE THREAD

**Issue by jawshooah** [StylishThemes/GitHub-Dark#279]
Don't know how much you guys care about ZenHub, but I've noticed this little sign-in box floating in the bottom-right of every GitHub page the last few days:

![ZenHub sign-in floater](https://www.dropbox.com/s/gzkl7e34yikjyt9/Screenshot%202016-01-01%2016.12.16.png?raw=1)

**Comment by Mottie** [comment]
Hi @jawshooah!

Thanks for reporting this problem... the fix is in the master branch. We'll update userstyles.org soon.

**Comment by jawshooah** [comment]
Awesome, thanks for the quick fix!
