### ISSUE TITLE
Recently edited branch line

### ISSUE THREAD

**Issue by keith** [StylishThemes/GitHub-Dark#280]
Looks like this line is left unstyled

<img width="271" alt="screen shot 2016-01-01 at 14 03 08" src="https://cloud.githubusercontent.com/assets/283886/12072445/43ee91ac-b093-11e5-87de-e33c2e0d4197.png">

**Comment by Mottie** [comment]
Hi @keith!

Got a link to that page?

**Comment by keith** [comment]
It only shows for branches _you_ have recently pushed to. So you have to push commits to 2 branches, then hit the main repo page to see it.

**Comment by Mottie** [comment]
Ok, how about sharing a selector, or providing a PR? :grin:

**Comment by keith** [comment]
I'll grab it the next time I see it!

**Comment by Mottie** [comment]
Ok... I'll go ahead and push a new release then.

**Comment by keith** [comment]
:+1: yea it doesn't stick around. It's only if you've pushed to a branch in the last short amount of time.

**Comment by Mottie** [comment]
Grrr LOL... I just pushed a new release.. oh well

**Comment by keith** [comment]
No worries! Thanks @silverwind  & @Mottie

**Comment by silverwind** [comment]
Well that was easy to repro :smile: , sorry about that @Mottie 

```
git checkout -b "test-branch-1"
git commit --allow-empty -a -m "test"
git push origin test-branch-1

git checkout -b "test-branch-2"
git commit --allow-empty -a -m "test"
git push origin test-branch-2
```
