### ISSUE TITLE
Theme Request: Google Inbox Dark 

### ISSUE THREAD

**Issue by jawshooah** [StylishThemes/GitHub-Dark#281]
Not sure where to send a request for a theme, but this is the most actively maintained @StylishThemes repo, so I'll put it here (please let me know where it should go instead!)

Google Inbox is awesome, but it's blindingly bright. I'd love to see @StylishThemes put together a dark theme, since you guys have done such an awesome job with GitHub, StackOverflow, etc.

**Comment by ddavison** [comment]
gmail already does have a dark theme, and a theming system. have you looked into that yet?

**Comment by jawshooah** [comment]
Not Gmail, Inbox. It's a different product. inbox.google.com

**Comment by Mottie** [comment]
I found this one: https://userstyles.org/styles/114870

If you think we'd do better job, then maybe I'd consider modifying that style; but I don't want to take on more work right now.

**Comment by jawshooah** [comment]
Ah, probably should have searched userstyles.org before opening this :blush:

That one is alright, but there are some glaring style issues:
  - read/unread emails are too difficult to distinguish
  - email text background is still bright white
  - helper links added by Inbox (e.g. "View Issue", "View Pull Request" for GitHub emails) are an unattractive color, which can't be configured

It's usable for now, but I'd definitely love to see you guys take a crack at it. But I completely understand if you don't have time to take on a new project right now.

**Comment by silverwind** [comment]
Unfortunately, I don't think anyone of us here is going to style a site they don't use extensively. It's just too much work to keep up with site changes (and a good style needs permanent maintenance). I'd suggest you take a look at [global styles](https://userstyles.org/styles/browse/global) so you can toggle any site to dark mode on-demand.

I still plan to release a global dark style of my own, but the one I'm using is not really in a finished state by any means. :wink:

**Comment by Poorchop** [comment]
@jawshooah you could use the style that Mottie linked as a baseline and tweak it to match the StylishThemes palette. I've done it myself for a few sites and it's easy when someone has already done the work of identifying most of the necessary selectors.

**Comment by ddavison** [comment]
I totally forgot google was working on Inbox.. i'm so used to gmail :)  sorry @jawshooah

**Comment by silverwind** [comment]
I'm sorry, but as I said, I don't think anyone here is motivated to style a site we don't use. If you come up with something yourself, we can of course include it in the organization :)

**Comment by stevenette** [comment]
Oh thank god. I have just had a hell of a time upgrading hangouts, gmail to inbox, etc ad naseum and then inbox.google was so damn bright. This is literally the only forum I could find on it. There were no skins, themes, modes, or anything in dark mode. That is until I found out a couple years ago I downloaded some skin theme thing called Deluminate? I always had it off for some reason, I turned it on and inbox went dark! I can see again!

**Comment by Mottie** [comment]
If you ever run into a situation where you can't find a style and don't want to be blinded, check out the [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh) Chrome extension... it essentially inverts everything on the page so things may not look perfect, but it helps a little.

**Comment by Mottie** [comment]
Oh, also check out Flux - https://justgetflux.com/ - it's an app, not a browser extension, that removes some of the blue light that your monitor displays. It also adjusts these colors based on the time of day. It's great for coding, but not so good when you're designing with colors.

**Comment by zamber** [comment]
This possibly can be closed as it seems that someone is maintaining a dark user style for Inbox - https://userstyles.org/styles/148289/dark-inbox-by-dm
