### ISSUE TITLE
Replace Grunt with a build script

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#282]
So, `grunt` is going a bit out of fashion and it's getting hard to find plugins. There's `gulp` but I'm not really sure I want to tie us into another ecosystem which may or may not survive in the long-term.

All our tools expose a Node.js API, so I think a `build.js` script might be in order. It definitely is much more flexible than `grunt`, `gulp` or even `make` could ever be.

@Mottie I'll get started on it once we know which of the current Grunt tasks we need to replicate. Do we really need the custom style generation with `build.json`? I'm not sure anyone's really using it. Also, what about `user` and `usermin`? I think we can drop `user`? Oh, and are you using `dev`?

**Comment by Mottie** [comment]
Go for it... 

The only build I use now is `grunt user` as it creates the version I copy and paste into userstyles.org.

Yeah, I think we can drop the custom build as well since we have the userscript up and running.

**Comment by silverwind** [comment]
I'll make sure to also include a version bumping mechanism that generates the Changelog from recent commits. Are you fine with using a `CHANGELOG.md` for that purpose?

**Comment by Mottie** [comment]
Sure, it'll save me some work :grin:

**Comment by Mottie** [comment]
Or, we could just drop the change log?

**Comment by silverwind** [comment]
So, you never used `usermin`? Maybe we shall I drop minification completely, until size is a concern again?

**Comment by Mottie** [comment]
Yeah, I don't minify at all since we got a little more breathing room on userstyles.

**Comment by silverwind** [comment]
Hmm yeah, let's drop the changelog. The commit history ought to be good enough :)

**Comment by silverwind** [comment]
Might be a good opportunity to use [shelljs](https://github.com/shelljs/shelljs).

**Comment by silverwind** [comment]
Having used `gulp` recently on one of my projects, I think it'd be a great replacement for `grunt`. The nice thing about it is that you can use custom code sections everywhere in the pipeline, and the plugin ecosystem is vast, too.

**Comment by Mottie** [comment]
If you want to work on it, I don't mind. I haven't used gulp that much but I'm sure I can figure it out.

**Comment by silverwind** [comment]
Will follow up with something for https://github.com/StylishThemes/New-GitHub-Dark.
