### ISSUE TITLE
Heavy check mark (✔) hard to see on black background

### ISSUE THREAD

**Issue by leoj3n** [StylishThemes/GitHub-Dark#283]
The check mark "✔" is nearly invisible. Is this to be expected or something to be fixed?

Any other unicode characters that need to be considered?

http://graphemica.com/%E2%9C%94

**Comment by silverwind** [comment]
Not sure we can do anything about colored unicode, unless there's a way for CSS to select single letters. GitHub's image emoji are already [handled](https://github.com/StylishThemes/GitHub-Dark/blob/d2606d5683271b82e1fc6bfab79771cb01a52774/github-dark.css#L1007-L1019) by the way: :heavy_check_mark:

**Comment by silverwind** [comment]
We might be able to use [unicode-range](https://developer.mozilla.org/en/docs/Web/CSS/@font-face/unicode-range) to override the affected codepoints. Anyone care to compile a list of dark unicode characters?

**Comment by Mottie** [comment]
Do you have an example of where the checkmark is being used? The network graph is the only place we use `#000` as a background color.

**Comment by leoj3n** [comment]
@Mottie https://github.com/mauricecruz/zero-base-themes#notice

**Comment by Mottie** [comment]
This is what I see on that page

![2016-01-30 10_13_42-mauricecruz_zero-base-themes_ chrome devtools extension that loads themes using](https://cloud.githubusercontent.com/assets/136959/12696857/45fd8f26-c73a-11e5-914c-e9a50aceb3cd.png)

Are you seeing something different?

**Comment by leoj3n** [comment]
![image](https://cloud.githubusercontent.com/assets/990216/12696873/9624a80e-c73a-11e5-8ac6-e27716b2a51b.png)

Google Chrome Canary on OS X

**Comment by Mottie** [comment]
Ahh, so the text is being replaced. Would you copy/paste the image element here.

**Comment by Mottie** [comment]
Hmm, @silverwind can you see what you can do... I don't own an Appl€ device, so...

**Comment by leoj3n** [comment]
![image](https://cloud.githubusercontent.com/assets/990216/12696901/4ab278aa-c73b-11e5-8654-1aa5345bcf0e.png)

Doesn't look like an image from Developer Tools inspector (above). Setting an inline text color of the `<p>` with `!important` doesn't affect the check mark. If I do so on say google.com the check mark respects the style and inherits the color. Strange.

**Comment by silverwind** [comment]
Well, these are unicode glyphs. Github uses System fonts so the rendered glyph will be dependant on the OS. I'd say this is more of a design issue of Apple's glyphs than an issue specific to this style.

I assume Google uses a Webfont that has the `color`-respecting property of the glyph set.

**Comment by leoj3n** [comment]
Looks like this is the culprit:

```css
.markdown-body {
  font-family: "Helvetica Neue", Helvetica, "Segoe UI", Arial, freesans, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
}
```

If I change that to just:

```css
.markdown-body {
  font-family: "Helvetica Neue";
}
```

the heavy check mark is rendered like normal.

**Comment by silverwind** [comment]
Should be fixed, thanks!

**Comment by silverwind** [comment]
Just to test:

Apple: ©®™▪◼◾♠♣✔✖➕➖➗➰⬛〰
Segeo + Apple: 🎶🎼💱💲🔃🔙🔚🔛🔜🔝

**Comment by silverwind** [comment]
Really fixed all of them now. Turns out Github does add a `g-emoji` element for code points it considers to be Emojis, the Checkmark isn't one of them, so I was able to cleanly invert those. Also created a script to generate the rules because I'm bad at math.

The `Segeo UI Emoji` font isn't handled yet, I think it's a icon font exclusive to Windows 10 which I can't test.

**Comment by Mottie** [comment]
Hmm, none of the emoji you posted in this thread are being automatically replaced.

![2016-01-30 18_23_24-heavy check mark hard to see on black background issue 283 stylishtheme](https://cloud.githubusercontent.com/assets/136959/12699389/1139cdd2-c77f-11e5-8f38-c6c7cfc0c145.png)

Interestingly, some do get replaced in my gmail.

![2016-01-30 18_28_37- github-dark heavy check mark hard to see on black background 283 - wowm](https://cloud.githubusercontent.com/assets/136959/12699402/65b06b46-c77f-11e5-9cb0-86fe42986170.png)

**Comment by silverwind** [comment]
Firefox on OS X:
![screen shot 2016-01-31 at 10 27 21 am](https://cloud.githubusercontent.com/assets/115237/12701292/45799092-c805-11e5-89b9-d59c4b94b69e.png)
Not sure why your emoji have such a dark shade on Windows.

**Comment by Mottie** [comment]
The darker ones are being replaced:

```html
<g-emoji alias="black_medium_small_square" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/25fe.png">◾</g-emoji>
```

and an `invert(70%)` is applied on it. If I disable that definition in the dev panel, a `body { color: #c0c0c0 !important; }` is applied and all the colors match. So, it looks like the unicode character isn't being replaced by the image.

**Comment by silverwind** [comment]
Try my latest change! I changed the invert so the outcome should be closer to `#c0c0c0` and made it apply only to fallback images (which I see here on Firefox/Windows 7).

**Comment by Mottie** [comment]
Looks good! Thanks!!

**Comment by silverwind** [comment]
Argh, turns out this broke OS X pure unicode characters again, had to remove `> img`.

**Comment by leoj3n** [comment]
:+1:  Thanks for all your hard work on this @Mottie and especially @silverwind :bangbang:
