### ISSUE TITLE
Contributors in package.json

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#287]
We're up to 20-some contributors (@ddavison is in there twice :wink:), and the "contributors" section of the [`package.json`](https://github.com/StylishThemes/GitHub-Dark/blob/master/package.json) needs to either be updated or maybe moved to a separate file if we plan on continuing to update the list.

I mean, it's awesome that we have contributors! I would just like less work, and all of the same information can be found in the graphs: https://github.com/StylishThemes/GitHub-Dark/graphs/contributors

What do you guys think?

**Comment by ddavison** [comment]
i'm only in there once :P  

as far as this issue goes, it wouldn't be too difficult to make a script that spits out all git authors to that file

**Comment by Mottie** [comment]
Oh, I thought you were in there listed as ddavison and sircapsalot.

And thanks!

**Comment by silverwind** [comment]
Let's do an (AUTHORS)[https://github.com/nodejs/node/blob/master/AUTHORS] file.

**Comment by Mottie** [comment]
That sounds like a plan!

**Comment by silverwind** [comment]
Don't do it manually, there's a script to generate these. I'll look for it.

**Comment by ddavison** [comment]
sure thing.. sounds easier. almost done :)

**Comment by ddavison** [comment]
I already have one @silverwind

**Comment by ddavison** [comment]
https://github.com/StylishThemes/GitHub-Dark/commit/0e839af97b5d2b012e5cf33cb11b7de50fa5cebf
