### ISSUE TITLE
Tab width issue in diffs

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#289]
Something seems wrong about the tab width at [this line](https://github.com/sindresorhus/public-ip/pull/10/files#diff-2cce40143051e25f811b56c79d619bf5R23), it is rendered a a single space for some reason.

**Comment by Mottie** [comment]
It looks like the diff changed...

When I changed my tab size to `8`, it looked like it was rendering properly.

**Comment by silverwind** [comment]
Looks like this is actually working as intended. The diff markes +/- push zero indented lines right by 1 character and the tab is just one more character to the right, not fixable I think.
