### ISSUE TITLE
Theme request: Obsidian

### ISSUE THREAD

**Issue by VerstandInvictus** [StylishThemes/GitHub-Dark#290]
### Feature Request

I would love to see Obsidian added as a code theme, if possible.

http://color-themes.com/?view=theme&id=563a1a6180b4acf11273ae3d

Thanks for considering!

**Comment by ddavison** [comment]
Obsidian.. such a great theme.  loved using that theme, before i found Zenburn.

**Comment by silverwind** [comment]
This looks to be a good resource for it: https://github.com/mekwall/obsidian-color-scheme

**Comment by Mottie** [comment]
Does anyone else want to take this one and run with it? :stuck_out_tongue_closed_eyes: 

If not, I'll see what I can do, but not until tomorrow.

**Comment by Mottie** [comment]
It's not perfect because of the weird syntax highlighter that GitHub is using.

Check it out here: https://stylishthemes.github.io/GitHub-Dark/

**Comment by VerstandInvictus** [comment]
Looks great to me. Thanks!
