### ISSUE TITLE
File review of a pull request is unstyled

### ISSUE THREAD

**Issue by bacongobbler** [StylishThemes/GitHub-Dark#293]
Hey! Thank you for the project. Been using it for months and it's been awesome! I just noticed this morning that when doing a file review, the header for showing files are unstyled. For example https://github.com/StylishThemes/GitHub-Dark/pull/291/files

Screenshot in case it's un-reproducible:

![2016-03-15-111946_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1360539/13789117/dfb07484-ea9f-11e5-8d77-9293b0683921.png)

**Comment by keith** [comment]
This is part of this new feature https://github.com/blog/2123-more-code-review-tools

**Comment by Mottie** [comment]
Thanks for reporting this! I'll have it fixed and on userstyles soon.

**Comment by bacongobbler** [comment]
:tada:
