### ISSUE TITLE
New GitHub header is huge until signed in

### ISSUE THREAD

**Issue by saildata** [StylishThemes/GitHub-Dark#296]
![screenshot from 2016-03-16 21 51 45](https://cloud.githubusercontent.com/assets/11636184/13835054/46467e6e-ebc2-11e5-9460-f423afedca98.png)

Recently I noticed that the GitHub header is huge until you have signed in. I've modified my local Stylish theme to correct it and match the theme color (see screenshot below). I wanted to open an issue prior to a PR. Looking at the screenshot now, I think that the top margin should be increased a little.

![screenshot from 2016-03-16 21 52 13](https://cloud.githubusercontent.com/assets/11636184/13835106/b88575a2-ebc2-11e5-9649-696497416aa3.png)

**Comment by simov** [comment]
:wave: that can be seen on the blog posts as well https://github.com/blog/2124-kindly-closing-pull-requests even when signed in.

**Comment by Mottie** [comment]
The header appears to be styled to me (not white), so is this issue only about the padding?

We "try" to maintain the original look of GitHub (except darker) as much as possible, so I think a change like this should be added to a separate user style.

**Comment by simov** [comment]
Yep it's dark :) , ignore my comment from above. I'm usually behind master and I didn't checked.

**Comment by silverwind** [comment]
Yes, we usually only change colors and such, only in very rare cases, we change the layout. I too think that that header has too much padding, but I don't want to add another "hack" to fix it. I'd suggest you create another userstyle with this content:

````css
@-moz-document domain("github.com") {
  .site-header {
    padding-top: 10px !important;
    padding-bottom: 10px !important;
  }
}
````
