### ISSUE TITLE
Color Job Ad/Alert Background Tint of Theme Setting

### ISSUE THREAD

**Issue by wldcordeiro** [StylishThemes/GitHub-Dark#305]
### Unstyled Content

[x] No other existing issue and/or pull request.
[x] URL of unstyled content. - Github.com Main page
[x] If unable to provide a URL, please report the class name of unstyled content. - `.github-jobs-promotion`
[ ] Provide steps to reproduce (opening a dialog, etc).
![github - firefox developer edition_017](https://cloud.githubusercontent.com/assets/580982/14478529/de161c74-00d3-11e6-880d-a6ea8291e6cf.png)

**Comment by silverwind** [comment]
Those blue boxes are hard to style because the background needs to be of a darker shade, but a filter can only be applied to the whole box including foreground. I think we have to wait for [backdrop-filter](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter) to be implemented by more browsers.

**Comment by wldcordeiro** [comment]
Ah, I see. It's the same here in issue view too, but if it's something that's just difficult to do with browsers now it's not bad (plus blue and orange work well together.)

**Comment by Mottie** [comment]
There is also a css 4 proposal for [`color-mod()`](https://drafts.csswg.org/css-color/#modifying-colors)! <img title=":_ excite :" src="https://cloud.githubusercontent.com/assets/136959/13559383/49d88766-e3d9-11e5-9c0c-9a958bfc03ee.gif">

**Comment by Mottie** [comment]
Edge v17 will support [backdrop-filters](https://caniuse.com/#feat=css-backdrop-filter) ([source](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/9160189-backdrop-filters))

**Comment by silverwind** [comment]
Wohoo, I updated [mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter).

**Comment by Mottie** [comment]
They're switching to a new compatibility table (see [filter](https://developer.mozilla.org/en-US/docs/Web/CSS/filter#Browser_compatibility_2)). And that's why I opened https://github.com/mdn/browser-compat-data/issues/734; that, and I'm not sure how to create a `css/properties/backdrop-filter.json` property file from scratch.

**Comment by silverwind** [comment]
Not sure I like that new design, but thanks for the pointer!

**Comment by the-j0k3r** [comment]
> Edge v17 will support backdrop-filters (source)

Isnt that Edge :poop: just used for installing Firefox now days?

**Comment by the-j0k3r** [comment]
There is a way around this by styling these boxes with a rgba of base color  for background with around .5 opacity

**Comment by xt0rted** [comment]
These alerts don't use a colored background anymore, it's `#181818`. There's no class that'll let you change the border color without also changing colors elsewhere.

![image](https://user-images.githubusercontent.com/831974/71270491-b83a2c80-231f-11ea-89c6-d969e1250d13.png)

```html
<div class="d-block Box border-blue no-underline px-2 py-1">
  <div class="d-flex flex-items-baseline p-1 no-underline flex-justify-between">
    <a href="https://jobs.github.com/positions/d28b2d1a-e85a-11e8-9b78-62dc829f5516" class="d-block f6 lh-condensed link-gray-dark no-underline f6">
      <span class="text-bold">The Atlantic</span> is hiring: <span class="text-bold">Lead Front End Developer in Washington, DC &amp; New York, NY</span>
    </a>
  </div>
</div>
```

**Comment by silverwind** [comment]
> These alerts don't use a colored background anymore

This makes the issue obsolete.

Regarding `backdrop-filter`, it's starting to gain traction in Browsers (Firefox has is behind a `about:config` pref), so we may soon be able to use it. Thought I  can't think i a case where I'd use it currently.

**Comment by the-j0k3r** [comment]
@wldcordeiro 

See https://github.com/StylishThemes/GitHub-Dark/issues/1113#issuecomment-658075241

In a few days will be published as addon style so these type things should be handled in that style.
