### ISSUE TITLE
Little white arrow on "Verified" tooltip of PR

### ISSUE THREAD

**Issue by charlesmilette** [StylishThemes/GitHub-Dark#306]
See screenshot:
![capture](https://cloud.githubusercontent.com/assets/6440374/14546323/b8b527a4-0272-11e6-8995-2b1644f79d42.PNG)

You can view the tooltip by going [here](https://github.com/nefarius/ScpToolkit/pull/267) and clicking on "Verified" with your mouse

Not doing it in commit history:
![capture2](https://cloud.githubusercontent.com/assets/6440374/14546406/37400044-0273-11e6-9094-665e8c251714.PNG)

**Comment by Mottie** [comment]
Hi @charlesmilette!

Thanks for reporting this, I'll have it fixed in the master branch shortly.
