### ISSUE TITLE
GPG Signing Dropdown Unstyled Content

### ISSUE THREAD

**Issue by NiXXeD** [StylishThemes/GitHub-Dark#307]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [x] URL of unstyled content.
- [x] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

* Url: https://github.com/NiXXeD/dotfiles/commits/master
* Click the "Verified" commit button on my latest commit.
  ![screen shot 2016-04-21 at 4 13 40 pm](https://cloud.githubusercontent.com/assets/5414721/14724479/0b1d08ea-07dc-11e6-928b-93506c2a155a.png)
* Class name: `.signed-commit-header`

**Comment by silverwind** [comment]
This was fixed in https://github.com/StylishThemes/GitHub-Dark/commit/ec5cd337fcec83b687806798a32ab1cea0de80c1. Make sure you're up to date!

**Comment by NiXXeD** [comment]
Huh, I had literally just clicked "Check Update" before submitting, but it appears Stylish wasn't updating it. The version in the style was showing from March. I could repeatedly click to check update and install but it wasn't updating I guess. I had to delete and reinstall the theme entirely, and now it's working.

Sorry to waste your time!

**Comment by silverwind** [comment]
I don't have much experience with Stylish's update feature, but we're regularily getting issues like this.

Might be worth to bring up the issue at https://github.com/JasonBarnabe/stylish.
