### ISSUE TITLE
Labels picker white background

### ISSUE THREAD

**Issue by joelworsham** [StylishThemes/GitHub-Dark#312]
### Unstyled Content

"Labels" picker in right sidebar for issues.
https://github.com/StylishThemes/GitHub-Dark/issues/305 (any issue management url)

**Comment by Mottie** [comment]
Thanks for letting us know! All fixed <img title=":_ excite :" src="https://cloud.githubusercontent.com/assets/136959/13559383/49d88766-e3d9-11e5-9c0c-9a958bfc03ee.gif">

**Comment by Mottie** [comment]
Hmm, I guess I missed using the base color as the hover/focus color... I'll fix it, but it won't be on userstyles until the next update.

**Comment by Mottie** [comment]
<img title=":_ derp :" src="https://cloud.githubusercontent.com/assets/136959/13559387/49e2ecce-e3d9-11e5-8a16-73cbfdb7230e.gif">  never mind! I think the hover/focus color was dark grey because it wouldn't interfere with the selected label colors.
