### ISSUE TITLE
Files Changed Diff Bar on Pull Request Unformatted

### ISSUE THREAD

**Issue by FizzBuzz791** [StylishThemes/GitHub-Dark#313]
Used the below to fix it.

.pr-toolbar {
    background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAACCAYAAACZgbYnAAAAEklEQVQImWNgYGBgYHB3d/8PAAOIAdULw8qMAAAAAElFTkSuQmCC) right repeat-y!important;
    color: #a0a0a0!important
  }
  .diffbar{
    background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAACCAYAAACZgbYnAAAAEklEQVQImWNgYGBgYHB3d/8PAAOIAdULw8qMAAAAAElFTkSuQmCC) right repeat-y!important;
    color: #a0a0a0!important                  
  }

**Comment by Mottie** [comment]
Hi @FizzBuzz791!

Please share a link to the page where we can see this issue. I would like to avoid using gradient background images, so seeing the toolbar would help.

**Comment by silverwind** [comment]
Yeah, gonna need a screenshot or link please!

**Comment by FizzBuzz791** [comment]
Apologies, I neglected to make sure I had the latest update. It looks like you've actually fixed it by using `background: transparent !important` in one of the large catch-alls.
