### ISSUE TITLE
Settings - OAuth Applications - Authorized applications = border bug

### ISSUE THREAD

**Issue by simov** [StylishThemes/GitHub-Dark#316]
![oauth-apps-border](https://cloud.githubusercontent.com/assets/1694112/15565737/4f7ea48a-2325-11e6-996d-aa092bddddff.png)

The border should be gray, take a look at the `Developer applications` if you have any.

**Comment by Mottie** [comment]
Hi @simov!

Please see if the change I just made also applied to the developer applications. Thanks!

**Comment by simov** [comment]
Yep, the border is gray (fixed) in both places :+1:
