### ISSUE TITLE
block or report dropdown style

### ISSUE THREAD

**Issue by SSARCandy** [StylishThemes/GitHub-Dark#317]
### Unstyled Content

[x] No other existing issue and/or pull request.
[x] URL of unstyled content.
[x] If unable to provide a URL, please report the class name of unstyled content.
[x] Provide steps to reproduce (opening a dialog, etc).

![image](https://cloud.githubusercontent.com/assets/6803791/15628540/050c89ea-2536-11e6-84ad-58cc0800cd08.png)

**Comment by silverwind** [comment]
This is already fixed in the latest version (https://github.com/StylishThemes/GitHub-Dark/commit/5942f717cb01e0219fa4bc176542d45f6ece9e5e), please update!
