### ISSUE TITLE
Hover over groups of checkboxes

### ISSUE THREAD

**Issue by mewmew** [StylishThemes/GitHub-Dark#318]
### Unstyled Content

Example URL: https://github.com/mewmew/associative_memory/issues/7

Steps to reproduce.

1. Hover the mouse cursor over the checkbox groups.
2. The background will be highlighted in white.

Version of GitHub-Dark: Github Dark Theme v1.14.78 (5/24/2016)

### Feature Request

Make the background dark when hovering over groups of checkboxes ![bright hover example](https://i.imgur.com/67iGWrL.png)

**Comment by silverwind** [comment]
testing.

- [ ] abc
 - [ ] a
 - [ ] b
 - [ ] c

- [ ] abc
 - [ ] a
 - [ ] b
 - [ ] c

**Comment by mewmew** [comment]
@silverwind Oh, wow. Thank you for the truly incredible response time in fixing this issue. I am in awe. May I ask, do you have a charity close to heart? I wish to donate to some good cause as a sign of my gratitude. Happy regards /u

**Comment by silverwind** [comment]
@mewmew Thanks! No particulary charity comes to mind, but if I'd have to choose, I'd give to cancer research. 😉

**Comment by mewmew** [comment]
> Thanks! No particulary charity comes to mind, but if I'd have to choose, I'd give to cancer research. :wink:

Consider it done.
