### ISSUE TITLE
Unstyled dropdown menu items

### ISSUE THREAD

**Issue by jawshooah** [StylishThemes/GitHub-Dark#321]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [ ] URL of unstyled content.
- [x] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

Dropdown menu items appear to be unstyled. Relevant classes are `select-menu-item`, `js-navigation-open`, and `js-navigation-item`. To reproduce, open a dropdown menu (issue labels, PR authors, etc). Example screenshot:

<img width="415" alt="screen shot 2016-05-31 at 3 26 16 am" src="https://cloud.githubusercontent.com/assets/4551271/15666676/2582477c-26e0-11e6-9554-9d96381af91d.png">

**Comment by Mottie** [comment]
Hi @jawshooah!

This dropdown should be styled in the latest version. Please check to make sure you're using v1.14.80.

**Comment by jawshooah** [comment]
Interesting, I updated through the Stylish extension and it didn't work. I did add a new domain to the list for matching; would that prevent it from successfully updating?

**Comment by silverwind** [comment]
I think that could mark the style as "custom". At least in Firefox, I don't get a "check for update" on custom styles.

**Comment by jawshooah** [comment]
Looks like this is a [known issue](https://github.com/JasonBarnabe/stylish-chrome/issues/172) with the Chrome extension. Updating on GitHub Dark's theme page worked for me. Thanks!
