### ISSUE TITLE
Unstyled content on upgrade page

### ISSUE THREAD

**Issue by J2TeaM** [StylishThemes/GitHub-Dark#323]
### Unstyled Content

- URL: https://github.com/account/upgrade
- Screenshot:

![image](https://cloud.githubusercontent.com/assets/5250117/15755310/5227b684-2926-11e6-91e0-7188a0485778.png)

**Comment by silverwind** [comment]
Thanks for reporting. Should all be fixed, including the help tooltips!

**Comment by silverwind** [comment]
Looks like the addition of a background to those radio boxes caused unintended side effects, will follow up.

**Comment by silverwind** [comment]
Okay radio buttons should be visible again, had to remove the background because of GitHub's weird way of styling them, so it's kind of a compromise.
