### ISSUE TITLE
Notification text is too dark

### ISSUE THREAD

**Issue by zsck** [StylishThemes/GitHub-Dark#325]
URL of unstyled content: `/notifications`
Class name(s) of relevant content:

    css-truncate-target js-notification-target js-navigation-open list-group-item-link

Steps to reproduce:

1. Get a notification for something
2. Navigate to `/notifications`
3. Observe dark title text is very hard to read

**Comment by silverwind** [comment]
Got a screenshot? I don't see any unreadable text on that page:

![](https://cloud.githubusercontent.com/assets/115237/15761069/92375e10-2916-11e6-821d-fb072aff2dc5.png)

**Comment by zsck** [comment]
Here's what I've been seeing when I navigate to notifications.
I'm using the latest version of Chrome with Stylish and have no other userstyles applied to Github.

<img width="725" alt="screen shot 2016-06-02 at 4 56 38 pm" src="https://cloud.githubusercontent.com/assets/682761/15761404/f538a798-28e5-11e6-9589-a7b7cc5ba583.png">

**Comment by silverwind** [comment]
Looks like you're using the other [github-dark](https://github.com/cquanu/github-dark), which I think is going to get renamed soon. Either open an issue there or try our style :)
