### ISSUE TITLE
Pinned repositories

### ISSUE THREAD

**Issue by colonelmo** [StylishThemes/GitHub-Dark#328]
Drag-and-drop to arrange the newly added "pinned repositories" doesn't work with dark theme turned on.

**Comment by silverwind** [comment]
Both should be fixed visually with today's release. Can you define "doesn't work"? Our style should never change functionality.

**Comment by silverwind** [comment]
Closing, I think this issue is invalid.

**Comment by colonelmo** [comment]
Sorry for the delay, that is my fault. + Yes it works perfectly now.
