### ISSUE TITLE
White Issue Hover State?

### ISSUE THREAD

**Issue by jakejohns** [StylishThemes/GitHub-Dark#330]
Did this just happen? Or did I mess up my own config some how?
![gh-dark_bad-hover](https://cloud.githubusercontent.com/assets/174708/16220150/09468738-3759-11e6-889b-d3f9042b5b70.png)

**Comment by simov** [comment]
Most probably GitHub updated their styles. Same bug here.

**Comment by Mottie** [comment]
I just added a fix that can be used immediately with the [GitHub-Dark Script](https://github.com/StylishThemes/GitHub-Dark-Script), but I'm going to hold off on updating userstyles.org until we determine there aren't more of these changes hiding somewhere.

**Comment by simov** [comment]
Works for me (through my extension). I like the new styles. I can't remember if the issue/pr list had some background color before that, but I think it's readable, same as the home page stream.

**Comment by silverwind** [comment]
Looks kind of weird being transparent, imho. I changed it to a solid background and also fixed link colors.

**Comment by simov** [comment]
That's even better :+1:

**Comment by Mottie** [comment]
Thanks @silverwind, I was short on time this morning :wink:

**Comment by silverwind** [comment]
New version is out with these fixes!
