### ISSUE TITLE
Unstyled content on dropdown menu

### ISSUE THREAD

**Issue by J2TeaM** [StylishThemes/GitHub-Dark#333]
### Unstyled Content

- URL of unstyled content: https://help.github.com/
- CSS selector: `.dropdown-menu:before`
- Screenshot: 

![image](https://cloud.githubusercontent.com/assets/5250117/16239853/038ae77c-3811-11e6-9f8b-53be2884ad5d.png)

**Comment by Mottie** [comment]
Thanks for reporting this problem! It's been fixed in the repo, but not yet on userstyles.org.
