### ISSUE TITLE
Table styles.

### ISSUE THREAD

**Issue by rayrutjes** [StylishThemes/GitHub-Dark#335]
All the tables are now badly designed:
![image](https://cloud.githubusercontent.com/assets/5570853/16257021/1fa3a60c-3856-11e6-8014-3a61317e6596.png)

**Comment by Mottie** [comment]
Hi @rayrutjes! Please update your style.

**Comment by rayrutjes** [comment]
Owe thank you, actually I was using the stylish build in "update" feature which would tell me that a new update was available but would never really apply it. Used the stylish website to do the update and it worked. Awesome work, keep it up!
