### ISSUE TITLE
Custom Syntax Themes

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#338]
I haven't had a chance to check it out yet, but GitHub recently created:

https://github.com/primer/github-syntax-theme-generator

They even have a [github-dark syntax theme](https://github.com/primer/github-syntax-dark) too!

**Comment by silverwind** [comment]
That thing seems to generate CSS out of [JSON](https://github.com/primer/github-syntax-theme-generator/blob/master/lib/themes/light.json) files. Might be useful to clean up our theme mess. :smile:

**Comment by un1versal** [comment]
If StylishThemes made that into some script ala GitHubDark Script style to make themes compatible with GitHub Dark from stylish and GitHub Dark Script that would be like a g33ks wet dream about dags and turtles

**Comment by Mottie** [comment]
Closing this issue as the generator still requires you to manually pick colors to match existing themes.
