### ISSUE TITLE
Improve upon yellow on guidleines box and compare pull-request

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#340]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [ ] URL of unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

Hello guys, its moi again... 

### Steps to reproduce:
1. Create a patch and force push + visit master origin repo
2. Press the Compare and pull request button

Theres a large style discrepancy between (Please review the guidelines for contributing to this repository.) and (compare & pull request) bounding boxes, the yellows used and how they ultimately look.

![contributing](https://cloud.githubusercontent.com/assets/3521959/16830617/f244d8cc-4997-11e6-80e6-8458181a2818.gif)

So there  (Please review the guidelines for contributing to this repository.) its that (omg killme) yellow with yellow text that **guidelines for contributing** is hovered it mixes with some blue, this looks not so nice.

suggestion: idk, but something it occurs to me is why not use the **Base color scheme** instead of that (omg killme) yellow and some light grey or white letters so as not to kill the hover?
(I usually like yellow against dark/black but that shade of yellow blend doesnt go together)  

![capture1](https://cloud.githubusercontent.com/assets/3521959/16830622/f9603e08-4997-11e6-8451-f64df84c1ca0.PNG)

Then that (compare & pull request) box, the yellow is a complete departure from the previous style, it screams (I dont belong here) when viewed against the black style, it sticks out too much as if it doesnt match the overall look?

Again like the previous suggestion using the  **Base color scheme** with some opposite color text to contrast?

As you can see the unstyled counterparts both match in style at least and the link to **guidelines for contributing** hover only difference is the underline

Aside from the **Username:Repo** letters and the Compare and pull request button style I cant see a difference between those pastel yellows. so that maybe some themeing omission?

![capture](https://cloud.githubusercontent.com/assets/3521959/16831070/db59e3d4-499a-11e6-8cc3-4bad7b452104.PNG)

![contributing](https://cloud.githubusercontent.com/assets/3521959/16831071/db5abfe8-499a-11e6-9149-2a3161ff213e.gif)

As a side note, Im addicted to this dark style and cant imagine ever going back to unstyled :+1:

**Comment by un1versal** [comment]
also these two when you press **New pull request** button

![capture](https://cloud.githubusercontent.com/assets/3521959/16831601/d80b52b4-499d-11e6-8487-9ff588911295.PNG)

![capture1](https://cloud.githubusercontent.com/assets/3521959/16831600/d80b4a8a-499d-11e6-9a6c-1e1bd7fb2aff.PNG)

and perhaps other s that use similar Styled colors one point that really sticks out aside from (killme) yellow is the styled green **Create pull request** button which doesnt match any of the unselected buttons (I know this isnt a real button) but the normal style has some gradient?

The unstyled is just faded color anyway so maybe you can do something here also?

pretty prease with cheese ontop?

**Comment by Mottie** [comment]
Hi @un1versal!

Not of fan of the baby-sh*t yellow, huh? LOL.

I remember making it a dark brown before, but I don't remember why it changed. Anyway, what do you think of changing it back to burnt-baby-sh*t brown with white text?

![yellow](https://cloud.githubusercontent.com/assets/136959/16839019/402172cc-4992-11e6-876f-25e436e7d1ba.gif)

```css
.yellow-panel {
    background: #2B1F00!important;
    border-color: #4A3600 !important;
    color: #ccc !important;
}
.yellow-panel-link {
    color: #fff !important;
}
.yellow-panel-link:hover {
    color: #fff !important;
    /* underline already applied */
}
```

**Comment by un1versal** [comment]
> Not of fan of the baby-sh*t yellow, huh? LOL.

haha :) you said it :gun: 

> I remember making it a dark brown before, but I don't remember why it changed. Anyway, what do you think of changing it back to burnt-baby-sh*t brown with white text?

is that all occurrences of baby-sh*t yellow? If yes then sure, but the link in white isnt n line with blue links type thing, however the rest in white looks MUCH better, the clarity there is wow straight away.

I have to wonder, wouldnt it all tie in better though if the ** Base color scheme** were used instead for that blend?

what about the other stuff?

**Comment by Mottie** [comment]
The class name on that panel is "flash-warn", so it's meant to be yellow-ish. The same colors are also applied to pending status, private labels, stale files, secret gists, etc. 

We actually already have a brown panel style with other warning panels:

```css
.brown-panel {
  background: #321 !important;
  border-color: #542 !important;
  color: #b74 !important;
}
```

But I'm thinking that maybe these yellow panels would look better being semi-transparent?

Here is the same yellow, but with a .4 opacity:

![baby-sh t-yellow-0 4](https://cloud.githubusercontent.com/assets/136959/16845780/b872ccb8-49af-11e6-9586-d3289d28008f.gif)

```css
.yellow-panel {
  background: rgba(56,52,18,.4)!important;
  border-color: #551 !important;
  color: #ddd !important;
}
```

Honestly, I don't think I like the hovered link matching the base color. 

What do you think @silverwind?

**Comment by Mottie** [comment]
Here, this screenshot give you a better idea of the semi-transparent background

![2016-07-14 10_47_36-new issue stylishthemes_github-dark](https://cloud.githubusercontent.com/assets/136959/16846024/85496576-49b0-11e6-9a95-ac327babaf56.png)

**Comment by silverwind** [comment]
Semi-Transparent could work, but it create some inconsistency with base-color (blue) panels which can't be made transparent because of https://github.com/StylishThemes/GitHub-Dark/issues/305#issuecomment-209540939.

**Comment by un1versal** [comment]
> But I'm thinking that maybe these yellow panels would look better being semi-transparent?
> 
> Here is the same yellow, but with a .4 opacity:
![](https://cloud.githubusercontent.com/assets/136959/16845780/b872ccb8-49af-11e6-9586-d3289d28008f.gif)

That transparency may just make that yellow be bearable, but I still think links should be consistent unselected and hover alike using base color.

**Comment by Mottie** [comment]
Ok, lets see what you guys think of semi-transparent brown. The links will match the base-color.

![2016-07-14 12_23_48-new issue stylishthemes_github-dark](https://cloud.githubusercontent.com/assets/136959/16848954/dcd9cc42-49bd-11e6-9280-b431220ec803.png)

Please feel free to change anything.

Oh and @un1versal, I didn't look for those unstyled panels you shared in the screenshots. What is the associated class name?

**Comment by silverwind** [comment]
Would anyone oppose me making them red-ish? :laughing:

**Comment by Mottie** [comment]
fine by me
<img alt="ghe-emoji" title=":_tuzki_dizzy:" src="https://cloud.githubusercontent.com/assets/136959/13203535/61480e08-d880-11e5-9ea8-7fc03c7d7b56.gif">

**Comment by un1versal** [comment]
> Oh and @un1versal, I didn't look for those unstyled panels you shared in the screenshots. What is the associated class name?

Ive no idea, I dont know css but element inspector pull this up for the element

![compareandpr](https://cloud.githubusercontent.com/assets/3521959/16853032/9217f220-4a02-11e6-82b8-7f98f62fe0f9.gif)

> Would anyone oppose me making them red-ish? :laughing:

red? :/ how would that look?

Does that mean you kill all the baby sh*t yellow everywhere also to look same?

**Comment by un1versal** [comment]
oh, do you hate me yet? no?

shall I open a separate ticket for these?

![hovercolorlabelsmilestones](https://cloud.githubusercontent.com/assets/3521959/16853465/58695e7c-4a04-11e6-93ae-b3e26e7a54a7.gif)

You guys must have eagle eyes :eyes: , or maybe Im just really blind :eyeglasses:

**Comment by Mottie** [comment]
We don't hate you! It's good to have fresh eyes on stuff.

Anyway, the labels & milestone hover styling matches what GitHub does - turn off the dark style and you'll see.

**Comment by un1versal** [comment]
> We don't hate you! It's good to have fresh eyes on stuff.

Thats cause Im half blind :D I have to look extra hard, I suppose thats why I have an irritating eye for detail :mag: 

> Anyway, the labels & milestone hover styling matches what GitHub does - turn off the dark style and you'll see.

Ill go out on a limb and say what we all think anyway, just cause GitHub does it doesnt mean its right 

the only difference being is you guys are actually 1.000.000 times better at support and actually open to improving things :+1: 

er did I say that out loud? ooops now to change identities and escape the country. ```</sarcasm>```

**Comment by un1versal** [comment]
better :+1:

**Comment by un1versal** [comment]
with some of the changes from 88ad779ff4efb91dd23d19f44046122071cb6895 to 26cada37fb36d0ff1539a15f5da4b50237bd8021 this looks better, but Im applying these manually against the exact code on http://userstyles.org/styles/37035 so its already a frankeinsteined version.

one thing I noticed is

![capture](https://cloud.githubusercontent.com/assets/3521959/16861832/50dc54ba-4a3c-11e6-8efa-958ff7abf456.PNG)

still has yellow text and button style is darker then others while unstyled is more faded, but I guess thats not terrible except for yellow text.

![capture1](https://cloud.githubusercontent.com/assets/3521959/16861864/a5319a34-4a3c-11e6-8d7d-9b0d90e6c8e1.PNG)

Gists the yellow idk, spyes? dont match the brown now. 

![capture](https://cloud.githubusercontent.com/assets/3521959/16861865/a53536d0-4a3c-11e6-8180-c188e4eedbc2.PNG)
 
And other brown parts like that secret bit needs some sort of outline I guess else gets lost against the dark grey.

Then again idk if thats cause I didnt apply something or because I now have a Frankensteined version. :/

I tried copying and pasting https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css into the [GitHub Dark Scipt](https://github.com/StylishThemes/GitHub-Dark-Script) but sadly that script doesnt like the trunk file and I noticed tons of bugs with that [GitHub Dark Scipt](https://github.com/StylishThemes/GitHub-Dark-Script) but Ill take that on another time, for now I think Ill wait for the final fixes here and maybe you guys can tell me how to make the newer source work properly.

thx...

**Comment by Mottie** [comment]
Ok, the yellow text and icons should now be fixed.

I don't have any secret gists, so please let me know the class name on that label.

Why is there a circle around the green "Create pull request" button? Am I missing something?

Once all these get ironed out, I'll update the userstyles site.

As for the GitHub Dark Script, which "trunk file" are you referring to? If you click the "Force Update Style" button, it gets the [github-dark.css](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css) file from the master branch, so you will have the most up-to-date style applied.

If you want to test changes, then open the github-dark.css file in an editor, make the changes, then select all & copy, then paste into the text area that appears when you click the click on the arrow up button next to the "Force Update Style" button.

![2016-07-15 14_10_28-improve upon yellow on guidleines box and compare pull-request issue 340 st](https://cloud.githubusercontent.com/assets/136959/16885796/ed8da670-4a95-11e6-9f4b-59484c32a747.png)

This only temporarily applies the changes. Once you reload the page, the style will revert back to the version that was cached.

**Comment by un1versal** [comment]
> If you want to test changes, then open the github-dark.css file in an editor, make the changes, then select all & copy, then paste into the text area that appears when you click the click on the arrow up button next to the "Force Update Style" button.

That doesnt seem work with master github-dark.css -> this file https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css *thats what I mean by master trunk file + github dark script when I click force apply, the base color and all other settings are ignored and not written to file...

> Why is there a circle around the green "Create pull request" button? Am I missing something?

(Just marking what doesnt match) the button is much darker than the others of same greenish style, isnt it suppose to be lighter? I guess it doesnt matter that much....

> I don't have any secret gists, so please let me know the class name on that label.

idk if this helps but thats what I get

![sling](https://cloud.githubusercontent.com/assets/3521959/16888594/fb426dd0-4ad8-11e6-982d-8143d57d3faf.gif)

**Comment by un1versal** [comment]
OK in https://github.com/StylishThemes/GitHub-Dark/pull/343#issuecomment-233125914 I also fixed an issue just noticed.

You guys should have a few fixes for here in #343, I hope thats is as you guys prefer.

**Comment by un1versal** [comment]
I think #343 closes this ticket now, I should have closed it from commit message.. Its not my first git dance though I wasnt expecting to fix that many issues there.

**Comment by Mottie** [comment]
LOL no worries.

**Comment by un1versal** [comment]
:beers:  :beers:  :beers:  :beers:  all around, nice team work.

**Comment by Mottie** [comment]
We mostly use issues for discussions, but I do watch the Gitter room:

[![Gitter](https://badges.gitter.im/StylishThemes/GitHub-Dark.svg)](https://gitter.im/StylishThemes/GitHub-Dark?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by un1versal** [comment]
Gitter? Im a good old fashioned IRC stickler myself... Ill check that out though, its nice to chat live.

You guys should consider IRC sort of support hangaround channel, Ide be happy to setup a channel for you guys.
