### ISSUE TITLE
Profile page: public activity tab -> octicon-rss visibility issue

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#345]
### Unstyled Content

- [x] No other existing issue and/or pull request.

this one I sort of had a half baked solution, but its not as good as it ideally should be so lets see what many head do here.

This is how it looks (the classes aren't styled by GitHub Dark) I think it looks like :poop:  by default

**Before**
![capture](https://cloud.githubusercontent.com/assets/3521959/16902536/a3cf4e56-4c59-11e6-9e1a-c2567a0aa95c.PNG)

As you can see the the `.octicon-rss` is near enough unreadable (even without GitHub Dark.)
better it is using `color: #000` but then the tab octicon-rss is invisible.

So here is my half backed solution
>**note**: I didnt know where to past this is code so I placed it near the top  

```
  /* rss profile button */
  .feed-icon {
    background: #dd4b02 !important;
  }
  .octicon-rss {
    color: #fff !important;
  }
```
**After**
![capture](https://cloud.githubusercontent.com/assets/3521959/16902562/50a36afe-4c5a-11e6-8125-5923a8d5c00b.PNG)

like I said its not ideal but its better, thoughts?

**Comment by Mottie** [comment]
Thanks! But try this instead

![2016-07-17 14_40_47-mottie rob garrison](https://cloud.githubusercontent.com/assets/136959/16902713/809190c0-4c2c-11e6-9c35-ed92ec88274f.png)

It's the style we already have set for the [blog page](https://github.com/blog).

**Comment by un1versal** [comment]
Ive no idea how to do that

**Comment by Mottie** [comment]
I've already pushed the change to the master branch... use "Force Update Style"

**Comment by un1versal** [comment]
ah lol yes thats much better btw ;)
