### ISSUE TITLE
issues with https://github.com/username.atom

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#346]
### Unstyled Content

- [x] No other existing issue and/or pull request.

### Issue

**Before**
![capture1](https://cloud.githubusercontent.com/assets/3521959/16902689/51a748cc-4c5e-11e6-8e57-0946097ebb6f.PNG)

This by default is half styled but the text in brow over brown box is hard to read and the select button text looks washed out

So this was my solution, I wasnt sure where to place code but placing it near the top for testing works hence this instead of PR.

```
  /* rss atom subscribe box */
  #subscribeButton {
    color: #000 !important;
  }
  #checkboxText, #subscribeUsingDescription {
    background: rgba(51,34,17,.4) !important;
    color: #ddd !important;
  }
```
**After**
![capture](https://cloud.githubusercontent.com/assets/3521959/16902701/915601ca-4c5e-11e6-875b-557503fa7e85.PNG)

this box is now MUCH improved and matches what was done in similar elements that were mentioned in #340 and fixed in #343

I would have submited a PR but both this and

**Comment by un1versal** [comment]
Aside form the issue that GitHub Dark Script doesnt style the atom, but Stylish does,
(some discussion on Gitter with @Mottie) the only other issue is the missing rss icon on the top left.

reference unstyled page.

![capture](https://cloud.githubusercontent.com/assets/3521959/16902929/4859b554-4c66-11e6-9edb-2c1ac2d5228e.PNG)

**Comment by Mottie** [comment]
Also, the atom page is only styled in Firefox; Chrome & Opera display raw data. Edge just pops up a warning message saying the atom page could not be downloaded.

After some investigation, I did find a solution to get the GitHub Dark Script to load on the .atom page; it is now available.

The style of this page should be "fixed" in this last patch.

**Comment by un1versal** [comment]
Thats fantastic looks as it should, I guess.

Thanks a million Mottie :)

To be honest the GitHub user atom page behaves weirdly, usually an RSS button is available in address bar (depending on settings) like for instance in this page.
![capture](https://cloud.githubusercontent.com/assets/3521959/16904233/a38427b6-4c89-11e6-894f-83e552ecdd57.PNG)

but in user atom page its not, so I wonder what deal is.

Glad you cracked it, one small step for Mottie, one Giant Leap for GD(S)
I hoep you like that last extra moldy cheese ontop.... :grin: 

I meant thx :+1:
