### ISSUE TITLE
Need transparent PNGs for Network Members graphs

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#347]
https://github.com/StylishThemes/GitHub-Dark/network/members features small dotted lines with a unfortunate white background on the PNGs:

https://assets-cdn.github.com/images/modules/network/t.png
https://assets-cdn.github.com/images/modules/network/l.png

Currently, these lines are hidden with `display:none`. It'd be great if we can get some replacement graphics in there and apply them through `url()`, similar to how it's done for the spinner images.

**Comment by Mottie** [comment]
Way back when this style was first created, there were some definitions for this... I think they were removed when the style got so big in favor of just inverting the image.

See https://github.com/StylishThemes/GitHub-Dark/commit/593c69ef4c67fb3daa3abb6a5a6675a3183d6987

**Comment by silverwind** [comment]
Oh wow, they must've gotten lost in time. If you could invert them, that'd be perfect :)

**Comment by Mottie** [comment]
Done in https://github.com/StylishThemes/GitHub-Dark/commit/820940e2f614731aba8200b23b27884f676aff19
