### ISSUE TITLE
Bug: Frontpage RSS link is not destinguishable from Normal text

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#349]
This **was not** a GitHub Dark bug, but since https://github.com/StylishThemes/GitHub-Dark/commit/e590fd01f64059fab6719af7f04ad0af93f4cc39 **it is now** also a GitHub Dark bug.

Normally you wouldnt ask a 3rd party project to fix these issues, but no point notifying GiHub because they just do nothing about it and just give you same old replies.

Im interested in what you guys think is best practice, when it comes to GitHub bad design decisions, because they are a pet peeve and it would be great if GitHub Dark, did not emulate such questionable decisions.

Hence the issue not PR, since there is also not a visited link color for most links in GitHub. (another pet peeve)

### Unstyled Content

- [x] No other existing issue and/or pull request.

![links](https://cloud.githubusercontent.com/assets/3521959/16940372/6134932a-4d81-11e6-94bd-a92341075cd3.gif)

----
See https://github.com/StylishThemes/GitHub-Dark/commit/e590fd01f64059fab6719af7f04ad0af93f4cc39#commitcomment-18293778

>in my opinion this is a bad design decision from GitHub.

>GitHub Dark, should not emulate/condone their bad decisions.

>Links are naturally expected to be blue and when you visited them they are expected to have a *visited* color, 

>Ignoring this preconception imo is bad web design (something GitHub often do.). because you cant distinguish **what is a link** from what **is normal text**—until you hover it with a mouse—or use another navigation method... 

>I once read a book titled ["Dont Make Me Think: A common sense approach to web usability](http://www.amazon.co.uk/Dont-Make-Me-Think-Usability/dp/0321965515%3FSubscriptionId%3DAKIAILSHYYTFIVPWUY6Q%26tag%3Dduc08-21%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3D0321965515) by Steve Krug
At my earliest convenience I will shoot and email with a link to that book to GitHub Support in a ironic and sarcastic sort of way.

**Comment by Mottie** [comment]
Hey @un1versal!

Personally, I try to leave things as they are (but darker) because users are already familiar with how things are set up. While I do agree with you that it is a bad UX to make links the same color as the text, it's not something I use so I think I'll let @silverwind make the call on this one. :grin:

**Comment by silverwind** [comment]
I understand your point that links not colored as link are bad UX generally speaking, but this kind of design is very common across GitHub. For example, almost everything in the Issues UI is actually links, but almost none are colored as such.

I also see a point of styling rarely used links in a grey tone to not have them "scream for attention", and while the choice of color on that frontpage RSS could be changed, I just don't see us doing such customizations, if only for the sake of maintainabilty. Sorry.

**Comment by un1versal** [comment]
craziness 1 common sense 0
