### ISSUE TITLE
Darken https://github.myshopify.com

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#352]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [x] URL of unstyled content.

Style https://github.myshopify.com

follow up from https://github.com/StylishThemes/GitHub-Dark/pull/351

**Comment by Mottie** [comment]
Hey @un1versal!

The `myshopify` isn't part of the GitHub domain, so it is outside the scope of this style.

Also, how much time do you actually plan on spending on that page?
<img title=":_ onion_head_dizzy :" src="https://cloud.githubusercontent.com/assets/136959/13371461/423cd794-dcec-11e5-8a01-4a9b56bd8163.gif">

**Comment by silverwind** [comment]
Yeah, the few frequently-used subdomains of GitHub are already enough work as-is. Styling this whole shop system might indeed be overkill.

**Comment by un1versal** [comment]
was just a suggestion for completeness. Personally never spent any time there except for today.
