### ISSUE TITLE
Network graph invert() filter rendering issue 

### ISSUE THREAD

**Issue by msva** [StylishThemes/GitHub-Dark#357]
Hi!
I've noticed quite strange rendering behaviour of network graph in firefox 47.0.1 on my laptop: all text labels (contributor names, commit messages, table header captions) on the canvas that assumed to be white (or at least very light) are pink, and "loading" animation on the canvas is dark gray with green artifacts (although it's assumed to has white color too).

If I edit this line:
https://github.com/StylishThemes/GitHub-Dark/blob/bd091cfd24745253c8121cf513d8c30686389a30/github-dark.css#L1205
and remove hue rotation — there is almost no artifacts. If I also remove saturation, it renders just fine.

And, I guess, "Loading" animation has pretty same problem (I just still not found the rule, which apply filters to it).

Not sure, if screenshot can show the issue (i.e. that it is related to rendering, but not to monitor), but here is screenshot with artifacts:
![](http://i.imgur.com/Zl13avS.png)
and here is "fixed" one:
![](http://i.imgur.com/SbJP5Yb.png)

**Comment by Mottie** [comment]
Hi @msva!

Interesting. I checked the same page in Firefox on my Desktop (Windows 10) and I'm not seeing the issue described.

![2016-07-23 05_26_22-network graph jung-kurt_luahpdf github](https://cloud.githubusercontent.com/assets/136959/17077442/5d803a6e-5096-11e6-908c-05a75ad654bd.png)

What OS are you using? Are you seeing the same issue on any other computer?

We include the hue-rotation and saturation in an attempt to get near the same colors as the original brighter graph, but it still messes up the avatars.

What do you think we should do?
* Completely remove the definition?
* Only invert the graph?
* Or maybe you could try adding a new Stylish style to override our settings?

    ```css
    @-moz-document domain("github.com") {
      div.network-graph-container {
        filter: invert(90.5%) !important;
      }
    }
    ```

  Oddly, this style overrides the GitHub Dark Script styling, but doesn't appear to override the GitHub Dark userstyle. Firefox is weird.

**Comment by msva** [comment]
If it is somehow possible to recolor that canvas by parts, it would be nice to only change hue of the elements, that doesn't contain rendered text (since they looks nice even with that hardcoded hue, and, I guess, add additional definition for that elements with textwithout hue rotation).

But as far as I googled, it is impossible to change colors of internal elements of canvas — I don't know how to fix that in right way.

Answering on your questions:
1) I'm using Gentoo Linux.
2) Actually, some time ago I've played with fonts hinting/subpixel rendering/lcdfilter, but should it affect canvas if any?
3) I tried to check from remote Xorg-over-ssh from another PC and there is all right. Although, there is also older firefox itself (41.0.2) and all the system.

By the way, I'm trying to play with custom style, that would override GH-Dark, but my most usefull result's side-effect was b&w-toned graph :(

**Comment by msva** [comment]
Nah. I've tried to disable subpixel rendering and restart Firefox and it doesn't help.

**Comment by Mottie** [comment]
Yeah, you can't target parts of the canvas, it's all or nothing. GitHub uses canvas because you can scroll back and forth through the commit history. I think adding that same functionality using SVG would be a lot harder to do.

Did you try the style I shared above? Worse case scenario you can use `filter:unset !important` to leave the canvas untouched.

**Comment by msva** [comment]
Yes, I initially tried the style you've shared above, but as you noticed, it has no priority over Stylish's GH Dark style. So, I did:
```css
div.network-graph-container canvas {
  filter: invert(0%) hue-rotate(270deg) saturate(50%) !important;
}
```
and got:
![](http://i.imgur.com/jvmtvX7.png)

Which is kinda near to "normal", but still has glitches ☺

**Comment by un1versal** [comment]
This is a take it or leave it proposition, you want no glitches then its back to white...

imo since this is a relative small part and the glitches being the inverted avatar its bad, but it looks beetr than having the whole lot in white.

see https://github.com/StylishThemes/GitHub-Dark/commit/47d2c058d01c5ef0ab62a80ab5f808b4cb8f3577 and https://github.com/StylishThemes/GitHub-Dark/commit/2086b02d44313ee8d3604f8f1660bbb0f2f7d53f comments.

**Comment by Mottie** [comment]
[You *can* polish a turd](https://www.youtube.com/watch?v=yiJ9fy1qSFI).

**Comment by un1versal** [comment]
Who knew... still turd though, so I guess that translates well to our case, you can polish it, but its a turd to begin with and no matter how shiny it will still be a polished turd in the end.

![capture](https://cloud.githubusercontent.com/assets/3521959/17184712/9f5e394e-5425-11e6-974f-6c3de66ab9d6.PNG)

yep, still :poop:

**Comment by Mottie** [comment]
Closing this issue as it shouldn't be a problem anymore.

**Comment by msva** [comment]
By the way, after some experiments with local fixing this issue I did ***something*** that followed in this:
http://i.imgur.com/0oMX1dq.png
(fonts rendering artefacts even on unstyled github).

And I have no idea what was that, and so how to revert it back :-/

// P.S., by the way, with current transparent graph I've got almost ideally what I want with:
```
@namespace url(http://www.w3.org/1999/xhtml);
    @-moz-document domain("github.com") {
      div.network-graph-container {
        border: none !important;
      }
      div.network-graph-container canvas {
        filter: invert(90%) hue-rotate(180deg) saturate(99%) !important;
      }
    }
```
(except for fonts artefacts and reverted avatars 😕)
