### ISSUE TITLE
out-of-date page refresh link is yellow stale-files-tab-link 

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#360]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [ ] URL of unstyled content.
- [x] If unable to provide a URL, please report the class name of unstyled content.
- [ ] Provide steps to reproduce (opening a dialog, etc).

`stale-files-tab-link` should be base color.

![demo1s](https://cloud.githubusercontent.com/assets/3521959/17115188/24f33a64-52aa-11e6-97b8-098dff4c079f.gif)

sorry about the braindead gif

**Comment by Mottie** [comment]
All fixed!
