### ISSUE TITLE
next (disabled link) is pretty unreadable

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#362]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [x] URL of unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

Navigate to https://status.github.com/messages/2016-07-25

**class** `.pagination .disabled`

![capture](https://cloud.githubusercontent.com/assets/3521959/17116401/8935eca6-52af-11e6-96dd-904298d38a28.PNG)

also in addition, the hover on both disabled and enabled could do with your usual TLC
imho I think the hover should be the underline since its a link.

**Comment by un1versal** [comment]
The previous week link reminds me of "I like Turtles" type thing...

**Comment by Mottie** [comment]
Your purple circle looks like a turtle.

**Comment by un1versal** [comment]
> Your purple circle looks like a turtle.

...having a pee

so you gonna fix the link hover underline or you getting a turtle>?
