### ISSUE TITLE
mention popup

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#368]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [ ] URL of unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

### Feature Request

its simple type @ and see the popup

![demo-a](https://cloud.githubusercontent.com/assets/3521959/17269054/08ab67ac-5636-11e6-855d-dd64288c2a91.gif)

the nickname on left is a little too dark, especially when selected contrast isnt great. On the right even though the names are darker, they become brighter when selected.

so maybe the nicks on left can also be lighter when selected and mmm the actual nicks not be as dark as that by default?... tried finding the selectors for this but cant seem to find them.

thx

**Comment by Mottie** [comment]
On it!
