### ISSUE TITLE
block cursor.

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#369]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [ ] URL of unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [ ] Provide steps to reproduce (opening a dialog, etc).

### Feature Request

Block cursor mod, is this possible?

**Comment by Mottie** [comment]
![69810180](https://cloud.githubusercontent.com/assets/136959/17270607/f54d1ab6-562b-11e6-85ab-3b1f4f665a65.jpg)

Wha?

**Comment by un1versal** [comment]
![demo-a](https://cloud.githubusercontent.com/assets/3521959/17274580/c548835a-56df-11e6-9326-918f34cf063f.gif)

![dags](https://cloud.githubusercontent.com/assets/3521959/17274587/1b8f6b8e-56e0-11e6-8a0b-1d8b97025a63.gif)

**Comment by Mottie** [comment]
Heh, I was going to correct you and say that you should have called it a *caret*. Hence my confusion; but after looking it up, it seems the two [terms are interchangeable](http://wikidiff.com/cursor/caret).

I also thought I should mention that I must like the term *caret* more after I discovered an alternate meaning:

> A kind of turtle, the hawksbill.

LOL. :turtle: 

Anyway, there isn't any way to create a block *caret* using only css. It is possible to create a block *caret* by adding a styled block behind the current caret position and move it using javascript, but that would truly be way beyond the scope of this style and the companion script.

**Comment by un1versal** [comment]
Carrots? I like carrots! :dancer: 

I suppose you can use the term Caret if you like, a Cursor is a more common term perhaps?

**Comment by Mottie** [comment]
What am I psycho? errr psychic? I have no idea :wink: 

This is as close as I could get with a block *caret* - https://jsfiddle.net/Mottie/24n8wsak/44/ - it would be so much easier to do with a fixed-width font; as it is, calculating the caret position is a real PITA.

**Comment by un1versal** [comment]
> What am I psycho? errr psychic? I have no idea :wink:

Psychotic?

> This is as close as I could get with a block **cursor** - https://jsfiddle.net/Mottie/24n8wsak/44/ - it would be so much easier to do with a fixed-width font; as it is, calculating the **cursor** position is a real PITA.

Very clever, but I see "whacha" mean, the block **cursor** follows the skinny **cursor** by a *lick*.

**Comment by un1versal** [comment]
about:config page

New > Integer
Name: ui.caretWidth
Value: 7

result 

via IRC via Mottie

![demo-a](https://cloud.githubusercontent.com/assets/3521959/17274802/c6520460-56e9-11e6-997d-ba1a98a5158c.gif)

do we wanna document this?

**Comment by silverwind** [comment]
The only thing about the caret that maybe styleable in the near future is the color. I [proposed](https://lists.w3.org/Archives/Public/www-style/2014Sep/0176.html) a multi-value property that would include `caret-width`, but it didn't seem to get much traction and only [caret-color](https://www.w3.org/TR/css-ui-3/#caret-color) is on the standard track right now.

**Comment by un1versal** [comment]
I dont know why color is favored, width improves on visibility while color is just styling, I suppose that all css proposes? Style something?

**Comment by silverwind** [comment]
I guess you should bring up this issue to the CSS WG if you want things to change :D

**Comment by un1versal** [comment]
I dont think one more nutter making noise is going to make any difference.

Im happy that this can be done Firefox side with advanced config, but everywhere on OS already is block cursor everywhere, bulimic 1 pixel wide cursors arent good for everyone.

**Comment by silverwind** [comment]
I'll close this as I feel it's not our job to document a browser-global setting. Maybe I'll try proposing a `caret-width` again to the CSS WG later.
