### ISSUE TITLE
Missing new/unread comment notification for issues/PRs

### ISSUE THREAD

**Issue by gbasood** [StylishThemes/GitHub-Dark#371]
### Unstyled Content
![](http://i.imgur.com/X7BdvOG.png)
And this is what it currently looks like under Github Dark:
![](http://i.imgur.com/lYPD6Gq.png)

- [x] No other existing issue and/or pull request.
- [ ] URL of unstyled content.
- [x] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

### Steps to reproduce
Disable Github Dark.
Go to a repository's issues/PRs in which you have issues or PRs that you are subscribed to
Notice the blue bar on issues that have new comments/commits/etc.
Enable Github Dark and notice that it's now missing.

### Feature Request
Read issues have the class `read`
Unread issues that have the blue bar on the left have the class `unread`

**Comment by Mottie** [comment]
Hi @gbasood!

Thanks for reporting this problem. Including the class name really helps! I'll have it fixed shortly.
