### ISSUE TITLE
Scrollbar is hardly visible

### ISSUE THREAD

**Issue by kevinlaw91** [StylishThemes/GitHub-Dark#372]
Scrollbar is too dark. If the scrollbar handle is too short (long page) and the user is using glossy LCD screen, the scrollbar does not looks like it's there at all.

Perhaps you can make it brighter (example: `background: grey`) so it is more usable.

**Comment by un1versal** [comment]
could you be a little more specific? What browser? Screenshot?

**Comment by kevinlaw91** [comment]
Simply make it brighter will do. Example in screenshot :)

Chrome 52 (Latest)/ Win 7

![screen](https://cloud.githubusercontent.com/assets/4179182/17299635/b9032754-5841-11e6-991a-9570b8fd9eb2.jpg)

**Comment by silverwind** [comment]
By the way, does Chrome allow transparent scrollbar background? Would look great, I'd say (I'm a Firefox user).

**Comment by Mottie** [comment]
I just tried... it doesn't look like transparency works.

**Comment by silverwind** [comment]
Here's how mine looks right now. Note that it isn't part of the theme yet, but maybe you can take the idea of colored hover highlight:

![](https://cloud.githubusercontent.com/assets/115237/17300543/217a7744-5813-11e6-8260-f64f2d52a0f1.gif)

**Comment by Mottie** [comment]
Should I make it match the base color?

**Comment by silverwind** [comment]
Yeah, I think that'd be nice. Maybe make the normal state a tad brighter (not as bright as in the screenhot above).

**Comment by silverwind** [comment]
Looks like transparent background is behind a flag: `chrome://flags/#overlay-scrollbars`

**Comment by Mottie** [comment]
Hmm, actually if I made it match the base color, I couldn't set the opacity to 60%.... we might have to wait until browsers support [8-digit hex colors](https://drafts.csswg.org/css-color/#hex-notation).

**Comment by silverwind** [comment]
Do we need opacity at all?

**Comment by Mottie** [comment]
Yes, if you search for items on the page, the scroll bar highlights the position

![2016-08-01 11_18_04-scrollbar is hardly visible issue 372 stylishthemes_github-dark](https://cloud.githubusercontent.com/assets/136959/17300843/ae17e130-57d9-11e6-9557-fffbe2f4859f.png)

**Comment by kevinlaw91** [comment]
why 8-digit hex? rgba() would suffice i guess?

**Comment by Mottie** [comment]
When you set a base-color on userstyles, it's a hex value. For rgba() we need to convert each value to decimal... that isn't possible with pure css.

**Comment by Mottie** [comment]
So how does this look? I used the same colors that silverwind used for Firefox, but with an opacity

![scrollbar](https://cloud.githubusercontent.com/assets/136959/17301148/31ffdd6c-57db-11e6-9dc6-7378ea906483.gif)

**Comment by Mottie** [comment]
Sadly, I couldn't get the thumb to change color while hovering the track. Chome seems to ignore this selector combo:

```css
::-webkit-scrollbar-track:hover ::-webkit-scrollbar-thumb {
  background: rgba(102, 170, 255, .6) !important;
}
```

**Comment by silverwind** [comment]
Damn chrome seems to really ignore `opacity` on the thumb, so the possibilites are quite limited:

https://jsfiddle.net/silverwind/qzsbf0tm/158/

@Mottie: I like them, but how about square corners? :)

**Comment by un1versal** [comment]
> @Mottie: I like them, but how about 90° corners? :)

noooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by Mottie** [comment]
LOL... maybe we need to make that a separate style too :stuck_out_tongue:

**Comment by silverwind** [comment]
Also would suggest something like `#1d1d1d` on the backgroudn to make them match the default bg texture.

**Comment by kevinlaw91** [comment]
Btw, the idle state color should have brighter tone like I proposed. something like `rgba(255,255,255,*)`

**Comment by un1versal** [comment]
> LOL... maybe we need to make that a separate style too :stuck_out_tongue:

thats not a bad ideas together with https://gist.github.com/un1versal/b5803d60d6398c80808fbf618386a761  my modded version from silverwinds scrollbar thingy for firefox

**Comment by Mottie** [comment]
Hmm, yeah, and in that style we can make the user set the rgb colors separately...

**Comment by silverwind** [comment]
@kevinlaw91 bright enough? https://jsfiddle.net/silverwind/qzsbf0tm/161/

**Comment by kevinlaw91** [comment]
@silverwind, unfortunately still too dark. may I suggest `rgba(255,255,255,.4)`?

**Comment by un1versal** [comment]
white? lol

**Comment by kevinlaw91** [comment]
lol, not white tbh. 0.4 alpha makes it more like gray 😂

**Comment by Mottie** [comment]
Ok, what about https://jsfiddle.net/Mottie/qzsbf0tm/165/?

**Comment by silverwind** [comment]
@mottie @kevinlaw91  `rgba(144,144,144,.5)` is a good middle ground, no?

**Comment by Mottie** [comment]
Fine by me.

**Comment by silverwind** [comment]
By the way, it doesn't look like overlay-scrollbars is going to come out of experimental status any time soon, https://bugs.chromium.org/p/chromium/issues/detail?id=274010. Too bad, we could've made nice cross-browser overlay scrollbars that way. I still plan to add them for Firefox at least because they work flawlessly there :)

**Comment by kevinlaw91** [comment]
Hold on. I'm taking picture with my phone to show you why I suggest "white" as the color. Haha

**Comment by silverwind** [comment]
Your phone must've very bad color reproduction, lol.

**Comment by silverwind** [comment]
By the way, the reason I chose a shadow of grey instead of white is this (Firefox):

![](https://cloud.githubusercontent.com/assets/115237/17301980/3badfd28-581a-11e6-9377-a07e733c3107.png)

**Comment by un1versal** [comment]
> Hold on. I'm taking picture with my phone to show you why I suggest "white" as the color. Haha

phone?

![](https://images.duckduckgo.com/iu/?u=http%3A%2F%2Femoticoner.com%2Ffiles%2Femoticons%2Fcrazy-rabbit%2Fcalm-down-crazy-rabbit-emoticon.gif%3F1292793765&f=1)

**Comment by kevinlaw91** [comment]
It's about reflection guys :D

white:
![white](https://cloud.githubusercontent.com/assets/4179182/17302073/fafa1702-584c-11e6-889c-5ad29d611860.jpg)

144:
![middle](https://cloud.githubusercontent.com/assets/4179182/17302075/fefc699a-584c-11e6-8211-f42c65e9a251.jpg)

**Comment by Mottie** [comment]
Ok, tell ya what... since it's difficult to make everyone happy. We can create a new scroll bar userstyle that allows you to pick the colors.

**Comment by kevinlaw91** [comment]
subtle change to the color, but when the LCD panel is tilted and viewing angle will make it completely invisible in my case

**Comment by Mottie** [comment]
The opaque white is too bright for me... it's a bit distracting. I wish Chrome would support the selector combo where hovering over the scrollbar track would brighten the thumb.

**Comment by Mottie** [comment]
@silverwind, should we make it a global style for both Firefox and Chrome?

**Comment by un1versal** [comment]
> @silverwind, should we make it a global style for both Firefox and Chrome?

what about the other browsers? they also support webkit I bet, except FIrefox

**Comment by silverwind** [comment]
@Mottie I don't think another style is really an option. Why not just make the thumb color configurable on userstyles.org? It doesn't strictly need alpha because Chrome doesn't support it anyways. I'd say start with `#444` as the default:

https://jsfiddle.net/silverwind/qzsbf0tm/166/

> @silverwind, should we make it a global style for both Firefox and Chrome?

Good idea, but I'm afraid Chrome bugs might not make it work as expected everywhere (iframes).

**Comment by kevinlaw91** [comment]
@Mottie I'm still ok with 144. 255 is just an humble opinion from me because it works perfectly in my case. Thanks 😊

**Comment by silverwind** [comment]
> what about the other browsers? they also support webkit I bet, except FIrefox

IE/Edge does not support userstyles at all, and Opera is a copy of Chrome :)

**Comment by Mottie** [comment]
The scrollbar does work with rgba colors - https://jsfiddle.net/Mottie/qzsbf0tm/168/

And we do need the opacity. I use the browser search all the time, I need my markers!

**Comment by silverwind** [comment]
Hmm, userstyles.org does not support RGBA?

**Comment by Mottie** [comment]
Let me double check.

**Comment by un1versal** [comment]
> IE/Edge do not support userstyles at all, and Opera is a copy of Chrome :)

Opera was a browser long before Chrome came along...

> It's about reflection guys :D

Glossy screens should die in a fire :D

**Comment by silverwind** [comment]
Worst case, we could make it a text box where the user enters a RGBA string.

**Comment by Mottie** [comment]
Yeah, it looks like the input only allows hex colors

![color](https://cloud.githubusercontent.com/assets/136959/17302533/48d7d1be-57e2-11e6-9e7e-c8d59c5929fe.gif)

**Comment by kevinlaw91** [comment]
> Glossy screens should die in a fire :D

Gotta throw it away now and buy something with better view angle 😁

**Comment by silverwind** [comment]
Things are getting complicated. @kevinlaw91 how about https://jsfiddle.net/silverwind/qzsbf0tm/169/?

**Comment by Mottie** [comment]
Grrr, the hover color needs to be slightly opaque... I needs my search result markers!

**Comment by kevinlaw91** [comment]
@silverwind Do you like `rgba(180,180,180,.5)`?

**Comment by kevinlaw91** [comment]
this is the color for chrome console dark theme scrollbar

**Comment by silverwind** [comment]
This: https://jsfiddle.net/silverwind/qzsbf0tm/171/

**Comment by silverwind** [comment]
Tweaked background: https://jsfiddle.net/silverwind/qzsbf0tm/172/

**Comment by silverwind** [comment]
And tweaked hover, lol: https://jsfiddle.net/silverwind/qzsbf0tm/173/

**Comment by Mottie** [comment]
My eyes!
<img title=":_ onion_head_scared_to_death :" src="https://cloud.githubusercontent.com/assets/136959/13371679/b8583b12-dcf1-11e5-946e-98a993508ecc.gif">

**Comment by kevinlaw91** [comment]
alpha .99 is overkill i guess. haha

**Comment by silverwind** [comment]
> alpha .99 is overkill i guess. haha

Maybe so, yeah. Guess `.8` could be sufficient. @Mottie wanna make the change?

**Comment by Mottie** [comment]
Ok

**Comment by silverwind** [comment]
@Mottie you can still go a bit darker, if you like :D

**Comment by Mottie** [comment]
I'm gonna hold off on updating userstyles for a few more days LOL.

**Comment by Mottie** [comment]
OMG... https://github.com/JasonBarnabe/userstyles/issues/13

I could use `/*[[base-color-rgb]]*/` to add a rgb color... I guess it won't work for rgba.

**Comment by silverwind** [comment]
omg nice find. How about making it base-color, .99 alpha?

**Comment by Mottie** [comment]
I think it only adds the `#, #, #` part, so we could append an alpha channel setting. I'm testing it now, but
I seem to be getting an error on userstyles :(

**Comment by silverwind** [comment]
Something like this?

````
background: rgba(/*[[base-color-rgb]]*/, .99) rgba(65, 131, 196, .99) !important;
````

**Comment by Mottie** [comment]
yes, that is how it works! :grin:

**Comment by silverwind** [comment]
Actually, make it 

````css
    background: rgba(65, 131, 196, .9999) !important;
    background: rgba(/*[[base-color-rgb]]*/, .9999) !important;
````

so CSS won't invalidate the rule when pasting the style.

**Comment by Mottie** [comment]
Ahhh ok.

**Comment by Mottie** [comment]
Lint doesn't like it... duplicate rules.

**Comment by silverwind** [comment]
Drop the rule, Luke.

**Comment by un1versal** [comment]
> Drop the lint rule, Luke.

Belly button lint? eww

**Comment by un1versal** [comment]
> silverwind commented 2 days ago • edited
> 
> @Mottie: I like them, but how about 90° corners? :)

@silverwind Actually now that I actually engaged my brain, the answer is yes, rounded corners blow chunks
