### ISSUE TITLE
selected text visibility on label selection menu

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#373]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [ ] URL of unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

### Steps to Duplicate

assign or unassign labels to an issue/pr when hovering over the already set labels you see selected text is too dark.

![demo-a](https://cloud.githubusercontent.com/assets/3521959/17355739/95b40458-594a-11e6-8b8c-38ec64402630.gif)

I think class is `.label-select-menu .select-menu-item.selected` https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L1681-L1681

**Comment by Mottie** [comment]
Actually, GitHub doesn't add a background color when hovering over a set label... it's probably a better idea to keep it that way since the hover color interferes.

![color](https://cloud.githubusercontent.com/assets/136959/17374930/7208410c-5974-11e6-8e7f-903285041ec8.gif)

**Comment by silverwind** [comment]
Yes, try to keep it as close as possiple to the original. I think last time I tried to fix that menu, I was unable to replicate the label-colored background on selected labels, but maybe there is a way through some `invert` + `hue-rotate` magic.

**Comment by un1versal** [comment]
> Yes, try to keep it as close as possiple to the original

I disagree with this principle simply because their consistency is flawed
