### ISSUE TITLE
inconsistency with label selectors

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#375]
- [x] No other existing issue and/or pull request.
- [ ] URL of unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

This should be somewhat similar to what was done for #373

![demo-a](https://cloud.githubusercontent.com/assets/3521959/17392190/95d8b82e-5a13-11e6-8fba-69c7b76687b4.gif)

That shows styled and unstyled for guidance...

@silverwind this is why my reply to you in https://github.com/StylishThemes/GitHub-Dark/issues/373#issuecomment-237333024

 >silverwind commented 13 hours ago 
   > Yes, try to keep it as close as possiple to the original

> un1versal commented 12 hours ago
   >I disagree with this principle simply because their consistency is flawed

following original sucks because they cant keep neither consistency not make up their minds on which styles to keep on hover styles throughout all these menus

on some you have a blue bar as you hover over the options on some you have a semi transparent 
bar...

Since I love consistency immediately I dislike these things.

**Comment by Mottie** [comment]
Try that update... no more colored background on hover, for labels.
