### ISSUE TITLE
brighten up and have consistent color header/bold on markdown/reply boxes -- revisit  #250

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#377]
This is a revisit of issue #250 @silverwind prefers a new ticket open for easy tracking

![demo-a](https://cloud.githubusercontent.com/assets/3521959/17429309/f361957e-5ae5-11e6-8d12-0d9fe107140d.gif)
## Header / bold text

Currently as you can see above the bold text is more or less right color and intensity but header text is much much brighter, this should be consistent more or less with the unstyled

I prefer the brighter counterparts (not quite so bright) for header text / bold text because its reading text and makes a nice contrast because its not large portions of text.
## Quoted text

> This text should be slightly brighter,  so its easier for blind folk to see it.
## Normal Text

This regular text, when you compose message is `#eee` and then becomes `#c0c0c0` thats just too dull, imo the composing text and the preview rendered should be same intensity and color.

**Comment by silverwind** [comment]
You didn't include the actually problematic section:

># **bold** with a [link]() and some `code`
## **bold** with a [link]() and some `code`
### **bold** with a [link]() and some `code`
#### **bold** with a [link]() and some `code`

> Quote block text color

**Comment by silverwind** [comment]
I cleaned up the mess that was `strong` and header colors. GitHub does not infer color from those elements, and neither should we. GitHub uses `#777` for quoted text. The inversion of this was a bit too dark for me, so I went with the next color step, currently `#949494`.

Regarding body text, I'd say it's fine as is. Github uses `#333` pretty consistently for body and forms, so I'd say the edit box text should actually be darkened.

As said before, I do not like to move too far away from GitHub's general color theme.

**Comment by un1versal** [comment]
> You didn't include the actually problematic section:

I did its in the gif, but thats not the main reason in this ticket.

**Comment by un1versal** [comment]
> GitHub uses #777 for quoted text. The inversion of this was a bit too dark for me, so I went with the next color step, currently #949494.

Yep my feeling exactly.

> As said before, I do not like to move too far away from GitHub's general color theme.

Thats fine also but its not exactly possible to achieve the same balance or contrast in a dark vs white scenario, so you end up having to move away just far enough.

In my mind the ideal is good readability and contrast with some consideration paid to blinder folk.

**Comment by un1versal** [comment]
since the comment box has not been addressed heres something else.

Normal text still slightly too dark,

lets compare all markdown.

# H1
## H2
### H3
#### H4
##### H5
###### H6

As you can see H6 is slightly darker should be same as all other headers.

Alt-H1
======

Alt-H2
------

Underline style looks brighter then headers to me. imo should be same no?

---

>Quote box
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam magna urna, sodales nec ultrices in, facilisis et nibh. Vestibulum convallis. 

Quote still slightly too dark

---

`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam magna urna, sodales nec ultrices in, facilisis et nibh. Vestibulum convallis. 
`

single backtick brigness is same as normal text but since the background is draker is easier to read then the normal text/

---

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Nam magna urna, sodales nec ultrices in, 
facilisis et nibh. Vestibulum convallis. 
```

Code 3x backticks is nice and bright the normal text should be that bright also.

---

- Lorem ipsum dolor sit amet, consectetur adipiscing elit.
- Lorem ipsum dolor sit amet, consectetur adipiscing elit.

1. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
2. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

- [ ] Lorem ipsum dolor sit amet, consectetur adipiscing elit.
- [ ] Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Lists looks compared to nomarl text, thers no contrast difference which is fine but when looking it close to quotes and code boxes or single backticks it looks inconsistent.

Can this be revised an improved with half a mind payed into people who have not perfect vision?

**Comment by xt0rted** [comment]
Not sure if it's related, but the help pages also have some inconsistent header stylings. https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/

The classes for the `h4` tag is `.markdown-format h4`. The `pre > code` styling is a bit off as well which also uses the `.markdown-format` prefix.

**Comment by Mottie** [comment]
Thanks @xt0rted! I'll take a look.

**Comment by Mottie** [comment]
There, try those updates.

**Comment by Mottie** [comment]
@un1versal The inline code blocks were made slightly darker, but the code style *does* partly depend on the selected syntax highlighting theme.

**Comment by Mottie** [comment]
@silverwind I wonder if we should just combined the inline code "single lines" and "big blocks"? So that even the `inline code` will use the same background colors as the selected theme - this is especially prominent when using the solarized dark or cobalt theme.

**Comment by un1versal** [comment]
the inline code should have a slight difference from normal text, which is fine, ;) before these latest changes it was brighter than normal text when it should have been the other way around... which is what youve done, so its right at last.

the only thing that needs a slight tweak is the quote block though should be slightly darker than it is now, but a lil bit brighter than it was before,... ;)

**Comment by silverwind** [comment]
> combined the inline code "single lines" and "big blocks"

I'd leave them separate for now. If there are unsolveable issues on help, I'd suggest we start with https://github.com/StylishThemes/GitHub-Dark/issues/399.
