### ISSUE TITLE
Brighten up some markdown when edited via browser

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#378]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [ ] URL of unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

Currently if and when you [edit any markdown document via browser](https://github.com/StylishThemes/GitHub-Dark/edit/master/README.md) for e.g. this repos readme, some aspects are just way too dark while others are perhaps slightly too bright and vivid.

Consistency isnt as great as it could be due to the unbalance.

![capture](https://cloud.githubusercontent.com/assets/3521959/17429378/52d2d9b4-5ae6-11e6-8888-288d6617f8bf.PNG)

**Comment by Mottie** [comment]
Hey @un1versal!

What syntax highlighting theme is that?

**Comment by un1versal** [comment]
mebivore or whatever its called

**Comment by Mottie** [comment]
Actually, I would prefer not to change the base themes from what people expect. It is odd though that the Mebivore that we have doesn't match the one from here: https://ace.c9.io/build/kitchen-sink.html.

Anyway, I think the best option would be to create a new theme based on [the `mebivore.css` theme source file](https://github.com/StylishThemes/GitHub-Dark/blob/master/themes/src/merbivore.css).... you can use the demo (the `index.html` file) to test it... sadly, the ACE Editor theme is showing javascript and not markdown.

**Comment by un1versal** [comment]
Well Ill make a new theme then and then we can take it from there... Shouldn't be too hard

**Comment by Mottie** [comment]
LOL

The CSS for the Ace Editor all start out with `.ace_editor`... so all the selectors at the beginning apply to GitHub's syntax highlighting theme.

**Comment by un1versal** [comment]
Ive edited this theme colors fully but the bullet `*` and header `#` markers are unchanged, so still pretty much extremely hard to notice.

**Comment by un1versal** [comment]
So any idea how to fix the remainder `*` and `#` those arent part of ace editor I dont think, like I said edited the full lot and made no changes there.

**Comment by Mottie** [comment]
Find & modify `.ace_heading` and `.ace_list` in the theme. Or add this in a new style:

```css
.ace_heading, .ace_list {
  color: #ddd !important;
}
```

**Comment by un1versal** [comment]
That works, but FYI its not available in Mebivore and a few other themes GitHub Dark ships at all.

**Comment by Mottie** [comment]
Is this still an issue?

**Comment by un1versal** [comment]
Would need to check all the syntax highlighting themes to verify it.

**Comment by silverwind** [comment]
The CodeMirror themes are straigt from their repo and are usually pretty high-quality. I doubt it's really an issue anymore. Reopen if necessary.
