### ISSUE TITLE
Build status list is no longer fully styled

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#379]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [x] URL of unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

The build status list for PRs just stopped being fully styled. The background and border colors are now the default colors.

This is what it looks like in Edge (working on a plugin to use GitHub-Dark in it) and FireFox.

Example: https://github.com/NancyFx/Nancy/pull/2435#partial-pull-merging

<img width="587" alt="build-status" src="https://cloud.githubusercontent.com/assets/831974/17431288/48ef5f9a-5ac7-11e6-8dea-ef7f74dae5a6.png">

**Comment by un1versal** [comment]
confirmed broken

Personally I blame turtles and dags @Mottie gets too excited

**Comment by Mottie** [comment]
Hi @xt0rted!

Thanks for reporting this problem. I'll have it fixed in the master branch shortly. We need to take care of a few other issues before userstyles gets updated.

And I think we need to blame Nancy, she's the one that got reported!

**Comment by un1versal** [comment]
> And I think we need to blame Nancy, she's the one that got reported!

Nancy? Does  she own the turtles and dags?
