### ISSUE TITLE
Unstyled: PR status box

### ISSUE THREAD

**Issue by jawshooah** [StylishThemes/GitHub-Dark#380]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [x] URL of unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

URL: https://github.com/caskroom/homebrew-cask/pull/23485

Steps to reproduce: scroll down to the status box and click "Show all checks".

<img width="769" alt="screen shot 2016-08-05 at 3 51 47 pm" src="https://cloud.githubusercontent.com/assets/4551271/17448947/1a98f512-5b25-11e6-9e7e-55a9ad3d7645.png">

**Comment by Mottie** [comment]
Hi @jawshooah!

This was just fixed in #379.... I'll update userstyles soon.

**Comment by jawshooah** [comment]
Gotcha, sorry, my issue search must have been a bit too narrow.
