### ISSUE TITLE
PR Comment errors are hard to read

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#381]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [ ] URL of unstyled content.
- [x] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

<img width="582" alt="github-comment-error" src="https://cloud.githubusercontent.com/assets/831974/17460876/5fca12b6-5c46-11e6-80d2-5b826cc53276.png">
This is how it looks in Edge and FireFox, haven't tried any other browsers.

Click the Comment button on this issue, or any PR, without entering any text to get the error. The classes in question are `comment-form-error js-comment-form-error`

**Comment by un1versal** [comment]
fix concocted, should be up in a sec.
