### ISSUE TITLE
Unstyled content on release page

### ISSUE THREAD

**Issue by J2TeaM** [StylishThemes/GitHub-Dark#383]
### Unstyled Content

- URL of unstyled content: https://github.com/*USERNAME*/*REPO*/releases/edit/v1.0.0
- CSS Selector: `.uploaded-files>li.delete`
- Screenshot:

![image](https://cloud.githubusercontent.com/assets/5250117/17541778/05d20616-5eed-11e6-8cf0-a9ce5f3c8484.png)

**Comment by Mottie** [comment]
Thanks! It's all fixed in the master branch. I'll update userstyles soon.
