### ISSUE TITLE
unstyled tooltips

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#384]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [x] URL of unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

1) goto https://github.com/un1versal
2) hover over a few repos and wait for tooltip
3) goto https://github.com/username?tab=activity
4) hover over a link and wait for tooltip

styled vs unstyled demo

![demo-a](https://cloud.githubusercontent.com/assets/3521959/17544444/22bd0906-5ecf-11e6-86e1-617257f6d794.gif)

Im pretty sure I saw others but tbh cant remember now.

**Comment by un1versal** [comment]
theres others in wiki and comment box

styled tooltips vs unstyled demo

![demo-a](https://cloud.githubusercontent.com/assets/3521959/17544578/199a31ea-5ed0-11e6-87c4-e93a9b90037f.gif)

**Comment by un1versal** [comment]
theres more in notifications

https://github.com/notifications?all=1

![demo-a](https://cloud.githubusercontent.com/assets/3521959/17545086/ef392106-5ed2-11e6-9b16-52ab4f17a1d5.gif)

**Comment by Mottie** [comment]
Those are `title tooltips`, they are styled by the browser and there is no css that I know of that will style them.

**Comment by un1versal** [comment]
if thats true across browsers then consider unstyling them all so at least they look consistent

**Comment by Mottie** [comment]
You can't style them with css.

**Comment by xt0rted** [comment]
The styled ones are done via https://github.com/primer/tooltips

**Comment by Mottie** [comment]
Yes, the built-in tooltips... those tooltips require a `tooltipped tooltipped-{direction}` class name *and* the tooltip added to the `aria-label` attribute. All of the unstyled tooltips mentioned in this issue are `title` attribute tooltips. If you know how to style those, I'm all ears/eyes.

**Comment by xt0rted** [comment]
You can add styled tooltips with CSS just like GitHub is doing.
```css
a[title]:hover::after {
    content: attr(title);
    position: absolute;
    background-color: #fff;
    color: #333;
    padding: 5px;
    border-radius: 3px;
}
```

The issue with this is you'll still get the native tooltips showing next to these unless you can add a small piece of javascript to remove all of the `title` attributes which is really hacky and could break parts of the site. Plus without JS there's no way to properly position all of these.

There's no way to style the ones the browser creates, and no way to turn them off without removing the `title` attributes.

You could change the styled ones to be light colored like the native tooltips. These look different in each browser & OS though so you still won't have a consistent look, just color unless someone changes their system settings.

**Comment by Mottie** [comment]
Yes, converting titles into tooltips would be better suited as a userscript... I'll see what I can do.

**Comment by Mottie** [comment]
Ok, I've created a userscript - [click here to install](https://raw.githubusercontent.com/StylishThemes/GitHub-Dark-Script/master/github-script-make-tooltips.user.js).
