### ISSUE TITLE
Unstyled page

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#387]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [x] URL of unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [ ] Provide steps to reproduce (opening a dialog, etc).

https://enterprise.github.com/sn-contact

**Comment by Mottie** [comment]
The entire `enterprise` subdomain isn't styled, not just that one page.

Is it really *that* important to style pages that may only rarely be used? The style is already overly-bloated, adding style for one more domain isn't bad, but all the tweaks needed for that page that most people rarely visit seems to me that it might not be necessary.

**Comment by un1versal** [comment]
I find this odd, that sume sub domains are styled and some are not and already for the same reasons quoted above, I remember this discussion from when I added https://training.github.com/ and was declined for that reason.

so my question is, why favor some sub domains but not all?

imo you wither go all out or dont go there at all, half way jobs makes for a general odd look.

perhaps I suggest moving these subdomains to own separate style

**Comment by silverwind** [comment]
It's simple: We (open source developers) never visit those marketing-heavy pages, so we don't care about them. It'd be a full-time job of its own to just keep up with all the changes added by the many employees of GitHub. Not interested in that, sorry.
