### ISSUE TITLE
Impossible to read header colors on elements and pages

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#388]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [ ] URL of unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

Affected pages (random content inside)

https://github.com/site/terms
https://github.com/site/privacy
https://github.com/security

https://github.com/explore
https://github.com/open-source
https://github.com/business

the gif below is incomplete thers way too much stuff to include

![demo-a](https://cloud.githubusercontent.com/assets/3521959/17546216/faf2541c-5ed8-11e6-8ddf-236489af9b06.gif)

The one of many examples to show @silverwind that GitHub styles are flawed especially when you just darken something and leave content untouched or pick color styles that are equally as terrible.

i.e. You cannot follow these styles blindly. **CONSIDER USERS WITH VISUAL IMPAIRMENTS** (pun intended.) and ffs dont use baby sh*it color styles it looks awful on DARK

![capture](https://cloud.githubusercontent.com/assets/3521959/17546552/ae743edc-5eda-11e6-9108-2ac8b5f56f1c.PNG)

![capture3](https://cloud.githubusercontent.com/assets/3521959/17546681/450bbb5e-5edb-11e6-9380-6980d11ce309.PNG)

![capture2](https://cloud.githubusercontent.com/assets/3521959/17546680/4505baec-5edb-11e6-86c1-9c15ca51123d.PNG)

**Comment by Mottie** [comment]
I think I've fixed most of these... I don't remember how to get to this page though:

![capture](https://cloud.githubusercontent.com/assets/3521959/17546552/ae743edc-5eda-11e6-9108-2ac8b5f56f1c.PNG)

**Comment by un1versal** [comment]
> I think I've fixed most of these... I don't remember how to get to this page though:

https://github.com/contact

**Comment by Mottie** [comment]
I'll leave this issue open for now in case you find any more header color issues.

**Comment by silverwind** [comment]
I think we should eventually create separate `@-moz-document` sections for sites that run off their own stylesheets like `help.github.com`. Does Stylish for Chrome support multiple `@-moz-document` rules when importing a Mozilla-format style yet?

**Comment by Mottie** [comment]
Yes, Stylish splits them into separate sections. So it works just fine. Using the built-in editor is a tiny bit more troublesome though.

**Comment by silverwind** [comment]
Nice. We might be able to introduce color variables and re-use them in `@-moz-document` scoped sections.

http://caniuse.com/#feat=css-variables

**Comment by un1versal** [comment]
here is some more

to navigate there from github dark https://github.com/StylishThemes/GitHub-Dark/settings/hooks then scroll to bottom and click [Browse the directory](https://github.com/integrations) links to https://github.com/integrations 

#### class `intgrs-lstng-item-header`

![capture](https://cloud.githubusercontent.com/assets/3521959/18301472/8a1bc4f6-74c9-11e6-8140-4af77dc3079c.PNG)

**Comment by un1versal** [comment]
and some more at https://developer.github.com/libraries/

![capture](https://cloud.githubusercontent.com/assets/3521959/18607662/fc693670-7cca-11e6-84e3-bfbacf6c0e9c.PNG)

**Comment by silverwind** [comment]
All fixed i guess.

**Comment by un1versal** [comment]
> All fixed i guess.

Not really

See https://status.github.com/messages

![capture](https://cloud.githubusercontent.com/assets/3521959/19147192/f1b5bf44-8bae-11e6-8b03-b0bc41749660.PNG)

**Comment by silverwind** [comment]
Fixed in https://github.com/StylishThemes/GitHub-Dark/commit/117d6a1c0d53c25fed42e93da05b5ccd9b1425fa.
