### ISSUE TITLE
Merge Statuses are not styled on pull requests

### ISSUE THREAD

**Issue by Chekote** [StylishThemes/GitHub-Dark#391]
### Unstyled Content

- [ ] No other existing issue and/or pull request.
- [ ] There is no single URL. Any pull request with a merge status entry will display the issue.
- [ ] "merge-status-item" is the class of the unstyled content.
- [ ] Create a pull request with a merge status from a service such as CircleCI, Travis, etc.

![screen shot 2016-08-12 at 2 42 51 pm](https://cloud.githubusercontent.com/assets/550486/17618257/39b98494-609c-11e6-9eab-5ede0c907a38.png)

**Comment by un1versal** [comment]
I think youre not running an up-to-date version of GitHub Dark...

this works fine here current version and was fixed recently in https://github.com/StylishThemes/GitHub-Dark/commit/0a91d971477141b6ce722586d66ef87a72b7bd6e around 7 days ago

**Comment by Mottie** [comment]
Also see https://github.com/JasonBarnabe/stylish-chrome/issues/179

**Comment by silverwind** [comment]
Please update your style!
