### ISSUE TITLE
[new navigation for StackOveflow(beta feature)] the text in 2 of the 3 new tabs appears truncated

### ISSUE THREAD

**Issue by darkred** [StylishThemes/GitHub-Dark#394]
### Unstyled Content (not styled properly)

- [X] No other existing issue and/or pull request.
- [ ] URL of unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [X] Provide steps to reproduce (opening a dialog, etc).

<br>
Affected pages: http://stackoverflow.com/*

I've been testing the [New Navigation for StackOverflow](http://meta.stackexchange.com/questions/256814/new-navigation-for-stack-overflow-is-in-alpha-testing) (beta feature) some months now (using FF 48, Stylish 2.0.7 in win 10 x64).

I've noticed this issue:
The text in 2 of the 3 new tabs, `voted`, `active` appears truncated after applying the userstyle.
All three tabs, have this classname `.intellitab`.
STR
Login to  http://stackoverflow.com having enabled the new-nav feature.
Screenshots:
![2016-08-19_212949](https://cloud.githubusercontent.com/assets/723651/17820683/acab9612-6656-11e6-8c59-a1bf72a2fb23.jpg)
![2016-08-19_212936](https://cloud.githubusercontent.com/assets/723651/17820373/30e09a06-6655-11e6-9d81-7bfbd6181d6d.jpg)

**Comment by Mottie** [comment]
Hi @darkred!

Thanks, I'll look into this problem! And don't worry about closing this issue and reopening it in the Stackoverflow repo.

**Comment by darkred** [comment]
Sorry about that! Here it is https://github.com/StylishThemes/StackOverflow-Dark/issues/33
