### ISSUE TITLE
Network Graph not displaying at all

### ISSUE THREAD

**Issue by retep998** [StylishThemes/GitHub-Dark#395]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [x] URL of unstyled content. https://github.com/StylishThemes/GitHub-Dark/network or similar on any other repo.
- [x] Provide steps to reproduce (opening a dialog, etc). Go there with Firefox 47 on Windows 10 and the Network Graph doesn't display. Disabling the style with Stylish makes the Network graph visible again, reenabling the style promptly makes it vanish again.
- [x] Screenshots.
 Github Dark enabled ![](http://i.imgur.com/rdRdMek.png)
 Github Dark disabled ![](http://i.imgur.com/yooL8Ca.png)

**Comment by Mottie** [comment]
Hmm, I can't seem to duplicate this... I'm using Firefox v48.0.2 in Windows 10.

Are you using Stylish or the script?

**Comment by silverwind** [comment]
Also cannon reproduce (on Firefox 50 right now). Can you right-click > inspect the area and see if there's anything there at all, and if some style is hiding it?

**Comment by retep998** [comment]
I am using Stylish.

After a quick test with setting background-color on stuff...
The `<div id="network" class="network">` element is definitely visible.
The `<div class="network-graph-container js-network-graph-container" data-network-graph-meta-url="/StylishThemes/GitHub-Dark/network/meta" data-network-graph-chunk-url="/StylishThemes/GitHub-Dark/network/chunk">` inside it definitely is not.

Like, the canvas is there, but I have no idea why it isn't rendering. My cursor changes to the 4 way move cursor when I hover over the area where it should be, and turning off ad blockers has no effect. I don't really know what is going on. It is clearly there, just invisible. I can even click on it and it'll take me places.

**Comment by Mottie** [comment]
Try disabling all of the other addons. If it reappers then you know the culprit isn't Stylish. Re-enable the plugins one-by-one to find the cause.

If the problem is within Stylish, the try disabling the other styles.

**Comment by retep998** [comment]
I have every single style disabled except for Github Dark (not that I had any other styles that applied to Github anyway). I have disabled all my addons, switched back to default skin for Firefox, and restarted my browser. Network Graph still does not display with Github Dark enabled via Stylish. Disabling Github Dark makes it appear, and enabling it makes it disappear.

**Comment by retep998** [comment]
Here is the full contents of my current Github Dark style: https://gist.github.com/retep998/036bb8377e6648073c79ca3f33d51c07

**Comment by Mottie** [comment]
I'm not really sure how to fix the problem for you since I can't reproduce it.

Maybe try this:

* Right-click on the network graph and select "Inspect Element".
* In the Inspector tab, turn off stuff like `position:relative` and `overflow:hidden` to see if anything happens.

  ![network](https://cloud.githubusercontent.com/assets/136959/18023271/a4ed34f6-6bbc-11e6-8d3f-d173006ef3c7.gif)

I wonder if using the [GitHub-Dark-Script](https://github.com/StylishThemes/GitHub-Dark-Script) would make a difference.

**Comment by retep998** [comment]
I tried using the Github Dark Script instead, and the same issue occurs, the network graph is not visible.

**Comment by Mottie** [comment]
Try updating to Firefox since you're a version behind.

**Comment by retep998** [comment]
Firefox tells me I am up to date.
![](http://i.imgur.com/PmVpgj6.png)

**Comment by Mottie** [comment]
I'm using 48.0.2

**Comment by retep998** [comment]
After manually updating Firefox to 48.0.2, the Network Graph still does not display when using the Github Dark style.

**Comment by silverwind** [comment]
Hmm, Canvas issues can be GPU related. Try turning off Hardware acceleration in Advanced options, and also try Help - Restart with Addons disabled once.

**Comment by retep998** [comment]
Okay, seems like it is hardware acceleration which is causing it to not work when using Github Dark.

![](http://i.imgur.com/HFLbEXo.png)

**Comment by Mottie** [comment]
We use `filter: invert(90.5%) hue-rotate(180deg) saturate(200%) !important;` on the container, so that is likely why you're having issues then.

@silverwind Do you think we should make the inverting of the network graph optional? It seems like we been getting a lot of issues related to it.

**Comment by silverwind** [comment]
Given that it bugs like that with certain GPUs, I'd say we remove those filters. Maybe just a bit of opacity?

**Comment by retep998** [comment]
For the record I am using an AMD Radeon R9 380 with the very latest drivers.

**Comment by Mottie** [comment]
I can set up userstyles to allow choosing any of those options:

1. Default.
2. Opacity.
3. Invert.

**Comment by silverwind** [comment]
@Mottie Sure, if you like. I'm just a bit worried it might not be the most popular option. Let's make opacity the "default" thought, for best compatibilty.

**Comment by Mottie** [comment]
Do you want to take care of it? If you're busy, I'll work on it tomorrow. I'm trying to finish up a project right now... and I'm still reinstalling software since my reformat :crying_cat_face:

**Comment by silverwind** [comment]
I'll go ahead and make it transparent, like it was before. That should at least fix the immediate issue here.

**Comment by silverwind** [comment]
@retep998 try from `master`.

**Comment by retep998** [comment]
That change appears to work.

![](http://i.imgur.com/nwzpuOc.png)

**Comment by silverwind** [comment]
Thanks. It's not pretty, but at least it shows 😉 . I'm hoping GitHub will eventually move away from this unstyleable `<canvas>`.
