### ISSUE TITLE
Notification indicator is unstyled

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#398]
I think the ring around the blue dot is suppose to be same color as background when styled.

![store](https://cloud.githubusercontent.com/assets/3521959/18226276/200f9ccc-71fe-11e6-949e-1c4901437800.gif)

Havent checked yet  what the class is, if I find it Ill submit a fix

**Comment by Mottie** [comment]
[It is set here](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L148-L151). If the border color is missing, it might be from editing the source.

**Comment by un1versal** [comment]
the border was missing indeed thx...
