### ISSUE TITLE
Latest firefox Nightly blocks installing Stylish to use this.

### ISSUE THREAD

**Issue by AraHaan** [StylishThemes/GitHub-Dark#402]
The URL is here https://addons.mozilla.org/firefox/downloads/latest/2108/platform:5/addon-2108-latest.xpi?src=external-installbox when going to this in latest Nightly build (51.0a1).(Would open for Stylist itself but the repo to that is unknown).

**Comment by AraHaan** [comment]
turns out I looked at wrong spot the link to there was wrong for firefox.

**Comment by Mottie** [comment]
For future reference, the Stylish repo is here: https://github.com/JasonBarnabe/stylish/
