### ISSUE TITLE
Invert Colors of Folders within Repositories

### ISSUE THREAD

**Issue by AraHaan** [StylishThemes/GitHub-Dark#403]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [ ] URL of unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [ ] Provide steps to reproduce (opening a dialog, etc).

### Feature Request
Make Folders in a Repository be inverted colors.

**Comment by Mottie** [comment]
Hi @AraHaan!

Can you please clarify what you mean. Currently the folders (icons) are the same as the selected base color:

## `#4183c4`

![2016-09-10 06_23_16-stylishthemes_github-dark_ dark github style](https://cloud.githubusercontent.com/assets/136959/18410139/2fb74bf4-771f-11e6-812d-b368e2eb1c28.png)


## `#6D8048`

![2016-09-10 06_20_36-stylishthemes_github-dark_ dark github style](https://cloud.githubusercontent.com/assets/136959/18410142/3c370892-771f-11e6-9e0f-7012437d45b5.png)

**Comment by AraHaan** [comment]
oh.

**Comment by Mottie** [comment]
Did this answer your question? Can I close this issue?

**Comment by AraHaan** [comment]
yeah
