### ISSUE TITLE
Everything is on fire (major github feature update)

### ISSUE THREAD

**Issue by SEAPUNK** [StylishThemes/GitHub-Dark#404]
GitHub just now updated everything, including a new profile page, projects, etc.

https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features

**Comment by xt0rted** [comment]
These are a couple pages with issues now
https://github.com/StylishThemes/GitHub-Dark/projects
https://github.com/xt0rted

**Comment by Spidersouris** [comment]
https://developer.github.com/early-access/platform-roadmap/ too

**Comment by Mottie** [comment]
OMG it burns! LOL

Yeah, I think I might just add some quick patches to fix the big things, but now might be a good time to maybe start over to get rid of all the obsolete selectors in this style.

**Comment by ddavison** [comment]
#404 Issue Not Found.

*(sorry, had to)*

**Comment by jadengore** [comment]
@ddavison You beat me to it 👌

**Comment by SEAPUNK** [comment]
#404 style not found, more like

**Comment by silverwind** [comment]
> start over

We could start a branch for a rewrite from scratch with only the selectors that apply and with `@-moz-document`  scopes for each site. I estimate it will take a few weeks to finish. In the meanwhile, let's do some short-term fixes for the recent changes.

**Comment by Mottie** [comment]
Working on it now

**Comment by joubertredrat** [comment]
```css
/* new usernav on profile */
.user-profile-nav {
    background-color: transparent !important;
}

.user-profile-sticky-bar::after {
    background-color: #181818 !important;
}
```
Fixed new navbar on profile for me

**Comment by Mottie** [comment]
Hmm, I was going to make the `.user-profile-nav` also have a `#181818` background, but I think your idea is better.

**Comment by Mottie** [comment]
Nope, it needs to be `#181818`.

**Comment by silverwind** [comment]
Yeah, sounds better to have it go to the header-color once it stickies. BTW, I wouldn't mind dropping the sticky positioning later, similar to what I've done on the diff sticky.

**Comment by silverwind** [comment]
Inline discussion sample: https://github.com/nodejs/node/pull/8519#discussion-diff-78636665

**Comment by Mottie** [comment]
Thanks

**Comment by Mottie** [comment]
Ok, that's what I've got so far.

**Comment by Mottie** [comment]
Should I go ahead and update userstyles? I'm sure I've missed stuff.

**Comment by simov** [comment]
:wave: can we got some solid background on the profile's popular repositories? (low priority)

**Comment by Mottie** [comment]
Done

**Comment by simov** [comment]
Thanks :cat2: 
I added the contributions widget to that request, I think it needs a solid background too.

**Comment by Mottie** [comment]
You mean the graph or the timeline?

**Comment by simov** [comment]
![contrib](https://cloud.githubusercontent.com/assets/1694112/18530889/2fcccad6-7adc-11e6-9dfb-924842013f30.png)

This one.

**Comment by Mottie** [comment]
Graph LOL okay.

**Comment by SEAPUNK** [comment]
I wonder, how will the timeline images be handled?

**Comment by simov** [comment]
@Mottie yep, my bad. It's looking good now.

**Comment by Mottie** [comment]
@SEAPUNK Well we can either invert them or make them dimmer. I'll need to add some padding at the bottom too to keep them from overlapping the text.

**Comment by simov** [comment]
![popup](https://cloud.githubusercontent.com/assets/1694112/18531087/35fb6a74-7add-11e6-82cd-427ba6f87e55.png)

Header text and some weird shadow below the widget.

**Comment by Mottie** [comment]
Simov, that's exactly how it looks with the style turned off. Hover over it to see the highlight background.

**Comment by simov** [comment]
@Mottie 
![screen](https://cloud.githubusercontent.com/assets/1694112/18531198/b89bc834-7add-11e6-88ca-9f16e10ed228.png)

**Comment by Mottie** [comment]
@SEAPUNK What do you think of that fix?

Simov, ok I'll look again LOL

**Comment by SEAPUNK** [comment]
@Mottie I think the invert looks a tad nicer.

![](https://i.imgur.com/sjgPR2s.png) ![](https://i.imgur.com/6O6MZs8.png)

**Comment by Mottie** [comment]
@SEAPUNK What filter settings are you using?

**Comment by SEAPUNK** [comment]
`invert(90%)`

although I think there's a better number that will hit the sweet spot.

**Comment by SEAPUNK** [comment]
90.5% is pretty much perfect.

**Comment by Mottie** [comment]
Try these settings and tell me what you think

```css
-webkit-filter: invert(90.5%) hue-rotate(180deg) saturate(200%) !important;
        filter: invert(90.5%) hue-rotate(180deg) saturate(200%) !important;
```

**Comment by SEAPUNK** [comment]
Oh yeah, that's beautiful.

**Comment by Mottie** [comment]
Ok, I'll go ahead and use that... but I just updated userstyles.org, so I'll wait to update there until we get more stable.

**Comment by SEAPUNK** [comment]
Could the background be made transparent for these elements on the contribution timeline?

![](https://conf.6f.io/cba4cc3cc0d05089fa2b7.png)

**Comment by Mottie** [comment]
Sadly, we can't make it transparent or the horizontal border appears underneath.

**Comment by Mottie** [comment]
GitHub made the background white to hide that fact. I guess I could add some padding to make it look better.

**Comment by SEAPUNK** [comment]
What about setting it to the background colo-- well, that wouldn't work too nicely if the background was an image, oh well.

**Comment by Mottie** [comment]
> BTW, I wouldn't mind dropping the sticky positioning later, similar to what I've done on the diff sticky

@silverwind Maybe that code should be split out because others might find it useful.

**Comment by simov** [comment]
![tfa](https://cloud.githubusercontent.com/assets/1694112/18540814/e75c74ec-7b29-11e6-8a9a-1e9e0e175dd0.png)

The new TFA enforcing on organizations, the table border is white.

**Comment by simov** [comment]
![bg](https://cloud.githubusercontent.com/assets/1694112/18552251/4c18bc8a-7b64-11e6-8191-6a307bffbb21.png)

The background issue I mentioned yesterday. I guess you'll have to up your monitor brightness to see it.

**Comment by Mottie** [comment]
@simov It looks like that problem occurred because my selector to add a background to the contribution graph wasn't specific enough. GitHub didn't add a unique class name the the graph wrapper, so I had to improvise. Anyway, try it now.

**Comment by silverwind** [comment]
@Mottie I'll do a pass on the changes now.

**Comment by Mottie** [comment]
Thanks!

**Comment by simov** [comment]
Seems to be working, @Mottie :+1:

**Comment by silverwind** [comment]
Wow, what a ungodly hack their `position:sticky` on the user profile is. I managed to tame it with 
````css
.user-profile-nav.is-stuck, .user-profile-sticky-bar.is-stuck,
.user-profile-sticky-bar.is-stuck:after,
.vcard-names-container.is-stuck {
  position: static !important;
}
.user-profile-nav.is-placeholder, .user-profile-sticky-bar.is-stuck,
.vcard-names-container.is-stuck {
  display: none !important;
}
```
Given that the header background effect (which should be transparent, but that looks bad when sticky) doesn't really work with a background, I'm inclined to just make it the default.

**Comment by silverwind** [comment]
Done with the user profile. I opted to not include above hack as the page started to act rather weird. I think their JS is accessing some of the CSS properties I was modifying. 😟

**Comment by silverwind** [comment]
@Mottie care to help me out with https://github.com/nodejs/node/pull/8519#r78637092? The pseudo-element for the timeline line is not showing the `#444` background for some weird reason:
![](https://cloud.githubusercontent.com/assets/115237/18560095/618ea5fa-7b7a-11e6-8a95-81c129a66a89.png)

**Comment by Mottie** [comment]
GitHub set a `-1` z-index on it, so it disappeared when we added a background color.

**Comment by Mottie** [comment]
I'm not sure I like the `3px` width though... or, maybe the background should be more transparent?

**Comment by Mottie** [comment]
Oops, I broke it LOL

**Comment by silverwind** [comment]
@Mottie aargh, I'm getting speared by the timeline:

![](https://cloud.githubusercontent.com/assets/115237/18560854/ab53f73c-7b7d-11e6-90a9-4dff10eb4409.png)

**Comment by Mottie** [comment]
Skewered Silverwind, sounds like 🐟 on a stick, like 🍢 .

**Comment by silverwind** [comment]
Review timelines fixed with a hack. Let's :shipit:.

**Comment by Mottie** [comment]
Done.

**Comment by SEAPUNK** [comment]
Woo!

**Comment by simov** [comment]
No more :fire: 
Cheers :cocktail:
