### ISSUE TITLE
unstyled reply box on inline comments

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#405]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [ ] URL of unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

When commenting inline theres an unstyled reply box

![gif](https://cloud.githubusercontent.com/assets/3521959/18533076/5d9da1d2-7ad8-11e6-8df5-92062aa8b83b.gif)

**Comment by Mottie** [comment]
It should have been fixed in #404... do a forced update.

**Comment by un1versal** [comment]
I dont use this or the script anymore for a long time, Ill update my local fork tomorrow, thx

**Comment by un1versal** [comment]
thx, it works!

![capture](https://cloud.githubusercontent.com/assets/3521959/18533622/56838584-7adc-11e6-8d68-4cb0290d7dc9.PNG)

**Comment by Mottie** [comment]
YAY!

So, I'm going to start working on version 2 of this style. I think it might be nicer to use [SASS](http://sass-lang.com/guide) variables. That way you can change the values of colors to whatever you want. Once I get things set up, I would appreciate some help and feedback 😉.

**Comment by un1versal** [comment]
I'll help where I can and *always* provide feedback, goes without saying....

**Comment by silverwind** [comment]
[CSS Variables](http://caniuse.com/#feat=css-variables) are supported in everything but Edge nowadays, by the way :)

**Comment by Mottie** [comment]
I was just trying them out yesterday, the Stylish editor shows lots of lint error messages, but it works. I still don't think it's possible to manipulate colors though 😢.
