### ISSUE TITLE
Unstyled button

### ISSUE THREAD

**Issue by J2TeaM** [StylishThemes/GitHub-Dark#408]
- [X] No other existing issue and/or pull request.
- [X] URL of unstyled content: https://github.com/J2TeaM/awesome-AutoIt/blob/master/CONTRIBUTING.md
- [X] The class name of unstyled content: `#js-repo-pjax-container div.file-navigation.js-zeroclipboard-container > div.BtnGroup.float-right > button`

![image](https://cloud.githubusercontent.com/assets/5250117/18585746/f72e01be-7c42-11e6-9ecc-8f7f07bb214f.png)

I think maybe GitHub forgot a few classes for this button :trollface:

![image](https://cloud.githubusercontent.com/assets/5250117/18585696/a76e82fc-7c42-11e6-8e73-a8938abac12e.png)

**Comment by Mottie** [comment]
Hi @J2TeaM!

Thanks for letting us know. Man, that button is fugly.

**Comment by silverwind** [comment]
Not seeing this anymore, I guess we ca revert the fix?

Current HTML:
```
<button aria-label="Copy file path to clipboard" class="js-zeroclipboard btn btn-sm BtnGroup-item tooltipped tooltipped-s" data-copied-hint="Copied!" type="button">Copy path</button>
```

**Comment by J2TeaM** [comment]
@silverwind agree, I noticed that they have added two classes `btn btn-sm`.

**Comment by silverwind** [comment]
Alright, reverted. Better not add more cruft. :)
