### ISSUE TITLE
Unstyled content, pull request inline review new review procedures notices

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#409]
### Unstyled Content

- [x] No other existing issue and/or pull request.

![gif](https://cloud.githubusercontent.com/assets/3521959/18594045/09876e2a-7c36-11e6-95b9-bcb192ada76f.gif)

This was added recently to get this message again clear all GitHub cookies.

**Comment by silverwind** [comment]
Already fixed in https://github.com/StylishThemes/GitHub-Dark/commit/63d085fbcd1ecb3b1bbeb37235ed08df9da6e613, please update!
