### ISSUE TITLE
Syntax highlighting on GH Blog

### ISSUE THREAD

**Issue by skwerlman** [StylishThemes/GitHub-Dark#410]
Using the Vibrant Ink variant of theme.

https://developer.github.com/changes/2016-04-18-new-webhook-actions-are-live/

![image](https://cloud.githubusercontent.com/assets/6954107/18608602/fce6c89c-7cbb-11e6-9e0d-313d08f0dec6.png)
(No, the code is not selected)

**Comment by Mottie** [comment]
Hi @skwerlman!

Please share which syntax highlighting theme you have selected.

**Comment by Mottie** [comment]
Oh, sorry, somehow I glossed over your first sentence LOL. Anyway, this should be fixed. I'll update the userstyles site in a minute.

**Comment by Mottie** [comment]
Hmm, and that blue isn't very readable. I just remembered that their help/developer pages still use pygments, but we don't have a vibrant ink pygments style.

**Comment by Mottie** [comment]
Ok, this should now be resolved. Since there isn't a Vibrant Ink pygments style, it currently falls back to Twilight.
