### ISSUE TITLE
Font smoothing in OS X seems to make the text look worse

### ISSUE THREAD

**Issue by mannykary** [StylishThemes/GitHub-Dark#412]
I've noticed that the text is a bit blurry in OS X. I'm not sure if it's because I'm using an external monitor (1920x1080 resolution), but I can see the same issue when I view GitHub on my MacBook Pro  (with Retina screen).

Here are comparison screenshots:

Font smoothing on:
![font_smoothing_on](https://cloud.githubusercontent.com/assets/4285073/18618311/f467fdb6-7d98-11e6-8359-702ebd3b9d41.png)

Font smoothing off:
![font_smoothing_off](https://cloud.githubusercontent.com/assets/4285073/18618313/fc3136fc-7d98-11e6-8af8-4b805f846c1f.png)

<h2>When viewing code:</h2>

Font smoothing on:
![code_font_smoothing_on](https://cloud.githubusercontent.com/assets/4285073/18618316/14ee12e6-7d99-11e6-94d2-9493d252504d.png)

Font smoothing off:
![code_font_smoothing_off](https://cloud.githubusercontent.com/assets/4285073/18618317/1c6f57e6-7d99-11e6-8be5-5f639966ffde.png)

I turned off font smoothing by commenting out the [CSS for OS X font rendering](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L2754).

Related ticket: https://github.com/StylishThemes/GitHub-Dark/issues/86

**Comment by silverwind** [comment]
You prefer this overly bold rendering? I'd argue that it helps on that code font, but on the main site (especially on buttons), it makes matter worse.

I wonder why you're seeing a change on a retina display, as the pixel ratio media query should prevent it from taking effect there.

**Comment by mannykary** [comment]
On the contrary, I don't mind the overly bold text on the main site, but to each their own.

I had a suspicion that it was due to my external monitor, so I disconnected it to see if the media query would be ignored. Unfortunately not:

![image](https://cloud.githubusercontent.com/assets/4285073/18618512/24ec6f72-7d9d-11e6-8d8a-ba722a440f2d.png)

I also confirmed that the resolution of my screen is indeed over 1.99dppx (using mydevice.io):
![image](https://cloud.githubusercontent.com/assets/4285073/18618520/48d65fc4-7d9d-11e6-91e6-a77901b38c71.png)

**Comment by silverwind** [comment]
Hmm, does it work if you change the media query to `-webkit-min-device-pixel-ratio: 2`?

**Comment by mannykary** [comment]
When I use that media query condition, it does not get applied on my screen, which makes no sense because my screen is retina, and the media query condition you mentioned targets retina screens. So shouldn't the media query be applied?

Conversely, I tried `-webkit-max-device-pixel-ratio: 2`, which should only target non-retina screens, and it gets applied.

**Comment by mannykary** [comment]
The media query works as expected on my 11-inch MacBook Air, which does not have a retina screen. I'm a bit at a loss for why there is inconsistent behavior here.

**Comment by silverwind** [comment]
Decided to remove the hack as I recently discovered a system-wide switch to disable this overly bold light-on-dark text in the General section of the System Preferences (needs a reboot to become active):

<img width="284" alt="" src="https://cloud.githubusercontent.com/assets/115237/20494641/288b3fd8-b01e-11e6-87bf-0aa9b5e1cffa.png">
