### ISSUE TITLE
:eyeglasses:  :sunny:  weird styling in API (developer)  page

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#413]
### Unstyled Content

- [x] No other existing issue and/or pull request.
- [x] URL of unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

nav to https://developer.github.com/
toggle style on/off

![gif](https://cloud.githubusercontent.com/assets/3521959/18629439/482e0c64-7e5d-11e6-9ce0-070c0f00c7df.gif)

also notice the Explore the documentation button is blue (equivalent to basecolor?) when unstyled and styled its black, so the design intent is considerable from the call to action not being so obvious.

also notice the top banner and links become unreadable when styled.

**Comment by un1versal** [comment]
also the magnifying glass on search box goes bye bye...

I blame @mottie he likes turtles and dags and caravans and the tick...

**Comment by Mottie** [comment]
Fixed.
