### ISSUE TITLE
Theme Request: Dracula

### ISSUE THREAD

**Issue by darvid** [StylishThemes/GitHub-Dark#415]
Edited to show progress:

* [ ] GitHub: **needed**
* [x] CodeMirror: Added
* [x] Jupyter: Added

----

### Unstyled Content
- [ x ] No other existing issue and/or pull request.
### Feature Request

Support for the [Dracula](https://draculatheme.com/) color scheme would be fantastic.

**Comment by silverwind** [comment]
https://github.com/dracula/sublime/blob/master/Dracula.tmTheme
https://github.com/dracula/pygments/blob/master/dracula.css

**Comment by Mottie** [comment]
Adding these should be fairly easy; but the way the build process is set up, a base GitHub theme is required before a CodeMirror or Jupyter theme can be included.

**Comment by Mottie** [comment]
As the GitHub syntax theme would need to be hand crafted (see [this comment](https://github.com/StylishThemes/GitHub-Dark/issues/425#issuecomment-250357197) for more details), I added an assistance welcome label.

**Comment by Mottie** [comment]
I've updated userstyles to allow setting the three syntax themes (GitHub, CodeMirror & Jupyter) separately, so you can at least enjoy Dracula in CodeMirror and Jupyter pages.

**Comment by abhinavk99** [comment]
Are there any plans to complete the Dracula theme for Github? It's been a while since there's been any activity on this issue so I'm just wondering.

**Comment by the-j0k3r** [comment]
> Are there any plans to complete the Dracula theme for Github? It's been a while since there's been any activity on this issue so I'm just wondering.

Just going trough issues I noticed this,, given the lack of progress I would add, any help anyone interested can provide to get this moving along would be fantastic. =)

**Comment by stephen-bunn** [comment]
If anyone is interested in a quick solution, I threw together a personal branch at https://github.com/stephen-bunn/GitHub-Dark/tree/dracula-github-theme to give myself a basic Dracula GitHub theme. I haven't yet opened a PR as there is a rewrite in progress (https://github.com/StylishThemes/GitHub-Dark-Syntax-Themes) that has blocked other similar PRs (#1226).

**Comment by silverwind** [comment]
I'm happy to merge more themes in a similar spirit than https://github.com/StylishThemes/GitHub-Dark/pull/1226.
