### ISSUE TITLE
Background image source for versions prior to 1.15.3

### ISSUE THREAD

**Issue by Fironet** [StylishThemes/GitHub-Dark#416]
Could the previous background image be linked/attached here? I find it much nicer than the one that replaced it in the latest 1.15.3 (9/19/2016) update and would like to be able to use it for my version. Thanks.

**Comment by silverwind** [comment]
It's here: https://github.com/StylishThemes/GitHub-Dark/blob/master/images/backgrounds/bg-tile1.png

**Comment by silverwind** [comment]
@Mottie this is because I've switched the Background to `bg-crosshatch.png` on userstyles.org.

**Comment by Fironet** [comment]
@silverwind thanks. Found it in the meantime by mounting a day old backup :) Is there a way of modifying userstyles without breaking the auto updates?

**Comment by silverwind** [comment]
Yes, your best bet is another style on top of ours. I'm not sure about the loading order of Stylish, but it's probably alphabetically.

As for the backgrounds: Maybe we ca add both as options.

**Comment by Mottie** [comment]
> Maybe we ca add both as options.

Easy enough to do.

**Comment by Mottie** [comment]
Done... I named it "Original"

**Comment by silverwind** [comment]
Looking great, thanks!
