### ISSUE TITLE
White nav bar on user page

### ISSUE THREAD

**Issue by JimViebke** [StylishThemes/GitHub-Dark#417]
The nav bar on a user page is white and the grey text is difficult to read. See my user page for an example: https://github.com/JimViebke.

I think the full class name is `user-profile-nav js-sticky top-0`.

**Comment by silverwind** [comment]
Are you updated? I don't see it:

![](https://cloud.githubusercontent.com/assets/115237/18756570/be488858-80f0-11e6-86b7-c7f8a12b3db4.png)

**Comment by JimViebke** [comment]
Possibly my update is failing silently? https://www.dropbox.com/s/gyrtjte4krm0ln9/github%20dark.PNG?dl=0

**Comment by Mottie** [comment]
The Chrome Stylish addon doesn't seem to update as expected - see https://github.com/JasonBarnabe/stylish-chrome/issues/179. To fix this, please go to the [userstyles page](https://userstyles.org/styles/37035/github-dark) and update from there.

**Comment by JimViebke** [comment]
Thank you! Updating from the userstyles page fixed the issue.
