### ISSUE TITLE
Github Guides black headers intead of greyish

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#418]
### Unstyled Content

- [x] I am using the most up-to-date GitHub Dark style!

  

- [x] No other existing issue and/or pull request.
- [ ] Provide the URL of the unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.

  

- [x] Provide steps to reproduce (opening a dialog, etc).

https://guides.github.com/features/mastering-markdown/

![capture](https://cloud.githubusercontent.com/assets/3521959/18786742/62e3019e-8197-11e6-91ca-2eac805a524e.PNG)

**Comment by Mottie** [comment]
Thanks, all fixed.
