### ISSUE TITLE
repo name are overlaping with slash

### ISSUE THREAD

**Issue by SSARCandy** [StylishThemes/GitHub-Dark#419]
### Unstyled Content

- [x] I am using the most up-to-date GitHub Dark style!

  

- [x] No other existing issue and/or pull request.
- [x] Provide the URL of the unstyled content.
- [x] If unable to provide a URL, please report the class name of unstyled content.

  

- [x] Provide steps to reproduce (opening a dialog, etc).

https://github.com/StylishThemes/GitHub-Dark

![image](https://cloud.githubusercontent.com/assets/6803791/18808359/8d70ccc4-8292-11e6-86d9-3b9334a72d05.png)
In trending page, all repo name are overlaping with the `/`, I found that in original style, all repo name will prefix with `space`, but github-dark didn't.

I think it could be fix by modifying `margin-right` in `.slash` class.

**Comment by silverwind** [comment]
Hmm, we don't touch the layout there. Does the issue show with the style disabled? Are you up to date?

![](https://cloud.githubusercontent.com/assets/115237/18808674/c67379ba-8268-11e6-8fad-03ddd7b4dea3.png)

**Comment by Mottie** [comment]
I'm not seeing the issue either, but it is interesting that GitHub's stylesheet has this definition applied to the "slash".

```css
.repo-list-name .slash {
    margin-right: -4px;
    margin-left: -4px;
}
```

**Comment by silverwind** [comment]
Must be some kind of hack on their part. What browser are you using @SSARCandy?

**Comment by SSARCandy** [comment]
i'm pretty sure my style is up to date(I'm using user-script and had click `Force Update Style`)
my browser is chrome(53.0.2785.116 m (64-bit))

**Comment by SSARCandy** [comment]
this is the DOM tree with the style-disabled
![image](https://cloud.githubusercontent.com/assets/6803791/18809157/c3992a2a-82a7-11e6-8a32-3a5164268b5b.png)

and this is enabled
![image](https://cloud.githubusercontent.com/assets/6803791/18809160/df787dfe-82a7-11e6-9026-c23df4ae9c22.png)

i think the problem is repo name with and without `spaces` prefix

**Comment by Mottie** [comment]
I've never see the "ghh-repo-x" and "tooltipstered" class names before. I wonder if it is a different extension or userscript?

**Comment by SSARCandy** [comment]
@silverwind  I install it form https://greasyfork.org/en/scripts/15562-github-dark-script

**Comment by Mottie** [comment]
Yes, but I'm saying that whatever is modifying the HTML and adding the above class names ("ghh-user-x" is *not* our script). Please turn off any other userscripts and/or browser extensions or addons to determine which one is making the modification.

**Comment by SSARCandy** [comment]
ok, I found the problem.
it is because **GitHub Hovercard(0.8.1)** 
by disabled it, everything works fine!

sorry for bothering you guys
