### ISSUE TITLE
Organizations - Teams - White border again :)

### ISSUE THREAD

**Issue by simov** [StylishThemes/GitHub-Dark#420]
![border](https://cloud.githubusercontent.com/assets/1694112/18811587/690e1dac-82bd-11e6-9023-f8e82a86762c.png)

**Comment by Mottie** [comment]
Hi @simov!

Please provide the class names for that box. I'm not seeing it in our organization.

**Comment by simov** [comment]
![borders](https://cloud.githubusercontent.com/assets/1694112/18811668/a660fc6c-82c0-11e6-9f4c-878e8b9cfbac.png)

I'm not very familiar with your code base, that's why I'm just reporting it.

**Comment by Mottie** [comment]
Ok, thanks! Please make sure it's been fixed.

**Comment by simov** [comment]
It's looking good :cat2:
