### ISSUE TITLE
Editor is now CodeMirror

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#422]
GitHub switched from ACE to CodeMirror on Gist and GitHub. We need to

- Investigate if ACE is active somewhere, otherwise drop the ACE themes.
- Create new themes. Examples: https://github.com/codemirror/CodeMirror/tree/master/theme
- Do a general pass on things not styles by themes (`cm-s-github` is a partial theme that relies on CodeMirror's default theme to some extent)

**Comment by silverwind** [comment]
Twilight theme is partially done. Unresolved issue: selection and line highlight do not work.

**Comment by silverwind** [comment]
Looking at the official CodeMirror themes, only these are available from our themes:

- [x] ambiance
- [ ] chaos
- [ ] clouds-midnight
- [x] cobalt
- [ ] idle-fingers
- [ ] kr-theme
- [ ] merbivore
- [ ] merbivore-soft
- [x] monokai
- [ ] mono-industrial
- [ ] mono-industrial-clear
- [ ] obsidian
- [x] pastel-on-dark
- [x] solarized-dark
- [ ] terminal
- [ ] tomorrow-night
- [ ] tomorrow-night-blue
- [x] tomorrow-night-bright
- [x] tomorrow-night-eighties
- [x] twilight
- [x] vibrant-ink

I'm thinking about dropping some of the lesser used (some in bad state) to have fewer, but well-supported themes.

**Comment by Mottie** [comment]
YAY <sarcasm>, I wake up to this!

It's gonna be a fun day.

I'll take a look at the Twilight theme. All the tomorrow-night and tomorrow-night-blue are essentially the same colors with a different background, I think.

**Comment by Mottie** [comment]
I think I'm going to separate the syntax, Jupyter and Code mirror themes into different source files. Then combine them in the build process so if a style is missing, we can fall back to Twilight, or something.

**Comment by un1versal** [comment]
would be a good time to do a github-dark default theme... joking Im not volunteering.

**Comment by silverwind** [comment]
@Mottie sounds like a plan. Twilight is already fixed, I'm workin on ambience right now and will basically copy-paste all themes that are available as official CodeMirror themes. Wanna get the Gruntfile up to the task?

**Comment by Mottie** [comment]
Ok, I'll start with that. And yes, we can add the primer GitHub dark theme into the mix.

**Comment by silverwind** [comment]
@Mottie maybe we could do a structure like:

`themes/github` (for the sake of not having a better name)
`themes/codemirror`
`themes/jupyter`

The task should create `.min.css` files with all three themes concatenated, if a specific theme isn't there, fallback to twilight or something. I hope it's doable with Grunt.

**Comment by Mottie** [comment]
Yeah it is and that actually was my plan. Get outta my head! 😁

**Comment by un1versal** [comment]
> ...Get outta my head! :grin:

sounds like an old Billie Ocean song...

**Comment by Mottie** [comment]
> Billie Ocean song

Thanks! Now it's stuck in my head LOL

**Comment by silverwind** [comment]
ambience done, cobalt next.

**Comment by silverwind** [comment]
All available CodeMirror themes done (see https://github.com/StylishThemes/GitHub-Dark/issues/422#issuecomment-249419814).

**Comment by Mottie** [comment]
Awesome! Now I can actually rearrange the folders LOL

**Comment by silverwind** [comment]
Sec, I think I messed up Solarized dark, lol.

**Comment by silverwind** [comment]
Nevermind, the color change was intentional. Go ahead.

**Comment by silverwind** [comment]
Note: Active line highlight in CodeMirror might not work as expected with minfied themes in Firefox because of a [clean-css bug](https://github.com/jakubpawlowicz/clean-css/pull/814).

**Comment by Mottie** [comment]
Ugh, I've been cleaning up the code and I have to run out for a bit. I'll pick this up again in about an hour.

I'll push the work I have so far, but it is not yet complete.

**Comment by Mottie** [comment]
Ok, please check https://github.com/StylishThemes/GitHub-Dark/commit/23f4bc7a540a72c39311a692c5149fc1ec5472ed

I'll be back in a bit.

**Comment by Mottie** [comment]
Ok, everything should be done now.

I ran into two issues:

* @silverwind I don't know how to get stylelint, in the command line, to check the css in the `github`, `codemirror` and `jupyter` subfolders. Can you help me out with that please? 😁 
* Most times when I run `grunt themes`, the `build` folder isn't being removed. I'm not sure why.

**Comment by silverwind** [comment]
@Mottie the clean-css bug has been fixed. Please make sure to `npm i -g clean-css` before the next release of theme files. ;)

**Comment by silverwind** [comment]
> @silverwind I don't know how to get stylelint, in the command line, to check the css in the github, codemirror and jupyter subfolders

I think you need to `themes/**`, which depends on your shell having recursive globbing enabled `shopt -s globstar` in bash, `setopt globstarshort` in zsh.

Note that stylelint does not support recursive directories linting like eslint does (you could skip the `/**` with eslint). Related: https://github.com/stylelint/stylelint/issues/717
