### ISSUE TITLE
ace editor gutter is unstyled when in document edit mode.

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#423]
### Unstyled Content

- [x] I am using the most up-to-date GitHub Dark style!

  

- [x] No other existing issue and/or pull request.
- [ ] Provide the URL of the unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.

  

- [x] Provide steps to reproduce (opening a dialog, etc).

edit a file via browser

![capture](https://cloud.githubusercontent.com/assets/3521959/18815022/bbb3aa5a-831b-11e6-9819-b12fb7e65cb5.PNG)

**Comment by silverwind** [comment]
ACE was replaced by CodeMirror. See https://github.com/StylishThemes/GitHub-Dark/issues/422

**Comment by un1versal** [comment]
its still broken...
