### ISSUE TITLE
Remove .min.css files from git

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#424]
I think we should untrack them and add `*.min.css` to `.gitignore`. They are just build artifacts which polute the git history and serve no real purpose being in version control.

**Comment by Mottie** [comment]
Ok, sounds good to me.

**Comment by Mottie** [comment]
Actually, the [main demo](https://stylishthemes.github.io/GitHub-Dark/) uses those files.

**Comment by silverwind** [comment]
Whoops. Wanna link the demo to the unminfied files?

**Comment by Mottie** [comment]
Yeah, working on that now.

**Comment by Mottie** [comment]
Well, now I found out that this change also breaks the GitHub Dark script theme selection and the [archived pygments demo](https://stylishthemes.github.io/GitHub-Dark/archived/), which doesn't really matter.

I guess I could rewrite the script to load it the source files, but I won't have time until later today, unless you think reverting this change is a better idea.

**Comment by silverwind** [comment]
Okay the script issue is a bit hard to fix, reverted in https://github.com/StylishThemes/GitHub-Dark/commit/5f4dbe2261a62f011faaea924bfc27df84012f47 for now.

**Comment by Mottie** [comment]
I think I'm going to move the archived pygments style into a new repository as well as update the script to load the src files... I have a bunch of stuff to take care of before my trip, so I'll try to get it done sometime today.

**Comment by silverwind** [comment]
Didn't you mention that pygments was still in use somewhere? Are we sure it's gone? If not, I'd suggest creating a `themes/pygments` directory and put in the files where we have a matching GitHub theme.

**Comment by Mottie** [comment]
Yeah, Jupyter and I think the API (Developer) pages are using pygments.

**Comment by Mottie** [comment]
The way the build script is set up, you need a theme in the github folder before any codemirror or jupyter styles are added. So yeah, we could fill up the jupyter folder with a bunch of styles, but they won't be used. Unless you think we should allow separate theme selection for github, codemirror and jupyter.

**Comment by silverwind** [comment]
So jupyter themes are actually pygments?

**Comment by Mottie** [comment]
yes, but we add an extra `#notebook .highlight table` to the beginning of each one.

**Comment by silverwind** [comment]
Yeah, that ought to be one thing domain-scoped rules will solve. I'm fine if we remove those old pygments themes from the repo, given that we can transform the jupyter ones easily later.
