### ISSUE TITLE
Updating style breaks everything

### ISSUE THREAD

**Issue by EnzoMartin** [StylishThemes/GitHub-Dark#427]
Seems the update from October 1st broke a few things, hitting `Update` from Stylish has resulted in the following in Chrome 53:

![screen shot 2016-10-06 at 16 44 57](https://cloud.githubusercontent.com/assets/735558/19157075/62431bbe-8be4-11e6-970b-7f973f9a6ff2.png)

**Comment by silverwind** [comment]
Just to make sure it's userstyles related: Does `import` with https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-dark.css work?

**Comment by EnzoMartin** [comment]
It works, but there's still errors:

![screen shot 2016-10-06 at 17 16 42](https://cloud.githubusercontent.com/assets/735558/19158371/bd705ad4-8be8-11e6-86ff-888713924fe8.png)

**Comment by silverwind** [comment]
Huh, this is weird. Chrome should support `@supports` since ages and the syntax looks correct. I'll check out userstyles.org.

**Comment by silverwind** [comment]
Okay the style template on userstyles.org was definitely corrupted. I've uploaded a new build, please try again. Not sure what to make out of these errors, thought.

**Comment by EnzoMartin** [comment]
Works 👍 

Still some errors showing though, but nothing breaking I can see

Thanks!
