### ISSUE TITLE
Unstyled content

### ISSUE THREAD

**Issue by J2TeaM** [StylishThemes/GitHub-Dark#428]
### Unstyled Content

- [x] I am using the most up-to-date GitHub Dark style!
- [x] No other existing issue and/or pull request.
- [x] URL: https://github.com/orgs/[ORGANIZATION]/invitations/[USERNAME]/edit
- [x] The class name of unstyled content: `.add-member-team-list .team-row-header`

### Screenshot

![image](https://cloud.githubusercontent.com/assets/5250117/19164323/ae68c094-8c29-11e6-985a-cdda48506af3.png)

**Comment by silverwind** [comment]
Thanks, totally missed that page.
