### ISSUE TITLE
Unstyled Content: Commit Form

### ISSUE THREAD

**Issue by jawshooah** [StylishThemes/GitHub-Dark#429]
### Unstyled Content

- [x] I am using the most up-to-date GitHub Dark style!
- [x] No other existing issue and/or pull request.
- [x] Provide the URL of the unstyled content.
- [x] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

---

Any URL for editing a file through GitHub's web UI will do. Here: https://github.com/StylishThemes/GitHub-Dark/edit/master/README.md

Both the `input` and `textarea` elements are unstyled.

<img width="1001" alt="screen shot 2016-10-08 at 1 37 13 pm" src="https://cloud.githubusercontent.com/assets/4551271/19215014/aabad1d0-8d5f-11e6-9ad6-c2975daf8592.png">

<img width="817" alt="screen shot 2016-10-08 at 2 00 26 pm" src="https://cloud.githubusercontent.com/assets/4551271/19215015/ac40917a-8d5f-11e6-8c28-d7624e6ab1ac.png">

**Comment by silverwind** [comment]
Hmm, not seeing this in either Chrome or Firefox. The only thing wrong I've noticed was the little bubble arrow of the form which I fixed. I wonder why your text boxes aren't full-width. Is some other Extension or Theme active that could interfere maybe?

![](https://cloud.githubusercontent.com/assets/115237/19215070/c74dac08-8d93-11e6-812b-2f0904fa114f.png)

**Comment by jawshooah** [comment]
The shortened boxes are part of [Refined GitHub](https://github.com/sindresorhus/refined-github), but the problem appears without that extension enabled as well:

<img width="993" alt="screen shot 2016-10-08 at 3 04 41 pm" src="https://cloud.githubusercontent.com/assets/4551271/19215323/aa4d6e70-8d68-11e6-802c-254ed2667880.png">

Seems like the problem is with [GitHub Commit Limits](https://github.com/StylishThemes/GitHub-Commit-Limit).

**Comment by silverwind** [comment]
Try reinstalling from https://userstyles.org/styles/107938/github-commit-limits with `#181818` as the background color.

**Comment by jawshooah** [comment]
That worked, thanks!

**Comment by silverwind** [comment]
@Mottie we might wanna remove the background option in `github-commit-limits` and just go transparent.

**Comment by jawshooah** [comment]
Side note, any suggestion for the red foreground color that blends with the rest of GHD?

**Comment by skwerlman** [comment]
I just used a lighter gray like `#303030`

**Comment by Mottie** [comment]
@silverwind I didn't use `transparent` because the background color of the input would then show as `#222` and not the intended `#181818`.

![2016-11-06 16_20_15-editing github-dark_readme md at master stylishthemes_github-dark](https://cloud.githubusercontent.com/assets/136959/20042303/0dc5bcec-a43d-11e6-9634-e3399ef2f6c5.png)

**Comment by silverwind** [comment]
Weird, where's that `#222` coming from?

**Comment by Mottie** [comment]
The panel background behind the input.

**Comment by silverwind** [comment]
Ah, of course. Using a pseudo-element instead of the gradient would be necessary for a "proper" solution then.

**Comment by silverwind** [comment]
But of course replaced elements like `<input>` and `<textarea>` cannot contain a pseudo element, so I guess it's a hopeless case.

**Comment by Mottie** [comment]
Hmm, well actually we could set the `background-color` of the input to `#181818` because the gradient is considered an image. I'll make that update now.
