### ISSUE TITLE
Unstyled Content: Review summary form

### ISSUE THREAD

**Issue by jawshooah** [StylishThemes/GitHub-Dark#431]
### Unstyled Content

- [x] I am using the most up-to-date GitHub Dark style!
- [x] No other existing issue and/or pull request.
- [] Provide the URL of the unstyled content.
- [x] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

---

Class name: `review-summary-form-wrapper`

Steps to reproduce:
- Navigate to an open PR
- Open the "Files changed" tab
- Add a line comment and click "Start a review"
- Open the "Conversations" tab
- Scroll down to the review summary form

With [Refined GitHub](https://github.com/sindresorhus/refined-github) extension enabled:
<img width="802" alt="screen shot 2016-10-13 at 11 17 08 am" src="https://cloud.githubusercontent.com/assets/4551271/19355103/11709d44-9137-11e6-8df7-ad166e4c71df.png">

With [Refined GitHub](https://github.com/sindresorhus/refined-github) extension disabled:
<img width="793" alt="screen shot 2016-10-13 at 11 27 17 am" src="https://cloud.githubusercontent.com/assets/4551271/19355390/37782286-9138-11e6-8811-301e5ce4b61e.png">

HTML and CSS:
<img width="1162" alt="screen shot 2016-10-13 at 11 14 57 am" src="https://cloud.githubusercontent.com/assets/4551271/19355106/133941a8-9137-11e6-8b8d-62d901d2bbd0.png">

**Comment by silverwind** [comment]
You sure you're up to date? I remember fixing this form in https://github.com/StylishThemes/GitHub-Dark/commit/828e1d2de3ccc0f453205112764a9184b2c9d179.

**Comment by jawshooah** [comment]
Did you push the new tag up to userstyles.org? It's showing the last update on October 1: https://userstyles.org/styles/37035/github-dark

**Comment by silverwind** [comment]
Weird, I thought I had updated. Well, I just updated again, try that one.

**Comment by jawshooah** [comment]
That did it! :+1:
