### ISSUE TITLE
First Issue and First Pull Request images unstyled

### ISSUE THREAD

**Issue by KamranMackey** [StylishThemes/GitHub-Dark#434]
When on my profile, I noticed that the "First Issue" and "First Pull Request" images are not styled to fit with the rest of the theme. I am using the latest GitHub Dark version. I have attached images below showing the issue.

![github_dark_first_issue_image_broken](https://cloud.githubusercontent.com/assets/1617100/19415730/bb214748-9336-11e6-936e-3e3befa892dc.png)
![github_dark_first_pr_image_broken](https://cloud.githubusercontent.com/assets/1617100/19415726/a0903920-9336-11e6-945a-3b703a760d38.png)

**Comment by silverwind** [comment]
Can you possibly link to such a page showing these images? I can't seem to see them on your profile.

**Comment by skwerlman** [comment]
If you click 2012 on his profile, and 'Show more activity' a couple of times, it shows up.

**Comment by silverwind** [comment]
Thanks, I see it. Will fix that soonish.

**Comment by KamranMackey** [comment]
@silverwind I also added images to the issue itself. You should be able to see them if you view the issue on your computer.
