### ISSUE TITLE
contribution calendar no longer respects base color

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Dark#440]
### Unstyled Content

- [x] I am using the most up-to-date GitHub Dark style!

  

- [ ] No other existing issue and/or pull request.
- [ ] Provide the URL of the unstyled content.
- [x] If unable to provide a URL, please report the class name of unstyled content.

  

- [ ] Provide steps to reproduce (opening a dialog, etc).

* Reference #432
* https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L1131-L1138 

The issue is back completely only now its all yellow

![capture](https://cloud.githubusercontent.com/assets/3521959/19860301/1d7ea4d0-9f80-11e6-81a4-e4221c9f119f.PNG)

blame is still OK however, class must have changed or something.

![capture](https://cloud.githubusercontent.com/assets/3521959/19860416/855530b0-9f80-11e6-82d2-6ecbbca574ef.PNG)

**Comment by un1versal** [comment]
also I think ```.progress-bar.anim-grow-x``` should also be styled to match the base color, currently its not and has never been.

**Comment by ddavison** [comment]
keep in mind, without github dark, the contribution colors have changed due to Halloween.

**Comment by un1versal** [comment]
Im not sure weather to laugh or cry! Let me bang my head against the wall instead ;)

**Comment by silverwind** [comment]
That's working as intended. I applied some fixes last year to fix the special halloween colors and am glad the fixes still work 💀. The colors will revert to normal tomorrow.

Regarding progress bars: Also working as intended, these colors are meant to emulate traffic lights.

**Comment by un1versal** [comment]
> That's working as intended. I applied some fixes last year to fix the special halloween colors and am glad the fixes still work :skull:. The colors will revert to normal tomorrow.

If you look at unstyled vs styled, its not exactly the same, look closer.

> Regarding progress bars: Also working as intended, these colors are meant to emulate traffic lights.

mk then

**Comment by silverwind** [comment]
> If you look at unstyled vs styled, its not exactly the same, look closer.

It's specifically styled that way:

https://github.com/StylishThemes/GitHub-Dark/blob/44d5ac5228c030c45efe86359c0f1c7a8b49e125/github-dark.css#L1167-L1173
