### ISSUE TITLE
Wider scroll bar

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#441]
[Wider scrollbar](https://forum.userstyles.org/discussion/52296) request:

> Can you add an option on the install page for wider scroll bar please. Up to 35 max say, which adjusts the round corners accordingly.

Right now it's set as a max width/height of `10px`. 

@silverwind I was thinking it might be better to set it to `1em`. It won't be nearly as wide as `35px`, but it would at least adjust as the user zoom or unzooms the page.

**Comment by silverwind** [comment]
+1 to add an configuration option for them. Personally, I like my scrollbars pretty thin, but if you feel they should be wider, go ahead, it won't affect me as a Firefox user. 😉

**Comment by Mottie** [comment]
Ha ha! I'll wait to see what comments JonnyRedHed has about my questions about rounded corners and the max width setting.

**Comment by silverwind** [comment]
We could also just seperate out the scrollbars to its own style. Gives the benefit of stopping these kind of discussions and the use can modify them easily to their own need.

**Comment by un1versal** [comment]
I use this as a style.

The only problem is the way when there's a horizontal scrollbar, it covers the last line so you cant read it.
Other than that works a treat and easy to customize.

FYI I dislike round corners, that's for Apple spoiled brats,

```
/* overlay-scrollbars
 * https://github.com/silverwind/overlay-scrollbars
 * based on https://github.com/silverwind/overlay-scrollbars
 */

/* AGENT_SHEET */

scrollbar {
  -moz-appearance: none !important;
  background: none !important;
  position: relative !important;
  border: none !important;
  z-index: 999999 !important;
}

scrollbar thumb {
  -moz-appearance: none !important;
  border: none !important;
  padding: 0px 0px !important;
  background: none !important;
  border-radius: 0px !important;
}

scrollbar[orient="vertical"] thumb,
scrollbar[orient="horizontal"] thumb {
  background: #898989 !important;
  min-height: 14px !important;
  min-width: 14px !important;
  margin-top: -14px !important;
  margin-bottom: 0px !important;
  height: 14px !important
}

scrollbar[orient="vertical"] thumb:hover, scrollbar[orient="vertical"] thumb:active,
scrollbar[orient="horizontal"] thumb:hover, scrollbar[orient="horizontal"] thumb:active {
  background: #5E8ACC !important
}

scrollbar[orient="vertical"] {
  width: 14px !important;
  margin-left: -14px !important;
  margin-right: 0px !important;
  margin-bottom: 2px !important;
}

scrollbar[orient="horizontal"] {
  height: 14px !important;
  margin-top: -14px !important;
  margin-bottom: 0px !important;
}

scrollbar:not(#foo) {
  background-color: rgba(135, 135, 135, .20) !important
  }

scrollbar scrollbarbutton, scrollbar scrollcorner {
  display: none !important
}
```

**Comment by silverwind** [comment]
As state in other issue, I don't think we should style scrollbars at all, but if no one complains, I'm happy to keep the Chrome scrollbar style.

Oh, and

> I was thinking it might be better to set it to 1em. It won't be nearly as wide as 35px, but it would at least adjust as the user zoom or unzooms the page.

ems, rems, pixels and other units that run off CSS pixels should already adjust to page zoom.
