### ISSUE TITLE
[Issues Tab] Issue title font size is ridiculously big.

### ISSUE THREAD

**Issue by KamranMackey** [StylishThemes/GitHub-Dark#442]
When using the GitHub Dark theme (this also happens with GitHub's own light theme), I've noticed that the font size changed to be ridiculously big for issue titles when on the "Issues" tab itself. Doesn't happen with issue pages, but when in the Issues tab, the font size is huge. I haven't messed with my font settings at all. I have attached a screenshot showing the issue and was wondering if you guys could override GitHub's issue title font size when on the Issues tab to be smaller. Thanks.

![Issue Tab Font Issue](https://cloud.githubusercontent.com/assets/1617100/20150321/8770f886-a672-11e6-809c-b59b9fe7d810.png)

**Comment by silverwind** [comment]
Didn't see that one before, might be Chrome-specific. I'd suggest you first try reporting it to GitHub on https://github.com/contact, they are usually pretty fast on resolving these if you provice clear steps to reproduce.

**Comment by silverwind** [comment]
Oh, and by the way: Your screenshot looks pretty normal to me, I certainly can't see "ridiculous big titles".

**Comment by KamranMackey** [comment]
@silverwind The issue titles used to be a fair bit smaller. Now they are bigger and it makes the issue listings ugly imo.

**Comment by KamranMackey** [comment]
Anyway, I just contacted GitHub Support and let them know about the issue.

**Comment by silverwind** [comment]
Looks the same as always to me:

![](https://cloud.githubusercontent.com/assets/115237/20150590/f3b69c5a-a6b6-11e6-9cca-241cbdd45afd.png)

Anyways, we certainly won't touch font sizes in this theme unless absolutely necessary, and this doesn't look like such a case to me, sorry.

**Comment by KamranMackey** [comment]
Alright. Thanks though. I might as well close the issue though.
