### ISSUE TITLE
Unstyled Content: Contribution Activity Images

### ISSUE THREAD

**Issue by Spidersouris** [StylishThemes/GitHub-Dark#443]
### Unstyled Content

- [x] I am using the most up-to-date GitHub Dark style!

  

- [x] No other existing issue and/or pull request.
- [x] Provide the URL of the unstyled content.
- [x] If unable to provide a URL, please report the class name of unstyled content.

  

Example: https://github.com/Sparqey

.text-center width-fit pt-4

**Comment by Mottie** [comment]
Hi @Spidersouris!

Weird, I thought I had those inverted, and added some padding. Something must have changed while I was away.

**Comment by Spidersouris** [comment]
Hm, maybe it is an issue on my end? I updated the theme tho, but it can happens. Are the screenshots unstyled for you too?

**Comment by Mottie** [comment]
Oh, I see that it is unstyled now. I was saying I know I inverted those images in the past. Something changed... I'm not sure if it was a class name, or done purposefully. I'll see what @silverwind says because I don't want to add the style back if there was a problem.

**Comment by Spidersouris** [comment]
OK, no problem! By the way, your script is really awesome, keep up the good work 👍

**Comment by silverwind** [comment]
Looks to be a rename of classes and ids on GitHub's side. Should be fixed.
