### ISSUE TITLE
Unstyled Merge Status Items

### ISSUE THREAD

**Issue by Rockstar04** [StylishThemes/GitHub-Dark#444]
### Unstyled Content

- [X] I am using the most up-to-date GitHub Dark style!
- [X] No other existing issue and/or pull request.
- [X] Provide the URL of the unstyled content.
        https://github.com/dev-sec/chef-nginx-hardening/pull/39#issuecomment-260933420

![screenshot_2016-11-16_08-08-11](https://cloud.githubusercontent.com/assets/641721/20350419/74ace356-abd4-11e6-8f1f-5a403cfb2e1f.png)

Snippet of HTML code is in a Gist:
https://gist.github.com/Rockstar04/afdadbb735ec8d8c90bfe424f7280306

The specific class that needs attention seems to be  `.merge-status-item`

**Comment by silverwind** [comment]
I'm not seeing it. Is your style up to date? Try updating on userstyles.org.

<img width="934" alt="" src="https://cloud.githubusercontent.com/assets/115237/20353983/efc2eb42-ac1c-11e6-846b-bb4d4bdb00d7.png">

**Comment by Rockstar04** [comment]
I updated when I saw the issue, do you need to restart Chrome for the updated style to take effect? I obviously refresh the page to check if it was corrected.

**Comment by silverwind** [comment]
Should work without a restart. Try editing the style to see the version in the comment. You can also try reinstalling.

**Comment by Rockstar04** [comment]
Sorry, I updated/check for updates several times before reporting.Per your suggestion above, I copied the style manually over from github to the edit screen in Stylish, and then updated again and finally got the latest version. Everything is rendering as expected now.

**Comment by Mottie** [comment]
No worries, it's actually a Stylish for Chrome issue (I'm guessing you're using Chrome):

See https://github.com/stylish-userstyles/stylish-chrome/issues/179.

You can also check out our [GitHub Dark (user)Script](https://github.com/StylishThemes/GitHub-Dark-Script) which allows you to always get the latest update.

**Comment by Rockstar04** [comment]
I read that when I was filling out the template for the issue, and like I said, I clicked check up updated manually, it found an update and I installed it. I did that at least twice before reporting the issue.

Thanks to everyone who works on this! This is the only reason I use Stylish. Github should offer this as a native option.

**Comment by silverwind** [comment]
I assume it's a Stylish bug, but the chances getting that fixed are pretty low as the Stylish author has pretty much lost interest in further development. While the Firefox version is pretty flawless, its days are numbered too.

I'm hoping a better userstyle engine comes around soon. Maybe we should attempt to write our own :)
