### ISSUE TITLE
text-shadow and gradient to be removed

### ISSUE THREAD

**Issue by Spidersouris** [StylishThemes/GitHub-Dark#451]
### Unstyled Content

- [x] I am using the most up-to-date GitHub Dark style!
- [x] No other existing issue and/or pull request.

https://help.github.com/ - ul#bootcamp li a h4 (text-shadow: none;)

https://developer.github.com/ - .bg-custom-gradient (background-image: none;)

**Comment by Mottie** [comment]
Hi @Spidersouris!

Thanks, the problem has been fixed in the master branch.
