### ISSUE TITLE
Watched repository table is white

### ISSUE THREAD

**Issue by jucrouzet** [StylishThemes/GitHub-Dark#452]
### Unstyled Content

- [X] I am using the most up-to-date GitHub Dark style!
- [X] No other existing issue and/or pull request.
- [X] Provide the URL of the unstyled content : https://github.com/watching
- [X] ~~If unable to provide a URL,~~ please report the class name of unstyled content : ` .Box`
- [X] Provide steps to reproduce : Go to https://github.com/watching while logged in an account with watched repos

**Comment by jucrouzet** [comment]
![virtualbox_2016-12-28_08-55-50](https://cloud.githubusercontent.com/assets/471070/21517084/4d7f6ea6-ccdc-11e6-8025-a78d127e1ddb.png)

**Comment by Mottie** [comment]
Hi @jucrouzet!

I am not seeing the problem in the screen shot. Please make sure you are using v1.16.16.

**Comment by jucrouzet** [comment]
Yup, you were right, it turned out to be a Stylish/Chrome Extension problem (https://github.com/stylish-userstyles/stylish-chrome/issues/188) that blocked the update.
I removed the style, re-added it and it works.

My bad.

**Comment by Mottie** [comment]
No worries! It's a common problem.

You shouldn't need to completely remove the style, just manually update it from [userstyles](http://userstyles.org/styles/37035).
