### ISSUE TITLE
tick not visible in "new repository" page

### ISSUE THREAD

**Issue by franklinyu** [StylishThemes/GitHub-Dark#456]
### Unstyled Content

- [x] I am using the most up-to-date GitHub Dark style!
- [x] No other existing issue and/or pull request.
- [x] the URL of the unstyled content: <https://github.com/new>, with selector `#repository_name`

### steps to reproduce

1. go to the page
2. enter something
3. there should be a tick as the background of the textbox for good names, or a warning sign when there is an error (like duplicate name); instead I see nothing in the right of the textbox.

**Comment by franklinyu** [comment]
In addition, `.owner-reponame .warning` is too transparent; the text in warning box is mixed with the underlying text. `.owner-reponame .error` works very well, in contrast.

**Comment by Mottie** [comment]
Hi @franklinyu!

Thanks for letting us know! I'll have the fix available in the master branch... we'll update userstyles sometime soon.
