### ISSUE TITLE
StylishThemes Extension

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#458]
I am going to start working on a browser extension/addon as a replacement for Stylish; but it'll only be for StylishThemes styles

This could take me some time, since my list of ideas seems to be getting longer and longer!

* Make it easy to toggle the style.
* Auto-update style directly from GitHub. Or a custom URL, so that we can support forks?
* Customization of specific placeholders for each of the different styles.
* Allow loading a custom font from an external source (Google fonts?).
* Submit issue directly from the extension/addon?
  * Add to contextmenu, so the user can right-click to submit?
  * Include screenshot (as an option). Allow user to frame it?
  * Include HTML of the clicked on item (as an option).
* Iframe support, since some rendered pages load in an iframe (svg, jupyter pages, etc).
* Editor? It would be easier to include a textarea to only copy-paste styles into, but maybe having an actual editor would be better?
* Make it easy to add support for any new StylishThemes.
* Support browsers:
  * Chrome
  * Firefox
  * Opera
  * Safari - I'll need to get help with converting the extension to work in Safari since I don't own any Apple devices.
  * Other?
* Support GitHub enterprise sites? I'm not sure how to do this yet as I don't know which URLs will need to be included... e.g. do you use `https://github.mysite.com` or `https://mysite.com/github/`, and what about subdomains?
* ✨ Add a "tweak" section allowing your own custom css which gets tacked to the end of the style.
* ✨ Allow setting syntax themes for GitHub (in general), Jupyter & codemirror separately.
* ✨ Figure out a way to sanitize css... [this module](https://github.com/jsonmaur/xss-clean/blob/master/src/xss.js) uses JSON stringify and parse, is that adequate?

<img title=":_ chemist :" src="https://cloud.githubusercontent.com/assets/136959/13512302/638bd0c2-e15f-11e5-9d10-9c8dfeeb138c.gif">

**Comment by silverwind** [comment]
I was toying with the idea of writing a userstyle addon to, but my vision would be a bit different:

- full stylish replacement that supports loading and updating from a url (and possibly userstyles.org), with a configurable update interval.
- load styles from a directory containing CSS files, no built-in editor. Put a filesystem watch (if possible) on all active styles and reload when changed.
- support a userscript-esque comment header in styles to declare included sites, options, and possibly URLs for other CSS files to be included before the current style.
- no support for userstyle customization comments, at least not in the way they currently work. This will make the styles fully contained and portable in a single file.

I don't really have the time and motivation to do this right now, but that's how I would do it :)

**Comment by Mottie** [comment]
I think the problem we're having with the GitHub-Dark userscript in Chrome is that there is a lag time between the extension determining which userscripts to run and running them. You won't see this problem if you only have a few userscripts running, but when you have a bunch (more than 10 maybe?) scripts running, this delay leads to the flash of white.

That's why I'm leaning towards making an extension.

**Comment by narcolepticinsomniac** [comment]
A fork of the previous version of Stylish with all analytics removed and a compatible backup feature [here](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne).

**Comment by Mottie** [comment]
Hmm, I guess I can stop working on the custom StylishThemes extension then <img title=":_ whew :" src="https://cloud.githubusercontent.com/assets/136959/13512600/44bfd830-e161-11e5-94d7-6c4fab078980.gif">.

I'm going on vacation next week anyway! I'll be gone for 3 weeks.
