### ISSUE TITLE
Search box no longer has a border when unfocused

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#460]
### Unstyled Content

- [x] I am using the most up-to-date GitHub Dark style!
- [x] No other existing issue and/or pull request.
- [x] Provide the URL of the unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

### Feature Request
The search box in the top nav no longer has a border when it's unfocused. The issue happens on all pages including the repo search box on this page.

![image](https://cloud.githubusercontent.com/assets/831974/22846751/08b37b8e-efb7-11e6-9bee-597dcb44582f.png)

![image](https://cloud.githubusercontent.com/assets/831974/22846759/175765f6-efb7-11e6-8fbe-b45d4065a3e0.png)

**Comment by Mottie** [comment]
Hi @xt0rted!

Thanks for letting us know!... Oh, GitHub switched to using a dark header. Is this the first signs of a dark theme?

**Comment by xt0rted** [comment]
We'll get an official dark theme once GitLab adds one 😜

**Comment by KamranMackey** [comment]
@Mottie Nah, it's probably just so that way the consumer version of GitHub is more alike to its Enterprise counterpart, which also has a dark header.

**Comment by xt0rted** [comment]
@Mottie maybe there is hope after all https://twitter.com/mdo/status/830151588698218496

**Comment by Mottie** [comment]
Oh, this may put us out of a job! 😜
<img title=":_badger:" src="https://cloud.githubusercontent.com/assets/136959/13512240/15d31412-e15f-11e5-8577-06cff0976977.gif">

**Comment by silverwind** [comment]
>  this may put us out of a job

I'm pretty sure that we'll never be satisfied with whatever theme the might create 🤣
