### ISSUE TITLE
Inverted emojis

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#461]
I was working on the [Emoji wiki page](https://github.com/StylishThemes/GitHub-Dark/wiki/Emoji) after I discovered one was broken and a few were missing - see https://github.com/WebpageFX/emoji-cheat-sheet.com/issues/429.

Anyway, I noticed that a few emojis looked weird 

:loop: `:loop:` :curly_loop: `:curly_loop:`

Now look at how they render on the wiki page:

![2017-02-11 08_21_10-editing emoji stylishthemes_github-dark wiki](https://cloud.githubusercontent.com/assets/136959/22854383/207a7d36-f033-11e6-9495-bd92161a72d3.png)

Fun, GitHub renders them differently!

I don't know if there is a difference on Macs or Linux, so I didn't want to make these inverted emoji selectors only target wiki pages until we get some more information.

**Comment by Mottie** [comment]
Hmm... 

:feet: `:feet:` :paw_prints: `:paw_prints:`

![2017-02-11 08_21_19-editing emoji stylishthemes_github-dark wiki](https://cloud.githubusercontent.com/assets/136959/22854388/35d71d60-f033-11e6-9c4b-a787f6123cd5.png)

**Comment by xt0rted** [comment]
Awhile back GitHub started replacing the emoji images with native emojis. On the wiki page you're seeing all images while in the issue you're seeing them replaced with what you're browser & os support.

If you view source you can see the emojis use custom tags now and some JS to determine which version to show.

**Issue**
```html
<g-emoji alias="curly_loop" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/27b0.png" ios-version="6.0">➰</g-emoji>
```

**Wiki**
```html
<img class="emoji" title=":curly_loop:" alt=":curly_loop:" src="https://camo.githubusercontent.com/280f7461532a3cdc353c6beeb52832676577ee5e/68747470733a2f2f6173736574732d63646e2e6769746875622e636f6d2f696d616765732f69636f6e732f656d6f6a692f756e69636f64652f323762302e706e67" height="20" width="20" align="absmiddle" data-canonical-src="https://assets-cdn.github.com/images/icons/emoji/unicode/27b0.png">
```

I'm on one of the newer preview builds of Win10 which has more emoji support and a version of Edge which uses the [colored versions](https://twitter.com/MSEdgeDev/status/821436421160333312). So for me `:curly_loop:` looks different in this issue between Edge & Chrome.

**Comment by silverwind** [comment]
Here's the deal:

- Old Windows with bad Emoji support gets the fallback images. Can be targeted with `g-emoji[fallback-src]`
- New Windows uses unicode glyphs, apparently now colored in the latest version. Not sure how to handle them, but if they are colored already, that's fine I guess.
- Mac uses the Apple Color Emoji unicode font. We invert all glyphs except a few problematic ones which are exclude with CSS `unicode-range`.

To handle all cases:

- Add the placeholder namer to both the `[alt]` and `[alias]` sections and then append the unicode glyph in [`tools/unicode-gen.js`](https://github.com/StylishThemes/GitHub-Dark/blob/master/tools/unicode-gen.js).
- Run the script and copy the output to the `g-emoji` section so the fallback images get inverted too. 

I'll add those two you mentioned above.

**Comment by silverwind** [comment]
Even still, there's the issue with those emoji in code, at least on macOS:

https://github.com/StylishThemes/GitHub-Dark/blob/master/tools/unicode-gen.js

<img width="457" alt="screen shot 2017-02-12 at 10 38 04" src="https://cloud.githubusercontent.com/assets/115237/22861051/6859d782-f10f-11e6-8c33-ae32b5486eac.png">
<img width="307" alt="screen shot 2017-02-12 at 10 38 58" src="https://cloud.githubusercontent.com/assets/115237/22861057/7c3e8db0-f10f-11e6-96e1-48987da9ca91.png">

Short of creating our own no-color font glyphs (a woff font could be loaded with a data-uri), I'm out of ideas on how to handle those.

**Comment by Mottie** [comment]
It looks like this might be resolved now... I'm seeing images in place of unicode emojis. Do you think we can close this one @silverwind?

**Comment by silverwind** [comment]
Might as well.
