### ISSUE TITLE
Toolbar is missing in pull request diffs.

### ISSUE THREAD

**Issue by nvladimiroff** [StylishThemes/GitHub-Dark#464]
When viewing the changes in a pull request, the toolbar that's usually at the top is missing, except for a phantom drop shadow. The class for this div is `pr-toolbar`.

URL: https://github.com/StylishThemes/GitHub-Dark/pull/426/files
![missingbar](https://cloud.githubusercontent.com/assets/4212385/23365589/95fa74ee-fcd1-11e6-8897-fc53e8eb7bd7.PNG)
![bar](https://cloud.githubusercontent.com/assets/4212385/23365599/99ea4ca0-fcd1-11e6-9136-e1af765bb698.png)

**Comment by silverwind** [comment]
This was actually a intentional change from me because I found it a waste of vertical space. I guess a point could be made about having the Review button always available.

I'll think about it. Maybe I'll bring it back at reduced height.
