### ISSUE TITLE
Contributions graph styling recently stopped working

### ISSUE THREAD

**Issue by elderapo** [StylishThemes/GitHub-Dark#465]
### Unstyled Content

- [x] I am using the most up-to-date GitHub Dark style!
- [x] No other existing issue and/or pull request.
- [x] Provide the URL of the unstyled content.

### Feature Request
Looks like contributions graph stying doesn't work anymore. To reproduce just go to any user profil. Example: https://github.com/elderapo

![image](https://cloud.githubusercontent.com/assets/10766808/23492989/9e67f46a-ff08-11e6-97b6-869c75e7a2fc.png)

**Comment by BrainArchitect** [comment]
Same for me, it appears that some kind of update pushed in the Github site made the add-on break.

**Comment by silverwind** [comment]
Github made some adjustments to the color scheme in the calendar which broke our selectors. Fixed in v1.17.4.
