### ISSUE TITLE
Recently pushed branches section is not able to read.

### ISSUE THREAD

**Issue by gluons** [StylishThemes/GitHub-Dark#466]
It can only see branch name.

![your recently pushed branches](https://cloud.githubusercontent.com/assets/4688092/23537961/2980dbf8-0002-11e7-82c7-034b75ad7fc4.png)

![your recently pushed branches 2](https://cloud.githubusercontent.com/assets/4688092/23537978/4cf8db8a-0002-11e7-84ab-1359f90e0463.png)

### Unstyled Content

- [x] I am using the most up-to-date GitHub Dark style!

  

- [x] No other existing issue and/or pull request.
- [ ] Provide the URL of the unstyled content.
- [x] If unable to provide a URL, please report the class name of unstyled content.
  ```
  .RecentBranches .css-truncate
  ```

  

- [x] Provide steps to reproduce (opening a dialog, etc).
   - Push some commit to your non-default branch and see at `Your recently pushed branches:` section.

**Comment by silverwind** [comment]
Thanks, fixed in v1.17.5.

<img width="387" src="https://cloud.githubusercontent.com/assets/115237/23555543/a1f2568a-0029-11e7-97b4-c7b4b7fcd249.png">
