### ISSUE TITLE
Issue popup menus break the layout instead of floating

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#474]
### Unstyled Content

- [x] I am using the most up-to-date GitHub Dark style!
- [x] No other existing issue and/or pull request.
- [ ] Provide the URL of the unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

The popup menus on issues & prs is pushing the layout to the right instead of floating over it.

![image](https://cloud.githubusercontent.com/assets/831974/24337690/9d762dce-126d-11e7-9a07-a83703e734a6.png)

**Comment by Mottie** [comment]
Hi @xt0rted!

I am not able to reproduce this issue. What OS/browser combo does this occur in. Is this also a problem with the userstyle disabled? Do you know of a solution, or can you provide a fix?

**Comment by xt0rted** [comment]
Win10 build 15063 and the latest version of chrome. It was happening consistently for me so I'll take a look tomorrow.

**Comment by xt0rted** [comment]
Some more info on this one. If the page doesn't scroll (vertical or horizontal) then the page doesn't blow out to the right. If you make your browser just narrow enough that the page will scroll you'll see the menu shift to the right.

What I've found is the `position: sticky` rule at [github-dark.css#L590](https://github.com/StylishThemes/GitHub-Dark/blob/c687bdb418b274c9278da00ddb977ef9f0c54860/github-dark.css#L590) is the cause of the layout change. When I turn that rule off the menu moves back to the left and looks as it should.

**Comment by xt0rted** [comment]
56.0.2924.87 - can repro
57.0.2987.110 - can't repro

Guess it was a chrome bug?
