### ISSUE TITLE
Projects popup tabs are unstyled

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#475]
### Unstyled Content

- [x] I am using the most up-to-date GitHub Dark style!
- [x] No other existing issue and/or pull request.
- [ ] Provide the URL of the unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

The tabs in the projects popup on issues & prs are unstyled.

![image](https://cloud.githubusercontent.com/assets/831974/24337710/c4d1281a-126d-11e7-9a70-0fe81c47e405.png)

**Comment by Mottie** [comment]
Hi @xt0rted!

Confirmed. Thanks for reporting!

**Comment by Mottie** [comment]
Testing

 - [ ] item 1
 - [ ] item 2
