### ISSUE TITLE
PR toolbar flashes and freezes the page when scrolling fast

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#476]
### Unstyled Content

- [x] I am using the most up-to-date GitHub Dark style!
- [x] No other existing issue and/or pull request.
- [ ] Provide the URL of the unstyled content.
- [ ] If unable to provide a URL, please report the class name of unstyled content.
- [x] Provide steps to reproduce (opening a dialog, etc).

The sticky menu on the PR review page freezes the page sometimes when scrolling fast. I can't repro without GitHub-Dark but I'm not sure why this would be causing it. In the image the flashing is 2-3x slower than how it actually happens.

![github-dark pr menu](https://cloud.githubusercontent.com/assets/831974/24338235/c44bc68a-1271-11e7-9254-5544b5727f79.gif)

**Comment by Mottie** [comment]
Hi @xt0rted!

I am not able to reproduce this issue. What OS/browser combo does this occur in? Do you know of a solution, or can you provide a fix?

**Comment by xt0rted** [comment]
Win10 build 15063 and the latest version of chrome. I was in the middle of reviewing PRs and didn't have time to look into it, just wanted to log it since it kept happening. I'll try to dig into this some more tomorrow.

**Comment by xt0rted** [comment]
56.0.2924.87 - can repro
57.0.2987.110 - can't repro

Guess it was a chrome bug like #474?

**Comment by silverwind** [comment]
Certainly sounds like a Chrome bug. The PR toolbar styling is a bit more involved on our side (it's not just a recolor), maybe some combination of our styles and their JS trigger this bug. If you can consistently reproduce, it'd be interesting if toggling certain styles on the element or the `:after` pseudo of it change anything about the flickering.

**Comment by NiXXeD** [comment]
For me it's easy and consistent to reproduce (and all of my coworkers), but not by scrolling fast. I'm on Chrome 57.x OSX.

It has to do with the point where the popover happens, if you scroll really slowly, right when it transitions to popover, stop scrolling and it will jitter like this.

**Comment by Mottie** [comment]
Oh, now that I tried scrolling really slowly, I am able to reproduce this issue.

![dev](https://cloud.githubusercontent.com/assets/136959/24808891/4ed1fb84-1b83-11e7-8b43-b2602126d3a7.gif)

It looks like the "is-stuck" class is being added and removed in a loop. I found that removing the set height of the stuck toolbar fixes the problem.

**Comment by silverwind** [comment]
Maybe just remove the `.is-stuck` and keep the 40px height? Now the `.pr-toolbar` is still 60px high, overlapping the content by 20px:

<img width="633" alt="screen shot 2017-04-07 at 18 43 09" src="https://cloud.githubusercontent.com/assets/115237/24810306/3f68dea8-1bc2-11e7-93b4-80350f8c9474.png">

**Comment by Mottie** [comment]
It's overlapping but not hiding the content... does that overlap cause problems other than trying to select content?

**Comment by silverwind** [comment]
Just a minor inconvenience of not being able to click stuff underneath. Does it still flicker at 40px?

**Comment by Mottie** [comment]
Setting it to `40px` was causing the flicker. I didn't try other sizes.

**Comment by Mottie** [comment]
Ok, this last update should take care of the issue.

**Comment by silverwind** [comment]
How weird that that helps, must be some JS which is assuming 60 height or something. Thanks for looking into it.
