### ISSUE TITLE
Bright items in GitHub repo branch menu

### ISSUE THREAD

**Issue by mewmew** [StylishThemes/GitHub-Dark#477]
### Unstyled Content

- [x] The issue only occurs when the GitHub-Dark style is enabled.
- [x] I am using the most up-to-date GitHub-Dark style!

  

- [x] No other existing issue and/or pull request was found.
- [x] Please provide steps to reproduce this issue (opening a dialog, etc).

Click on branch menu in a repository. Should look something along the lines of the provided screenshot.

![Bright items in repo branch menu](https://image.ibb.co/fQBmBF/github_dark_with_bright_menu.png)

- [x] This issue occurs in the following OS/browser combinations:

Arch Linux, Firefox

  

- [x] Please provide the URL of the unstyled content, if not obvious.

Any repo on github.

- [x] If unable to provide a URL, please report the class name of unstyled content.

**Comment by Mottie** [comment]
Hi @mewmew!

This was just fixed in https://github.com/StylishThemes/GitHub-Dark/commit/79213e6025e0ff4ef0d2feba47e6800cc1ca0b4b

I'll update userstyle.org in a few minutes.

**Comment by Mottie** [comment]
LOL Derp... @silverwind, I used "minor" instead of "patch" on this last update. Oh well.

**Comment by mewmew** [comment]
Oh wow, lovely! Thanks a lot @Mottie!

**Comment by Mottie** [comment]
Not a problem! 😸
