### ISSUE TITLE
Editor line numbers unstyled

### ISSUE THREAD

**Issue by james0x0A** [StylishThemes/GitHub-Dark#479]
Line numbers are unstyled in the editor for normal repositories and gist
https://gist.github.com/

**Comment by james0x0A** [comment]
CodeMirror-lines may have been renamed CodeMirror-linenumbers

**Comment by Mottie** [comment]
Hi @james0x0A!

Maybe I'm not seeing the update yet, but I still see "CodeMirror-lines" and no "CodeMirror-linenumbers". And the line numbers are still dark for me.

Are you seeing this issue with a specific theme, or all themes?

**Comment by james0x0A** [comment]
This issue seems to have resolved itself.    Probably a stale cache. Sorry for the inconvenience.
