### ISSUE TITLE
Unstyled - two issues

### ISSUE THREAD

**Issue by simov** [StylishThemes/GitHub-Dark#480]
:wave: 

Latest master here:

1. https://github.com/organizations/[YOUR_ORG]/settings/oauth_application_policy

The approved OAuth apps list:

![approved-apps](https://cloud.githubusercontent.com/assets/1694112/24894415/e23bbf7e-1e92-11e7-84ce-2fb666624e33.png)

2. https://github.com/orgs/[YOUR_ORG]/teams/[YOUR_TEAM]

Visible only when you have pending invitations for that team:

![pending-invitations](https://cloud.githubusercontent.com/assets/1694112/24894528/a05cf02c-1e93-11e7-839b-81862382ac75.png)

I can test with latest master once you push. Thanks!

**Comment by Mottie** [comment]
Hi @simov!

Thanks for letting us know! I'll have it fixed shortly.

**Comment by simov** [comment]
Еverything looks good now :sparkles: 
Thanks!
