### ISSUE TITLE
[Addon] Github User Info

### ISSUE THREAD

**Issue by Bluscream** [StylishThemes/GitHub-Dark#481]
https://github.com/jerone/UserScripts/tree/master/Github_User_Info <- has a own readme with screenshots etc.

**Comment by Mottie** [comment]
Hi @Bluscream!

Easy peezy... <img title=":_excite:" src="https://cloud.githubusercontent.com/assets/136959/13559383/49d88766-e3d9-11e5-9c0c-9a958bfc03ee.gif">

**Comment by Bluscream** [comment]
Pawsome ! :3
