### ISSUE TITLE
Bad style (height) for topic detail

### ISSUE THREAD

**Issue by AmirSavand** [StylishThemes/GitHub-Dark#482]
### Screenshot
![image](https://cloud.githubusercontent.com/assets/4629328/25074941/01787ab4-2319-11e7-8a72-dd460869a7a7.png)

### Where
Look at the tags/topics [here](https://github.com/search?q=topic%3Aangularjs+org%3ASavandBros&type=Repositories)

**Comment by Mottie** [comment]
Hi @AmirSavand!

Thanks for letting us know... it looks like the unstyled topic tags don't include a border, so when we add a border, it throws off the styling a bit.
