### ISSUE TITLE
Latest update is bugged

### ISSUE THREAD

**Issue by narcolepticinsomniac** [StylishThemes/GitHub-Dark#483]
A lot of redundant/broken code.

Repeated hex values, background image broken (missing comma and background-attachment issue), lots of empty rules. I get the feeling someone copypasta'd the wrong revision of the code to USO.

**Comment by Mottie** [comment]
Hi @narcolepticinsomniac!

Sorry about that... all fixed now!

**Comment by narcolepticinsomniac** [comment]
Thanks! Disabling it was a harsh reality. You guys make this place look good.

**Comment by silverwind** [comment]
Looks like I pasted the wrong file on userstyles (github-dark.css instead of github-dark-userstyle.build.css). I'll automate the publishing so that won't happen again soon.
