### ISSUE TITLE
Background missing in latest update

### ISSUE THREAD

**Issue by skwerlman** [StylishThemes/GitHub-Dark#484]
### Unstyled Content

- [x] The issue only occurs when the GitHub-Dark style is enabled.
- [x] I am using the most up-to-date GitHub-Dark style!
- [x] No other existing issue and/or pull request was found.

The background image no longer appears for me anywhere on Github; instead I have a flat grey background.

**Comment by Mottie** [comment]
Hi @skwerlman!

Sorry about that... all fixed now!
