### ISSUE TITLE
"Private" text for repos is no longer bordered

### ISSUE THREAD

**Issue by Technoblazed** [StylishThemes/GitHub-Dark#485]
### Unstyled Content

- [x] The issue only occurs when the GitHub-Dark style is enabled.
- [x] I am using the most up-to-date GitHub-Dark style!
- [x] No other existing issue and/or pull request was found.
- [x] Please provide steps to reproduce this issue (opening a dialog, etc).

Open up a private Github repo, the "Private" text to the right of the repo name no longer has a yellow border: ![Image of Private Repo](https://i.tech-no.me/200417204848.png)

- [x] This issue occurs in the following OS/browser combinations:

Latest Chrome

- [x] If unable to provide a URL, please report the class name of unstyled content.

`<span class="Label Label--outline v-align-middle">Private</span>`

**Comment by silverwind** [comment]
Looks like GitHub had a fit of uppercasing various classes. `.State` (The tag color on issues) is also affected.

**Comment by silverwind** [comment]
Can you show a screenshot how it looks with the style disabled? When I add that HTML to a page, I get a faint grey border, so not sure where your yellow is coming from.

**Comment by Technoblazed** [comment]
There's the grey border without it, but I could've sworn that yesterday, there was a yellowy/orange border around the Private, unless that's been removed since  the last time I updated?

**Comment by Mottie** [comment]
I think private and secret (`.gist-secret-label`) use the same color definition.

**Comment by silverwind** [comment]
Not anymore it seems. I'll invert the border and make it slightly brighter from that color.

**Comment by Technoblazed** [comment]
Thanks beautiful <3
