### ISSUE TITLE
Private issue/pr reference icon isn't visible

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#489]
### Unstyled Content

- [x] The issue only occurs when the GitHub-Dark style is enabled.
- [x] I am using the most up-to-date GitHub-Dark style!
- [x] No other existing issue and/or pull request was found.
- [x] Please provide steps to reproduce this issue (opening a dialog, etc).
- [x] This issue occurs in the following OS/browser combinations:
- [ ] Please provide the URL of the unstyled content, if not obvious.
- [x] If unable to provide a URL, please report the class name of unstyled content.

Win10: Chrome 58

When you link to a public issue/pr from a private issue the reference that shows in the public issue has a lock icon next to the status label. This is styled in such a way that it's not visible anymore.

![image](https://cloud.githubusercontent.com/assets/831974/25822401/8905c11e-3406-11e7-9064-b34b553e6697.png)
![image](https://cloud.githubusercontent.com/assets/831974/25822427/9567a986-3406-11e7-8e12-b7d782a1e464.png)

The class of the icon is `.discussion-item-private` which is for the surrounding `span`.

**Comment by Mottie** [comment]
Hi @xt0rted!

Thanks for letting us know! Since I don't have any private repos, would a simple inversion of the icon work in this case?

```css
.discussion-item-private {
  -webkit-filter: invert(100%) !important;
          filter: invert(100%) !important;
}
```

**Comment by xt0rted** [comment]
Added that to the end of the stylesheet and it looks to have worked.

![image](https://cloud.githubusercontent.com/assets/831974/25835697/e4e2c67e-344e-11e7-96b7-e2bf324db4a2.png)

**Comment by xt0rted** [comment]
The style I'm seeing applied to this class from GitHub is `color: rgba(27,31,35,0.7);`, when I turn that off the icon shows correctly. Even setting it to `color: inherit;` works. For whatever reason when it's `rgba()` the icon goes invisible.

**Comment by Mottie** [comment]
Let me know if that fixed it 😸

**Comment by xt0rted** [comment]
It sure did!

**Comment by xt0rted** [comment]
@Mottie I was just working on a PR and noticed the info icon that shows when a commit or pr will auto close the linked issue is styled with `#7b7b7b` and comes from the class `a.discussion-item-help`. Should the lock icon be updated to use that instead of `#c0c0c0`?

The lock icon isn't a link while the info icon is (it goes to https://help.github.com/articles/closing-issues-via-commit-messages/).

![image](https://cloud.githubusercontent.com/assets/831974/25837913/363e7c66-345e-11e7-9814-5723d42ca769.png)

**Comment by Mottie** [comment]
Hmm, yeah `#7b7b7b` does look like it might be a better color... what do you think @silverwind?

**Comment by silverwind** [comment]
Got a example where it appears? I'm fine if it's a inversion of GitHub's color, or close to.
