### ISSUE TITLE
Pending review label text is hard to read

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#490]
### Unstyled Content

- [x] The issue only occurs when the GitHub-Dark style is enabled.
- [x] I am using the most up-to-date GitHub-Dark style!
- [x] No other existing issue and/or pull request was found.
- [x] Please provide steps to reproduce this issue (opening a dialog, etc).
- [x] This issue occurs in the following OS/browser combinations: Win10 Chrome 58
- [ ] Please provide the URL of the unstyled content, if not obvious.
- [x] If unable to provide a URL, please report the class name of unstyled content.

When starting a review the pending label shows as a light yellow with grey text which is hard to read. The full list of classes on the label is
`timeline-comment-label Label--outline bg-yellow-light is-pending position-relative`

![image](https://cloud.githubusercontent.com/assets/831974/25915241/e3d072e0-358e-11e7-8d49-b272b84dc865.png)

**Comment by Mottie** [comment]
Hi @xt0rted!

Thanks for reporting this problem. I'm not sure how to test the change, so thank you for sharing the class names.

@silverwind, I think we can target `.bg-yellow-light` and have it match the brown colors. What do you think? Is it something that can be done with the build you're setting up?

**Comment by xt0rted** [comment]
If you create a PR and then leave a comment on one of the lines you'll be asked if you want to start a review or just leave a single comment. Select start a review and the comment will show with the pending label until you finalize it.

**Comment by silverwind** [comment]
Fixed by https://github.com/StylishThemes/GitHub-Dark/commit/fd5a0e76810a715a32f56c26b7a1f2587d264ac8. I updated the script to ignore `!important` source rules like for the case with this one.
