### ISSUE TITLE
shelf-title missing styling

### ISSUE THREAD

**Issue by DJScias** [StylishThemes/GitHub-Dark#492]
### Unstyled Content

- [x] The issue only occurs when the GitHub-Dark style is enabled.
- [x] I am using the most up-to-date GitHub-Dark style!

  

- [x] No other existing issue and/or pull request was found.
- [x] Please provide steps to reproduce this issue (opening a dialog, etc).
Go to https://github.com/ and have the "Learn Git and Github without any code!" popup.
- [x] This issue occurs in the following OS/browser combinations:
Windows 10 Pro x64, Chrome
  

- [x] Please provide the URL of the unstyled content, if not obvious.
https://github.com/
- [ ] If unable to provide a URL, please report the class name of unstyled content.

  

### Feature Request
The class `shelf-title` has no styling for the dark theme and is barely readable (or not at all).

How it looks like now:
![image](https://cloud.githubusercontent.com/assets/439655/26026789/86437142-3802-11e7-8836-98ed1ff98857.png)
Something's actually there, selected it.
![image](https://cloud.githubusercontent.com/assets/439655/26026791/8aea844c-3802-11e7-88c1-e7ec75489dc9.png)

Fixed this locally by giving it a `color: #ddd !important` and it came out to be this:
![image](https://cloud.githubusercontent.com/assets/439655/26026812/d519816c-3802-11e7-983a-ca3327ab2d0c.png)

Feel free to give it any color you guys feel is right though, just here to report it.

**Comment by Mottie** [comment]
Hi @DJScias!

Thanks for letting us know! I'll set the color to `#c0c0c0` to go along with our current palette. Let us know if that works for you.

**Comment by silverwind** [comment]
Hmm I don't see a color on `.shelf-title` in GitHub's CSS. Could it be that the color is set on a parent, maybe this one?

````css
.intro-shelf {
 color:rgba(27,31,35,0.85);
}
````

Anyone got the HTML of that popup?

**Comment by Mottie** [comment]
I couldn't find it.

**Comment by DJScias** [comment]
Hello there @Mottie,

I'm not sure if there's been any changes to it as I don't see them (I checked for updates on the style theme).

It's still showing me the following in the console:
![image](https://cloud.githubusercontent.com/assets/439655/26028635/0f356024-3825-11e7-838d-aab44284bc19.png)

**Comment by Mottie** [comment]
I just changed the selector to use `.intro-shelf`. The update was only applied to the master branch of this repo. We have yet to update userstyle.org. I'll see what @silverwind says about the update because I have not yet familiarized myself with the auto-generated build script.

**Comment by silverwind** [comment]
Added a generator rule here:

https://github.com/StylishThemes/GitHub-Dark/commit/fd04c718248b49d462a2bece29eff10722f26b26

It's pretty simple, you add a new property to the `mappings` object, the key is the declaration as it is in GitHub's stylesheet, the value is the replacement declaration. After that is added, run `node tools/generate.js` and copy the output into `github-dark.css`, replacing the old block.
