### ISSUE TITLE
Github MarketPlace

### ISSUE THREAD

**Issue by Johann-S** [StylishThemes/GitHub-Dark#495]
With this new pages this class `.MarketplaceSideNav` isn't styled by Github-Dark
See : https://github.com/marketplace

**Comment by Mottie** [comment]
Hi @Johann-S!

Thanks for letting us know! I'll have it fixed in the master branch shortly.

**Comment by silverwind** [comment]
And I fixed the other stuff on that site :)

**Comment by Mottie** [comment]
hehe thanks!

**Comment by Johann-S** [comment]
thank you very much for you awesome theme 👍

**Comment by silverwind** [comment]
Thank you too for Bootstrap v4 😉
