### ISSUE TITLE
Highlighted code is difficult to read

### ISSUE THREAD

**Issue by cipri-tom** [StylishThemes/GitHub-Dark#502]
* **Browser**: Firefox
* **Operating System**: Linux Mint 17.3 (Based on Ubuntu 14.04)
* **Screenshot**: 
![screenshot from 2017-06-13 15 03 41](https://user-images.githubusercontent.com/2991890/27083649-8625e992-5049-11e7-9050-5d6b5cc722b5.png)

* **HTML of the section where the issue occurs**:

````html
<td id="LC117" class="blob-code blob-code-inner js-file-line" style="background-color: rgb(255, 251, 221);">                
````

Hmm, seems impossible to fix, since some JS adds the style inline :( .

**Comment by silverwind** [comment]
> Hmm, seems impossible to fix, since some JS adds the style inline :( .

Easy, we just select the lines based on the inline style. Quite fragile to break but works.

**Comment by cipri-tom** [comment]
Awesome ! Thank you !

Mind if we set it to something just a tad bit more striking ? For example a bit of yellow would look nice:
![screenshot from 2017-06-13 21 01 26](https://user-images.githubusercontent.com/2991890/27099533-8fbeddba-507b-11e7-8876-51184f2f25ea.png)

This is `rgba(255, 243, 155, .3)` but I'm sure you know a better combination to go with this nice dark background.

**Comment by Mottie** [comment]
The color would depend on the selected syntax highlighter. I don't think that color would go very well with solarized dark.

Maybe we should consider including the hover highlighting style in with the syntax theme instead of outside of it?

**Comment by silverwind** [comment]
> Maybe we should consider including the hover highlighting style in with the syntax theme instead of outside of it?

I'd keep it a shade of gray because it's neutral and will work on all background colors and also will most likely not clash with syntax themes, but I agree it could be a shade brighter.

**Comment by silverwind** [comment]
.35 alpha over .3 alpha seems to give the contrast it needs on my screen.

**Comment by silverwind** [comment]
Went with 0.4, I think that's fine:

<img width="401" src="https://user-images.githubusercontent.com/115237/27100700-3b26aa90-507f-11e7-9509-fa09599f3526.png">
