### ISSUE TITLE
Background image not applying

### ISSUE THREAD

**Issue by VladimirDev93** [StylishThemes/GitHub-Dark#503]
Hey, 

I'm using your style since... ever 😸 , but now that I've installed "Stylus" extension instead of "Stylish" (It gone broken... again, can't install anything), on advance setup of your style, when I click on "Original image" under the "Background image", I don't get the straight little cubes background, but the one that is rotated (Default).

Can you check that out, please?

**Comment by silverwind** [comment]
The default background was changed a long time ago, but you should be able to get it back by downloading https://github.com/StylishThemes/GitHub-Dark/raw/master/images/backgrounds/bg-tile1.png and reinstalling the style with that selected from userstyles.org.

**Comment by Mottie** [comment]
Hi @VladimirDev93!

I just tried it out and it's working for me... I'm seeing the original (non-rotated) blocks as a background image.

What browser are you using?

**Comment by VladimirDev93** [comment]
Chromium, `Version 58.0.3029.110 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)`
with `Stylus`, not `Stylish` extension.

**Comment by Mottie** [comment]
Try reloading the userstyles.org page and selecting "original" again. If that still doesn't work, then use the URL silverwind provided and add that as a custom background image. And if that *still* doesn't work, edit the "GitHub-Dark" style and look to see what the background image is being set as... then share it with us.

**Comment by VladimirDev93** [comment]
It works when I copy and paste the link locally in the style (Edit the style) that silverwind gave me. 

When I think about it, maybe the extension isn't compatible with the Chromium browser, because I've installed one your other style, "Stackoverflow dark" and it still behaves the same. Maybe it's Chromium after all. I believe that everything works fine on Google Chrome.

**Comment by Mottie** [comment]
Oh, you think it's the browser extension? What does the CSS in the editor look like?

**Comment by VladimirDev93** [comment]
![screenshot from 2017-06-13 20-42-04](https://user-images.githubusercontent.com/12301022/27098720-e0f7aa02-5078-11e7-8a6f-6fb36dde29ea.png)

The thing is, this "Stylus" extension is way better than the official one from userstyle.org.
It has more options than the official one.

**Comment by Mottie** [comment]
What does the background image show when you select the original background?

If you find a problem with the extension, please open an issue here: https://github.com/schomery/stylus

**Comment by VladimirDev93** [comment]
![untitled-1](https://user-images.githubusercontent.com/12301022/27099258-a95ecdb2-507a-11e7-93ba-91d0ff7e67d7.jpg)

You can close this issue, because, even changing the colors of the text to "cyan" for the sake of test, it did not apply the custom settings. Even the code has not changed the syntax to "Monokai". Your style is fine, the problem is the extension. No matter what I select on advanced style settings, it will install the default settings of the style. Sorry for taking your time on useless issue. I'll open an issue on their repository. Once again, sorry.

**Comment by Mottie** [comment]
No worries! 😸
