### ISSUE TITLE
increase contrast for code span and active reaction

### ISSUE THREAD

**Issue by franklinyu** [StylishThemes/GitHub-Dark#504]
The active reaction area `.comment-reactions .user-has-reacted` looks slightly too dart for me (currently `#182030`, I can't really tell whether I reacted in a glance); `#222d44` looks better.

In addition, the code span is currently `#181818`. How about `#2e2e2e`?

I guess it is set in `/tools/generate.js` but not sure how to modify it.

**Comment by Mottie** [comment]
Hi @franklinyu!

Hmm, `#222d44` is a bit too bright to me. And what do you mean by a "code span"?

**Comment by franklinyu** [comment]
By “code span” I mean `this`, that is, inline `<code>` elements.

> `#222d44` is a bit too bright to me.

Just name a color you like. I'm mainly concerned about the case where there's only one reactions, for example:

![screenshot 2017-06-15 p m 6 54 15](https://user-images.githubusercontent.com/3153452/27204995-4458c6a6-51fc-11e7-9439-e80fc5f13e18.png)
![screenshot 2017-06-15 p m 6 54 06](https://user-images.githubusercontent.com/3153452/27205003-4994ec9e-51fc-11e7-8737-4c7aeaae98aa.png)

(it seems more legible when compared side by side… Forget it if you think it's Ok, and I'll do it in my custom style.)

**Comment by Mottie** [comment]
Oh, *that* code span 😛... I originally had the code span matching the syntax theme background, but ended up changing it to a grey-scale color because it made it a bit too distracting for inline code (e.g. Tomorrow Night Blue is kinda bright). We're trying to keep a consistent color palette and `#2e2e2e` isn't one of our background colors, but we could switch to `#222`; I looked at `#282828` and I think even that it too bright.

As for the reaction, I was thinking that maybe the background could be set as the base color but with a 30% opacity. 

```css
.comment-reactions .user-has-reacted {
  background-color: rgba(/*[[base-color-rgb]]*/, .3) !important;
}
```

What do you think @silverwind?

**Comment by silverwind** [comment]
> As for the reaction, I was thinking that maybe the background could be set as the base color but with a 30% opacity.

I'd go with 20%.

For the inline code blocks it's kind of complicated. They are defined in each syntax theme. Maybe they'll look better when made a bit brighter if guess we should remove the border on them if we make them brighter. Another option could be to match them to the big blocks at `#141414` and keep the border.

**Comment by franklinyu** [comment]
Excuse me, but what is the “base color” here? Is it the current background color `#182030`? So you mean `rgba(24,32,48,0.3)`?

As for the code span, if both of you are happy with the current setting, then it's either just my personal preference, or there's something wrong with my screen or lamp or something. In either case I think it's better for me to create my personal fix locally.

**Comment by Mottie** [comment]
> For the inline code blocks it's kind of complicated. They are defined in each syntax theme. 

We actually do set the background color of inline code and non-syntax highlighted code block to `#181818` - [ref](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L3308-L3315).

> what is the “base color” here?

The base color is a color you pick for your theme; it can be seen applied to links, focus outlines and some panels. By default it is set to `#4183c4`.

![](https://user-images.githubusercontent.com/136959/27225436-b557a986-525f-11e7-8134-e28a9f2410ee.png)

**Comment by franklinyu** [comment]
Then yes, hooking it with base color would be great!

**Comment by Mottie** [comment]
Ok, let me know what you guys think of these changes....

* Reactions are now 0.2 opacity of the base color
* Inline code blocks brightened from `#181818` to `#222222`.
