### ISSUE TITLE
Github Dark Settings are missing sometimes

### ISSUE THREAD

**Issue by ShalokShalom** [StylishThemes/GitHub-Dark#506]
* **Browser**: Opera
* **Operating System**: KaOS
* **HTML section and Screenshot**: 
![screenshot_20170615_141417](https://user-images.githubusercontent.com/6344099/27180750-222477d2-51d5-11e7-8e82-d5e2fca061b7.png)
Reload fix the issue temporarily.

**Comment by Mottie** [comment]
The GitHub Dark Settings are only applied through the GitHub-Dark script which I assume you're using since Stylus doesn't look like it is applying any styles.

I see some errors in the console, are any of them associated with the userscript?

**Comment by ShalokShalom** [comment]
How to check this?

I deleted all my Opera settings, lets see if that one work now.

**Comment by Mottie** [comment]
> How to check this?

You'll need to have the GItHub Dark (user)Script installed... then you can open the settings from the dropdown or press <kbd>g</kbd>, then <kbd>0</kbd> within one second of each other to open the settings panel.

**Comment by ShalokShalom** [comment]
?

**Comment by ShalokShalom** [comment]
You recommend me to open the Github Dark Settings, when they are not available?

**Comment by Mottie** [comment]
I was asking you to install GitHub-Dark-Script... then check if the settings are there since the settings panel is only added by the script, not the GitHub-Dark userstyle which is all css.

I don't have access to any systems with a KaOS, so I can't test or see the issue. Does the setting panel show up in Chrome?

**Comment by ShalokShalom** [comment]
Yes, I put this issue into the wrong repo. 

The name of this issue is anyway "Github Dark Settings are missing sometimes" 

They are there sometimes, sometimes not. 
I deleted my Opera folder in .config and it works until perfectly.

**Comment by silverwind** [comment]
Sounds like a race condition of sorts. What userscript engine is this running on?

**Comment by ShalokShalom** [comment]
Violent monkey.

**Comment by Mottie** [comment]
Sorry for the delay... I haven't used Violent monkey. Have you tried other userscript engines? Is Violent Monkey the only one causing this problem?

**Comment by ShalokShalom** [comment]
I deleted my Opera folder in .config and it works until perfectly.
