### ISSUE TITLE
Generated selectors

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#508]
Hey @silverwind 

I seem to be encountering this issue a bit more lately. Essentially since GitHub has included `!important` flags in their selectors, sometimes the GitHub-Dark script styling sometimes doesn't override them - I'm not sure about Stylus. I haven't been able to reproduce the problem consistently in order to find the actual cause. It happens mostly when I use the pager. This screenshot shows an issue with the `.border-bottom` styling, but it does tend to fix itself after using the pager again:

![](https://user-images.githubusercontent.com/136959/27361954-69d93fee-55f0-11e7-83c4-4d4992834537.gif)

I've also seen it happen with the `.link-gray-dark:hover` definition to issue title links on [main issue pages](https://github.com/StylishThemes/GitHub-Dark/issues).

Since our generated selectors have the same specificity as the existing selectors with an `!important` flag, what do you think about adding a prefix, like `body` to each of the generated selectors? We could limit this to only the selectors with an `!important` flag.

...or, maybe it's just me noticing it and it's a rare enough occurrence that we can ignore it...

**Comment by silverwind** [comment]
This is only with the script, right? I was hoping we could get away with our styles coming after GitHub's, so same-specificity styles get overridden by order. Can you check the DOM tree if our styles really is defined last when it happens? I suspect that might not always be the case.

**Comment by Mottie** [comment]
Yeah, it looks like the `<body>` doesn't exist when our style is added.

In this screenshot, you can see that the two stylus userstyles I use are added immediately after the `<head>` when they are usually added after the `</body>`.

![](https://user-images.githubusercontent.com/136959/27381421-6e29301a-5648-11e7-890e-4daa7405fe1a.gif)

Maybe we can copy Stylus' method and append our stylesheet after whatever element, `</head>` or `</body>` exists when it is applied.

**Comment by silverwind** [comment]
`<head>` should always load before `<body>`, and from what I read, `run_at: document_start` does not guarantee that any of them exist. If we still have issues, we could try running a `setInterval` until `<head>` is there and append after it. Of course this can break if the site has stylesheets in `<body>` but that's rather uncommon.

**Comment by Mottie** [comment]
The update has *so far* been working very well for me.
