### ISSUE TITLE
Syntax Themes Not Applying - Chrome

### ISSUE THREAD

**Issue by napalm684** [StylishThemes/GitHub-Dark#510]
* **Browser**: Version 59.0.3071.115 (Official Build) (64-bit)
* **Operating System**: Windows 7
* **Screenshot**:

![image](https://user-images.githubusercontent.com/8197405/27961032-66960e58-62fb-11e7-87f8-27790af28fd9.png)

![image](https://user-images.githubusercontent.com/8197405/27961025-5cf5b006-62fb-11e7-8b89-203e6ce76c27.png)

* **HTML of the section where the issue occurs**:

````html
<tbody><tr>
        <td id="L1" class="blob-num js-line-number" data-line-number="1"></td>
        <td id="LC1" class="blob-code blob-code-inner js-file-line"><span class="pl-k">@import</span> '<span class="pl-v">../../node_modules/normalize.css/normalize.css</span>';</td>
      </tr>
      <tr>
        <td id="L2" class="blob-num js-line-number" data-line-number="2"></td>
        <td id="LC2" class="blob-code blob-code-inner js-file-line"><span class="pl-k">@import</span> '<span class="pl-v">globals/_typography.scss</span>';</td>
      </tr>
      <tr>
        <td id="L3" class="blob-num js-line-number" data-line-number="3"></td>
        <td id="LC3" class="blob-code blob-code-inner js-file-line"><span class="pl-k">@import</span> '<span class="pl-v">globals/_vars-mixins.scss</span>';</td>
      </tr>
      <tr>
        <td id="L4" class="blob-num js-line-number" data-line-number="4"></td>
        <td id="LC4" class="blob-code blob-code-inner js-file-line">
</td>
      </tr>
      <tr>
        <td id="L5" class="blob-num js-line-number" data-line-number="5"></td>
        <td id="LC5" class="blob-code blob-code-inner js-file-line"><span class="pl-ent">body</span> {</td>
      </tr>
      <tr>
        <td id="L6" class="blob-num js-line-number" data-line-number="6"></td>
        <td id="LC6" class="blob-code blob-code-inner js-file-line">    <span class="pl-c1"><span class="pl-c1">background-color</span></span>: <span class="pl-smi">$background</span>;</td>
      </tr>
      <tr>
        <td id="L7" class="blob-num js-line-number" data-line-number="7"></td>
        <td id="LC7" class="blob-code blob-code-inner js-file-line">}</td>
      </tr>
</tbody>
````

**Comment by Mottie** [comment]
Hi @napalm684!

From what determine from looking at the screenshots, the "theme" setting in the first screenshot is to set the theme for the Stylus editor, not the GitHub Dark style. To change the syntax theme for GitHub, you'll need to either:

* Set the syntax theme on [userstyles.org](http://userstyles.org/styles/37035) - make sure to click on the "Advanced Style Settings" to open the panel.

  ![](https://user-images.githubusercontent.com/136959/27225436-b557a986-525f-11e7-8134-e28a9f2410ee.png)

  See [more detailed instructions here](https://github.com/StylishThemes/GitHub-Dark/wiki/Install#automatic-installation-from-userstylesorg)

* Or, switch to using our [GitHub-Dark userscript](https://github.com/StylishThemes/GitHub-Dark-Script) which allows you to dynamically change the syntax themes.

  ![](https://cloud.githubusercontent.com/assets/136959/22908590/022f56d8-f215-11e6-954c-decc9ecbd259.png)

**Comment by napalm684** [comment]
Yeah so I am an idiot.  Sorry it is working as intended must have looked too quickly at the instructions.  Thanks!

**Comment by Mottie** [comment]
Hehe no worries! I've been there too!
