### ISSUE TITLE
header ate blueberries

### ISSUE THREAD

**Issue by SEAPUNK** [StylishThemes/GitHub-Dark#515]
pretty sure the links and icons were white a moment ago

* **Browser**: Chrome
* **Operating System**: OSX
* **Screenshot**:

![screen shot 2017-07-20 at 5 14 00 pm](https://user-images.githubusercontent.com/4400726/28444033-f9208abe-6d6e-11e7-8a3a-282cb24b7bf0.png)

* **HTML of the section where the issue occurs**:

https://gist.github.com/SEAPUNK/a48df4fc942b93195d5d59e2e7bdcee5

**Comment by Mottie** [comment]
Hi @SEAPUNK!

Yep, GitHub just changed the header classes... I'll have a fix up in a few minutes.

**Comment by SEAPUNK** [comment]
👋 

cool, cool

**Comment by Mottie** [comment]
Fixed in https://github.com/StylishThemes/GitHub-Dark/commit/16fa2d8d754baa982a6c3c462958c89797ab224f.
