### ISSUE TITLE
The repository description gets sometimes loaded in unreadable color

### ISSUE THREAD

**Issue by ShalokShalom** [StylishThemes/GitHub-Dark#516]
* **Firefox**:
* **KaOS**:

* **HTML of the section where the issue occurs**:

```html
<span class="col-11 text-gray-dark mr-2" itemprop="about">
    A safe JavaScript widget framework for advertising and other mashups.
</span>
````

![screenshot_20170721_172834](https://user-images.githubusercontent.com/6344099/28470798-2fd07be2-6e3b-11e7-8e18-2d3a216da59d.png)

**Comment by Mottie** [comment]
Hi @ShalokShalom!

I am not seeing this same problem. Please share the class name of the element.

**Comment by silverwind** [comment]
Yes, please share the full HTML of that text when it happens. We correctly stile `.text-gray-dark`, maybe you color comes from an addon?

**Comment by ShalokShalom** [comment]
The whole inner and outer HTML: https://gist.github.com/ShalokShalom/47bc2d5ec88684f79970e70af5c3b3cb

**Comment by ShalokShalom** [comment]
Ahm, how?

**Comment by Mottie** [comment]
Oh, I thought you were using the userscript... I just updated userstyles.org.

**Comment by ShalokShalom** [comment]
I use the Stylish theme, since it loads faster. Github-Script is useless to me. Thanks
