### ISSUE TITLE
Unreadable highlight for code of conduct template

### ISSUE THREAD

**Issue by MrCraftCod** [StylishThemes/GitHub-Dark#526]
* **Browser**: Vivaldi | 1.12.941.3 (Official Build) (64-bit)
* **Operating System**: Windows 10
* **URL**: [https://github.com/StylishThemes/GitHub-Dark/community/code-of-conduct/new?template=citizen-code-of-conduct](https://github.com/StylishThemes/GitHub-Dark/community/code-of-conduct/new?template=citizen-code-of-conduct)
* **Screenshot**:
![vivaldi_2017-08-27_22-37-18](https://user-images.githubusercontent.com/1688389/29753747-55a72c3a-8b78-11e7-800e-100bc4de728d.png)

* **HTML of the section where the issue occurs**: 
````html
<p>A primary goal of <span class="CommunityTemplate-highlight js-template-highlight" data-fieldname="community_name">Di3   Projet Cpp</span> is to be inclusive to the largest number of contributors, with the most varied and diverse backgrounds possible. As such, we are committed to providing a friendly, safe and welcoming environment for all, regardless of gender, sexual orientation, ability, ethnicity, socioeconomic status, and religion (or lack thereof).</p>
````

**Comment by Mottie** [comment]
Hi @MrCraftCod!

Thanks for letting us know! I'll have it fixed in the master branch shortly. We'll get the userstyles site updated soon.
