### ISSUE TITLE
Two issues in license picker

### ISSUE THREAD

**Issue by skwerlman** [StylishThemes/GitHub-Dark#527]
* **Browser**: 60.0.3112.113
* **Operating System**: Arch Linux 64-bit
* **Screenshot**: 
![2017-08-27-213317_1889x933_scrot](https://user-images.githubusercontent.com/6954107/29756153-788efcb8-8b6f-11e7-8fc2-26009f72aecf.png)

* **HTML of the section where the issue occurs**:

Unreadable text
````html
<p>Copyright (c) <span class="CommunityTemplate-highlight js-template-highlight" data-fieldname="year">2017</span> <span class="CommunityTemplate-highlight js-template-highlight" data-fieldname="fullname">Fullname</span></p>
````

Solid background
```html
<div class="CommunityTemplate-header px-4 bg-white clearfix">
    <a href="/skwerlman/grc-temp-repo/community/license/new" class="js-selected-navigation-item selected float-left text-bold link-gray-dark no-underline" data-selected-links=" /skwerlman/grc-temp-repo/community/license/new">Add a license to your project</a>
  </div>
```

* **Page URL**: https://github.com/<username\>/<repo-name\>/community/license/new?branch=master&template=mit

**Comment by Mottie** [comment]
Hi @skwerlman!

This was fixed in https://github.com/StylishThemes/GitHub-Dark/commit/3895f72f9098ef3d6fd8590964e4aff45a71dd89 (see #526). It's currently only available in the master branch; we'll update the userstyle as soon as we resolve issues #524 - #525.

**Comment by skwerlman** [comment]
ah, cool! is the solid header background (`CommunityTemplate-header`) fixed too?

**Comment by Mottie** [comment]
Actually, I didn't mess with it since the `pagehead` has a bottom margin - it's a bit messed up. I'm not sure what to do with it, maybe make it transparent?
