### ISSUE TITLE
Incorrect position of profile drop down arrow

### ISSUE THREAD

**Issue by AmirSavand** [StylishThemes/GitHub-Dark#528]
The style is updated and here's a screenshot:

![image](https://user-images.githubusercontent.com/4629328/29818755-d48717fc-8cce-11e7-810d-006508d9eb64.png)

**Comment by silverwind** [comment]
What exactly do you mean and do you see it without the style too? The arrow is off-center in the avatar for me too:

<img width="202" src="https://user-images.githubusercontent.com/115237/29836091-5f387eac-8cf4-11e7-8c0e-4b906f960717.png">

**Comment by AmirSavand** [comment]
@silverwind It's like 1px off so it should be 1px above.

**Comment by AmirSavand** [comment]
Your avatar is off center, the original drop down is fine, the style however, should be a bit upper.

**Comment by AmirSavand** [comment]
@Mottie Awesome!

Yes, I think GitHub positioned it in center of both avatar and the arrow (not the avatar only).
