### ISSUE TITLE
Session refresh banner issues - look twice to see what it says

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#535]
* **Browser**: Firefox 55.0.3
* **Operating System**: Win 10
* **Screenshot**: 

![unthemed](https://user-images.githubusercontent.com/31389848/30386669-596e924a-98a2-11e7-8009-e06abb66ecec.PNG)

![themed](https://user-images.githubusercontent.com/31389848/30386726-7ba92244-98a2-11e7-92e8-d3331a44a5a6.PNG)

* **HTML of the section where the issue occurs**:

````html
<div class="js-stale-session-flash stale-session-flash flash flash-warn flash-banner is-signed-in">
    <svg aria-hidden="true" class="octicon octicon-alert" height="16" version="1.1" viewBox="0 0 16 16" width="16"><path fill-rule="evenodd" d="M8.865 1.52c-.18-.31-.51-.5-.87-.5s-.69.19-.87.5L.275 13.5c-.18.31-.18.69 0 1 .19.31.52.5.87.5h13.7c.36 0 .69-.19.86-.5.17-.31.18-.69.01-1L8.865 1.52zM8.995 13h-2v-2h2v2zm0-3h-2V6h2v4z"></path></svg>
    <span class="signed-in-tab-flash">You signed in with another tab or window. <a href="">Reload</a> to refresh your session.</span>
    <span class="signed-out-tab-flash">You signed out in another tab or window. <a href="">Reload</a> to refresh your session.</span>
  </div>
````

**Comment by Mottie** [comment]
Hi @the-j0k3r!

Thanks for letting us know. I'm going to specifically target this banner and make it completely opaque. I think the other warning messages look better with a partial opacity, as most don't overlay the header.

**Comment by the-j0k3r** [comment]
Sure, that works too. thanks. only recently became aware of this style, looks fantastic. good job ;)
