### ISSUE TITLE
Bold text doesn't really appear to be bold

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#537]
With the dark theme I tend to miss that text is bold. This is a mix of the colors and GitHub using `font-weight: 600` for most of its text. Bumping this up to `700` is better, but it's still nowhere as good as black on white. Is there something we can do to make this stand out a little more?

* **Browser**: Chrome
* **Operating System**: Win10 Creators Update
* **Screenshot**:

**Current - 600**

![image](https://user-images.githubusercontent.com/831974/30766777-76aa8920-9fc5-11e7-8240-a9774397568f.png)

**Bolder - 700**

![image](https://user-images.githubusercontent.com/831974/30766789-89641d1a-9fc5-11e7-9477-96a4719d7be4.png)

**Comment by Mottie** [comment]
Hi @xt0rted!

Hmm, it actually looks better if we brighten the color up a bit. The text is set to `#c0c0c0`, but when you brighten it to `#e2e2e2` it looks better:

![](https://user-images.githubusercontent.com/136959/30767153-176df41a-9fc0-11e7-8398-f4de3e8beec8.png)

**Comment by xt0rted** [comment]
That looks better.

Side question, are the inline color previews all supposed to be defaulted to black? It looks like the styles for `.Box` are stepping on the inline background color.

![image](https://user-images.githubusercontent.com/831974/30767314-b5c2083c-9fc9-11e7-90cf-26e60d8f0265.png)

**Comment by Mottie** [comment]
Yeah, I'm fixing that now... it looks like the generate script is including `.Box` which is added to swatches inside of color blocks.

**Comment by xt0rted** [comment]
@Mottie this looks to have regressed recently. Bolded text is using `#c0c0c0` again.

**Comment by Mottie** [comment]
Thanks for letting me know... it'll be in the next release.
