### ISSUE TITLE
rss link color not base color

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#538]
All links here are base color thing.

* **Browser**: Firefox 56
* **Operating System**: Win 10
* **Screenshot**:

![css](https://user-images.githubusercontent.com/31389848/31056492-3d6da7a8-a6ca-11e7-8995-e9b660b85363.PNG)

please imagine the mouse over hand cursor thing (wasnt captured)

* **HTML of the section where the issue occurs**:

https://github.com/

````html
<a class="f6 link-gray mt-2 d-inline-block" href="/editout.private.atom?token=GJhgsjxgBVFfavbZXVFSxvBNZXFGSFXfx==" data-ga-click="Dashboard, click, News feed atom/RSS link - context:user"><svg aria-hidden="true" class="octicon octicon-rss mr-1" height="16" version="1.1" viewBox="0 0 10 16" width="10"><path fill-rule="evenodd" d="M2 13H0v-2c1.11 0 2 .89 2 2zM0 3v1a9 9 0 0 1 9 9h1C10 7.48 5.52 3 0 3zm0 4v1c2.75 0 5 2.25 5 5h1c0-3.31-2.69-6-6-6z"></path></svg>Subscribe to your news feed</a>
````

thank you.

**Comment by Mottie** [comment]
Hi @the-j0k3r!

Thanks for letting us know. It'll be fixed soon.

**Comment by the-j0k3r** [comment]
Thank you and enjoy whats left of Sunday.
