### ISSUE TITLE
Stop overriding tab size

### ISSUE THREAD

**Issue by glebm** [StylishThemes/GitHub-Dark#539]
I did not expect GitHub Dark to override the default GitHub tab sizes.

`data-tab-size` is set differently by GitHub depending on several factors, for example:

1. GitHub respects `.editorconfig` and similar files when setting the tabs size.
2. The defaults are different depending on the language, e.g. it's 8 for Go, but 4 for JavaScript.

GitHub Dark breaks all of that by forcing the same tab size everywhere.
It also causes issues with other extensions that rely on `data-tab-size`, such as [Render Whitespace on GitHub](https://github.com/glebm/render-whitespace-on-github).

 Colors have nothing do with the tab size. GitHub Dark should not be touching the tab size.

**Comment by silverwind** [comment]
I prefer to have a consistent tab sizes on everything I view, but I guess we could add a option during style installation that leaves it as-is, if that works for you.

Otherwise, we could also move the tab-size modification to it's own userstyle.

**Comment by glebm** [comment]
While either would fix my problem, removing tab-size from this userstyle seems like the best option to me, because modularity and separation of concerns.

There are other ways to set a custom tab size already, for example:
https://github.com/lukechilds/github-custom-tab-size

**Comment by Mottie** [comment]
> add a option during style installation that leaves it as-is

That sounds good to me, I'll update the script.

**Comment by glebm** [comment]
@Mottie If you decide to go that way, please make that option default.

**Comment by Mottie** [comment]
All done.

**Comment by silverwind** [comment]
Created a separate style for fixed tab size: https://github.com/StylishThemes/GitHub-tab-size

**Comment by glebm** [comment]
Thank you!
