### ISSUE TITLE
Diff +/- aren't styled correctly when Refined GitHub is installed

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#540]
[refined-github](https://github.com/sindresorhus/refined-github) has a feature where it adjusted the html for the `+` and `-` in diffs so they aren't included during copy. Because of this the symbols lose their styling 😢

* **Browser**: Chrome
* **Operating System**: Win10
* **Screenshot**:
![image](https://user-images.githubusercontent.com/831974/31153935-dde82a0c-a871-11e7-9a28-be990f4d94de.png)

* **HTML of the section where the issue occurs**:

The selector is `.code-review.blob-code.blob-code-addition::before`

````html
<tr class="refined-github-diff-signs">
    <td class="blob-num blob-num-empty empty-cell"></td>
    <td class="blob-code blob-code-empty empty-cell"></td>

    <td class="blob-num blob-num-addition js-linkable-line-number" id="diff-8d1043c42931bf314e47f8ced3169f49R2" data-line-number="2"></td>

    <td class="code-review blob-code blob-code-addition">
        <button class="btn-link add-line-comment js-add-line-comment js-add-split-line-comment" data-type="addition" data-path="..." data-anchor="diff-..." data-position="2" data-line="2" type="button" aria-label="Add line comment"><svg aria-hidden="true" class="octicon octicon-plus" height="16" version="1.1" viewBox="0 0 12 16" width="12"><path fill-rule="evenodd" d="M12 9H7v5H5V9H0V7h5V2h2v5h5z"></path></svg></button>

      <span class="blob-code-inner">{</span>

    </td>
</tr>
````

**Comment by Mottie** [comment]
Hi @xt0rted!

I don't use that extension much, it's a little too opinionated for my tastes, but it does have a lot of nice features. Please let us know if there are any other unstyled elements, so we can maintain it better.
