### ISSUE TITLE
Expand/Collapse link not base color styled

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#541]
Here is another 

* **Browser**: Firefox 56.0
* **Operating System**: WIn 10
* **Screenshot**:

![capture](https://user-images.githubusercontent.com/31389848/31171246-ed89272e-a8f6-11e7-9d90-f5de3cda0d75.PNG)
![capture1](https://user-images.githubusercontent.com/31389848/31171245-ed88cf90-a8f6-11e7-96c6-0a6ddf9eb929.PNG)

* **HTML of the section where the issue occurs**:

````html
<button type="button" class="btn-link link-gray js-details-target" aria-label="Show or hide contributors" aria-expanded="false" data-initial-state="true">
        <span class="Details-content--shown">Expand<svg aria-hidden="true" class="octicon octicon-chevron-down ml-1" height="16" version="1.1" viewBox="0 0 10 16" width="10"><path fill-rule="evenodd" d="M5 11L0 6l1.5-1.5L5 8.25 8.5 4.5 10 6z"></path></svg></span>
        <span class="Details-content--hidden">Collapse<svg aria-hidden="true" class="octicon octicon-chevron-up ml-1" height="16" version="1.1" viewBox="0 0 10 16" width="10"><path fill-rule="evenodd" d="M10 10l-1.5 1.5L5 7.75 1.5 11.5 0 10l5-5z"></path></svg></span>
      </button>
````

**Comment by Mottie** [comment]
Hi @the-j0k3r!

Would you please provide a link to the page. We are already including `link-gray`, so it would help if we could see which style is overriding the definition.

**Comment by the-j0k3r** [comment]
I cant provide any links, there are none to provide.

You will need to block people that have previously contributed to a repository, then visit that repository.

**Comment by silverwind** [comment]
@Mottie you can just paste the HTML from the OP anywhere on the page and then inspect the styles on the new nodes. In this case, it's this style that we need to override:

````css
.link-gray:hover {
    color: #0366d6 !important;
}
````

**Comment by the-j0k3r** [comment]
Neat. Just works™

Thanks guys.
