### ISSUE TITLE
tab setting in https://userstyles.org/styles/37035/github-dark has no effect

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#543]
* **Browser**: forefox 56
* **Operating System**: Win 10
* **Screenshot**:

![capture0](https://user-images.githubusercontent.com/31389848/31399924-c4031952-ade5-11e7-9dc3-24a7a01eabef.PNG)

* **HTML of the section where the issue occurs**:

Github edit
![capture](https://user-images.githubusercontent.com/31389848/31399897-b14245a4-ade5-11e7-9e93-7dc013345e18.PNG)
````html
<select class="form-select select-sm js-code-indent-width">
          <optgroup label="Indent size">
            <option value="2" selected="selected">2</option>
<option value="4">4</option>
<option value="8">8</option>
          </optgroup>
        </select>

````
Gist edit tabs
![capture1](https://user-images.githubusercontent.com/31389848/31399918-bf09b776-ade5-11e7-83c9-358cd06bbced.PNG)

````html
<select class="form-select select-sm js-code-indent-width">
          <optgroup label="Indent size">
            <option value="2">2</option>
<option value="4">4</option>
<option value="8" selected="selected">8</option>
          </optgroup>
        </select>
```

**Comment by Mottie** [comment]
Hi @the-j0k3r!

It's working for me. I think that another style or userscript, there are a lot, is modifying the tab size and overriding the GitHub Dark setting. Try turning them off one-by-one to find the culprit. Please let us know if it's one of ours.

**Comment by the-j0k3r** [comment]
Well, I disabled everything except github-dark cleared cookies, restarted firefox, disabled stylus/re-enabled, and still doesnt work.

**Comment by Mottie** [comment]
Are you using any userscripts?

**Comment by Mottie** [comment]
Oh, and we just changed the default tab setting on userstyles.org to "don't modify" (disabled). The totally messed up the storage, so you'll need to add any customizations *every time* you install/update a style.

**Comment by the-j0k3r** [comment]
I did

**Comment by the-j0k3r** [comment]
removed github dark rinse and repeat resets re-install gh dark 

![capture](https://user-images.githubusercontent.com/31389848/31402257-65618ac0-aded-11e7-8858-d5d17d19f060.PNG)

the code is there, still doesnt work.

**Comment by Mottie** [comment]
![](https://user-images.githubusercontent.com/136959/31402452-a08bdba0-adbb-11e7-89e9-3e3706a0ab8a.gif)

**Comment by the-j0k3r** [comment]
well that works but doesnt work on the tab settings when editing code.

**Comment by Mottie** [comment]
Ahh, you mean CodeMirror...

From looking at the HTML, it appears that CodeMirror adds a span with however many spaces you have the tab size set to:

```html
<span class="cm-tab" role="presentation" cm-text="	">        </span> <!-- tab size 8 -->
<span class="cm-tab" role="presentation" cm-text="	">    </span> <!-- tab size 4 -->
<span class="cm-tab" role="presentation" cm-text="	">  </span> <!-- tab size 2 -->
```

```css
.cm-tab {
  display: inline-block;
  text-decoration: inherit;
}
```

I don't think there's much we can do about that besides modifying it with javascript.

**Comment by Mottie** [comment]
Any ideas @silverwind?

The `cm-text` attribute does contain a tab, but I don't think using a `:before` or `:after` with that content would make any difference if we can't remove the spaces inside the span...

**Comment by silverwind** [comment]
You could try `font-size: 0` on the span.

**Comment by Mottie** [comment]
That almost worked... but setting the font size for the `:after` is adding a top and bottom pad?

![](https://user-images.githubusercontent.com/136959/31408868-8befa924-adcf-11e7-8f4a-d92d0e2dec29.gif)

```css
.cm-tab {
  display: inline !important;
  font-size: 0 !important;
}
span.cm-tab:after {
  content: attr(cm-text) !important;
  display: inline !important;
  font-size: 1rem !important;
}
```

I've tried `.8rem` but then the tab size changes as well.

**Comment by the-j0k3r** [comment]
superseded by https://github.com/StylishThemes/GitHub-Dark/pull/959#issuecomment-779314529
