### ISSUE TITLE
Diff plus overlaps file info bar

### ISSUE THREAD

**Issue by jodizzle** [StylishThemes/GitHub-Dark#544]
* **Browser**: Firefox 57
* **Operating System**: Linux
* **Screenshot**: 
![diff-plus-overlap](https://user-images.githubusercontent.com/672268/31419253-c530089e-ae08-11e7-8cce-5dda4130c063.png)

* **HTML of the section where the issue occurs**:

File info bar:
```html
<div class="file-info">
      <span class="diffstat tooltipped tooltipped-e" aria-label="0 additions &amp; 4 deletions">4 <span class="block-diff-deleted"></span><span class="block-diff-deleted"></span><span class="block-diff-deleted"></span><span class="block-diff-deleted"></span><span class="block-diff-neutral"></span></span>
      <a href="#diff-a084b794bc0759e7a6b77810e01874f2" class="link-gray-dark" title=".gitignore">.gitignore</a>
</div>
```
I'm having trouble locating the HTML for the plus.  Maybe because it's a hover element?

For clarity, in the image I'm hovering over part of where line 8 would be visible without the style active.

Not sure if this is an issue per se, but it's something that sticks out to me.

**Comment by Mottie** [comment]
Hi @jodizzle!

Thanks for letting us know! I'll get this fixed soon.

**Comment by Mottie** [comment]
Fixed in https://github.com/StylishThemes/GitHub-Dark/commit/40b2a51b69cddedd4180d5bd523a040bf83b85c4.

**Comment by jodizzle** [comment]
Thanks!
