### ISSUE TITLE
New index page

### ISSUE THREAD

**Issue by joubertredrat** [StylishThemes/GitHub-Dark#545]
Hi guys,

Since today github have new index here as screen on display below. I'm reporting this because I dont know if you will apply dark style for this new index.

Thanks.

![screenshot-github com-2017-10-11-18-02-44](https://user-images.githubusercontent.com/1520407/31466682-72b79c84-aeae-11e7-9a1e-554f59168fdf.png)

**Comment by Mottie** [comment]
Hi @joubertredrat!

I saw it, and it doesn't appear to have any issues, but we might have a few unnecessary selectors now...

**Comment by silverwind** [comment]
Did a few tweaks like adding background to these new notice boxes and made the font color in the news feed slightly darker, I think it's in pretty good shape.
