### ISSUE TITLE
Octolink link color didn't get change

### ISSUE THREAD

**Issue by gluons** [StylishThemes/GitHub-Dark#549]
* **Browser**: Firefox Nightly 58.0a1
* **Operating System**: Windows 10
* **Screenshot**:
![screenshot-2017-10-25 buunguyen octotree](https://user-images.githubusercontent.com/4688092/31980864-a70f9042-b979-11e7-968c-fc354c29d60d.png)

* **HTML of the section where the issue occurs**:

````html
<a class="jstree-anchor" href="/buunguyen/octotree/tree/master/.github" tabindex="-1" data-download-url="/buunguyen/octotree/tree/master/.github" data-download-filename=".github" id="octotree.github_anchor"><i class="jstree-icon jstree-themeicon tree jstree-themeicon-custom" role="presentation"></i>.github</a>
````

**Comment by Mottie** [comment]
Hi @gluons!

Thanks for letting us know. It looks like we just need to increase the specificity of the selector.
