### ISSUE TITLE
Syntax Highlighting Theme Requests

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#55]
This issue lists possible syntax highlighting themes to include with this repo. These are themes I could use help with converting to a standard pygments theme.

If you find any that you'd like to have included, please list them in this thread.
#### Vim Themes (need [conversion to pygments](https://github.com/honza/vim2pygments))
- [x] [Mustang](http://hcalves.deviantart.com/art/Mustang-Vim-Colorscheme-98974484) 
- [x] [Vitamins](http://hcalves.deviantart.com/art/Vitamins-Vim-Colorscheme-98630379)
- [x] [Neverland](https://github.com/trapd00r/neverland-vim-theme)
- [x] [Birds of Paradise](https://github.com/kennethlove/Birds-of-Paradise-VIM-Theme)
- [x] [Digerati](http://hcalves.deviantart.com/art/Digerati-Vim-Colorscheme-100471798)
- [x] [Pastels on Dark](https://github.com/mikefarmer/pastelsondark-vim)
- [x] [Up](https://github.com/kennethlove/up.vim)
- [x] Darcula
#### Other Themes (need conversion)
- [x] [Twilight.tmTheme](https://github.com/cj/sublime/blob/master/Color%20Scheme%20-%20Default/Twilight.tmTheme)
- [x] [Idle Fingers](http://idlefingers.co.uk/)

@aalvarado Could you help out with some of these? Thanks! :P

**Comment by psthompson** [comment]
What ever happened to the Dracula theme that was being worked on. I would love to see that implemented.

**Comment by Poorchop** [comment]
There used to be a lot of color schemes and I think there was even one for Dracula. At some point, GitHub stopped using pygments for syntax highlighting. It looks like it now uses Ace editor color schemes and I don't know of any preexisting tools for easy conversion. I'm sure more themes could still be implemented, but I'm guessing that it would take a lot of manual effort.

I like Dracula as well plus a few other color schemes but in my experience, creating a CodeMirror scheme was a pain, so I imagine doing the same will be a pain for Ace (assuming that's what GitHub uses now).

**Comment by Mottie** [comment]
Actually GitHub uses an in-house syntax highlighting program, so the way it selects elements to highlight is a bit different than pygments and most other plugins. So, yes, all the currently available syntax themes were manually tweaked in an attempt to match the original theme; but it may not look good in every language.

If you have the time and would like to make a theme, you can tweak [this template code](https://github.com/StylishThemes/GitHub-Dark/blob/master/themes/template/template.css). Then use [this wiki page](https://github.com/StylishThemes/GitHub-Dark/wiki/Highlighting) to test it. We would be happy to include any submitted themes.

**Comment by silverwind** [comment]
That template is a bit out of date thought, I'd suggest [Twilight](https://github.com/StylishThemes/GitHub-Dark/blob/master/themes/src/twilight.css) as a starting point.
