### ISSUE TITLE
It's good but you know the ux and ui in the index-demo page was really bad and I think I can handle it

### ISSUE THREAD

**Issue by alimazrooei** [StylishThemes/GitHub-Dark#551]
# That Index page was bs

**Comment by Mottie** [comment]
You're right... I tried to fix up the page a bit. You can now tab and use space to toggle the blocks.

What do you think?

**Comment by alimazrooei** [comment]
I think it's bs and I can help you to improve that

2017-10-26 5:55 GMT+03:30 Rob Garrison <notifications@github.com>:

**Comment by alimazrooei** [comment]
what do you think?


2017-10-27 0:02 GMT+03:30 علی مزروعی <rebel.king700@gmail.com>:

**Comment by alimazrooei** [comment]
da fuck?
I'm busy bro
don't you understand?
I wanted to pr but I've been busy

2017-11-15 2:01 GMT+03:30 silverwind <notifications@github.com>:

**Comment by Mottie** [comment]
@alimazrooei Go ahead and submit a PR, we don't need an open issue.
