### ISSUE TITLE
Tooltips are really hard to see

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#552]
I'm not sure if this changed recently but I'm finding tooltips to be really hard to see now. Currently they're using `rgba(27,31,35,0.8)` for their background color which seems to cause them to blend in almost entirely in a lot of areas.

* **Browser**: Chrome 62
* **Operating System**: Win10
* **Screenshot**:
![image](https://user-images.githubusercontent.com/831974/32388129-0df3c42a-c09d-11e7-8778-47d7cef6ff1d.png)

* **HTML of the section where the issue occurs**:

````html
<button type="submit" class="mark-all-as-read css-truncate tooltipped tooltipped-w" aria-label="Mark all kudu notifications as read">
    <svg aria-hidden="true" class="octicon octicon-check" height="16" version="1.1" viewBox="0 0 12 16" width="12"><path fill-rule="evenodd" d="M12 5l-8 8-4-4 1.5-1.5L4 10l6.5-6.5z"></path></svg>
</button>
````

**Comment by Mottie** [comment]
Hi @xt0rted!

Thanks for reporting this!

@silverwind I added a few generator rules to brighten the tooltips, let me know what you think.

**Comment by xt0rted** [comment]
The update color is a lot better. The only place this is still a bit of an issue is when there's text under the tooltip, such as in an issue where you use the `Closes #123` syntax. In that instance the tooltip for the issue would have text under it which shows through because of the alpha channel on the background color.

**Comment by Mottie** [comment]
I'd prefer not to go completely opaque, so I changed the value to 0.9. Is that better?

**Comment by xt0rted** [comment]
Stylus keeps saying `server unreachable` 😞 when I try to update, but I changed it dev tools to check. And yea I think that's much better than it was.

**Comment by silverwind** [comment]
Looking fine to me, thanks.
