### ISSUE TITLE
New commit comment button has no background color now

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#553]
* **Browser**: chrome 62
* **Operating System**: Win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/32413555-86ff7ce8-c1e1-11e7-9a1a-3e9af1a261c9.png) ![image](https://user-images.githubusercontent.com/831974/32413564-c3dbb65e-c1e1-11e7-9d93-642d105c4306.png)

* **HTML of the section where the issue occurs**:

```html
<button class="btn-link add-line-comment js-add-line-comment js-add-split-line-comment"
        data-type="addition"
        data-path="..."
        data-anchor="diff-..."
        data-position="6"
        data-line="173"
        type="button"
        aria-label="Add line comment">
    <svg aria-hidden="true" class="octicon octicon-plus" height="16" version="1.1" viewBox="0 0 12 16" width="12">
        <path fill-rule="evenodd" d="M12 9H7v5H5V9H0V7h5V2h2v5h5z"></path>
    </svg>
</button>
```

**Comment by Mottie** [comment]
Hi @xt0rted!

Thanks! It's been fixed in the master branch.
