### ISSUE TITLE
Bottom border for items

### ISSUE THREAD

**Issue by RaitaroH** [StylishThemes/GitHub-Dark#556]
* **Browser**: Firefox 59
* **Operating System**: Linux Mint 17.3 64bit
* **Screenshot**:
![screenshot from 2017-11-15 16 44 26](https://user-images.githubusercontent.com/19552720/32841878-42e09bbe-ca24-11e7-92da-26539cf4c14b.png)
* **HTML of the section where the issue occurs**:

````html
.UnderlineNav-item.selected
{
border-bottom-color: #e36209;
}
````
So change this to:
````html
.UnderlineNav-item.selected
{
border-bottom-color: /*[[base-color]]*/;
}
````
Or change it to white to keep it as it was in the past. I just don't know what shade you are using so, there you go.

**Comment by silverwind** [comment]
Got a link to a page where this shows?

**Comment by skwerlman** [comment]
for me, it shows on every profile page
