### ISSUE TITLE
Description Color

### ISSUE THREAD

**Issue by julmot** [StylishThemes/GitHub-Dark#559]
https://github.com/ngx-material-keyboard/core

* **Browser**: FF 57
* **Operating System**: Win 10
* **Screenshot**:

Original:

![topic](https://user-images.githubusercontent.com/8310677/33059860-62a372c0-ce96-11e7-80ea-231b67140be7.png)

After:

![topic](https://user-images.githubusercontent.com/8310677/33059866-6d8e5f10-ce96-11e7-8789-2c93b577de49.png)

* **HTML of the section where the issue occurs**:

````html
<div class="repository-meta-content col-11 mb-1">
          <span class="col-11 text-gray-dark mr-2" itemprop="about">
            Onscreen virtual keyboard for Angular ≥ 4 (<a href="https://angular.io/" rel="nofollow">https://angular.io/</a>) using Material 2 (<a href="https://material.angular.io/" rel="nofollow">https://material.angular.io/</a>).
          </span>
          <span itemprop="url"><a href="https://ngx-material-keyboard.github.io/core/" rel="nofollow">https://ngx-material-keyboard.github.…</a></span>
    </div>
````

**Comment by skwerlman** [comment]
I'm not seeing this in Chrome 63 on Windows 10
![image](https://user-images.githubusercontent.com/6954107/33060136-3ca262e2-ce65-11e7-874e-cba08a55ea96.png)

**Comment by Mottie** [comment]
Hi @julmot!

Please make sure you have the most up-to-date style installed... it is currently v1.19.13 updated on 2017-11-15.

**Comment by julmot** [comment]
Strange. Sometimes it appears even after updating, sometimes it doesn't. Closing for now. Thanks for reaching out :-)
