### ISSUE TITLE
Feature comparison table at pricing section hard to read

### ISSUE THREAD

**Issue by TrueFurby** [StylishThemes/GitHub-Dark#560]
* **Browser**: Firefox 57.0 (64-bit)
* **Operating System**: Windows 10
* **Screenshot**: https://screenshots.firefox.com/7mUuUbDGON2j6T3R/github.com

* **HTML of the section where the issue occurs**: https://gist.github.com/TrueFurby/ed6e9567656a988ca53b615f6037e0a0

**Comment by Mottie** [comment]
Hi @TrueFurby!

Thanks for reporting this problem, I'll get it fixed shortly.

**Comment by Mottie** [comment]
Page location for future reference: https://github.com/pricing

**Comment by TrueFurby** [comment]
Thanks man!
