### ISSUE TITLE
Wiki indent contradiction 

### ISSUE THREAD

**Issue by sparcut** [StylishThemes/GitHub-Dark#562]
The indention in [`CONTRIBUTING.md#github-style-guide` ](https://github.com/StylishThemes/GitHub-Dark/blob/1a459badff42f652a39346c5e125b4dbf0e7d837/.github/CONTRIBUTING.md#github-dark-style-guide) contradicts when is said in the wiki.

![chrome_2017-11-29_14-07-52](https://user-images.githubusercontent.com/16233822/33356147-00f38662-d50f-11e7-8316-e8eb35fd3ab5.png)

(contrib.md says `2`, wiki uses `4`  in build)

**Comment by Mottie** [comment]
The JSON that is shown in the screenshot are the custom GitHub settings. The "tab" set the code block `tab-size`  which is `8` by default on GitHub.
