### ISSUE TITLE
Build wiki/grunt problems

### ISSUE THREAD

**Issue by sparcut** [StylishThemes/GitHub-Dark#563]
Looking through the [build wiki](https://github.com/StylishThemes/GitHub-Dark/wiki/Build) and the grunt tasks in the actual project, there are a ton more, and differently named tasks.

The default task also does not seem to build as described, rather it seems it takes minified versions of themes.

Default also seems to also modify github-dark.css as well as build file.

**Comment by Mottie** [comment]
Hi @sparcut!

Yeah, we've been bad about updating the wiki page. If it isn't listed on the wiki page, then it's probably a task only used in development, e.g. `grunt patch` which packages a patch release.

The default grunt task should be creating a `github-dark-{GitHub-theme}-{main-color}.build.css` file modified from the `github-dark.css` file. The options can be modified by adding a `build.json` file to the root as described in the build wiki.

Anyway, now that [Stylus](https://add0n.com/stylus.html) and [Freestyler](http://freestyler.ws/) support [usercss](https://github.com/openstyles/stylus/wiki/Usercss) formats, I would recommend installing our [`github-dark.user.css` style](https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-dark.user.css) directly from the repository. It will automatically update and doesn't depend on userstyles.org. The options can also be modified from within the extension.

**Comment by sparcut** [comment]
Yeah, just saw the Stylus link on the readme, switched from Stylish. Enjoying it.

**Comment by silverwind** [comment]
I documented all current grunt tasks: https://github.com/StylishThemes/GitHub-Dark#development

@Mottie do you actually use the `watch` task? I don't think it really serves any purpose.

**Comment by Mottie** [comment]
I never use it.

**Comment by silverwind** [comment]
Okay, dropped it. I removed the outdated grunt stuff in the wiki, so this should be resolved.
