### ISSUE TITLE
Testing theme - files

### ISSUE THREAD

**Issue by sparcut** [StylishThemes/GitHub-Dark#564]
Do you have any suggestion for testing themes, ensure compatibility across languages/syntaxes?

**Comment by Mottie** [comment]
Hi @sparcut!

Not really. We initially set up [this demo](https://stylishthemes.github.io/GitHub-Dark/) for testing pygments back when GitHub used it; but now it's only good for Jupyter theme testing.

Now that GitHub is using their own PrettyLights highlighter, you *might* get better results using their [theme generator](https://github.com/primer/github-syntax-theme-generator), but it still requires manual conversion and visual tweaking of existing themes. We have a [wiki page](https://github.com/StylishThemes/GitHub-Dark/wiki/Highlighting) set up for that, but that's lots of manual work.

As for CodeMirror, we've only been using existing themes...

**Comment by sparcut** [comment]
Yeah, I went through and did github and codemirror theme by hand... I think I'll translate it into the generator so it'll cover the full scope of selectors.
