### ISSUE TITLE
Project search dropdown not themed when no result

### ISSUE THREAD

**Issue by phit** [StylishThemes/GitHub-Dark#569]
* **Browser**: FF Nightly 59
* **Operating System**: Windows 10
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/2097483/33521207-f5e3de7e-d7cb-11e7-9352-49291faada29.png)

* **HTML of the section where the issue occurs**:

https://gist.github.com/phit/d033e485ba541bad727c9c7ce266a9c8

fix should be

```
.card-filter-autocomplete-dropdown .autocomplete-keyword-only {
    background: #181818;
}
```

**Comment by Mottie** [comment]
Hi @phit!

Thanks for reporting this problem, I'll get it fixed in the master branch/usercss shortly.
