### ISSUE TITLE
Odd breakages on lavabit/magma repo

### ISSUE THREAD

**Issue by skwerlman** [StylishThemes/GitHub-Dark#570]
* **Browser**: Chromium 62.0.3202.94
* **Operating System**: Arch Linux
* **Screenshot**:
Grey rectangle in file listings
![2017-12-04-072023_1030x409_scrot](https://user-images.githubusercontent.com/6954107/33552761-21487414-d8c4-11e7-8b0a-8c6ddde953be.png)
Grey squares instead of chevrons
![2017-12-04-072033_516x127_scrot](https://user-images.githubusercontent.com/6954107/33552762-21537bc0-d8c4-11e7-84d7-25cef5cd2996.png)
![2017-12-04-072043_198x39_scrot](https://user-images.githubusercontent.com/6954107/33552763-215e5112-d8c4-11e7-9f6d-19d2bcb046b4.png)
Thick outlines around tabs and code blocks
![2017-12-04-072050_713x156_scrot](https://user-images.githubusercontent.com/6954107/33552764-21680e78-d8c4-11e7-843d-68a2d1fdc9c4.png)
![2017-12-04-072143_914x175_scrot](https://user-images.githubusercontent.com/6954107/33552766-2186381c-d8c4-11e7-8907-1282164683ae.png)
Very odd styling on issues and PRs
![2017-12-04-072214_1033x834_scrot](https://user-images.githubusercontent.com/6954107/33552768-21915382-d8c4-11e7-96c9-51575337d19e.png)

* **Pages where the issues occur**:

https://github.com/lavabit/magma
https://github.com/lavabit/magma/issues

This does not occur for any other repos I've seen.

**Comment by silverwind** [comment]
That seems like a browser and/or gpu driver bug to me. Maybe try disabling hardware accelleration if that's possible?

**Comment by skwerlman** [comment]
The issues persist with hardware acceleration disabled...

**Comment by silverwind** [comment]
Can you inspect one of those tabs and show the compued border styles? Like here:

<img width="1253" alt="screen shot 2017-12-04 at 14 43 36" src="https://user-images.githubusercontent.com/115237/33555722-ab051648-d901-11e7-8272-3f0b2bc75d37.png">

**Comment by skwerlman** [comment]
![2017-12-04-090232_949x824_scrot](https://user-images.githubusercontent.com/6954107/33556425-e476e544-d8d1-11e7-935a-0b1a2a487389.png)

**Comment by silverwind** [comment]
Very weird, the browser thinks they are 1px wide but renders differently. Maybe try another version of Chrome?

**Comment by Mottie** [comment]
The border color is set as `rgb` and not `rgba` too...

**Comment by silverwind** [comment]
> The border color is set as rgb and not rgba too...

That's fine I think, just some sort of optimizations the browsers do. My Firefox Devtools also show rgba colors for everything.

**Comment by Mottie** [comment]
Well, I think there might be another style... we have it set as `rgba(0, 0, 0, 0)` but the screenshot is showing `rga(51, 51, ...`

**Comment by skwerlman** [comment]
I found the issue, and I feel a bit dumb for not figuring it out sooner. Turns out one of the styles i use which is supposed to apply to all .bit domains (from zeronet) had a messed up regex which somehow matched the `bit` in `lavabit`, causing it to apply to the page.
