### ISSUE TITLE
Issue label popup has too high of a z-index now

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#571]
It looks like GitHub changed their z-indexes today and the value of `29` used by GitHub-Dark is too high so it prevents you from interacting with the issue label popup now. Their current value is `20` which looks to work ok with the custom styles.

* **Browser**: Chrome 62
* **Operating System**: Win10
* **Screenshot**:

* **HTML of the section where the issue occurs**:

````html
<div class="modal-backdrop js-touch-events"></div>
````

**Comment by Mottie** [comment]
Hi @xt0rted!

Please be more specific. We don't have any z-indexes above `6` and we don't have either of the selectors listed above. I'm guessing you might be referring to a different style?

**Comment by xt0rted** [comment]
Looks like this is working now. Earlier the label popup only worked with GitHub-Dark disabled. The style rules looked slightly different then as well (`.modal-backdrop` was getting a `z-index` of `29` with this enabled and `20` with it disabled). Maybe I had a partial update or they fixed whatever was wrong. Either way I'm not seeing the issue now.
