### ISSUE TITLE
Bolded links can't be distinguished from normal bolded text

### ISSUE THREAD

**Issue by tambry** [StylishThemes/GitHub-Dark#573]
* **Browser**: Chrome 63.0.3239.84 64-bit
* **Operating System**: Widows 10 Pro N 1709 16299.98

Example markdown:
```
**Normal bolded text**  
[**I'm a bolded link**](https://www.google.com)
```

**Normal bolded text**  
[**I'm a bolded link**](https://www.google.com)

[With dark theme](https://i.imgur.com/wCRfAYQ.png)  
[Without dark theme](https://i.imgur.com/rW22soD.png)

HTML of the section where the issue occurs:
````html
<a href="https://www.google.com" rel="nofollow">
	<strong>I'm a bolded link</strong>
</a>
````

**Comment by tambry** [comment]
This issue is back once again.

**Comment by auscompgeek** [comment]
I think #537 is regressing this.

**Comment by Mottie** [comment]
Oops! I'll have that fixed ASAP.
