### ISSUE TITLE
release status colors

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#574]
Pre-release + Latest release labels colors arent styled properly vs unstyled

* **Browser**:FF 57.0.2
* **Operating System**: win 10
* **Screenshot**:

![releasecolor](https://user-images.githubusercontent.com/31389848/33936692-48556d6a-dff8-11e7-94cb-9ea3904993b7.gif)

* **HTML of the section where the issue occurs**:

i.e. https://github.com/atom/atom/releases

````html
<span class="Label Label--outline mb-2 Label--prerelease">
          Pre-release
      </span>

<span class="Label Label--outline mb-2 Label--latest">
          <a href="/atom/atom/releases/latest">Latest release</a>
      </span>
````

**Comment by Mottie** [comment]
Hi @the-j0k3r!

Thanks for letting us know. This'll be fixed in the master branch shortly.
