### ISSUE TITLE
Pre-release/Latest indicator in Release page has no color.

### ISSUE THREAD

**Issue by gluons** [StylishThemes/GitHub-Dark#575]
Orange (Pre-release) and Green (Latest) colors have gone. 🙁

---

* **Github Dark:** v1.20.6 (2017-12-10)
* **Browser**: Firefox Nightly 59.0a1
* **Operating System**: Linux Mint 18.2
* **Screenshot**:

  - **Pre-release:**
    ![1](https://user-images.githubusercontent.com/4688092/34079653-6586d134-e364-11e7-96fb-731998122e06.png)
    ![2](https://user-images.githubusercontent.com/4688092/34079655-6ac0b28c-e364-11e7-86aa-2f087c7d8c65.png)
  - **Latest release:**
    ![3](https://user-images.githubusercontent.com/4688092/34079656-6e7ea9ce-e364-11e7-9fde-e4dd7917519b.png)
    ![4](https://user-images.githubusercontent.com/4688092/34079657-718f666c-e364-11e7-829c-687ec557ef13.png)

* **HTML of the section where the issue occurs**:

````html
<span class="Label Label--outline mb-2 Label--prerelease">Pre-release</span>
<span class="Label Label--outline mb-2 Label--latest"><a href="/zeit/hyper/releases/latest">Latest release</a></span>
````

**Comment by Mottie** [comment]
Hi @gluons!

This should have been fixed within the past week to for #574. Odd that it appears that you're using the most up-to-date style. Please check again.

**Comment by Mottie** [comment]
Oh... it's only in the master branch. I'll update USO in a minute.

**Comment by gluons** [comment]
Ops! I haven't known that this issue has been reported. Sorry.

**Comment by Mottie** [comment]
No worries! All done.

**Comment by gluons** [comment]
Thank you very much. You're so fast. Superb! 🎉
