### ISSUE TITLE
The CodeMirror theme is messed up

### ISSUE THREAD

**Issue by RaitaroH** [StylishThemes/GitHub-Dark#577]
* **Browser**:
Firefox Nightly 59, Waterfox 56
* **Operating System**:
KDE Neon
* **Screenshot**:
![screenshot_20171229_180654](https://user-images.githubusercontent.com/19552720/34441423-5d2d7f4c-ecc4-11e7-9315-5057a033a954.png)

* **HTML of the section where the issue occurs**:
Any

Managed to fix it with the following options:
![screenshot_20171229_180947](https://user-images.githubusercontent.com/19552720/34441439-74ffa2da-ecc4-11e7-9f68-1e86e6679fd2.png)

It seems that Jupyter Syntax theme is the problem.

**Comment by Mottie** [comment]
Thanks @RaitaroH!

It looks like the base16 Ocean Dark is the only theme that would cause this problem; but I'll go ahead and fix all the Jupyter themes to only specifically apply to Jupyter pages.

**Comment by RaitaroH** [comment]
I see. Thanks @Mottie
