### ISSUE TITLE
Projects: In progress section of progress bar is not purple

### ISSUE THREAD

**Issue by auscompgeek** [StylishThemes/GitHub-Dark#578]
**Browser**: Firefox 57
**Operating System**: Arch Linux
**Screenshot**:
![github](https://user-images.githubusercontent.com/128854/34634986-b4c025b0-f2dd-11e7-8a75-daf632b1b6be.png)
![github-dark](https://user-images.githubusercontent.com/128854/34634992-c1f7c38c-f2dd-11e7-8748-81a15bb726fa.png)
**HTML of the section where the issue occurs**:
```html
<div class="tooltipped tooltipped-s" aria-label="21 done / 7 in progress / 21 to do">
  <span class="progress-bar progress-bar-small">
    <span class="progress d-inline-block bg-green" style="width: 43%">&nbsp;</span>
    <span class="progress d-inline-block bg-purple" style="width: 14%">&nbsp;</span>
  </span>
</div>
```

Looks like the autogenerated rule for `.bg-purple` is being overridden by the `.progress-bar .progress` rule. Unfortunately it doesn't look like we can just remove the latter selector, because it affects the milestone progress bar.

**Comment by Mottie** [comment]
Hi @auscompgeek!

Thanks for reporting this problem, I'll have it fixed shortly.

**Comment by silverwind** [comment]
Quite a tricky issue as GitHub is using `!important` on `.bg-purple`. A proper fix would be that the generator should emit non-important styles, but that would likely break a lot of things.
