### ISSUE TITLE
File icons are too dark

### ISSUE THREAD

**Issue by MechaLynx** [StylishThemes/GitHub-Dark#579]
* **Browser**: Firefox 58.0b15x32
* **Operating System**: Win7x64
* **Screenshot**: 

![2018-01-11 16_32_24-58 0-win-x86-32 _ 20180108140638 stylishthemes_github-dark_ dark github style](https://user-images.githubusercontent.com/8427257/34830682-4d6843ac-f6ed-11e7-8aa8-9a61e6125e9a.png)

I'm using the `user.css` version on Stylus.

I'd fix it myself but I don't have the time to look into it at the moment. If it isn't picked up I'll do it once I can.

**Comment by Mottie** [comment]
Hi @MechaLynx!

Thanks! I was just about to fix it 😸
