### ISSUE TITLE
The issue label automatic labelstyle font color doesnt work.

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#580]
* **Browser**: Firefox 58
* **Operating System**: win 10
* **Screenshot**:

![with](https://user-images.githubusercontent.com/31389848/35427310-70d214b6-0260-11e8-9a19-93ac3718652d.PNG)

![without](https://user-images.githubusercontent.com/31389848/35427319-81b804c0-0260-11e8-89c1-15bf92e52240.PNG)

* **HTML of the section where the issue occurs**:

````html
<a href="/StylishThemes/GitHub-Dark/issues?q=is%3Aissue+is%3Aopen+label%3Aupstream-bug" class="d-inline-block IssueLabel v-align-text-top labelstyle-aa1111 linked-labelstyle-aa1111" style="background-color: #aa1111; color: #ffffff" title="upstream-bug">upstream-bug</a>
````

**Comment by the-j0k3r** [comment]
My bad , seems the auto-update didnt actually come through.

**Comment by silverwind** [comment]
These new labels are so bad. They have inconstent padding in issue list vs. issue view and they aren't vertically centered. I ought to add a hack or two if GitHub doesn't fix them in the next days.

**Comment by the-j0k3r** [comment]
> I ought to add a hack or two if GitHub doesn't fix them in the next days.

if? 🎪 🤡

**Comment by silverwind** [comment]
Looks like someone is actually working on them, I noticed a few changes already. Let's hope :)

**Comment by the-j0k3r** [comment]
🤞

**Comment by Mottie** [comment]
It's fitting that our two labels show the issue so prominently.
