### ISSUE TITLE
White border on profile image (details in screenshot)

### ISSUE THREAD

**Issue by raniesantos** [StylishThemes/GitHub-Dark#582]
![ghd](https://user-images.githubusercontent.com/8528269/35619249-56b812ae-06b8-11e8-856b-98e05f36c7f4.jpg)

**Comment by Mottie** [comment]
Hi @raniesantos!

This was fixed in https://github.com/StylishThemes/GitHub-Dark/commit/33030758a930aa13ef38fc0d929c97aa420b54c9. It is now available in the usercss and on userstyles.org.
