### ISSUE TITLE
Inverted avatar in Insights > Network

### ISSUE THREAD

**Issue by RaitaroH** [StylishThemes/GitHub-Dark#583]
* **Browser**:
Firefox
* **Operating System**:
KDE Neon
* **Screenshot**:
![screenshot_20180131_194045](https://user-images.githubusercontent.com/19552720/35638031-a7e03e94-06be-11e8-9935-55e0fcfce5c6.png)

* **HTML of the section where the issue occurs**:

````
https://github.com/OpenUserCSS/OpenUserCSS-DeepDark/network
````

**Comment by silverwind** [comment]
This is a known issue and unsolvable because the network graph uses the `<canvas>` element which can only be targeted as a whole by CSS. The only other option would be to not style this element at all, which would leave a white box, something probably even less desirable.

**Comment by AfroThundr3007730** [comment]
JavaScript is the only method I know of for styling elements in a canvas, but that is probably outside the scope of a userstyle. Probably doable, but the juice most likely isn't worth the squeeze on this one.

**Comment by the-j0k3r** [comment]
You can handle it in GitHub Dark Script.
