### ISSUE TITLE
Ajax Pagination in issues

### ISSUE THREAD

**Issue by phit** [StylishThemes/GitHub-Dark#585]
* **Browser**: FF60/Chrome65
* **Operating System**: Win10
* **Screenshot**: https://i.imgur.com/rVFwVTE.png [example](https://github.com/MinecraftForge/MinecraftForge/pull/4666#issuecomment-356141682)

* **HTML of the section where the issue occurs**:
https://gist.github.com/phit/97870c72d788fbfc107e3cf87391040b

```
.ajax-pagination-form.js-ajax-pagination.progressive-timeline-loader-container.pagination-loader-container.mt-4.mb-4.ml-0.text-center {
    background-color: transparent !important;
}
```

this seems to at least remove the black bar, but still leaves the white zigzag line from

```
.pagination-loader-container {
    background-color: #fff;
    background-image: url("/images/modules/pulls/progressive-disclosure-line@2x.png");
    background-repeat: repeat-x;
    background-position: left center;
    background-size: 32px;
}
```

**Comment by Mottie** [comment]
Hi @phit!

I fixed this in https://github.com/StylishThemes/GitHub-Dark/commit/4eb413710f2c2529613bfa73223a22960c5f17cc - it's just not available on userstyles, or in the usercss yet.

**Comment by phit** [comment]
should've checked the recent commits first, my bad!

**Comment by Mottie** [comment]
No worries! 😸
