### ISSUE TITLE
White box on top of the repo actions

### ISSUE THREAD

**Issue by targos** [StylishThemes/GitHub-Dark#587]
* **Browser**: Google Chrome Version 64.0.3282.167
* **Operating System**: Fedora 27
* **Screenshot**:

![image](https://user-images.githubusercontent.com/2352663/36467939-765fd9b4-16e1-11e8-8d26-2112f86d6b4f.png)

* **HTML of the section where the issue occurs**:

![screenshot from 2018-02-21 08-31-15](https://user-images.githubusercontent.com/2352663/36467964-a07b2d20-16e1-11e8-8dbc-c4b9a02c2e06.png)

````html
<div class="js-socket-channel js-updatable-content" data-channel="repo:27193779:post-receive:2352663 repo:29471300:post-receive:2352663" data-url="/nodejs/node/show_partial?partial=tree%2Frecently_touched_branches_list">
  </div>
````

This appeared recently. I don't know if it is due to an update of an extension or GitHub.

**Comment by silverwind** [comment]
I don't see this box, but it could be something from GitHub. Could you check if it shows with your browser extensions disabled?

**Comment by targos** [comment]
It is also present when extensions are disabled but has a height of 0.

I can find this in the inspector:
![image](https://user-images.githubusercontent.com/2352663/36479541-5695fce4-1709-11e8-8410-bc6171d37e91.png)

Still investigating where it could come from...

**Comment by targos** [comment]
It is `refined-github`: https://github.com/sindresorhus/refined-github/blob/baacc31b4c85f3b472a10ca9caef73f3a27796da/source/content.css#L777-L788

**Comment by silverwind** [comment]
Opened https://github.com/sindresorhus/refined-github/issues/1106.

Not sure what to do about it. We could change the extension's white background but that would not look good on textured backgrounds. Waiting for feedback on that issue.

**Comment by silverwind** [comment]
Overriding with transparent background looks like this:

<img width="530" alt="screen shot 2018-02-21 at 19 21 02" src="https://user-images.githubusercontent.com/115237/36497715-044a8b5a-1734-11e8-8206-3d084da61f08.png">

**Comment by bfred-it** [comment]
If you set the background color in a CSS variable Refined GitHub can probably pick it up and use it as background. Alternative solutions welcome

**Comment by silverwind** [comment]
Worked around the issue by making the background transparent.

IMHO, a proper fix must come out of https://github.com/sindresorhus/refined-github/issues/1106.

**Comment by silverwind** [comment]
I think this is the best we an do about this for now. Follow https://github.com/sindresorhus/refined-github/issues/1109 for a better solution.

**Comment by targos** [comment]
Thank you
