### ISSUE TITLE
[Suggestion] Italics in blockquotes

### ISSUE THREAD

**Issue by darkred** [StylishThemes/GitHub-Dark#588]
* **Browser**: Chrome 64 and Firefox 58, Stylus 1.2.7
* **Operating System**: win10x64
* **Screenshot**: [Before](https://user-images.githubusercontent.com/723651/36620878-df3ade02-18fd-11e8-9192-eec454e75022.jpg) - [After](https://user-images.githubusercontent.com/723651/36620879-e09a177c-18fd-11e8-88eb-d465d089012d.jpg)

GitHub normally displays blockquotes simply as indented normal text.
I find this style (normal text) very difficult to visually distinguish blockquotes from normal text, 
that's why my suggestion is to use **italics in blockquotes,** 
i.e. something like the following CSS rule (that's what I use): 
_(although I think that my selector `blockquote p` is too generic, and I'm not very experienced in CSS, that's why I didn't make a PR instead)_ :

```
blockquote p {
  font-style: italic;   
}
```

**Comment by silverwind** [comment]
We don't usually strain too far from GitHub's style I think this style should mainly be about color. I don't think that this tweak shouldn't be in our style.

Why don't you write a separate style with this tweak? If you're using Stylus, it's as simple as clicking "Write new style", paste your CSS and hit save. I'd only suggest adding a `!important` to the declaration to make sure it always applies.

**Comment by darkred** [comment]
> Why don't you write a separate style with this tweak? 

That's what I already do, that's I meant with _"that's what I use"_ 
(thanks for the `!important` suggestion nevertheless).

It's just that I find the fact that GitHub doesn't use italics for blockquotes so confusing,
that I thought that my simple tweak, even though it's not about color, might be useful to include in your great style.

**Comment by silverwind** [comment]
You could try to contact them at https://github.com/contact or open an issue about it on https://github.com/isaacs/github/issues, but I'm not sure they would agree.

Nevertheless, I think we could maybe add an style config option for this, @Mottie, what do you think?

**Comment by Mottie** [comment]
We've tried not to add too many opinionated styles to GitHub-Dark, so honestly, I think it would be better to put changes like this in a separate style.

**Comment by silverwind** [comment]
Okay, alright then.
