### ISSUE TITLE
Gradient colors and white line on "Explore" section

### ISSUE THREAD

**Issue by VladimirDev93** [StylishThemes/GitHub-Dark#595]
![untitled](https://user-images.githubusercontent.com/12301022/37560010-8ac5127c-2a30-11e8-8637-387fb3e2c2ae.png)

Yup, there they are.

**Comment by Mottie** [comment]
Hi @VladimirDev93!

Hmm, I'm going to push a change that removes the gradient... maybe it's not the best solution; but it's not a simple case.

Also, I noticed that the container isn't scrollable when GitHub-Dark isn't applied. I wonder if we should change that behavior - @silverwind what do you think?

**Comment by the-j0k3r** [comment]
> Also, I noticed that the container isn't scrollable when GitHub-Dark isn't applied

It is scrollable here for some reason, and, it has gradient applied on the scrollbar edges, this looks really weird + vomitous. :hankey: 

![capture](https://user-images.githubusercontent.com/31389848/37708714-9a7746f0-2cff-11e8-8139-f649b3884dca.PNG)

`<rant>`I really dislike the built in scrollbars in windows, against a dark background they are really piercing and distracting.`</rant>`

**Comment by silverwind** [comment]
Might be a Chrome-specific behaviour that it's not scrollable, but I like it. There is a padding-right issue on the box which is a case of Chrome violating the CSS spec (https://bugzilla.mozilla.org/show_bug.cgi?id=748518). I'll do some tweaks on the page.
