### ISSUE TITLE
Invalid field labels not styled and input icons not visible

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#597]
* **Browser**: Chrome 65
* **Operating System**: Win10
* **Screenshot**:

https://github.com/settings/admin

![image](https://user-images.githubusercontent.com/831974/37813651-75584246-2e3c-11e8-8cd4-7f6baaec9f7e.png)

![image](https://user-images.githubusercontent.com/831974/37813663-8230f6a2-2e3c-11e8-99c9-5ffc60a6d613.png)

* **HTML of the section where the issue occurs**:

````html
<input type="password" name="user[password]" id="user_new_password" data-autocheck-url="/signup_check/password" data-autocheck-authenticity-token="" tabindex="2" required="required" class="form-control is-autocheck-errored" data-com.agilebits.onepassword.user-edited="yes">
````

**Comment by Mottie** [comment]
Hi @xt0rted!

It looks like the invalid css selector (`:not(li.moved)`) mentioned in #589 is invaliding the block that styles the error label color. I think we might need to either separate those invalid rules into a separate block, or ignore them for now. What do you think @silverwind?

I'll work on a fix for the icon.

**Comment by Mottie** [comment]
I ended up removing the troublesome selector in the generate process.

**Comment by silverwind** [comment]
Nice work. So the issue was the the invalid selector invalidated the combined minfied rule?

**Comment by Mottie** [comment]
> So the issue was the the invalid selector invalidated the combined minfied rule

Yep
