### ISSUE TITLE
Tab border top style

### ISSUE THREAD

**Issue by AmirSavand** [StylishThemes/GitHub-Dark#601]
![image](https://user-images.githubusercontent.com/4629328/37865418-32223bec-2f8d-11e8-825a-f2fd28ac944c.png)

Why not also have that orange border top style too? The color can be anything but the border looks really nice, the dark theme should also support it.

**Comment by auscompgeek** [comment]
https://github.com/StylishThemes/GitHub-Selected-Tab-Color

**Comment by AmirSavand** [comment]
@auscompgeek looks cool, but why is it a different stylish theme?

**Comment by Mottie** [comment]
Hi @AmirSavand!

We're trying to keep the main GitHub-Dark repository as un-opinionated as possible. So we split this style out because it adds tab color highlighting to so much more than just the main tabs.

**Comment by AmirSavand** [comment]
@Mottie ok so you can close this I guess.
