### ISSUE TITLE
Background color conflict with refined github in review comments

### ISSUE THREAD

**Issue by targos** [StylishThemes/GitHub-Dark#603]
* **Browser**: Chrome 65
* **Operating System**: Windows 10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/2352663/38305382-006d2f02-380d-11e8-95b6-78607ad2ffcc.png)

Link: https://github.com/nodejs/node/pull/19605#discussion_r179105528

* **HTML of the section where the issue occurs**:

````html
<div id="discussion_r179105528" class="review-comment previewable-edit js-comment js-task-list-container unminimized-comment js-reorderable-task-lists reorderable-task-lists timeline-item-highlight" data-body-version="d5aed4c6ac7381f3311ac21b66dd5400">
    </div>
````

![image](https://user-images.githubusercontent.com/2352663/38305562-8e6040d8-380d-11e8-95b4-454432a3d86e.png)

Rules added in refined github: https://github.com/sindresorhus/refined-github/pull/1182

**Comment by Mottie** [comment]
Hi @targos!

Thanks for reporting this problem. This'll get fixed in the next update.
