### ISSUE TITLE
Submitting modified version of Github-Dark - purple color variation

### ISSUE THREAD

**Issue by wltjr** [StylishThemes/GitHub-Dark#606]
I have a slightly tweaked version of the Github-Dark, where I replaced the core color with purple.

I would like to share this modified version. Not sure if there is some means for me to contribute these modifications, or provide the color for my variation. Thank you!

![shot-2018-04-10_14-59-29](https://user-images.githubusercontent.com/12835340/38577762-d9b54350-3ccf-11e8-8cd2-72e15cf130ff.jpg)
![shot-2018-04-10_15-02-16](https://user-images.githubusercontent.com/12835340/38577880-31e9093a-3cd0-11e8-8fb2-091caf3de89e.jpg)

**Comment by wltjr** [comment]
Hi @Mottie 
I assume that would produce some config file or something I can carry over to many systems? The thing is I need to install it on many. It seemed easier to have it as a custom style that I could select/export/import. And carry over to other systems that way via automation.

**Comment by wltjr** [comment]
@Mottie ps, I made one for [Travis-CI](https://github.com/Obsidian-StudiosInc/Travis-CI-Dark-Purple) as well, still a wip, that could be furthered. Not sure if that is something you all maybe interested in having. I can help maintain that. Just seemed like you all had most of the common ones. I am also making one for [Sonarcloud.io](https://sonarcloud.io). Pretty basic css for now, no image replacements patterned backgrounds etc. But not opposed to that stuff. Just trying to save my eyes. Flipping from black and white a lot is noticeable.

**Comment by wltjr** [comment]
@Mottie also back to my original comments, it maybe a style others want as well like say [Gentoo](https://gentoo.org/), as purple is part of Gentoo, as seen in like [Gentoo's Bugzilla](https://bugs.gentoo.org/). Though my use is for my company and predates my use of Gentoo. The purple was just a universe saying we were meant for each other thing.

**Comment by silverwind** [comment]
I think a [custom build](https://github.com/StylishThemes/GitHub-Dark/wiki/Build) might suit your needs. You clone the repo, modify a JSON file and get a built file with your custom color.

Regarding your styles: I wouldn't be opposed to hosting them on our organization if they reach a certain quality level and are maintained. Looking at the screenshit of the Travis style, I'd say it needs a bit more work (white borders are too bright, green text should probably be gray).

**Comment by wltjr** [comment]
For the most part I have things for my needs. I was going to host a copy somewhere and maybe upload to [userstyles.org](userstyles.org). It was mostly for others sake I was seeking to share. 
I am always good for my needs, just trying to share for others.

Regarding my Travis style. White borders are carried over from their default, I may darken, but some what like the contrast. It was a very initial start open to feedback, changes, etc. I still have more things to change from their defaults. Regarding the green text, not sure if you understand Travis, but that changes color based on the [build status](https://travis-ci.org/Obsidian-StudiosInc/entrance/builds). Scroll down and you will see. That is how Travis is normally. If anything maybe darker green/red. But gray means [canceled](https://travis-ci.org/Obsidian-StudiosInc/os-xtoo/branches).

Here is the initial one for [SonarCloud](https://userstyles.org/styles/158324/sonarcloud-dark-purple) as well. Colors there will likely remain for contrast. Though maybe darker shades of green/red, etc.

**Comment by the-j0k3r** [comment]
@wltjr 
see https://github.com/Obsidian-StudiosInc/Travis-CI-Dark-Purple/issues/1

I suggest you make the purple color a user selectable thing, I like part of your style but the purple is something personal I prefer to use some color that makes a good transition from Github-Dark to Travis, Appveyor whatever.

That said I submitted some fixes which should give more coverage to your style, this doesn not include and logged in to travis changes, I did not cover that areas, but everything else you missed, I done.

There are still a few elements that are not styled properly however, like .jobs-list hover and normal style and other tables like that, but I fixed what I could.

Enjoy.

**Comment by Mottie** [comment]
I'm going to go ahead and close this issue. You shouldn't need to manually modify our GitHub-Dark style, but you are more than welcome to do it.

**Comment by wltjr** [comment]
No worries, I will continue to tweak it per my needs. I modified the base color per the advanced settings. But other elements remained blue I had changed to purple. Plus some things that have blue colors I rather not be blue or purple. Like all my comments here now have a blue header. Default github style is all the same color for headers. The blue box around topics. Which the default github style has nothing around those. The brown for messages I really dislike. Things that deviate from the default github theme rather than inverting.

I will likely have to make and maintain my own version. Either a fork or from scratch, as somethings I do not care about. Like the patterned background. That could be a solid black. Just different tastes.

**Comment by silverwind** [comment]
Yes, there is a favoritism towards blue in certain cases which can not easily be fixed because of CSS limitations (`backdrop-filter` support is needed for some cases) and in some cases personal preference.

If you want to start from scratch, take a look at [generate.js](https://github.com/StylishThemes/GitHub-Dark/blob/master/tools/generate.js). I imagine 90% of the work can be done by simply remapping colors and it's a huge help when GitHub updates.

**Comment by wltjr** [comment]
@silverwind blue seems most common. I run Enlightenment desktop and it is also their base color. Used on the desktop and [website](http://www.enlightenment.org/). Which is why I have my own theme for that as well, [Eminence](https://github.com/Obsidian-StudiosInc/eminence). Though not using Eminence theme for the DM I am working on [Entrance](https://user-images.githubusercontent.com/12835340/31921581-1c2f0d7c-b83e-11e7-8d90-1dac94ae8e5c.jpg). Thus the blue in Entrance screenshots, also to give users realistic expectation on default look.

Eminence also has a [gtkrc](https://github.com/Obsidian-StudiosInc/eminence/blob/master/src/gtkrc-2.0) file for GTK apps, though blue remains there in some cases. That uses Adwaita Dark for GTK, which also has a base color of blue for some things for both light and dark. I see blue used on many sites as well as various themes. I think studies have shown it to be the color we most favor, living on a blue planet :earth_americas: 

Thanks for the suggestion on generate.js I will check that out. Though I am semi familiar with starting from scratch in my own crude simplistic ways for [Travis-CI](https://userstyles.org/styles/158318/travis-ci-dark-purple) and [SonarCloud](https://userstyles.org/styles/158324/sonarcloud-dark-purple). The CSS in each repo, [travis css](https://github.com/Obsidian-StudiosInc/Travis-CI-Dark-Purple/blob/master/travis-ci-dark-purple.css) and [sonar](https://github.com/Obsidian-StudiosInc/SonarCloud-Dark-Purple/blob/master/sonarcloud-dark-purple.css), is rather straight forward and basic. Need to refactor Sonar like Travis. Fairly easy to add more or modify stuff as those sites change. Hopefully not to often. Still more to do in each. I just whipped those up and modify as time permits, or things bug me enough to act  :smiling_imp:

Not sure what I will do for Github. This theme seems pretty complex, and not sure I want to maintain my changes on top of such. Maybe easier to just start over my way. Thanks again for the suggestions!
