### ISSUE TITLE
Feature Request: schedule theme

### ISSUE THREAD

**Issue by stevenvachon** [StylishThemes/GitHub-Dark#611]
I use a theme-scheduler plugin for my SublimeText which applies a light theme during the day and a dark theme in the evening. It'd be great if I could do the same with this GitHub theme.

**Comment by Mottie** [comment]
Hi @stevenvachon!

GitHub-Dark is pure CSS, so the only way to schedule anything is with JavaScript.

Alternatives:
* Theme managers (e.g. Stylus & Stylish) make it pretty easy to toggle themes on & off manually.
* Stylus does have a enhancement [request to add scheduling](https://github.com/openstyles/stylus/issues/51), but it hasn't shown any progress in a while.
* Install [f.lux](https://justgetflux.com/). This program doesn't change the theme, it alters your monitor screen colors depending on the time of day.
* We could modify the [GitHub-Dark userscript](https://github.com/StylishThemes/GitHub-Dark-Script) to turn on/off at specific times, but you'd have to install a different browser extension... and we'd have to add the enhancement.

**Comment by stevenvachon** [comment]
I have f.lux, but yellowing/reddening the screen is not the same.

Where can I find the Stylish options for scheduling? I'm using macOS

**Comment by Mottie** [comment]
Neither Stylus or Stylish have scheduling options.

**Comment by stevenvachon** [comment]
Ok, thank you. Feel free to close this if it's not possible or desirable to implement this in the userscript.

**Comment by Mottie** [comment]
Closing this issue... I opened an enhancement request in the [script repo](https://github.com/StylishThemes/GitHub-Dark-Script/issues/48).
