### ISSUE TITLE
Usernames are truncated even when not too long

### ISSUE THREAD

**Issue by AlexandreBonneau** [StylishThemes/GitHub-Dark#620]
* **Browser**: Firefox `61.0b7`
* **Operating System**: Linux Debian Stretch
* **Screenshot**:
![2018-05-09 github change - ugly truncated usernames](https://user-images.githubusercontent.com/7248877/40452379-55c0662c-5e7d-11e8-8ab4-a419bb95cb9c.png)

* **HTML of the section where the issue occurs**:

````html
<h3 class="timeline-comment-header-text f5 text-normal">
    <strong class="css-truncate">
  <a class="author text-inherit css-truncate-target" data-hovercard-user-id="7248877" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="/AlexandreBonneau" aria-describedby="hovercard-aria-description">AlexandreBonneau</a>
    </strong>
    commented
    <a href="#issuecomment-391502286" class="timestamp"><relative-time datetime="2018-05-23T21:28:18Z" title="23 mai 2018 à 11:28 UTC−10">7 minutes ago</relative-time></a>
  </h3>
````

Recently Github pushed a changed that truncate the usernames in the comment header even when those are not *that* long, resulting in a bad UX, and hard time to identify who's talking to who.

The faulty css class is `.css-truncate-target`; if you remove it you solve the problem.
Perhaps there is a better way to retrieve the old non-truncate behavior?

**Comment by AlexandreBonneau** [comment]
This is great!
Thanks @silverwind for this hyper-speed fix!!

**Comment by silverwind** [comment]
No problem. You might want to [contact GitHub](https://github.com/contact) about it, they are usually pretty responsive to this kind of feedback.

**Comment by AlexandreBonneau** [comment]
I did few weeks ago, and since nothing changed, I posted here :)
