### ISSUE TITLE
Default theme in usercss version 

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#621]
@Mottie I noticed that the usercss version does not use the default theme (twilight) like in `github-dark.css`, would you agree changing it?

**Comment by Mottie** [comment]
Usercss selections don't allow you to choose a default option; it always picks the first option. I've requested this feature to be added to Stylus, but it hasn't been opened as an issue.

**Comment by silverwind** [comment]
Ah, but we can move Twilight first, right?

**Comment by Mottie** [comment]
Yeah, we could

**Comment by silverwind** [comment]
Done :)
