### ISSUE TITLE
New comment edit dropdown and diff popup

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#623]
GitHub just rolled out the ability to view comment edits.

Issues with it:
- The existing `edit` dropdown is no longer visible with the dark theme
- Edits made before this went live show in a blueish color (you can't view the changes for these)
- Plain text in the diff popup is blueish
- Delete revision menu option should be red
- Edit highlights have a background color with the dark theme but not by default

* **Browser**: chrome
* **Operating System**: win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/40514449-2b8e2a88-5f77-11e8-9754-fbe0d20e6f02.png)

![image](https://user-images.githubusercontent.com/831974/40514460-34affa4c-5f77-11e8-8442-7e57f9769a32.png)

![image](https://user-images.githubusercontent.com/831974/40514483-410d292c-5f77-11e8-8a79-3731b8ec3830.png)

![image](https://user-images.githubusercontent.com/831974/40514528-6dd99e4a-5f77-11e8-8d3a-0c237c56168a.png)

![image](https://user-images.githubusercontent.com/831974/40514540-79bb6a68-5f77-11e8-8c79-f92fe0196e05.png)

* **HTML of the section where the issue occurs**:

Too much html to copy but you can view it on my comment from earlier https://github.com/StylishThemes/GitHub-Dark/issues/622#issuecomment-391768122

**Comment by Mottie** [comment]
Hey @xt0rted!

Thanks for reporting this.

@silverwind, it looks like this commit - https://github.com/StylishThemes/GitHub-Dark/commit/46bfed89dea399c464f88f72fa7d4695dfbe33d7 - added the following css:

```css
.issues-listing .js-notice {
  display: none !important;
}
```

Which is applying to the "edited" summary:

```html
<details class="details-reset js-dropdown-details d-inline-block dropdown">

  <summary class="btn-link no-underline text-gray dropdown-toggle js-notice">
    <div class="position-relative">
      <span>edited</span>
      <svg>...</svg>
    </div>
  </summary>

  <div class="anim-scale-in">...</div>
</details>
```

Please take a look.

**Comment by Mottie** [comment]
Also @xt0rted, I wasn't able to find the options dropdown that would allow you to delete a revision from history... I edited a few old comments and it never showed up.

**Comment by xt0rted** [comment]
@Mottie the edit dropdown on my recently edited issues/comments is no longer clickable even with GitHub Dark disabled so I can't check this right now

**Comment by silverwind** [comment]
I removed that selector, it's too broad. Will check later if I can get a better matching one for those popups on top of issues/pull lists.

**Comment by xt0rted** [comment]
@Mottie this feature was just turned back on. To get to the delete option edit a comment at least twice, and then select the oldest revision. In the history modal the options dropdown should include a delete option. According to the docs you can't delete the most recent revision, so that might be why you weren't seeing it.

Edits made while this was disabled for non staff members won't show diffs, so it's probably best to just create a couple new edits to a comment to guarantee the diff history is displayed.

**Comment by Mottie** [comment]
I'm still not seeing the "options" dropdown menu.

**Comment by xt0rted** [comment]
This is what I'm seeing
![gif](https://user-images.githubusercontent.com/831974/40693539-de1fdfe0-6385-11e8-937c-895cda72636d.gif)

**Comment by Mottie** [comment]
Ahh, I never clicked on the menu item... ok, it's been fixed. I just updated, so this'll get included in the next update.

**Comment by silverwind** [comment]
Looking good. I see that texts in that menu are in a slight shade of blue while GitHub uses a lighter gray. @Mottie would you agree changing it to grey?

**Comment by silverwind** [comment]
Should all be fixed.
