### ISSUE TITLE
Missing highlighting for code blocks in posts on developer.github.com

### ISSUE THREAD

**Issue by ght** [StylishThemes/GitHub-Dark#624]
## Symptom
The highlighted code snippets in GitHub Developer posts are not highlighted properly, making tokens that are colored dark by default hard to read. 

For an example, see [Request further actions from a check run](https://developer.github.com/changes/2018-05-23-request-actions-on-checks/).

## Underlying Problem
As far as my short debugging shows, the likely cause is that the selectors in [`themes/jupyter/*.css`](../tree/bdb4da6/themes/jupyter) match only `#notebook .highlight …, body.api .highlight …` and the body has `class="blog"` on those pages.

## Proposed Fix
Adding `body.blog .highlight …` to all selectors that have `#notebook .highlight …, body.api .highlight …` fixes the broken highlighting. This might not be an ideal solution though, since there are >50 occurrences, so total size would increase by _~1.5KiB_.

Instead simplifying the selectors to just `.highlight …` would fix the problem too and reduce the size by a comparable amount, but there was probably a reason why the selectors were made more specific.

In [github-dark.css](../blob/bdb4da6/github-dark.css#L4551) the second of those options is already implemented.

## Screenshot
![image](https://user-images.githubusercontent.com/248399/40686331-43d28566-6397-11e8-9d70-ffb377a9f842.png)

## HTML of the Section from above Screenshot
```html
<li>
<p>The integrator indicates that they can apply a further action. We designed these <code>actions</code> to be flexible for the integrator to specify which actions <em>they</em> can offer the user.</p>

<p>For example, a linter type app with the ability to fix any failures found includes a "Fix" option, along with the check run input in the new <code>actions</code> input parameter:</p>

<pre class="highlight highlight-json"><code><span class="s2">"actions"</span><span class="err">:</span><span class="w"> </span><span class="p">[{</span><span class="w">
    </span><span class="nt">"label"</span><span class="p">:</span><span class="w"> </span><span class="s2">"Fix"</span><span class="p">,</span><span class="w">
    </span><span class="nt">"description"</span><span class="p">:</span><span class="w"> </span><span class="s2">"Let us fix that for you"</span><span class="p">,</span><span class="w">
    </span><span class="nt">"identifier"</span><span class="p">:</span><span class="w"> </span><span class="s2">"fix_errors"</span><span class="w">
</span><span class="p">}]</span><span class="w">
</span></code></pre>
</li>
```

**Comment by Mottie** [comment]
Hi @ght!

Yeah, it looks like we missed those pages. I'll get this fixed ASAP.
