### ISSUE TITLE
Problem emoji in username overviw tab.

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#628]
The issue occurs in the user overview tab https://github.com/**<username>**?tab=overview

The problem is the `:dove:` and `:peace_symbol:`  only in that page, the actual post the emoji display perfectly OK.

* **Browser**: FF 60.0.1
* **Operating System**: Windows 10
* **Screenshot**:

Problem in overview tab.
![dove-peace](https://user-images.githubusercontent.com/31389848/41030241-c5a0a77e-6975-11e8-9f89-b7aa191eaada.PNG)

OK in main post its OK
![ok-in-post](https://user-images.githubusercontent.com/31389848/41031298-356116fa-6978-11e8-854c-530c572ba907.PNG)

> ### Note
> I tried fixing this adding
```css
  [alt=":dove:"], [alt=":peace_symbol:"]
```
```css
  [alias="dove"], [alias="peace_symbol"] 
```
```css
  g-emoji[fallback-src$="1f54a.png"], g-emoji[fallback-src$="262e.png"]
```
into  https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L2239-L2280

But this breaks both on main post and breaks the `:peace_symbol:` on both sides, but the dove is fixed on overview tab :( AH!

So thinking out-loud- the thought is to exclude the overview tab, but Ive no idea how.

* **HTML of the section where the issue occurs**:

````html
<div class="text-gray mb-0 mt-2">
          <p>The <code>--disable-all: #d62929;</code> has to stay really. <g-emoji class="g-emoji" alias="dove" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f54a.png"><img class="emoji" alt="dove" src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f54a.png" width="20" height="20"></g-emoji> <g-emoji class="g-emoji" alias="peace_symbol" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/262e.png"><img class="emoji" alt="peace_symbol" src="https://assets-cdn.github.com/images/icons/emoji/unicode/262e.png" width="20" height="20"></g-emoji>
<a target="_blank" href="https://user-images.githubusercontent.com/31389848/40885704-7edba0ea-6723-11e8-831c-18cfdadd47ee.PNG"></a>
The <code>--no-match: #FFC700;</code> I swapped instead of <code>#d99b45<span style="background-color: #d99b45; height: 0.8em; width: 0.8em;" class="ml-1 d-inline-block v-align-middle Box border-black-fade"></span></code> for an already existing color from <code>/*Ye…</code></p>
        </div>
````

**Comment by Mottie** [comment]
Hi @the-j0k3r!

It looks like our `div[id^="contribution-created"] img` selector is causing the problem. It was meant to invert the "First Pull Request" event image in the overview. I'll change it to specifically target that image.
