### ISSUE TITLE
kbd tags are almost indistinguishable from code tags

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#629]
* **Browser**: Chrome 67
* **Operating System**: Win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/41137534-8a08da58-6aa9-11e8-8961-fb2815bd9027.png)

![image](https://user-images.githubusercontent.com/831974/41137520-7ac51318-6aa9-11e8-98a8-8a50cbb8192f.png)

KBD: <kbd>F5</kbd>

Code: `F5`

* **HTML of the section where the issue occurs**:

````html
<kbd>F5</kbd>
````

**Comment by the-j0k3r** [comment]
@xt0rted 3rd time the charm? https://github.com/StylishThemes/GitHub-Dark/commit/4d8d9937988afbd8b74d1cb5d571cdeac9e9e908 :=)
