### ISSUE TITLE
auto completion of issue reports selection is broken.

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#645]
* **Browser**: ff 66.0.2
* **Operating System**: win 10 por
* **Screenshot**:

![capture](https://user-images.githubusercontent.com/31389848/41601173-a293d6f2-73cf-11e8-9853-adfabd59b6ac.PNG)

* **HTML of the section where the issue occurs**:

Cant right click it
````html

````

**Comment by Mottie** [comment]
Related to #622... lets keep it all in one place.

**Comment by Mottie** [comment]
Errr #644.

**Comment by the-j0k3r** [comment]
LO⅃
