### ISSUE TITLE
Post/comment is edit option unstyled

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#648]
* **Browser**: sigh... FF 66.0.2
* **Operating System**: Winblows 10 Pro bugged version 1709
* **Screenshot**:

![capture](https://user-images.githubusercontent.com/31389848/41608343-35842f06-73e0-11e8-803d-01ba1b27cebe.PNG)

* **HTML of the section where the issue occurs**:

````html
<summary class="btn-link no-underline text-gray dropdown-toggle js-notice">
        <div class="position-relative">
          <span>
              edited
          </span>
          <svg height="11" class="octicon octicon-triangle-down v-align-middle" viewBox="0 0 12 16" version="1.1" width="8" aria-hidden="true"><path fill-rule="evenodd" d="M0 5l6 6 6-6H0z"></path></svg>
        </div>
      </summary>
````

**Comment by xt0rted** [comment]
This is coming from `.dropdown-toggle`

**Comment by Mottie** [comment]
Fixed in master... it'll be available in the next update. We need to see if there are other minor issues lurking in the <del>dark</del> light!
