### ISSUE TITLE
Github projects - dropdown toggle

### ISSUE THREAD

**Issue by ravkr** [StylishThemes/GitHub-Dark#649]
* **Screenshot**:
![zrzut ekranu z 2018-06-19 19-08-41](https://user-images.githubusercontent.com/3875202/41612805-3cbe5dd2-73f4-11e8-9d5e-c82d3bba3a8c.png)
![zrzut ekranu z 2018-06-19 19-08-33](https://user-images.githubusercontent.com/3875202/41612806-3cee8980-73f4-11e8-9366-4270467704ee.png)

* **HTML of the section where the issue occurs**:
````html
<button class="text-gray-light btn-octicon p-1 dropdown-toggle js-menu-target selected" type="button" aria-label="Column menu" aria-expanded="true" aria-haspopup="true">
    <svg class="octicon octicon-kebab-horizontal" viewBox="0 0 13 16" version="1.1" width="13" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M1.5 9a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3zm5 0a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3zM13 7.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"></path></svg>
  </button>
````

**Comment by Mottie** [comment]
Thanks @ravkr!

Fixed in master, update to usercss/userstyle.org pending other issues. See #648.

**Comment by Mottie** [comment]
Hmm, maybe that would look better with a transparent background.
