### ISSUE TITLE
really blinding blue button

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#651]
* **Browser**: FF 66.0.2 blablabla
* **Operating System**: winblows 10 bild the build 1709
* **Screenshot**:

![capture](https://user-images.githubusercontent.com/31389848/41628149-2ae03f78-741b-11e8-8cbf-f7579088b06b.PNG)

* **HTML of the section where the issue occurs**:

````html
<form action="/settings/security/delegated-account-recovery" accept-charset="UTF-8" method="get"><input name="utf8" value="✓" type="hidden">
            <input name="provider_origin" value="https://www.facebook.com" type="hidden">
            <input src="https://assets-cdn.github.com/images/modules/dar/store-token-with-facebook.png" width="236" type="image" height="34">
</form>
````

**Comment by the-j0k3r** [comment]
This is probably not a bug, but WHY would anyone trust facebook with security?

**Comment by Mottie** [comment]
Crazy that they're using an input as an image... not much we can do about it. Here's what it looks like inverted & hue rotated:

![](https://user-images.githubusercontent.com/136959/41628324-9aff0e06-73e9-11e8-9447-7e3e56e85f9f.png)

**Comment by the-j0k3r** [comment]
lol invert and hue-rotate are not the only tricks in the bag.

try: filter: grayscale/contrats and brightness if you need it.

**Comment by Mottie** [comment]
And just because... here it is without a width restriction LOL

![](https://assets-cdn.github.com/images/modules/dar/store-token-with-facebook.png)

**Comment by the-j0k3r** [comment]
![capture](https://user-images.githubusercontent.com/31389848/41628462-8865b7e4-741c-11e8-9e53-aa4b0c9f001f.PNG)


```filter: grayscale(100%) contrast(80%) !important```

**Comment by Mottie** [comment]
Reusing existing selectors...

**Comment by the-j0k3r** [comment]
neat, grayscale 30% also good :

**Comment by the-j0k3r** [comment]
brightness 75% is like 25% more wtf. :) hahaha good think I never go there to trust facebook with my security.
