### ISSUE TITLE
Duplicate font Menlo.

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#655]
* **Browser**: NA
* **Operating System**: NA
* **Screenshot**: NA

Both Userstyles and The UserCSS version add an advanced configuration that adds Menlo font. Grrreat :)

https://github.com/StylishThemes/GitHub-Dark/blob/73f78d23a1b853267ba46a4f781464a45eb61f28/github-dark.user.css#L174

![capture](https://user-images.githubusercontent.com/31389848/41659829-49890c76-7492-11e8-89af-04c066d63d2c.PNG)

I dont understand this because its already hardcoded, so is this an oversight or?

UserCSS https://github.com/StylishThemes/GitHub-Dark/blob/73f78d23a1b853267ba46a4f781464a45eb61f28/github-dark.user.css#L1209

Regular https://github.com/StylishThemes/GitHub-Dark/blob/73f78d23a1b853267ba46a4f781464a45eb61f28/github-dark.css#L1017

**Comment by silverwind** [comment]
The style must still work when the placeholder is not replaced, the other fonts act as a fallback. I don't think we can solve the potential duplication, browsers certainly don't care.

**Comment by the-j0k3r** [comment]
Alright.
