### ISSUE TITLE
Question: selecting bg in the UserCSS version.

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#656]
So I was testing your userCSS version, great and all, but... HOW do I chnage the background like you do in userstyles, the only option is to paste the URL but I want one of the default backgrounds.

So which hoops must I jump for this, except grabbing the url from userstyles version and paste it in there.

**Comment by silverwind** [comment]
Default backgrounds are here, you can link to the raw version:

https://github.com/StylishThemes/GitHub-Dark/tree/master/images/backgrounds

Not sure how to improve the usercss experience.

**Comment by Mottie** [comment]
It's complicated... the usercss settings can't be nested.

I just tested the following method, and it works great, but would this interface be confusing to users?

The "Background image [wrap in url()]" entry would be replaced with a select, and a new entry "Custom Background; include url()" is added below it. It will *only* work if the "Custom" option is selected in the dropdown

![](https://user-images.githubusercontent.com/136959/41678464-c2af8a3c-7490-11e8-937d-ce982ba0a7f9.png)

I thought about changing the text to "> Custom; include url()" but that might be more confusing...

![](https://user-images.githubusercontent.com/136959/41678605-1b9ccbc8-7491-11e8-991b-cb14abd6a5c1.png)

**Comment by the-j0k3r** [comment]
Na that interface is good. :) Most of all its simple.

IDK about using url vs URL in label tbh for custom option but the rest looks good.

**Comment by Mottie** [comment]
You can't really drop the wrapping `url()` because that's the way we have things set up from when the userstyle was first modified to include options. We could make it so only the image url is entered, but the transition would likely break stuff all over the place until a user updates.

**Comment by the-j0k3r** [comment]
I meant the label portion... lol, Cup of coffee?

Instead of... (and look at capitalization) as you have in screenshot.

<kbd>Custom Background; include url()</kbd>

to

<kbd>Custom background; include URL</kbd>

**Comment by the-j0k3r** [comment]
Ah also you do know that your "editorconfig` adds extra line at the bottom and your userCSS has none :) I was fixing LF/CRLF on my commits and that one kept popping up.

**Comment by the-j0k3r** [comment]
closed by https://github.com/StylishThemes/GitHub-Dark/commit/6944c4f893cbd5b6179fe7205c0661512d23c469
