### ISSUE TITLE
Selectors for user profile` ajax-pagination-btn` issue with pre-generated and selectors?

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#667]
The problem is I see blue borders in this show more button when focus, upon closer inspection I see that the :active state **forced via browser** caused this button to have a background as set by base color.

![pagination](https://user-images.githubusercontent.com/31389848/42237854-e8aca3d0-7ef6-11e8-8fe7-97380e989ad9.gif)

This background comes https://github.com/StylishThemes/GitHub-Dark/blob/1a58bd914cbeae57d15c0941a5f3d1b8494f2fe2/github-dark.css#L1102

## Now the real fun started.

If what Im looking at is correct the `ajax-pagination-btn` is being targeted by auto-generated with
https://github.com/StylishThemes/GitHub-Dark/blob/1a58bd914cbeae57d15c0941a5f3d1b8494f2fe2/github-dark.css#L61-L62

- [x] several entries spotted around with the same selectors, <s>but none of them target that button.
I tied using it and failed.</s>

- [x] there is no :active selector for it, yet forcing it via browser shows base-color background

- [x] on focus there is a blue box shadow

The selector that targets this button is `.ajax-pagination-form .btn.btn-outline.ajax-pagination-btn:active` 

if this is true all `ajax-pagination-form .btn.btn-outline.ajax-pagination-btn` need updating (and adding the :active) and because there is so many of them a cleanup is probably best thing here.

So ill leave this to @Mottie or @silverwind I can do a PR but it will be overriding auto-generated with selectors that work (assuming Im right)

* **Browser**: FF 61.0
* **Operating System**: WIn 10 1709 pro
* **Screenshot**:

![capture](https://user-images.githubusercontent.com/31389848/42236543-184f2148-7ef3-11e8-91a3-d48df5ac2c4b.PNG)

* **HTML of the section where the issue occurs**:

````html
<form class="ajax-pagination-form js-ajax-pagination col-10 js-show-more-timeline-form" data-title="the-j0k3r / June 2018" data-year="2018" data-url="/the-j0k3r?tab=overview&amp;from=2018-06-01&amp;to=2018-06-30" data-from="2018-07-01" data-to="2018-07-03" action="/the-j0k3r?tab=overview&amp;from=2018-06-01&amp;to=2018-06-30&amp;include_header=no" accept-charset="UTF-8" method="get"><input name="utf8" value="✓" type="hidden">

    <img class="contribution-activity-spinner col-10 next" alt="" src="https://assets-cdn.github.com/images/spinners/octocat-spinner-128.gif">

    <button type="submit" class="ajax-pagination-btn btn btn-outline border-gray-dark width-full f6 mt-0 py-2 contribution-activity-show-more" data-disable-with="">
      Show more activity
    </button>

  <p class="text-gray f6 mt-4">
    Seeing something unexpected? Take a look at the
    <a href="https://help.github.com/categories/setting-up-and-managing-your-github-profile">GitHub profile guide</a>.
  </p>
</form>
````

**Comment by the-j0k3r** [comment]
@Mottie if my assumption is correct, want me to have a stab at this or is it something you prefer to do yourself?

**Comment by Mottie** [comment]
Yeah, go ahead. Thanks.
