### ISSUE TITLE
transfer repository, focus loss affects background button state

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#668]
Just noticed this while transferring a repo, default GH style doesn't have this problem

* **Browser**: FF 61.0
* **Operating System**: win 10 pro
* **Screenshot**:

watch that hovering the popup with <kbd>I understand, transfer this repository</kbd> affects the background not focused <kbd>Transfer</kbd> state. :) can we do this to all buttons? Buttons like to party too :)
![repo-transfer-button-weirdness](https://user-images.githubusercontent.com/31389848/42248307-ce772866-7f1c-11e8-8b56-afeb1731f9c4.gif)

* **HTML of the section where the issue occurs**:

background transfer button
````html
<summary class="btn btn-danger boxed-action">Transfer</summary>
````
popup button
````html
<button type="submit" class="btn btn-block btn-danger" data-disable-invalid="">I understand, transfer this repository.</button>
````

**Comment by the-j0k3r** [comment]
[![Highway to the, Danger Zone](https://user-images.githubusercontent.com/31389848/42248564-21a7f0be-7f1e-11e8-8944-518ecb0b2b65.png)](https://youtu.be/siwpn14IE7E)

No no one killed that Kenny. (that I know of)

**Comment by the-j0k3r** [comment]
OK so it was a focus loss that was more noticeable while hovering popup.

unrelated but related to noise above, GitHub is PR behaviour must have changed recently, I had to rename a commit (after a couple of tries) to force proper commit order of appearance in PR, commit order was fine up-to opening PR but after went sideways and decided to ignore it.

@the-j0k3r waves fist @ GitHubMs

**Comment by Mottie** [comment]
Hi @the-j0k3r!

Hmm, I kinda like the party background buttons... LOL 🤘😜
