### ISSUE TITLE
("Issues" and "Pull Requests" pages) There's no color change as you hover the entries in the 'Author' and 'Assignee' dropdowns

### ISSUE THREAD

**Issue by darkred** [StylishThemes/GitHub-Dark#672]
* **Browser**: Chrome 67, Firefox 61, Stylus 1.4.9, GitHub Dark 1.20.51
* **Operating System**: win 10x64
* **Screenshot**: (see below)

* **HTML of the section where the issue occurs** (the following is from https://github.com/StylishThemes/GitHub-Dark/issues , the "Author" dropdown, as I hover the 1st nickname)

````html
<a href="/StylishThemes/GitHub-Dark/issues?q=is%3Aopen+is%3Apr+author%3Adarkred" class="select-menu-item " aria-checked="false" role="menuitem">
        <svg class="octicon octicon-check select-menu-item-icon" viewBox="0 0 12 16" version="1.1" width="12" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M12 5l-8 8-4-4 1.5-1.5L4 10l6.5-6.5L12 5z"></path></svg>
        <div class="select-menu-item-gravatar"><img src="https://avatars1.githubusercontent.com/u/723651?s=60&amp;v=4" width="30" height="30" alt="@darkred"></div>
        <div class="select-menu-item-text">
          darkred
          
          <span class="description-inline"></span>
        </div>
      </a>
````

The issue is that there's no color change (background and text colors) as you hover the entries in the dropdowns 'Author' and 'Assignee' in "Issues" and "Pull Requests" pages.

Screen capture from https://github.com/StylishThemes/GitHub-Dark/issues
(the same occurs in https://github.com/StylishThemes/GitHub-Dark/pulls)
![12345](https://user-images.githubusercontent.com/723651/42276834-e5e93fda-7f9d-11e8-9e2c-b0a4270812d4.gif)

**Comment by Mottie** [comment]
Hi @darkred!

Thanks for letting us know. It looks like we just needed to regenerate our style since GitHub changed a bunch of selectors around.

**Comment by Mottie** [comment]
Fixed in https://github.com/StylishThemes/GitHub-Dark/commit/ba0ce82cbe1087b17d184b3dff3c43249c880f01.

**Comment by darkred** [comment]
Thanks a lot for the quick response, @Mottie !
