### ISSUE TITLE
Staff badge background is dark and hard to see now

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#674]
I noticed this a few days ago but I'm not sure if it was an intentional change in color, or if GitHub made a change that caused it. In the hover card it's not too bad, but on the profile page it seems unnoticeable at normal size.

* **Browser**: chrome
* **Operating System**: win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/42290150-861a3e76-7f91-11e8-87f7-985f32ed4c4a.png)

![image](https://user-images.githubusercontent.com/831974/42290162-93f1fbc4-7f91-11e8-9e36-6ac3d37ac3f6.png)

* **HTML of the section where the issue occurs**:

The background color is coming from the `.bg-blue` rule

```html
<div class="flex-self-start">
  <div class="rounded-1 overflow-hidden">
    <a data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:profile" href="/niik">
      <img class="d-block" height="60" width="60" alt="@niik" src="https://avatars2.githubusercontent.com/u/634063?s=88&amp;v=4">
    </a>
    <div class="d-block f6 bg-blue no-underline text-bold text-uppercase text-white text-center">Staff</div>
  </div>
</div>
````

````html
<ul class="vcard-details border-top border-gray-light py-3">
  <li class="vcard-detail pt-1 css-truncate css-truncate-target">
    <svg aria-label="Organization" class="octicon octicon-organization" viewBox="0 0 16 16" version="1.1" width="16" height="16" role="img"><path fill-rule="evenodd" d="M16 12.999c0 .439-.45 1-1 1H7.995c-.539 0-.994-.447-.995-.999H1c-.54 0-1-.561-1-1 0-2.634 3-4 3-4s.229-.409 0-1c-.841-.621-1.058-.59-1-3 .058-2.419 1.367-3 2.5-3s2.442.58 2.5 3c.058 2.41-.159 2.379-1 3-.229.59 0 1 0 1s1.549.711 2.42 2.088C9.196 9.369 10 8.999 10 8.999s.229-.409 0-1c-.841-.62-1.058-.59-1-3 .058-2.419 1.367-3 2.5-3s2.437.581 2.495 3c.059 2.41-.158 2.38-1 3-.229.59 0 1 0 1s3.005 1.366 3.005 4z"></path></svg>
    <span class="p-org" itemprop="worksFor">GitHub</span>
      <span class="label bg-blue text-uppercase">Staff</span>
  </li>
</ul>
````

**Comment by the-j0k3r** [comment]
@silverwind 

That fix breaks this and breaks this for me in Firefox.

before 0937215
![before](https://user-images.githubusercontent.com/31389848/42934742-c8e26d0a-8b3f-11e8-8380-9fc7fc651a46.png)

after 0937215
![after](https://user-images.githubusercontent.com/31389848/42934781-e9c164ea-8b3f-11e8-9353-be46089381f4.png)

While the popover remains the same with/without this fix

![capture](https://user-images.githubusercontent.com/31389848/42934863-2523bf2e-8b40-11e8-8dbf-6812541046c4.PNG)

It also breaks issue 2 in https://github.com/StylishThemes/GitHub-Dark/issues/699
