### ISSUE TITLE
Incorrect styling in create label form

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#678]
The color input text should be styled red (it's red even when the input value is valid) and the submit button disabled. Right now the text isn't red and the button is only styled as disabled in its `:hover` state.

The input text color is being overridden by `input:not(.btn-link)` and the button style is due to a missing `.btn-primary:disabled` selector.

* **Browser**: chrome
* **Operating System**: win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/42329139-063de196-803e-11e8-85ff-f38cc04af17e.png)

![image](https://user-images.githubusercontent.com/831974/42329171-12ce524c-803e-11e8-8a20-572cb56b7dbb.png)

* **HTML of the section where the issue occurs**:

```html
<input required="" aria-describedby="label--color-error" value="#bfdadc" type="text" name="label[color]" id="label-color-" style="width: 6em" class="form-control input-monospace pb-1 mr-0 js-new-label-color-input text-red" maxlength="7" autocomplete="off" spellcheck="off" pattern="#?([a-fA-F0-9]{6}|[a-fA-F0-9]{3})" title="Hex colors should only contain numbers and letters from a-f">
```

````html
<button data-disable-invalid="" class="btn btn-primary" data-disable-with="Saving..." type="submit" disabled="">Create label</button>
````

**Comment by Mottie** [comment]
Hi @xt0rted!

Thanks for reporting this issue. Hmm, I think maybe it should be green when the color is valid... what do you think?

**Comment by xt0rted** [comment]
I think the color applied by the `input:not(.btn-link)` selector is a good default since that matches all the other inputs (seems odd to make this one red).

Since they're using native form validation we can use the [`:invalid`](https://caniuse.com/#feat=form-validation) pseudo-class to style it red with something like `input[id="label-color-"]:invalid`.

**Comment by Mottie** [comment]
Yeah, but I was thinking about including a `input[id="label-color-"]:valid` as well.

**Comment by Mottie** [comment]
Oh wait... that's odd. If you enter an invalid color, the text stays red no matter what you enter. So that's GitHub's fault it's always red. Disregard my last statement 😛

**Comment by xt0rted** [comment]
I realized that after I took the screen shots and was too lazy to re-do them 😴

**Comment by xt0rted** [comment]
Looks like the `.text-red` class is added only after you fill in the field wrong. They don't remove it once the field is valid so that's on them, but fixing it so the text is red when that class is added should give us the same default functionality.

**Comment by Mottie** [comment]
I think using `:invalid` is a better choice. I'll report the problem either way.

**Comment by xt0rted** [comment]
@Mottie the `disabled` button style I mentioned wasn't fixed. I just ran into it on another page where I was trying to submit a form only to realize the button was actually disabled if you turn off GitHub Dark.

I think the fix is changing

```css
.btn-primary:not(.compare-button):not(.btn-outline) { ... }
```

to

```css
.btn-primary:not(.compare-button):not(.btn-outline):not([disabled]) { ... }
```

**Comment by xt0rted** [comment]
Or if you want to be less verbose, `:enabled` 🤦‍♂️

**Comment by Mottie** [comment]
Disabled buttons should have their opacity reduced. Which page are you seeing this non-disabled looking button?

**Comment by xt0rted** [comment]
Open the create new label form, but don't fill anything in. The `Create label` button will have the `disabled` attribute set and the button's color will be the same as a button you can click. On hover the color gets darker vs. enabled buttons which get lighter, but that's not really intuitive.

The other page I ran into this on is https://github.com/settings/installations when viewing the slack integration.

**Comment by Mottie** [comment]
Ok, the fix will be available in the next update.
