### ISSUE TITLE
Remove support for Stylish and userstyles.org

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#683]
Given the [latest news](https://robertheaton.com/2018/07/02/stylish-browser-extension-steals-your-internet-history/) about shady businesses of the owners of the Stylish extension (and userstyles.org), I feel like we should delete our account there along with all styles hosted on it as I do not want to associate anymore with the owners. Also, the extension has been [pulled](https://arstechnica.com/information-technology/2018/07/stylish-extension-with-2m-downloads-banished-for-tracking-every-site-visit/) from various stores so it makes the site kind of  obsolete too. @Mottie are you fine with it? Less work when updating the style, too.

**Comment by silverwind** [comment]
Yes, OpenUserCSS is certainly an option, but I'd only consider it if there is a way to automate update deployment via an API, otherwise it's too much work for little benefit.

**Comment by tambry** [comment]
Seems like they do have an API (api.openusercss.org), and there's code for the API in their repo, but it doesn't look like it's documented.

**Comment by silverwind** [comment]
I see there's a GraphQL API but it looks rather complicated to write a client against without documentation (lots of body parameters).

@DecentM I don't suppose you maybe have a sample client to api.openusercss.org available?

**Comment by the-j0k3r** [comment]
There was an interesting discussion on USO about licensing and source code https://forum.userstyles.org/discussion/61002/stylish-open-source-status-as-of-2017#latest but I disagree with the views expressed, because no one bothered to read GPLv3 and paragraph 6 more specifically.

In any event there seems to be mystery surrounding mystery that no one is able to cut through for various reasons and officially there is no effort in clarifying anything or assuage peoples qualms.

OpenUserCSS has had some bugs squashed in the areas of adding/managing styles, sadly nothing has been done about automatic deployment, but dont despair there are issues open and being tracked, waiting further development and bug fixes, So in time with more maturity it will be a valid option for you guys :)

**Comment by silverwind** [comment]
> I can work on converting all the remaining styles into user.css versions, then we can host them all here on GitHub.

That'd be great, yes. Once we have all our styles in usercss format, we're free to move from USO. For the simple styles without configuration, all that should be needed is a small header.

> nothing has been done about automatic deployment

Yeah, seems so. I think at minimum I'd need a way to generate auth tokens in the web interface and a API endpoint to POST a updated style to. I have to admit, this GraphQL stuff seems a bit intimedating, I guess I'd prefer REST endpoints, but maybe I'm too old-fashioned. :)

> The only thing with that is visibility and popularity which leads to exposure is considerably lower than USO.

I don't particularily care about popularity, we write styles mostly for our own use.

**Comment by the-j0k3r** [comment]
Here is one thing to consider, remove the mention of stylish from all readmes and wiki entries. I know I will.

> I don't particularily care about popularity, we write styles mostly for our own use.

I also write styles for my usage, but after I spent x amount of hours writing it and tweaking it/updating it and posting on GH, its nice to share with others and have users find them sort of easily, that said a certain degree of difficulty will likely filter out some users you may or may not want to have :).

**Comment by DecentM** [comment]
> I think at minimum I'd need a way to generate auth tokens in the web interface...  

You only need tokens for actions that require logging in, like changing passwords, uploading a theme, etc. The rest of the functions are publicly accessible (this may change in the future if I see a lot of abuse), so it should be easy to search for themes and get their contents from any app.

> ...and a API endpoint to POST a updated style to. I have to admit, this GraphQL stuff seems a bit intimedating, I guess I'd prefer REST endpoints, but maybe I'm too old-fashioned. :)  

I've written some API functions for usage in Stylus here: https://github.com/openstyles/stylus/blob/44a11508fff2175da9397972c62396c8bc23c80a/background/openusercss-api.js  
You can think of GraphQL as REST with some restrictions. You can only do POST and the body must contain a string that's a valid query. For example, this string:
```
query {
  theme(id: "5a2f03e7ba666f0b00b9c829") {
    title
    screenshots
    user {
      displayname
    }
  }
}
```
will result in the following JSON response:
```json
{
  "data": {
    "theme": {
      "title": "Dark Google search",
      "screenshots": [
        "https://i.imgur.com/hdNGXpm.png",
        "https://i.imgur.com/A3Agtsa.png"
      ],
      "user": {
        "displayname": "DecentM"
      }
    }
  }
}
```
If you feel like experimenting, there is an excellent Star Wars themed API you can poke without installing anything here: https://graphql.org/swapi-graphql/  
You can also do the same thing with the OUC API by downloading GraphiQL from here: https://github.com/skevy/graphiql-app/releases (set the endpoint to https://api.openusercss.org)

**Comment by Mottie** [comment]
I think GitHub must've gone crazy... the comment arrows only appear in self posts and the new comment area now.

![](https://user-images.githubusercontent.com/136959/42543284-bd64ea64-8470-11e8-9655-bcb2558b7bd5.png)

**Comment by the-j0k3r** [comment]
> I think GitHub must've gone crazy.

Im quite sure of it. for quite a few reasons.

**Comment by silverwind** [comment]
I could live without those arrows, but let's not derail this topic any more.

**Comment by the-j0k3r** [comment]
Ive removed all mentions of stylish on my readmes in its entirety, I see you only have removed from GHD.

**Comment by silverwind** [comment]
The Safari Extension (code at https://github.com/350d/stylish) is independent from the other Stylish extensions, so I kept the link. I don't think it includes any tracking code, but probably best to check twice.

**Comment by the-j0k3r** [comment]
Also, https://github.com/StylishThemes/GitHub-Dark/wiki/Install#stylish, I would make contributions to wiki, but its closed.

**Comment by the-j0k3r** [comment]
IDK what reasons were, but Ive been updating my readmes etc and replaced Stylish with Freestyler and found Freestyler also is not anywhere for G Chrome.

TBH never really looker into it much.

**Comment by Mottie** [comment]
Did I miss something? Freestyler *claims* to have extensions for Chrome, Firefox, Opera and Safari - https://freestyler.ws/plugin-page - The Firefox & Safari versions appear to expect you to install them directly, but no instructions are included.

**Comment by the-j0k3r** [comment]
> Did I miss something? Freestyler claims to have extensions for Chrome,

At some point something happened, and now they dont seem to have any I could find easily from their download page but seems the only one that is offered an indirect link i.e to gchrome store.

Have no idea of reason and also dont have much interest in finding out :)

**Comment by silverwind** [comment]
I did a short test with FreeStyler on Safari:

1. It does not support the usercss format.
2. It maintains its own community site where authors have to upload styles.

Our readme states usercss support for FreeStyler. Is this true for the Chrome/Firefox versions only perhaps?

**Comment by silverwind** [comment]
More FreeStyler testing:

- The Chrome extension page is 404. I assume it was either redacted or taken down by Google.
- The Firefox extension installs, but does not seem to support usercss either.

Also, it seems it is not possible to install/create a style not published on freestyler.ws. I'm thinking we have to drop that one too.

**Comment by the-j0k3r** [comment]
> The Chrome extension page is 404. I assume it was either redacted or taken down by Google.

Ive said this same thing, but I think its strange that 3rd party site has newer version and FS forums have no news of anything that new.

Does anyone know where sourcecode for Freestyler is? Does it even exist?

**Comment by Mottie** [comment]
I don't know where the freestylers source is located, but we should share the alternate [xStyle](https://github.com/FirefoxBar/xStyle) which only supports the `@advanced` variables format in [usercss](https://github.com/openstyles/stylus/wiki/UserCSS#xstyle-compatibility). I don't know if it works with the freestyler.ws site.

**Comment by Mottie** [comment]
> Our readme states usercss support for FreeStyler

Sorry, I was thinking of xStyle.

**Comment by silverwind** [comment]
> Does anyone know where sourcecode for Freestyler is? Does it even exist?

I don't think it is published anywere but you can just rename a .xpi extension for Firefox to .zip and inspect the minified Javascript source. From a cursory look, it seems to include some sort of "statistics" code which seems a bit fishy, maybe this was the reason it was taken down from the Chrome store (assuming it was).

**Comment by jtheletter** [comment]
FreeStyler seems to work on Safari, but its interface is clunkier, and it doesn't seem to have an import function.

**Comment by silverwind** [comment]
I've now deleted (or rather, archived) all our userstyles.org styles with messages to install from GitHub instead, so this is actually fixed now.

**Comment by Mottie** [comment]
Thanks! I've been super busy... product launch tomorrow.
