### ISSUE TITLE
User name in fork modal is the wrong color

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#698]
* **Browser**: chrome
* **Operating System**: win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/42883346-608cf260-8a69-11e8-9bf2-c353360e78fd.png)

* **HTML of the section where the issue occurs**:

````html
<button type="submit" name="organization" value="xt0rted" tabindex="0" class="owner-select-target" aria-label="" title="@xt0rted">
  <img class="avatar owner-select-avatar" src="https://avatars3.githubusercontent.com/u/831974?s=200&amp;v=4" width="100" height="100" alt="@xt0rted">
  <span class="owner css-truncate css-truncate-target">
    @xt0rted
  </span>
</button>
````

**Comment by Mottie** [comment]
Hi @xt0rted!

It'll be fixed in the master branch shortly. Thanks for reporting the problem!
