### ISSUE TITLE
Clear search button/icon is hard to see

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#702]
It's been awhile since I've looked at this, so I'm not sure if the color changed recently, but I thought this was more visible than it is now.

* **Browser**: chrome
* **Operating System**: win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/42977288-4c8948aa-8b94-11e8-864b-78ef2a30f864.png)

* **HTML of the section where the issue occurs**:

````html
<div class="issues-reset-query-wrapper">
    <a class="issues-reset-query" href="/StylishThemes/GitHub-Dark/issues?q=is%3Aissue+is%3Aopen">
      <svg class="octicon octicon-x issues-reset-query-icon" viewBox="0 0 12 16" version="1.1" width="12" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.48 8l3.75 3.75-1.48 1.48L6 9.48l-3.75 3.75-1.48-1.48L4.52 8 .77 4.25l1.48-1.48L6 6.52l3.75-3.75 1.48 1.48L7.48 8z"></path></svg>
      Clear current search query, filters, and sorts
</a>  </div>
````

**Comment by Mottie** [comment]
Hi @xt0rted!

Thanks for reporting this issue... it's fixed in the master branch & it'll be available in the next update.

**Comment by xt0rted** [comment]
@Mottie I installed `refined-github` again to try it out with some of the annoying things disabled. It's adding commit links to the status labels above. With `github-dark` disabled they're white, but with it enabled they're blue.

Is this something you want to try fixing? I'm probably going to turn that feature off since there's already a link to the same commit at the bottom of the issue.

![image](https://user-images.githubusercontent.com/831974/42980155-1351e37a-8ba4-11e8-8d94-b41b5dbd76a5.png)

Setting `color: inherit` on the `a` fixes it.

```html
<div class="TableObject-item">
        <a href="#event-1743889120"><div class="State State--red">
          <svg class="octicon octicon-issue-closed" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7 10h2v2H7v-2zm2-6H7v5h2V4zm1.5 1.5l-1 1L12 9l4-4.5-1-1L12 7l-1.5-1.5zM8 13.7A5.71 5.71 0 0 1 2.3 8c0-3.14 2.56-5.7 5.7-5.7 1.83 0 3.45.88 4.5 2.2l.92-.92A6.947 6.947 0 0 0 8 1C4.14 1 1 4.14 1 8s3.14 7 7 7 7-3.14 7-7l-1.52 1.52c-.66 2.41-2.86 4.19-5.48 4.19v-.01z"></path></svg>
          Closed
         in <code><a href="/StylishThemes/GitHub-Dark/commit/8674b5577b79cb31abfe92cbde400b39710c8b02">8674b55</a></code></div></a>
    </div>
```

**Comment by Mottie** [comment]
What do you think of making that link `#ddd`?

![](https://user-images.githubusercontent.com/136959/42981084-0c9e2376-8ba0-11e8-8bcf-2acdf515fba0.png)

**Comment by xt0rted** [comment]
Works for me
