### ISSUE TITLE
Membership type heading is black until hovered.

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#710]
* **Browser**: FF 61.0.1
* **Operating System**: Win 10
* **Screenshot**:

https://github.com/orgs/StylishThemes/people

![titlesandsmalltext](https://user-images.githubusercontent.com/31389848/43152069-714ae66a-8f65-11e8-95e9-7f570b7f2243.gif)

![capture](https://user-images.githubusercontent.com/31389848/43152003-3b433540-8f65-11e8-843f-4d7cd1148b9d.PNG)

* **HTML of the section where the issue occurs**:

````html
<button type="submit" class="btn-plain select-menu-item-text js-select-button-text">
          <span class="select-menu-item-heading">Public</span>
          <span class="description">Your membership is visible to everyone and is displayed on your public profile.</span>
        </button>
<button type="submit" class="btn-plain select-menu-item-text js-select-button-text">
          <span class="select-menu-item-heading">Private</span>
          <span class="description">Your membership is only visible to other members of this organization.</span>
        </button>
````

**Comment by the-j0k3r** [comment]
Nor me atm :(

**Comment by xt0rted** [comment]
`#000` is the default color of `button` text, it's coming from the browser's default stylesheet

![image](https://user-images.githubusercontent.com/831974/43153056-3db03b06-8f3e-11e8-8b11-335a9449a56d.png)

**Comment by the-j0k3r** [comment]
Firefox devtools are a poor cousin to Chromes, but I heard (dont know if its right) their ditching it soon.

**Comment by silverwind** [comment]
Right, it inherits from the browser's `button` style. I think you could do

````css
.inline-form .btn-plain {
  color: inherit;
}
````

**Comment by the-j0k3r** [comment]
Yes that works :)

**Comment by xt0rted** [comment]
That selector looks way too generic for that control, `.select-menu-item.navigation-focus .select-menu-item-heading` seems more appropriate.

**Comment by xt0rted** [comment]
Actually for our use you don't need the `.navigation-focus` modifier class.

**Comment by silverwind** [comment]
Yes, `.select-menu-item .select-menu-item-heading` could also work, less chance of breakage that way.

**Comment by the-j0k3r** [comment]
`.select-menu-item .select-menu-item-heading` doesnt work with color: inherit

**Comment by the-j0k3r** [comment]
Ill have a look in a while after dinner, unless someone is faster than me.

**Comment by silverwind** [comment]
Yeah, you'd have to add a specific color style to it which would probably also require a separate style for hover. I'd leave it as is, chance of breakage with `.btn-plain` is probably low as it will inherit some light color from a parent element.

**Comment by the-j0k3r** [comment]
Also the hover white needs adjusting else it dims on hover too. 🙄

**Comment by silverwind** [comment]
Actually, I think this was broken in https://github.com/StylishThemes/GitHub-Dark/commit/e75460ace96a9e24fa3029fdd9b33d34892f76e6. Checking if I can maybe define `button` color in a way that other rules can override later.

**Comment by the-j0k3r** [comment]
OK dinner, its looking hairier than it seems with `.select-menu-item .select-menu-item-heading`

**Comment by silverwind** [comment]
Better fix in https://github.com/StylishThemes/GitHub-Dark/commit/539b066c0d60c2001a2426b13d5062d84bf39639. This just overrides the default style of the browser. And a simple `button` selector is so low-weight that anything that comes after it will override it.

**Comment by silverwind** [comment]
And moved it before everything in https://github.com/StylishThemes/GitHub-Dark/commit/458d5105930737c180e417c02bf9efd19b02565d. That way, same-specificity autogenerated rules can override it too.
