### ISSUE TITLE
Image on dashboard content is hidden

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#712]
* **Browser**: chrome
* **Operating System**: win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/43168477-67db32e6-8f6b-11e8-89a3-ca95c91c1fe3.png)

![image](https://user-images.githubusercontent.com/831974/43168469-5a307386-8f6b-11e8-8ad7-575405a02c02.png)

* **HTML of the section where the issue occurs**:

````html
<li>
        <div class="inset-figure">
          <img alt="" src="https://assets-cdn.github.com/images/modules/notices/context_button.png" width="100" height="30">
        </div>
        Use the switch context button in the upper left corner of this screen
        to switch between your personal context (<strong>xt0rted</strong>)
        and this organization.
      </li>
````

This is being hidden with the `img[src$="/notices/context_button.png"] ` selector

**Comment by Mottie** [comment]
Hi @xt0rted!

Please share a link to that page... you can replace the organization name with something like `:org`, so I have a clue as to where to find that dashboard.

**Comment by xt0rted** [comment]
https://github.com/orgs/13degrees/dashboard

Looks to only show when it's an empty org

**Comment by Mottie** [comment]
Ahh ok, it looks like it was added in https://github.com/StylishThemes/GitHub-Dark/pull/445... I'm not sure why it was hidden. Do you think we can remove this now @silverwind?

**Comment by silverwind** [comment]
Old comment from me:

>  I had to remove that defunkt pseudo-button as it was just a plain image with no way to invert it properly

So if you can invert it properly, please do :)

**Comment by silverwind** [comment]
@xt0rted it would help if you can post the full HTML of that box.

**Comment by Mottie** [comment]
You can create a new empty organization to see it... click on your name in the left column on github.com main feed page, then choose the empty organization:

```html
<div class="dashboard-notice mt-3">
	<svg height="32" class="octicon octicon-organization notice-icon" viewBox="0 0 16 16" version="1.1" width="32" aria-hidden="true"><path fill-rule="evenodd" d="M16 12.999c0 .439-.45 1-1 1H7.995c-.539 0-.994-.447-.995-.999H1c-.54 0-1-.561-1-1 0-2.634 3-4 3-4s.229-.409 0-1c-.841-.621-1.058-.59-1-3 .058-2.419 1.367-3 2.5-3s2.442.58 2.5 3c.058 2.41-.159 2.379-1 3-.229.59 0 1 0 1s1.549.711 2.42 2.088C9.196 9.369 10 8.999 10 8.999s.229-.409 0-1c-.841-.62-1.058-.59-1-3 .058-2.419 1.367-3 2.5-3s2.437.581 2.495 3c.059 2.41-.158 2.38-1 3-.229.59 0 1 0 1s3.005 1.366 3.005 4z"></path></svg>
	<h2>You’re an owner of the <strong>virtual-kbd</strong> organization!</h2>

	<p>Here are some quick tips for an owner.</p>

	<ul>
		<li>
			<div class="inset-figure">
				<img alt="" src="https://assets-cdn.github.com/images/modules/notices/context_button.png" width="100" height="30">
			</div>
			Use the switch context button in the upper left corner of this screen to switch between your personal context (<strong>Mottie</strong>) and this organization.
		</li>

		<li>
			Create teams and add users to control access to your organization’s repositories. There’s no limit, so create as many as you need!
		</li>

		<li>
			<div class="inset-figure">
				<img alt="" src="https://assets-cdn.github.com/images/modules/notices/account_settings.png" width="100" height="32">
			</div>
			Control your organization’s
			<strong>billing information</strong>, public profile, and other settings using the “Organization settings” section under your personal Settings, which you will find at the top right of your screen.
		</li>

		<li>
			<div class="inset-figure">
				<img alt="" src="https://assets-cdn.github.com/images/modules/notices/fork_button.png" width="100" height="24">
			</div>
			Add repositories to this organization by using the “New repository” button to the right. Using the “fork” button on a repository, you’ll be given the option to fork the repository into this organization.
		</li>
	</ul>

	<p><small class="text-gray">Add users or repositories to remove this box.</small></p>
</div>
```

**Comment by silverwind** [comment]
Okay, then we can just invert all images and unhide the hidden one.

**Comment by Mottie** [comment]
I don't think we need to invert them, they're so small and it's a page that probably won't get much traffic. I think we only need to remove that selector and that'll be enough.

**Comment by silverwind** [comment]
Fine with me too.

**Comment by the-j0k3r** [comment]
full width dashboard... So now I have to make a style to revert that fugliness :)

**Comment by Mottie** [comment]
LOL just opt-out, and send some feedback about the fugliness 😝.

**Comment by the-j0k3r** [comment]
I did send feedback, but you wont be able to opt-out anymore once its live and I doubt they care, I have a 4k screen at 2560x1440p to make it readable and it just looks odd, its not friendly as before imo.

**Comment by xt0rted** [comment]
The entire site is moving to a semi-fluid layout and will soon match the dashboard. I know an insider 😉

**Comment by the-j0k3r** [comment]
Yey well done MS,way to screw up GH, why am I even surprised
