### ISSUE TITLE
Text selection barely visible in Chrome after building the theme using grunt

### ISSUE THREAD

**Issue by krupenja** [StylishThemes/GitHub-Dark#718]
* **Browser**: Chrome Dev channel version 69.0.3497.12.
* **Operating System**: macOS 10.13.6

* **HTML of the section where the issue occurs**: Any page on Github.

**Steps**:
1. Build the theme using `grunt` by following directions here: https://github.com/StylishThemes/GitHub-Dark/wiki/Build
2. Use the following `build.json` settings (everything default except `"webkit"   : true`):

```json
{
  "theme": "idle-fingers",
  "themeCM": "twilight",
  "themeJP": "twilight",
  "color": "#008080",
  "font": "Menlo",
  "image": "url(https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/images/backgrounds/bg-tile1.png)",
  "tiled": true,
  "codeWrap": false,
  "attach": "scroll",
  "tab": 4,
  "webkit": true
}
```
3. Add the generated CSS file to Stylus extension.
4 Open any page on GitHub.
5. Try selecting any text.

**Result**:
Text selection is barely visible. There is no colour highlighting, all selected text simply turns white. More easily visible if you select code. See this example:
![kap](https://user-images.githubusercontent.com/26354715/43361299-207efff6-92d4-11e8-8987-969fbe121842.gif)

This problem is not present if installing the theme from [userstyles.org](userstyles.org).

**Comment by krupenja** [comment]
OK, after running grunt again the problem is gone even though I have not changed anything. Weirb but closing as not reproducible.

**Comment by the-j0k3r** [comment]
Hi @krupenja 

I have also found that sometimes running grunt has unexpected results and that re-running usually produces the expected results.

Not entirely sure why it happens though.

Perhaps @silverwind has some idea.

**Comment by silverwind** [comment]
Not in the mood to debug grunt right now, but we should eventually rewrite it to a standalone build script.
