### ISSUE TITLE
More github.com subdomains

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#719]
I'm looking for feedback on if we should include the following pages with this style:

* https://services.github.com/ (https://services.github.com/on-demand/ - no link from main page?)
* https://lab.github.com/

It looks like it will need some minor tweaks to get it working, but not too bad.

**Comment by the-j0k3r** [comment]
Neat, why not?

Also why not add https://styleguide.github.com  to that?

**Comment by Mottie** [comment]
I hesitate to add https://styleguide.github.com/primer/ because its a css framework based on a white color scheme.

Especially look at this page - https://styleguide.github.com/primer/utilities/colors/ - none of the defined colors would match what is being described. And, the syntax highlighting, PrettyLights I presume, doesn't match our settings since it doesn't have the "pl-" prefix on the class names.

**Comment by xt0rted** [comment]
I don't think any of these pages should be covered by this theme.

https://styleguide.github.com (some of the pages are restricted to the github org only)
https://hubot.github.com
https://slack.github.com
https://desktop.github.com

All of these are github pages (like https://primer.github.io/) but hosted with github.com to convey being owned by them and not a community project.

**Comment by xt0rted** [comment]
On the topic of this, can `graphql-explorer.githubapp.com` be removed from the url rules since it redirects to `https://developer.github.com/v4/explorer/` now?

**Comment by Mottie** [comment]
The url graphql-explorer.githubapp.com, does redirect to the developer subdomain, but the explorer still runs within an iframe from githubapp.com. If you remove the entry, the iframe turns white.

**Comment by silverwind** [comment]
I'd reduce the list of sites to what is absolutely neccessary for powerusers (novices would not find or install our style anways). For me, that's github.com, gist, news and status, as well as framed content on these sites.

**Comment by xt0rted** [comment]
I'd also include the blog since they've been posting more frequent updates to it, such as at https://blog.github.com/changelog/

**Comment by the-j0k3r** [comment]
Whatever is happening dont take away from whats currently supported :)

**Comment by silverwind** [comment]
> also include the blog

That's what I meant with "news" 😉

**Comment by xt0rted** [comment]
They have so many subdomains now I thought news.github.com was a real page
