### ISSUE TITLE
Filename overflows file header in PRs

### ISSUE THREAD

**Issue by auscompgeek** [StylishThemes/GitHub-Dark#724]
Looks like this was caused by 9b5fa7eeaa25028dc8c0f53849cffad002532272.

* **Browser**: Firefox 61.0.1
* **Operating System**: Arch Linux
* **URL**: https://github.com/wpilibsuite/allwpilib/pull/1022
* **Screenshot**:
![image](https://user-images.githubusercontent.com/128854/43560037-04f3a240-9654-11e8-9936-ff9dfa240ed3.png)
* **HTML of the section where the issue occurs**:
```html
<summary class="file-header js-toggle-outdated-comments">
    <span class="btn-link text-gray float-right f6 outdated-comment-label show-outdated-button"><svg class="octicon octicon-unfold position-relative mr-1" viewBox="0 0 14 16" version="1.1" width="14" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M11.5 7.5L14 10c0 .55-.45 1-1 1H9v-1h3.5l-2-2h-7l-2 2H5v1H1c-.55 0-1-.45-1-1l2.5-2.5L0 5c0-.55.45-1 1-1h4v1H1.5l2 2h7l2-2H9V4h4c.55 0 1 .45 1 1l-2.5 2.5zM6 6h2V3h2L7 0 4 3h2v3zm2 3H6v3H4l3 3 3-3H8V9z"></path></svg>Show outdated</span>
    <span class="btn-link text-gray float-right f6 outdated-comment-label hide-outdated-button"><svg class="octicon octicon-fold position-relative mr-1" viewBox="0 0 14 16" version="1.1" width="14" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7 9l3 3H8v3H6v-3H4l3-3zm3-6H8V0H6v3H4l3 3 3-3zm4 2c0-.55-.45-1-1-1h-2.5l-1 1h3l-2 2h-7l-2-2h3l-1-1H1c-.55 0-1 .45-1 1l2.5 2.5L0 10c0 .55.45 1 1 1h2.5l1-1h-3l2-2h7l2 2h-3l1 1H13c.55 0 1-.45 1-1l-2.5-2.5L14 5z"></path></svg>Hide outdated</span>
        <a href="/wpilibsuite/allwpilib/pull/1022/files/7e1216e5fb83bff4153d0a033f5e2edfb1b5a577#diff-9614fb171e262da53ef7674d190ff496" class="file-info link-gray-dark" title="wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/Shuffleboard.java">
      wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/Shuffleboard.java
    </a>
  </summary>
```

**Comment by Mottie** [comment]
Hi @auscompgeek!

I can't duplicate this problem. I see the `.java` ending on all three files using the latest user.css style in the same version of Firefox on Windows. I don't have a Linux system to test.

The commit that was shared deals with the "Files changed" tab and shouldn't cause the issue seen in the screen shot.

**Comment by auscompgeek** [comment]
Hm. Turns out this only becomes a problem if you zoom in. (I always have GitHub zoomed at 110% because the code font size is oddly small to me otherwise.)

It's definitely caused by the CSS introduced in that commit though; the CSS selector `.pull-request-tab-content .file-header` does select those headers.

**Comment by Mottie** [comment]
LOL, I'm always zoomed in to 110% as well. I'm still not seeing the problem. What happens if you disable the `padding: 1px 10px !important` definition from the dev tools?

**Comment by auscompgeek** [comment]
No dice.

If it helps, it seems my file headers are using the Droid Sans Mono Slashed font, and the sans-serif font is Noto Sans.

**Comment by the-j0k3r** [comment]
IDK, so far both `:not(.js-toggle-outdated-comments)` and `:not(summary)` are the only ones that work in that position.

And neither of those affect the functionality of 9b5fa7e or the area that it proposes to fix here

**Comment by the-j0k3r** [comment]
OK got it, fix incoming.

**Comment by auscompgeek** [comment]
Heh, I was wondering whether the height rule there was necessary.

**Comment by the-j0k3r** [comment]
Its more complicated that that see https://github.com/StylishThemes/GitHub-Dark/issues/598

which is why that was developed. But because the heigh can increase in file-header to accomodate extra long lines the issue with those re-happens again in these portions.

**Comment by the-j0k3r** [comment]
@auscompgeek see https://github.com/StylishThemes/GitHub-Dark/issues/598#issuecomment-409949690 it explain the issue further.

**Comment by Mottie** [comment]
GitHub truncates the path/filename so that it doesn't expand into two rows. Try the CSS I shared, it won't effect the file names in the conversation tab.

**Comment by the-j0k3r** [comment]
Again no this issue affects two portions what @auscompgeek pointed out and the fileheaders in diff view.
Disable GHD and look not just at this but also at the info I posted at https://github.com/StylishThemes/GitHub-Dark/issues/598#issuecomment-409949690

If you dont want to, just look at this with the above code.

![oveflow](https://user-images.githubusercontent.com/31389848/43620202-77013102-96c9-11e8-9e4c-730dfd7e3d0d.gif)

**Comment by Mottie** [comment]
Ok, I still can't reproduce, so I'll leave it to you.

**Comment by xt0rted** [comment]
I can't repro this either. Out of curiosity what font size are you seeing used on that text? Mine's `12px` and the only way I can get the text to overflow is to increase the size.

**Comment by the-j0k3r** [comment]
this

```css
    .pull-request-tab-content .diff-view .file-header {
      height: 32px !important;
      padding: 1px 10px !important;
    }
```

equals

![oveflow](https://user-images.githubusercontent.com/31389848/43620558-33245dcc-96cb-11e8-991e-39484b3ee73f.gif)

font size or no font size the difference between default and GHD is painfully obvious

**Comment by the-j0k3r** [comment]
This maybe a Firefox thing I realize neither of you use Firefox but the full width of elements is cut off here and these headers overflow like showed above.

**Comment by the-j0k3r** [comment]
It wont work whitespace pre.

Ive played with this to ad nauseaum to fix #598 and whatever tweaks are there are necessary to make it work here

Are you even looking at the gifs Im posting? anyway, Do whatever, Ill just open bug reports or fix it localy

**Comment by the-j0k3r** [comment]
white space pre

![capture](https://user-images.githubusercontent.com/31389848/43621001-3bacfd08-96cd-11e8-9151-d62aa497c43f.PNG)

**Comment by Mottie** [comment]
Actually, I was thinking about this:

```css
.pull-request-tab-content .file-header {
  text-overflow: ellipsis;
  overflow: hidden;
  white-space: nowrap;
}
```

**Comment by the-j0k3r** [comment]
YOu cant remove the padding else what that proposes to fix is null and void, but lets ignore that for a second.

Your proposal.

![oveflow](https://user-images.githubusercontent.com/31389848/43621526-eaf07e28-96cf-11e8-9211-7ac5a45c744b.gif)

Text is now overlapping and as you can see when I disabled GHD the header is double height.

**Comment by xt0rted** [comment]
In your settings do you have a minimum font size set? Because If i set that to `14px` then I'm able to repro the overflowing text.

If I disable the `32px` file header rule, with and without Refined GitHub enabled, the headers expand when needed and look to work fine in both the comments view and the diff view. Why is this height being explicitly set in the first place? Was it just a stylistic choice like how the diff header is shorter in GHD than by default?

**Comment by the-j0k3r** [comment]
>In your settings do you have a minimum font size set?

I do, but does that explain  the differences between default and GHD?

**Comment by xt0rted** [comment]
It explains **why** the text is overflowing and why we couldn't see it. Now @Mottie can adjust his settings and see it too which is better than a screen shot.

**Comment by the-j0k3r** [comment]
Sucks to be half blind in a modern world of UHD

**Comment by Mottie** [comment]
I did adjust the font size... that's how I came up with https://github.com/StylishThemes/GitHub-Dark/issues/724#issuecomment-410126618... I'm done for tonight. You guys hash it out.

**Comment by the-j0k3r** [comment]
> I'm done for tonight. You guys hash it out.

Im also done tonight and with this

Ive had an extremely long day and cantdiscuss the reasons why https://github.com/StylishThemes/GitHub-Dark/commit/9b5fa7eeaa25028dc8c0f53849cffad002532272 has to be as it is since it was already itself a long discussion in #598 and https://github.com/StylishThemes/GitHub-Dark/issues/612 and since its inception in https://github.com/StylishThemes/GitHub-Dark/pull/690 and after the fact in https://github.com/StylishThemes/GitHub-Dark/commit/5743cd7092c69ab2a724a3c02c65fd806e2a10bd why the reason of each value existence discussing it further is just going nowhere.

**Comment by silverwind** [comment]
Instead of setting a minimum font size which ought to break layouts, I can recommend a extension like [this](https://addons.mozilla.org/en-US/firefox/addon/zoom-page-we/) where you can set a default zoom level. I usually use 200% on screens above 1080p.

**Comment by the-j0k3r** [comment]
I dont like distorting things with zoom levels, I could have also opted to use higher DPI but that is more distortion, neither look as natural as my current setup which has taken a long time to mature in most text based sites.

This is my best result sadly.
