### ISSUE TITLE
overflow of commit hash

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#727]
* **Browser**: FF 66.0.1
* **Operating System**: win 10 pro
* **Screenshot**:

![oveflow](https://user-images.githubusercontent.com/31389848/43621408-27395d9c-96cf-11e8-9342-3280a565efa0.gif)

* **HTML of the section where the issue occurs**:

click 9b5fa7e I can only dupe this in that commit for some reason and its present in default 

````html
<span class="sha user-select-contain">9b5fa7eeaa25028dc8c0f53849cffad002532272</span>
````

**Comment by Mottie** [comment]
I'm seriously not seeing any of the reported overflows... in either Chrome or Firefox.

**Comment by the-j0k3r** [comment]
And Im not making them up

**Comment by the-j0k3r** [comment]
Your OS?

**Comment by Mottie** [comment]
Windows 10, Firefox 61.0.1 (64-bit)

**Comment by the-j0k3r** [comment]
Its the minimum font setting in Firefox set to 14px that helps this issue be viisible, BUT only in that hash I point out, others its OK, so IDK, again.

Same OS here and Firefox version and bitness.

**Comment by silverwind** [comment]
Smells like a Firefox bug. Does my mentioned [alternative](https://github.com/StylishThemes/GitHub-Dark/issues/724#issuecomment-410258708) work for you?

**Comment by the-j0k3r** [comment]
You can read my response below there.

I dont know if it is a Firefox bug or what, because it is literally only on that commit https://github.com/StylishThemes/GitHub-Dark/commit/9b5fa7eeaa25028dc8c0f53849cffad002532272, others dont do that like for instance some random one like https://github.com/StylishThemes/GitHub-Dark/commit/5d17f8f83e29002b91eb6b004bd326cd01918929

![capture](https://user-images.githubusercontent.com/31389848/43654487-4793ac54-9743-11e8-8e68-2f9a7b5eaa2f.PNG)

And its there in default style with GHD disabled, which definetly rules out GHD, but I thought to report it in case we can find where the bug belongs.

It makes no sense, why one commit is whack the other isnt, maybe if I find more commits that break then maybe something makes itself obvious.

**Comment by silverwind** [comment]
Okay, I see it too in Firefox and Chrome. The line is simply not able to hold all content, nothing to do with our style. I'd certainly not want to start adding hacks for it, it's a Github bug.

<img width="378" alt="screenshot 2018-08-03 at 20 18 21" src="https://user-images.githubusercontent.com/115237/43658878-6513c072-975a-11e8-8665-29b71081189e.png">

**Comment by the-j0k3r** [comment]
Ah ah! GitHub bug, weird thats its just that one, very weird.

**Comment by the-j0k3r** [comment]
AH I figured it out,

That commit bugs out due to some of these occurrences in same place. You merged a PR from me and your commit was signed so the combination of your long nick + the verified label + message + hash + the minimum font size set to 14px was the perfect recipe.

**Comment by the-j0k3r** [comment]
I have a local script that reverts the GitHub font to previous so I was able to add a workaround that pretty much overrides Firefox minimum font size for that area, so far it seems to work OK. So Im happy.
