### ISSUE TITLE
Verified domain url has incorrect hover state

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#728]
A new feature was just released to add a `verified` badge to organizations that verify their domain. The page to do this has a url in a code block which shows an underline on hover that's not there by default.

https://blog.github.com/changelog/2018-08-07-domain-verification/

* **Browser**: chrome
* **Operating System**: win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/43841518-5d1272f2-9af1-11e8-8b0e-e7c03be4df13.png)

![image](https://user-images.githubusercontent.com/831974/43841551-6bec3b46-9af1-11e8-9389-d4b26d86b3d9.png)

* **HTML of the section where the issue occurs**:

````html
<span class="text-small text-mono bg-gray p-1 rounded-2">_github-challenge-******.******.com.</span>
````

This is the rule that's causing it:

```css
.text-mono:hover {
  ...;
}
```

**Comment by silverwind** [comment]
Removed all these underline styles, they were added a long time ago and I don't find them in GH's sheet, so probably not useful.
