### ISSUE TITLE
collapsed line in diff should be use diffrence color

### ISSUE THREAD

**Issue by qwIvan** [StylishThemes/GitHub-Dark#731]
![image](https://user-images.githubusercontent.com/7613160/43929986-c01d369c-9c69-11e8-9c44-d1181cc68348.png)
![image](https://user-images.githubusercontent.com/7613160/43930000-ce7cee58-9c69-11e8-8a96-403134d4fae1.png)

Otherwise it will difficult to detect.

**Comment by Mottie** [comment]
If we completely remove the `.blob-num[colspan]` selector (set as `#1c1c1c`), the background color becomes the darker blue version, but hovering the button is still the base color.

![](https://user-images.githubusercontent.com/136959/43937429-2d25a31a-9c23-11e8-8bc3-39a5aad5bb46.png)

Maybe we could set the `.blob-num[colspan]` to `#333`?

![](https://user-images.githubusercontent.com/136959/43937519-c59dd392-9c23-11e8-907f-64c220d73f7c.png)

**Comment by Mottie** [comment]
I went with using `#333` since the change from blue to base-color doesn't make sense.

**Comment by qwIvan** [comment]
![image](https://user-images.githubusercontent.com/7613160/43949632-ae3f8108-9cc0-11e8-90c1-de08872d4ab4.png)
@the-j0k3r Yes, color of these line is more lighter shade, but these color are same with modified lines.
