### ISSUE TITLE
Danger zone isn't very dangerous

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#734]
The red border of the `.Box--danger` class isn't being applied and there's a bottom border added to the header container which contains the modifier class `.border-bottom-0` that should remove the border so the red border shows through.

* **Browser**: chrome
* **Operating System**: win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/44285089-f60dd900-a231-11e8-80f9-975ff401b85c.png)

![image](https://user-images.githubusercontent.com/831974/44285101-032ac800-a232-11e8-8c71-3ae56058f769.png)

* **HTML of the section where the issue occurs**:

````html
<div class="Subhead Subhead--spacious border-bottom-0 mb-0">
  <h2 class="Subhead-heading">
    Danger Zone
  </h2>
</div>

<div class="Box Box--danger">
  <ul>
    <li class="Box-row">
    </li>
  </ul>
</div>
````

**Comment by xt0rted** [comment]
The `.border-bottom-0` modifier is an issue on the Features section as well

![image](https://user-images.githubusercontent.com/831974/44285413-36ba2200-a233-11e8-819a-893f77605133.png)

**Comment by Mottie** [comment]
Hi @xt0rted!

Thanks for reporting this problem. We can remove the `.Subhead` border, it shouldn't be added.
