### ISSUE TITLE
Beta label for activity overview option isn't green

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#735]
A new feature was just released on your profile page. So far the beta label looks to be the only incorrectly styled element on here. This same label shows on the beta dashboard at https://github.com and isn't green there either.

https://blog.github.com/changelog/2018-08-24-profile-activity-overview/

* **Browser**: chrome
* **Operating System**: win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/44606619-b7d96200-a7bb-11e8-997b-4fed3a494717.png)

![image](https://user-images.githubusercontent.com/831974/44606601-a85a1900-a7bb-11e8-90c3-aa7bbb0b3e4a.png)

* **HTML of the section where the issue occurs**:

````html
<form class="d-inline-block" action="/beta_enrollments" accept-charset="UTF-8" method="post">
  <input name="utf8" type="hidden" value="?">
  <input type="hidden" name="_method" value="delete">
  <input type="hidden" name="authenticity_token" value="...">
  <input type="hidden" name="feature" value="org_scoped_activity">
  <button type="submit" class="dropdown-item ws-normal btn-link text-left pl-5">
    <svg class="octicon octicon-check select-menu-item-icon mt-1" viewBox="0 0 12 16" version="1.1" width="12" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M12 5l-8 8-4-4 1.5-1.5L4 10l6.5-6.5L12 5z"></path></svg>
    <div class="d-flex flex-items-center text-bold">
      Activity overview
      <span class="f6 d-inline-block px-1 ml-2 rounded-1 border border-green text-normal">Beta</span>
    </div>
    <span class="f6 mt-1">
        Turning off the activity overview will hide the section on your profile.
    </span>
  </button>
</form>
````

**Comment by xt0rted** [comment]
I guess the new chart could be changed to blue instead of green, haven't looked into that though.

**Comment by Mottie** [comment]
Thanks @xt0rted!

**Comment by Mottie** [comment]
I think it was meant to be green, not the base-color.
