### ISSUE TITLE
Page not found text is hard to read

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#736]
An incorrect link was published on the blog earlier. Looks like the text isn't styled yet so it's hard to read.

* **Browser**: chrome
* **Operating System**: win10
* **Link**: https://developer.github.com/changes/2018-08-28-user-level-permissions-for-github-apps
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/44621909-be7bde00-a87c-11e8-9faf-23887c9cb313.png)

* **HTML of the section where the issue occurs**:

````html
<div class="container">
  <section class="main pt-5 clearfix gut-3" role="main">
    <div class="content col-md-8">
      <div class="not-found-container">
        <h2>
          <a id="whoops-looks-like-that-page-doesnt-exist" class="anchor" href="#whoops-looks-like-that-page-doesnt-exist" aria-hidden="true"><span aria-hidden="true" class="octicon octicon-link"></span></a>
          Whoops, looks like that page doesn't exist.
        </h2>
      </div>
    </div>
  </section>
</div>
````

**Comment by Mottie** [comment]
Hi @xt0rted!

Fixed in https://github.com/StylishThemes/GitHub-Dark/commit/d86ffba0a7e1a233bc2e0c28cbe5f864d285d44a, but the new replacements also include all `h1` through `h5`, so we'd need to test to make sure it doesn't mess up anything else before we release the next version.

**Comment by xt0rted** [comment]
A new version was released with this fix. I've yet to notice any issues with it.

**Comment by silverwind** [comment]
Looks fine to me :shipit:
