### ISSUE TITLE
Review comment being edited has an orange border

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#737]
Not sure if this is an issue or not, but when you edit a review comment the `.review-summary-form-wrapper` element has an orange border applied. The default style has this light grey.

The change was made about 2 years ago but I'm not sure if/when the default style changed. I can try asking about this but there's no guarantee I'll be able to get a response on it.

https://github.com/StylishThemes/GitHub-Dark/blob/941db69ef01a50a292d30be49f0833e2c460c61f/github-dark.css#L3168-L3170

To repro this go to a PR's `Files changed` tab and select `Review changes` and add a comment. Go back to the `Conversation` tab and select edit on the comment.

* **Browser**: chrome
* **Operating System**: win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/44695142-b324e000-aa3f-11e8-9462-1184a9310fc0.png)

![image](https://user-images.githubusercontent.com/831974/44695685-5b3ba880-aa42-11e8-89be-d290acd45d87.png)

* **HTML of the section where the issue occurs**:

````html
...
````

**Comment by Mottie** [comment]
Hi @xt0rted!

Thanks for reporting this issue. I think we should just remove the selector since it's already being modified by the auto-generated rules (border set to `#343434`).
