### ISSUE TITLE
User profile bugfix no longer needed

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#738]
The fix added in 58bc50661f2e8362486898354cc074a6ee2c777c is no longer needed according to the comments in the original issue at https://github.com/isaacs/github/issues/934#issuecomment-373466586

https://github.com/StylishThemes/GitHub-Dark/blob/0c0e6ef20482c9c2a342945b6365cbce09a2910c/github-dark.css#L1566-L1570

**Comment by silverwind** [comment]
Does not show anymore on the linked org page. I assume this was fixed pretty quickly by GitHub, thanks for noticing.
