### ISSUE TITLE
Table background

### ISSUE THREAD

**Issue by stonecrusher** [StylishThemes/GitHub-Dark#740]
* **Browser**: FF 62.0
* **Operating System**: Win8.1
* **GitHub Dark Version**: 1.20.68
* **Screenshot**: 
![2018-09-12 14_31_34-options openstyles_stylus wiki url_ https___github com_openstyles_stylus_w](https://user-images.githubusercontent.com/1388389/45425213-fcf50380-b698-11e8-938f-607957c3f392.png)
([Link to example](https://github.com/openstyles/stylus/wiki/Options#toolbar-icon))

The current selector `table` darkens the space right of the table instead of showing the page background there. Depending on your screen preferences it may not be very visible to you, so I put a red frame to the second table to show.

Maybe the `table` selector can be dropped completely as alternatives like `table tr` and `table tr:nth-child(2n)` are already defined and shouldn't be overwritten by something like `table *`.

**Comment by Mottie** [comment]
Hi @stonecrusher!

Yeah, it looks like it'll work if the `table` background definition is completely removed. I'll update the master branch, and it'll be available in the next update.
