### ISSUE TITLE
Colour encoding on commit graph is the opposite of original GitHub styles

### ISSUE THREAD

**Issue by nwarwick** [StylishThemes/GitHub-Dark#741]
Colour encoding for the commit graph could be updated to match better with the original styling. E.g. GitHub normally represents days with more commits as a darker square, whereas lighter squares represent days with less commits. Although I like the blue theme, I think it would be nice to keep this the same.

![screen shot 2018-09-13 at 11 41 33 am](https://user-images.githubusercontent.com/7636254/45499414-63862a00-b74a-11e8-8980-7f0ea68317f4.png)

````html
<g transform="translate(561, 0)">
          <rect class="day" width="8" height="8" x="-40" y="0" fill="#7bc96f" data-count="5" data-date="2018-09-02"></rect>
          <rect class="day" width="8" height="8" x="-40" y="10" fill="#c6e48b" data-count="4" data-date="2018-09-03"></rect>
          <rect class="day" width="8" height="8" x="-40" y="20" fill="#c6e48b" data-count="1" data-date="2018-09-04"></rect>
          <rect class="day" width="8" height="8" x="-40" y="30" fill="#c6e48b" data-count="1" data-date="2018-09-05"></rect>
          <rect class="day" width="8" height="8" x="-40" y="40" fill="#7bc96f" data-count="7" data-date="2018-09-06"></rect>
          <rect class="day" width="8" height="8" x="-40" y="50" fill="#239a3b" data-count="10" data-date="2018-09-07"></rect>
          <rect class="day" width="8" height="8" x="-40" y="60" fill="#c6e48b" data-count="1" data-date="2018-09-08"></rect>
</g>
````

**Comment by silverwind** [comment]
I don't agree. In a dark theme it's usually best to invert the brightness on everything, so light things go dark and vice versa  and I think the contribution calendar is a good example of it done right.

**Comment by nwarwick** [comment]
In this case the theme is changing the way users visually parse information from something. A dark theme doesn't have to invert everything. It just has to be dark, look good, and be readable.

**Comment by qubidt** [comment]
A dark theme is fundamentally different from a light one. This wouldn't make any sense.

> changing the way users visually parse information

That's the opposite of what is happening. Making the days with the most commits darker would invert the relationship between the calendar colors and the background in terms of contrast. It would be completely unintuitive that the squares with the least contrast are the most notable ones.

**Comment by Mottie** [comment]
I agree with Silverwind. In addition, no matter what base color is chosen, the legend under the contribution graph shows the colors so that should minimize any difficulty in visually parsing the info.

![legend](https://user-images.githubusercontent.com/136959/46341679-7334b800-c5fe-11e8-97df-92fefe20db29.png)
