### ISSUE TITLE
Alert notes are hard to read

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#746]
* **Browser**: chrome
* **Operating System**: win10
* **Url**: https://developer.github.com/changes/2018-04-25-github-services-deprecation/
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/46336067-ad4e8b80-c5f7-11e8-8146-a876b9c25e40.png)

* **HTML of the section where the issue occurs**:

````html
<div class="alert note">

<p><strong>Note</strong>: We no longer support GitHub Services as of October 1, 2018, and GitHub Services will stop working on January 31, 2019. Please see the <a href="/changes/2018-10-01-denying-new-github-services">blog post</a> for details. You can use the <a href="/v3/guides/replacing-github-services">Replacing GitHub Services guide</a> to help you update your services to webhooks.</p>

</div>
````

**Comment by Mottie** [comment]
Thanks for letting us know... fixed in master.
