### ISSUE TITLE
Compare changes search results has incorrect icon color on hover

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#750]
* **Browser**: chrome
* **Operating System**: win10
* **How to repro**: go to https://github.com/StylishThemes/GitHub-Dark/compare and then in the branch drop down type `s`. The last item in the list will be your search term with the icon next to it.
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/46626669-004ba580-cb06-11e8-93b0-0ec24df18eb3.png)

![image](https://user-images.githubusercontent.com/831974/46626646-f033c600-cb05-11e8-862b-5100e418c8bc.png)

* **HTML of the section where the issue occurs**:

````html
<form class="js-commitish-form" action="/org/repo/compare/master...xt0rted:master" accept-charset="UTF-8" method="get">
  <input name="utf8" type="hidden" value="?">
  <input type="hidden" name="new_compare_type" value="head">
  <div class="select-menu-item select-menu-new-item-form js-navigation-item js-new-item-form last-visible navigation-focus" aria-selected="true">
    <svg class="octicon octicon-history select-menu-item-icon" viewBox="0 0 14 16" version="1.1" width="14" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M8 13H6V6h5v2H8v5zM7 1C4.81 1 2.87 2.02 1.59 3.59L0 2v4h4L2.5 4.5C3.55 3.17 5.17 2.3 7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-.34.03-.67.09-1H.08C.03 7.33 0 7.66 0 8c0 3.86 3.14 7 7 7s7-3.14 7-7-3.14-7-7-7z"></path></svg>
    <div class="select-menu-item-text">
      <span class="js-new-item-name">ray</span>
    </div>
  </div>
</form>
````

**Comment by Mottie** [comment]
Hi @xt0rted!

Thanks for reporting this problem. It's been fixed in the master branch.
