### ISSUE TITLE
Delete GitHub App button text is not red

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#753]
The hover & focus colors are all correct, it's just the default state where the text isn't the right color.

There's a style for `.btn-danger` but the text color from this is being replaced by the rule `input:not(.btn-link)`

This is found under https://github.com/organizations/StylishThemes/settings/installations then click `Configure` on any of the installed apps.

* **Browser**: chrome
* **Operating System**: win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/46705932-db3b5d80-cbff-11e8-9ceb-d47a8422f3b0.png)

![image](https://user-images.githubusercontent.com/831974/46705921-c78ff700-cbff-11e8-9b94-97cf37e9a7f2.png)

* **HTML of the section where the issue occurs**:

````html
<input class="btn btn-danger" data-confirm="This action cannot be undone. Are you sure you want to uninstall this GitHub App from 11 repositories?" type="submit" value="Uninstall">
````

**Comment by Mottie** [comment]
Thanks @xt0rted! It's been fixed in master.
