### ISSUE TITLE
Blue marketing button has wrong text color

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#757]
There's a secondary issue on this page which is a massive white box on the left side on larger screens.

* **Browser**: chrome
* **Operating System**: win10
* **URL**: https://github.com/features/actions
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/47045401-b5aed680-d160-11e8-8040-0317a0b90082.png)

* **HTML of the section where the issue occurs**:

````html
<a href="/features/actions/signup" class="btn-mktg f4 px-5">Sign up for the beta</a>
````

This is the element that's white. Making the background transparent fixes it.

```html
<div class="actions-bg-mask position-absolute top-0 bottom-0 width-full"></div>
```

**Comment by Mottie** [comment]
Hi @xt0rted!

Thanks for reporting this problem!
