### ISSUE TITLE
Auto-removing style?

### ISSUE THREAD

**Issue by advaith1** [StylishThemes/GitHub-Dark#763]
* **Browser**: Google Chrome Version 72.0.3593.0
* **Operating System**: macOS Mojave Version 10.14 (18A391)

This style used to work perfectly. However, today I noticed that this seems to be uninstalled on page load. Whenever I reinstall the style it is applied, but when I reload GitHub it gets uninstalled. I'm using the [Stylus](https://chrome.google.com/webstore/detail/clngdbkpkpeebahjckkjfobafhncgmne) extension. This wasn't an issue until today, and yesterday GitHub became part of Microsoft, maybe they added some code to remove userstyles?

The GitHub Dark Script seems to be unaffected.

**Comment by Mottie** [comment]
Hi @advaith1!

We're only providing the userstyle (CSS) here. This problem sounds more like it might be an issue to open up in [Stylus' repo](https://github.com/openstyles/stylus). Please describe how to reproduce the problem there.

**Comment by silverwind** [comment]
> maybe they added some code to remove userstyles

Sites cannot uninstall styles fortunately. Check if you can reproduce using other styles or sites, if so, it's most likely a Stylus issue.
