### ISSUE TITLE
Transfer issue dialog z-index problem

### ISSUE THREAD

**Issue by aNNiMON** [StylishThemes/GitHub-Dark#766]
* **Browser**: Firefox 63.0.1
* **Operating System**: Arch Linux
* **Screenshot**:
![sl-normal](https://user-images.githubusercontent.com/1321838/47918585-a98f7c80-deb5-11e8-8ae8-59e90aad171e.gif)
![sl-dark](https://user-images.githubusercontent.com/1321838/47918593-b0b68a80-deb5-11e8-9ae7-2290ce29069d.gif)

![image](https://user-images.githubusercontent.com/1321838/47919152-50c0e380-deb7-11e8-8e05-1da06b5a15b7.png)

* **HTML of the section where the issue occurs**:
 <details>
  <summary>&lt;details-dialog&gt;</summary>

````html
<details-dialog class="anim-fade-in fast Box Box--overlay text-gray-dark f5" aria-labelledby="lock-dialog-title" role="dialog" tabindex="-1">
      <form action="<hidden>/issues/2/transfer" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="<hidden>">
  <input type="hidden" name="issue_id" value="<hidden>">
  <div class="Box-header">
    <button class="Box-btn-octicon btn-octicon float-right" type="button" aria-label="Close dialog" data-close-dialog="">
      <svg class="octicon octicon-x" viewBox="0 0 12 16" version="1.1" width="12" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.48 8l3.75 3.75-1.48 1.48L6 9.48l-3.75 3.75-1.48-1.48L4.52 8 .77 4.25l1.48-1.48L6 6.52l3.75-3.75 1.48 1.48L7.48 8z"></path></svg>
    </button>
    <h3 id="lock-dialog-title" class="Box-title">
      Transfer this issue
      <span class="border border-green rounded-1 mx-2 px-1 f6">Beta</span>
    </h3>
  </div>
  <div class="Box-body p-3">
    <div class="select-menu js-menu-container js-select-menu">
      <button class="btn select-menu-button js-menu-target" type="button" aria-haspopup="true" aria-expanded="false">
        <i>Repository:</i>
        <span class="js-select-button">Choose a repository</span>
      </button>
      <div class="select-menu-modal-holder js-menu-content js-navigation-container" style="top: auto; right: auto">
        <div class="select-menu-modal">
          <div class="select-menu-header" tabindex="-1">
            <button class="btn-link close-button js-menu-close" type="button"><svg aria-label="Close menu" class="octicon octicon-x" viewBox="0 0 12 16" version="1.1" width="12" height="16" role="img"><path fill-rule="evenodd" d="M7.48 8l3.75 3.75-1.48 1.48L6 9.48l-3.75 3.75-1.48-1.48L4.52 8 .77 4.25l1.48-1.48L6 6.52l3.75-3.75 1.48 1.48L7.48 8z"></path></svg></button>
            <span class="select-menu-title">Options</span>
          </div>
          <div class="js-select-menu-deferred-content">
            <div class="select-menu-filters">
              <div class="select-menu-text-filter">
                <input type="text" id="example-filter-field" class="form-control js-filterable-field js-navigation-enable" placeholder="Filter this list" aria-label="Type to filter" autocomplete="off">
              </div>
            </div>
            <div class="select-menu-list" data-filterable-for="example-filter-field" data-filterable-type="substring">
              <input type="hidden" name="example" value="">
                <div class="select-menu-item js-navigation-item">
                  <input type="radio" name="repository_id" value="<hidden>" required="">
                  <svg class="octicon octicon-check select-menu-item-icon" viewBox="0 0 12 16" version="1.1" width="12" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M12 5l-8 8-4-4 1.5-1.5L4 10l6.5-6.5L12 5z"></path></svg>
                  <div class="select-menu-item-text js-select-button-text">
                    Project 1
                  </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="Box-footer">
    <button type="submit" class="btn btn-block" data-disable-with="Transferring issue…" data-disable-invalid="" disabled="">
      Transfer issue
    </button>
  </div>
</form>
    </details-dialog>
````

</details>

**Comment by xt0rted** [comment]
I can repro this in Chrome on Windows. It's being caused by:

```css
.discussion-sidebar {
  position: sticky !important;
  top: 0 !important;
}
```

The modal is inside of that container which has a `z-index` of 21, and `.pagehead-actions` is 31. Changing the `z-index` of `.discussion-sidebar` to be 31+ fixes the issue. Not sure if it'll negatively affect anything else though.

The other thing I'm noticing is this side bar isn't actually sticky anymore. If that rule is removed the issue goes away. So we need to either change the `z-index` of the side bar or remove the `position: sticky` from it.

**Comment by aNNiMON** [comment]
Adding `z-index: 33` partially fixes this issue, but hovering on a dialog is still required:
https://gfycat.com/unimportantmenacinggossamerwingedbutterfly

**Comment by xt0rted** [comment]
The modal doesn't cut off for me in Chrome, but does in Firefox.

From what I've read `position: sticky` creates a new stacking context consisting of the sticky element's container and the overlay & modal are positioned inside of this. When you scroll up you'll see that the overlay stops at the top of the side bar's container and that's where the modal starts to get cut off.

These elements are set to `position: fixed` and to be positioned at the top of their container. In Chrome this container always fills the screen when you scroll, but in Firefox it doesn't until you do something to cause a repaint and that's when the modal shows up again.

This behavior looks like a bug in Firefox.

**Comment by Mottie** [comment]
Please try adding this CSS after the snippet that @xt0rted shared and see if it helps:

```css
.discussion-sidebar .Box {
  top: 10% !important;
}
```

Setting the `top` moves the window down a bit. I wasn't encountering the z-index issue, but I'm not using Linux so I don't know.

**Comment by xt0rted** [comment]
@Mottie I can repro in Firefox on Windows so it's not Linux specific

**Comment by xt0rted** [comment]
This issue happens in the other direction too. If you scroll to the top of the page and open the modal, as you scroll down the overlay starts to scroll with the page. Once you do something to cause a reflow/repaint then the overlay updates to fill the whole screen.

**Comment by the-j0k3r** [comment]
I cant find

```css
.discussion-sidebar {
  position: sticky !important;
  top: 0 !important;
}
```
So can we retest this with latest release?

**Comment by xt0rted** [comment]
This isn't an issue anymore since we removed the sticky sidebar. I'm sure it's still an issue when using [StylishThemes/GitHub-Sticky-Sidebar](https://github.com/StylishThemes/GitHub-Sticky-Sidebar) but it looks like a browser bug and not something we could fix with a css hacks. Either way it's not an issue for this repo anymore.
