### ISSUE TITLE
Extra horizontal line when creating issues

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#770]
* **Browser**: chrome
* **Operating System**: win10
* **Url**: [choose a template ](https://github.com/appveyor/ci/issues/new/choose), [using a template](https://github.com/appveyor/ci/issues/new?labels=&template=bug_report.md), [when you can edit labels etc.](https://github.com/StylishThemes/GitHub-Dark/issues/new)
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/48528100-81136500-e85b-11e8-8180-5ae4a4129661.png)

![image](https://user-images.githubusercontent.com/831974/48527820-75736e80-e85a-11e8-963d-643923d2fecf.png)

![image](https://user-images.githubusercontent.com/831974/48528030-3db8f680-e85b-11e8-9093-45fe30e05c74.png)

* **HTML of the section where the issue occurs**:

```css
.new-issue-form {
  border-top: 1px solid #343434 !important;
}
```

````html
<div class="discussion-timeline new-issue-form">
  ...
</div>
````

```html
<div class="new-issue-form" data-issue-and-pr-hovercards-enabled="">
  ...
</div>
```

**Comment by Mottie** [comment]
Hi @xt0rted!

Thanks! Fixed.
