### ISSUE TITLE
Make file headers sticky on commit and compare view just like on PR file list

### ISSUE THREAD

**Issue by ght** [StylishThemes/GitHub-Dark#771]
The sticky file headers requested for the PR file list in #531 and implemented in 5b91c21f18 are very useful.

Please make the file headers sticky on [commit](../commit/fdbd89afd6) and [compare](../compare/master@{5day}...master) pages too, so you always see what file you are looking at.

**Comment by Mottie** [comment]
I like it!

We already have this available in our [Fixed header style](https://github.com/StylishThemes/GitHub-FixedHeader); and there is some controversy about even including a sticky header style in GitHub-Dark by default - see [#730](https://github.com/StylishThemes/GitHub-Dark/pull/730#issuecomment-413291477), so I don't know how others (*cough* @the-j0k3r) would feel about this PR.

**Comment by silverwind** [comment]
I get a headache even thinking about https://github.com/StylishThemes/GitHub-Dark/pull/730#issuecomment-413291477, @Mottie if you like them, why not create a addon style for them? :)

**Comment by Mottie** [comment]
The fixed header style already includes all of this (I think)... we could just remove it from GHD completely.

**Comment by silverwind** [comment]
Ah, yes then please go ahead and remove it from GHD.

**Comment by xt0rted** [comment]
I tried using the sticky header style but since it made the main nav sticky I removed it (only wanted the file headers). If we're moving this out of GHD can we make the main nav optional?

**Comment by Mottie** [comment]
> can we make the main nav optional

Sure!

**Comment by the-j0k3r** [comment]
>  so I don't know how others (_cough_ @the-j0k3r) would feel about this PR.

I would agree with @Mottie and @silverwind that its time to remove this from GHD and make it its own style :)

**Comment by the-j0k3r** [comment]
See #819, Its grief pure and simple.

**Comment by the-j0k3r** [comment]
65f3e82b1c8e9c3d09ee7aa73840577ee0c38021 has been merged which removes this problematic tweak, please add as a standalone style, @Mottie @Silverwind are we using https://github.com/StylishThemes/GitHub-FixedHeader to add this and what 65f3e82b1c8 removed  too?
