### ISSUE TITLE
The Github Community page isn't styled at all

### ISSUE THREAD

**Issue by Serkan-devel** [StylishThemes/GitHub-Dark#775]
Styles aren't applied here https://github.community/

**Comment by Mottie** [comment]
Hi @Serkan-devel!

Please try out https://github.com/StylishThemes/GitHub-Community-Dark

**Comment by Serkan-devel** [comment]
Shouldn't this be included into the same style? Both sites operate for the same community and look similar

**Comment by Mottie** [comment]
The class names are all different; and given that the GitHub Dark UserCSS version is over 400KB in size, it'd be better to keep this entirely different site (it's a different domain even) separate.
