### ISSUE TITLE
Url inputs don't have correct focus state

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#776]
* **Browser**: chrome
* **Operating System**: win10
* **Url**: https://github.com/settings/profile
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/49150132-fe1df000-f2d9-11e8-9641-5d33216830ea.png)

* **HTML of the section where the issue occurs**:

````html
<input type="url" class="form-control" value="" name="user[profile_blog]" id="user_profile_blog">
````

**Comment by Mottie** [comment]
Hi @xt0rted!

Thanks! Fixed in the master.
