### ISSUE TITLE
Watch repo option descriptions are darker on hover than they used to be

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#778]
Since the `Releases only` watch option was added a few days ago the option descriptions seem darker on hover compared to in other areas.

* **Browser**: chrome
* **Operating System**: win10
* **Url**: https://github.com/StylishThemes/GitHub-Dark and https://github.com/StylishThemes/GitHub-Dark/settings
* **Screenshot**:

How it used to look

![image](https://user-images.githubusercontent.com/831974/49245864-8935dd80-f3e1-11e8-886f-6ec23220ac74.png)

How it looks now

![image](https://user-images.githubusercontent.com/831974/49245912-a9fe3300-f3e1-11e8-8619-9512024ee0d6.png)

* **HTML of the section where the issue occurs**:

````html
<button type="submit" name="do" value="included" class="select-menu-item width-full" aria-checked="false" role="menuitemradio">
  <svg class="octicon octicon-check select-menu-item-icon" viewBox="0 0 12 16" version="1.1" width="12" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M12 5l-8 8-4-4 1.5-1.5L4 10l6.5-6.5L12 5z"></path></svg>
  <div class="select-menu-item-text">
    <span class="select-menu-item-heading">Not watching</span>
    <span class="description">Be notified only when participating or @mentioned.</span>
    <span class="hidden-select-button-text" data-menu-button-contents="">
      <svg class="octicon octicon-eye v-align-text-bottom" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M8.06 2C3 2 0 8 0 8s3 6 8.06 6C13 14 16 8 16 8s-3-6-7.94-6zM8 12c-2.2 0-4-1.78-4-4 0-2.2 1.8-4 4-4 2.22 0 4 1.8 4 4 0 2.22-1.78 4-4 4zm2-4c0 1.11-.89 2-2 2-1.11 0-2-.89-2-2 0-1.11.89-2 2-2 1.11 0 2 .89 2 2z"></path></svg>
      Watch
    </span>
  </div>
</button>
````

**Comment by Mottie** [comment]
Hi @xt0rted!

Thanks for reporting this issue.
