### ISSUE TITLE
Milestone open/closed tabs have a white border

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#779]
* **Browser**: chrome
* **Operating System**: win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/49246571-437a1480-f3e3-11e8-8077-d0eedf9eb49b.png)

![image](https://user-images.githubusercontent.com/831974/49246689-84722900-f3e3-11e8-9bfc-7c721303ee56.png)

* **HTML of the section where the issue occurs**:

````html
<div class="select-menu-tabs" role="tablist">
  <ul>
    <li class="select-menu-tab">
      <button type="button" role="tab" class="select-menu-tab-nav" aria-selected="true">Open</button>
    </li>
    <li class="select-menu-tab">
      <button type="button" role="tab" class="select-menu-tab-nav" aria-selected="false" tabindex="-1">Closed</button>
    </li>
  </ul>
</div>
````

**Comment by xt0rted** [comment]
Looks like the Projects dropdown has the same tabs, but they're colored correctly.

The difference in the markup seems to be the removal of css classes to identify their state. Newer html/components are moving away from classes and over to `aria-*` attributes as a way to ensure/force accessibility.

![image](https://user-images.githubusercontent.com/831974/49247032-49242a00-f3e4-11e8-8352-36da8a3a928f.png)

```html
<div class="select-menu-tabs">
    <ul>
      <li class="select-menu-tab">
        <button type="button" data-tab-filter="tab-recent" class="select-menu-tab-nav js-select-menu-tab selected" aria-current="true">Recent</button>
      </li>

        <li class="select-menu-tab">
          <button type="button" data-tab-filter="tab-repository" class="select-menu-tab-nav js-select-menu-tab" aria-current="false">Repository</button>
        </li>

        <li class="select-menu-tab">
          <button type="button" data-tab-filter="tab-organization" class="select-menu-tab-nav js-select-menu-tab" aria-current="false">Organization</button>
        </li>

    </ul>
  </div>
```

**Comment by Mottie** [comment]
Hi @xt0rted!

Thanks for reporting this issue.

**Comment by xt0rted** [comment]
@Mottie I'm running the latest version but still seeing this issue

**Comment by xt0rted** [comment]
The latest release is from a day before this was fixed. Nothing to see here.
