### ISSUE TITLE
Browser extensions for dark theme

### ISSUE THREAD

**Issue by iliyaZelenko** [StylishThemes/GitHub-Dark#780]
Hi, I could try to write browser extensions that include a dark theme, I have experience in this area.
Or has someone done this before me? 

I saw an extension in the Chrome Store which includes a black theme and used it myself and noticed that there are a lot of mistakes, your styles look better. 

Can I start making extensions based on your styles?

**Comment by silverwind** [comment]
I don't see a need to have an extension. We have the CSS version (this repo) and also a Userscript version (https://github.com/StylishThemes/GitHub-Dark-Script), which should cover pretty much all browsers. A extension would require maintenance (to stay compatible with browser APIs) and does not allow the user to edit, which I see as a big drawback.

I guess I cannot stop you from making a extension, but I certainly would not support such an endeavour.

**Comment by Mottie** [comment]
Hi @iliyaZelenko!

There are a bunch of [global dark extensions](https://github.com/openstyles/stylus/wiki/Stylish-alternatives#global-dark-extensions), one of which named [Dark Night Mode](https://github.com/DarkNightMode/Dark-Night-Mode-Chrome-Extension) uses a "new algorithm" to darken websites. The "algorithm" for GitHub is to use our GitHub Dark theme LOL.

**Comment by iliyaZelenko** [comment]
Hi, I agree with you. But there are people who don’t know Stylus and don’t want to understand its settings. Search for styles somewhere, I do not argue that this is a cool tool and very flexible, but many people just want to drive into the search for "github dark" and easily put on a beautiful dark theme.

 I will try to create an extension, even more just by interest, I don’t need to write any special scripts (except for the GitHub-Dark-Script, it would be cool to write such a thing, but now I'm not going to do it), the most important is the styles, and they are already written for me. I will report here when I post an extension, see if it will be interesting for people. 

@Mottie Thank you, I took for myself one cool extension, it changes the theme well. But the handwritten styles will always be better worked out.
