### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#782]
I just got access to https://github.com/features/actions. Do you want me to start collecting feedback for this, and if so do you want it all in one issue or one thing per issue?

**Comment by Mottie** [comment]
All in one would be easier to manage... You willing to help out? 😁

**Comment by xt0rted** [comment]
The editor for actions loads in an iframe from `https://launch-editor.github.com` which explains why nothing in it was dark. Once I added that to the url rule things got a little better, but not by much.

The current stylesheet is https://launch-editor-assets.githubusercontent.com/_next/static/css/commons.d076a817.chunk.css. They're using webpack/react for the site so this might be annoying to work with. The filenames will have a hash that changes every time the contents changes, and there's `.jsx-#######` class names which I think change with each build.

**Comment by xt0rted** [comment]
Yea I can try. I've been working on another dark theme lately so hopefully I won't screw anything up too bad https://github.com/xt0rted/Harvest-Dark

**Comment by Mottie** [comment]
Hmm, it still looks like it's based on primer... hopefully it won't be too bad.

**Comment by xt0rted** [comment]
Some commit messages have a prefix and others don't, is there a preferred way of doing this?

**Comment by xt0rted** [comment]
I was referring to the `Themes:`, `Meta:`, `Settings:` prefix they have

**Comment by xt0rted** [comment]
This is what the editor page looks like currently. The top section with the buttons, and the side bar with the tabs, do we want those to have a background color or should they be left transparent?

The new dashboard has as similar style to this page but was made transparent. In this instance I think it might be better to give these sections a background color. What are your thoughts?

![image](https://user-images.githubusercontent.com/831974/49604348-a88db700-f95b-11e8-982c-79da4f3d0b4c.png)

![image](https://user-images.githubusercontent.com/831974/49604001-c3136080-f95a-11e8-8c10-e4db48521f97.png)

Some good news is the `Edit new file` and `Preview` tabs use existing styles and look fine. It's just the visual editor that needs some styling along with the `Start commit` dropdown.

**Comment by silverwind** [comment]
I'd do `#181818` for top and sidebar and `#202020` for the action card area.

**Comment by xt0rted** [comment]
Fully styling this is going to be a real pain. A lot of the class names are dynamic so we'll have to rely on the generation script to swap colors (I'm sure this'll break with almost every update they make though). The really annoying thing is just how much inline styling there is. Hopefully this changes as the feature moves out of beta.

```html
<div class="jsx-4068269804 editor-node position-relative mx-4 f6 rounded-2 lh-condensed text-white" style="width: 260px; margin-bottom: 80px; cursor: auto; background-color: rgb(68, 77, 85); z-index: 1; border: 1px solid rgb(35, 41, 46); box-shadow: rgba(27, 31, 35, 0.4) 0px 1px 15px;">
    <div class="jsx-4068269804 p-3">
        <h5 class="css-iu9met">New workflow</h5>
        <h6 class="css-1nzzweh">on <span class="jsx-4068269804 text-white text-semibold">push</span></h6>
    </div>
    <div class="jsx-4068269804 flow-footer d-flex flex-items-center flex-justify-between flex-auto py-2 px-3">
        <div class="jsx-4068269804"></div>
        <div class="jsx-4068269804">
            <div class="d-inline-block">
                <button class="text-white css-15cskdj" blacklist="css,color,bg,m,mt,mr,mb,ml,mx,my,p,pt,pr,pb,pl,px,py,fontFamily,fontSize,fontWeight,lineHeight,textAlign" color="blue.5">Edit</button>
            </div>
        </div>
    </div>
    <div class="jsx-3904261368 ">
        <div class="jsx-3724960542 port position-absolute d-inline-block circle output event live">
            <div class="jsx-3726811500 d-inline-block circle position-relative"></div>
        </div>
    </div>
</div>
```

```html
<div class="editor-node flex-shrink-0 d-inline-block position-relative mx-4 f6 rounded-2 bg-gray" style="cursor: auto; width: 260px; margin-bottom: 80px; z-index: 1; border: 1px dashed rgb(3, 102, 214); box-shadow: rgba(3, 102, 214, 0.3) 0px 0px 0px 0.2em;">
    <div class="jsx-3724960542 port position-absolute d-inline-block circle input isEditing isGhost"></div>
    <div class="jsx-151674343 d-flex flex-items-center flex-justify-between flex-auto lh-condensed py-2 px-3 v-mid" style="border-top-right-radius: 6px; border-top-left-radius: 6px; border-bottom: 1px dashed rgb(149, 157, 165);">
        <div class="jsx-151674343 d-flex flex-items-center flex-justify-between width-full">
            <div class="jsx-151674343"></div>
            <div class="jsx-151674343">
                <div class="css-k0pacu CircleBadge" bg="" blacklist="css,color,bg,m,mt,mr,mb,ml,mx,my,p,pt,pr,pb,pl,px,py" style="background-color: transparent; width: 48px; height: 48px; border: 1px dashed rgb(149, 157, 165); box-shadow: none;"><span class="CircleBadge-icon jsx-2868147874"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="d-flex flex-justify-center p-3" style="height: 153px;">
        <div></div>
        <div class="d-flex flex-items-center">
            <div class="d-inline-block">
                <button class="f5 text-bold css-15cskdj" blacklist="css,color,bg,m,mt,mr,mb,ml,mx,my,p,pt,pr,pb,pl,px,py,fontFamily,fontSize,fontWeight,lineHeight,textAlign" color="blue.5"></button>
            </div>
        </div>
    </div>
    <div class="jsx-648997698 ">
        <div class="jsx-3724960542 port position-absolute d-inline-block circle output isEditing isGhost"></div>
    </div>
</div>
```

**Comment by silverwind** [comment]
Almost seems like some framework generated that. Guess we can style it like this

````css
[style*="background-color: rgb(68, 77, 85)"] {
    background-color: `#343434` !important
}
````
Actually it does not seem like a bad way to replace colors.

**Comment by the-j0k3r** [comment]
Hello :) looking good indeed. Question. are we styling the https://github.com/features/actions webpage in meanwhile? If so I maybe able to help out there.

**Comment by xt0rted** [comment]
@Mottie @silverwind have either of you requested access to the beta for @StylishThemes? I was going to sign us up but only admins can.

**Comment by Mottie** [comment]
I just signed up.

**Comment by xt0rted** [comment]
I finally had some time to setup a few actions this past week and got the styles all ironed out. They're ready to push & merge but the usercss grunt task is breaking things. Hopefully I'll get this fixed in the next day or two because it's breaking more than this update https://github.com/StylishThemes/GitHub-Dark/commit/c823f08a4d0f785471b406c7e435c0b8d3993a87.

**Comment by xt0rted** [comment]
This has been added in b818e4e5c360f82ee0e8da3db140b2d0e4d557be 🎉

There's 3 selectors at the very end that will change frequently due to being generated from React. Over all the html/css has improved a lot since my initial version so I'm hopeful this will improve even more soon.

Public view of a workflow: https://github.com/primer/css/blob/master/.github/main.workflow
Run results show in the PR checks tab (no custom styling needed): https://github.com/primer/css/pull/692/checks

**Run history**

![image](https://user-images.githubusercontent.com/831974/53388819-aa638700-395a-11e9-8b6d-323937c1b4cb.png)

**Run history - failed action**

![image](https://user-images.githubusercontent.com/831974/53388847-ccf5a000-395a-11e9-856b-1ab991024839.png)
