### ISSUE TITLE
gh-header now has white bg

### ISSUE THREAD

**Issue by kuanb** [StylishThemes/GitHub-Dark#785]
Color needs to be override/made transparent.

Example of what it looks like right now:
![image](https://user-images.githubusercontent.com/6053396/49602389-31e1c100-f93d-11e8-9781-79294a10358b.png)

Css setting:
![image](https://user-images.githubusercontent.com/6053396/49602430-4f168f80-f93d-11e8-823a-349df063dbf9.png)

Removing setting resolves the issue:
![image](https://user-images.githubusercontent.com/6053396/49602464-6190c900-f93d-11e8-897b-c6f9eb761b13.png)

**Comment by kuanb** [comment]
Hrm, though I just checked the css in master and I see it has:

https://github.com/StylishThemes/GitHub-Dark/blob/ea085a49f2472cc2a5417c8c0608c386985af452/github-dark.css#L1579-L1580

Which suggests it is already set to `none !important`. Curious if there's some issue where the new background color setting is somehow overriding it.

**Comment by xt0rted** [comment]
@silverwind just fixed this issue in master, that's why you're seeing that change.

**Comment by silverwind** [comment]
Yes, this is fixed in https://github.com/StylishThemes/GitHub-Dark/commit/acc76270b620027e7e4adeb98421305b00b1278b, will release soonish.
