### ISSUE TITLE
Stretched Header conflicts with octotree

### ISSUE THREAD

**Issue by MCOfficer** [StylishThemes/GitHub-Dark#788]
* **Browser**: Firefox 63.0.3 (64-Bit)
* **Operating System**: Windows 10 Pro 10.0.17134 (aka 1803, Redstone 4 or April 2018 Update)
* **Screenshot**: 
![firefox_2018-12-06_22-38-26](https://user-images.githubusercontent.com/22377202/49613705-8c643700-f9a8-11e8-8ed6-5120e4645ad8.png)

As you can see, the auto-stretching header is overlapped by the octotree extension on the left. This is not technically an issue with this style, but this is the point where it can best be prevented.

I'm not sure what the best fix for this is - Detect the presence of octotree and adjust the header accordingly (not sure if that's even possible) or just create an option to turn off the stretched header.
i'm fine with either of those.

**Comment by xt0rted** [comment]
I just tested this and it is an issue with GHD. It looks like removing the following rule fixes the issue.

https://github.com/StylishThemes/GitHub-Dark/blob/fa027c25a4d92bd2ee23ac63a8226d99037582ea/github-dark.css#L4339-L4341

**Comment by xt0rted** [comment]
Another issue I'm seeing with this plugin is the button to toggle it has the wrong icon color. Removing the selector `a.octotree_toggle:not(.octotree_loading) > span:after` in the the following rule looks to fix the colors so they match the default buttons.

https://github.com/StylishThemes/GitHub-Dark/blob/fa027c25a4d92bd2ee23ac63a8226d99037582ea/github-dark.css#L4334-L4338

**Comment by MCOfficer** [comment]
can confirm both of those, although the second one also makes the icon appear black when not hovered (vs the current white):
![grafik](https://user-images.githubusercontent.com/22377202/49618184-d6084e00-f9b7-11e8-8fe6-ea591cf64f60.png)
![grafik](https://user-images.githubusercontent.com/22377202/49618126-9e010b00-f9b7-11e8-90c5-b80d5f7c0889.png)

but the blue vs current grey when hovered would be an improvement:
![grafik](https://user-images.githubusercontent.com/22377202/49618138-ace7bd80-f9b7-11e8-81b2-5d31878ccee3.png)

![grafik](https://user-images.githubusercontent.com/22377202/49618116-95103980-f9b7-11e8-9137-638ce977abae.png)

**Comment by xt0rted** [comment]
I have a PR incoming that addresses all of these issues.
