### ISSUE TITLE
Can't install from GitHub using Stylus on Firefox 63

### ISSUE THREAD

**Issue by AdrienPoupa** [StylishThemes/GitHub-Dark#789]
* **Browser**: Firefox 63
* **Operating System**: KUbuntu 18.04
* **Screenshot**: This is what I get when I open https://stylishthemes.github.io/GitHub-Dark/github-dark.user.css
![image](https://user-images.githubusercontent.com/15086425/49617284-fcab9200-f981-11e8-9e68-2556e6514d9f.png)

It works fine with other themes

**Comment by AdrienPoupa** [comment]
Yes I can install other themes (other than github dark) just fine

**Comment by silverwind** [comment]
Weird, are you on the latest Stylus version? I think this would certainly be something to post on the [stylus issue tracker](https://github.com/openstyles/stylus/issues). A userstyle is not able to show a `alert` like this, so it must come from Stylus itself.

**Comment by AdrienPoupa** [comment]
I'm using Stylus 1.5.2. Interestingly, if I load https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-dark.user.css it is working, but not with https://stylishthemes.github.io/GitHub-Dark/github-dark.user.css

**Comment by the-j0k3r** [comment]
Hello fine people.

Im unable to duplicate this Windows 7/10 side and Ubuntu 18.04 LTS side using Firefox 64, but I wonder if this maybe a Kubuntu + Firefox 63 specific?
@AdrienPoupa if youre able to use other OS to test that out, it would help somewhat I think to rule out any weirdness. 

> Weird, are you on the latest Stylus version? I think this would certainly be something to post on the [stylus issue tracker](https://github.com/openstyles/stylus/issues). A userstyle is not able to show a `alert` like this, so it must come from Stylus itself.

I agree, all else excluded this would be my next door to knock on.

Happy Holidays everyone.

**Comment by silverwind** [comment]
I think the only place here Stylus uses plain `alert()` is [here](https://github.com/openstyles/stylus/blob/8d6c88e3775927e972f4b78f4cda80ecd5b7f169/content/install-hook-usercss.js#L21). I suspect some setting or addon interfering, try in safe mode.

**Comment by the-j0k3r** [comment]
Im marking this external because [alert() ](https://github.com/openstyles/stylus/blob/8d6c88e3775927e972f4b78f4cda80ecd5b7f169/content/install-hook-usercss.js#L21) 

Having tested in several browsers and OS's the install links both https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-dark.user.css and https://stylishthemes.github.io/GitHub-Dark/github-dark.user.css with no issues whatsoever makes me wonder if some routing issue is to blame.

**Comment by silverwind** [comment]
Closing this until further information is provided.
