### ISSUE TITLE
Selected comments have wrong border & box shadow colors

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#801]
Looks like a new update went out that uses `[aria-selected=true]` instead of the `:target` selector. Some of this is fixed by regenerating the css, but there's some spots that aren't picked up by it such as the arrow on your own issue comment and the border of code comments.

* **Browser**: chrome
* **Operating System**: win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/49903694-088dcd00-fe36-11e8-94f9-3bc9e59c08a4.png)

![image](https://user-images.githubusercontent.com/831974/49903668-f744c080-fe35-11e8-9b89-f713995342b7.png)

* **HTML of the section where the issue occurs**:

```html
<div class="timeline-comment-group js-minimizable-comment-group js-targetable-comment" id="issue-237027598" aria-selected="true">
    <div class="unminimized-comment editable-comment comment previewable-edit js-comment js-task-list-container timeline-comment reorderable-task-lists current-user" data-body-version="32fdc28eff53c4f32e00163ddc8f5ccd" data-unfurl-authenticity-token="M/E41VWnbUWIyUl1zlk4dby2JdW+Vk0uEkZoUE2fMezQF7o2TjesrbUnwL4mwh4SfN1P7lTHADeq5CUQAIjE1A==">
      ...
    </div>
</div>
```

````html
<div class="review-comment js-minimizable-comment-group js-targetable-comment" id="discussion_r240331997" data-gid="MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDI0MDMzMTk5Nw==" data-url="/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDI0MDMzMTk5Nw==/comments/review_comment" aria-selected="true">
  ...
</div>
````

**Comment by xt0rted** [comment]
Looks like this only happens when you click on one of the date/time links, but if you right click and open it in a new tab then the correct colors show. It seems they're using `:target` on page load, and `[aria-selected=true]` when the page is already loaded.

**Comment by xt0rted** [comment]
dbd3439452e5d8350ebb46773ab05d3ada1d6da9 fixes some of the color issues, but not all of it.

@silverwind I use the default blue as my base color and in b3469a825ba8952ff4848a88fcd45795e8aa3922 this was changed to a different shade. The rule for `.timeline-comment-group[aria-selected=true] .timeline-comment` is showing 2 different colors, is this due to the rgb variant not being updated too?

![image](https://user-images.githubusercontent.com/831974/49960226-b7d1af00-fedd-11e8-87c2-00781d0acea0.png)

**Comment by silverwind** [comment]
Oh, indeed I forgot to update `rgb` and `rgba` variants. Hold on.

**Comment by silverwind** [comment]
Fixed
