### ISSUE TITLE
Selected related issues have light background color

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#802]
Looks like some new updates went out today for the related issues feature when creating new issues. The selected issue background is light now instead of dark.

When regenerating the css the selector `.related-issue-item.navigation-focus` gets auto-generated with a background color of `#202020` but the section's background is `#222` so you can't even tell the color changed. Changing this to `#343434` seems to work better.

* **Browser**: chrome
* **Operating System**: win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/49904241-974f1980-fe37-11e8-870d-fd5e588b2cbc.png)

* **HTML of the section where the issue occurs**:

````html
<li class="related-issue-item js-navigation-item navigation-focus" aria-selected="true">
  <a data-hydro-click="{&quot;event_type&quot;:&quot;related_issues.click&quot;,&quot;payload&quot;:{&quot;repository_id&quot;:1219740,&quot;client_id&quot;:&quot;790373834.1527194507&quot;,&quot;originating_request_id&quot;:&quot;FBBA:51F2:C7B437:188792E:5C118FA9&quot;,&quot;originating_url&quot;:&quot;https://github.com/StylishThemes/GitHub-Dark/issues/new?_pjax=%23js-repo-pjax-container&quot;,&quot;user_id&quot;:831974}}" data-hydro-click-hmac="7414ffeb6595911cf96db22635330cffaade3c0d0d9cabe33727e73ac3bca924" class="d-flex flex-row p-2 no-underline js-related-issue-suggestion-link js-navigation-open" href="https://github.com/StylishThemes/GitHub-Dark/issues/716" data-hydro-client-context="{&quot;position_in_list&quot;:0,&quot;number_of_related_issues&quot;:4,&quot;title_length&quot;:42,&quot;title_string_at_time_of_click&quot;:&quot;Selected comments have wrong border colors&quot;,&quot;id_of_clicked_result&quot;:344942363,&quot;results_shown_at_time_of_click&quot;:[344942363,26778874,386570683,95235136]}">
    ...
  </a>
</li>
````

**Comment by silverwind** [comment]
I agree, `#202020` works against `#181818` but in this case we have a lighter background, so I suggest manually styling it (e.g. overriding the generated rule), maybe `#2a2a2a`  to keep the same color difference, but `#333` is probably fine too.
