### ISSUE TITLE
Customized scrollbar is broken in Vivaldi (also request for option to be disabled)

### ISSUE THREAD

**Issue by chocmake** [StylishThemes/GitHub-Dark#820]
In the Vivaldi browser the userstyle's customized scrollbar can't be dragged or selected. It *does* however work within text boxes (like the one I'm composing this issue with).

Using latest version of the theme at the time of posting and tested on multiple Github pages.

* **Browser**: Vivaldi 2.2.1388.37 (Stable channel) (32-bit) [latest]
* **Operating System**: Windows 8.1
* **Screenshot**: 

![gif](https://user-images.githubusercontent.com/34178938/50762336-c2a31800-12c0-11e9-952a-4e7fe909b808.gif)

Apart from mentioning this issue I'd also like to request for an option within Stylus to disable the customized scrollbar as it's both far too narrow and in the spirit of customization not everyone wants an alternate style scrollbar. I could edit the userstyle manually but I'm not sure if auto updates are retained or if auto updates would break the changes.

Thanks.

**Comment by the-j0k3r** [comment]
Thank you for your report. =)

>Apart from mentioning this issue I'd also like to request for an option within Stylus to disable the customized scrollbar

The scrollbar CSS was added 15 days ago in https://github.com/StylishThemes/GitHub-Dark/commit/55c2c87a600207deb0c77a270debd73db5c5362b by @silverwind.

I dont have an idea why @silverwind didn't make this optional, but I also agree that opinionated changes, should be, at least optional.

> I could edit the userstyle manually but I'm not sure if auto updates are retained or if auto updates would break the changes.

Just to clarify, If you edit the userstyle CSS manually, Stylus wont update your style due to local changes, That also means future updates that fix other things that crop up will also not come through for the same reason.

Best bet, if GHD is affecting your scrollbars (which it seems to) it needs to be fixed, we should to make this optional or better, its own style.

**Comment by the-j0k3r** [comment]
Hi, would you like to test #826 it should make the code optional and is disabled by default.

I would like however to move this type of CSS to its own style, documented in #826.

**Comment by chocmake** [comment]
@the-j0k3r wasn't sure how to test otherwise so just did a find and replace of the changes manually and it appears to work, adding an drop-down option that toggles between the unstyled and styled scrollbars.

Still undraggable on Vivaldi though, not sure what the cause is of that.

**Comment by the-j0k3r** [comment]
Ive just tested this in Vivaldi, it works just fine

Vivaldi  2.2.1388.37 (Stable channel) (64-bit)
Executable Path | C:\Program Files\Vivaldi\Application\vivaldi.exe
Profile Path | C:\Users\Joker\AppData\Local\Vivaldi\User Data\Default

Stylus 1.5.2 + GitHub Dark + this PR ->. https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/553efc20e1e18ee1ac03d9ddbedd5c1866931528/github-dark.user.css

So it maybe something in your system.

**Comment by chocmake** [comment]
Btw, noticed yesterday that my manual changes were reverted without any other interaction. You mentioned in the earlier post manual changes halt auto updates. Based on the latest commit it appears there was an update, so it seems Stylus does overwrite manual changes?

**Comment by atillabyte** [comment]
I'm using Firefox Quantum (65.0b9 (64-bit)) and the custom scroll bar tends to not appear whenever I load a page, although, when I refresh, then it appears.

**Comment by antishok** [comment]
re: Firefox, the issue is easy to reproduce if you open a link in a new (unopened) tab, let the tab load, then switch to it. There is no scrollbar

**Comment by the-j0k3r** [comment]
Vivaldi is chrome based, the previous version is OK, the problem with scrollbars in chrome are the same @supports that make it work on chrome is also what breaks it.

https://github.com/StylishThemes/GitHub-Dark/blob/68bcb8d7cea5166b35035b5f77edf7500180610d/github-dark.css#L3936-L3942

**Comment by silverwind** [comment]
Try dropping the `@supports`, it's really only a safeguard that currently applies to no browser.

**Comment by the-j0k3r** [comment]
OK =) News.

The scrollbar code now lives in its own repo it supports Firefox (working reliably and fully) and Chrome Including in some tested derivative browsers. If interested visit https://github.com/StylishThemes/Overlay-Scrollbars

Regarding the bug select/drag of scrollbars, the new scrollbars theme located at https://github.com/StylishThemes/Overlay-Scrollbars **wont cause the issues** you experienced with these scrollbars you reported.

You can also enable Overlay scrollbar support in Vivaldi by doing the following

1) Type `vivaldi://flags/#overlay-scrollbars` into address bar
2) Enable: Overlay Scrollbars
![capture](https://user-images.githubusercontent.com/31389848/51378872-6afd7b80-1b0e-11e9-8e93-835192dadff0.PNG)

For more information visit https://forum.vivaldi.net/topic/21914/how-to-mod-webpage-scrollbar-with-custom-css/11

Or you can use no scrollbar styling whatsoever, the choice is yours =)

Hope it helps.

**Comment by Mottie** [comment]
Would you add those Vivaldi instructions to the overlay-scrollbars repo readme?
