### ISSUE TITLE
Links to userstyles.org

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#822]
While browsing around I noticed there's still some links to `userstyles.org`. Do we want to remove/change any of these?

https://github.com/StylishThemes/GitHub-Dark/blob/0c80c2d00f021586644939399e69dc63749993df/package.json#L7

https://github.com/StylishThemes/GitHub-Dark/blob/0c80c2d00f021586644939399e69dc63749993df/github-dark.css#L3

I think this one might be good to point to `https://stylishthemes.github.io/GitHub-Dark/github-dark.user.css` since that's the preferred way to get this now.

https://github.com/StylishThemes/GitHub-Dark/blob/0c80c2d00f021586644939399e69dc63749993df/index.html#L293

**Comment by Mottie** [comment]
Sounds good! Please go ahead and make the changes, no PR needed...

Sorry, I haven't been around. I've been so busy with work I'm too tired to follow up.
