### ISSUE TITLE
Language graph now has a white separator between languages

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#823]
https://blog.github.com/changelog/2019-01-09-more-readable-repository-language-bar/

I played around with making this a few different colors (`#1c1c1c` `#222222`, `#343434`) and they all basically look the same. Do we want to keep this white, make it a darker color, or remove it?

* **Browser**: chrome
* **Operating System**: win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/50917797-7d8bfc80-140c-11e9-820b-7133aa08af3f.png)

* **HTML of the section where the issue occurs**:

```css
.repository-lang-stats-graph .language-color:not(:first-child) {
  border-left: 1px solid #fff;
}
```

````html
<button type="button" class="d-flex p-0 repository-lang-stats-graph js-toggle-lang-stats" title="Click for language details" data-ga-click="Repository, language bar stats toggle, location:repo overview">
    <span class="language-color" aria-label="CSS 71.1%" style="width:71.1%; background-color:#563d7c;" itemprop="keywords">CSS</span>
    <span class="language-color" aria-label="HTML 24.7%" style="width:24.7%; background-color:#e34c26;" itemprop="keywords">HTML</span>
    <span class="language-color" aria-label="JavaScript 4.1%" style="width:4.1%; background-color:#f1e05a;" itemprop="keywords">JavaScript</span>
    <span class="language-color" aria-label="Shell 0.1%" style="width:0.1%; background-color:#89e051;" itemprop="keywords">Shell</span>
</button>
````

**Comment by the-j0k3r** [comment]
I say remove it for now, I cant see any improvement here specially around bright colors.

**Comment by silverwind** [comment]
Hmm yeah, I don't see much value in it, so removal might be the best option, just make sure to add a link to this issue and add the rule near the "GitHub Bug" stuff, because it is certainly opinionated.

Also if you look closely at the end of the bar, you can see that GitHub forgot to remove the final spacer, so there is a unsightly gap at the end of the language bar.

**Comment by the-j0k3r** [comment]
I would make anything opinionated like this optional and something problematic its own style, no?

**Comment by silverwind** [comment]
Too many options are also not good. I'm happy with just darkening them to `#181818` too, but if possible add a workaround for the final spacer.

**Comment by xt0rted** [comment]
@silverwind the right border is actually because the right most item is being pushed off the chart now that there's a left border. In this repo is **Shell** at a whole fraction of a percent. I'm sure the light color for this language doesn't help either.

My understanding of how these two options work seems to be backwards from what  I'm seeing, but the results don't lie in this example. Modifying the rule `.repository-lang-stats-graph .language-color` looks to fix it.

**`box-sizing: border-box`**

![image](https://user-images.githubusercontent.com/831974/51211310-1aeea100-18e3-11e9-97ab-ae3dc4e72927.png)

**`box-sizing: content-box`**

![image](https://user-images.githubusercontent.com/831974/51211343-348fe880-18e3-11e9-9fa5-234db32ac0fb.png)

**Comment by silverwind** [comment]
> box-sizing: content-box

Good find, we can add that as a temporary fix on our side, or [contact](https://github.com/contact) them about it.

**Comment by the-j0k3r** [comment]
These white separators remove the space available for displaying smaller percentage of the language, so hiding the separator, it would make that shell more than 1px wide right? (is so consider removing it)

**Comment by xt0rted** [comment]
In this instance Shell is `0.1%` wide, which even with the border removed is less than a full percent.

**Comment by silverwind** [comment]
Opted to remove it. A 1px line is not going to add much value imho.
