### ISSUE TITLE
Selected text barely visible (White highlight)

### ISSUE THREAD

**Issue by Bloumbs** [StylishThemes/GitHub-Dark#834]
Highlighting both code and regular text is changing the color of the text to white and not having the light blue background behind to easily tell what you're selecting. On some code/text it looks and works fine, but on some other specific pages, it is quite hard to tell what you're selecting on that page with it being white. I don't know if this was a universal Github Dark change or not, but Im just wondering where I can look to possibly edit this, because I don't know. If I got something wrong or this issue has been addressed and changed, I apologize. Ive looked around for a solution and haven't seen it. :)

* **Browser**: Safari 12.0.2 / Chrome 71.0.3578.98

* **Operating System**: macOS Mojave 10.14.2

* **Screenshot**:
![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/39519792/51330602-746ae300-1a3d-11e9-969b-340f15f0ed87.gif)

**Steps using Stylus on macOS/Windows in Chrome**:

**1.** Click "Install the usercss" from Github Dark README.md:

![799976c58c6b43aa5063e7921bbaf1a6](https://user-images.githubusercontent.com/39519792/51331372-366ebe80-1a3f-11e9-8fd1-33831fa6b63d.png)

**2.** Click "Install style" from Stylus page that pops up:

![download 20](https://user-images.githubusercontent.com/39519792/51331560-a11ffa00-1a3f-11e9-91ab-35e3bfa690e3.png)

**3** "Github Dark" theme is set. Open Github in Chrome and highlight text.

**Steps using Cascadea app on macOS in Safari**:

**1.** Click "Install the usercss" from Github Dark README.md:

![799976c58c6b43aa5063e7921bbaf1a6](https://user-images.githubusercontent.com/39519792/51330415-16d69680-1a3d-11e9-8413-c14e6fc13b82.png)

**2.** Click "Allow" on popup to open in Cascadea.app:

![5eee91b21cbdf4618afc97c206b3fdf3](https://user-images.githubusercontent.com/39519792/51330714-a67c4500-1a3d-11e9-8a50-e8b5294cc0d9.png)

**3.** Click 'Yes' when asked "Do you want to install the style "GitHub Dark"?"

**4.** "Github Dark" theme is set. Open Github in Safari and highlight text.

**Comment by the-j0k3r** [comment]
Hello and thank you for the report.

Please read https://github.com/StylishThemes/GitHub-Dark/issues/808#issuecomment-450350913
and
https://github.com/StylishThemes/GitHub-Dark/issues/808#issuecomment-450356324

Those should let you know about the limitations of cascadea and what you can do.

**Comment by silverwind** [comment]
Hmm, but it should not happen with Stylus and Chrome.

**Comment by Bloumbs** [comment]
**1.** **Change "text selection" color values on line 1315 from default: #fff (White), and add background-color on line 1314:**

![screen shot 2019-01-22 at 1 27 22 am](https://user-images.githubusercontent.com/39519792/51522352-c66d8900-1dee-11e9-8b73-fc6ef0a8b572.png)
