### ISSUE TITLE
Horizontal scroll bars showing up on big PRs

### ISSUE THREAD

**Issue by ThiefMaster** [StylishThemes/GitHub-Dark#844]
This only happens when the dark theme is enabled. It doesn't happen with all PRs but when it does happen it happens consistently as soon as the sticky header is triggered when scrolling down.

One PR where it happens is [this one](https://github.com/indico/indico/pull/3742/files).

**Comment by silverwind** [comment]
Related to https://github.com/StylishThemes/GitHub-Dark/commit/e65b8d9ddf2a7f5d314ac59a7aeaded20ebd58a3
