### ISSUE TITLE
Missing background on issue preview details in projects

### ISSUE THREAD

**Issue by ThiefMaster** [StylishThemes/GitHub-Dark#850]
![image](https://user-images.githubusercontent.com/179599/52784231-b3984e00-3054-11e9-90a2-5ed0f5cc3267.png)

Can be seen live [here](https://github.com/indico/indico/projects/2) by simply previewing an issue.

**Comment by Mottie** [comment]
Hi @ThiefMaster!

Thanks for reporting this issue. It's been fixed.
