### ISSUE TITLE
Pull request popover content overflow outside area.

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#851]
Like title says., though this is an external issue to this project since it happens when GHD is also turned off.

Opened ticket here maybe someone has some idea where to report this issue to or maybe the issue has already been reported + we know this issue exists.

* **Browser**: FF 65.0
* **Operating System**: Win 10 Pro/Ubuntu 18.04LTS
* **Screenshot**:

![popover](https://user-images.githubusercontent.com/31389848/52844205-5b208980-3104-11e9-9eb7-2b9f237f799a.gif)

* **Link to page with the issue**: Any Project Pull request https://github.com/StylishThemes/GitHub-Dark/pulls

**Comment by silverwind** [comment]
You can try contact GitHub via https://github.com/contact, they can file bugs on their internal issue tracker.

**Comment by the-j0k3r** [comment]
Thx for reply.

>You can try contacting GitHub via https://github.com/contact,

I rather reach out in a repo for the project that generates this css, just havent looked into which one is the correct one, maybe even make a contrib with a fix, idk :man_shrugging: 

>If they are unresponsive, we can add a hack to fix it

`<insert-name>.user.css` maybe a solution worth looking into for reasons above and posting as a temp workaround, I'll see what I can come up with (if no one beats me to it in the meanwhile).
Something external to GHD is better in any case easier to control when its fixed upstream.

**Comment by the-j0k3r** [comment]
A temporary fix as it also affect issue popover not just pr popover.

Its not what Ide consider a nice result but its better than the current situation.
Feel free to make better suggestion.

```
/* ==UserStyle==
@name           HACK GitHub-Dark#851
@namespace      github.com/openstyles/stylus
@version        1.0.0
@description    A temp fix for https://github.com/StylishThemes/GitHub-Dark/issues/851
@author         Some lil' Elf
==/UserStyle== */

@-moz-document domain("github.com") {
  .Popover-message--large.Box[style="width:360px;"] {
	width: calc(75% + 10px) !important;
  }
}
```

**Comment by Mottie** [comment]
GitHub uses [primer](https://styleguide.github.com/primer/) as a base, but then they add lots of customizations on top of it. If you see the same issue with primer, then open an issue there, otherwise contact GitHub is the best method.

**Comment by xt0rted** [comment]
I think this might be fixed already. I'm not able to reproduce it and checking some of the popups in the [primer repo](https://github.com/primer/css/pulls) show the branch name being truncated with a `...`

**Comment by xt0rted** [comment]
Never mind, I don't think this is a "bug" per se but rather your browser's font scaling changing the size. I still passed the info along to someone in case it helps.

**Comment by the-j0k3r** [comment]
I think this is fixed, I cant duplicate this anymore by hovering ticket titles in the GHD PR tracker. Ill close this soon as more testing is done and Im sure issue is gone.
