### ISSUE TITLE
`.dropdown-menu` has transparent background when logged out

### ISSUE THREAD

**Issue by stonecrusher** [StylishThemes/GitHub-Dark#854]
* **Browser**: FF 65.0.1
* **Operating System**: Win 8.1
* **Screenshot**: 
![2019-02-17 12_23_15-greenshot](https://user-images.githubusercontent.com/1388389/52912318-15a0bf80-32b0-11e9-9a6d-359f0570a1d7.png)

* **Link to page with the issue**: https://github.com/

**Comment by the-j0k3r** [comment]
Thank you for your report. Its very strange, Im not able to repro sadly.

![menu](https://user-images.githubusercontent.com/31389848/52913298-efcde780-32bc-11e9-994e-d00700df694e.gif)

**Comment by stonecrusher** [comment]
This should help: This rule overrides the proper `background-color` rule.

![2019-02-17 14_23_53-the world s leading software development platform github url_ https___gith](https://user-images.githubusercontent.com/1388389/52913642-3244f380-32c0-11e9-99d4-2c8e83e6a46a.png)

**Comment by xt0rted** [comment]
With the latest version of GHD I'm seeing this in **Chrome 72.0.3626.109 (Official Build) (64-bit)** and **FF 66.0b8 (64-bit)**

**Comment by xt0rted** [comment]
This should be fixed in the next release.
