### ISSUE TITLE
"Clear filters" in PR diff view has weird left padding

### ISSUE THREAD

**Issue by ThiefMaster** [StylishThemes/GitHub-Dark#855]
![image](https://user-images.githubusercontent.com/179599/52936899-f1032100-335d-11e9-96c0-78920a17dd6a.png)

https://github.com/indico/indico-plugins-cern/pull/36/files/3e5f294038cb7026782f48b969bd011fc6b045c8..50620023b79056a75500c4c28146c670ab85757e (link might break at some point due to force pushes, it's simply a PR with a filter set to show only selected commits)

**Comment by the-j0k3r** [comment]
Thank you for your bug report.

It seems this particular portion `.pr-toolbar .subset-files-tab`  is not suppose t have any border and background and having both makes it look like some padding is there.

A possible fix is adding to both border and background selectors the (:not(.js-reset-filters)) like .pr-toolbar .subset-files-tab:not(.js-reset-filters) and problem will go away. Though Im looking if we can avoid adding a selector prefixed with js-
