### ISSUE TITLE
Default issue/pr status label is too dark

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#858]
* **Browser**: chrome
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/pull/857
* **Screenshot**:
![image](https://user-images.githubusercontent.com/831974/53291494-1a6ae500-3782-11e9-8b2c-4466022ac6cc.png) ![image](https://user-images.githubusercontent.com/831974/53291506-32daff80-3782-11e9-93c6-cd9345a19bf2.png)

I tried adding `.State` to the `background: #444`  rule, and adding a new one that used `background-color`, but because the color variants are being auto generated they show up earlier in the style and get overwritten by the new default color rule.

**Comment by silverwind** [comment]
Looks like a manual rule to me. It's unusual for GitHub to use such a dark shade of grey.
