### ISSUE TITLE
Update document rule for zuora.com to be a regex

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#861]
Just creating an issue so I don't forget about this.

The url used in these iframes contains `github.com` which means we can change this to a regex so it's more specific:
```regex
https://www\.zuora\.com.*github\.com.*
```

_Originally posted by @xt0rted in https://github.com/StylishThemes/GitHub-Dark/pull/857#discussion_r259669807_

**Comment by silverwind** [comment]
If we can style them via `iframe[src*="www.zuora.com"] .selector`, it would be my preference. Thought I do remember Stylus having issues with iframes.

**Comment by xt0rted** [comment]
I tried using the `iframe` selector but it wasn't working.

**Comment by narcolepticinsomniac** [comment]
`iframe` cannot be a parent selector in CSS. It doesn't work that way.

**Comment by Mottie** [comment]
> style them via `iframe[src^="https://www.zuora.com"] .selector`

That should have been ` html[stylus-iframe^="https://www.zuora.com"] .selector`.

**Comment by xt0rted** [comment]
Enabling that setting puts a `stylus-iframe="https://github.com"` attribute on the iframe's html element which let's us keep the `domain(zuora.com)` selector, but then we need to prefix every selector with `html[stylus-iframe*="github.com"]` and convey to our users that this will only work if they turn that feature on. Seems easier to just use the regex check and leave the css alone.

**Comment by the-j0k3r** [comment]
>  Seems easier to just use the regex check and leave the css alone.

Agreed, depending on some setting thats not on by default is far from ideal, I vote regex =)

**Comment by silverwind** [comment]
> iframe cannot be a parent selector in CSS

Right. I do remember there was the [seamless attribute](https://caniuse.com/#feat=iframe-seamless) at one time to allow parent site styles to affect the child, but seems it was never meant to be. Current approach in https://github.com/StylishThemes/GitHub-Dark/pull/866 looks fine to me.
