### ISSUE TITLE
Draft PR icon is red in popover

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#864]
This icon should be grey according to the base styles. This shows up on the notification page and the PR list page.

* **Browser**: chrome
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/JasonEtco/actions-toolkit/pulls
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/53606977-d6654f00-3b8a-11e9-8953-74469a519e63.png)

![image](https://user-images.githubusercontent.com/831974/53606933-acac2800-3b8a-11e9-92af-f96158c833e4.png)

```html
<svg class="octicon octicon-git-pull-request closed text-gray" title="Draft" viewBox="0 0 12 16" version="1.1" width="12" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M11 11.28V5c-.03-.78-.34-1.47-.94-2.06C9.46 2.35 8.78 2.03 8 2H7V0L4 3l3 3V4h1c.27.02.48.11.69.31.21.2.3.42.31.69v6.28A1.993 1.993 0 0 0 10 15a1.993 1.993 0 0 0 1-3.72zm-1 2.92c-.66 0-1.2-.55-1.2-1.2 0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2 0 .65-.55 1.2-1.2 1.2zM4 3c0-1.11-.89-2-2-2a1.993 1.993 0 0 0-1 3.72v6.56A1.993 1.993 0 0 0 2 15a1.993 1.993 0 0 0 1-3.72V4.72c.59-.34 1-.98 1-1.72zm-.8 10c0 .66-.55 1.2-1.2 1.2-.65 0-1.2-.55-1.2-1.2 0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2zM2 4.2C1.34 4.2.8 3.65.8 3c0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2 0 .65-.55 1.2-1.2 1.2z"></path></svg>
```

**Comment by silverwind** [comment]
Github is using `!important` on `text-gray` and unfortunately, we can not fix this via reordering in the generator because `.closed.octicon` has higher specificity. Had to add a manual fix.
