### ISSUE TITLE
Broken Usercss

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#867]
I pushed a new release today and broke usercss installation/updating. The problem is the syntax highlighting selectors immediately before the github syntax theme placeholder:

```css
  /* inline code - big blocks */
.markdown-format pre,
.markdown-body pre,
.markdown-format .highlight pre,
.markdown-body .highlight pre,
#facebox pre,
.blob-expanded,
.terminal,
.copyable-terminal,
#notebook .input_area,
.blob-code-context,
.markdown-format code,
.api pre,
.api code,
.hook-delivery-details pre,
.hook-delivery-container pre;
```

The only solution I've been able to come up with (so far) is to replace that block with another placeholder

```css
  /* inline code - big blocks */
/*[[syntax-prefix]]*/
```

then add the following block to the usercss metadata:

```css
@advanced dropdown syntax-prefix "" {
  1 "Read Only" <<<EOT
  .markdown-format pre, .markdown-body pre, .markdown-format .highlight pre,
  .markdown-body .highlight pre, #facebox pre, .blob-expanded, .terminal,
  .copyable-terminal, #notebook .input_area, .blob-code-context,
  .markdown-format code, .api pre, .api code, .hook-delivery-details pre,
  .hook-delivery-container pre,
  EOT;
} 
```

It works, but it makes the usercss options menu ugly and would break the style for users that install github-dark.css directly.

**Comment by silverwind** [comment]
Hmm, I would probably just duplicate the whole block into all themes and add a comment that any change done on this block needs to be done on all themes as well.

**Comment by Mottie** [comment]
The problem was actually the `default e.g. 10px` that was made as the default for code font size.

The period must have been messing up the parser.

**Comment by Mottie** [comment]
See https://github.com/openstyles/usercss-meta/issues/68

**Comment by the-j0k3r** [comment]
Some reply in https://github.com/StylishThemes/GitHub-Dark/commit/7a7bb3a505519b275779c09da404263575792516
