### ISSUE TITLE
Project board yellows

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#869]
* **Browser**: chrome
* **Operating System**: win10
* **Screenshot**:

To repro open the side menu and then create a new card.

![image](https://user-images.githubusercontent.com/831974/53708110-e043b800-3dff-11e9-8fd0-3c47c64238f8.png)

https://github.com/StylishThemes/GitHub-Dark/projects/1#card-18342294

![image](https://user-images.githubusercontent.com/831974/53708202-652ed180-3e00-11e9-86d0-fcd0350eca82.png)

**Comment by the-j0k3r** [comment]
This is coming from `html:not(#X) .bg-yellow-light` which is set to `#651` 

I think `background-color: #261d08` would be more fitting for these. re: the activity background, for the text maybe go with `#542`.

@silverwind

**Comment by xt0rted** [comment]
The same rule is styling the `outdated` comment label now too.

![image](https://user-images.githubusercontent.com/831974/53871904-200acb00-3fcb-11e9-8ddf-53328e222dd8.png)

![image](https://user-images.githubusercontent.com/831974/53871939-2a2cc980-3fcb-11e9-974b-2a49518389d6.png)

**Comment by xt0rted** [comment]
The green `Beta` label is also using the wrong colors now because of the `html:not(#X)` prefixes that were added (create a new issue and enter `yellow` and you should see it in the related issues list). What were those added to fix? They seem to be breaking a lot of stuff now.

**Comment by silverwind** [comment]
> What were those added to fix

GitHub's original stylesheet has `!important` on those color classes (to override grey text mostly), so I thought it'd be good to emulate that. But in hindsight, it's also not really optimal because those pseudo-importants are kind of hard to override.

**Comment by xt0rted** [comment]
re: view new activity, there's a similar spot to this when you go to delete a repo which is using the `.flash-warn` style. The background color for that is `rgba(51, 34, 17, 0.4)` and looks like this.

![image](https://user-images.githubusercontent.com/831974/54039487-0dda8980-4191-11e9-9d17-101e3608d8bb.png)

**Comment by the-j0k3r** [comment]
This could be addressed now the `html:not(#X)` is gone.
