### ISSUE TITLE
Full width alerts have left & right borders

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#876]
You can recreate this by injecting the html below into a page immediately following the `#start-of-content` element on the dashboard.

The issue is they're adding a `.flash-full` class which removes the left & right borders, but our generated style for the `.flash` class  sets the border color and the size & style. Since this shows up farther down the css chain their modifier is being overridden.

I'm only bringing this up because I'm curious if the generator can be set up to ignore the border style and just handle the color. This might fix some edge cases and make the style a bit simpler.

* **Browser**: chrome
* **Operating System**: win10
* **Link to page with the issue**:
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/54040300-0caa5c00-4193-11e9-9ba6-9e009696eaf4.png)

* **Html**:

```html
<div id="js-flash-container">
    <div class="flash flash-full flash-notice">
  <div class="container-lg px-2">
    <button class="flash-close js-flash-close" type="button" aria-label="Dismiss this message">
      <svg class="octicon octicon-x" viewBox="0 0 12 16" version="1.1" width="12" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.48 8l3.75 3.75-1.48 1.48L6 9.48l-3.75 3.75-1.48-1.48L4.52 8 .77 4.25l1.48-1.48L6 6.52l3.75-3.75 1.48 1.48L7.48 8z"></path></svg>
    </button>
      Your repository "blah blah blah" was successfully deleted.
  </div>
</div>
</div>
```

**Comment by the-j0k3r** [comment]
border-color: blabla would work to replace the color set in border: 1px solid blabla

**Comment by xt0rted** [comment]
I wasn't sure if the generator could output `border-color` instead of `border` for these. If it can it seems like a better option, but I'm not sure if it'd work or if there's a reason why that's not how it's already being done.

**Comment by the-j0k3r** [comment]
Its seems its done..
https://github.com/StylishThemes/GitHub-Dark/blob/4a1d34920a3bf5b0f93e49c337483cdc19103716/tools/generate.js#L47

**Comment by xt0rted** [comment]
This would also fix the footer top border on full width pages. There's a double border that's just barely noticeable on pages such as [PR checks](https://github.com/StylishThemes/GitHub-Dark/pull/868/checks).

![image](https://user-images.githubusercontent.com/831974/54085782-0ee9f300-4318-11e9-8b63-f710833df647.png)

**Comment by xt0rted** [comment]
Found another spot where this is happening. On the [help site](https://help.github.com/en/articles/viewing-your-repositorys-workflows) the search box container has a top border on small screens but removes it with `.border-md-top-0` on larger screens.

![image](https://user-images.githubusercontent.com/831974/54277335-f4a55480-4565-11e9-87f5-dd1dcb6181c7.png)

@silverwind you know the history of this more than I do, does it seem reasonable to try switching the border rules so they only set the color and not also the style?

**Comment by silverwind** [comment]
Changed all border generators to just do color only. Also cleaned up the `.flash` styling significantly, eliminating all manual rules that we accumulated over the years.
