### ISSUE TITLE
Search dropdown isn't fully styled now

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#878]
* **Browser**: chrome
* **Operating System**: win10
* **Link to page with the issue**: any
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/54165759-74350580-4438-11e9-860f-98272a6145c0.png)

This is really annoying, I was running what was in master all week (kept updating it each day) and none of this showed up as n issue until doing the release.

**Comment by silverwind** [comment]
We have a lot of issues like this with the removal of `!imporant` from generated rules. Solution is pretty much always to drop the conflicting non-generated rules that have `!important`.
