### ISSUE TITLE
Search suggestions are not readable

### ISSUE THREAD

**Issue by alsoknownasdrew** [StylishThemes/GitHub-Dark#879]
* **Browser**: Google Chrome 72.0.3626.121
* **Operating System**: macOS Mojave 10.14.3
* **Link to page with the issue**: Search form in Github Header
* **Screenshot**:
![Schermata 2019-03-12 alle 10 26 10](https://user-images.githubusercontent.com/19336615/54190066-640e3c00-44b3-11e9-9f90-5189f71e72eb.png)
![Schermata 2019-03-12 alle 10 07 07](https://user-images.githubusercontent.com/19336615/54190088-6b354a00-44b3-11e9-8426-b6def8cde3ab.png)

**Comment by the-j0k3r** [comment]
Thank you for this report.

Please update GHD, its been fixed in https://github.com/StylishThemes/GitHub-Dark/commit/946ab25dacfa591af36a8bd90f2317970a5da9fd
