### ISSUE TITLE
Star event in feed isn't themed

### ISSUE THREAD

**Issue by sh7dm** [StylishThemes/GitHub-Dark#881]
* **Browser**: FF 65
* **Operating System**: Ubuntu 18.04
* **Link to page with the issue**: https://github.com
* **Screenshot**:
![изображение](https://user-images.githubusercontent.com/19504461/54307527-fd853d00-45dc-11e9-8b2f-c9c67c2147e6.png)

**Comment by xt0rted** [comment]
This is showing correctly for me.

![image](https://user-images.githubusercontent.com/831974/54309496-a19fc180-45a6-11e9-8d27-0250032ef1d9.png)

Can you make sure you're using the latest version from https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-dark.user.css?

**Comment by giuseppeM99** [comment]
Same issue, i found out that it was an extension (refined github), disabling it solved the problem

**Comment by xt0rted** [comment]
Just released 1.21.12 which fixes this.
