### ISSUE TITLE
Alert text is two different colors

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#882]
* **Browser**: chrome
* **Operating System**: win10
* **Link to page with the issue**:
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/54310706-605ce100-45a9-11e9-96f6-b3902bda7cec.png)

The text for these used to be `#bebebe`. Is that what we want to set them back to? They look kind of weird following the default styles.

![image](https://user-images.githubusercontent.com/831974/54310951-fabd2480-45a9-11e9-9c0a-a69f24b92e9b.png)

![image](https://user-images.githubusercontent.com/831974/54311012-1aece380-45aa-11e9-873e-26b4d322a701.png)

**Comment by silverwind** [comment]
I don't want them completely grey/white. Maybe a lighter shade of yellow or `rgba` color would be better.

**Comment by the-j0k3r** [comment]
I have this one

![Capture](https://user-images.githubusercontent.com/31389848/54809352-5448e180-4c83-11e9-90ed-25fa0a7cee01.PNG)

The background color seems fine, but the text color were setting `#874;` which could be a few ticks lighter and increase legibility/contrast cause atm seems a bit dull.

**Comment by the-j0k3r** [comment]
Ive brightened `#874` in https://github.com/StylishThemes/GitHub-Dark/commit/b4a096f19bd6b94d9d31b184b20eb563e50c8473 to '#a58f4c` much more legible,

Regarding this ticket though, I tried getting the exact color for the text but the color picker ones dont trigger anything in generator

```
>> Warning: no declarations for color: #867748 found!

>> Warning: no declarations for color: #79662c found!
```

@xt0rted what color are we replacing then? I cant see that warning on your screenshots.

**Comment by silverwind** [comment]
Color picking screenshots is usually not a very reliable way to get a color 😉

@xt0rted got some HTML?

**Comment by xt0rted** [comment]
```html
<div class="flash flash-warn mt-3 ">
    <div class="float-right">
      <a href="/StylishThemes/GitHub-Dark/network/alerts" class="btn mb-2 float-right" data-octo-click="vuln_alert_review">See security alerts</a>
    </div>
  <div>
      <h5 class="mb-1" style="display-inline"><svg height="18" class="octicon octicon-alert mr-1" viewBox="0 0 16 16" version="1.1" width="18" aria-hidden="true"><path fill-rule="evenodd" d="M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"></path></svg>We found potential security vulnerabilities in your dependencies.</h5>
    <p class="text-small">
        Only the owner of this repository can see this message.
      <br>
      <a href="/settings/notifications">Manage your notification settings</a> or <a href="https://help.github.com/articles/about-security-alerts-for-vulnerable-dependencies" target="_blank">learn more about vulnerability alerts.</a>
    </p>
  </div>
</div>
```

**Comment by silverwind** [comment]
How about `#fc9`, does this look okay to you?

<img width="850" alt="Screenshot 2019-04-03 at 23 13 49" src="https://user-images.githubusercontent.com/115237/55513533-378ab180-5666-11e9-9140-f69edff1080b.png">

Or maybe `#eca`?

<img width="852" alt="Screenshot 2019-04-03 at 23 15 31" src="https://user-images.githubusercontent.com/115237/55513612-6b65d700-5666-11e9-8a41-160e7be1bc69.png">

I guess these alerts are meant to be noticed, so I think bright colors are fine there.

**Comment by xt0rted** [comment]
`#fc9` looks good. With f.lux enabled they both look basically the same, but when it's off the first looks a bit better I think.

**Comment by silverwind** [comment]
Fixed in https://github.com/StylishThemes/GitHub-Dark/commit/06539ea1565606cb601e4b976131fa518c49af21.

**Comment by the-j0k3r** [comment]
ugh, why not just use  `#a58f4c` before/after
![generic](https://user-images.githubusercontent.com/31389848/54809587-041e4f00-4c84-11e9-8da4-afde6a0c4934.gif)

else this type warning also has diff colors, I think `#fc9` is way too bright anyway.
