### ISSUE TITLE
Expand commit message button has wrong text color on hover

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#883]
* **Browser**: chrome
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/pull/866#commits-pushed-5ef3d4b
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/54311584-43c1a880-45ab-11e9-8e28-f544022bfd06.png)

The rule for this is `.timeline-commits .hidden-text-expander .ellipsis-expander:hover` which has the `background-color` set to `!important` but the `color` isn't.

**Comment by xt0rted** [comment]
Is the fix for this just removing the `!important` from this rule? https://github.com/StylishThemes/GitHub-Dark/blob/0ef0b62759e74196960e2d7cb39815869c3a5ddf/github-dark.css#L3922-L3931

**Comment by the-j0k3r** [comment]
I would ID the actual selector and place in a non important rule, rather than removing important from all the selectors in rule to fix this only and probably break other things.

idk about you but lately its been a chase of own tail to fix breakages, its gets old really quick and makes me dizzy =)

**Comment by silverwind** [comment]
We don't need `!important` if we exactly match the selectors (latter style wins), so I removed it. Also removed a bunch of manual selectors targeting the expander dots.

Generally, we should start handing out `!important` only in cases where it is absolutely necessary. It is never necessary for generated rules.
