### ISSUE TITLE
Code comment text is brighter now

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#884]
I think this is a result of the recent `!important` changes. The `Member` label and the comment itself are brighter than they used to be, but only for the inline code comments. When these show in the PR timeline they're styled correctly.

* **Browser**: chrome
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/commit/721a1d31f28454a93f434c7f106f02030decac29#r32734731
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/54326162-ef82ec80-45db-11e9-9234-f0a05d7303c6.png)

**Comment by silverwind** [comment]
The color was coming from `.highlight`. GitHub has no color on that selector so neither should we. Removed it.
