### ISSUE TITLE
multiple stars feed with white background with refined github

### ISSUE THREAD

**Issue by giuseppeM99** [StylishThemes/GitHub-Dark#885]
* **Browser**: Firefox 65.0.2
* **Operating System**: Manjaro Linux 5.0.1
* **Link to page with the issue**: https://github.com/
* **Screenshot**: 
![immagine](https://user-images.githubusercontent.com/8383704/54479583-7d4e1a00-481e-11e9-907c-dbab0d3a00eb.png)

**Comment by xt0rted** [comment]
Just released v1.21.14 which should fix this.

**Comment by giuseppeM99** [comment]
![immagine](https://user-images.githubusercontent.com/8383704/54482934-7be71680-484b-11e9-8e8f-7d609c162c8e.png)
The separator is still white
miss an !important at https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L630 ?

**Comment by xt0rted** [comment]
@giuseppeM99 I'm unable to reproduce this with the activity in my feed right now. If you could provide a copy of the html for your activity section then I can use that to fix it. The `<div data-repository-hovercards-enabled>...</div>` element is what I'm looking for.

**Comment by giuseppeM99** [comment]
Sure, here it is
https://pastebin.com/5mt3REfC

**Comment by xt0rted** [comment]
The borders look ok for me. I have v1.21.14 of GHD and v19.3.16.1845 of Refined GitHub.

![image](https://user-images.githubusercontent.com/831974/54496760-5e589200-48c9-11e9-9d66-9b237ec29e04.png)

**Comment by xt0rted** [comment]
Here's what my activity feed looks like now.

![image](https://user-images.githubusercontent.com/831974/54497962-59024400-48d7-11e9-9504-dc3cf4aaeb81.png)

**Comment by giuseppeM99** [comment]
I have Refined GitHub 19.3.17.1846 and GitHub Dark 1.21.14
Still having this issue
![immagine](https://user-images.githubusercontent.com/8383704/54498186-012e0200-4904-11e9-95cd-8205236a46a1.png)

Changing
```
  body[class="page-responsive"] .inbox-zero, .dashboard-rollup-items .body {
    border-top-color: #343434;
  }
```
To
```
  body[class="page-responsive"] .inbox-zero, .dashboard-rollup-items .body {
    border-top-color: #343434 !important;
  }
```
fixes the issue for me:

![immagine](https://user-images.githubusercontent.com/8383704/54498244-10617f80-4905-11e9-891e-1fe74e327630.png)

**Comment by xt0rted** [comment]
I'm able to reproduce this now. It looks to only happen in FF (Stylus and UserScript). @silverwind how do you want to handle this since we've been moving away from using `!important`?

**Comment by silverwind** [comment]
Should be solvable without important with a generator rule that matches the rule in `refined-github`. We do prefix their styles now which adds additional specificity, thought.

**Comment by the-j0k3r** [comment]
So, is this still an issue at this time?

**Comment by giuseppeM99** [comment]
Seems to work well now, thanks

**Comment by the-j0k3r** [comment]
Thank you =)

**Comment by giuseppeM99** [comment]
Hey remember me?
I think refined github broke this again.
![immagine](https://user-images.githubusercontent.com/8383704/57968775-11e40e00-796f-11e9-97fc-3bb768dc4669.png)
Browser: Mozilla Firefox 66.0.5
OS: Manjaro linux
Theme version: 1.21.54
Refined github version: 19.5.17.1704

**Comment by silverwind** [comment]
Not seeing this white background. Is your style up to date?

**Comment by giuseppeM99** [comment]
yes it is, version 1.21.54

**Comment by silverwind** [comment]
Not seeing it but may be broken because of https://github.com/sindresorhus/refined-github/pull/1983. I have a idea on how to fix it but it's not trivial. Consider refined-github unsupported until then.

**Comment by silverwind** [comment]
Try 1.21.55, I'm pretty positive it might fix it. If not, please find out what CSS selector adds that background. Also check if your refined-github is up to date.

**Comment by giuseppeM99** [comment]
Yup, works well again. Thansk :heart:

**Comment by fregante** [comment]
You’ll be glad to know that this feature will likely be natively fixed in the next version of Refined GitHub https://github.com/sindresorhus/refined-github/pull/3801#pullrequestreview-547548815

**Comment by silverwind** [comment]
Thanks for the notice, removed our overrides.
