### ISSUE TITLE
New/edit file page has mixed backgrounds

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#886]
The `.file-box` class is where the background color is coming from. It's using the value from one of the syntax themes.

* **Browser**: chrome & FF
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/new/master
* **Syntax theme**: Monokai
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/54501481-e061ae80-48fb-11e9-8483-670a62b615b9.png)

**Comment by stonecrusher** [comment]
lol you introduced the bug [by yourself](https://github.com/StylishThemes/GitHub-Dark/blame/037f1a2b63e0c5daa9fce6ff7827ed80e181fb7b/github-dark.user.css#L5444) with 1.21.14 :-)

Just wanted to file a bug that `.file-box` should have transparent background and found this already.
![2019-03-19 19_12_58-New File ### URL_ https___github com_stonecrusher_stylus-UserCSS_new_master](https://user-images.githubusercontent.com/1388389/54630859-15e0d600-4a7b-11e9-8743-318c15425244.png)

**Comment by xt0rted** [comment]
That's just because I did the release, the selector was added in 09ca5032e6bac947b4ceb614a9c5cae8f608d36c by @silverwind so it's their fault 😛

**Comment by silverwind** [comment]
Made that selector more specific now and did a tweak to remove a ugly margin above codemirror.
