### ISSUE TITLE
Private repo warning message has mixed styles

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#887]
* **Browser**: chrome
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/:user/:repo/settings
* **Screenshot**:

**Default**

![image](https://user-images.githubusercontent.com/831974/54539960-7b46a100-496d-11e9-949b-c8eaed5eb864.png)

**Now**

![image](https://user-images.githubusercontent.com/831974/54539926-6e29b200-496d-11e9-9564-a344d75905f1.png)

**A couple versions back**

![image](https://user-images.githubusercontent.com/831974/54540106-c2349680-496d-11e9-9df1-29e2feb25117.png)

**Comment by silverwind** [comment]
Maybe fixed by https://github.com/StylishThemes/GitHub-Dark/commit/037f1a2b63e0c5daa9fce6ff7827ed80e181fb7b?

**Comment by xt0rted** [comment]
Yea this is fixed in master.
