### ISSUE TITLE
Site header color just broke

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#889]
The header is now using the class `.Header-old` which has unstyled it. Rerunning the generator isn't fully fixing it though.

There's a lot of `.Header` selectors but I'm not sure if we want to update those or add duplicate selectors.

* **Browser**: chrome
* **Operating System**: win10
* **Link to page with the issue**: github.com
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/54648873-424a2180-4a7e-11e9-864f-701c9bef562b.png)

**After regenerating (with what's in master)**

![image](https://user-images.githubusercontent.com/831974/54648901-58f07880-4a7e-11e9-91f5-3879f5aee4e1.png)

**Comment by the-j0k3r** [comment]
can you test this: https://gist.github.com/the-j0k3r/83dcbdcada04c327e763a74a426810e3 it seems fixed here.

**Comment by scote** [comment]
@the-j0k3r I test it and it works on Chrome.

**Comment by the-j0k3r** [comment]
Thanks @scote 

@xt0rted There should be more contrast perhaps, `#222` seems a bit too dark. What do you think?

**Comment by silverwind** [comment]
Fixed this on master before seeing this thread. I mapped the blue shade of the header to `#181818` like it was before, possibly affecting a few more other elements, but nothing major.
