### ISSUE TITLE
Some input borders aren't the primary color on focus

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#893]
This can be seen in the title input of new issues & prs, as well as the issue filter input.  Removing the `!import` from the `border-color: #343434` rule looks to fix this, but I'm not sure if it also breaks anything.

* **Browser**: chrome
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/issues/new
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/54731227-76e3d900-4b63-11e9-81f3-d4e33a709f69.png)

![image](https://user-images.githubusercontent.com/831974/54731221-69c6ea00-4b63-11e9-8510-73b61876e7ca.png)

**Comment by the-j0k3r** [comment]
Here is another one

![Capture](https://user-images.githubusercontent.com/31389848/54736986-1463fa80-4bae-11e9-9c06-f849f4b3e82a.PNG)

its has blue around the top but default has none.

**Comment by the-j0k3r** [comment]
This is due to @silverwind https://github.com/StylishThemes/GitHub-Dark/commit/6c6d58de396d4d9096ecc07971ba7307a13da9a6 sadly. =( it seems like `form-control.focus` issue.

**Comment by the-j0k3r** [comment]
Im the opposite. See https://github.com/StylishThemes/GitHub-Dark/commit/6c6d58de396d4d9096ecc07971ba7307a13da9a6#r32854380

**Comment by the-j0k3r** [comment]
I have a funky one.

![generic-base-color](https://user-images.githubusercontent.com/31389848/54749263-4c7e3400-4bd4-11e9-9502-8fa65426c782.gif)

Set base color to something non blue and voila the box-shadow remains blue

![Capture](https://user-images.githubusercontent.com/31389848/54749446-d4fcd480-4bd4-11e9-949d-da0cb02c6d3a.PNG)

**Comment by silverwind** [comment]
Fixed the reported issues except the last one, not sure what's going on there. Maybe try again if latest changes did anything to it.

**Comment by the-j0k3r** [comment]
Yes, seems OK now. Thanks =)
