### ISSUE TITLE
Links in diffs are unreadable

### ISSUE THREAD

**Issue by LingMan** [StylishThemes/GitHub-Dark#896]
* **Browser**: Firefox 66.0.1
* **Operating System**: Manjaro Linux
* **Link to page with the issue**: https://github.com/iXit/wine-nine-standalone/commit/e9cfdd9d2ebdbca7b757adf15c6779e2b0e728e3
* **Screenshot**: 
![Screenshot from 2019-03-27 13-13-23](https://user-images.githubusercontent.com/18645382/55075191-a5e1d980-5092-11e9-832d-59e1bae301c3.png)

It's especially bad on the green background.

**Comment by Mottie** [comment]
Hi @LingMan!

Thanks for letting us know. And providing a link was great help!

It looks like the class `.pl-corl` hasn't been included in all of our GitHub syntax themes (including our [template](https://github.com/StylishThemes/GitHub-Dark/blob/master/themes/src/_template-github.css#L137)).

I found that [primer's dark syntax theme](https://github.com/primer/github-syntax-dark/blob/master/lib/github-dark.css#L126) doesn't match [the color](https://github.com/StylishThemes/GitHub-Dark/blob/master/themes/src/github/github-dark.css#L108) we have set from an older version of primer's theme. We should update that style and check & update our other GitHub syntax styles with any missing selectors.

**Comment by the-j0k3r** [comment]
`.pl-corl` related by @Mottie https://github.com/StylishThemes/GitHub-Dark/commit/7dd80bd3f838f23cb04d40fce97a77c0bd0c53cf  but that doesnt seem to exist anymore.

GHD 3 themes only styling this. 

* themes/src/github/one-dark.css
* themes/src/github/railscasts.css
* themes/src/github/github-dark.css

One could try those themes and see how that is going.

**Comment by the-j0k3r** [comment]
@Mottie so do we want static definitions for all styles or do we want a base-color solution so all links match what we set in GHD?

**Comment by Mottie** [comment]
I think it should be static & match the syntax style since we can't guarantee a base-color link would be readable on all syntax background colors.

**Comment by the-j0k3r** [comment]
The only problem is to find what color each style uses, Ive no idea where to go find that.

**Comment by Mottie** [comment]
I added a "Commit (rst) Diff" example to the [demo](https://stylishthemes.github.io/GitHub-Dark/) - I essentially picked the SCSS link color from each theme.

**Comment by LingMan** [comment]
Thanks for the quick fix.
