### ISSUE TITLE
PDF viewer styles missing

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#904]
* **Browser**: chrome
* **Operating System**: win10
* **Link to page with the issue**:
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/55353356-16249c80-5491-11e9-9ddd-466a00674375.png)

![image](https://user-images.githubusercontent.com/831974/55354102-d8c10e80-5492-11e9-8fed-ce27b544fb6f.png)

I have [a large pdf](http://xml.cxml.org/current/cXMLReferenceGuide.pdf) in one of my repos and when you click through to it GitHub will render the first 50 pages and show a button to view more pages.

The area with the button isn't styled, adding this file to the generator fixes it https://render.githubusercontent.com/assets/pdf-effeb1f6266aa69a5cc3fb0de5617951.css.

It looks like [public pdfs](https://github.com/npm/shirts/blob/7422b3be1cc61cbc98567db5febd80dc772b6d04/old/invoice.pdf) will render in the viewer even when you're not logged in, but the generator doesn't pick up the style sheet because it's in an iframe. If you go to https://render.githubusercontent.com there isn't anything that references this file either.

Do we want to find a way to make this work with the generator, or should we run it through the generator and then copy the selectors over to existing rules?

**Comment by Mottie** [comment]
Hi @xt0rted!

From my brief examination, it seems like each page of the PDF is drawn on a canvas, at least in the example page you shared, and in [Mozilla's PDF.js repo](https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld.pdf). We could invert the canvas but then any and all images would also be inverted.

Can you share a link to a PDF that is rendered using PDF.js? If GitHub uses this library, it would render everything in HTML ([example](https://mozilla.github.io/pdf.js/web/viewer.html)); and therefore we could style it.

**Comment by the-j0k3r** [comment]
PDF repos for testing

* https://github.com/mynane/PDF/tree/master/typescript_pdf
* https://github.com/tpn/pdfs

**Comment by xt0rted** [comment]
@Mottie GitHub is using PDF.js but depending on how you use it you can output either html or `canvas` tags. Their implementation looks to be to download the file via a web worker and then render each page out to a `canvas` tag.

The css for the viewer doesn't style the pdf output, it's just for the UI elements like the container background and the footer with the load more button & spinner.

**Comment by silverwind** [comment]
Found a way to add it to the generator. Bottom "more" panel is covered, not sure if there's anything else to do.

**Comment by xt0rted** [comment]
Looks good to me.

**Comment by Atcold** [comment]
It's still broken.
If you go to this [link](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/slides/10%20-%20Attention%20%26%20transformer.pdf), you'll the last page is missing.

**Comment by the-j0k3r** [comment]
> It's still broken.
> If you go to this [link](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/slides/10%20-%20Attention%20%26%20transformer.pdf), you'll the last page is missing.

I did go and this is what I see

![Screenshot_2020-04-22 Atcold pytorch-Deep-Learning](https://user-images.githubusercontent.com/31389848/79951011-3e09e800-8478-11ea-936f-8d9b9c46ddd1.png)

Thats exactly the same as with GHD disabled.

Ensure that:

* no other addons are interfering.
* its not the browser profile
* try dif browser

State you operating details, show screenshots essentially thers not much to go on.

**Comment by Atcold** [comment]
Try zooming in to, say 200% (yeah, I'm using a very large screen).

**Comment by the-j0k3r** [comment]
@Atcold 

What you want to do is test wih GHD disabled and enabled, with GHD disabled at 200% I see no issues

Also with GHD enabled seems to be complete

![generic](https://user-images.githubusercontent.com/31389848/80308129-70e01300-87cd-11ea-92c3-61155e74bec8.gif)

So without you posting more information lie I requested earlier as is I cant duplicate your issue.

**Comment by Atcold** [comment]
Hmm…
<img width="1500" alt="Screenshot 2020-04-27 at 23 18 32" src="https://user-images.githubusercontent.com/2119355/80443559-7af13700-88dd-11ea-9517-28af92473e99.png">
<img width="1499" alt="Screenshot 2020-04-27 at 23 18 01" src="https://user-images.githubusercontent.com/2119355/80443566-7dec2780-88dd-11ea-9c11-c29c05f70963.png">

**Comment by the-j0k3r** [comment]
@Atcold nothing to be done here.

* Tell us what browser youre using.
* Tell us what OS youre using
* Disable ALL other addons
* Try a Different Browser
*Ttry a Fresh browser profile.

So far cannot duplicate. and cant fix what cant be duplicated.
