### ISSUE TITLE
Octotree v3 support <3

### ISSUE THREAD

**Issue by xPixv** [StylishThemes/GitHub-Dark#911]
* **Browser**: Chromium Edge Dev
* **Operating System**: Windows 10
* **Link to page with the issue**: Any repo
* **Screenshot**:
![image](https://user-images.githubusercontent.com/9652227/56082796-bbefe800-5e4f-11e9-83a7-c6c7c1d6b803.png)

![image](https://user-images.githubusercontent.com/9652227/56082788-98c53880-5e4f-11e9-8831-3cdc59cc26fd.png)

Thank you in advance~

BTW, dark mode is provided in Octotree Pro.

**Comment by the-j0k3r** [comment]
Hello @xPixv! Thank you for reaching out with this request. =)

Im assuming you meant this https://github.com/ovity/octotree ?

From my part, Ive no plans at this time to add support for this, but that's not to say someone else wont, but lets wait for other feedback ;)

Thanks -)

**Comment by Mottie** [comment]
We supported the older version of Octotree, I don't see why we can't support the newer version.

**Comment by Mottie** [comment]
But, yeah... moving it to a separate userstyle would be better.

**Comment by xt0rted** [comment]
The only issue I see with styling this now is there's two versions starting with v3. There's the free open source version and a new paid version with extra features (which includes a dark theme actually). Updating the existing style for this shouldn't be an issue but we'll need to rely on pro users to help with any missing styling there.

**Comment by xt0rted** [comment]
Just pushed up https://github.com/StylishThemes/GitHub-Dark/commit/c6e6d85563c03c273bc3aa4bf372c739a403ac33 which is my first pass at supporting v3. There's some old selectors that probably need removing, but this gets us almost all of the way there.

![image](https://user-images.githubusercontent.com/831974/56084205-b7024880-5dfd-11e9-83f4-aa602b849c4b.png)

**Comment by xPixv** [comment]
Hi @xt0rted ,
I found that Octotree Free and Octotree Pro are TWO extentions.

Free: https://chrome.google.com/webstore/detail/octotree/bkhaagjahfmjljalopjnoealnfndnagc
Pro: https://chrome.google.com/webstore/detail/octotree-pro/fjcahddnekkgihjnjnimgiggdmlgcnbc

Pro have dark mode natively. How about GitHub Dark support Free version only? As long as GitHub Dark do not break Pro dark mode style.

**Comment by MCOfficer** [comment]
That would require [whoever does it] to purchase the pro version, if they even have distinctive differences.
It might be easier to just create a variable which disables octotree support.

**Comment by Patrick-Batenburg** [comment]
Octotree Pro with white theme:
![octotree-pro-white-main](https://user-images.githubusercontent.com/10193417/56100653-cd062b00-5f1b-11e9-8754-659994a8a291.png)

Octotree Pro with dark theme:
![octotree-pro-main-main](https://user-images.githubusercontent.com/10193417/56100661-e1e2be80-5f1b-11e9-9362-20b21d7840c3.png)

Octotree Pro with white theme search:
![octotree-pro-white-search](https://user-images.githubusercontent.com/10193417/56100662-e60edc00-5f1b-11e9-8a68-8074e1511000.png)

Octotree Pro with dark theme search:
![octotree-pro-dark-search](https://user-images.githubusercontent.com/10193417/56100664-ead39000-5f1b-11e9-9e81-bab6be242c13.png)

When using dark theme most texts gets a teal colour or input boxes get a teal coluored outline:
![search](https://user-images.githubusercontent.com/10193417/56100689-35550c80-5f1c-11e9-95db-72684516b1ec.png)

Octotree Pro without dark theme, but with Github Dark enabled:
![image](https://user-images.githubusercontent.com/10193417/56100771-160aaf00-5f1d-11e9-9e9f-d2c8cea6b3ce.png)

Gist of Octotree Pro DOM if needed: https://gist.github.com/Patrick-Batenburg/2e63e455f69dcdf3268e2f120c23edb3

**Comment by xt0rted** [comment]
I made a few more changes and pushed v1.21.35. Give this a try and let us know how it looks.

**Comment by xPixv** [comment]
Hi @xt0rted ,
Free version everything is OK. Maybe we need wait @Patrick-Batenburg 's Pro version feedback.

But, how can I make these `white` words (or icons) to `#bebebe`? 

![image](https://user-images.githubusercontent.com/9652227/56105285-0ff0ee80-5f6e-11e9-8904-4114a2aebe3f.png)

![image](https://user-images.githubusercontent.com/9652227/56105311-29923600-5f6e-11e9-98cc-5870167b4353.png)

![image](https://user-images.githubusercontent.com/9652227/56105319-33b43480-5f6e-11e9-99d9-8eff02f3f90a.png)

![image](https://user-images.githubusercontent.com/9652227/56105337-4c244f00-5f6e-11e9-8f8e-ad4535aa6c05.png)

Did I miss something?

**Comment by iamsauravsharma** [comment]
Issue with folder and file name color
Browser:- Firefox 66.0.3
Operating system:- Manjaro
![Screenshot_20190415_113906](https://user-images.githubusercontent.com/38726015/56110176-42511a80-5f73-11e9-851c-bb5c3bddbc33.png)

**Comment by MCOfficer** [comment]
Same issue as  @iamsauravsharma , Firefox 67.b10 @ Ubuntu Mate 18.04

- No other userstyles or userscripts
- All other Add-Ons disabled
- Tried Firefox "Default", "Light" and "Dark" Theme

**Comment by Fubuchi** [comment]
@MCOfficer, @iamsauravsharma   If you inspect the site and disable the color line like this

![image](https://user-images.githubusercontent.com/42483897/56147797-15cceb00-5fd3-11e9-8396-acedc263c562.png)

Your selected color in github dark setting will work even after YOU RELOAD THE TAB OR OPEN ANOTHER REPO IN THAT ONE. Unfortunately, if you open another tab, you must do it again. I'm not sure what is the magic here because chrome doesn't have this bug.

**Comment by indocomsoft** [comment]
I tried fixing the issue with Firefox in PR #914

**Comment by xt0rted** [comment]
The FireFox text color issue was resolved but I'll let @silverwind or @the-j0k3r do the release since they made all the changes since the last one and I'm not sure if they're finished yet.

I also styled the popup that shows on first run or when you load two instances of the extension.

![image](https://user-images.githubusercontent.com/831974/56267660-76385700-60bd-11e9-98ae-2a3f1da8386b.png)

For some reason none of the icons will load for me in FF. Is anyone else having this issue? This is what's showing in my console.

```
Content Security Policy: The page’s settings blocked the loading of a resource at chrome-extension://0d3a30c7-7c46-437c-af9c-67ccabd54bdb/fonts/fontawesome.woff2 (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at chrome-extension://0d3a30c7-7c46-437c-af9c-67ccabd54bdb/fonts/octicons.woff2 (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at chrome-extension://0d3a30c7-7c46-437c-af9c-67ccabd54bdb/fonts/file-icons.woff2 (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at chrome-extension://0d3a30c7-7c46-437c-af9c-67ccabd54bdb/fonts/devopicons.woff2 (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at chrome-extension://0d3a30c7-7c46-437c-af9c-67ccabd54bdb/fonts/mfixx.woff2 (“font-src”).
```

**Comment by MCOfficer** [comment]
i just now ran into this issue, through sheer coincidence, so: no, it's no just you. i'll let you know when i can repro it.
