### ISSUE TITLE
Merge PR confirmation box arrow is the wrong color

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#915]
* **Browser**: chrome
* **Operating System**: win10
* **Link to page with the issue**: go to any open PR and click the merge button, when the confirmation button shows that's when the arrow is the wrong color
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/56266950-79cade80-60bb-11e9-852c-8ed970676f6b.png)

**Comment by the-j0k3r** [comment]
I would have a shot at this, except for laziness and not having an open PR to test, I did have a go at yours https://github.com/StylishThemes/GitHub-Dark/pull/868 but it has conflicts in generate.js so I wont get any mileage on this until that is done =)

Is the time you spend on rebasing that PR less than fixing this? IDK hehe =)
