### ISSUE TITLE
Scrollbars are not styled on Chrome

### ISSUE THREAD

**Issue by abyss7** [StylishThemes/GitHub-Dark#916]
* **Browser**: Google Chrome
* **Operating System**: Fedora 30
* **Link to page with the issue**: any page with scrollbar
* **Screenshot**: 
![Screenshot_20190417_155941](https://user-images.githubusercontent.com/5627721/56289656-19bf5100-612a-11e9-942d-e9f4b1f7d924.png)

**Comment by the-j0k3r** [comment]
Hello @abyss7 ! Thank you for reaching out with that report.

Please take a look at https://github.com/StylishThemes/Overlay-Scrollbars, more specifically https://github.com/StylishThemes/Overlay-Scrollbars/blob/master/github-overlay-scrollbars.user.css

Have a good day. =)
