### ISSUE TITLE
Settings icon is the wrong color

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#917]
* **Browser**: chrome 73
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/settings
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/56325014-a542dd00-613e-11e9-80d7-123067ead2e3.png)

![image](https://user-images.githubusercontent.com/831974/56325019-ad9b1800-613e-11e9-87f1-4c5045038c24.png)

**Comment by the-j0k3r** [comment]
They all could do with brightening up, In Firefox everything is darker, IDK why.

Also why is it you have access to that part and I dont...  I get a 404 page... thx @silverwind =)

**Comment by the-j0k3r** [comment]
Well mine is not even there,

![Capture](https://user-images.githubusercontent.com/31389848/56338299-d4426880-61a9-11e9-8fe1-36b55f8484c7.PNG)
