### ISSUE TITLE
Status section looks strange around the emoji

### ISSUE THREAD

**Issue by J12ATA** [StylishThemes/GitHub-Dark#919]
Color needs to be changed from `#ccbb44` to `#fffbdd`

* **Browser**: Chrome Version 74.0.3729.91 (Official Build) beta (64-bit)
* **Operating System**: MacOS Mojave 10.14.4 (18E226)
* **Screenshot**: 
<img width="1280" alt="Screen Shot 2019-04-18 at 4 34 28 PM" src="https://user-images.githubusercontent.com/12861319/56397288-e64af800-61f7-11e9-8bd8-0419bed6e93e.png">

Thanks in advance!

**Comment by xt0rted** [comment]
Looks like they changed the class name for this. Regenerating fixes it. Working on a new release now.

**Comment by xt0rted** [comment]
Fixed in 82b817f9d0932015f607bc0fb68bfa63eaa1db03 and released in [v1.21.40](https://github.com/StylishThemes/GitHub-Dark/releases/tag/v1.21.40).

**Comment by J12ATA** [comment]
I can confirm it is now working. Thank you @xt0rted 😃

**Comment by Mottie** [comment]
There's a yellow border in my profile... weird

**Comment by xt0rted** [comment]
Same here, looks like it's only showing up on my own status when it's set to busy.

**Comment by xt0rted** [comment]
Fixed in b8c8959292cfbf125826bb3ffb96b5c10583ebaa and released in [v1.21.41](https://github.com/StylishThemes/GitHub-Dark/releases/tag/v1.21.41).
