### ISSUE TITLE
Expand/Collapse Button in PR Review not working as expected 

### ISSUE THREAD

**Issue by StephenHodgson** [StylishThemes/GitHub-Dark#923]
* **Browser**: Chrome
* **Operating System**: Windows 10
* **Link to page with the issue**: Any Pull Request Review Files tab

Problem Behavior:

Alt + Click does not expand / collapse all files

Expected Behavior:

Alt + Click will expand / collapse all files

**Comment by Mottie** [comment]
Hi @StephenHodgson!

If you're referring to the [GitHub-diff-file-toggle](https://greasyfork.org/en/scripts/18788-github-diff-file-toggle) userscript, it's actually <kbd>Shift</kbd> + Click.

**Comment by StephenHodgson** [comment]
For vanilla GitHub I'm confident it's Alt. But in either case Shift doesn't work either.

**Comment by StephenHodgson** [comment]
Either that or the script you linked is interfering with vanilla GitHub functionality. 

Sometimes it doesn't load in if the diff is too big and the regular style comes though:
![image](https://user-images.githubusercontent.com/13334553/56527289-4ac0cc80-6502-11e9-8ad1-97e9a534240e.png)

**Comment by Mottie** [comment]
It doesn't look like the userscript is enabled. The arrow becomes a button, and includes a tooltip:

![arrow](https://user-images.githubusercontent.com/136959/56528709-3df9a400-6515-11e9-8e4d-37b375f638ac.png)

**Comment by Mottie** [comment]
It does appear to break the built-in <kbd>Alt</kbd> + Click, but I've been testing it and the <kbd>Shift</kbd> + Click does work. As does the accordion mode.

**Comment by StephenHodgson** [comment]
> It doesn't look like the userscript is enabled. 

It is, but sometimes when the diff is large it breaks/doesn't load for whatever reason. (Might be a separate issue).

I'm all for just disabling that script completely. How does one go about doing that?

**Comment by Mottie** [comment]
Uninstall it from Tampermonkey/Greasemonkey... or if you're using our GitHub Dark Script, open the settings window ([ref](https://github.com/StylishThemes/GitHub-Dark-Script#using-the-script)).

**Comment by StephenHodgson** [comment]
Ah, the settings was in the GitHub settings in the website. Tricky haha. Found it.

I'll go ahead and close this then.
