### ISSUE TITLE
Mobile tabs need better styling

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#924]
* **Browser**: kiwi browser or chrome desktop in mobile view
* **Operating System**: android 9/win10
* **Link to page with the issue**:
  - https://github.com/
  - https://github.com/StylishThemes/GitHub-Dark
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/56612418-5daace00-65e2-11e9-920c-18a498780b96.png)

![image](https://user-images.githubusercontent.com/831974/56612400-5257a280-65e2-11e9-9cbb-91ab8894da85.png)

![image](https://user-images.githubusercontent.com/831974/56612715-078a5a80-65e3-11e9-9262-c6064169e44a.png)

![image](https://user-images.githubusercontent.com/831974/56612768-2557bf80-65e3-11e9-97a4-5569014f0a6e.png)

With the [Overlay-Scrollbars](https://github.com/StylishThemes/Overlay-Scrollbars) style. Not sure if there's a way to exclude the mobile views from this or if we even want to try. I'm not using it on my phone, it's showing up here because I'm using chrome & dev tools.

![image](https://user-images.githubusercontent.com/831974/56612444-6b605380-65e2-11e9-86e6-bab5d294aa2b.png)

![image](https://user-images.githubusercontent.com/831974/56612383-3f44d280-65e2-11e9-8be9-2616361b70b7.png)

**Comment by silverwind** [comment]
2px line removed, need to do more (add transparency).

**Comment by xt0rted** [comment]
With the recent UI changes this isn't an issue anymore.
