### ISSUE TITLE
OAuth screen is missing hover style

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#926]
You don't need to sign up for ZenHub, just click the `Sign in with GitHub` button to see the authorize screen.

The color being used here is `#ffe` but I'm not sure what would look good in its place. I'm thinking maybe `#242424` or `#333`. The yellow doesn't seem to have any contextual meaning other than to show that the item is being hovered so a light grey seems more appropriate than a brownish yellow.

* **Browser**: chrome
* **Operating System**: win10
* **Link to page with the issue**: https://app.zenhub.com/login
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/56614854-f98b0880-65e7-11e9-93a7-76dd213de122.png)

![image](https://user-images.githubusercontent.com/831974/56614882-03ad0700-65e8-11e9-87a7-4513085e6041.png)

The top is `#333` and the bottom is `#242424`.

![image](https://user-images.githubusercontent.com/831974/56615787-d7928580-65e9-11e9-9153-7e2965d18615.png)

**Comment by silverwind** [comment]
Voting for `#242424`

**Comment by the-j0k3r** [comment]
Also voting for `#242424`

**Comment by the-j0k3r** [comment]
Should be fixed in next release
