### ISSUE TITLE
Incorrect colors in header elements, and lines above header links

### ISSUE THREAD

**Issue by akmadian** [StylishThemes/GitHub-Dark#928]
I've had some small graphical bugs for the last month or so, the GH octocat logo is blue instead of white, as are the PR, Issues, Marketplace, and Explore links. The links in the header also have small grey lines over them. The blue coloring persists to other pages with the header, but the grey lines don't. No functionality is broken, it's just visual.

I'm not very good with CSS :/

* **Browser**: 73.0.3683.103 (64 Bit)
* **Operating System**: Win 10 Pro (64 Bit)
* **Link to page with the issue**: https://github.com/
* **User CSS Version:** 1.20.104 (at least this is what it says in the file)
* **Screenshot**: ![pic](https://i.imgur.com/IqkBcZZ.png)

I'd be happy to help work on this, but I'm not sure how much help I could be... Thanks for your work, my eyes love it!

**Comment by the-j0k3r** [comment]
@akmadian Thank you for reaching out with this issue report.

Your usercss version is quite outdated, current version is 1.21.45, so try to force update your version [click here](https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-dark.user.css) and if issue persists, make a comment on this ticket so we can reopen it.

Thank you again.

**Comment by akmadian** [comment]
That fixed it, thanks!

**Comment by the-j0k3r** [comment]
If you're using Stylus and make any local edits to any installed styles, when the default 24-hour check for updates comes, those styles are bypassed and can only be force-updated instead of being automatically updated.

I cant think of any other reason why your version of GHD was so far behind. =)

Glad its working though =)
