### ISSUE TITLE
Commit changes arrow is the wrong color

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#929]
These arrows are so annoying now. Every time one is fixed another breaks.

* **Browser**: chrome 73
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/edit/master/.npmrc
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/56814352-03da1c00-680d-11e9-83f7-d54b93f39805.png)

**Comment by xt0rted** [comment]
This fixes the color, but who knows where else it may break. I'm going to run with this locally for a bit to see if anything stands out.

```css
.commit-form:after {
  border-right-color: #202020;
}
```

**Comment by the-j0k3r** [comment]
This is autogenerated to `#181818` 

https://github.com/StylishThemes/GitHub-Dark/blob/2bb91a83a13f2eccf7646250825a99aea4a0cf98/github-dark.css#L1123-L1129 so its likely changing the autogen color something else in that group may break

**Comment by xt0rted** [comment]
This is still an issue.

![image](https://user-images.githubusercontent.com/831974/56920458-3bf19100-6a91-11e9-8bf5-13058d535ace.png)

![image](https://user-images.githubusercontent.com/831974/56920471-47dd5300-6a91-11e9-996a-863f03241919.png)

**Comment by the-j0k3r** [comment]
Its broken again in a completely different way... this was broken after https://github.com/StylishThemes/GitHub-Dark/commit/a13973e0ddff61c2142549b44102980e3bc17c72 right?

**Comment by the-j0k3r** [comment]
Yep order of generated styles I guess.

https://github.com/StylishThemes/GitHub-Dark/blob/ebd3fdcc4cd149ca29d03188f16c3b9be492a356/github-dark.css#L552-L555

https://github.com/StylishThemes/GitHub-Dark/blob/ebd3fdcc4cd149ca29d03188f16c3b9be492a356/github-dark.css#L708-L710

and this breaks it.

https://github.com/StylishThemes/GitHub-Dark/blob/ebd3fdcc4cd149ca29d03188f16c3b9be492a356/github-dark.css#L1084-L1100

@silverwind

**Comment by silverwind** [comment]
Will check it out

**Comment by the-j0k3r** [comment]
@silverwind same issue with https://github.com/StylishThemes/GitHub-Dark/issues/936

Not that it matters much, all my FF extensions have been disabled =)

**Comment by the-j0k3r** [comment]
This commit broke it https://github.com/StylishThemes/GitHub-Dark/commit/92ee1a98cbc017344d3e553e35e757211c062554

but now that I fixed #918 and transposed issue https://github.com/StylishThemes/GitHub-Dark/issues/942 The positioning of the  border in generator can be rest, thus all the issues around this wack-a-mole can be closed too.

I know I said I would wait for feedback, but, these issues bug me a great deal.

**Comment by silverwind** [comment]
Fine with it. The proper fix for these order issues would be to generate in original style order, but that will result in a few thousand generated rules that were tedious to scroll through which is why it's not implemented yet.

**Comment by the-j0k3r** [comment]
I think it works as is atm, afaik you moved the rule to fix mobile mobile style which had no effect in the end except cause issues, I find some of the time its trial and error to come up with something that fully work. 

I think mobile styles vs desktop really need a robust @media call so we dont have to break unnecessary things in future. 

It would be a fantastic addition to a new style, published side-by-side, I know you said you dont like the extra workload, but it would also make the styles specific and thus smaller and not so much to scroll through. Not that you have to cause it would be I guess autogenerated like the current usercss is, I dont think this would add much overhead to generator, but that last part is just a guess.
