### ISSUE TITLE
Patch Files have white background color.

### ISSUE THREAD

**Issue by SE7-KN8** [StylishThemes/GitHub-Dark#932]
* **Browser**: Firefox 66.0.3
* **Operating System**: Windows 10
* **Link to page with the issue**: [link (Example)](https://github.com/1g4-linux/bp/blob/5b2d01b3be39842cd555994f545982827469511f/dev-lang/python/files/shrink_python.patch)
* **Screenshot**:
![grafik](https://user-images.githubusercontent.com/35075354/56910403-c8f51400-6aaa-11e9-85d6-68e323f7d826.png)

**Comment by xt0rted** [comment]
This is the `GitHub Dark` syntax theme

**Comment by silverwind** [comment]
Theme issue?

**Comment by xt0rted** [comment]
Looks like the `.pl-md` and `.pl-mi1` classes are using the default colors for this theme.

**Comment by the-j0k3r** [comment]
Yea, the themes were all updated recently, including this, I'll have a go at this in a sec.

**Comment by the-j0k3r** [comment]
after fix ![Capture](https://user-images.githubusercontent.com/31389848/56946530-9a1e8280-6b2a-11e9-8a9a-30a62458d3c8.PNG)
