### ISSUE TITLE
Draft PR icon is the wrong color on mobile

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#934]
* **Browser**: Kiwi browser (screenshots taken in Chrome dev tools)
* **Operating System**: Android 9
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/pulls
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/56920626-b9b59c80-6a91-11e9-817e-4ce848689bd7.png) ![image](https://user-images.githubusercontent.com/831974/56920651-c5a15e80-6a91-11e9-8a45-c24778a920ab.png)

**Comment by xt0rted** [comment]
I think this is a color ordering issue which is causing the green to take priority over the grey.

**Comment by silverwind** [comment]
Yes it is, there's no elegant fixes for these, but I reordered for now.
