### ISSUE TITLE
Should the border-blue class apply blue or the primary color?

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#935]
The `.border-blue` class is being used to style alert sections on the help site, but we're setting that to the primary color. Should this be blue or the primary color? For similarly looking elements such as branches, tags, labels, and commit details, we're using blue for the borders.

I'm not sure where else this style is used, so far these alert boxes is the only spot I've found. However, I did find that the alert box about setting up issue templates is using the class `.border-blue-light` which is not set to the primary color.

* **Browser**: chrome 74
* **Operating System**: win10
* **Link to page with the issue**:
  - https://help.github.com/en/articles/searching-code
  - https://github.com/StylishThemes/GitHub-Dark/settings
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/56981504-07dba600-6b4d-11e9-8139-acdfdd6d3507.png)

![image](https://user-images.githubusercontent.com/831974/56981867-e929df00-6b4d-11e9-851c-4f353b16514b.png)

**Comment by silverwind** [comment]
Seems resonable to have those classes with "blue" in their name stay actually blue.

**Comment by the-j0k3r** [comment]
https://github.com/StylishThemes/GitHub-Dark/blob/31cca07ed8b6f737db0e705fc676a2771253c868/tools/generate.js#L167

I would just change that to `#246` aka `#224466`

**Comment by the-j0k3r** [comment]
OK, I went with a manual fix to avoid breaking these other areas where a base-color is wanted.
If there is another way to fix this without breaking something else, please let me know specifically what that is.

The commit message should be self explanatory.
