### ISSUE TITLE
The network graph has been removed

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#937]
https://github.blog/changelog/2019-05-01-deprecating-the-network-graph/

If I'm not mistaken there was custom styling for this which can be removed now.

**Comment by silverwind** [comment]
There is a invert that targeted that `<canvas>`, but other than that, there shouldn't be much.

**Comment by silverwind** [comment]
Bit sad to see it go, it was a nice way to find the most active forks of a repo.

**Comment by xt0rted** [comment]
You're not alone https://twitter.com/GHchangelog/status/1123612047059685378

**Comment by xt0rted** [comment]
Some good news after all https://twitter.com/lukehefson/status/1123643479459094528

>From what I know your guess about compute is close to the truth and that the team is already working on even better solutions!!! Apologies for any disruption to your workflows in the mean time ❤️

**Comment by the-j0k3r** [comment]
Ive no idea what the benefits are of ripping something out without a better working replacement, if that was the intention. I would love to see the replacement not be within some canvas type, They aent exactly best looking elements when inverted.

**Comment by the-j0k3r** [comment]
the relevant selector is `div#network.network > div > canvas` within https://github.com/StylishThemes/GitHub-Dark/blob/ebd3fdcc4cd149ca29d03188f16c3b9be492a356/github-dark.css#L4011-L4017

**Comment by xt0rted** [comment]
After the negative response to their incorrect usage of `deprecate` the network graph is back, for now.

https://github.com/StylishThemes/GitHub-Dark/network

**Comment by the-j0k3r** [comment]
> After the negative response to their incorrect usage of `deprecate` the network graph is back, for now.

It was when I check around for these earlier, so I assumed it never left.

I also block twitter and friends so never really read the `negative` feedback on this.
All I wish is that the replacement wont be within a canvas so we can actually style it properly.

**Comment by xt0rted** [comment]
From what I heard they're now making improvements to this instead of removing & replacing. There's really nothing we need to do for now.

**Comment by silverwind** [comment]
Hope they get rid of the canvas in turn to allow proper styling :)

**Comment by the-j0k3r** [comment]
If only as many ppl complaining about the removal, would suggest some alternative to canvas, it would likely have a more positive effect. Now only 4 suggestions from us, Im not sure what will happen there, not that I know what to suggest either atm.

**Comment by xt0rted** [comment]
The changes being worked on now sound like it's purely on the backend for how the graph data is generated. The UI was never an issue for them, but the effort required to generate the data was.
