### ISSUE TITLE
Color of links and icons do not suit well with a dark theme

### ISSUE THREAD

**Issue by alexherbo2** [StylishThemes/GitHub-Dark#940]

**Comment by Mottie** [comment]
Hi @alexherbo2!

The link & icon colors are set by the base color of our theme. You can see a list of all the options on the [installation wiki page](https://github.com/StylishThemes/GitHub-Dark/wiki/Install#options).

**Comment by the-j0k3r** [comment]
@alexherbo2

If you have not installed our usercss version, I recommend it, it has configurable options to change your link/icon colors to something you prefer, like so:

![Capture](https://user-images.githubusercontent.com/31389848/57175751-99019400-6e4f-11e9-883c-033eec6edb68.PNG)

 If there is something else regarding this subject, feel free to elaborate on further comments illustrations such as screenshots are also helpful.

For now, closing this.
