### ISSUE TITLE
Green background rule not being applied due to malformed selector

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#941]
I was just goofing around on the 2FA settings page and noticed the green `Enabled ✔️` label wasn't being styled. After digging through our styles I found that we have a rule and selector for this, but the entire rule is being ignored because of a malformed selector in it.

https://github.com/StylishThemes/GitHub-Dark/blob/31cca07ed8b6f737db0e705fc676a2771253c868/github-dark.css#L2242

The selector in question is `.select-menu-button.primary:after:active` and is coming right from GitHub's style sheet like that. This looks to possibly be an old rule used on the green merge button dropdown but the current one uses slightly different selectors.

I'm not sure what we can do to fix this aside from maybe exclude it in the generator? The reason it's not working is because the pseudo element selector should come second. If I reorder those then the rule is picked up and applied to the label.

I've passed this on to someone so hopefully this gets fixed upstream and we don't need to do anything aside from regenerate.

* **Browser**: chrome 74
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/settings/two_factor_authentication/configure
* **Screenshot**:

**As-is**

![image](https://user-images.githubusercontent.com/831974/57117927-9870dc80-6d2d-11e9-9f88-1df4d25813f2.png)

**Modified selector**

![image](https://user-images.githubusercontent.com/831974/57117986-1e8d2300-6d2e-11e9-8353-a2e814fd41b2.png)

**Comment by silverwind** [comment]
Maybe we could do a selector validation in the generator. Not sure if PostCSS is up to the task, but it seems a good way to prevent future issues like this.

**Comment by xt0rted** [comment]
For now it seems easier to just exclude `.select-menu-button.primary:after:active` in the generator.

There seems to be two issues going on here. The first is GitHub's shipping an invalid selector, and the second is all of the browsers I've tested (Chrome, Edge, IE11, FF, iOS Safari) fully ignore the rule when this selector is part of it. I'd expect the other selectors on the rule to apply, but the browsers simply don't load the rule at all. My repro of this that was reported to GitHub can be seen here https://codepen.io/xt0rted/pen/OYLbeJ.

**Comment by silverwind** [comment]
This is normal CSS behaviour. If one selector in a group is invalid, the whole group is ignored. That's why we currently exclude vendor-specific selectors.

I tried a few validators without any luck. Specifically, I need one that validates this from Selectors Level 3:

> Only one pseudo-element may appear per selector, and if present it must appear after the sequence of simple selectors

**Comment by silverwind** [comment]
As a workaround, add something like `/::?(before|after):.+/` to `unmergeableSelectors `.

**Comment by silverwind** [comment]
Trying something

**Comment by xt0rted** [comment]
Is that supposed to force a standalone rule for just `.select-menu-button.primary:after:active`? It looks to exclude it entirely just like if it was in the `ignoreSelectors` list.

```diff
index 6d6ff0e..7d78578 100644
--- a/github-dark.css
+++ b/github-dark.css
@@ -2318,8 +2318,7 @@
     color: #6cc644 !important;
   }
   /* auto-generated rule for "background-color: #28a745" */
-  .btn-primary, .btn-primary-mktg:hover,
-  .select-menu-button.primary:after:active, .billing-plans .coupon td,
+  .btn-primary, .btn-primary-mktg:hover, .billing-plans .coupon td,
   .plan-choice--experiment.open .plan-choice-icon,
   .plan-choice--experiment.selected .plan-choice-icon,
   .plan-choice--experiment.plan-choice--green.open .plan-choice-icon,
```

**Comment by silverwind** [comment]
Yes, it should actually create a standalone rule, but I see it's not implemented correctly and drops it entirely. Gonna fix that later. Workaround applied. Still looking into a validator.

**Comment by silverwind** [comment]
Fixed `unmergeableSelectors` handling in  https://github.com/StylishThemes/GitHub-Dark/commit/34da0877db28f0ad7ca0ca3e01997fe211151b07 and moved the invalid selector to `ignoreSelectors` in https://github.com/StylishThemes/GitHub-Dark/commit/32df9a5097949edc36e1b7e062a0eaae69a0b107, so this is fixed.

**Comment by xt0rted** [comment]
@silverwind I just came across another icon on mobile that should be red but wasn't (it's related to 72d63477af4deb1a83e08ff26a6e77f6b2e6242a). After digging into it more I found the issue is coming from another bad selector at line 3216.

https://github.com/StylishThemes/GitHub-Dark/blob/893fb77a11d77696267200c927bae91bd250a353/github-dark.css#L3216-L3217

Removing this selector causes the rule to be picked up and the icon is styled red. How should this get added to the exclude list?

**Comment by silverwind** [comment]
Oh, good find. I removed that rule assuming GitHub had fixed but apparently not. Restored it in https://github.com/StylishThemes/GitHub-Dark/commit/907a0ccdfc19194949a81de26a39843cd9f30311.

I'm looking for a module to validate CSS selectors. The only good ones I've found use the online W3C service which is not what I want, it should just work offline.

**Comment by the-j0k3r** [comment]
Theres a java download here http://jigsaw.w3.org/css-validator/DOWNLOAD.html

**Comment by silverwind** [comment]
Forgot to mentioned it should be Javascript. Maybe stylellint can actually do it, need to check.

**Comment by the-j0k3r** [comment]
I haven't found anything else offline wise.
