### ISSUE TITLE
Automated regeneration + release

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#944]
I'm thinking of setting up a daily cron job that does:

- Run generator
- If there are changes, commit and push a new release

This would mean `master` must be ready for release anytime, so can not contain experimental stuff, but I think we already handle it that way.

**Comment by the-j0k3r** [comment]
go for it. around midnight would be good...

**Comment by silverwind** [comment]
Cron job set up for 10 AM CEST, this should translate to after midnight on the US timezones.

**Comment by Mottie** [comment]
Would you mind sharing how you set up the cron job? It's mostly for learning purposes... 😸

**Comment by silverwind** [comment]
crontab -e
```
0 10 * * * /path/to/autocommit.zsh &> /path/to/autocommit.log
```

``` bash
#!/bin/zsh -l

set -x
cd $(dirname $0:A)
git fetch --tags origin master
git reset --hard origin/master
git pull origin master
rm -rf node_modules
npm i
npx grunt generate
if [[ $(git status --porcelain) ]]; then
  npx grunt lint || exit 1
  git commit -am "daily automated regeneration"
  npx grunt patch
  git push -u --follow-tags origin master
else
  echo "no changes to commit"
fi
```

I recall it being important that the shell (can be bash too) is called with `-l` as a login shell so the shell startup files are sourced (which some tools might rely on).

**Comment by the-j0k3r** [comment]
Are those auto commits signed @silverwind?

**Comment by silverwind** [comment]
Yes, but that is one reason why I want to move it to a bot account, so that I can give the bot its own GPG key.

**Comment by silverwind** [comment]
First autocommit and release happened:

https://github.com/StylishThemes/GitHub-Dark/commit/fb0789bfb0f4b7c6ee9ace12a0d58065d922cb2c
https://github.com/StylishThemes/GitHub-Dark/commit/4e9daf65df57d7a3b62e9c4c4ae04dba9bcb8117

I actually changed it to run more frequent, every 6 hours currently, might adjust later.
