### ISSUE TITLE
Support for "GitHub Hovercard" extension

### ISSUE THREAD

**Issue by darkred** [StylishThemes/GitHub-Dark#946]
* **Browser**: Chrome 74.0.3729.157/Firefox 66.0.5, Stylus 1.5.3, GitHub Dark 1.21.57
* **Operating System**:Windows 10
* **Link to page with the issue**: e.g. https://github.com/StylishThemes/GitHub-Dark/issues
* **Screenshot**: 
![2019-05-19_224031](https://user-images.githubusercontent.com/723651/57987223-24ea0180-7a87-11e9-9cf4-07029a36d984.jpg)

Using the [GitHub Hovercard](https://chrome.google.com/webstore/detail/github-hovercard/mmoahbbnojgkclgceahhakhnccimnplk?hl=en-US) v1.8.0 extension.
I've noticed that the hovercards that the extension creates are not styled.
Could you please consider supporting this extension ?

**Comment by silverwind** [comment]
Would like to supported it via loading their CSS, but it doesn't look like their extension defines any CSS files in their manifest (probably loading their styles via JS):

https://github.com/Justineo/github-hovercard/blob/master/extensions/chrome/manifest.json

So unfortunately it seems impossible to support it in an automated way.

**Comment by Mottie** [comment]
It's here: https://github.com/Justineo/github-hovercard/blob/master/src/hovercard.css

**Comment by xt0rted** [comment]
There's a built-in dark theme for this extension. It could really do without the background opacity though which makes it hard to see what's in it.

![image](https://user-images.githubusercontent.com/831974/58061598-d1d68400-7b44-11e9-96f6-a53b73230cfe.png)

**Comment by silverwind** [comment]
Fixed by adding a new `files` option to crx sources. Also did away with that ugly transparency on the tooltips. Extension needs to be set to dark theme to work properly.

**Comment by darkred** [comment]
Thanks a lot!
