### ISSUE TITLE
Mixed content error

### ISSUE THREAD

**Issue by donaldboulton** [StylishThemes/GitHub-Dark#947]
When using Chrome stylus I get a Mixed content error on http://...Roboto font from every website I visit, killing https: for some sites.
Sure would be nice to see github dark again but the costs of mixed content is not cool.

**Comment by the-j0k3r** [comment]
Hello @donaldboulton, thank you for reaching out to us with this issue report.

Im not sure I understand this report however, GHD doesnt use any roboto fonts.

Could you elaborate?

**Comment by silverwind** [comment]
Must be something else. We do not use web fonts at all in this style.

**Comment by donaldboulton** [comment]
Reinstalled everything and now its ok
Thanks

**Comment by the-j0k3r** [comment]
Thanks for letting us know. Glad its working again for you.
