### ISSUE TITLE
.pl-bu isnt included in most GHD's syntax themes.

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#948]
* **Browser**: FF 67
* **Operating System**: Win 10 pro 1803
* **Link to page with the issue**:

https://github.com/StylishThemes/Pocket-Dark/blob/4e68f41f1de77ca61426cdf5452216ec9be24172/pocket-dark.user.css#L16-L18

* **Screenshot**:
![Capture](https://user-images.githubusercontent.com/31389848/58366443-a4862f00-7ed2-11e9-867b-affb9c509623.PNG)

link to css styling this atm https://github.githubassets.com/assets/frameworks-a2fba223d5af91496cac70d4ec3624df.css

@mottie ;)

**Comment by Mottie** [comment]
Thanks! Should be fixed for all themes now.

**Comment by the-j0k3r** [comment]
Great, I was gonna get to it at some stage,
