### ISSUE TITLE
Demo page: several issues.

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#956]
So this seems to be different than the others:

Issues:

- [x] background is light color in javascript codemirror demo <s>(apparently caused by blocking 3rd party cookies WTH? cookies in the demo page??)</s> nope false alarm see https://github.com/StylishThemes/GitHub-Dark/issues/956#issuecomment-503413338
- [x] double scrollbars in javascript codemirror demo
- [x] scrollbars showing by default (should show only in popup?)
- [x] fork and star buttons dont show counts (they do in Atom HTML previewer)
- [x] unstyled dropdown select menus

* **Browser**: FF 67.0.2 64-bit
* **Operating System**:Win 10 pro 1803
* **Link to page with the issue**: https://stylishthemes.github.io/GitHub-Dark/
* **Screenshot**:

![Screenshot_2019-06-18 GitHub Dark Syntax Highlighting Themes](https://user-images.githubusercontent.com/31389848/59658513-24d34380-91a4-11e9-9069-c82462c98cf2.png)

**Comment by xt0rted** [comment]
The fork & star counts are working fine for me. Chrome on top Edge (chromium based) on the bottom:

![image](https://user-images.githubusercontent.com/831974/59737490-de292c00-922b-11e9-972e-d64a13a1782d.png)

**Comment by the-j0k3r** [comment]
Just updated to Firefox 67.0.3 (64-bit) with exact same results I reported.

**Comment by silverwind** [comment]
You can update the to shields.io badges:

https://img.shields.io/github/stars/StylishThemes/GitHub-Dark.svg?style=flat
https://img.shields.io/github/forks/StylishThemes/GitHub-Dark.svg?style=flat

Those shouldn't have that issue, and more importantly, use plurals 😉

**Comment by the-j0k3r** [comment]
Well I did https://github.com/StylishThemes/GitHub-Dark/commit/bc621873b15740c49ecdbbffe627346993166657 but that changed nothing =(

**Comment by silverwind** [comment]
Works for me, I just copied the header from README, I like those button styles there more than the old ones.

https://stylishthemes.github.io/GitHub-Dark/

**Comment by the-j0k3r** [comment]
in https://github.com/StylishThemes/GitHub-Dark/commit/bc621873b15740c49ecdbbffe627346993166657 its not the flat buttons, I tried the shield.io version of the same there was, then just replaced with your suggestion, but I see you used a sledgehammer.

1 issue down
4 to go

**Comment by Mottie** [comment]
I've just fixed the CodeMirror background & scrollbars.

**Comment by the-j0k3r** [comment]
I think theres just the codemirror gutter number atm and some minor things, Ill look at them later.
