### ISSUE TITLE
Issue header not displaying properly

### ISSUE THREAD

**Issue by ackvf** [StylishThemes/GitHub-Dark#963]
* **Browser**: Version 74.0.3729.169 (Official Build) (64-bit)
* **Operating System**: Windows 10 Enterprise, 10.0.17763 Build 17763
* **Link to page with the issue**: https://github.com/microsoft/vscode/issues/32836
* **Screenshot**:

Stylus disabled
![image](https://user-images.githubusercontent.com/2313018/61286652-944c4b00-a7c3-11e9-9145-03489c933d31.png)

Stylus enabled
![image](https://user-images.githubusercontent.com/2313018/61286770-cb226100-a7c3-11e9-8d7d-eb6a9099062e.png)

There are two issues:
- the white background
- extra `height: 72px !important`

![image](https://user-images.githubusercontent.com/2313018/61286892-1ccaeb80-a7c4-11e9-8921-444cc17c6501.png)

The sticky header is also white

![image](https://user-images.githubusercontent.com/2313018/61287835-09208480-a7c6-11e9-8e6c-48ec67cef59d.png)

---
As a quick fix, I added a custom section with this code
```
/* my own overrides */
.gh-header {
    background-color: transparent !important;
}
.gh-header .gh-header-sticky.js-sticky-offset-scroll {
    height: 1px !important;
}

.gh-header-shadow {
    background: #181818 !important;
}
```

**Comment by silverwind** [comment]
Your installed style is likely very out of date, try updating it.

**Comment by the-j0k3r** [comment]
@ackvf, Thank you for reaching out to us with this issue report.

Immediately visiting the page indicated (with Firefox), theres no visible issues like described that I can see.

![Screenshot_2019-07-16 Customizable tabs in text editor Multiple rows display, font size, grouping · Issue #32836 · microsof](https://user-images.githubusercontent.com/31389848/61287195-a2e73200-a7c4-11e9-9098-e6e176d295bc.png)

I cant see anything either with Chrome, and cause @silverwind replied in meanwhile with same suggestion, maybe try disable any other styles just in case they cause any other issues.

**Comment by ackvf** [comment]
@silverwind I did try to update it before posting and I forced the update over my custom overrides which brought back the issue.

![image](https://user-images.githubusercontent.com/2313018/61287517-518b7280-a7c5-11e9-9e53-6e6368dff8b8.png)

Am I doing something wrong?

**Comment by the-j0k3r** [comment]
>over my custom overrides

Maybe thats the issue, What custom overrides are these you mention.

Maybe try not to add any custom overrides, if you meant style settings then IDK, it works here just fine.
Have you some other style active that maybe causing the issues? If so disable that.

**Comment by ackvf** [comment]
- I don't have any other Stylus styles installed.
- After a fresh install of Stylus and Github Dark, I encounter the style bug explained above
- the custom override is mentioned above as a fix for aforementioned issues, disabling my overrides brings back the issue.

**Comment by the-j0k3r** [comment]
Personally speaking, I cant see the issues you reported in 3 browsers, Firefox 68 64bit Or Chrome 75.0.3770.100 and Vivaldi 2.6

Perhaps you may want to remove any browser profiles that stuck around from old insall or try in another machine to see.

**Comment by ackvf** [comment]
Allright, this is weird. Well actually not that much. My computer is just a month old, but I synchronized all my extensions and settings so the github dark came automatically. Trying to update it yielded an archived version v1.20.84, which is correct as the style itself points to it, so it thinks it's up to date.

```
/*! Github Dark v1.20.84 (2018-11-19) */
/*! Repository: https://github.com/StylishThemes/GitHub-Dark    */
/*! Userstyle:  http://userstyles.org/styles/37035              */
/*! License:    https://creativecommons.org/licenses/by-sa/4.0/ */
```

So I have just installed Chrome Canary to get rid of all profile data (just in case), installed Stylus (as the only extension) then I followed the **Repository** link above, where I clicked the first link
> :octocat: Dark GitHub style [https://raw.githubusercontent.com/Sty…](https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-dark.user.css)
which immediately offered me to **Install style** and then I got the **non-archived most recent version**.

Anyway, I immediately see a difference in background which I don't like, so I guess, I will have to stick to the old one... Or can I change the background picture easily?

![image](https://user-images.githubusercontent.com/2313018/61289671-26575200-a7ca-11e9-917d-5ad5afad0dad.png)


Closing as my style was an old archived one and the issue does not apply to the new one. Thanks for your fast responses anyway. And perhaps, advice me how to change the background.

**Comment by the-j0k3r** [comment]
The background can be customized in Stylus (this style settings)

![Capture](https://user-images.githubusercontent.com/31389848/61289877-b4cbd380-a7ca-11e9-8db8-6ff2c0a106dd.PNG)

**Comment by ackvf** [comment]
Allright, now I cannot interact with stylus, lol. I created an issue at google https://support.google.com/chrome/thread/9999253

/edit: I managed to get to stylus manager through settings://extensions

Thank you for all the help. And also, thank you for hinting me that there is also a dark style for Stylus :)

**Comment by the-j0k3r** [comment]
There is, the one in use in screenshot, its called [Stylus Deepdark](https://gitlab.com/RaitaroH/Stylus-DeepDark)
