### ISSUE TITLE
Firefox "Highlight All" search highlight colors swapped

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#964]
In Firefox 69, I see that the "other" search results for some reason get their background/foreground swapped with the style active:

![image](https://user-images.githubusercontent.com/115237/61286818-ea20f300-a7c3-11e9-8c4b-733f67e3f36f.png)

![image](https://user-images.githubusercontent.com/115237/61286872-0f156600-a7c4-11e9-8cc1-5210a6cfd230.png)

No sure what is triggering this issue. I think we should attempt to restore the default browser styles with white text on green/pink background.

**Comment by the-j0k3r** [comment]
Same in FF 68 stable channel

**Comment by the-j0k3r** [comment]
I dont think its the style itself doing this, it seems that FF has some kind of internal detection of what color the background is and swaps the colors to suit.

Just add this anywhere on style

```css
	p {
		background: #eee;
	}
```

As soon as p background is #eee the colors display as the first screenshot you posted.

![Screenshot_2019-07-16 Issue header not displaying properly · Issue #963 · StylishThemes GitHub-Dark](https://user-images.githubusercontent.com/31389848/61307745-2d448b80-a7ef-11e9-8d45-41e50fcf5338.png)

**Comment by silverwind** [comment]
There is this color swap mechanism in Firefox's code:

https://github.com/mozilla/gecko-dev/blob/8478c8b076a13af9ac5b29ff677c1f4fea2a7ed6/layout/generic/nsTextFrame.cpp#L3828-L3849

So apparently there is not enough contrast (which seems doubtful) between the grey background and the pink so it's swapping it to white.

Something about this mechanism must have recently changed as I don't remember these white backgrounds. Maybe I'll open a bugzilla on it later.

**Comment by the-j0k3r** [comment]
I cant say Ive ever paid enough attention to this, so cant say if its changed recently or if its always been like that, mozilla's Git blame results are also not helpful here.

Only way to be sure is to install some much older version of FF and see (I guess).

**Comment by xt0rted** [comment]
I just tested this out and I'm seeing both colors on this page depending on where the selected text is. Searching for `issue` gives a green background on the issues tab & in the comments, and a white background in the new issue button and pin & transfer issue links. It seems to be the same with and without a background image.

**Comment by silverwind** [comment]
Also seeing it in your comment. Apparently it's a close call and the slightly brighter code box already triggers it:

<img width="196" src="https://user-images.githubusercontent.com/115237/61349215-9c5bc780-a863-11e9-9a00-6ab312b1e214.png">

**Comment by the-j0k3r** [comment]
I see that only when I switch between tabs.

**Comment by silverwind** [comment]
I'll close this as CSS can not touch these highlights at all, so there's nothing we can do. Might still open a Firefox bug later.
