### ISSUE TITLE
Links and Icons have lost colors

### ISSUE THREAD

**Issue by simov** [StylishThemes/GitHub-Dark#965]
![colors](https://user-images.githubusercontent.com/1694112/61315727-0a72a100-a808-11e9-9dff-f7470cad9942.png)

* **Browser**: Version 75.0.3770.100 (Official Build) (64-bit)
* **Operating System**: Ubuntu

**Comment by silverwind** [comment]
Hmm, can't reproduce on Firefox. Icons are green. Issue links color on hover:

<img width="258" src="https://user-images.githubusercontent.com/115237/61322873-f8e0c780-a80e-11e9-99a8-13e97e0bfb9a.png">

**Comment by simov** [comment]
Is it work for you on Chrome?

**Comment by silverwind** [comment]
Yes. Maybe try reinstalling?

**Comment by silverwind** [comment]
Maybe another style is interfering? What makes the issue titles monospaced in that screenshot?

**Comment by simov** [comment]
I'm using my own [extension](https://github.com/simov/styler) for injecting the styles, but that shouldn't be a problem since I'm using this setup for who knows how many years now.

I checked my additional styles, but none of them interferes with Github Dark. So I'm starting to suspect that something changed in the way the icons are styled and that prevents them from being applied.

**Comment by simov** [comment]
Found it:

```css
svg:not([fill]) {
  fill: #fff;
}
```

This doesn't even need to override the css rules because it's applied on the SVG itself. Now I'm trying to figure out how to negate that.

**Comment by simov** [comment]
Just commented that line out in GitHub Dark, until I figure out how to negate that property.

**Comment by simov** [comment]
Wait so that's for `@-moz-document domain("help.github.com")` only. So it have to be something with the way I'm parsing these rules in my extension. I don't think I take into account the domain name.

**Comment by the-j0k3r** [comment]
@simov Can you try with Stylus to see if the issue is still present?

**Comment by simov** [comment]
@the-j0k3r I don't have that one installed.

**Comment by the-j0k3r** [comment]
How can we know then if the issue is with style or styler?

**Comment by simov** [comment]
Yep, let me explain. My own extension called Styler isn't published in Chrome Store, it's my own thing that I'm using locally, and there is a bug in it. I haven't used Stylus or any of that so far. The issue arises from the fact that I strip the `@-moz-document domain` and since `fill: #fff` was added for help.github.com now it gets injected into my styles for github.com

**Comment by the-j0k3r** [comment]
Your extension seems nice, except for the fact that it also doesnt seem to support UserCSS options configuration (like Stylus does), in a style like this customization is key, unless of course you build the style, editing the settings values on the build files and compile a new style, which makes sense since its a once and forget thing (for a local user that is).

Hope you solve it anyway, good luck. =)

**Comment by silverwind** [comment]
We've been including multiple `@-moz-document` since a while now to target some sub-sites of GitHub specifically. Previously it was just one big section.
