### ISSUE TITLE
user contrib graph too opaque color, add alpha.

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#970]
* **Browser**: FF 68.0.1
* **Operating System**: Win 10 pro
* **Link to page with the issue**: https://github.com/vednoc/dark-gitlab/graphs/contributors
* **Screenshot**: ![Capture](https://user-images.githubusercontent.com/31389848/61816645-16d0ac80-ae4d-11e9-8994-0ddb1cb70030.PNG)

```css
.contrib-person path {
	fill: #fb8532;
}
```

We can add this to generator, Im a bit busy with another project atm, hence report.

**Comment by silverwind** [comment]
Added some opacity similar to the style on the green area above. Don't think it justifies a generator rule.

**Comment by the-j0k3r** [comment]
Thanks =)
