### ISSUE TITLE
Can't add custom background URL

### ISSUE THREAD

**Issue by whyseman** [StylishThemes/GitHub-Dark#971]
* **Browser**: Google Chrome v75
* **Operating System**: Windows 10 Version 1903
* **Link to page with the issue**: /
* **Screenshot**: /

Hi, 

I can't add the custom URL for the backgroud. I tried to add this URL in the extension (under the "Custom Background" input filed) https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/images/backgrounds/bg-tile-uniform.png but it won't change.
Even tried to remove the `url()` function and leave just the link, didn't work.

**Comment by Mottie** [comment]
Hi @whyseman!

Please also make sure that the "Background" option is set to "Custom":

![](https://user-images.githubusercontent.com/136959/61980792-57e7ce80-afbd-11e9-8548-1bf407e58782.png)

**Comment by whyseman** [comment]
OMG, I'm so clumsy, it's ok now. Sorry!

**Comment by the-j0k3r** [comment]
Thanks for letting us know., it happens =)
