### ISSUE TITLE
Security advisories seem not styled correctly

### ISSUE THREAD

**Issue by saschagrunert** [StylishThemes/GitHub-Dark#972]
Hey :wave:, the security advisories seem to need some restyling, see the attached screenshot. :)

* **Browser**:  Chromium 75.0.3770.100
* **Operating System**: openSUSE Tumbleweed
* **Link to page with the issue**: https://github.com/rootless-containers/slirp4netns/security/advisories/GHSA-vp7q-v36g-7vq7
* **Screenshot**:
![screenshot](https://user-images.githubusercontent.com/695473/62194155-94c71300-b379-11e9-9ee8-1f85e004b2ed.png)

**Comment by AkihiroSuda** [comment]
@saschagrunert The advisory wasn't be intended to be public at this moment ... 😓

**Comment by xt0rted** [comment]
@AkihiroSuda should the comment history be deleted?

**Comment by Mottie** [comment]
I removed the screenshot and changed the url.

**Comment by xt0rted** [comment]
@Mottie you can still view it in the comment history though which is why I asked.
