### ISSUE TITLE
Feature Request: nuget.pkg.github.com subdomain support

### ISSUE THREAD

**Issue by xPixv** [StylishThemes/GitHub-Dark#973]
For example: https://nuget.pkg.github.com/StylishThemes/GitHub-Dark

**Comment by the-j0k3r** [comment]
I would say please make your request known in https://github.com/StylishThemes/GitHub-Dark/pull/938

**Comment by xt0rted** [comment]
I don't think you're actually supposed to browse the site from this subdomain. By default you're not even logging in to it. It's my understanding that this is meant to be used by package managers only. Is there anything available under `*.pkg.github.com` that isn't accessible from `github.com`?

**Comment by xPixv** [comment]
Hahaha, yep, I accidentally opened this subdomain, and I do not work on it in daily work. And I didn't find any difference between it and main site, it looks like a mirror. :/

If you consider it not necessary to be supported by GItHub Dark, it's fine, haha. :)

**Comment by the-j0k3r** [comment]
Yep seems like it https://nuget.pkg.github.com/ will display 
![Screenshot from 2019-08-04 20-26-13](https://user-images.githubusercontent.com/31389848/62427638-2c1fc380-b6f6-11e9-9793-47caeb670fdf.png)
