### ISSUE TITLE
Inconsistent archived repo banners

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#974]
This looks to have been a result of d722c79b4160c852b5ed55a372a91ba99e001c48.

* **Browser**: chrome 76
* **Operating System**: win10
* **Link to page with the issue**:
  - https://github.com/xt0rted/GitHub-Hide-Annotations
  - https://github.com/xt0rted/GitHub-Hide-Annotations/releases
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/62436234-0c47ca00-b70d-11e9-8988-fe28dd48d333.png)

**Comment by silverwind** [comment]
The selector is bad, will check out later.
