### ISSUE TITLE
Unstyled alerts on the developer site

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#978]
Not sure if this is something that needs fixing, but it looks kind of weird compared to the other alerts around the site. I'm using `Fira Code Retina` for the code font which is why that text is a little larger, but even with the default font it basically looks the same.

* **Browser**: chrome 76
* **Operating System**: win10
* **Link to page with the issue**: https://developer.github.com/actions/
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/62789598-47dcee00-ba97-11e9-9c86-9759c70f72a0.png)

![image](https://user-images.githubusercontent.com/831974/62789804-b621b080-ba97-11e9-8e39-94cb528a41c3.png)

**Comment by silverwind** [comment]
Yes, this `.deprecation-note` needs styling. It should be manually for now in the domain-specific section.

**Comment by xt0rted** [comment]
I didn't even realize this wasn't styled, I thought it was just the code blocks.

It looks like we're not styling `.alert.danger` on this domain either. I didn't see one, but you can update the class on the note here which also has code blocks in it. https://developer.github.com/v3/scim/#update-a-user-attribute

**Comment by the-j0k3r** [comment]
@xt0rted see https://github.com/StylishThemes/GitHub-Dark/commit/a99b3b6939a7f59a726242e37b4e36d4a82c6157

Regarding this issue in main post, Im not able to get the selector, even with breaking execution.

If someone knows the selector let me know.

**Comment by xt0rted** [comment]
Here's a copy of the alert html 😃 

```html
<div class="deprecation-banner deprecation-note">
 <p>
   <b>The documentation at <code>https://developer.github.com/actions</code> and support for the HCL syntax in GitHub Actions will be removed on September 30, 2019.</b>
   Documentation for the new limited public beta using the YAML syntax is available on <code>https://help.github.com</code>. See <a href="https://help.github.com/en/categories/automating-your-workflow-with-github-actions">"Automating your workflow with GitHub Actions"</a> for documentation using the YAML syntax.
 </p>
</div>
```

**Comment by the-j0k3r** [comment]
how does this strike you?

```css
	.deprecation-banner {
    background: #200;
    border-color: #911;
	}
	.deprecation-banner p {
		color: #f66;
	}
```

**Comment by xt0rted** [comment]
I'm ok letting this one go for now. The page in question no longer exists (it's just the alert with a link going to the help page that it redirects to) and I haven't seen this alert on any other pages.

**Comment by the-j0k3r** [comment]
It exists, this flickers in for a length of time determined how long the page takes to redirect.
