### ISSUE TITLE
GitHub Actions v2 preview

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#979]
I just got access to the new version of actions so I'm going to use this issue to keep track of the new UI changes as I see them. I'll make sure to turn the background image on for these since it looks different without it.

**New getting started screen**

![image](https://user-images.githubusercontent.com/831974/62828434-55d46100-bbb4-11e9-99de-d3e3910b12ae.png)

![image](https://user-images.githubusercontent.com/831974/62828452-97fda280-bbb4-11e9-9772-6c26d2db5581.png)

![image](https://user-images.githubusercontent.com/831974/62828446-80beb500-bbb4-11e9-8f2b-52bfaf3f70f0.png)

![image](https://user-images.githubusercontent.com/831974/62828448-8caa7700-bbb4-11e9-9c07-0ba165d8a759.png)

**Comment by xt0rted** [comment]
**Setting up a new workflow**

The visual editor has been removed, but will be coming back in a future version according to a comment on twitter. No idea how long that'll be though.

Neither of these sections have a vertical scrollbar by default, the overlay scrollbar style is added this in.

![image](https://user-images.githubusercontent.com/831974/62828565-055f0280-bbb8-11e9-839d-c241807694ac.png)

![image](https://user-images.githubusercontent.com/831974/62828560-f6785000-bbb7-11e9-967a-542101cd5365.png)

**Comment by xt0rted** [comment]
**New workflow**

First workflow created and pending execution.

![image](https://user-images.githubusercontent.com/831974/62828991-9ab2c480-bbc1-11e9-9070-9f2cd212e2e3.png)

![image](https://user-images.githubusercontent.com/831974/62828992-a7cfb380-bbc1-11e9-8da5-eb80c24b58a0.png)

Workflow execution results.

![image](https://user-images.githubusercontent.com/831974/62829009-e49baa80-bbc1-11e9-83c9-c32b4ce8cdb8.png)

![image](https://user-images.githubusercontent.com/831974/62829015-fed58880-bbc1-11e9-8141-820600ae2196.png)

The expanded job results sections don't have vertical scrollbars by default, the overlay scrollbar style is adding these.

![image](https://user-images.githubusercontent.com/831974/62829023-1d3b8400-bbc2-11e9-9ab3-bb7550a31680.png)

![image](https://user-images.githubusercontent.com/831974/62829025-2e849080-bbc2-11e9-9e39-aedc2e59e21f.png)

**Comment by the-j0k3r** [comment]
Those headers `Set up job` and `Dump GitHub content` sure can use a color tweak.

**Comment by silverwind** [comment]
Those pages look kind of bad with the border but with no background. We should either remove the borders or add a opaque background.

**Comment by the-j0k3r** [comment]
I vote opaque

**Comment by xt0rted** [comment]
This is handled pretty well by the generator and some manual styling. I don't think there's anything more to be done here.
