### ISSUE TITLE
"Sign up for the GitHub Package Registry (Beta)" is not perfectly placed

### ISSUE THREAD

**Issue by yousef157** [StylishThemes/GitHub-Dark#981]
* **Browser**: Google Chrome
* **Operating System**: Windows 10 Pro
* **Link to page with the issue**: Any releases page. Example: https://github.com/StylishThemes/GitHub-Dark/releases
* **Screenshot**:
![image](https://user-images.githubusercontent.com/48018938/62959494-fa031580-be09-11e9-9bca-c0cc0e08cf8c.png)

I think this is a new button.

**Comment by Mottie** [comment]
Hi @yousef157!

Is the "Select tag" dropdown added by a third party app? I'm not seeing it.

**Comment by Mottie** [comment]
Ahh never mind, it's being added by Refined GitHub. Please report the issue in that repo.

**Comment by yousef157** [comment]
Alright, sorry!

**Comment by yousef157** [comment]
Very close, I almost posted it but there was already an issue with it. https://github.com/sindresorhus/refined-github/issues/2325
