### ISSUE TITLE
Transparent images in issue texts makes them unreadable

### ISSUE THREAD

**Issue by HolgerJeromin** [StylishThemes/GitHub-Dark#983]
* **Browser**: 
Vivaldi
* **Operating System**: 
Windows 7
* **Link to page with the issue**: 
https://github.com/gravitystorm/openstreetmap-carto/pull/3829
and
https://github.com/gravitystorm/openstreetmap-carto/issues/120#issuecomment-143260696

This repo issues often have transparent images.
* **Screenshot**:
![image](https://user-images.githubusercontent.com/2410353/63179575-b9470e80-c04c-11e9-9200-970c037a7536.png)
and
![image](https://user-images.githubusercontent.com/2410353/63179927-79345b80-c04d-11e9-85be-b673038b3d1e.png)

ref #463

**Comment by Mottie** [comment]
Hi @HolgerJeromin!

Hmm, I thought we had the background change to white on hover:

```css
.markdown-body img:hover {
    background-color: #fff !important;
}
```

But I don't see it any more.

**Comment by xt0rted** [comment]
@Mottie the white background on hover was only when viewing an image in a repo such as this https://github.com/StylishThemes/logos/blob/master/github.dark/githubdark.svg

**Comment by silverwind** [comment]
Seems like that background effect could be done to all images inside `.markdown-body`

**Comment by the-j0k3r** [comment]
> @Mottie the white background on hover was only when viewing an image in a repo such as this https://github.com/StylishThemes/logos/blob/master/github.dark/githubdark.svg

If I remember this right, the only effect was for jupyter notebooks images https://github.com/StylishThemes/GitHub-Dark/issues/846 and a page https://github.com/sujitpal/statlearning-notebooks/blob/master/src/chapter2.ipynb

None of the issue reported here are encompassed in that.

**Comment by HolgerJeromin** [comment]
> also its interesting that the images in gravitystorm/openstreetmap-carto#120 (comment) are dark and many other similar images posted in that topic are not.

The others are PNG without transparency but white background in the image itself.

> Why are we exactly changing this? I reverted this to white as per default and cant see any ill effects

Fine with me.

**Comment by the-j0k3r** [comment]
> Why are we exactly changing this? I reverted this to white as per default and cant see any ill effects

Thas a question more for @mottie @silverwind @xt0rted cause I cant remember why this was changed, there has to be a reason.

**Comment by the-j0k3r** [comment]
AH I see it, all emoji and other images rendered to png are affected by this, I dont even think the hover solution is nice cause it looks nasty when hovering things around.

I think we should make this optional with a toggle in style settings to restore the white bg if a user prefers it.

**Comment by the-j0k3r** [comment]
OK this is more or less handled by https://github.com/StylishThemes/Feature-Override-Styles/commit/06fbdd9e2a4e326628330c231951436c989beaf9

See https://github.com/StylishThemes/Feature-Override-Styles#github-dark and [Install the GitHub Dark IMG Background Color usercss](https://raw.githubusercontent.com/StylishThemes/Feature-Override-Styles/master/github-dark-img-bg-clr.user.css)
