### ISSUE TITLE
Code blocks in alerts have dark background

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#984]
* **Browser**: chrome 76
* **Operating System**: win10
* **Link to page with the issue**: Go to Settings > Features > Set up sponsor button on any repo
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/63194973-5a2ecd00-c03f-11e9-8f23-42b3cba7e580.png)

The background color is subtle here, but it's set to `#222222` while the default style doesn't have a background color. We might be able to use `.js-template-suggestion .flash p code` to remove the background, or we could go all in and style these like we do elsewhere. Anyone have a preference for this?

**Comment by xt0rted** [comment]
This is similar to #978 but it looks like `.flash` is used on github.com, `.alert` is used on developer.github.com, and `.bg-blue-light` is used on help.github.com. If only they had some type of component library with standard class names they could use on all threww of these sites 🙄

**Comment by the-j0k3r** [comment]
I fixed a bunch of these a while back along with other style issues on help pages, but seems there are still many like this now being overwritten again.

**Comment by the-j0k3r** [comment]
I see this at this time

![Capture](https://user-images.githubusercontent.com/31389848/63920372-fe9e0f80-ca40-11e9-873b-065acb3b49ed.PNG)
