### ISSUE TITLE
Setup GitHub Actions

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#986]
We just got access to actions on this org so I'm going to migrate my original workflow to the new yaml setup. These are the workflows I was going to configure, is there anything else we'd like to setup?

- [ ] CI build like Travis with ESLint & StyleLint annotations
- [ ] Scheduled workflow to regenerate & push changes back

I'm working on migrating my actions over to v2 and adjusting how they work so they're a bit more configurable. I can set this up later this week.

I have a new `/command` action that can trigger a workflow from comments. This could be useful for doing releases so if you comment `/release patch` on the most recent commit it could kick off an automated release for you.

**Comment by silverwind** [comment]
Should be a good start. For the regenerate, check out https://github.com/StylishThemes/GitHub-Dark/issues/944#issuecomment-491686539.

**Comment by silverwind** [comment]
Could commit that regenerate bash script to the repo, if you like.

**Comment by the-j0k3r** [comment]
What do you also think about to also set up greetings.yml?

**Comment by xt0rted** [comment]
@the-j0k3r what would that do?

**Comment by the-j0k3r** [comment]
According to the explanation it greets first time contributors to the repo.

![Capture](https://user-images.githubusercontent.com/31389848/63571554-cbf7a100-c580-11e9-90fb-d4c814d447ce.PNG)

**Comment by xt0rted** [comment]
Sounds good to me. Any ideas for what the messages should say? It has one for first issue and one for first pr.

**Comment by the-j0k3r** [comment]
Something along these lines: (or whatever is most appropriate).

```
        issue-message: 'Welcome and thank you for bringing this issue to our attention.'
        pr-message: 'Welcome and thank you for sharing this contribution with us.'
```

Also we could probably automatically label things but Im unsure if the label action works for issues as well as pr or if it works with our repo since most contributions are likely to be to one file only.

**Comment by the-j0k3r** [comment]
@xt0rted how do you get actions in other org repos? Is this by request or?

**Comment by silverwind** [comment]
I think you need to opt-in to the beta, at least that's the way for personal accounts, not sure for orgs.

**Comment by xt0rted** [comment]
@the-j0k3r you need to sign up for the beta at https://github.com/features/actions. I think only org admins can request access though, when I signed up `StylishThemes` wasn't on the list but the other orgs I'm in were. I think @Mottie had to sign us up for it.

Both Actions and [GPR](https://github.com/features/package-registry) will be opened up to everyone in mid November so you'll have access soon enough even if you don't get in the beta.

**Comment by xt0rted** [comment]
I pushed up e9f476087db745fab0d85add734acf48d2a90b08 which does basic building just like we're doing on Travis. I didn't turn off Travis, figured let this go for a bit and see how it works.

The next step is to setup the linting actions to create annotations, but I'm still in the process of upgrading them (they just released an update to the build runner to help with this).

I don't have enough repo access to do it, but could we setup Dependabot on the workflow file? That will ensure we're using the latest versions of the actions and can be setup to auto merge the PRs if we want. Right now I'm using `v1` for the two actions which pulls the highest v1 release, but using Dependabot will pin them and keep them up to date automatically.

**Comment by the-j0k3r** [comment]
Ping @xt0rted any advances on https://github.com/StylishThemes/GitHub-Dark/issues/986#issuecomment-524191508?

**Comment by the-j0k3r** [comment]
ping again.
