### ISSUE TITLE
unstyled timeline elements in issues

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#987]
* **Browser**: FF 68.0.2
* **Operating System**:  Win 10 pro 1803
* **Link to page with the issue**: https://github.com/platformio/platformio-atom-ide-terminal/issues/766
* **Screenshot**:

![Capture](https://user-images.githubusercontent.com/31389848/63403462-9ebfbd00-c3df-11e9-9372-72a6e328512f.PNG)

**Comment by silverwind** [comment]
This was fixed yesterday, please update the style.

**Comment by the-j0k3r** [comment]
Hi, yep my style should have updated but didnt, manual did it., closing both.
