### ISSUE TITLE
Unstyled timeline break on issues and PRs

### ISSUE THREAD

**Issue by AfroThundr3007730** [StylishThemes/GitHub-Dark#991]
A `div.TimelineItem-break` will occur whenever there is activity after a merge/close event.

The offending element:

![image](https://user-images.githubusercontent.com/7613032/64203039-2b5b8800-ce82-11e9-8182-5d6544d3a346.png)

Examples [here](https://github.com/StylishThemes/Pocket-Dark/pull/1) and [here](https://github.com/akissa/clamavmirror/issues/2).

**Comment by the-j0k3r** [comment]
Hey @AfroThundr3007730 

Just for ref: the default rule is.

```
.TimelineItem-break {
	background-color: #fff;
	border: 0;
	border-top: 4px solid #e1e4e8;
	height: 24px;
	margin: 0 0 -16px;
	position: relative;
	z-index: 1;
}
```

Both values are already in generator
bg
https://github.com/StylishThemes/GitHub-Dark/blob/5817e33de0752f81be91c68e05161e167f541ef6/tools/generate.js#L20

border
https://github.com/StylishThemes/GitHub-Dark/blob/5817e33de0752f81be91c68e05161e167f541ef6/tools/generate.js#L60

>Note: The previous value was double hyphened (`.TimelineItem--break`)hence issue showed up.

Regeneration will fix this up.

**Comment by the-j0k3r** [comment]
Actually not that simple cause the bg is opaque and needs to be transparent else this happens.

So manual partial fix coming up.
