### ISSUE TITLE
unstyled elements in https://github.com/features/actions

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#992]
* **Browser**:  FF 69.0
* **Operating System**: Win 10 pro 
* **Link to page with the issue**: https://github.com/features/actions
* **Screenshot**:
![Screenshot_2019-09-04 Features • GitHub Actions](https://user-images.githubusercontent.com/31389848/64244858-14607880-cf0a-11e9-9995-d222fe6b1298.png)

**Comment by Mottie** [comment]
Related to #977, Can we close it?
