### ISSUE TITLE
Text in issues is now dark on dark background

### ISSUE THREAD

**Issue by ssa3512** [StylishThemes/GitHub-Dark#993]
Issues are practically unreadable now

* **Browser**: Chromium: 76.0.3809.132
* **Operating System**: Windows 10 1903
* **Link to page with the issue**:  Click on any issue from this page: https://github.com/StylishThemes/GitHub-Dark/issues
* **Screenshot**:
## Example 1
![image](https://user-images.githubusercontent.com/1991399/64450043-452de280-d0af-11e9-9206-1adb8411383b.png)

## Example 2
![image](https://user-images.githubusercontent.com/1991399/64449944-fd0ec000-d0ae-11e9-89fd-7972e1751913.png)

**Comment by OvermindDL1** [comment]
Just coming in to report this myself, his an inspector view:
![image](https://user-images.githubusercontent.com/401605/64450220-e3fe1300-d09e-11e9-84d9-567834aaeb76.png)

**Comment by xt0rted** [comment]
I'm looking into this now

**Comment by xt0rted** [comment]
Looks like @silverwind just fixed this in e67cb73b4500993b8b4ae9a9a9ef6f7ae0f9ba58

Try updating to v1.22.85
