### ISSUE TITLE
Too dark text on Issues page

### ISSUE THREAD

**Issue by grasmanek94** [StylishThemes/GitHub-Dark#997]
* **Browser**: Google Chrome | 76.0.3809.132 (Official Build) (64-bit) (cohort: Stable)
* **Operating System**: Microsoft Windows 10 Pro Version 1903 (OS Build 18362.329)

* **Link to page with the issue**:

- https://github.com/StylishThemes/GitHub-Dark/issues/989
- https://github.com/StylishThemes/GitHub-Dark/issues/new?assignees=&labels=bug+%3Abug%3A&template=bug_report.md&title=

* **Screenshot**: 
-  https://i.imgur.com/bj9nzga.png
-  https://i.imgur.com/YLoRid8.png

* **Version**: `@version     1.22.84`

Is this an issue with this stylesheet or my browser somehow? I tried reverting my browser theme back default to, but that did not fix the too dark text.

**Comment by the-j0k3r** [comment]
@grasmanek94 Please upgrade your style version to 1.22.85.

This was reported and fixed in #993
