### ISSUE TITLE
The .css outcome of custom theme has several lines with invalid css syntax

### ISSUE THREAD

**Issue by danhnguyen30041975** [StylishThemes/GitHub-Dark#998]
* **Browser**: N/A
* **Operating System**: macOS
* **Link to page with the issue**:  N/A
* **Screenshot**: N/A

I create a custom theme using default `build.json` from the repo by below code snippet

```bash
$ node -v
v10.8.0
$ git clone git@github.com:StylishThemes/GitHub-Dark.git ghd
$ cd ghd
$ git checkout 93168d98 # it's v1.22.88
$ npm i
$ node ./node_modules/.bin/grunt
```

Then I have new file `github-dark-twilight-cf6a4c.build.css` whose content is at https://gist.github.com/danhnguyen30041975/11f85960f47b84c12bab1fc87eb9efa6. There are several problems on the generated css file which causes compiling error when the file is used as input for css processors [less](http://lesscss.org/) or [sass](https://sass-lang.com/)

1. The character `}` at [line 8518](https://gist.github.com/danhnguyen30041975/11f85960f47b84c12bab1fc87eb9efa6#file-github-dark-twilight-cf6a4c-build-css-L8518) is redundant. There should no `}` at that line
1. The css for `--bg-custom` at [line 5](https://gist.github.com/danhnguyen30041975/11f85960f47b84c12bab1fc87eb9efa6#file-github-dark-twilight-cf6a4c-build-css-L5) has invalid syntax, it should have a default value like `--bg-custom: /*[[bg-custom]]*/ #fff;`
1. At [line 8501](https://gist.github.com/danhnguyen30041975/11f85960f47b84c12bab1fc87eb9efa6#file-github-dark-twilight-cf6a4c-build-css-L8501), the `--ghd-code-color:` miss final `;`. It should be like `--ghd-code-color:#ccc;} `.

Could you help fix these problems ?

**Comment by the-j0k3r** [comment]
@danhnguyen30041975 you may want to try with node 12

https://github.com/StylishThemes/GitHub-Dark/blob/93168d98f1c3810881cfa84c9b84c1153c37ac0e/package.json#L9

>Then I have new file github-dark-twilight-cf6a4c.build.css whose content is at https://gist.github.com/danhnguyen30041975/11f85960f47b84c12bab1fc87eb9efa6. There are several problems on the generated css file which causes compiling error when the file is used as input for css processors less or sass

Im not sure where you get this file from, the only files you should count on for after generation for usage are github-dark.css and github-dark.user.css

> node ./node_modules/.bin/grunt

Please see our valid scripts at https://github.com/StylishThemes/GitHub-Dark#development

I may have missed something as Im a bit confused with that output file you say you end up with, maybe someone else has a better insight.

**Comment by the-j0k3r** [comment]
I notice that by running grunt as advertised in build scripts you end up with a file that has no -moz rules, that could explain the extra closing brackets and other errors.

I never really used this so @silverwind or @Mottie can explain why this file is broken.

**Comment by danhnguyen30041975** [comment]
Thanks @the-j0k3r 

> you may want to try with node 12

I tried and the problem is still there

> I notice that by running grunt as advertised in build scripts you 

It was documented at Wiki (https://github.com/StylishThemes/GitHub-Dark/wiki/Build), and the [grunt code](https://github.com/StylishThemes/GitHub-Dark/blob/master/Gruntfile.js#L333) also works as that way

Thanks for replying, again

D

**Comment by the-j0k3r** [comment]
@silverwind please have a look, this looks broken to me and no idea how to fix.

**Comment by silverwind** [comment]
I think at this point we're better off removing support for `build.json`. There's no need for it with UserCSS variables and it's more of a relic of the past right now.

**Comment by the-j0k3r** [comment]
Yes, lets.

**Comment by danhnguyen30041975** [comment]
Thanks @the-j0k3r for following-up

Hi @silverwind 

> I think at this point we're better off removing support for build.json.

Removing `build.json` means there is no customization for existing themes in github-dark. Is it correct ? Is there any alternative support like `build.json` in new github-dark ?

**Comment by the-j0k3r** [comment]
I think you can still customize the style just by editing the usercss template in tools and the github-dark.css and build a new theme based on that, The new github dark, lets not jump that far ahead of the horses, its not been worked on for a long time and shouldn't be used by anyone at this time.

Perhaps if you tell us what youre trying to achieve, we can make some more pertinent suggestions on how to achieve it?

**Comment by danhnguyen30041975** [comment]
Hi @the-j0k3r, 

I want to have some "themes" (different colors) in github pages on my browser. The approach I follow is: I use custom build from github-dark, with little customization (with less), and paste the final css output into [Stylish](https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en).

It've been useful approach till now when I have full customization on the dark theme.

It's great if we have alternative customization like `build.json` having valid css

**Comment by the-j0k3r** [comment]
Just fork and customize till your hearts content in a commit or two, then to keep it up to date rebase your changes ontop of ours so yours are always at the top.

**Comment by the-j0k3r** [comment]
@danhnguyen30041975 you may want to consider Stylus https://add0n.com/stylus.html instead of stylish, Stylish doest care about your privacy.

**Comment by the-j0k3r** [comment]
this has been removed in https://github.com/StylishThemes/GitHub-Dark/commit/878658480c45acbdd42f43bcd6c0674fb2ab09f1
