### ISSUE TITLE
No longer plays nice with Refined GitHub's Pull Request collapse feature

### ISSUE THREAD

**Issue by AdrianTP** [StylishThemes/GitHub-Dark#999]
# The Minimum Required Information

* **Browser**: Google Chrome Version 76.0.3809.132 (Official Build) (64-bit)
* **Operating System**: macOS Mojave Version 10.14.5 (18F132)
* **Link to page with the issue**: https://github.com/jquery/jquery/pull/4379/files (any pull request with multiple files and collapsed lines within the diff view)
* **Screenshot**: https://youtu.be/UqMH1TGsER0

# Prerequisites

Have the following installed in Chrome:

- [ ] Refined GitHub
- [ ] Tampermonkey
- [ ] GitHub-Dark

# Description

GitHub-Dark used to play nice with Refined GitHub until the recent update (when the file expansion carets moved from the right side to the left). Now there is a strange interaction occurring. I have noticed two glitches occurring here, in particular...

# Steps to Reproduce

## Scenario A

**What Happens**: The expand/collapse caret behaves oddly if you load a page and the previous pull request file collapse/expand state was expanded, or if the file collapses for any reason other than an intentional user interaction.

With a file expanded, perform the following steps:

1. Refresh the page
(notice that the diff starts expanded, then collapses)
2. Click on a previously-expanded file's expansion caret
(notice that the diff does not expand and the dropdowns above the file list turn blue)
3. Click on that same file's expansion caret a second time
(notice that the diff expands and the dropdowns turn grey again)

## Scenario B

**What happens**: The expand/collapse gutter buttons within each file trigger the overall file collapse, making it nigh impossible to review a file.

With a file expanded, perform the following steps:

1. Click on a gutter expansion button
(notice that the diff lines expand, then the whole file immediately collapses and needs to be double-clicked to expand again)

# Summary

I know that interoperability with other extensions and scripts is not your job, nor is it Refined GitHub's (@sindresorhus). I also know it is nobody's fault -- GitHub had a UI update and now anything designed to work with that UI needs to be updated. I also know it is probably a happy accident that Refined GitHub and GitHub-Dark even worked together in the first place. That said it would be amazing if they could work together again. Toward that end I will do my best to assist in debugging the issue, if anyone is willing to investigate.

I appreciate everything you do. Your userstyle and script makes my eyes hurt a lot less after a whole day of code reviews.

**Comment by Mottie** [comment]
Hi @AdrianTP!

I wasn't able to duplicate what's being described (or shown in the video). Is there possibly another userscript causing interference? Or maybe I don't have the same options set for Refined GitHub?

> it is probably a happy accident that Refined GitHub and GitHub-Dark even worked together in the first place

Nope, we support it on purpose 😉

> Your userstyle and script makes my eyes hurt a lot less after a whole day of code reviews.

Making your eyes ❤️ you is our goal!

**Comment by silverwind** [comment]
I wouldn't say `refined-github` is fully supported. We do process their styles but none of the maintainers is actually using that extension, so issues are bound to show up.

**Comment by AdrianTP** [comment]
@Mottie - Very good point.

I have three GitHub userscripts installed:
1. [GitHub Sort Content](https://github.com/Mottie/GitHub-userscripts/blob/master/github-sort-content.user.js)
2. [Wide GitHub](https://github.com/xthexder/wide-github)
3. [my own fork of GitHub Dark Script](https://github.com/AdrianTP/GitHub-Dark-Script/tree/issue-989) 

When I enable only GitHub Dark Script, Scenario A still occurs, but Scenario B does not.

When I enable GitHub Dark Script _and_ Wide GitHub, Scenario A still occurs, but Scenario B does not.

When I enable GitHub Dark Script _and_ GitHub Sort Content, Scenario A and Scenario B both occur. So it seems it may be an interaction between my fork of GitHub Dark Script and GitHub Sort Content.

My fork of GitHub Dark Script was made to support my monkey-patch to https://github.com/StylishThemes/GitHub-Dark: https://github.com/StylishThemes/GitHub-Dark/issues/989. I have not submitted it as a PR because I could not figure out how to "properly" fix it. My fork is one commit behind StylishThemes/GitHub-Dark-Script master.

Comparison of my fork and branch of GitHub-Dark-Script against StylishThemes master: https://github.com/StylishThemes/GitHub-Dark-Script/compare/master...AdrianTP:issue-989

Comparison of my fork and branch of GitHub-Dark against StylishThemes master: https://github.com/StylishThemes/GitHub-Dark/compare/master...AdrianTP:issue-989

Neither Scenario A or Scenario B occur at all with GitHub Dark Script disabled in Tampermonkey, no matter which other userscripts are enabled.

**Comment by the-j0k3r** [comment]
@AdrianTP you're reporting issues against GitHub Dark that happen with GitHub Dark Script and your other scripts.

Can you test with Stylus and Github Dark usercss and the refined github extension just to make sure its nothing related to some conflict or bugs in script version of Github Dark.

**Comment by the-j0k3r** [comment]
@AdrianTP ping =)

**Comment by AdrianTP** [comment]
@the-j0k3r with Stylus, "GitHub-Dark Script", and GitHub-Dark "usercss" installed as per the instructions in the [`README.md`](https://github.com/StylishThemes/GitHub-Dark/blob/master/README.md), and with Refined GitHub installed and running, Scenario A still occurs with the latest code from GitHub-Dark. I loaded up a Pull Request, which displayed with the files expanded (but with collapsed sections) by default. Once I toggled the overall file collapse action for one file, refreshing the page leads to *all* files in the list displaying in fully-collapsed mode, and it requires two clicks to re-expand a file.

All that said...once I *deleted* "GitHub Dark Script" from Tampermonkey and *reinstalled* it, Scenario A stopped occurring. The version number in Tampermonkey for GHDS was 2.5.7, which is the latest, so I'm not sure why this made a difference -- perhaps some kind of caching issue?

Now, when I refresh the page after toggling the collapsed/expanded state of files in a Pull Request, if I previously only collapsed one file, then all will refresh as expanded; if I previously collapsed all the files, then all will refresh as collapsed; if I previously collapsed all files, and I expand just one file prior to refreshing, then they all refresh as expanded. The requirement to click twice to trigger an expansion after a refresh is now gone. I assume this is the expected behaviour?

**Comment by the-j0k3r** [comment]
> I assume this is the expected behaviour?

Wouldn't know, none here afaik uses Refined GitHub.

But in any case you dont need GitHub Dark Script, Stylus and GitHub Dark should be more efficient and less buggy that GHD script.

**Comment by the-j0k3r** [comment]
@AdrianTP ping =)

**Comment by the-j0k3r** [comment]
Whats the status of this issue?

**Comment by silverwind** [comment]
No feedback, let's close it.

**Comment by the-j0k3r** [comment]
And its sort of unrelated due to https://github.com/StylishThemes/GitHub-Dark/issues/999#issuecomment-534274017

Its not even related to this style.
